<?php
$TOC = array (
  0 => 
  array (
    0 => 'context.socket.php',
    1 => 'ソケットコンテキストオプション',
  ),
  1 => 
  array (
    0 => 'context.http.php',
    1 => 'HTTP コンテキストオプション',
  ),
  2 => 
  array (
    0 => 'context.ftp.php',
    1 => 'FTP コンテキストオプション',
  ),
  3 => 
  array (
    0 => 'context.ssl.php',
    1 => 'SSL コンテキストオプション',
  ),
  4 => 
  array (
    0 => 'context.curl.php',
    1 => 'CURL コンテキストオプション',
  ),
  5 => 
  array (
    0 => 'context.phar.php',
    1 => 'Phar コンテキストオプション',
  ),
  6 => 
  array (
    0 => 'context.params.php',
    1 => 'コンテキストパラメータ',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => '言語リファレンス',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP マニュアル',
  ),
);