<?php
$TOC = array (
  0 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'PHP の振る舞いの変更',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => '音声フォーマットの操作',
  ),
  2 => 
  array (
    0 => 'refs.remote.auth.php',
    1 => '認証サービス',
  ),
  3 => 
  array (
    0 => 'refs.utilspec.cmdline.php',
    1 => 'コマンドライン関連',
  ),
  4 => 
  array (
    0 => 'refs.compression.php',
    1 => '圧縮およびアーカイブ',
  ),
  5 => 
  array (
    0 => 'refs.creditcard.php',
    1 => 'クレジットカード処理',
  ),
  6 => 
  array (
    0 => 'refs.crypto.php',
    1 => '暗号',
  ),
  7 => 
  array (
    0 => 'refs.database.php',
    1 => 'データベース関連',
  ),
  8 => 
  array (
    0 => 'refs.calendar.php',
    1 => '日付および時刻関連',
  ),
  9 => 
  array (
    0 => 'refs.fileprocess.file.php',
    1 => 'ファイルシステム',
  ),
  10 => 
  array (
    0 => 'refs.international.php',
    1 => '自然言語および文字エンコーディング',
  ),
  11 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => '画像処理および作成',
  ),
  12 => 
  array (
    0 => 'refs.remote.mail.php',
    1 => 'メール関連',
  ),
  13 => 
  array (
    0 => 'refs.math.php',
    1 => '数学',
  ),
  14 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'テキスト以外の MIME 型',
  ),
  15 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'プロセス制御',
  ),
  16 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'その他の基本モジュール',
  ),
  17 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'その他のサービス',
  ),
  18 => 
  array (
    0 => 'refs.search.php',
    1 => '検索エンジン用の拡張モジュール',
  ),
  19 => 
  array (
    0 => 'refs.utilspec.server.php',
    1 => 'サーバー固有のモジュール',
  ),
  20 => 
  array (
    0 => 'refs.basic.session.php',
    1 => 'セッション関連',
  ),
  21 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'テキスト処理',
  ),
  22 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => '変数・データ型関連',
  ),
  23 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'ウェブサービス',
  ),
  24 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows 用のモジュール',
  ),
  25 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML 操作',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'index.php',
    1 => 'PHP マニュアル',
  ),
);