<?php
$TOC = array (
  0 => 
  array (
    0 => 'copyright.php',
    1 => '著作権',
  ),
  1 => 
  array (
    0 => 'manual.php',
    1 => 'PHP マニュアル',
  ),
  2 => 
  array (
    0 => 'getting-started.php',
    1 => 'はじめに',
  ),
  3 => 
  array (
    0 => 'install.php',
    1 => 'インストールと設定',
  ),
  4 => 
  array (
    0 => 'langref.php',
    1 => '言語リファレンス',
  ),
  5 => 
  array (
    0 => 'security.php',
    1 => 'セキュリティ',
  ),
  6 => 
  array (
    0 => 'features.php',
    1 => '機能',
  ),
  7 => 
  array (
    0 => 'funcref.php',
    1 => '関数リファレンス',
  ),
  8 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP のコア: ハッカーの手引き',
  ),
  9 => 
  array (
    0 => 'faq.php',
    1 => 'FAQ',
  ),
  10 => 
  array (
    0 => 'appendices.php',
    1 => '付録',
  ),
);
$PARENTS = array (
);