<?php
$TOC = array (
  0 => 
  array (
    0 => 'language.basic-syntax.php',
    1 => '基本的な構文',
  ),
  1 => 
  array (
    0 => 'language.types.php',
    1 => '型',
  ),
  2 => 
  array (
    0 => 'language.variables.php',
    1 => '変数',
  ),
  3 => 
  array (
    0 => 'language.constants.php',
    1 => '定数',
  ),
  4 => 
  array (
    0 => 'language.expressions.php',
    1 => '式',
  ),
  5 => 
  array (
    0 => 'language.operators.php',
    1 => '演算子',
  ),
  6 => 
  array (
    0 => 'language.control-structures.php',
    1 => '制御構造',
  ),
  7 => 
  array (
    0 => 'language.functions.php',
    1 => '関数',
  ),
  8 => 
  array (
    0 => 'language.oop5.php',
    1 => 'クラスとオブジェクト',
  ),
  9 => 
  array (
    0 => 'language.namespaces.php',
    1 => '名前空間',
  ),
  10 => 
  array (
    0 => 'language.exceptions.php',
    1 => '例外(exceptions)',
  ),
  11 => 
  array (
    0 => 'language.generators.php',
    1 => 'ジェネレータ',
  ),
  12 => 
  array (
    0 => 'language.references.php',
    1 => 'リファレンスの説明',
  ),
  13 => 
  array (
    0 => 'reserved.variables.php',
    1 => '定義済の変数',
  ),
  14 => 
  array (
    0 => 'reserved.exceptions.php',
    1 => '定義済みの例外',
  ),
  15 => 
  array (
    0 => 'reserved.interfaces.php',
    1 => '定義済みのインターフェイスとクラス',
  ),
  16 => 
  array (
    0 => 'context.php',
    1 => 'コンテキストオプションとパラメータ',
  ),
  17 => 
  array (
    0 => 'wrappers.php',
    1 => 'サポートするプロトコル/ラッパー',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'index.php',
    1 => 'PHP マニュアル',
  ),
);