<?php
	function example($text) {
        echo "<blockquote><table border=1 cellpadding=3 cellspacing=3><tr bgcolor=#d0d0d0><td>";
        highlight_string($text);
        echo "</td></tr></table></blockquote>";
    }
?>
<HTML>
<HEAD>
   <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
   <META NAME="GENERATOR" CONTENT="Mozilla/4.0b3 [en] (Win95; I) [Netscape]">
<STYLE ID="ietssxyz" TYPE="text/css"></STYLE>

<SCRIPT LANGUAGE="JavaScript1.2" SRC="style.js"></SCRIPT>
</HEAD>
<BODY link="teal" vlink="teal" alink="red">
<LINK REL=STYLESHEET TYPE="text/css" HREF="style.css">
