<?php
$TOC = array (
  0 => 
  array (
    0 => 'about.formats.php',
    1 => 'Formats',
  ),
  1 => 
  array (
    0 => 'about.notes.php',
    1 => 'About user notes',
  ),
  2 => 
  array (
    0 => 'about.prototypes.php',
    1 => 'How to read a function definition (prototype)',
  ),
  3 => 
  array (
    0 => 'about.phpversions.php',
    1 => 'PHP versions documented in this manual',
  ),
  4 => 
  array (
    0 => 'about.more.php',
    1 => 'How to find more information about PHP',
  ),
  5 => 
  array (
    0 => 'about.howtohelp.php',
    1 => 'How to help improve the documentation',
  ),
  6 => 
  array (
    0 => 'about.generate.php',
    1 => 'How we generate the formats',
  ),
  7 => 
  array (
    0 => 'about.translations.php',
    1 => 'Translations',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'appendices.php',
    1 => 'Appendices',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);