<?php
$TOC = array (
  0 => 
  array (
    0 => 'apache.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'apache.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'apache.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'apache.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.apache.php',
    1 => 'Apache',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.server.php',
    1 => 'Server Specific Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);