<?php
$TOC = array (
  0 => 
  array (
    0 => 'apd.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'apd.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'apd.installwin32.php',
    1 => 'Building on Win32',
  ),
  3 => 
  array (
    0 => 'apd.configuration.php',
    1 => 'Runtime Configuration',
  ),
  4 => 
  array (
    0 => 'apd.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.apd.php',
    1 => 'APD',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);