<?php
$TOC = array (
  0 => 
  array (
    0 => 'apd.examples.usage.php',
    1 => 'How to use PHP-APD in your scripts',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.apd.php',
    1 => 'APD',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);