<?php
$TOC = array (
  0 => 
  array (
    0 => 'history.php',
    1 => 'History of PHP and related projects',
  ),
  1 => 
  array (
    0 => 'migration53.php',
    1 => 'Migrating from PHP 5.2.x to PHP 5.3.x',
  ),
  2 => 
  array (
    0 => 'migration52.php',
    1 => 'Migrating from PHP 5.1.x to PHP 5.2.x',
  ),
  3 => 
  array (
    0 => 'migration51.php',
    1 => 'Migrating from PHP 5.0.x to PHP 5.1.x',
  ),
  4 => 
  array (
    0 => 'migration5.php',
    1 => 'Migrating from PHP 4 to PHP 5.0.x',
  ),
  5 => 
  array (
    0 => 'oop4.php',
    1 => 'Classes and Objects (PHP 4)',
  ),
  6 => 
  array (
    0 => 'debugger.php',
    1 => 'Debugging in PHP',
  ),
  7 => 
  array (
    0 => 'configure.php',
    1 => 'Configure options',
  ),
  8 => 
  array (
    0 => 'ini.php',
    1 => 'php.ini directives',
  ),
  9 => 
  array (
    0 => 'extensions.php',
    1 => 'Extension List/Categorization',
  ),
  10 => 
  array (
    0 => 'aliases.php',
    1 => 'List of Function Aliases',
  ),
  11 => 
  array (
    0 => 'reserved.php',
    1 => 'List of Reserved Words',
  ),
  12 => 
  array (
    0 => 'resource.php',
    1 => 'List of Resource Types',
  ),
  13 => 
  array (
    0 => 'filters.php',
    1 => 'List of Available Filters',
  ),
  14 => 
  array (
    0 => 'transports.php',
    1 => 'List of Supported Socket Transports',
  ),
  15 => 
  array (
    0 => 'types.comparisons.php',
    1 => 'PHP type comparison tables',
  ),
  16 => 
  array (
    0 => 'tokens.php',
    1 => 'List of Parser Tokens',
  ),
  17 => 
  array (
    0 => 'userlandnaming.php',
    1 => 'Userland Naming Guide',
  ),
  18 => 
  array (
    0 => 'about.php',
    1 => 'About the manual',
  ),
  19 => 
  array (
    0 => 'cc.license.php',
    1 => 'Creative Commons Attribution 3.0',
  ),
  20 => 
  array (
    0 => 'indexes.php',
    1 => 'Function Index',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);