<?php
$TOC = array (
  0 => 
  array (
    0 => 'bc.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'bc.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'bc.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'bc.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.bc.php',
    1 => 'BC Math',
  ),
  1 => 
  array (
    0 => 'refs.math.php',
    1 => 'Mathematical Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);