<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.classobj.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'classobj.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'classobj.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'classobj.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.classobj.php',
    1 => 'Classes/Object Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);