<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.kadm5.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'kadm5.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'kadm5.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'kadm5.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.kadm5.php',
    1 => 'KADM5 Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.auth.php',
    1 => 'Authentication Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);