<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.mysqlnd.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'mysqlnd.overview.php',
    1 => 'Overview',
  ),
  2 => 
  array (
    0 => 'mysqlnd.install.php',
    1 => 'Installation',
  ),
  3 => 
  array (
    0 => 'mysqlnd.config.php',
    1 => 'Runtime Configuration',
  ),
  4 => 
  array (
    0 => 'mysqlnd.persist.php',
    1 => 'Persistent Connections',
  ),
  5 => 
  array (
    0 => 'mysqlnd.stats.php',
    1 => 'Statistics',
  ),
  6 => 
  array (
    0 => 'mysqlnd.notes.php',
    1 => 'Notes',
  ),
  7 => 
  array (
    0 => 'mysqlnd.plugin.php',
    1 => 'MySQL Native Driver Plugin API',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  1 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);