<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.rar.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'rar.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'rar.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'rar.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.rar.php',
    1 => 'Rar Functions',
  ),
  5 => 
  array (
    0 => 'class.rararchive.php',
    1 => 'RarArchive',
  ),
  6 => 
  array (
    0 => 'class.rarentry.php',
    1 => 'RarEntry',
  ),
  7 => 
  array (
    0 => 'class.rarexception.php',
    1 => 'RarException',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);