<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.sca.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'sca.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'sca.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'sca.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.sca.php',
    1 => 'SCA Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);