<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.calendar.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'calendar.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'calendar.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.calendar.php',
    1 => 'Calendar Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.calendar.php',
    1 => 'Date and Time Related Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);