<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.memcached.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'memcached.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'memcached.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'memcached.expiration.php',
    1 => 'Expiration Times',
  ),
  4 => 
  array (
    0 => 'memcached.callbacks.php',
    1 => 'Callbacks',
  ),
  5 => 
  array (
    0 => 'memcached.sessions.php',
    1 => 'Sessions support',
  ),
  6 => 
  array (
    0 => 'class.memcached.php',
    1 => 'Memcached',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);