<?php
$TOC = array (
  0 => 
  array (
    0 => 'dotnet.intro.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'dotnet.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'dotnet.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.dotnet.php',
    1 => '.NET Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);