<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.mcrypt.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'mcrypt.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'mcrypt.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'mcrypt.ciphers.php',
    1 => 'Mcrypt ciphers',
  ),
  4 => 
  array (
    0 => 'mcrypt.examples.php',
    1 => 'Examples',
  ),
  5 => 
  array (
    0 => 'ref.mcrypt.php',
    1 => 'Mcrypt Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.crypto.php',
    1 => 'Cryptography Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);