<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.tidy.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'tidy.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'tidy.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'tidy.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'class.tidy.php',
    1 => 'Tidy',
  ),
  5 => 
  array (
    0 => 'class.tidynode.php',
    1 => 'TidyNode',
  ),
  6 => 
  array (
    0 => 'ref.tidy.php',
    1 => 'Tidy Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);