<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.mhash.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'mhash.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'mhash.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'mhash.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.mhash.php',
    1 => 'Mhash Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.crypto.php',
    1 => 'Cryptography Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);