<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.chdb.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'chdb.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'chdb.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'chdb.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'class.chdb.php',
    1 => 'chdb',
  ),
  5 => 
  array (
    0 => 'ref.chdb.php',
    1 => 'chdb Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);