<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.iconv.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'iconv.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'iconv.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.iconv.php',
    1 => 'iconv Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);