<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.domxml.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'domxml.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'domxml.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.domxml.php',
    1 => 'DOM XML (PHP 4) Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);