<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.apc.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'apc.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'apc.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.apc.php',
    1 => 'APC Functions',
  ),
  4 => 
  array (
    0 => 'class.apciterator.php',
    1 => 'APCIterator',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);