<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.ssdeep.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'ssdeep.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'ssdeep.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.ssdeep.php',
    1 => 'ssdeep Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'Text Processing',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);