<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.mysqli.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'mysqli.overview.php',
    1 => 'Overview',
  ),
  2 => 
  array (
    0 => 'mysqli.setup.php',
    1 => 'Installing/Configuring',
  ),
  3 => 
  array (
    0 => 'mysqli.persistconns.php',
    1 => 'The mysqli Extension and Persistent Connections',
  ),
  4 => 
  array (
    0 => 'mysqli.constants.php',
    1 => 'Predefined Constants',
  ),
  5 => 
  array (
    0 => 'mysqli.summary.php',
    1 => 'The MySQLi Extension Function Summary',
  ),
  6 => 
  array (
    0 => 'class.mysqli.php',
    1 => 'MySQLi',
  ),
  7 => 
  array (
    0 => 'class.mysqli-stmt.php',
    1 => 'MySQLi_STMT',
  ),
  8 => 
  array (
    0 => 'class.mysqli-result.php',
    1 => 'MySQLi_Result',
  ),
  9 => 
  array (
    0 => 'class.mysqli-driver.php',
    1 => 'MySQLi_Driver',
  ),
  10 => 
  array (
    0 => 'class.mysqli-warning.php',
    1 => 'MySQLi_Warning',
  ),
  11 => 
  array (
    0 => 'ref.mysqli.php',
    1 => 'Aliases and deprecated Mysqli Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  1 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);