<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.gupnp.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'gupnp.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'gupnp.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'gupnp.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.gupnp.php',
    1 => 'Gupnp Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);