<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.win32ps.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'win32ps.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'win32ps.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'win32ps.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.win32ps.php',
    1 => 'win32ps Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);