<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.msession.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'msession.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'msession.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.msession.php',
    1 => 'Msession Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.session.php',
    1 => 'Session Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);