<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.inotify.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'inotify.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'inotify.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.inotify.php',
    1 => 'Inotify Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.fileprocess.file.php',
    1 => 'File System Related Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);