<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.java.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'java.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'java.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'java.servlet.php',
    1 => 'Java Servlet SAPI',
  ),
  4 => 
  array (
    0 => 'java.examples.php',
    1 => 'Examples',
  ),
  5 => 
  array (
    0 => 'ref.java.php',
    1 => 'Java Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);