<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.stream.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'stream.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'stream.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'stream.filters.php',
    1 => 'Stream Filters',
  ),
  4 => 
  array (
    0 => 'stream.contexts.php',
    1 => 'Stream Contexts',
  ),
  5 => 
  array (
    0 => 'stream.errors.php',
    1 => 'Stream Errors',
  ),
  6 => 
  array (
    0 => 'stream.examples.php',
    1 => 'Examples',
  ),
  7 => 
  array (
    0 => 'class.streamwrapper.php',
    1 => 'streamWrapper',
  ),
  8 => 
  array (
    0 => 'ref.stream.php',
    1 => 'Stream Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);