<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.tokenizer.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'tokenizer.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'tokenizer.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'tokenizer.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.tokenizer.php',
    1 => 'Tokenizer Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);