<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.dom.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'dom.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'dom.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'class.domattr.php',
    1 => 'DOMAttr',
  ),
  4 => 
  array (
    0 => 'class.domcharacterdata.php',
    1 => 'DOMCharacterData',
  ),
  5 => 
  array (
    0 => 'class.domcomment.php',
    1 => 'DOMComment',
  ),
  6 => 
  array (
    0 => 'class.domdocument.php',
    1 => 'DOMDocument',
  ),
  7 => 
  array (
    0 => 'class.domdocumentfragment.php',
    1 => 'DOMDocumentFragment',
  ),
  8 => 
  array (
    0 => 'class.domdocumenttype.php',
    1 => 'DOMDocumentType',
  ),
  9 => 
  array (
    0 => 'class.domelement.php',
    1 => 'DOMElement',
  ),
  10 => 
  array (
    0 => 'class.domentity.php',
    1 => 'DOMEntity',
  ),
  11 => 
  array (
    0 => 'class.domentityreference.php',
    1 => 'DOMEntityReference',
  ),
  12 => 
  array (
    0 => 'class.domexception.php',
    1 => 'DOMException',
  ),
  13 => 
  array (
    0 => 'class.domimplementation.php',
    1 => 'DOMImplementation',
  ),
  14 => 
  array (
    0 => 'class.domnamednodemap.php',
    1 => 'DOMNamedNodeMap',
  ),
  15 => 
  array (
    0 => 'class.domnode.php',
    1 => 'DOMNode',
  ),
  16 => 
  array (
    0 => 'class.domnodelist.php',
    1 => 'DOMNodeList',
  ),
  17 => 
  array (
    0 => 'class.domnotation.php',
    1 => 'DOMNotation',
  ),
  18 => 
  array (
    0 => 'class.domprocessinginstruction.php',
    1 => 'DOMProcessingInstruction',
  ),
  19 => 
  array (
    0 => 'class.domtext.php',
    1 => 'DOMText',
  ),
  20 => 
  array (
    0 => 'class.domxpath.php',
    1 => 'DOMXPath',
  ),
  21 => 
  array (
    0 => 'ref.dom.php',
    1 => 'DOM Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);