<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.exif.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'exif.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'exif.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.exif.php',
    1 => 'Exif Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);