<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.datetime.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'datetime.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'datetime.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'timezones.php',
    1 => 'List of Supported Timezones',
  ),
  4 => 
  array (
    0 => 'datetime.formats.php',
    1 => 'Date and Time Formats',
  ),
  5 => 
  array (
    0 => 'class.datetime.php',
    1 => 'DateTime',
  ),
  6 => 
  array (
    0 => 'class.datetimezone.php',
    1 => 'DateTimeZone',
  ),
  7 => 
  array (
    0 => 'class.dateinterval.php',
    1 => 'DateInterval',
  ),
  8 => 
  array (
    0 => 'class.dateperiod.php',
    1 => 'DatePeriod',
  ),
  9 => 
  array (
    0 => 'ref.datetime.php',
    1 => 'Date/Time Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.calendar.php',
    1 => 'Date and Time Related Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);