<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.ldap.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'ldap.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'ldap.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ldap.using.php',
    1 => 'Using the PHP LDAP calls',
  ),
  4 => 
  array (
    0 => 'ldap.examples.php',
    1 => 'Examples',
  ),
  5 => 
  array (
    0 => 'ref.ldap.php',
    1 => 'LDAP Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);