<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.openssl.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'openssl.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'openssl.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'openssl.certparams.php',
    1 => 'Key/Certificate parameters',
  ),
  4 => 
  array (
    0 => 'openssl.cert.verification.php',
    1 => 'Certificate Verification',
  ),
  5 => 
  array (
    0 => 'ref.openssl.php',
    1 => 'OpenSSL Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.crypto.php',
    1 => 'Cryptography Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);