<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.objaggregation.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'objaggregation.examples.php',
    1 => 'Examples',
  ),
  2 => 
  array (
    0 => 'ref.objaggregation.php',
    1 => 'Object Aggregation Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);