<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.imagick.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'imagick.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'imagick.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'imagick.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'class.imagick.php',
    1 => 'The Imagick class',
  ),
  5 => 
  array (
    0 => 'class.imagickdraw.php',
    1 => 'The ImagickDraw class',
  ),
  6 => 
  array (
    0 => 'class.imagickpixel.php',
    1 => 'The ImagickPixel class',
  ),
  7 => 
  array (
    0 => 'class.imagickpixeliterator.php',
    1 => 'The ImagickPixelIterator class',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);