<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.zlib.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'zlib.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'zlib.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'zlib.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.zlib.php',
    1 => 'Zlib Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);