<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.pdo.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'pdo.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'pdo.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'pdo.connections.php',
    1 => 'Connections and Connection management',
  ),
  4 => 
  array (
    0 => 'pdo.transactions.php',
    1 => 'Transactions and auto-commit',
  ),
  5 => 
  array (
    0 => 'pdo.prepared-statements.php',
    1 => 'Prepared statements and stored procedures',
  ),
  6 => 
  array (
    0 => 'pdo.error-handling.php',
    1 => 'Errors and error handling',
  ),
  7 => 
  array (
    0 => 'pdo.lobs.php',
    1 => 'Large Objects (LOBs)',
  ),
  8 => 
  array (
    0 => 'class.pdo.php',
    1 => 'PDO',
  ),
  9 => 
  array (
    0 => 'class.pdostatement.php',
    1 => 'PDOStatement',
  ),
  10 => 
  array (
    0 => 'class.pdoexception.php',
    1 => 'PDOException',
  ),
  11 => 
  array (
    0 => 'pdo.drivers.php',
    1 => 'PDO Drivers',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.database.abstract.php',
    1 => 'Abstraction Layers',
  ),
  1 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);