<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.bc.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'bc.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'bc.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.bc.php',
    1 => 'BC Math Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.math.php',
    1 => 'Mathematical Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);