<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.radius.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'radius.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'radius.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'radius.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.radius.php',
    1 => 'Radius Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.auth.php',
    1 => 'Authentication Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);