<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.intl.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'intl.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'intl.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'intl.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'class.collator.php',
    1 => 'Collator',
  ),
  5 => 
  array (
    0 => 'class.numberformatter.php',
    1 => 'NumberFormatter',
  ),
  6 => 
  array (
    0 => 'class.locale.php',
    1 => 'Locale',
  ),
  7 => 
  array (
    0 => 'class.normalizer.php',
    1 => 'Normalizer',
  ),
  8 => 
  array (
    0 => 'class.messageformatter.php',
    1 => 'MessageFormatter',
  ),
  9 => 
  array (
    0 => 'class.intldateformatter.php',
    1 => 'IntlDateFormatter',
  ),
  10 => 
  array (
    0 => 'class.resourcebundle.php',
    1 => 'ResourceBundle',
  ),
  11 => 
  array (
    0 => 'ref.intl.grapheme.php',
    1 => 'Grapheme Functions',
  ),
  12 => 
  array (
    0 => 'ref.intl.idn.php',
    1 => 'IDN Functions',
  ),
  13 => 
  array (
    0 => 'ref.intl.php',
    1 => 'intl Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);