<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.sockets.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'sockets.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'sockets.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'sockets.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'sockets.errors.php',
    1 => 'Socket Errors',
  ),
  5 => 
  array (
    0 => 'ref.sockets.php',
    1 => 'Socket Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);