<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.session.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'session.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'session.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'session.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'session.security.php',
    1 => 'Sessions and security',
  ),
  5 => 
  array (
    0 => 'ref.session.php',
    1 => 'Session Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.session.php',
    1 => 'Session Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);