<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.xml.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'xml.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'xml.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'xml.eventhandlers.php',
    1 => 'Event Handlers',
  ),
  4 => 
  array (
    0 => 'xml.case-folding.php',
    1 => 'Case Folding',
  ),
  5 => 
  array (
    0 => 'xml.error-codes.php',
    1 => 'Error Codes',
  ),
  6 => 
  array (
    0 => 'xml.encoding.php',
    1 => 'Character Encoding',
  ),
  7 => 
  array (
    0 => 'xml.examples.php',
    1 => 'Examples',
  ),
  8 => 
  array (
    0 => 'ref.xml.php',
    1 => 'XML Parser Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);