<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.mongo.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'mongo.manual.php',
    1 => 'Manual',
  ),
  2 => 
  array (
    0 => 'mongo.core.php',
    1 => 'Core Classes',
  ),
  3 => 
  array (
    0 => 'mongo.types.php',
    1 => 'Types',
  ),
  4 => 
  array (
    0 => 'mongo.gridfs.php',
    1 => 'GridFS Classes',
  ),
  5 => 
  array (
    0 => 'mongo.functions.php',
    1 => 'Functions',
  ),
  6 => 
  array (
    0 => 'mongo.exceptions.php',
    1 => 'Exceptions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  1 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);