<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.mbstring.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'mbstring.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'mbstring.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'mbstring.encodings.php',
    1 => 'Summaries of supported encodings',
  ),
  4 => 
  array (
    0 => 'mbstring.ja-basic.php',
    1 => 'Basics of Japanese multi-byte encodings',
  ),
  5 => 
  array (
    0 => 'mbstring.http.php',
    1 => 'HTTP Input and Output',
  ),
  6 => 
  array (
    0 => 'mbstring.supported-encodings.php',
    1 => 'Supported Character Encodings',
  ),
  7 => 
  array (
    0 => 'mbstring.overload.php',
    1 => 'Function Overloading Feature',
  ),
  8 => 
  array (
    0 => 'mbstring.php4.req.php',
    1 => 'PHP Character Encoding Requirements',
  ),
  9 => 
  array (
    0 => 'ref.mbstring.php',
    1 => 'Multibyte String Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);