<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.iisfunc.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'iisfunc.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'iisfunc.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.iisfunc.php',
    1 => 'IIS Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.server.php',
    1 => 'Server Specific Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);