<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.w32api.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'w32api.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'w32api.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'w32api.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.w32api.php',
    1 => 'W32api Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);