<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.http.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'http.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'http.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'http.request.options.php',
    1 => 'Request Options',
  ),
  4 => 
  array (
    0 => 'class.httpdeflatestream.php',
    1 => 'The HttpDeflateStream class',
  ),
  5 => 
  array (
    0 => 'class.httpinflatestream.php',
    1 => 'The HttpInflateStream class',
  ),
  6 => 
  array (
    0 => 'class.httpmessage.php',
    1 => 'The HttpMessage class',
  ),
  7 => 
  array (
    0 => 'class.httpquerystring.php',
    1 => 'The HttpQueryString class',
  ),
  8 => 
  array (
    0 => 'class.httprequest.php',
    1 => 'The HttpRequest',
  ),
  9 => 
  array (
    0 => 'class.httprequestpool.php',
    1 => 'The HttpRequestPool class',
  ),
  10 => 
  array (
    0 => 'class.httpresponse.php',
    1 => 'The HttpResponse',
  ),
  11 => 
  array (
    0 => 'ref.http.php',
    1 => 'HTTP Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);