<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.pdf.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'pdf.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'pdf.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'pdf.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.pdf.php',
    1 => 'PDF Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);