<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.sphinx.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'sphinx.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'sphinx.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'sphinx.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'class.sphinxclient.php',
    1 => 'SphinxClient',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);