<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.solr.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'solr.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'solr.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.solr.php',
    1 => 'Solr Functions',
  ),
  4 => 
  array (
    0 => 'solr.examples.php',
    1 => 'Examples',
  ),
  5 => 
  array (
    0 => 'class.solrutils.php',
    1 => 'SolrUtils',
  ),
  6 => 
  array (
    0 => 'class.solrinputdocument.php',
    1 => 'SolrInputDocument',
  ),
  7 => 
  array (
    0 => 'class.solrdocument.php',
    1 => 'SolrDocument',
  ),
  8 => 
  array (
    0 => 'class.solrdocumentfield.php',
    1 => 'SolrDocumentField',
  ),
  9 => 
  array (
    0 => 'class.solrobject.php',
    1 => 'SolrObject',
  ),
  10 => 
  array (
    0 => 'class.solrclient.php',
    1 => 'SolrClient',
  ),
  11 => 
  array (
    0 => 'class.solrresponse.php',
    1 => 'SolrResponse',
  ),
  12 => 
  array (
    0 => 'class.solrqueryresponse.php',
    1 => 'SolrQueryResponse',
  ),
  13 => 
  array (
    0 => 'class.solrupdateresponse.php',
    1 => 'SolrUpdateResponse',
  ),
  14 => 
  array (
    0 => 'class.solrpingresponse.php',
    1 => 'SolrPingResponse',
  ),
  15 => 
  array (
    0 => 'class.solrgenericresponse.php',
    1 => 'SolrGenericResponse',
  ),
  16 => 
  array (
    0 => 'class.solrparams.php',
    1 => 'SolrParams',
  ),
  17 => 
  array (
    0 => 'class.solrmodifiableparams.php',
    1 => 'SolrModifiableParams',
  ),
  18 => 
  array (
    0 => 'class.solrquery.php',
    1 => 'SolrQuery',
  ),
  19 => 
  array (
    0 => 'class.solrexception.php',
    1 => 'SolrException',
  ),
  20 => 
  array (
    0 => 'class.solrclientexception.php',
    1 => 'SolrClientException',
  ),
  21 => 
  array (
    0 => 'class.solrillegalargumentexception.php',
    1 => 'SolrIllegalArgumentException',
  ),
  22 => 
  array (
    0 => 'class.solrillegaloperationexception.php',
    1 => 'SolrIllegalOperationException',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);