<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.pcre.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'pcre.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'pcre.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'pcre.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'pcre.pattern.php',
    1 => 'PCRE Patterns',
  ),
  5 => 
  array (
    0 => 'ref.pcre.php',
    1 => 'PCRE Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'Text Processing',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);