<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.strings.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'strings.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'string.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.strings.php',
    1 => 'String Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'Text Processing',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);