<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.sdo.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'sdo.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'sdo.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'sdo.limitations.php',
    1 => 'Limitations',
  ),
  4 => 
  array (
    0 => 'sdo.examples.php',
    1 => 'Examples',
  ),
  5 => 
  array (
    0 => 'ref.sdo.php',
    1 => 'SDO Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);