<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.ming.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'ming.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'ming.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ming.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.ming.php',
    1 => 'Ming Functions',
  ),
  5 => 
  array (
    0 => 'class.swfaction.php',
    1 => 'SWFAction',
  ),
  6 => 
  array (
    0 => 'class.swfbitmap.php',
    1 => 'SWFBitmap',
  ),
  7 => 
  array (
    0 => 'class.swfbutton.php',
    1 => 'SWFButton',
  ),
  8 => 
  array (
    0 => 'class.swfdisplayitem.php',
    1 => 'SWFDisplayItem',
  ),
  9 => 
  array (
    0 => 'class.swffill.php',
    1 => 'SWFFill',
  ),
  10 => 
  array (
    0 => 'class.swffont.php',
    1 => 'SWFFont',
  ),
  11 => 
  array (
    0 => 'class.swffontchar.php',
    1 => 'SWFFontChar',
  ),
  12 => 
  array (
    0 => 'class.swfgradient.php',
    1 => 'SWFGradient',
  ),
  13 => 
  array (
    0 => 'class.swfmorph.php',
    1 => 'SWFMorph',
  ),
  14 => 
  array (
    0 => 'class.swfmovie.php',
    1 => 'SWFMovie',
  ),
  15 => 
  array (
    0 => 'class.swfprebuiltclip.php',
    1 => 'SWFPrebuiltClip',
  ),
  16 => 
  array (
    0 => 'class.swfshape.php',
    1 => 'SWFShape',
  ),
  17 => 
  array (
    0 => 'class.swfsound.php',
    1 => 'SWFSound',
  ),
  18 => 
  array (
    0 => 'class.swfsoundinstance.php',
    1 => 'SWFSoundInstance',
  ),
  19 => 
  array (
    0 => 'class.swfsprite.php',
    1 => 'SWFSprite',
  ),
  20 => 
  array (
    0 => 'class.swftext.php',
    1 => 'SWFText',
  ),
  21 => 
  array (
    0 => 'class.swftextfield.php',
    1 => 'SWFTextField',
  ),
  22 => 
  array (
    0 => 'class.swfvideostream.php',
    1 => 'SWFVideoStream',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);