<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.pspell.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'pspell.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'pspell.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.pspell.php',
    1 => 'Pspell Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);