<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.gmp.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'gmp.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'gmp.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'gmp.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.gmp.php',
    1 => 'GMP Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.math.php',
    1 => 'Mathematical Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);