<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.gmagick.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'gmagick.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'gmagick.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'gmagick.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'class.gmagick.php',
    1 => 'Gmagick',
  ),
  5 => 
  array (
    0 => 'class.gmagickdraw.php',
    1 => 'GmagickDraw',
  ),
  6 => 
  array (
    0 => 'class.gmagickpixel.php',
    1 => 'GmagickPixel',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);