<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.oauth.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'oauth.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'oauth.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'oauth.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.oauth.php',
    1 => 'OAuth Functions',
  ),
  5 => 
  array (
    0 => 'class.oauth.php',
    1 => 'OAuth',
  ),
  6 => 
  array (
    0 => 'class.oauthprovider.php',
    1 => 'OAuthProvider',
  ),
  7 => 
  array (
    0 => 'class.oauthexception.php',
    1 => 'OAuthException',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);