<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.xmlreader.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'xmlreader.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'class.xmlreader.php',
    1 => 'XMLReader',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);