<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.spl.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'spl.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'spl.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'spl.datastructures.php',
    1 => 'Datastructures',
  ),
  4 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  5 => 
  array (
    0 => 'spl.interfaces.php',
    1 => 'Interfaces',
  ),
  6 => 
  array (
    0 => 'spl.exceptions.php',
    1 => 'Exceptions',
  ),
  7 => 
  array (
    0 => 'ref.spl.php',
    1 => 'SPL Functions',
  ),
  8 => 
  array (
    0 => 'spl.files.php',
    1 => 'File Handling',
  ),
  9 => 
  array (
    0 => 'spl.misc.php',
    1 => 'Miscellaneous Classes and Interfaces',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);