<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.stomp.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'stomp.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'stomp.examples.php',
    1 => 'Examples',
  ),
  3 => 
  array (
    0 => 'ref.stomp.php',
    1 => 'Stomp Functions',
  ),
  4 => 
  array (
    0 => 'class.stomp.php',
    1 => 'Stomp',
  ),
  5 => 
  array (
    0 => 'class.stompframe.php',
    1 => 'StompFrame',
  ),
  6 => 
  array (
    0 => 'class.stompexception.php',
    1 => 'StompException',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);