<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.ifx.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'ifx.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'ifx.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.ifx.php',
    1 => 'Informix Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  1 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);