<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.session-pgsql.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'session-pgsql.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'session-pgsql.tables.php',
    1 => 'Table definitions',
  ),
  3 => 
  array (
    0 => 'session-pgsql.constants.php',
    1 => 'Predefined Constants',
  ),
  4 => 
  array (
    0 => 'ref.session-pgsql.php',
    1 => 'Session PgSQL Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.session.php',
    1 => 'Session Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);