<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.swf.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'swf.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'swf.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'swf.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.swf.php',
    1 => 'SWF Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);