<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.oci8.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'oci8.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'oci8.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'oci8.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'oci8.connection.php',
    1 => 'Connection Handling',
  ),
  5 => 
  array (
    0 => 'oci8.datatypes.php',
    1 => 'Supported Datatypes',
  ),
  6 => 
  array (
    0 => 'ref.oci8.php',
    1 => 'OCI8 Functions',
  ),
  7 => 
  array (
    0 => 'oldaliases.oci8.php',
    1 => 'OCI8 Obsolete Aliases and Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  1 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);