<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.tokyo-tyrant.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'tokyo-tyrant.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'tokyo-tyrant.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'tokyo-tyrant.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'class.tokyotyrant.php',
    1 => 'TokyoTyrant',
  ),
  5 => 
  array (
    0 => 'class.tokyotyranttable.php',
    1 => 'TokyoTyrantTable',
  ),
  6 => 
  array (
    0 => 'class.tokyotyrantquery.php',
    1 => 'TokyoTyrantQuery',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  1 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);