<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.mnogosearch.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'mnogosearch.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'mnogosearch.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.mnogosearch.php',
    1 => 'mnoGoSearch Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);