<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.soap.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'soap.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'soap.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.soap.php',
    1 => 'SOAP Functions',
  ),
  4 => 
  array (
    0 => 'class.soapclient.php',
    1 => 'SoapClient',
  ),
  5 => 
  array (
    0 => 'class.soapserver.php',
    1 => 'SoapServer',
  ),
  6 => 
  array (
    0 => 'class.soapfault.php',
    1 => 'SoapFault',
  ),
  7 => 
  array (
    0 => 'class.soapheader.php',
    1 => 'SoapHeader',
  ),
  8 => 
  array (
    0 => 'class.soapparam.php',
    1 => 'SoapParam',
  ),
  9 => 
  array (
    0 => 'class.soapvar.php',
    1 => 'SoapVar',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);