<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.reflection.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'reflection.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'reflection.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'reflection.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'reflection.extending.php',
    1 => 'Extending',
  ),
  5 => 
  array (
    0 => 'class.reflection.php',
    1 => 'Reflection',
  ),
  6 => 
  array (
    0 => 'class.reflectionclass.php',
    1 => 'ReflectionClass',
  ),
  7 => 
  array (
    0 => 'class.reflectionextension.php',
    1 => 'ReflectionExtension',
  ),
  8 => 
  array (
    0 => 'class.reflectionfunction.php',
    1 => 'ReflectionFunction',
  ),
  9 => 
  array (
    0 => 'class.reflectionfunctionabstract.php',
    1 => 'ReflectionFunctionAbstract',
  ),
  10 => 
  array (
    0 => 'class.reflectionmethod.php',
    1 => 'ReflectionMethod',
  ),
  11 => 
  array (
    0 => 'class.reflectionobject.php',
    1 => 'ReflectionObject',
  ),
  12 => 
  array (
    0 => 'class.reflectionparameter.php',
    1 => 'ReflectionParameter',
  ),
  13 => 
  array (
    0 => 'class.reflectionproperty.php',
    1 => 'ReflectionProperty',
  ),
  14 => 
  array (
    0 => 'class.reflector.php',
    1 => 'Reflector',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);