<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.image.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'image.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'image.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'image.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.image.php',
    1 => 'GD and Image Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);