<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.mail.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'mail.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'mail.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.mail.php',
    1 => 'Mail Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.mail.php',
    1 => 'Mail Related Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);