<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.uodbc.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'uodbc.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'uodbc.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.uodbc.php',
    1 => 'ODBC Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.database.abstract.php',
    1 => 'Abstraction Layers',
  ),
  1 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);