<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.bzip2.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'bzip2.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'bzip2.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'bzip2.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.bzip2.php',
    1 => 'Bzip2 Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);