<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.newt.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'newt.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'newt.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'newt.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.newt.php',
    1 => 'Newt Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.cmdline.php',
    1 => 'Command Line Specific Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);