<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.wincache.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'wincache.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'wincache.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.wincache.php',
    1 => 'WinCache Functions',
  ),
  4 => 
  array (
    0 => 'wincache.win32build.php',
    1 => 'Building for Windows',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);