<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.amqp.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'amqp.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'amqp.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'amqp.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'class.amqpconnection.php',
    1 => 'AMQPConnection',
  ),
  5 => 
  array (
    0 => 'class.amqpexchange.php',
    1 => 'AMQPExchange',
  ),
  6 => 
  array (
    0 => 'class.amqpqueue.php',
    1 => 'AMQPQueue',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);