<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.phar.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'phar.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'phar.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'phar.using.php',
    1 => 'Using Phar Archives',
  ),
  4 => 
  array (
    0 => 'phar.creating.php',
    1 => 'Creating Phar Archives',
  ),
  5 => 
  array (
    0 => 'phar.fileformat.php',
    1 => 'What makes a phar a phar and not a tar or a zip?',
  ),
  6 => 
  array (
    0 => 'class.Phar.php',
    1 => 'Phar',
  ),
  7 => 
  array (
    0 => 'class.PharData.php',
    1 => 'PharData',
  ),
  8 => 
  array (
    0 => 'class.PharFileInfo.php',
    1 => 'PharFileInfo',
  ),
  9 => 
  array (
    0 => 'class.PharException.php',
    1 => 'PharException',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);