<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.memcache.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'memcache.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'memcache.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'memcache.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'class.memcache.php',
    1 => 'Memcache',
  ),
  5 => 
  array (
    0 => 'ref.memcache.php',
    1 => 'Memcache Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);