<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.sem.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'sem.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'sem.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.sem.php',
    1 => 'Semaphore Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);