<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.sqlite3.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'sqlite3.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'sqlite3.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'class.sqlite3.php',
    1 => 'SQLite3',
  ),
  4 => 
  array (
    0 => 'class.sqlite3stmt.php',
    1 => 'SQLite3Stmt',
  ),
  5 => 
  array (
    0 => 'class.sqlite3result.php',
    1 => 'SQLite3Result',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  1 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);