<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.runkit.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'runkit.constants.php',
    1 => 'Predefined Constants',
  ),
  2 => 
  array (
    0 => 'runkit.setup.php',
    1 => 'Installing/Configuring',
  ),
  3 => 
  array (
    0 => 'ref.runkit.php',
    1 => 'runkit Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);