<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.curl.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'curl.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'curl.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'curl.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.curl.php',
    1 => 'cURL Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);