<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.ctype.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'ctype.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'ctype.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.ctype.php',
    1 => 'Ctype Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);