<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.xmlrpc.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'xmlrpc.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'xmlrpc.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.xmlrpc.php',
    1 => 'XML-RPC Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);