<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.spplus.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'spplus.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'spplus.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.spplus.php',
    1 => 'SPPLUS Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.creditcard.php',
    1 => 'Credit Card Processing',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);