<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.filter.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'filter.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'filter.filters.php',
    1 => 'Types of filters',
  ),
  3 => 
  array (
    0 => 'filter.constants.php',
    1 => 'Predefined Constants',
  ),
  4 => 
  array (
    0 => 'filter.examples.php',
    1 => 'Examples',
  ),
  5 => 
  array (
    0 => 'ref.filter.php',
    1 => 'Filter Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);