<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.regex.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'regex.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'regex.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'regex.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.regex.php',
    1 => 'POSIX Regex Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'Text Processing',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);