<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.shmop.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'shmop.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'shmop.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'shmop.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.shmop.php',
    1 => 'Shared Memory Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);