<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.sdo-das-xml.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'sdo-das-xml.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'sdo-das-xml.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'sdo-das-xml.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.sdo-das-xml.php',
    1 => 'SDO DAS XML Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);