<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.scream.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'scream.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'scream.examples.php',
    1 => 'Examples',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);