<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.ktaglib.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'ktaglib.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'ktaglib.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'class.mpegfile.php',
    1 => 'KTaglib_MPEG_File',
  ),
  4 => 
  array (
    0 => 'class.audioproperties.php',
    1 => 'KTaglib_MPEG_AudioProperties',
  ),
  5 => 
  array (
    0 => 'class.tag.php',
    1 => 'KTaglib_Tag',
  ),
  6 => 
  array (
    0 => 'class.id3v2tag.php',
    1 => 'KTaglib_ID3v2_Tag',
  ),
  7 => 
  array (
    0 => 'class.id3v2frame.php',
    1 => 'KTaglib_ID3v2_Frame',
  ),
  8 => 
  array (
    0 => 'class.id3v2attachedpictureframe.php',
    1 => 'KTaglib_ID3v2_AttachedPictureFrame',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);