<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.snmp.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'snmp.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'snmp.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.snmp.php',
    1 => 'SNMP Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);