<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.judy.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'judy.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'class.judy.php',
    1 => 'Judy',
  ),
  3 => 
  array (
    0 => 'ref.judy.php',
    1 => 'Judy Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);