<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.haru.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'haru.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'haru.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'haru.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'haru.builtin.php',
    1 => 'Builtin Fonts And Encodings',
  ),
  5 => 
  array (
    0 => 'class.haruexception.php',
    1 => 'HaruException',
  ),
  6 => 
  array (
    0 => 'class.harudoc.php',
    1 => 'HaruDoc',
  ),
  7 => 
  array (
    0 => 'class.harupage.php',
    1 => 'HaruPage',
  ),
  8 => 
  array (
    0 => 'class.harufont.php',
    1 => 'HaruFont',
  ),
  9 => 
  array (
    0 => 'class.haruimage.php',
    1 => 'HaruImage',
  ),
  10 => 
  array (
    0 => 'class.haruencoder.php',
    1 => 'HaruEncoder',
  ),
  11 => 
  array (
    0 => 'class.haruoutline.php',
    1 => 'HaruOutline',
  ),
  12 => 
  array (
    0 => 'class.haruannotation.php',
    1 => 'HaruAnnotation',
  ),
  13 => 
  array (
    0 => 'class.harudestination.php',
    1 => 'HaruDestination',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);