<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.ps.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'ps.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'ps.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.ps.php',
    1 => 'PS Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);