<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.var.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'var.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'var.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.var.php',
    1 => 'Variable handling Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);