<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.id3.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'id3.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'id3.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.id3.php',
    1 => 'ID3 Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);