<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.apd.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'apd.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'apd.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'apd.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'ref.apd.php',
    1 => 'APD Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);