<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.gearman.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'gearman.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'gearman.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'gearman.examples.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'class.gearmanclient.php',
    1 => 'GearmanClient',
  ),
  5 => 
  array (
    0 => 'class.gearmanjob.php',
    1 => 'GearmanJob',
  ),
  6 => 
  array (
    0 => 'class.gearmantask.php',
    1 => 'GearmanTask',
  ),
  7 => 
  array (
    0 => 'class.gearmanworker.php',
    1 => 'GearmanWorker',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);