<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.com.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'com.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'com.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'com.error-handling.php',
    1 => 'Errors and error handling',
  ),
  4 => 
  array (
    0 => 'com.examples.php',
    1 => 'Examples',
  ),
  5 => 
  array (
    0 => 'ref.com.php',
    1 => 'COM Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);