<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.parsekit.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'parsekit.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'parsekit.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.parsekit.php',
    1 => 'Parsekit Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);