<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.oggvorbis.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'oggvorbis.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'oggvorbis.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'oggvorbis.contexts.php',
    1 => 'Context options',
  ),
  4 => 
  array (
    0 => 'oggvorbis.examples.php',
    1 => 'Examples',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);