<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.spl-types.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'spl-types.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'class.splint.php',
    1 => 'SplInt',
  ),
  3 => 
  array (
    0 => 'class.splfloat.php',
    1 => 'SplFloat',
  ),
  4 => 
  array (
    0 => 'class.splenum.php',
    1 => 'SplEnum',
  ),
  5 => 
  array (
    0 => 'class.splbool.php',
    1 => 'SplBool',
  ),
  6 => 
  array (
    0 => 'class.splstring.php',
    1 => 'SplString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);