<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.lzf.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'lzf.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'lzf.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'ref.lzf.php',
    1 => 'LZF Functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);