<?php
$TOC = array (
  0 => 
  array (
    0 => 'calendar.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'calendar.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'calendar.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'calendar.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.calendar.php',
    1 => 'Calendar',
  ),
  1 => 
  array (
    0 => 'refs.calendar.php',
    1 => 'Date and Time Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);