<?php
$TOC = array (
  0 => 
  array (
    0 => 'gmagick.addimage.php',
    1 => 'Gmagick::addimage',
  ),
  1 => 
  array (
    0 => 'gmagick.addnoiseimage.php',
    1 => 'Gmagick::addnoiseimage',
  ),
  2 => 
  array (
    0 => 'gmagick.annotateimage.php',
    1 => 'Gmagick::annotateimage',
  ),
  3 => 
  array (
    0 => 'gmagick.blurimage.php',
    1 => 'Gmagick::blurimage',
  ),
  4 => 
  array (
    0 => 'gmagick.borderimage.php',
    1 => 'Gmagick::borderimage',
  ),
  5 => 
  array (
    0 => 'gmagick.charcoalimage.php',
    1 => 'Gmagick::charcoalimage',
  ),
  6 => 
  array (
    0 => 'gmagick.chopimage.php',
    1 => 'Gmagick::chopimage',
  ),
  7 => 
  array (
    0 => 'gmagick.clear.php',
    1 => 'Gmagick::clear',
  ),
  8 => 
  array (
    0 => 'gmagick.commentimage.php',
    1 => 'Gmagick::commentimage',
  ),
  9 => 
  array (
    0 => 'gmagick.compositeimage.php',
    1 => 'Gmagick::compositeimage',
  ),
  10 => 
  array (
    0 => 'gmagick.construct.php',
    1 => 'Gmagick::__construct',
  ),
  11 => 
  array (
    0 => 'gmagick.cropimage.php',
    1 => 'Gmagick::cropimage',
  ),
  12 => 
  array (
    0 => 'gmagick.cropthumbnailimage.php',
    1 => 'Gmagick::cropthumbnailimage',
  ),
  13 => 
  array (
    0 => 'gmagick.current.php',
    1 => 'Gmagick::current',
  ),
  14 => 
  array (
    0 => 'gmagick.cyclecolormapimage.php',
    1 => 'Gmagick::cyclecolormapimage',
  ),
  15 => 
  array (
    0 => 'gmagick.deconstructimages.php',
    1 => 'Gmagick::deconstructimages',
  ),
  16 => 
  array (
    0 => 'gmagick.despeckleimage.php',
    1 => 'Gmagick::despeckleimage',
  ),
  17 => 
  array (
    0 => 'gmagick.destroy.php',
    1 => 'Gmagick::destroy',
  ),
  18 => 
  array (
    0 => 'gmagick.drawimage.php',
    1 => 'Gmagick::drawimage',
  ),
  19 => 
  array (
    0 => 'gmagick.edgeimage.php',
    1 => 'Gmagick::edgeimage',
  ),
  20 => 
  array (
    0 => 'gmagick.embossimage.php',
    1 => 'Gmagick::embossimage',
  ),
  21 => 
  array (
    0 => 'gmagick.enhanceimage.php',
    1 => 'Gmagick::enhanceimage',
  ),
  22 => 
  array (
    0 => 'gmagick.equalizeimage.php',
    1 => 'Gmagick::equalizeimage',
  ),
  23 => 
  array (
    0 => 'gmagick.flipimage.php',
    1 => 'Gmagick::flipimage',
  ),
  24 => 
  array (
    0 => 'gmagick.flopimage.php',
    1 => 'Gmagick::flopimage',
  ),
  25 => 
  array (
    0 => 'gmagick.frameimage.php',
    1 => 'Gmagick::frameimage',
  ),
  26 => 
  array (
    0 => 'gmagick.gammaimage.php',
    1 => 'Gmagick::gammaimage',
  ),
  27 => 
  array (
    0 => 'gmagick.getcopyright.php',
    1 => 'Gmagick::getcopyright',
  ),
  28 => 
  array (
    0 => 'gmagick.getfilename.php',
    1 => 'Gmagick::getfilename',
  ),
  29 => 
  array (
    0 => 'gmagick.getimagebackgroundcolor.php',
    1 => 'Gmagick::getimagebackgroundcolor',
  ),
  30 => 
  array (
    0 => 'gmagick.getimageblueprimary.php',
    1 => 'Gmagick::getimageblueprimary',
  ),
  31 => 
  array (
    0 => 'gmagick.getimagebordercolor.php',
    1 => 'Gmagick::getimagebordercolor',
  ),
  32 => 
  array (
    0 => 'gmagick.getimagechanneldepth.php',
    1 => 'Gmagick::getimagechanneldepth',
  ),
  33 => 
  array (
    0 => 'gmagick.getimagecolors.php',
    1 => 'Gmagick::getimagecolors',
  ),
  34 => 
  array (
    0 => 'gmagick.getimagecolorspace.php',
    1 => 'Gmagick::getimagecolorspace',
  ),
  35 => 
  array (
    0 => 'gmagick.getimagecompose.php',
    1 => 'Gmagick::getimagecompose',
  ),
  36 => 
  array (
    0 => 'gmagick.getimagedelay.php',
    1 => 'Gmagick::getimagedelay',
  ),
  37 => 
  array (
    0 => 'gmagick.getimagedepth.php',
    1 => 'Gmagick::getimagedepth',
  ),
  38 => 
  array (
    0 => 'gmagick.getimagedispose.php',
    1 => 'Gmagick::getimagedispose',
  ),
  39 => 
  array (
    0 => 'gmagick.getimageextrema.php',
    1 => 'Gmagick::getimageextrema',
  ),
  40 => 
  array (
    0 => 'gmagick.getimagefilename.php',
    1 => 'Gmagick::getimagefilename',
  ),
  41 => 
  array (
    0 => 'gmagick.getimageformat.php',
    1 => 'Gmagick::getimageformat',
  ),
  42 => 
  array (
    0 => 'gmagick.getimagegamma.php',
    1 => 'Gmagick::getimagegamma',
  ),
  43 => 
  array (
    0 => 'gmagick.getimagegreenprimary.php',
    1 => 'Gmagick::getimagegreenprimary',
  ),
  44 => 
  array (
    0 => 'gmagick.getimageheight.php',
    1 => 'Gmagick::getimageheight',
  ),
  45 => 
  array (
    0 => 'gmagick.getimagehistogram.php',
    1 => 'Gmagick::getimagehistogram',
  ),
  46 => 
  array (
    0 => 'gmagick.getimageindex.php',
    1 => 'Gmagick::getimageindex',
  ),
  47 => 
  array (
    0 => 'gmagick.getimageinterlacescheme.php',
    1 => 'Gmagick::getimageinterlacescheme',
  ),
  48 => 
  array (
    0 => 'gmagick.getimageiterations.php',
    1 => 'Gmagick::getimageiterations',
  ),
  49 => 
  array (
    0 => 'gmagick.getimagematte.php',
    1 => 'Gmagick::getimagematte',
  ),
  50 => 
  array (
    0 => 'gmagick.getimagemattecolor.php',
    1 => 'Gmagick::getimagemattecolor',
  ),
  51 => 
  array (
    0 => 'gmagick.getimageprofile.php',
    1 => 'Gmagick::getimageprofile',
  ),
  52 => 
  array (
    0 => 'gmagick.getimageredprimary.php',
    1 => 'Gmagick::getimageredprimary',
  ),
  53 => 
  array (
    0 => 'gmagick.getimagerenderingintent.php',
    1 => 'Gmagick::getimagerenderingintent',
  ),
  54 => 
  array (
    0 => 'gmagick.getimageresolution.php',
    1 => 'Gmagick::getimageresolution',
  ),
  55 => 
  array (
    0 => 'gmagick.getimagescene.php',
    1 => 'Gmagick::getimagescene',
  ),
  56 => 
  array (
    0 => 'gmagick.getimagesignature.php',
    1 => 'Gmagick::getimagesignature',
  ),
  57 => 
  array (
    0 => 'gmagick.getimagetype.php',
    1 => 'Gmagick::getimagetype',
  ),
  58 => 
  array (
    0 => 'gmagick.getimageunits.php',
    1 => 'Gmagick::getimageunits',
  ),
  59 => 
  array (
    0 => 'gmagick.getimagewhitepoint.php',
    1 => 'Gmagick::getimagewhitepoint',
  ),
  60 => 
  array (
    0 => 'gmagick.getimagewidth.php',
    1 => 'Gmagick::getimagewidth',
  ),
  61 => 
  array (
    0 => 'gmagick.getpackagename.php',
    1 => 'Gmagick::getpackagename',
  ),
  62 => 
  array (
    0 => 'gmagick.getquantumdepth.php',
    1 => 'Gmagick::getquantumdepth',
  ),
  63 => 
  array (
    0 => 'gmagick.getreleasedate.php',
    1 => 'Gmagick::getreleasedate',
  ),
  64 => 
  array (
    0 => 'gmagick.getsamplingfactors.php',
    1 => 'Gmagick::getsamplingfactors',
  ),
  65 => 
  array (
    0 => 'gmagick.getsize.php',
    1 => 'Gmagick::getsize',
  ),
  66 => 
  array (
    0 => 'gmagick.getversion.php',
    1 => 'Gmagick::getversion',
  ),
  67 => 
  array (
    0 => 'gmagick.hasnextimage.php',
    1 => 'Gmagick::hasnextimage',
  ),
  68 => 
  array (
    0 => 'gmagick.haspreviousimage.php',
    1 => 'Gmagick::haspreviousimage',
  ),
  69 => 
  array (
    0 => 'gmagick.implodeimage.php',
    1 => 'Gmagick::implodeimage',
  ),
  70 => 
  array (
    0 => 'gmagick.labelimage.php',
    1 => 'Gmagick::labelimage',
  ),
  71 => 
  array (
    0 => 'gmagick.levelimage.php',
    1 => 'Gmagick::levelimage',
  ),
  72 => 
  array (
    0 => 'gmagick.magnifyimage.php',
    1 => 'Gmagick::magnifyimage',
  ),
  73 => 
  array (
    0 => 'gmagick.mapimage.php',
    1 => 'Gmagick::mapimage',
  ),
  74 => 
  array (
    0 => 'gmagick.medianfilterimage.php',
    1 => 'Gmagick::medianfilterimage',
  ),
  75 => 
  array (
    0 => 'gmagick.minifyimage.php',
    1 => 'Gmagick::minifyimage',
  ),
  76 => 
  array (
    0 => 'gmagick.modulateimage.php',
    1 => 'Gmagick::modulateimage',
  ),
  77 => 
  array (
    0 => 'gmagick.motionblurimage.php',
    1 => 'Gmagick::motionblurimage',
  ),
  78 => 
  array (
    0 => 'gmagick.newimage.php',
    1 => 'Gmagick::newimage',
  ),
  79 => 
  array (
    0 => 'gmagick.nextimage.php',
    1 => 'Gmagick::nextimage',
  ),
  80 => 
  array (
    0 => 'gmagick.normalizeimage.php',
    1 => 'Gmagick::normalizeimage',
  ),
  81 => 
  array (
    0 => 'gmagick.oilpaintimage.php',
    1 => 'Gmagick::oilpaintimage',
  ),
  82 => 
  array (
    0 => 'gmagick.previousimage.php',
    1 => 'Gmagick::previousimage',
  ),
  83 => 
  array (
    0 => 'gmagick.profileimage.php',
    1 => 'Gmagick::profileimage',
  ),
  84 => 
  array (
    0 => 'gmagick.quantizeimage.php',
    1 => 'Gmagick::quantizeimage',
  ),
  85 => 
  array (
    0 => 'gmagick.quantizeimages.php',
    1 => 'Gmagick::quantizeimages',
  ),
  86 => 
  array (
    0 => 'gmagick.queryfontmetrics.php',
    1 => 'Gmagick::queryfontmetrics',
  ),
  87 => 
  array (
    0 => 'gmagick.queryfonts.php',
    1 => 'Gmagick::queryfonts',
  ),
  88 => 
  array (
    0 => 'gmagick.queryformats.php',
    1 => 'Gmagick::queryformats',
  ),
  89 => 
  array (
    0 => 'gmagick.radialblurimage.php',
    1 => 'Gmagick::radialblurimage',
  ),
  90 => 
  array (
    0 => 'gmagick.raiseimage.php',
    1 => 'Gmagick::raiseimage',
  ),
  91 => 
  array (
    0 => 'gmagick.read.php',
    1 => 'Gmagick::read',
  ),
  92 => 
  array (
    0 => 'gmagick.readimage.php',
    1 => 'Gmagick::readimage',
  ),
  93 => 
  array (
    0 => 'gmagick.readimageblob.php',
    1 => 'Gmagick::readimageblob',
  ),
  94 => 
  array (
    0 => 'gmagick.readimagefile.php',
    1 => 'Gmagick::readimagefile',
  ),
  95 => 
  array (
    0 => 'gmagick.reducenoiseimage.php',
    1 => 'Gmagick::reducenoiseimage',
  ),
  96 => 
  array (
    0 => 'gmagick.removeimage.php',
    1 => 'Gmagick::removeimage',
  ),
  97 => 
  array (
    0 => 'gmagick.removeimageprofile.php',
    1 => 'Gmagick::removeimageprofile',
  ),
  98 => 
  array (
    0 => 'gmagick.resampleimage.php',
    1 => 'Gmagick::resampleimage',
  ),
  99 => 
  array (
    0 => 'gmagick.resizeimage.php',
    1 => 'Gmagick::resizeimage',
  ),
  100 => 
  array (
    0 => 'gmagick.rollimage.php',
    1 => 'Gmagick::rollimage',
  ),
  101 => 
  array (
    0 => 'gmagick.rotateimage.php',
    1 => 'Gmagick::rotateimage',
  ),
  102 => 
  array (
    0 => 'gmagick.scaleimage.php',
    1 => 'Gmagick::scaleimage',
  ),
  103 => 
  array (
    0 => 'gmagick.separateimagechannel.php',
    1 => 'Gmagick::separateimagechannel',
  ),
  104 => 
  array (
    0 => 'gmagick.setfilename.php',
    1 => 'Gmagick::setfilename',
  ),
  105 => 
  array (
    0 => 'gmagick.setimagebackgroundcolor.php',
    1 => 'Gmagick::setimagebackgroundcolor',
  ),
  106 => 
  array (
    0 => 'gmagick.setimageblueprimary.php',
    1 => 'Gmagick::setimageblueprimary',
  ),
  107 => 
  array (
    0 => 'gmagick.setimagebordercolor.php',
    1 => 'Gmagick::setimagebordercolor',
  ),
  108 => 
  array (
    0 => 'gmagick.setimagechanneldepth.php',
    1 => 'Gmagick::setimagechanneldepth',
  ),
  109 => 
  array (
    0 => 'gmagick.setimagecolorspace.php',
    1 => 'Gmagick::setimagecolorspace',
  ),
  110 => 
  array (
    0 => 'gmagick.setimagecompose.php',
    1 => 'Gmagick::setimagecompose',
  ),
  111 => 
  array (
    0 => 'gmagick.setimagedelay.php',
    1 => 'Gmagick::setimagedelay',
  ),
  112 => 
  array (
    0 => 'gmagick.setimagedepth.php',
    1 => 'Gmagick::setimagedepth',
  ),
  113 => 
  array (
    0 => 'gmagick.setimagedispose.php',
    1 => 'Gmagick::setimagedispose',
  ),
  114 => 
  array (
    0 => 'gmagick.setimagefilename.php',
    1 => 'Gmagick::setimagefilename',
  ),
  115 => 
  array (
    0 => 'gmagick.setimageformat.php',
    1 => 'Gmagick::setimageformat',
  ),
  116 => 
  array (
    0 => 'gmagick.setimagegamma.php',
    1 => 'Gmagick::setimagegamma',
  ),
  117 => 
  array (
    0 => 'gmagick.setimagegreenprimary.php',
    1 => 'Gmagick::setimagegreenprimary',
  ),
  118 => 
  array (
    0 => 'gmagick.setimageindex.php',
    1 => 'Gmagick::setimageindex',
  ),
  119 => 
  array (
    0 => 'gmagick.setimageinterlacescheme.php',
    1 => 'Gmagick::setimageinterlacescheme',
  ),
  120 => 
  array (
    0 => 'gmagick.setimageiterations.php',
    1 => 'Gmagick::setimageiterations',
  ),
  121 => 
  array (
    0 => 'gmagick.setimageprofile.php',
    1 => 'Gmagick::setimageprofile',
  ),
  122 => 
  array (
    0 => 'gmagick.setimageredprimary.php',
    1 => 'Gmagick::setimageredprimary',
  ),
  123 => 
  array (
    0 => 'gmagick.setimagerenderingintent.php',
    1 => 'Gmagick::setimagerenderingintent',
  ),
  124 => 
  array (
    0 => 'gmagick.setimageresolution.php',
    1 => 'Gmagick::setimageresolution',
  ),
  125 => 
  array (
    0 => 'gmagick.setimagescene.php',
    1 => 'Gmagick::setimagescene',
  ),
  126 => 
  array (
    0 => 'gmagick.setimagetype.php',
    1 => 'Gmagick::setimagetype',
  ),
  127 => 
  array (
    0 => 'gmagick.setimageunits.php',
    1 => 'Gmagick::setimageunits',
  ),
  128 => 
  array (
    0 => 'gmagick.setimagewhitepoint.php',
    1 => 'Gmagick::setimagewhitepoint',
  ),
  129 => 
  array (
    0 => 'gmagick.setsamplingfactors.php',
    1 => 'Gmagick::setsamplingfactors',
  ),
  130 => 
  array (
    0 => 'gmagick.setsize.php',
    1 => 'Gmagick::setsize',
  ),
  131 => 
  array (
    0 => 'gmagick.shearimage.php',
    1 => 'Gmagick::shearimage',
  ),
  132 => 
  array (
    0 => 'gmagick.solarizeimage.php',
    1 => 'Gmagick::solarizeimage',
  ),
  133 => 
  array (
    0 => 'gmagick.spreadimage.php',
    1 => 'Gmagick::spreadimage',
  ),
  134 => 
  array (
    0 => 'gmagick.stripimage.php',
    1 => 'Gmagick::stripimage',
  ),
  135 => 
  array (
    0 => 'gmagick.swirlimage.php',
    1 => 'Gmagick::swirlimage',
  ),
  136 => 
  array (
    0 => 'gmagick.thumbnailimage.php',
    1 => 'Gmagick::thumbnailimage',
  ),
  137 => 
  array (
    0 => 'gmagick.trimimage.php',
    1 => 'Gmagick::trimimage',
  ),
  138 => 
  array (
    0 => 'gmagick.write.php',
    1 => 'Gmagick::write',
  ),
  139 => 
  array (
    0 => 'gmagick.writeimage.php',
    1 => 'Gmagick::writeimage',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gmagick.php',
    1 => 'Gmagick',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);