<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.imagick-adaptiveblurimage.php',
    1 => 'Imagick::adaptiveBlurImage',
  ),
  1 => 
  array (
    0 => 'function.imagick-adaptiveresizeimage.php',
    1 => 'Imagick::adaptiveResizeImage',
  ),
  2 => 
  array (
    0 => 'function.imagick-adaptivesharpenimage.php',
    1 => 'Imagick::adaptiveSharpenImage',
  ),
  3 => 
  array (
    0 => 'function.imagick-adaptivethresholdimage.php',
    1 => 'Imagick::adaptiveThresholdImage',
  ),
  4 => 
  array (
    0 => 'function.imagick-addimage.php',
    1 => 'Imagick::addImage',
  ),
  5 => 
  array (
    0 => 'function.imagick-addnoiseimage.php',
    1 => 'Imagick::addNoiseImage',
  ),
  6 => 
  array (
    0 => 'function.imagick-affinetransformimage.php',
    1 => 'Imagick::affineTransformImage',
  ),
  7 => 
  array (
    0 => 'function.imagick-animateimages.php',
    1 => 'Imagick::animateImages',
  ),
  8 => 
  array (
    0 => 'function.imagick-annotateimage.php',
    1 => 'Imagick::annotateImage',
  ),
  9 => 
  array (
    0 => 'function.imagick-appendimages.php',
    1 => 'Imagick::appendImages',
  ),
  10 => 
  array (
    0 => 'function.imagick-averageimages.php',
    1 => 'Imagick::averageImages',
  ),
  11 => 
  array (
    0 => 'function.imagick-blackthresholdimage.php',
    1 => 'Imagick::blackThresholdImage',
  ),
  12 => 
  array (
    0 => 'function.imagick-blurimage.php',
    1 => 'Imagick::blurImage',
  ),
  13 => 
  array (
    0 => 'function.imagick-borderimage.php',
    1 => 'Imagick::borderImage',
  ),
  14 => 
  array (
    0 => 'function.imagick-charcoalimage.php',
    1 => 'Imagick::charcoalImage',
  ),
  15 => 
  array (
    0 => 'function.imagick-chopimage.php',
    1 => 'Imagick::chopImage',
  ),
  16 => 
  array (
    0 => 'function.imagick-clear.php',
    1 => 'Imagick::clear',
  ),
  17 => 
  array (
    0 => 'function.imagick-clipimage.php',
    1 => 'Imagick::clipImage',
  ),
  18 => 
  array (
    0 => 'function.imagick-clippathimage.php',
    1 => 'Imagick::clipPathImage',
  ),
  19 => 
  array (
    0 => 'function.imagick-clone.php',
    1 => 'Imagick::clone',
  ),
  20 => 
  array (
    0 => 'function.imagick-clutimage.php',
    1 => 'Imagick::clutImage',
  ),
  21 => 
  array (
    0 => 'function.imagick-coalesceimages.php',
    1 => 'Imagick::coalesceImages',
  ),
  22 => 
  array (
    0 => 'function.imagick-colorfloodfillimage.php',
    1 => 'Imagick::colorFloodfillImage',
  ),
  23 => 
  array (
    0 => 'function.imagick-colorizeimage.php',
    1 => 'Imagick::colorizeImage',
  ),
  24 => 
  array (
    0 => 'function.imagick-combineimages.php',
    1 => 'Imagick::combineImages',
  ),
  25 => 
  array (
    0 => 'function.imagick-commentimage.php',
    1 => 'Imagick::commentImage',
  ),
  26 => 
  array (
    0 => 'function.imagick-compareimagechannels.php',
    1 => 'Imagick::compareImageChannels',
  ),
  27 => 
  array (
    0 => 'function.imagick-compareimagelayers.php',
    1 => 'Imagick::compareImageLayers',
  ),
  28 => 
  array (
    0 => 'function.imagick-compareimages.php',
    1 => 'Imagick::compareImages',
  ),
  29 => 
  array (
    0 => 'function.imagick-compositeimage.php',
    1 => 'Imagick::compositeImage',
  ),
  30 => 
  array (
    0 => 'function.imagick-construct.php',
    1 => 'Imagick::__construct',
  ),
  31 => 
  array (
    0 => 'function.imagick-contrastimage.php',
    1 => 'Imagick::contrastImage',
  ),
  32 => 
  array (
    0 => 'function.imagick-contraststretchimage.php',
    1 => 'Imagick::contrastStretchImage',
  ),
  33 => 
  array (
    0 => 'function.imagick-convolveimage.php',
    1 => 'Imagick::convolveImage',
  ),
  34 => 
  array (
    0 => 'function.imagick-cropimage.php',
    1 => 'Imagick::cropImage',
  ),
  35 => 
  array (
    0 => 'function.imagick-cropthumbnailimage.php',
    1 => 'Imagick::cropThumbnailImage',
  ),
  36 => 
  array (
    0 => 'function.imagick-current.php',
    1 => 'Imagick::current',
  ),
  37 => 
  array (
    0 => 'function.imagick-cyclecolormapimage.php',
    1 => 'Imagick::cycleColormapImage',
  ),
  38 => 
  array (
    0 => 'function.imagick-decipherimage.php',
    1 => 'Imagick::decipherImage',
  ),
  39 => 
  array (
    0 => 'function.imagick-deconstructimages.php',
    1 => 'Imagick::deconstructImages',
  ),
  40 => 
  array (
    0 => 'function.imagick-deleteimageartifact.php',
    1 => 'Imagick::deleteImageArtifact',
  ),
  41 => 
  array (
    0 => 'imagick.deskewimage.php',
    1 => 'Imagick::deskewImage',
  ),
  42 => 
  array (
    0 => 'function.imagick-despeckleimage.php',
    1 => 'Imagick::despeckleImage',
  ),
  43 => 
  array (
    0 => 'function.imagick-destroy.php',
    1 => 'Imagick::destroy',
  ),
  44 => 
  array (
    0 => 'function.imagick-displayimage.php',
    1 => 'Imagick::displayImage',
  ),
  45 => 
  array (
    0 => 'function.imagick-displayimages.php',
    1 => 'Imagick::displayImages',
  ),
  46 => 
  array (
    0 => 'function.imagick-distortimage.php',
    1 => 'Imagick::distortImage',
  ),
  47 => 
  array (
    0 => 'function.imagick-drawimage.php',
    1 => 'Imagick::drawImage',
  ),
  48 => 
  array (
    0 => 'function.imagick-edgeimage.php',
    1 => 'Imagick::edgeImage',
  ),
  49 => 
  array (
    0 => 'function.imagick-embossimage.php',
    1 => 'Imagick::embossImage',
  ),
  50 => 
  array (
    0 => 'function.imagick-encipherimage.php',
    1 => 'Imagick::encipherImage',
  ),
  51 => 
  array (
    0 => 'function.imagick-enhanceimage.php',
    1 => 'Imagick::enhanceImage',
  ),
  52 => 
  array (
    0 => 'function.imagick-equalizeimage.php',
    1 => 'Imagick::equalizeImage',
  ),
  53 => 
  array (
    0 => 'function.imagick-evaluateimage.php',
    1 => 'Imagick::evaluateImage',
  ),
  54 => 
  array (
    0 => 'imagick.exportimagepixels.php',
    1 => 'Imagick::exportImagePixels',
  ),
  55 => 
  array (
    0 => 'function.imagick-extentimage.php',
    1 => 'Imagick::extentImage',
  ),
  56 => 
  array (
    0 => 'function.imagick-flattenimages.php',
    1 => 'Imagick::flattenImages',
  ),
  57 => 
  array (
    0 => 'function.imagick-flipimage.php',
    1 => 'Imagick::flipImage',
  ),
  58 => 
  array (
    0 => 'function.imagick-floodfillpaintimage.php',
    1 => 'Imagick::floodFillPaintImage',
  ),
  59 => 
  array (
    0 => 'function.imagick-flopimage.php',
    1 => 'Imagick::flopImage',
  ),
  60 => 
  array (
    0 => 'function.imagick-frameimage.php',
    1 => 'Imagick::frameImage',
  ),
  61 => 
  array (
    0 => 'imagick.functionimage.php',
    1 => 'Imagick::functionImage',
  ),
  62 => 
  array (
    0 => 'function.imagick-fximage.php',
    1 => 'Imagick::fxImage',
  ),
  63 => 
  array (
    0 => 'function.imagick-gammaimage.php',
    1 => 'Imagick::gammaImage',
  ),
  64 => 
  array (
    0 => 'function.imagick-gaussianblurimage.php',
    1 => 'Imagick::gaussianBlurImage',
  ),
  65 => 
  array (
    0 => 'function.imagick-getcolorspace.php',
    1 => 'Imagick::getColorspace',
  ),
  66 => 
  array (
    0 => 'function.imagick-getcompression.php',
    1 => 'Imagick::getCompression',
  ),
  67 => 
  array (
    0 => 'function.imagick-getcompressionquality.php',
    1 => 'Imagick::getCompressionQuality',
  ),
  68 => 
  array (
    0 => 'function.imagick-getcopyright.php',
    1 => 'Imagick::getCopyright',
  ),
  69 => 
  array (
    0 => 'function.imagick-getfilename.php',
    1 => 'Imagick::getFilename',
  ),
  70 => 
  array (
    0 => 'function.imagick-getfont.php',
    1 => 'Imagick::getFont',
  ),
  71 => 
  array (
    0 => 'function.imagick-getformat.php',
    1 => 'Imagick::getFormat',
  ),
  72 => 
  array (
    0 => 'function.imagick-getgravity.php',
    1 => 'Imagick::getGravity',
  ),
  73 => 
  array (
    0 => 'function.imagick-gethomeurl.php',
    1 => 'Imagick::getHomeURL',
  ),
  74 => 
  array (
    0 => 'function.imagick-getimage.php',
    1 => 'Imagick::getImage',
  ),
  75 => 
  array (
    0 => 'function.imagick-getimagealphachannel.php',
    1 => 'Imagick::getImageAlphaChannel',
  ),
  76 => 
  array (
    0 => 'function.imagick-getimageartifact.php',
    1 => 'Imagick::getImageArtifact',
  ),
  77 => 
  array (
    0 => 'function.imagick-getimagebackgroundcolor.php',
    1 => 'Imagick::getImageBackgroundColor',
  ),
  78 => 
  array (
    0 => 'function.imagick-getimageblob.php',
    1 => 'Imagick::getImageBlob',
  ),
  79 => 
  array (
    0 => 'function.imagick-getimageblueprimary.php',
    1 => 'Imagick::getImageBluePrimary',
  ),
  80 => 
  array (
    0 => 'function.imagick-getimagebordercolor.php',
    1 => 'Imagick::getImageBorderColor',
  ),
  81 => 
  array (
    0 => 'function.imagick-getimagechanneldepth.php',
    1 => 'Imagick::getImageChannelDepth',
  ),
  82 => 
  array (
    0 => 'function.imagick-getimagechanneldistortion.php',
    1 => 'Imagick::getImageChannelDistortion',
  ),
  83 => 
  array (
    0 => 'function.imagick-getimagechanneldistortions.php',
    1 => 'Imagick::getImageChannelDistortions',
  ),
  84 => 
  array (
    0 => 'function.imagick-getimagechannelextrema.php',
    1 => 'Imagick::getImageChannelExtrema',
  ),
  85 => 
  array (
    0 => 'imagick.getimagechannelkurtosis.php',
    1 => 'Imagick::getImageChannelKurtosis',
  ),
  86 => 
  array (
    0 => 'function.imagick-getimagechannelmean.php',
    1 => 'Imagick::getImageChannelMean',
  ),
  87 => 
  array (
    0 => 'function.imagick-getimagechannelrange.php',
    1 => 'Imagick::getImageChannelRange',
  ),
  88 => 
  array (
    0 => 'function.imagick-getimagechannelstatistics.php',
    1 => 'Imagick::getImageChannelStatistics',
  ),
  89 => 
  array (
    0 => 'function.imagick-getimageclipmask.php',
    1 => 'Imagick::getImageClipMask',
  ),
  90 => 
  array (
    0 => 'function.imagick-getimagecolormapcolor.php',
    1 => 'Imagick::getImageColormapColor',
  ),
  91 => 
  array (
    0 => 'function.imagick-getimagecolors.php',
    1 => 'Imagick::getImageColors',
  ),
  92 => 
  array (
    0 => 'function.imagick-getimagecolorspace.php',
    1 => 'Imagick::getImageColorspace',
  ),
  93 => 
  array (
    0 => 'function.imagick-getimagecompose.php',
    1 => 'Imagick::getImageCompose',
  ),
  94 => 
  array (
    0 => 'function.imagick-getimagecompression.php',
    1 => 'Imagick::getImageCompression',
  ),
  95 => 
  array (
    0 => 'function.imagick-getimagecompressionquality.php',
    1 => 'Imagick::getImageCompressionQuality',
  ),
  96 => 
  array (
    0 => 'function.imagick-getimagedelay.php',
    1 => 'Imagick::getImageDelay',
  ),
  97 => 
  array (
    0 => 'function.imagick-getimagedepth.php',
    1 => 'Imagick::getImageDepth',
  ),
  98 => 
  array (
    0 => 'function.imagick-getimagedispose.php',
    1 => 'Imagick::getImageDispose',
  ),
  99 => 
  array (
    0 => 'function.imagick-getimagedistortion.php',
    1 => 'Imagick::getImageDistortion',
  ),
  100 => 
  array (
    0 => 'function.imagick-getimageextrema.php',
    1 => 'Imagick::getImageExtrema',
  ),
  101 => 
  array (
    0 => 'function.imagick-getimagefilename.php',
    1 => 'Imagick::getImageFilename',
  ),
  102 => 
  array (
    0 => 'function.imagick-getimageformat.php',
    1 => 'Imagick::getImageFormat',
  ),
  103 => 
  array (
    0 => 'function.imagick-getimagegamma.php',
    1 => 'Imagick::getImageGamma',
  ),
  104 => 
  array (
    0 => 'function.imagick-getimagegeometry.php',
    1 => 'Imagick::getImageGeometry',
  ),
  105 => 
  array (
    0 => 'function.imagick-getimagegravity.php',
    1 => 'Imagick::getImageGravity',
  ),
  106 => 
  array (
    0 => 'function.imagick-getimagegreenprimary.php',
    1 => 'Imagick::getImageGreenPrimary',
  ),
  107 => 
  array (
    0 => 'function.imagick-getimageheight.php',
    1 => 'Imagick::getImageHeight',
  ),
  108 => 
  array (
    0 => 'function.imagick-getimagehistogram.php',
    1 => 'Imagick::getImageHistogram',
  ),
  109 => 
  array (
    0 => 'function.imagick-getimageindex.php',
    1 => 'Imagick::getImageIndex',
  ),
  110 => 
  array (
    0 => 'function.imagick-getimageinterlacescheme.php',
    1 => 'Imagick::getImageInterlaceScheme',
  ),
  111 => 
  array (
    0 => 'function.imagick-getimageinterpolatemethod.php',
    1 => 'Imagick::getImageInterpolateMethod',
  ),
  112 => 
  array (
    0 => 'function.imagick-getimageiterations.php',
    1 => 'Imagick::getImageIterations',
  ),
  113 => 
  array (
    0 => 'function.imagick-getimagelength.php',
    1 => 'Imagick::getImageLength',
  ),
  114 => 
  array (
    0 => 'function.imagick-getimagemagicklicense.php',
    1 => 'Imagick::getImageMagickLicense',
  ),
  115 => 
  array (
    0 => 'function.imagick-getimagematte.php',
    1 => 'Imagick::getImageMatte',
  ),
  116 => 
  array (
    0 => 'function.imagick-getimagemattecolor.php',
    1 => 'Imagick::getImageMatteColor',
  ),
  117 => 
  array (
    0 => 'function.imagick-getimageorientation.php',
    1 => 'Imagick::getImageOrientation',
  ),
  118 => 
  array (
    0 => 'function.imagick-getimagepage.php',
    1 => 'Imagick::getImagePage',
  ),
  119 => 
  array (
    0 => 'function.imagick-getimagepixelcolor.php',
    1 => 'Imagick::getImagePixelColor',
  ),
  120 => 
  array (
    0 => 'function.imagick-getimageprofile.php',
    1 => 'Imagick::getImageProfile',
  ),
  121 => 
  array (
    0 => 'function.imagick-getimageprofiles.php',
    1 => 'Imagick::getImageProfiles',
  ),
  122 => 
  array (
    0 => 'function.imagick-getimageproperties.php',
    1 => 'Imagick::getImageProperties',
  ),
  123 => 
  array (
    0 => 'function.imagick-getimageproperty.php',
    1 => 'Imagick::getImageProperty',
  ),
  124 => 
  array (
    0 => 'function.imagick-getimageredprimary.php',
    1 => 'Imagick::getImageRedPrimary',
  ),
  125 => 
  array (
    0 => 'function.imagick-getimageregion.php',
    1 => 'Imagick::getImageRegion',
  ),
  126 => 
  array (
    0 => 'function.imagick-getimagerenderingintent.php',
    1 => 'Imagick::getImageRenderingIntent',
  ),
  127 => 
  array (
    0 => 'function.imagick-getimageresolution.php',
    1 => 'Imagick::getImageResolution',
  ),
  128 => 
  array (
    0 => 'function.imagick-getimagesblob.php',
    1 => 'Imagick::getImagesBlob',
  ),
  129 => 
  array (
    0 => 'function.imagick-getimagescene.php',
    1 => 'Imagick::getImageScene',
  ),
  130 => 
  array (
    0 => 'function.imagick-getimagesignature.php',
    1 => 'Imagick::getImageSignature',
  ),
  131 => 
  array (
    0 => 'function.imagick-getimagesize.php',
    1 => 'Imagick::getImageSize',
  ),
  132 => 
  array (
    0 => 'function.imagick-getimagetickspersecond.php',
    1 => 'Imagick::getImageTicksPerSecond',
  ),
  133 => 
  array (
    0 => 'function.imagick-getimagetotalinkdensity.php',
    1 => 'Imagick::getImageTotalInkDensity',
  ),
  134 => 
  array (
    0 => 'function.imagick-getimagetype.php',
    1 => 'Imagick::getImageType',
  ),
  135 => 
  array (
    0 => 'function.imagick-getimageunits.php',
    1 => 'Imagick::getImageUnits',
  ),
  136 => 
  array (
    0 => 'function.imagick-getimagevirtualpixelmethod.php',
    1 => 'Imagick::getImageVirtualPixelMethod',
  ),
  137 => 
  array (
    0 => 'function.imagick-getimagewhitepoint.php',
    1 => 'Imagick::getImageWhitePoint',
  ),
  138 => 
  array (
    0 => 'function.imagick-getimagewidth.php',
    1 => 'Imagick::getImageWidth',
  ),
  139 => 
  array (
    0 => 'function.imagick-getinterlacescheme.php',
    1 => 'Imagick::getInterlaceScheme',
  ),
  140 => 
  array (
    0 => 'function.imagick-getiteratorindex.php',
    1 => 'Imagick::getIteratorIndex',
  ),
  141 => 
  array (
    0 => 'function.imagick-getnumberimages.php',
    1 => 'Imagick::getNumberImages',
  ),
  142 => 
  array (
    0 => 'function.imagick-getoption.php',
    1 => 'Imagick::getOption',
  ),
  143 => 
  array (
    0 => 'function.imagick-getpackagename.php',
    1 => 'Imagick::getPackageName',
  ),
  144 => 
  array (
    0 => 'function.imagick-getpage.php',
    1 => 'Imagick::getPage',
  ),
  145 => 
  array (
    0 => 'function.imagick-getpixeliterator.php',
    1 => 'Imagick::getPixelIterator',
  ),
  146 => 
  array (
    0 => 'function.imagick-getpixelregioniterator.php',
    1 => 'Imagick::getPixelRegionIterator',
  ),
  147 => 
  array (
    0 => 'function.imagick-getpointsize.php',
    1 => 'Imagick::getPointSize',
  ),
  148 => 
  array (
    0 => 'function.imagick-getquantumdepth.php',
    1 => 'Imagick::getQuantumDepth',
  ),
  149 => 
  array (
    0 => 'function.imagick-getquantumrange.php',
    1 => 'Imagick::getQuantumRange',
  ),
  150 => 
  array (
    0 => 'function.imagick-getreleasedate.php',
    1 => 'Imagick::getReleaseDate',
  ),
  151 => 
  array (
    0 => 'function.imagick-getresource.php',
    1 => 'Imagick::getResource',
  ),
  152 => 
  array (
    0 => 'function.imagick-getresourcelimit.php',
    1 => 'Imagick::getResourceLimit',
  ),
  153 => 
  array (
    0 => 'function.imagick-getsamplingfactors.php',
    1 => 'Imagick::getSamplingFactors',
  ),
  154 => 
  array (
    0 => 'function.imagick-getsize.php',
    1 => 'Imagick::getSize',
  ),
  155 => 
  array (
    0 => 'function.imagick-getsizeoffset.php',
    1 => 'Imagick::getSizeOffset',
  ),
  156 => 
  array (
    0 => 'function.imagick-getversion.php',
    1 => 'Imagick::getVersion',
  ),
  157 => 
  array (
    0 => 'imagick.haldclutimage.php',
    1 => 'Imagick::haldClutImage',
  ),
  158 => 
  array (
    0 => 'function.imagick-hasnextimage.php',
    1 => 'Imagick::hasNextImage',
  ),
  159 => 
  array (
    0 => 'function.imagick-haspreviousimage.php',
    1 => 'Imagick::hasPreviousImage',
  ),
  160 => 
  array (
    0 => 'function.imagick-identifyimage.php',
    1 => 'Imagick::identifyImage',
  ),
  161 => 
  array (
    0 => 'function.imagick-implodeimage.php',
    1 => 'Imagick::implodeImage',
  ),
  162 => 
  array (
    0 => 'imagick.importimagepixels.php',
    1 => 'Imagick::importImagePixels',
  ),
  163 => 
  array (
    0 => 'function.imagick-labelimage.php',
    1 => 'Imagick::labelImage',
  ),
  164 => 
  array (
    0 => 'function.imagick-levelimage.php',
    1 => 'Imagick::levelImage',
  ),
  165 => 
  array (
    0 => 'function.imagick-linearstretchimage.php',
    1 => 'Imagick::linearStretchImage',
  ),
  166 => 
  array (
    0 => 'function.imagick-liquidrescaleimage.php',
    1 => 'Imagick::liquidRescaleImage',
  ),
  167 => 
  array (
    0 => 'function.imagick-magnifyimage.php',
    1 => 'Imagick::magnifyImage',
  ),
  168 => 
  array (
    0 => 'function.imagick-mapimage.php',
    1 => 'Imagick::mapImage',
  ),
  169 => 
  array (
    0 => 'function.imagick-mattefloodfillimage.php',
    1 => 'Imagick::matteFloodfillImage',
  ),
  170 => 
  array (
    0 => 'function.imagick-medianfilterimage.php',
    1 => 'Imagick::medianFilterImage',
  ),
  171 => 
  array (
    0 => 'function.imagick-mergeimagelayers.php',
    1 => 'Imagick::mergeImageLayers',
  ),
  172 => 
  array (
    0 => 'function.imagick-minifyimage.php',
    1 => 'Imagick::minifyImage',
  ),
  173 => 
  array (
    0 => 'function.imagick-modulateimage.php',
    1 => 'Imagick::modulateImage',
  ),
  174 => 
  array (
    0 => 'function.imagick-montageimage.php',
    1 => 'Imagick::montageImage',
  ),
  175 => 
  array (
    0 => 'function.imagick-morphimages.php',
    1 => 'Imagick::morphImages',
  ),
  176 => 
  array (
    0 => 'function.imagick-mosaicimages.php',
    1 => 'Imagick::mosaicImages',
  ),
  177 => 
  array (
    0 => 'function.imagick-motionblurimage.php',
    1 => 'Imagick::motionBlurImage',
  ),
  178 => 
  array (
    0 => 'function.imagick-negateimage.php',
    1 => 'Imagick::negateImage',
  ),
  179 => 
  array (
    0 => 'function.imagick-newimage.php',
    1 => 'Imagick::newImage',
  ),
  180 => 
  array (
    0 => 'function.imagick-newpseudoimage.php',
    1 => 'Imagick::newPseudoImage',
  ),
  181 => 
  array (
    0 => 'function.imagick-nextimage.php',
    1 => 'Imagick::nextImage',
  ),
  182 => 
  array (
    0 => 'function.imagick-normalizeimage.php',
    1 => 'Imagick::normalizeImage',
  ),
  183 => 
  array (
    0 => 'function.imagick-oilpaintimage.php',
    1 => 'Imagick::oilPaintImage',
  ),
  184 => 
  array (
    0 => 'function.imagick-opaquepaintimage.php',
    1 => 'Imagick::opaquePaintImage',
  ),
  185 => 
  array (
    0 => 'function.imagick-optimizeimagelayers.php',
    1 => 'Imagick::optimizeImageLayers',
  ),
  186 => 
  array (
    0 => 'function.imagick-orderedposterizeimage.php',
    1 => 'Imagick::orderedPosterizeImage',
  ),
  187 => 
  array (
    0 => 'function.imagick-paintfloodfillimage.php',
    1 => 'Imagick::paintFloodfillImage',
  ),
  188 => 
  array (
    0 => 'function.imagick-paintopaqueimage.php',
    1 => 'Imagick::paintOpaqueImage',
  ),
  189 => 
  array (
    0 => 'function.imagick-painttransparentimage.php',
    1 => 'Imagick::paintTransparentImage',
  ),
  190 => 
  array (
    0 => 'function.imagick-pingimage.php',
    1 => 'Imagick::pingImage',
  ),
  191 => 
  array (
    0 => 'function.imagick-pingimageblob.php',
    1 => 'Imagick::pingImageBlob',
  ),
  192 => 
  array (
    0 => 'function.imagick-pingimagefile.php',
    1 => 'Imagick::pingImageFile',
  ),
  193 => 
  array (
    0 => 'function.imagick-polaroidimage.php',
    1 => 'Imagick::polaroidImage',
  ),
  194 => 
  array (
    0 => 'function.imagick-posterizeimage.php',
    1 => 'Imagick::posterizeImage',
  ),
  195 => 
  array (
    0 => 'function.imagick-previewimages.php',
    1 => 'Imagick::previewImages',
  ),
  196 => 
  array (
    0 => 'function.imagick-previousimage.php',
    1 => 'Imagick::previousImage',
  ),
  197 => 
  array (
    0 => 'function.imagick-profileimage.php',
    1 => 'Imagick::profileImage',
  ),
  198 => 
  array (
    0 => 'function.imagick-quantizeimage.php',
    1 => 'Imagick::quantizeImage',
  ),
  199 => 
  array (
    0 => 'function.imagick-quantizeimages.php',
    1 => 'Imagick::quantizeImages',
  ),
  200 => 
  array (
    0 => 'function.imagick-queryfontmetrics.php',
    1 => 'Imagick::queryFontMetrics',
  ),
  201 => 
  array (
    0 => 'function.imagick-queryfonts.php',
    1 => 'Imagick::queryFonts',
  ),
  202 => 
  array (
    0 => 'function.imagick-queryformats.php',
    1 => 'Imagick::queryFormats',
  ),
  203 => 
  array (
    0 => 'function.imagick-radialblurimage.php',
    1 => 'Imagick::radialBlurImage',
  ),
  204 => 
  array (
    0 => 'function.imagick-raiseimage.php',
    1 => 'Imagick::raiseImage',
  ),
  205 => 
  array (
    0 => 'function.imagick-randomthresholdimage.php',
    1 => 'Imagick::randomThresholdImage',
  ),
  206 => 
  array (
    0 => 'function.imagick-readimage.php',
    1 => 'Imagick::readImage',
  ),
  207 => 
  array (
    0 => 'function.imagick-readimageblob.php',
    1 => 'Imagick::readImageBlob',
  ),
  208 => 
  array (
    0 => 'function.imagick-readimagefile.php',
    1 => 'Imagick::readImageFile',
  ),
  209 => 
  array (
    0 => 'function.imagick-recolorimage.php',
    1 => 'Imagick::recolorImage',
  ),
  210 => 
  array (
    0 => 'function.imagick-reducenoiseimage.php',
    1 => 'Imagick::reduceNoiseImage',
  ),
  211 => 
  array (
    0 => 'imagick.remapimage.php',
    1 => 'Imagick::remapImage',
  ),
  212 => 
  array (
    0 => 'function.imagick-removeimage.php',
    1 => 'Imagick::removeImage',
  ),
  213 => 
  array (
    0 => 'function.imagick-removeimageprofile.php',
    1 => 'Imagick::removeImageProfile',
  ),
  214 => 
  array (
    0 => 'function.imagick-render.php',
    1 => 'Imagick::render',
  ),
  215 => 
  array (
    0 => 'function.imagick-resampleimage.php',
    1 => 'Imagick::resampleImage',
  ),
  216 => 
  array (
    0 => 'function.imagick-resetimagepage.php',
    1 => 'Imagick::resetImagePage',
  ),
  217 => 
  array (
    0 => 'function.imagick-resizeimage.php',
    1 => 'Imagick::resizeImage',
  ),
  218 => 
  array (
    0 => 'function.imagick-rollimage.php',
    1 => 'Imagick::rollImage',
  ),
  219 => 
  array (
    0 => 'function.imagick-rotateimage.php',
    1 => 'Imagick::rotateImage',
  ),
  220 => 
  array (
    0 => 'function.imagick-roundcorners.php',
    1 => 'Imagick::roundCorners',
  ),
  221 => 
  array (
    0 => 'function.imagick-sampleimage.php',
    1 => 'Imagick::sampleImage',
  ),
  222 => 
  array (
    0 => 'function.imagick-scaleimage.php',
    1 => 'Imagick::scaleImage',
  ),
  223 => 
  array (
    0 => 'imagick.segmentimage.php',
    1 => 'Imagick::segmentImage',
  ),
  224 => 
  array (
    0 => 'function.imagick-separateimagechannel.php',
    1 => 'Imagick::separateImageChannel',
  ),
  225 => 
  array (
    0 => 'function.imagick-sepiatoneimage.php',
    1 => 'Imagick::sepiaToneImage',
  ),
  226 => 
  array (
    0 => 'function.imagick-setbackgroundcolor.php',
    1 => 'Imagick::setBackgroundColor',
  ),
  227 => 
  array (
    0 => 'function.imagick-setcolorspace.php',
    1 => 'Imagick::setColorspace',
  ),
  228 => 
  array (
    0 => 'function.imagick-setcompression.php',
    1 => 'Imagick::setCompression',
  ),
  229 => 
  array (
    0 => 'function.imagick-setcompressionquality.php',
    1 => 'Imagick::setCompressionQuality',
  ),
  230 => 
  array (
    0 => 'function.imagick-setfilename.php',
    1 => 'Imagick::setFilename',
  ),
  231 => 
  array (
    0 => 'function.imagick-setfirstiterator.php',
    1 => 'Imagick::setFirstIterator',
  ),
  232 => 
  array (
    0 => 'function.imagick-setfont.php',
    1 => 'Imagick::setFont',
  ),
  233 => 
  array (
    0 => 'function.imagick-setformat.php',
    1 => 'Imagick::setFormat',
  ),
  234 => 
  array (
    0 => 'function.imagick-setgravity.php',
    1 => 'Imagick::setGravity',
  ),
  235 => 
  array (
    0 => 'function.imagick-setimage.php',
    1 => 'Imagick::setImage',
  ),
  236 => 
  array (
    0 => 'function.imagick-setimagealphachannel.php',
    1 => 'Imagick::setImageAlphaChannel',
  ),
  237 => 
  array (
    0 => 'function.imagick-setimageartifact.php',
    1 => 'Imagick::setImageArtifact',
  ),
  238 => 
  array (
    0 => 'function.imagick-setimagebackgroundcolor.php',
    1 => 'Imagick::setImageBackgroundColor',
  ),
  239 => 
  array (
    0 => 'function.imagick-setimagebias.php',
    1 => 'Imagick::setImageBias',
  ),
  240 => 
  array (
    0 => 'function.imagick-setimageblueprimary.php',
    1 => 'Imagick::setImageBluePrimary',
  ),
  241 => 
  array (
    0 => 'function.imagick-setimagebordercolor.php',
    1 => 'Imagick::setImageBorderColor',
  ),
  242 => 
  array (
    0 => 'function.imagick-setimagechanneldepth.php',
    1 => 'Imagick::setImageChannelDepth',
  ),
  243 => 
  array (
    0 => 'function.imagick-setimageclipmask.php',
    1 => 'Imagick::setImageClipMask',
  ),
  244 => 
  array (
    0 => 'function.imagick-setimagecolormapcolor.php',
    1 => 'Imagick::setImageColormapColor',
  ),
  245 => 
  array (
    0 => 'function.imagick-setimagecolorspace.php',
    1 => 'Imagick::setImageColorspace',
  ),
  246 => 
  array (
    0 => 'function.imagick-setimagecompose.php',
    1 => 'Imagick::setImageCompose',
  ),
  247 => 
  array (
    0 => 'function.imagick-setimagecompression.php',
    1 => 'Imagick::setImageCompression',
  ),
  248 => 
  array (
    0 => 'function.imagick-setimagecompressionquality.php',
    1 => 'Imagick::setImageCompressionQuality',
  ),
  249 => 
  array (
    0 => 'function.imagick-setimagedelay.php',
    1 => 'Imagick::setImageDelay',
  ),
  250 => 
  array (
    0 => 'function.imagick-setimagedepth.php',
    1 => 'Imagick::setImageDepth',
  ),
  251 => 
  array (
    0 => 'function.imagick-setimagedispose.php',
    1 => 'Imagick::setImageDispose',
  ),
  252 => 
  array (
    0 => 'function.imagick-setimageextent.php',
    1 => 'Imagick::setImageExtent',
  ),
  253 => 
  array (
    0 => 'function.imagick-setimagefilename.php',
    1 => 'Imagick::setImageFilename',
  ),
  254 => 
  array (
    0 => 'function.imagick-setimageformat.php',
    1 => 'Imagick::setImageFormat',
  ),
  255 => 
  array (
    0 => 'function.imagick-setimagegamma.php',
    1 => 'Imagick::setImageGamma',
  ),
  256 => 
  array (
    0 => 'function.imagick-setimagegravity.php',
    1 => 'Imagick::setImageGravity',
  ),
  257 => 
  array (
    0 => 'function.imagick-setimagegreenprimary.php',
    1 => 'Imagick::setImageGreenPrimary',
  ),
  258 => 
  array (
    0 => 'function.imagick-setimageindex.php',
    1 => 'Imagick::setImageIndex',
  ),
  259 => 
  array (
    0 => 'function.imagick-setimageinterlacescheme.php',
    1 => 'Imagick::setImageInterlaceScheme',
  ),
  260 => 
  array (
    0 => 'function.imagick-setimageinterpolatemethod.php',
    1 => 'Imagick::setImageInterpolateMethod',
  ),
  261 => 
  array (
    0 => 'function.imagick-setimageiterations.php',
    1 => 'Imagick::setImageIterations',
  ),
  262 => 
  array (
    0 => 'function.imagick-setimagematte.php',
    1 => 'Imagick::setImageMatte',
  ),
  263 => 
  array (
    0 => 'function.imagick-setimagemattecolor.php',
    1 => 'Imagick::setImageMatteColor',
  ),
  264 => 
  array (
    0 => 'function.imagick-setimageopacity.php',
    1 => 'Imagick::setImageOpacity',
  ),
  265 => 
  array (
    0 => 'function.imagick-setimageorientation.php',
    1 => 'Imagick::setImageOrientation',
  ),
  266 => 
  array (
    0 => 'function.imagick-setimagepage.php',
    1 => 'Imagick::setImagePage',
  ),
  267 => 
  array (
    0 => 'function.imagick-setimageprofile.php',
    1 => 'Imagick::setImageProfile',
  ),
  268 => 
  array (
    0 => 'function.imagick-setimageproperty.php',
    1 => 'Imagick::setImageProperty',
  ),
  269 => 
  array (
    0 => 'function.imagick-setimageredprimary.php',
    1 => 'Imagick::setImageRedPrimary',
  ),
  270 => 
  array (
    0 => 'function.imagick-setimagerenderingintent.php',
    1 => 'Imagick::setImageRenderingIntent',
  ),
  271 => 
  array (
    0 => 'function.imagick-setimageresolution.php',
    1 => 'Imagick::setImageResolution',
  ),
  272 => 
  array (
    0 => 'function.imagick-setimagescene.php',
    1 => 'Imagick::setImageScene',
  ),
  273 => 
  array (
    0 => 'function.imagick-setimagetickspersecond.php',
    1 => 'Imagick::setImageTicksPerSecond',
  ),
  274 => 
  array (
    0 => 'function.imagick-setimagetype.php',
    1 => 'Imagick::setImageType',
  ),
  275 => 
  array (
    0 => 'function.imagick-setimageunits.php',
    1 => 'Imagick::setImageUnits',
  ),
  276 => 
  array (
    0 => 'function.imagick-setimagevirtualpixelmethod.php',
    1 => 'Imagick::setImageVirtualPixelMethod',
  ),
  277 => 
  array (
    0 => 'function.imagick-setimagewhitepoint.php',
    1 => 'Imagick::setImageWhitePoint',
  ),
  278 => 
  array (
    0 => 'function.imagick-setinterlacescheme.php',
    1 => 'Imagick::setInterlaceScheme',
  ),
  279 => 
  array (
    0 => 'function.imagick-setiteratorindex.php',
    1 => 'Imagick::setIteratorIndex',
  ),
  280 => 
  array (
    0 => 'function.imagick-setlastiterator.php',
    1 => 'Imagick::setLastIterator',
  ),
  281 => 
  array (
    0 => 'function.imagick-setoption.php',
    1 => 'Imagick::setOption',
  ),
  282 => 
  array (
    0 => 'function.imagick-setpage.php',
    1 => 'Imagick::setPage',
  ),
  283 => 
  array (
    0 => 'function.imagick-setpointsize.php',
    1 => 'Imagick::setPointSize',
  ),
  284 => 
  array (
    0 => 'function.imagick-setresolution.php',
    1 => 'Imagick::setResolution',
  ),
  285 => 
  array (
    0 => 'function.imagick-setresourcelimit.php',
    1 => 'Imagick::setResourceLimit',
  ),
  286 => 
  array (
    0 => 'function.imagick-setsamplingfactors.php',
    1 => 'Imagick::setSamplingFactors',
  ),
  287 => 
  array (
    0 => 'function.imagick-setsize.php',
    1 => 'Imagick::setSize',
  ),
  288 => 
  array (
    0 => 'function.imagick-setsizeoffset.php',
    1 => 'Imagick::setSizeOffset',
  ),
  289 => 
  array (
    0 => 'function.imagick-settype.php',
    1 => 'Imagick::setType',
  ),
  290 => 
  array (
    0 => 'function.imagick-shadeimage.php',
    1 => 'Imagick::shadeImage',
  ),
  291 => 
  array (
    0 => 'function.imagick-shadowimage.php',
    1 => 'Imagick::shadowImage',
  ),
  292 => 
  array (
    0 => 'function.imagick-sharpenimage.php',
    1 => 'Imagick::sharpenImage',
  ),
  293 => 
  array (
    0 => 'function.imagick-shaveimage.php',
    1 => 'Imagick::shaveImage',
  ),
  294 => 
  array (
    0 => 'function.imagick-shearimage.php',
    1 => 'Imagick::shearImage',
  ),
  295 => 
  array (
    0 => 'function.imagick-sigmoidalcontrastimage.php',
    1 => 'Imagick::sigmoidalContrastImage',
  ),
  296 => 
  array (
    0 => 'function.imagick-sketchimage.php',
    1 => 'Imagick::sketchImage',
  ),
  297 => 
  array (
    0 => 'function.imagick-solarizeimage.php',
    1 => 'Imagick::solarizeImage',
  ),
  298 => 
  array (
    0 => 'imagick.sparsecolorimage.php',
    1 => 'Imagick::sparseColorImage',
  ),
  299 => 
  array (
    0 => 'function.imagick-spliceimage.php',
    1 => 'Imagick::spliceImage',
  ),
  300 => 
  array (
    0 => 'function.imagick-spreadimage.php',
    1 => 'Imagick::spreadImage',
  ),
  301 => 
  array (
    0 => 'function.imagick-steganoimage.php',
    1 => 'Imagick::steganoImage',
  ),
  302 => 
  array (
    0 => 'function.imagick-stereoimage.php',
    1 => 'Imagick::stereoImage',
  ),
  303 => 
  array (
    0 => 'function.imagick-stripimage.php',
    1 => 'Imagick::stripImage',
  ),
  304 => 
  array (
    0 => 'function.imagick-swirlimage.php',
    1 => 'Imagick::swirlImage',
  ),
  305 => 
  array (
    0 => 'function.imagick-textureimage.php',
    1 => 'Imagick::textureImage',
  ),
  306 => 
  array (
    0 => 'function.imagick-thresholdimage.php',
    1 => 'Imagick::thresholdImage',
  ),
  307 => 
  array (
    0 => 'function.imagick-thumbnailimage.php',
    1 => 'Imagick::thumbnailImage',
  ),
  308 => 
  array (
    0 => 'function.imagick-tintimage.php',
    1 => 'Imagick::tintImage',
  ),
  309 => 
  array (
    0 => 'function.imagick-transformimage.php',
    1 => 'Imagick::transformImage',
  ),
  310 => 
  array (
    0 => 'function.imagick-transparentpaintimage.php',
    1 => 'Imagick::transparentPaintImage',
  ),
  311 => 
  array (
    0 => 'function.imagick-transposeimage.php',
    1 => 'Imagick::transposeImage',
  ),
  312 => 
  array (
    0 => 'function.imagick-transverseimage.php',
    1 => 'Imagick::transverseImage',
  ),
  313 => 
  array (
    0 => 'function.imagick-trimimage.php',
    1 => 'Imagick::trimImage',
  ),
  314 => 
  array (
    0 => 'function.imagick-uniqueimagecolors.php',
    1 => 'Imagick::uniqueImageColors',
  ),
  315 => 
  array (
    0 => 'function.imagick-unsharpmaskimage.php',
    1 => 'Imagick::unsharpMaskImage',
  ),
  316 => 
  array (
    0 => 'function.imagick-valid.php',
    1 => 'Imagick::valid',
  ),
  317 => 
  array (
    0 => 'function.imagick-vignetteimage.php',
    1 => 'Imagick::vignetteImage',
  ),
  318 => 
  array (
    0 => 'function.imagick-waveimage.php',
    1 => 'Imagick::waveImage',
  ),
  319 => 
  array (
    0 => 'function.imagick-whitethresholdimage.php',
    1 => 'Imagick::whiteThresholdImage',
  ),
  320 => 
  array (
    0 => 'function.imagick-writeimage.php',
    1 => 'Imagick::writeImage',
  ),
  321 => 
  array (
    0 => 'function.imagick-writeimagefile.php',
    1 => 'Imagick::writeImageFile',
  ),
  322 => 
  array (
    0 => 'function.imagick-writeimages.php',
    1 => 'Imagick::writeImages',
  ),
  323 => 
  array (
    0 => 'function.imagick-writeimagesfile.php',
    1 => 'Imagick::writeImagesFile',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.imagick.php',
    1 => 'ImageMagick',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);