<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairosurface.construct.php',
    1 => 'CairoSurface::__construct',
  ),
  1 => 
  array (
    0 => 'cairosurface.copypage.php',
    1 => 'CairoSurface::copyPage',
  ),
  2 => 
  array (
    0 => 'cairosurface.createsimilar.php',
    1 => 'CairoSurface::createSimilar',
  ),
  3 => 
  array (
    0 => 'cairosurface.finish.php',
    1 => 'CairoSurface::finish',
  ),
  4 => 
  array (
    0 => 'cairosurface.flush.php',
    1 => 'CairoSurface::flush',
  ),
  5 => 
  array (
    0 => 'cairosurface.getcontent.php',
    1 => 'CairoSurface::getContent',
  ),
  6 => 
  array (
    0 => 'cairosurface.getdeviceoffset.php',
    1 => 'CairoSurface::getDeviceOffset',
  ),
  7 => 
  array (
    0 => 'cairosurface.getfontoptions.php',
    1 => 'CairoSurface::getFontOptions',
  ),
  8 => 
  array (
    0 => 'cairosurface.gettype.php',
    1 => 'CairoSurface::getType',
  ),
  9 => 
  array (
    0 => 'cairosurface.markdirty.php',
    1 => 'CairoSurface::markDirty',
  ),
  10 => 
  array (
    0 => 'cairosurface.markdirtyrectangle.php',
    1 => 'CairoSurface::markDirtyRectangle',
  ),
  11 => 
  array (
    0 => 'cairosurface.setdeviceoffset.php',
    1 => 'CairoSurface::setDeviceOffset',
  ),
  12 => 
  array (
    0 => 'cairosurface.setfallbackresolution.php',
    1 => 'CairoSurface::setFallbackResolution',
  ),
  13 => 
  array (
    0 => 'cairosurface.showpage.php',
    1 => 'CairoSurface::showPage',
  ),
  14 => 
  array (
    0 => 'cairosurface.status.php',
    1 => 'CairoSurface::status',
  ),
  15 => 
  array (
    0 => 'cairosurface.writetopng.php',
    1 => 'CairoSurface::writeToPng',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);