<?php
$TOC = array (
  0 => 
  array (
    0 => 'mongoid.construct.php',
    1 => 'MongoId::__construct',
  ),
  1 => 
  array (
    0 => 'mongoid.gethostname.php',
    1 => 'MongoId::getHostname',
  ),
  2 => 
  array (
    0 => 'mongoid.getinc.php',
    1 => 'MongoId::getInc',
  ),
  3 => 
  array (
    0 => 'mongoid.getpid.php',
    1 => 'MongoId::getPID',
  ),
  4 => 
  array (
    0 => 'mongoid.gettimestamp.php',
    1 => 'MongoId::getTimestamp',
  ),
  5 => 
  array (
    0 => 'mongoid.setstate.php',
    1 => 'MongoId::__set_state',
  ),
  6 => 
  array (
    0 => 'mongoid.tostring.php',
    1 => 'MongoId::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'mongo.types.php',
    1 => 'Types',
  ),
  1 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  2 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  3 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  4 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  5 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);