<?php
$TOC = array (
  0 => 
  array (
    0 => 'streamwrapper.construct.php',
    1 => 'streamWrapper::__construct',
  ),
  1 => 
  array (
    0 => 'streamwrapper.dir-closedir.php',
    1 => 'streamWrapper::dir_closedir',
  ),
  2 => 
  array (
    0 => 'streamwrapper.dir-opendir.php',
    1 => 'streamWrapper::dir_opendir',
  ),
  3 => 
  array (
    0 => 'streamwrapper.dir-readdir.php',
    1 => 'streamWrapper::dir_readdir',
  ),
  4 => 
  array (
    0 => 'streamwrapper.dir-rewinddir.php',
    1 => 'streamWrapper::dir_rewinddir',
  ),
  5 => 
  array (
    0 => 'streamwrapper.mkdir.php',
    1 => 'streamWrapper::mkdir',
  ),
  6 => 
  array (
    0 => 'streamwrapper.rename.php',
    1 => 'streamWrapper::rename',
  ),
  7 => 
  array (
    0 => 'streamwrapper.rmdir.php',
    1 => 'streamWrapper::rmdir',
  ),
  8 => 
  array (
    0 => 'streamwrapper.stream-cast.php',
    1 => 'streamWrapper::stream_cast',
  ),
  9 => 
  array (
    0 => 'streamwrapper.stream-close.php',
    1 => 'streamWrapper::stream_close',
  ),
  10 => 
  array (
    0 => 'streamwrapper.stream-eof.php',
    1 => 'streamWrapper::stream_eof',
  ),
  11 => 
  array (
    0 => 'streamwrapper.stream-flush.php',
    1 => 'streamWrapper::stream_flush',
  ),
  12 => 
  array (
    0 => 'streamwrapper.stream-lock.php',
    1 => 'streamWrapper::stream_lock',
  ),
  13 => 
  array (
    0 => 'streamwrapper.stream-open.php',
    1 => 'streamWrapper::stream_open',
  ),
  14 => 
  array (
    0 => 'streamwrapper.stream-read.php',
    1 => 'streamWrapper::stream_read',
  ),
  15 => 
  array (
    0 => 'streamwrapper.stream-seek.php',
    1 => 'streamWrapper::stream_seek',
  ),
  16 => 
  array (
    0 => 'streamwrapper.stream-set-option.php',
    1 => 'streamWrapper::stream_set_option',
  ),
  17 => 
  array (
    0 => 'streamwrapper.stream-stat.php',
    1 => 'streamWrapper::stream_stat',
  ),
  18 => 
  array (
    0 => 'streamwrapper.stream-tell.php',
    1 => 'streamWrapper::stream_tell',
  ),
  19 => 
  array (
    0 => 'streamwrapper.stream-write.php',
    1 => 'streamWrapper::stream_write',
  ),
  20 => 
  array (
    0 => 'streamwrapper.unlink.php',
    1 => 'streamWrapper::unlink',
  ),
  21 => 
  array (
    0 => 'streamwrapper.url-stat.php',
    1 => 'streamWrapper::url_stat',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.stream.php',
    1 => 'Streams',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);