<?php
$TOC = array (
  0 => 
  array (
    0 => 'amqpqueue.ack.php',
    1 => 'AMQPQueue::ack',
  ),
  1 => 
  array (
    0 => 'amqpqueue.bind.php',
    1 => 'AMQPQueue::bind',
  ),
  2 => 
  array (
    0 => 'amqpqueue.cancel.php',
    1 => 'AMQPQueue::cancel',
  ),
  3 => 
  array (
    0 => 'amqpqueue.construct.php',
    1 => 'AMQPQueue::__construct',
  ),
  4 => 
  array (
    0 => 'amqpqueue.consume.php',
    1 => 'AMQPQueue::consume',
  ),
  5 => 
  array (
    0 => 'amqpqueue.declare.php',
    1 => 'AMQPQueue::declare',
  ),
  6 => 
  array (
    0 => 'amqpqueue.delete.php',
    1 => 'AMQPQueue::delete',
  ),
  7 => 
  array (
    0 => 'amqpqueue.get.php',
    1 => 'AMQPQueue::get',
  ),
  8 => 
  array (
    0 => 'amqpqueue.purge.php',
    1 => 'AMQPQueue::purge',
  ),
  9 => 
  array (
    0 => 'amqpqueue.unbind.php',
    1 => 'AMQPQueue::unbind',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.amqp.php',
    1 => 'AMQP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);