<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairocontext.appendpath.php',
    1 => 'CairoContext::appendPath',
  ),
  1 => 
  array (
    0 => 'cairocontext.arc.php',
    1 => 'CairoContext::arc',
  ),
  2 => 
  array (
    0 => 'cairocontext.arcnegative.php',
    1 => 'CairoContext::arcNegative',
  ),
  3 => 
  array (
    0 => 'cairocontext.clip.php',
    1 => 'CairoContext::clip',
  ),
  4 => 
  array (
    0 => 'cairocontext.clipextents.php',
    1 => 'CairoContext::clipExtents',
  ),
  5 => 
  array (
    0 => 'cairocontext.clippreserve.php',
    1 => 'CairoContext::clipPreserve',
  ),
  6 => 
  array (
    0 => 'cairocontext.cliprectanglelist.php',
    1 => 'CairoContext::clipRectangleList',
  ),
  7 => 
  array (
    0 => 'cairocontext.closepath.php',
    1 => 'CairoContext::closePath',
  ),
  8 => 
  array (
    0 => 'cairocontext.construct.php',
    1 => 'CairoContext::__construct',
  ),
  9 => 
  array (
    0 => 'cairocontext.copypage.php',
    1 => 'CairoContext::copyPage',
  ),
  10 => 
  array (
    0 => 'cairocontext.copypath.php',
    1 => 'CairoContext::copyPath',
  ),
  11 => 
  array (
    0 => 'cairocontext.copypathflat.php',
    1 => 'CairoContext::copyPathFlat',
  ),
  12 => 
  array (
    0 => 'cairocontext.curveto.php',
    1 => 'CairoContext::curveTo',
  ),
  13 => 
  array (
    0 => 'cairocontext.devicetouser.php',
    1 => 'CairoContext::deviceToUser',
  ),
  14 => 
  array (
    0 => 'cairocontext.devicetouserdistance.php',
    1 => 'CairoContext::deviceToUserDistance',
  ),
  15 => 
  array (
    0 => 'cairocontext.fill.php',
    1 => 'CairoContext::fill',
  ),
  16 => 
  array (
    0 => 'cairocontext.fillextents.php',
    1 => 'CairoContext::fillExtents',
  ),
  17 => 
  array (
    0 => 'cairocontext.fillpreserve.php',
    1 => 'CairoContext::fillPreserve',
  ),
  18 => 
  array (
    0 => 'cairocontext.fontextents.php',
    1 => 'CairoContext::fontExtents',
  ),
  19 => 
  array (
    0 => 'cairocontext.getantialias.php',
    1 => 'CairoContext::getAntialias',
  ),
  20 => 
  array (
    0 => 'cairocontext.getcurrentpoint.php',
    1 => 'CairoContext::getCurrentPoint',
  ),
  21 => 
  array (
    0 => 'cairocontext.getdash.php',
    1 => 'CairoContext::getDash',
  ),
  22 => 
  array (
    0 => 'cairocontext.getdashcount.php',
    1 => 'CairoContext::getDashCount',
  ),
  23 => 
  array (
    0 => 'cairocontext.getfillrule.php',
    1 => 'CairoContext::getFillRule',
  ),
  24 => 
  array (
    0 => 'cairocontext.getfontface.php',
    1 => 'CairoContext::getFontFace',
  ),
  25 => 
  array (
    0 => 'cairocontext.getfontmatrix.php',
    1 => 'CairoContext::getFontMatrix',
  ),
  26 => 
  array (
    0 => 'cairocontext.getfontoptions.php',
    1 => 'CairoContext::getFontOptions',
  ),
  27 => 
  array (
    0 => 'cairocontext.getgrouptarget.php',
    1 => 'CairoContext::getGroupTarget',
  ),
  28 => 
  array (
    0 => 'cairocontext.getlinecap.php',
    1 => 'CairoContext::getLineCap',
  ),
  29 => 
  array (
    0 => 'cairocontext.getlinejoin.php',
    1 => 'CairoContext::getLineJoin',
  ),
  30 => 
  array (
    0 => 'cairocontext.getlinewidth.php',
    1 => 'CairoContext::getLineWidth',
  ),
  31 => 
  array (
    0 => 'cairocontext.getmatrix.php',
    1 => 'CairoContext::getMatrix',
  ),
  32 => 
  array (
    0 => 'cairocontext.getmiterlimit.php',
    1 => 'CairoContext::getMiterLimit',
  ),
  33 => 
  array (
    0 => 'cairocontext.getoperator.php',
    1 => 'CairoContext::getOperator',
  ),
  34 => 
  array (
    0 => 'cairocontext.getscaledfont.php',
    1 => 'CairoContext::getScaledFont',
  ),
  35 => 
  array (
    0 => 'cairocontext.getsource.php',
    1 => 'CairoContext::getSource',
  ),
  36 => 
  array (
    0 => 'cairocontext.gettarget.php',
    1 => 'CairoContext::getTarget',
  ),
  37 => 
  array (
    0 => 'cairocontext.gettolerance.php',
    1 => 'CairoContext::getTolerance',
  ),
  38 => 
  array (
    0 => 'cairocontext.glyphpath.php',
    1 => 'CairoContext::glyphPath',
  ),
  39 => 
  array (
    0 => 'cairocontext.hascurrentpoint.php',
    1 => 'CairoContext::hasCurrentPoint',
  ),
  40 => 
  array (
    0 => 'cairocontext.identitymatrix.php',
    1 => 'CairoContext::identityMatrix',
  ),
  41 => 
  array (
    0 => 'cairocontext.infill.php',
    1 => 'CairoContext::inFill',
  ),
  42 => 
  array (
    0 => 'cairocontext.instroke.php',
    1 => 'CairoContext::inStroke',
  ),
  43 => 
  array (
    0 => 'cairocontext.lineto.php',
    1 => 'CairoContext::lineTo',
  ),
  44 => 
  array (
    0 => 'cairocontext.mask.php',
    1 => 'CairoContext::mask',
  ),
  45 => 
  array (
    0 => 'cairocontext.masksurface.php',
    1 => 'CairoContext::maskSurface',
  ),
  46 => 
  array (
    0 => 'cairocontext.moveto.php',
    1 => 'CairoContext::moveTo',
  ),
  47 => 
  array (
    0 => 'cairocontext.newpath.php',
    1 => 'CairoContext::newPath',
  ),
  48 => 
  array (
    0 => 'cairocontext.newsubpath.php',
    1 => 'CairoContext::newSubPath',
  ),
  49 => 
  array (
    0 => 'cairocontext.paint.php',
    1 => 'CairoContext::paint',
  ),
  50 => 
  array (
    0 => 'cairocontext.paintwithalpha.php',
    1 => 'CairoContext::paintWithAlpha',
  ),
  51 => 
  array (
    0 => 'cairocontext.pathextents.php',
    1 => 'CairoContext::pathExtents',
  ),
  52 => 
  array (
    0 => 'cairocontext.popgroup.php',
    1 => 'CairoContext::popGroup',
  ),
  53 => 
  array (
    0 => 'cairocontext.popgrouptosource.php',
    1 => 'CairoContext::popGroupToSource',
  ),
  54 => 
  array (
    0 => 'cairocontext.pushgroup.php',
    1 => 'CairoContext::pushGroup',
  ),
  55 => 
  array (
    0 => 'cairocontext.pushgroupwithcontent.php',
    1 => 'CairoContext::pushGroupWithContent',
  ),
  56 => 
  array (
    0 => 'cairocontext.rectangle.php',
    1 => 'CairoContext::rectangle',
  ),
  57 => 
  array (
    0 => 'cairocontext.relcurveto.php',
    1 => 'CairoContext::relCurveTo',
  ),
  58 => 
  array (
    0 => 'cairocontext.rellineto.php',
    1 => 'CairoContext::relLineTo',
  ),
  59 => 
  array (
    0 => 'cairocontext.relmoveto.php',
    1 => 'CairoContext::relMoveTo',
  ),
  60 => 
  array (
    0 => 'cairocontext.resetclip.php',
    1 => 'CairoContext::resetClip',
  ),
  61 => 
  array (
    0 => 'cairocontext.restore.php',
    1 => 'CairoContext::restore',
  ),
  62 => 
  array (
    0 => 'cairocontext.rotate.php',
    1 => 'CairoContext::rotate',
  ),
  63 => 
  array (
    0 => 'cairocontext.save.php',
    1 => 'CairoContext::save',
  ),
  64 => 
  array (
    0 => 'cairocontext.scale.php',
    1 => 'CairoContext::scale',
  ),
  65 => 
  array (
    0 => 'cairocontext.selectfontface.php',
    1 => 'CairoContext::selectFontFace',
  ),
  66 => 
  array (
    0 => 'cairocontext.setantialias.php',
    1 => 'CairoContext::setAntialias',
  ),
  67 => 
  array (
    0 => 'cairocontext.setdash.php',
    1 => 'CairoContext::setDash',
  ),
  68 => 
  array (
    0 => 'cairocontext.setfillrule.php',
    1 => 'CairoContext::setFillRule',
  ),
  69 => 
  array (
    0 => 'cairocontext.setfontface.php',
    1 => 'CairoContext::setFontFace',
  ),
  70 => 
  array (
    0 => 'cairocontext.setfontmatrix.php',
    1 => 'CairoContext::setFontMatrix',
  ),
  71 => 
  array (
    0 => 'cairocontext.setfontoptions.php',
    1 => 'CairoContext::setFontOptions',
  ),
  72 => 
  array (
    0 => 'cairocontext.setfontsize.php',
    1 => 'CairoContext::setFontSize',
  ),
  73 => 
  array (
    0 => 'cairocontext.setlinecap.php',
    1 => 'CairoContext::setLineCap',
  ),
  74 => 
  array (
    0 => 'cairocontext.setlinejoin.php',
    1 => 'CairoContext::setLineJoin',
  ),
  75 => 
  array (
    0 => 'cairocontext.setlinewidth.php',
    1 => 'CairoContext::setLineWidth',
  ),
  76 => 
  array (
    0 => 'cairocontext.setmatrix.php',
    1 => 'CairoContext::setMatrix',
  ),
  77 => 
  array (
    0 => 'cairocontext.setmiterlimit.php',
    1 => 'CairoContext::setMiterLimit',
  ),
  78 => 
  array (
    0 => 'cairocontext.setoperator.php',
    1 => 'CairoContext::setOperator',
  ),
  79 => 
  array (
    0 => 'cairocontext.setscaledfont.php',
    1 => 'CairoContext::setScaledFont',
  ),
  80 => 
  array (
    0 => 'cairocontext.setsource.php',
    1 => 'CairoContext::setSource',
  ),
  81 => 
  array (
    0 => 'cairocontext.setsourcergb.php',
    1 => 'CairoContext::setSourceRGB',
  ),
  82 => 
  array (
    0 => 'cairocontext.setsourcergba.php',
    1 => 'CairoContext::setSourceRGBA',
  ),
  83 => 
  array (
    0 => 'cairocontext.setsourcesurface.php',
    1 => 'CairoContext::setSourceSurface',
  ),
  84 => 
  array (
    0 => 'cairocontext.settolerance.php',
    1 => 'CairoContext::setTolerance',
  ),
  85 => 
  array (
    0 => 'cairocontext.showpage.php',
    1 => 'CairoContext::showPage',
  ),
  86 => 
  array (
    0 => 'cairocontext.showtext.php',
    1 => 'CairoContext::showText',
  ),
  87 => 
  array (
    0 => 'cairocontext.status.php',
    1 => 'CairoContext::status',
  ),
  88 => 
  array (
    0 => 'cairocontext.stroke.php',
    1 => 'CairoContext::stroke',
  ),
  89 => 
  array (
    0 => 'cairocontext.strokeextents.php',
    1 => 'CairoContext::strokeExtents',
  ),
  90 => 
  array (
    0 => 'cairocontext.strokepreserve.php',
    1 => 'CairoContext::strokePreserve',
  ),
  91 => 
  array (
    0 => 'cairocontext.textextents.php',
    1 => 'CairoContext::textExtents',
  ),
  92 => 
  array (
    0 => 'cairocontext.textpath.php',
    1 => 'CairoContext::textPath',
  ),
  93 => 
  array (
    0 => 'cairocontext.transform.php',
    1 => 'CairoContext::transform',
  ),
  94 => 
  array (
    0 => 'cairocontext.translate.php',
    1 => 'CairoContext::translate',
  ),
  95 => 
  array (
    0 => 'cairocontext.usertodevice.php',
    1 => 'CairoContext::userToDevice',
  ),
  96 => 
  array (
    0 => 'cairocontext.usertodevicedistance.php',
    1 => 'CairoContext::userToDeviceDistance',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);