<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swffontchar.addchars.php',
    1 => 'SWFFontChar-&gt;addChars',
  ),
  1 => 
  array (
    0 => 'function.swffontchar.addutf8chars.php',
    1 => 'SWFFontChar-&gt;addUTF8Chars',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);