<?php
$TOC = array (
  0 => 
  array (
    0 => 'arrayobject.append.php',
    1 => 'ArrayObject::append',
  ),
  1 => 
  array (
    0 => 'arrayobject.asort.php',
    1 => 'ArrayObject::asort',
  ),
  2 => 
  array (
    0 => 'arrayobject.construct.php',
    1 => 'ArrayObject::__construct',
  ),
  3 => 
  array (
    0 => 'arrayobject.count.php',
    1 => 'ArrayObject::count',
  ),
  4 => 
  array (
    0 => 'arrayobject.exchangearray.php',
    1 => 'ArrayObject::exchangeArray',
  ),
  5 => 
  array (
    0 => 'arrayobject.getarraycopy.php',
    1 => 'ArrayObject::getArrayCopy',
  ),
  6 => 
  array (
    0 => 'arrayobject.getflags.php',
    1 => 'ArrayObject::getFlags',
  ),
  7 => 
  array (
    0 => 'arrayobject.getiterator.php',
    1 => 'ArrayObject::getIterator',
  ),
  8 => 
  array (
    0 => 'arrayobject.getiteratorclass.php',
    1 => 'ArrayObject::getIteratorClass',
  ),
  9 => 
  array (
    0 => 'arrayobject.ksort.php',
    1 => 'ArrayObject::ksort',
  ),
  10 => 
  array (
    0 => 'arrayobject.natcasesort.php',
    1 => 'ArrayObject::natcasesort',
  ),
  11 => 
  array (
    0 => 'arrayobject.natsort.php',
    1 => 'ArrayObject::natsort',
  ),
  12 => 
  array (
    0 => 'arrayobject.offsetexists.php',
    1 => 'ArrayObject::offsetExists',
  ),
  13 => 
  array (
    0 => 'arrayobject.offsetget.php',
    1 => 'ArrayObject::offsetGet',
  ),
  14 => 
  array (
    0 => 'arrayobject.offsetset.php',
    1 => 'ArrayObject::offsetSet',
  ),
  15 => 
  array (
    0 => 'arrayobject.offsetunset.php',
    1 => 'ArrayObject::offsetUnset',
  ),
  16 => 
  array (
    0 => 'arrayobject.serialize.php',
    1 => 'ArrayObject::serialize',
  ),
  17 => 
  array (
    0 => 'arrayobject.setflags.php',
    1 => 'ArrayObject::setFlags',
  ),
  18 => 
  array (
    0 => 'arrayobject.setiteratorclass.php',
    1 => 'ArrayObject::setIteratorClass',
  ),
  19 => 
  array (
    0 => 'arrayobject.uasort.php',
    1 => 'ArrayObject::uasort',
  ),
  20 => 
  array (
    0 => 'arrayobject.uksort.php',
    1 => 'ArrayObject::uksort',
  ),
  21 => 
  array (
    0 => 'arrayobject.unserialize.php',
    1 => 'ArrayObject::unserialize',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.misc.php',
    1 => 'Miscellaneous Classes and Interfaces',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);