<?php
$TOC = array (
  0 => 
  array (
    0 => 'mysqli-driver.embedded-server-end.php',
    1 => 'mysqli_driver::embedded_server_end',
  ),
  1 => 
  array (
    0 => 'mysqli-driver.embedded-server-start.php',
    1 => 'mysqli_driver::embedded_server_start',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mysqli.php',
    1 => 'Mysqli',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);