<?php
$TOC = array (
  0 => 
  array (
    0 => 'domnode.appendchild.php',
    1 => 'DOMNode::appendChild',
  ),
  1 => 
  array (
    0 => 'domnode.clonenode.php',
    1 => 'DOMNode::cloneNode',
  ),
  2 => 
  array (
    0 => 'domnode.getlineno.php',
    1 => 'DOMNode::getLineNo',
  ),
  3 => 
  array (
    0 => 'domnode.hasattributes.php',
    1 => 'DOMNode::hasAttributes',
  ),
  4 => 
  array (
    0 => 'domnode.haschildnodes.php',
    1 => 'DOMNode::hasChildNodes',
  ),
  5 => 
  array (
    0 => 'domnode.insertbefore.php',
    1 => 'DOMNode::insertBefore',
  ),
  6 => 
  array (
    0 => 'domnode.isdefaultnamespace.php',
    1 => 'DOMNode::isDefaultNamespace',
  ),
  7 => 
  array (
    0 => 'domnode.issamenode.php',
    1 => 'DOMNode::isSameNode',
  ),
  8 => 
  array (
    0 => 'domnode.issupported.php',
    1 => 'DOMNode::isSupported',
  ),
  9 => 
  array (
    0 => 'domnode.lookupnamespaceuri.php',
    1 => 'DOMNode::lookupNamespaceURI',
  ),
  10 => 
  array (
    0 => 'domnode.lookupprefix.php',
    1 => 'DOMNode::lookupPrefix',
  ),
  11 => 
  array (
    0 => 'domnode.normalize.php',
    1 => 'DOMNode::normalize',
  ),
  12 => 
  array (
    0 => 'domnode.removechild.php',
    1 => 'DOMNode::removeChild',
  ),
  13 => 
  array (
    0 => 'domnode.replacechild.php',
    1 => 'DOMNode::replaceChild',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dom.php',
    1 => 'DOM',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);