<?php
$TOC = array (
  0 => 
  array (
    0 => 'domnamednodemap.getnameditem.php',
    1 => 'DOMNamedNodeMap::getNamedItem',
  ),
  1 => 
  array (
    0 => 'domnamednodemap.getnameditemns.php',
    1 => 'DOMNamedNodeMap::getNamedItemNS',
  ),
  2 => 
  array (
    0 => 'domnamednodemap.item.php',
    1 => 'DOMNamedNodeMap::item',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dom.php',
    1 => 'DOM',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);