<?php
$TOC = array (
  0 => 
  array (
    0 => 'domelement.construct.php',
    1 => 'DOMElement::__construct',
  ),
  1 => 
  array (
    0 => 'domelement.getattribute.php',
    1 => 'DOMElement::getAttribute',
  ),
  2 => 
  array (
    0 => 'domelement.getattributenode.php',
    1 => 'DOMElement::getAttributeNode',
  ),
  3 => 
  array (
    0 => 'domelement.getattributenodens.php',
    1 => 'DOMElement::getAttributeNodeNS',
  ),
  4 => 
  array (
    0 => 'domelement.getattributens.php',
    1 => 'DOMElement::getAttributeNS',
  ),
  5 => 
  array (
    0 => 'domelement.getelementsbytagname.php',
    1 => 'DOMElement::getElementsByTagName',
  ),
  6 => 
  array (
    0 => 'domelement.getelementsbytagnamens.php',
    1 => 'DOMElement::getElementsByTagNameNS',
  ),
  7 => 
  array (
    0 => 'domelement.hasattribute.php',
    1 => 'DOMElement::hasAttribute',
  ),
  8 => 
  array (
    0 => 'domelement.hasattributens.php',
    1 => 'DOMElement::hasAttributeNS',
  ),
  9 => 
  array (
    0 => 'domelement.removeattribute.php',
    1 => 'DOMElement::removeAttribute',
  ),
  10 => 
  array (
    0 => 'domelement.removeattributenode.php',
    1 => 'DOMElement::removeAttributeNode',
  ),
  11 => 
  array (
    0 => 'domelement.removeattributens.php',
    1 => 'DOMElement::removeAttributeNS',
  ),
  12 => 
  array (
    0 => 'domelement.setattribute.php',
    1 => 'DOMElement::setAttribute',
  ),
  13 => 
  array (
    0 => 'domelement.setattributenode.php',
    1 => 'DOMElement::setAttributeNode',
  ),
  14 => 
  array (
    0 => 'domelement.setattributenodens.php',
    1 => 'DOMElement::setAttributeNodeNS',
  ),
  15 => 
  array (
    0 => 'domelement.setattributens.php',
    1 => 'DOMElement::setAttributeNS',
  ),
  16 => 
  array (
    0 => 'domelement.setidattribute.php',
    1 => 'DOMElement::setIdAttribute',
  ),
  17 => 
  array (
    0 => 'domelement.setidattributenode.php',
    1 => 'DOMElement::setIdAttributeNode',
  ),
  18 => 
  array (
    0 => 'domelement.setidattributens.php',
    1 => 'DOMElement::setIdAttributeNS',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dom.php',
    1 => 'DOM',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);