<?php
$TOC = array (
  0 => 
  array (
    0 => 'sqlite3result.columnname.php',
    1 => 'SQLite3Result::columnName',
  ),
  1 => 
  array (
    0 => 'sqlite3result.columntype.php',
    1 => 'SQLite3Result::columnType',
  ),
  2 => 
  array (
    0 => 'sqlite3result.fetcharray.php',
    1 => 'SQLite3Result::fetchArray',
  ),
  3 => 
  array (
    0 => 'sqlite3result.finalize.php',
    1 => 'SQLite3Result::finalize',
  ),
  4 => 
  array (
    0 => 'sqlite3result.numcolumns.php',
    1 => 'SQLite3Result::numColumns',
  ),
  5 => 
  array (
    0 => 'sqlite3Result.reset.php',
    1 => 'SQLite3Result::reset',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sqlite3.php',
    1 => 'SQLite3',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);