<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.haruimage-getbitspercomponent.php',
    1 => 'HaruImage::getBitsPerComponent',
  ),
  1 => 
  array (
    0 => 'function.haruimage-getcolorspace.php',
    1 => 'HaruImage::getColorSpace',
  ),
  2 => 
  array (
    0 => 'function.haruimage-getheight.php',
    1 => 'HaruImage::getHeight',
  ),
  3 => 
  array (
    0 => 'function.haruimage-getsize.php',
    1 => 'HaruImage::getSize',
  ),
  4 => 
  array (
    0 => 'function.haruimage-getwidth.php',
    1 => 'HaruImage::getWidth',
  ),
  5 => 
  array (
    0 => 'function.haruimage-setcolormask.php',
    1 => 'HaruImage::setColorMask',
  ),
  6 => 
  array (
    0 => 'function.haruimage-setmaskimage.php',
    1 => 'HaruImage::setMaskImage',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.haru.php',
    1 => 'haru',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);