<?php
$TOC = array (
  0 => 
  array (
    0 => 'rararchive.close.php',
    1 => 'RarArchive::close',
  ),
  1 => 
  array (
    0 => 'rararchive.getcomment.php',
    1 => 'RarArchive::getComment',
  ),
  2 => 
  array (
    0 => 'rararchive.getentries.php',
    1 => 'RarArchive::getEntries',
  ),
  3 => 
  array (
    0 => 'rararchive.getentry.php',
    1 => 'RarArchive::getEntry',
  ),
  4 => 
  array (
    0 => 'rararchive.isbroken.php',
    1 => 'RarArchive::isBroken',
  ),
  5 => 
  array (
    0 => 'rararchive.issolid.php',
    1 => 'RarArchive::isSolid',
  ),
  6 => 
  array (
    0 => 'rararchive.open.php',
    1 => 'RarArchive::open',
  ),
  7 => 
  array (
    0 => 'rararchive.setallowbroken.php',
    1 => 'RarArchive::setAllowBroken',
  ),
  8 => 
  array (
    0 => 'rararchive.tostring.php',
    1 => 'RarArchive::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.rar.php',
    1 => 'Rar',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);