<?php
$TOC = array (
  0 => 
  array (
    0 => 'sphinxclient.addquery.php',
    1 => 'SphinxClient::addQuery',
  ),
  1 => 
  array (
    0 => 'sphinxclient.buildexcerpts.php',
    1 => 'SphinxClient::buildExcerpts',
  ),
  2 => 
  array (
    0 => 'sphinxclient.buildkeywords.php',
    1 => 'SphinxClient::buildKeywords',
  ),
  3 => 
  array (
    0 => 'sphinxclient.close.php',
    1 => 'SphinxClient::close',
  ),
  4 => 
  array (
    0 => 'sphinxclient.construct.php',
    1 => 'SphinxClient::__construct',
  ),
  5 => 
  array (
    0 => 'sphinxclient.escapestring.php',
    1 => 'SphinxClient::escapeString',
  ),
  6 => 
  array (
    0 => 'sphinxclient.getlasterror.php',
    1 => 'SphinxClient::getLastError',
  ),
  7 => 
  array (
    0 => 'sphinxclient.getlastwarning.php',
    1 => 'SphinxClient::getLastWarning',
  ),
  8 => 
  array (
    0 => 'sphinxclient.open.php',
    1 => 'SphinxClient::open',
  ),
  9 => 
  array (
    0 => 'sphinxclient.query.php',
    1 => 'SphinxClient::query',
  ),
  10 => 
  array (
    0 => 'sphinxclient.resetfilters.php',
    1 => 'SphinxClient::resetFilters',
  ),
  11 => 
  array (
    0 => 'sphinxclient.resetgroupby.php',
    1 => 'SphinxClient::resetGroupBy',
  ),
  12 => 
  array (
    0 => 'sphinxclient.runqueries.php',
    1 => 'SphinxClient::runQueries',
  ),
  13 => 
  array (
    0 => 'sphinxclient.setarrayresult.php',
    1 => 'SphinxClient::setArrayResult',
  ),
  14 => 
  array (
    0 => 'sphinxclient.setconnecttimeout.php',
    1 => 'SphinxClient::setConnectTimeout',
  ),
  15 => 
  array (
    0 => 'sphinxclient.setfieldweights.php',
    1 => 'SphinxClient::setFieldWeights',
  ),
  16 => 
  array (
    0 => 'sphinxclient.setfilter.php',
    1 => 'SphinxClient::setFilter',
  ),
  17 => 
  array (
    0 => 'sphinxclient.setfilterfloatrange.php',
    1 => 'SphinxClient::setFilterFloatRange',
  ),
  18 => 
  array (
    0 => 'sphinxclient.setfilterrange.php',
    1 => 'SphinxClient::setFilterRange',
  ),
  19 => 
  array (
    0 => 'sphinxclient.setgeoanchor.php',
    1 => 'SphinxClient::setGeoAnchor',
  ),
  20 => 
  array (
    0 => 'sphinxclient.setgroupby.php',
    1 => 'SphinxClient::setGroupBy',
  ),
  21 => 
  array (
    0 => 'sphinxclient.setgroupdistinct.php',
    1 => 'SphinxClient::setGroupDistinct',
  ),
  22 => 
  array (
    0 => 'sphinxclient.setidrange.php',
    1 => 'SphinxClient::setIDRange',
  ),
  23 => 
  array (
    0 => 'sphinxclient.setindexweights.php',
    1 => 'SphinxClient::setIndexWeights',
  ),
  24 => 
  array (
    0 => 'sphinxclient.setlimits.php',
    1 => 'SphinxClient::setLimits',
  ),
  25 => 
  array (
    0 => 'sphinxclient.setmatchmode.php',
    1 => 'SphinxClient::setMatchMode',
  ),
  26 => 
  array (
    0 => 'sphinxclient.setmaxquerytime.php',
    1 => 'SphinxClient::setMaxQueryTime',
  ),
  27 => 
  array (
    0 => 'sphinxclient.setoverride.php',
    1 => 'SphinxClient::setOverride',
  ),
  28 => 
  array (
    0 => 'sphinxclient.setrankingmode.php',
    1 => 'SphinxClient::setRankingMode',
  ),
  29 => 
  array (
    0 => 'sphinxclient.setretries.php',
    1 => 'SphinxClient::setRetries',
  ),
  30 => 
  array (
    0 => 'sphinxclient.setselect.php',
    1 => 'SphinxClient::setSelect',
  ),
  31 => 
  array (
    0 => 'sphinxclient.setserver.php',
    1 => 'SphinxClient::setServer',
  ),
  32 => 
  array (
    0 => 'sphinxclient.setsortmode.php',
    1 => 'SphinxClient::setSortMode',
  ),
  33 => 
  array (
    0 => 'sphinxclient.status.php',
    1 => 'SphinxClient::status',
  ),
  34 => 
  array (
    0 => 'sphinxclient.updateattributes.php',
    1 => 'SphinxClient::updateAttributes',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sphinx.php',
    1 => 'Sphinx',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);