<?php
$TOC = array (
  0 => 
  array (
    0 => 'judy.bycount.php',
    1 => 'Judy::byCount',
  ),
  1 => 
  array (
    0 => 'judy.construct.php',
    1 => 'Judy::__construct',
  ),
  2 => 
  array (
    0 => 'judy.count.php',
    1 => 'Judy::count',
  ),
  3 => 
  array (
    0 => 'judy.destruct.php',
    1 => 'Judy::__destruct',
  ),
  4 => 
  array (
    0 => 'judy.first.php',
    1 => 'Judy::first',
  ),
  5 => 
  array (
    0 => 'judy.firstempty.php',
    1 => 'Judy::firstEmpty',
  ),
  6 => 
  array (
    0 => 'judy.free.php',
    1 => 'Judy::free',
  ),
  7 => 
  array (
    0 => 'judy.gettype.php',
    1 => 'Judy::getType',
  ),
  8 => 
  array (
    0 => 'judy.last.php',
    1 => 'Judy::last',
  ),
  9 => 
  array (
    0 => 'judy.lastempty.php',
    1 => 'Judy::lastEmpty',
  ),
  10 => 
  array (
    0 => 'judy.memoryusage.php',
    1 => 'Judy::memoryUsage',
  ),
  11 => 
  array (
    0 => 'judy.next.php',
    1 => 'Judy::next',
  ),
  12 => 
  array (
    0 => 'judy.nextempty.php',
    1 => 'Judy::nextEmpty',
  ),
  13 => 
  array (
    0 => 'judy.offsetexists.php',
    1 => 'Judy::offsetExists',
  ),
  14 => 
  array (
    0 => 'judy.offsetget.php',
    1 => 'Judy::offsetGet',
  ),
  15 => 
  array (
    0 => 'judy.offsetset.php',
    1 => 'Judy::offsetSet',
  ),
  16 => 
  array (
    0 => 'judy.offsetunset.php',
    1 => 'Judy::offsetUnset',
  ),
  17 => 
  array (
    0 => 'judy.prev.php',
    1 => 'Judy::prev',
  ),
  18 => 
  array (
    0 => 'judy.prevempty.php',
    1 => 'Judy::prevEmpty',
  ),
  19 => 
  array (
    0 => 'judy.size.php',
    1 => 'Judy::size',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.judy.php',
    1 => 'Judy',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);