<?php
$TOC = array (
  0 => 
  array (
    0 => 'iteratoriterator.construct.php',
    1 => 'IteratorIterator::__construct',
  ),
  1 => 
  array (
    0 => 'iteratoriterator.current.php',
    1 => 'IteratorIterator::current',
  ),
  2 => 
  array (
    0 => 'iteratoriterator.getinneriterator.php',
    1 => 'IteratorIterator::getInnerIterator',
  ),
  3 => 
  array (
    0 => 'iteratoriterator.key.php',
    1 => 'IteratorIterator::key',
  ),
  4 => 
  array (
    0 => 'iteratoriterator.next.php',
    1 => 'IteratorIterator::next',
  ),
  5 => 
  array (
    0 => 'iteratoriterator.rewind.php',
    1 => 'IteratorIterator::rewind',
  ),
  6 => 
  array (
    0 => 'iteratoriterator.valid.php',
    1 => 'IteratorIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);