<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.imagickpixeliterator-clear.php',
    1 => 'ImagickPixelIterator::clear',
  ),
  1 => 
  array (
    0 => 'function.imagickpixeliterator-construct.php',
    1 => 'ImagickPixelIterator::__construct',
  ),
  2 => 
  array (
    0 => 'function.imagickpixeliterator-destroy.php',
    1 => 'ImagickPixelIterator::destroy',
  ),
  3 => 
  array (
    0 => 'function.imagickpixeliterator-getcurrentiteratorrow.php',
    1 => 'ImagickPixelIterator::getCurrentIteratorRow',
  ),
  4 => 
  array (
    0 => 'function.imagickpixeliterator-getiteratorrow.php',
    1 => 'ImagickPixelIterator::getIteratorRow',
  ),
  5 => 
  array (
    0 => 'function.imagickpixeliterator-getnextiteratorrow.php',
    1 => 'ImagickPixelIterator::getNextIteratorRow',
  ),
  6 => 
  array (
    0 => 'function.imagickpixeliterator-getpreviousiteratorrow.php',
    1 => 'ImagickPixelIterator::getPreviousIteratorRow',
  ),
  7 => 
  array (
    0 => 'function.imagickpixeliterator-newpixeliterator.php',
    1 => 'ImagickPixelIterator::newPixelIterator',
  ),
  8 => 
  array (
    0 => 'function.imagickpixeliterator-newpixelregioniterator.php',
    1 => 'ImagickPixelIterator::newPixelRegionIterator',
  ),
  9 => 
  array (
    0 => 'function.imagickpixeliterator-resetiterator.php',
    1 => 'ImagickPixelIterator::resetIterator',
  ),
  10 => 
  array (
    0 => 'function.imagickpixeliterator-setiteratorfirstrow.php',
    1 => 'ImagickPixelIterator::setIteratorFirstRow',
  ),
  11 => 
  array (
    0 => 'function.imagickpixeliterator-setiteratorlastrow.php',
    1 => 'ImagickPixelIterator::setIteratorLastRow',
  ),
  12 => 
  array (
    0 => 'function.imagickpixeliterator-setiteratorrow.php',
    1 => 'ImagickPixelIterator::setIteratorRow',
  ),
  13 => 
  array (
    0 => 'function.imagickpixeliterator-synciterator.php',
    1 => 'ImagickPixelIterator::syncIterator',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.imagick.php',
    1 => 'ImageMagick',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);