<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.httpinflatestream-construct.php',
    1 => 'HttpInflateStream::__construct',
  ),
  1 => 
  array (
    0 => 'function.httpinflatestream-factory.php',
    1 => 'HttpInflateStream::factory',
  ),
  2 => 
  array (
    0 => 'function.httpinflatestream-finish.php',
    1 => 'HttpInflateStream::finish',
  ),
  3 => 
  array (
    0 => 'function.httpinflatestream-flush.php',
    1 => 'HttpInflateStream::flush',
  ),
  4 => 
  array (
    0 => 'function.httpinflatestream-update.php',
    1 => 'HttpInflateStream::update',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.http.php',
    1 => 'HTTP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);