<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairofontoptions.construct.php',
    1 => 'CairoFontOptions::__construct',
  ),
  1 => 
  array (
    0 => 'cairofontoptions.equal.php',
    1 => 'CairoFontOptions::equal',
  ),
  2 => 
  array (
    0 => 'cairofontoptions.getantialias.php',
    1 => 'CairoFontOptions::getAntialias',
  ),
  3 => 
  array (
    0 => 'cairofontoptions.gethintmetrics.php',
    1 => 'CairoFontOptions::getHintMetrics',
  ),
  4 => 
  array (
    0 => 'cairofontoptions.gethintstyle.php',
    1 => 'CairoFontOptions::getHintStyle',
  ),
  5 => 
  array (
    0 => 'cairofontoptions.getsubpixelorder.php',
    1 => 'CairoFontOptions::getSubpixelOrder',
  ),
  6 => 
  array (
    0 => 'cairofontoptions.hash.php',
    1 => 'CairoFontOptions::hash',
  ),
  7 => 
  array (
    0 => 'cairofontoptions.merge.php',
    1 => 'CairoFontOptions::merge',
  ),
  8 => 
  array (
    0 => 'cairofontoptions.setantialias.php',
    1 => 'CairoFontOptions::setAntialias',
  ),
  9 => 
  array (
    0 => 'cairofontoptions.sethintmetrics.php',
    1 => 'CairoFontOptions::setHintMetrics',
  ),
  10 => 
  array (
    0 => 'cairofontoptions.sethintstyle.php',
    1 => 'CairoFontOptions::setHintStyle',
  ),
  11 => 
  array (
    0 => 'cairofontoptions.setsubpixelorder.php',
    1 => 'CairoFontOptions::setSubpixelOrder',
  ),
  12 => 
  array (
    0 => 'cairofontoptions.status.php',
    1 => 'CairoFontOptions::status',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);