<?php
$TOC = array (
  0 => 
  array (
    0 => 'mongocode.construct.php',
    1 => 'MongoCode::__construct',
  ),
  1 => 
  array (
    0 => 'mongocode.tostring.php',
    1 => 'MongoCode::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'mongo.types.php',
    1 => 'Types',
  ),
  1 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  2 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  3 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  4 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  5 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);