<?php
$TOC = array (
  0 => 
  array (
    0 => 'reflectionmethod.construct.php',
    1 => 'ReflectionMethod::__construct',
  ),
  1 => 
  array (
    0 => 'reflectionmethod.export.php',
    1 => 'ReflectionMethod::export',
  ),
  2 => 
  array (
    0 => 'reflectionmethod.getdeclaringclass.php',
    1 => 'ReflectionMethod::getDeclaringClass',
  ),
  3 => 
  array (
    0 => 'reflectionmethod.getmodifiers.php',
    1 => 'ReflectionMethod::getModifiers',
  ),
  4 => 
  array (
    0 => 'reflectionmethod.getprototype.php',
    1 => 'ReflectionMethod::getPrototype',
  ),
  5 => 
  array (
    0 => 'reflectionmethod.invoke.php',
    1 => 'ReflectionMethod::invoke',
  ),
  6 => 
  array (
    0 => 'reflectionmethod.invokeargs.php',
    1 => 'ReflectionMethod::invokeArgs',
  ),
  7 => 
  array (
    0 => 'reflectionmethod.isabstract.php',
    1 => 'ReflectionMethod::isAbstract',
  ),
  8 => 
  array (
    0 => 'reflectionmethod.isconstructor.php',
    1 => 'ReflectionMethod::isConstructor',
  ),
  9 => 
  array (
    0 => 'reflectionmethod.isdestructor.php',
    1 => 'ReflectionMethod::isDestructor',
  ),
  10 => 
  array (
    0 => 'reflectionmethod.isfinal.php',
    1 => 'ReflectionMethod::isFinal',
  ),
  11 => 
  array (
    0 => 'reflectionmethod.isprivate.php',
    1 => 'ReflectionMethod::isPrivate',
  ),
  12 => 
  array (
    0 => 'reflectionmethod.isprotected.php',
    1 => 'ReflectionMethod::isProtected',
  ),
  13 => 
  array (
    0 => 'reflectionmethod.ispublic.php',
    1 => 'ReflectionMethod::isPublic',
  ),
  14 => 
  array (
    0 => 'reflectionmethod.isstatic.php',
    1 => 'ReflectionMethod::isStatic',
  ),
  15 => 
  array (
    0 => 'reflectionmethod.setaccessible.php',
    1 => 'ReflectionMethod::setAccessible',
  ),
  16 => 
  array (
    0 => 'reflectionmethod.tostring.php',
    1 => 'ReflectionMethod::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.reflection.php',
    1 => 'Reflection',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);