<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swfshape.addfill.php',
    1 => 'SWFShape-&gt;addFill',
  ),
  1 => 
  array (
    0 => 'function.swfshape.construct.php',
    1 => 'SWFShape-&gt;__construct',
  ),
  2 => 
  array (
    0 => 'function.swfshape.drawarc.php',
    1 => 'SWFShape-&gt;drawArc',
  ),
  3 => 
  array (
    0 => 'function.swfshape.drawcircle.php',
    1 => 'SWFShape-&gt;drawCircle',
  ),
  4 => 
  array (
    0 => 'function.swfshape.drawcubic.php',
    1 => 'SWFShape-&gt;drawCubic',
  ),
  5 => 
  array (
    0 => 'function.swfshape.drawcubicto.php',
    1 => 'SWFShape-&gt;drawCubicTo',
  ),
  6 => 
  array (
    0 => 'function.swfshape.drawcurve.php',
    1 => 'SWFShape-&gt;drawCurve',
  ),
  7 => 
  array (
    0 => 'function.swfshape.drawcurveto.php',
    1 => 'SWFShape-&gt;drawCurveTo',
  ),
  8 => 
  array (
    0 => 'function.swfshape.drawglyph.php',
    1 => 'SWFShape-&gt;drawGlyph',
  ),
  9 => 
  array (
    0 => 'function.swfshape.drawline.php',
    1 => 'SWFShape-&gt;drawLine',
  ),
  10 => 
  array (
    0 => 'function.swfshape.drawlineto.php',
    1 => 'SWFShape-&gt;drawLineTo',
  ),
  11 => 
  array (
    0 => 'function.swfshape.movepen.php',
    1 => 'SWFShape-&gt;movePen',
  ),
  12 => 
  array (
    0 => 'function.swfshape.movepento.php',
    1 => 'SWFShape-&gt;movePenTo',
  ),
  13 => 
  array (
    0 => 'function.swfshape.setleftfill.php',
    1 => 'SWFShape-&gt;setLeftFill',
  ),
  14 => 
  array (
    0 => 'function.swfshape.setline.php',
    1 => 'SWFShape-&gt;setLine',
  ),
  15 => 
  array (
    0 => 'function.swfshape.setrightfill.php',
    1 => 'SWFShape-&gt;setRightFill',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);