<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairofontface.construct.php',
    1 => 'CairoFontFace::__construct',
  ),
  1 => 
  array (
    0 => 'cairofontface.gettype.php',
    1 => 'CairoFontFace::getType',
  ),
  2 => 
  array (
    0 => 'cairofontface.status.php',
    1 => 'CairoFontFace::status',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);