<?php
$TOC = array (
  0 => 
  array (
    0 => 'norewinditerator.construct.php',
    1 => 'NoRewindIterator::__construct',
  ),
  1 => 
  array (
    0 => 'norewinditerator.current.php',
    1 => 'NoRewindIterator::current',
  ),
  2 => 
  array (
    0 => 'norewinditerator.getinneriterator.php',
    1 => 'NoRewindIterator::getInnerIterator',
  ),
  3 => 
  array (
    0 => 'norewinditerator.key.php',
    1 => 'NoRewindIterator::key',
  ),
  4 => 
  array (
    0 => 'norewinditerator.next.php',
    1 => 'NoRewindIterator::next',
  ),
  5 => 
  array (
    0 => 'norewinditerator.haschildren.php',
    1 => 'NoRewindIterator::rewind',
  ),
  6 => 
  array (
    0 => 'norewinditerator.valid.php',
    1 => 'NoRewindIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);