<?php
$TOC = array (
  0 => 
  array (
    0 => 'serializable.serialize.php',
    1 => 'Serializable::serialize',
  ),
  1 => 
  array (
    0 => 'serializable.unserialize.php',
    1 => 'Serializable::unserialize',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'reserved.interfaces.php',
    1 => 'Predefined Interfaces',
  ),
  1 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);