<?php
$TOC = array (
  0 => 
  array (
    0 => 'reflectionproperty.clone.php',
    1 => 'ReflectionProperty::__clone',
  ),
  1 => 
  array (
    0 => 'reflectionproperty.construct.php',
    1 => 'ReflectionProperty::__construct',
  ),
  2 => 
  array (
    0 => 'reflectionproperty.export.php',
    1 => 'ReflectionProperty::export',
  ),
  3 => 
  array (
    0 => 'reflectionproperty.getdeclaringclass.php',
    1 => 'ReflectionProperty::getDeclaringClass',
  ),
  4 => 
  array (
    0 => 'reflectionproperty.getdoccomment.php',
    1 => 'ReflectionProperty::getDocComment',
  ),
  5 => 
  array (
    0 => 'reflectionproperty.getmodifiers.php',
    1 => 'ReflectionProperty::getModifiers',
  ),
  6 => 
  array (
    0 => 'reflectionproperty.getname.php',
    1 => 'ReflectionProperty::getName',
  ),
  7 => 
  array (
    0 => 'reflectionproperty.getvalue.php',
    1 => 'ReflectionProperty::getValue',
  ),
  8 => 
  array (
    0 => 'reflectionproperty.isdefault.php',
    1 => 'ReflectionProperty::isDefault',
  ),
  9 => 
  array (
    0 => 'reflectionproperty.isprivate.php',
    1 => 'ReflectionProperty::isPrivate',
  ),
  10 => 
  array (
    0 => 'reflectionproperty.isprotected.php',
    1 => 'ReflectionProperty::isProtected',
  ),
  11 => 
  array (
    0 => 'reflectionproperty.ispublic.php',
    1 => 'ReflectionProperty::isPublic',
  ),
  12 => 
  array (
    0 => 'reflectionproperty.isstatic.php',
    1 => 'ReflectionProperty::isStatic',
  ),
  13 => 
  array (
    0 => 'reflectionproperty.setaccessible.php',
    1 => 'ReflectionProperty::setAccessible',
  ),
  14 => 
  array (
    0 => 'reflectionproperty.setvalue.php',
    1 => 'ReflectionProperty::setValue',
  ),
  15 => 
  array (
    0 => 'reflectionproperty.tostring.php',
    1 => 'ReflectionProperty::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.reflection.php',
    1 => 'Reflection',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);