<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.haruannotation-setborderstyle.php',
    1 => 'HaruAnnotation::setBorderStyle',
  ),
  1 => 
  array (
    0 => 'function.haruannotation-sethighlightmode.php',
    1 => 'HaruAnnotation::setHighlightMode',
  ),
  2 => 
  array (
    0 => 'function.haruannotation-seticon.php',
    1 => 'HaruAnnotation::setIcon',
  ),
  3 => 
  array (
    0 => 'function.haruannotation-setopened.php',
    1 => 'HaruAnnotation::setOpened',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.haru.php',
    1 => 'haru',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);