<?php
$TOC = array (
  0 => 
  array (
    0 => 'solrdocument.addfield.php',
    1 => 'SolrDocument::addField',
  ),
  1 => 
  array (
    0 => 'solrdocument.clear.php',
    1 => 'SolrDocument::clear',
  ),
  2 => 
  array (
    0 => 'solrdocument.clone.php',
    1 => 'SolrDocument::__clone',
  ),
  3 => 
  array (
    0 => 'solrdocument.construct.php',
    1 => 'SolrDocument::__construct',
  ),
  4 => 
  array (
    0 => 'solrdocument.current.php',
    1 => 'SolrDocument::current',
  ),
  5 => 
  array (
    0 => 'solrdocument.deletefield.php',
    1 => 'SolrDocument::deleteField',
  ),
  6 => 
  array (
    0 => 'solrdocument.destruct.php',
    1 => 'SolrDocument::__destruct',
  ),
  7 => 
  array (
    0 => 'solrdocument.fieldexists.php',
    1 => 'SolrDocument::fieldExists',
  ),
  8 => 
  array (
    0 => 'solrdocument.get.php',
    1 => 'SolrDocument::__get',
  ),
  9 => 
  array (
    0 => 'solrdocument.getfield.php',
    1 => 'SolrDocument::getField',
  ),
  10 => 
  array (
    0 => 'solrdocument.getfieldcount.php',
    1 => 'SolrDocument::getFieldCount',
  ),
  11 => 
  array (
    0 => 'solrdocument.getfieldnames.php',
    1 => 'SolrDocument::getFieldNames',
  ),
  12 => 
  array (
    0 => 'solrdocument.getinputdocument.php',
    1 => 'SolrDocument::getInputDocument',
  ),
  13 => 
  array (
    0 => 'solrdocument.isset.php',
    1 => 'SolrDocument::__isset',
  ),
  14 => 
  array (
    0 => 'solrdocument.key.php',
    1 => 'SolrDocument::key',
  ),
  15 => 
  array (
    0 => 'solrdocument.merge.php',
    1 => 'SolrDocument::merge',
  ),
  16 => 
  array (
    0 => 'solrdocument.next.php',
    1 => 'SolrDocument::next',
  ),
  17 => 
  array (
    0 => 'solrdocument.offsetexists.php',
    1 => 'SolrDocument::offsetExists',
  ),
  18 => 
  array (
    0 => 'solrdocument.offsetget.php',
    1 => 'SolrDocument::offsetGet',
  ),
  19 => 
  array (
    0 => 'solrdocument.offsetset.php',
    1 => 'SolrDocument::offsetSet',
  ),
  20 => 
  array (
    0 => 'solrdocument.offsetunset.php',
    1 => 'SolrDocument::offsetUnset',
  ),
  21 => 
  array (
    0 => 'solrdocument.reset.php',
    1 => 'SolrDocument::reset',
  ),
  22 => 
  array (
    0 => 'solrdocument.rewind.php',
    1 => 'SolrDocument::rewind',
  ),
  23 => 
  array (
    0 => 'solrdocument.serialize.php',
    1 => 'SolrDocument::serialize',
  ),
  24 => 
  array (
    0 => 'solrdocument.set.php',
    1 => 'SolrDocument::__set',
  ),
  25 => 
  array (
    0 => 'solrdocument.sort.php',
    1 => 'SolrDocument::sort',
  ),
  26 => 
  array (
    0 => 'solrdocument.toarray.php',
    1 => 'SolrDocument::toArray',
  ),
  27 => 
  array (
    0 => 'solrdocument.unserialize.php',
    1 => 'SolrDocument::unserialize',
  ),
  28 => 
  array (
    0 => 'solrdocument.unset.php',
    1 => 'SolrDocument::__unset',
  ),
  29 => 
  array (
    0 => 'solrdocument.valid.php',
    1 => 'SolrDocument::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.solr.php',
    1 => 'Solr',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);