<?php
$TOC = array (
  0 => 
  array (
    0 => 'xmlreader.close.php',
    1 => 'XMLReader::close',
  ),
  1 => 
  array (
    0 => 'xmlreader.expand.php',
    1 => 'XMLReader::expand',
  ),
  2 => 
  array (
    0 => 'xmlreader.getattribute.php',
    1 => 'XMLReader::getAttribute',
  ),
  3 => 
  array (
    0 => 'xmlreader.getattributeno.php',
    1 => 'XMLReader::getAttributeNo',
  ),
  4 => 
  array (
    0 => 'xmlreader.getattributens.php',
    1 => 'XMLReader::getAttributeNs',
  ),
  5 => 
  array (
    0 => 'xmlreader.getparserproperty.php',
    1 => 'XMLReader::getParserProperty',
  ),
  6 => 
  array (
    0 => 'xmlreader.isvalid.php',
    1 => 'XMLReader::isValid',
  ),
  7 => 
  array (
    0 => 'xmlreader.lookupnamespace.php',
    1 => 'XMLReader::lookupNamespace',
  ),
  8 => 
  array (
    0 => 'xmlreader.movetoattribute.php',
    1 => 'XMLReader::moveToAttribute',
  ),
  9 => 
  array (
    0 => 'xmlreader.movetoattributeno.php',
    1 => 'XMLReader::moveToAttributeNo',
  ),
  10 => 
  array (
    0 => 'xmlreader.movetoattributens.php',
    1 => 'XMLReader::moveToAttributeNs',
  ),
  11 => 
  array (
    0 => 'xmlreader.movetoelement.php',
    1 => 'XMLReader::moveToElement',
  ),
  12 => 
  array (
    0 => 'xmlreader.movetofirstattribute.php',
    1 => 'XMLReader::moveToFirstAttribute',
  ),
  13 => 
  array (
    0 => 'xmlreader.movetonextattribute.php',
    1 => 'XMLReader::moveToNextAttribute',
  ),
  14 => 
  array (
    0 => 'xmlreader.next.php',
    1 => 'XMLReader::next',
  ),
  15 => 
  array (
    0 => 'xmlreader.open.php',
    1 => 'XMLReader::open',
  ),
  16 => 
  array (
    0 => 'xmlreader.read.php',
    1 => 'XMLReader::read',
  ),
  17 => 
  array (
    0 => 'xmlreader.readinnerxml.php',
    1 => 'XMLReader::readInnerXML',
  ),
  18 => 
  array (
    0 => 'xmlreader.readouterxml.php',
    1 => 'XMLReader::readOuterXML',
  ),
  19 => 
  array (
    0 => 'xmlreader.readstring.php',
    1 => 'XMLReader::readString',
  ),
  20 => 
  array (
    0 => 'xmlreader.setparserproperty.php',
    1 => 'XMLReader::setParserProperty',
  ),
  21 => 
  array (
    0 => 'xmlreader.setrelaxngschema.php',
    1 => 'XMLReader::setRelaxNGSchema',
  ),
  22 => 
  array (
    0 => 'xmlreader.setrelaxngschemasource.php',
    1 => 'XMLReader::setRelaxNGSchemaSource',
  ),
  23 => 
  array (
    0 => 'xmlreader.setschema.php',
    1 => 'XMLReader::setSchema',
  ),
  24 => 
  array (
    0 => 'xmlreader.xml.php',
    1 => 'XMLReader::XML',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.xmlreader.php',
    1 => 'XMLReader',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);