<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairo.availablefonts.php',
    1 => 'Cairo::availableFonts',
  ),
  1 => 
  array (
    0 => 'cairo.availablesurfaces.php',
    1 => 'Cairo::availableSurfaces',
  ),
  2 => 
  array (
    0 => 'cairo.statustostring.php',
    1 => 'Cairo::statusToString',
  ),
  3 => 
  array (
    0 => 'cairo.version.php',
    1 => 'Cairo::version',
  ),
  4 => 
  array (
    0 => 'cairo.versionstring.php',
    1 => 'Cairo::versionString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);