<?php
$TOC = array (
  0 => 
  array (
    0 => 'locale.acceptfromhttp.php',
    1 => 'Locale::acceptFromHttp',
  ),
  1 => 
  array (
    0 => 'locale.composelocale.php',
    1 => 'Locale::composeLocale',
  ),
  2 => 
  array (
    0 => 'locale.filtermatches.php',
    1 => 'Locale::filterMatches',
  ),
  3 => 
  array (
    0 => 'locale.getallvariants.php',
    1 => 'Locale::getAllVariants',
  ),
  4 => 
  array (
    0 => 'locale.getdefault.php',
    1 => 'Locale::getDefault',
  ),
  5 => 
  array (
    0 => 'locale.getdisplaylanguage.php',
    1 => 'Locale::getDisplayLanguage',
  ),
  6 => 
  array (
    0 => 'locale.getdisplayname.php',
    1 => 'Locale::getDisplayName',
  ),
  7 => 
  array (
    0 => 'locale.getdisplayregion.php',
    1 => 'Locale::getDisplayRegion',
  ),
  8 => 
  array (
    0 => 'locale.getdisplayscript.php',
    1 => 'Locale::getDisplayScript',
  ),
  9 => 
  array (
    0 => 'locale.getdisplayvariant.php',
    1 => 'Locale::getDisplayVariant',
  ),
  10 => 
  array (
    0 => 'locale.getkeywords.php',
    1 => 'Locale::getKeywords',
  ),
  11 => 
  array (
    0 => 'locale.getprimarylanguage.php',
    1 => 'Locale::getPrimaryLanguage',
  ),
  12 => 
  array (
    0 => 'locale.getregion.php',
    1 => 'Locale::getRegion',
  ),
  13 => 
  array (
    0 => 'locale.getscript.php',
    1 => 'Locale::getScript',
  ),
  14 => 
  array (
    0 => 'locale.lookup.php',
    1 => 'Locale::lookup',
  ),
  15 => 
  array (
    0 => 'locale.parselocale.php',
    1 => 'Locale::parseLocale',
  ),
  16 => 
  array (
    0 => 'locale.setdefault.php',
    1 => 'Locale::setDefault',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.intl.php',
    1 => 'intl',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);