<?php
$TOC = array (
  0 => 
  array (
    0 => 'reflectionclass.clone.php',
    1 => 'ReflectionClass::__clone',
  ),
  1 => 
  array (
    0 => 'reflectionclass.construct.php',
    1 => 'ReflectionClass::__construct',
  ),
  2 => 
  array (
    0 => 'reflectionclass.export.php',
    1 => 'ReflectionClass::export',
  ),
  3 => 
  array (
    0 => 'reflectionclass.getconstant.php',
    1 => 'ReflectionClass::getConstant',
  ),
  4 => 
  array (
    0 => 'reflectionclass.getconstants.php',
    1 => 'ReflectionClass::getConstants',
  ),
  5 => 
  array (
    0 => 'reflectionclass.getconstructor.php',
    1 => 'ReflectionClass::getConstructor',
  ),
  6 => 
  array (
    0 => 'reflectionclass.getdefaultproperties.php',
    1 => 'ReflectionClass::getDefaultProperties',
  ),
  7 => 
  array (
    0 => 'reflectionclass.getdoccomment.php',
    1 => 'ReflectionClass::getDocComment',
  ),
  8 => 
  array (
    0 => 'reflectionclass.getendline.php',
    1 => 'ReflectionClass::getEndLine',
  ),
  9 => 
  array (
    0 => 'reflectionclass.getextension.php',
    1 => 'ReflectionClass::getExtension',
  ),
  10 => 
  array (
    0 => 'reflectionclass.getextensionname.php',
    1 => 'ReflectionClass::getExtensionName',
  ),
  11 => 
  array (
    0 => 'reflectionclass.getfilename.php',
    1 => 'ReflectionClass::getFileName',
  ),
  12 => 
  array (
    0 => 'reflectionclass.getinterfacenames.php',
    1 => 'ReflectionClass::getInterfaceNames',
  ),
  13 => 
  array (
    0 => 'reflectionclass.getinterfaces.php',
    1 => 'ReflectionClass::getInterfaces',
  ),
  14 => 
  array (
    0 => 'reflectionclass.getmethod.php',
    1 => 'ReflectionClass::getMethod',
  ),
  15 => 
  array (
    0 => 'reflectionclass.getmethods.php',
    1 => 'ReflectionClass::getMethods',
  ),
  16 => 
  array (
    0 => 'reflectionclass.getmodifiers.php',
    1 => 'ReflectionClass::getModifiers',
  ),
  17 => 
  array (
    0 => 'reflectionclass.getname.php',
    1 => 'ReflectionClass::getName',
  ),
  18 => 
  array (
    0 => 'reflectionclass.getnamespacename.php',
    1 => 'ReflectionClass::getNamespaceName',
  ),
  19 => 
  array (
    0 => 'reflectionclass.getparentclass.php',
    1 => 'ReflectionClass::getParentClass',
  ),
  20 => 
  array (
    0 => 'reflectionclass.getproperties.php',
    1 => 'ReflectionClass::getProperties',
  ),
  21 => 
  array (
    0 => 'reflectionclass.getproperty.php',
    1 => 'ReflectionClass::getProperty',
  ),
  22 => 
  array (
    0 => 'reflectionclass.getshortname.php',
    1 => 'ReflectionClass::getShortName',
  ),
  23 => 
  array (
    0 => 'reflectionclass.getstartline.php',
    1 => 'ReflectionClass::getStartLine',
  ),
  24 => 
  array (
    0 => 'reflectionclass.getstaticproperties.php',
    1 => 'ReflectionClass::getStaticProperties',
  ),
  25 => 
  array (
    0 => 'reflectionclass.getstaticpropertyvalue.php',
    1 => 'ReflectionClass::getStaticPropertyValue',
  ),
  26 => 
  array (
    0 => 'reflectionclass.hasconstant.php',
    1 => 'ReflectionClass::hasConstant',
  ),
  27 => 
  array (
    0 => 'reflectionclass.hasmethod.php',
    1 => 'ReflectionClass::hasMethod',
  ),
  28 => 
  array (
    0 => 'reflectionclass.hasproperty.php',
    1 => 'ReflectionClass::hasProperty',
  ),
  29 => 
  array (
    0 => 'reflectionclass.implementsinterface.php',
    1 => 'ReflectionClass::implementsInterface',
  ),
  30 => 
  array (
    0 => 'reflectionclass.innamespace.php',
    1 => 'ReflectionClass::inNamespace',
  ),
  31 => 
  array (
    0 => 'reflectionclass.isabstract.php',
    1 => 'ReflectionClass::isAbstract',
  ),
  32 => 
  array (
    0 => 'reflectionclass.isfinal.php',
    1 => 'ReflectionClass::isFinal',
  ),
  33 => 
  array (
    0 => 'reflectionclass.isinstance.php',
    1 => 'ReflectionClass::isInstance',
  ),
  34 => 
  array (
    0 => 'reflectionclass.isinstantiable.php',
    1 => 'ReflectionClass::isInstantiable',
  ),
  35 => 
  array (
    0 => 'reflectionclass.isinterface.php',
    1 => 'ReflectionClass::isInterface',
  ),
  36 => 
  array (
    0 => 'reflectionclass.isinternal.php',
    1 => 'ReflectionClass::isInternal',
  ),
  37 => 
  array (
    0 => 'reflectionclass.isiterateable.php',
    1 => 'ReflectionClass::isIterateable',
  ),
  38 => 
  array (
    0 => 'reflectionclass.issubclassof.php',
    1 => 'ReflectionClass::isSubclassOf',
  ),
  39 => 
  array (
    0 => 'reflectionclass.isuserdefined.php',
    1 => 'ReflectionClass::isUserDefined',
  ),
  40 => 
  array (
    0 => 'reflectionclass.newinstance.php',
    1 => 'ReflectionClass::newInstance',
  ),
  41 => 
  array (
    0 => 'reflectionclass.newinstanceargs.php',
    1 => 'ReflectionClass::newInstanceArgs',
  ),
  42 => 
  array (
    0 => 'reflectionclass.setstaticpropertyvalue.php',
    1 => 'ReflectionClass::setStaticPropertyValue',
  ),
  43 => 
  array (
    0 => 'reflectionclass.tostring.php',
    1 => 'ReflectionClass::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.reflection.php',
    1 => 'Reflection',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);