<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairoscaledfont.construct.php',
    1 => 'CairoScaledFont::__construct',
  ),
  1 => 
  array (
    0 => 'cairoscaledfont.extents.php',
    1 => 'CairoScaledFont::extents',
  ),
  2 => 
  array (
    0 => 'cairoscaledfont.getctm.php',
    1 => 'CairoScaledFont::getCtm',
  ),
  3 => 
  array (
    0 => 'cairoscaledfont.getfontface.php',
    1 => 'CairoScaledFont::getFontFace',
  ),
  4 => 
  array (
    0 => 'cairoscaledfont.getfontmatrix.php',
    1 => 'CairoScaledFont::getFontMatrix',
  ),
  5 => 
  array (
    0 => 'cairoscaledfont.getfontoptions.php',
    1 => 'CairoScaledFont::getFontOptions',
  ),
  6 => 
  array (
    0 => 'cairoscaledfont.getscalematrix.php',
    1 => 'CairoScaledFont::getScaleMatrix',
  ),
  7 => 
  array (
    0 => 'cairoscaledfont.gettype.php',
    1 => 'CairoScaledFont::getType',
  ),
  8 => 
  array (
    0 => 'cairoscaledfont.glyphextents.php',
    1 => 'CairoScaledFont::glyphExtents',
  ),
  9 => 
  array (
    0 => 'cairoscaledfont.status.php',
    1 => 'CairoScaledFont::status',
  ),
  10 => 
  array (
    0 => 'cairoscaledfont.textextents.php',
    1 => 'CairoScaledFont::textExtents',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);