<?php
$TOC = array (
  0 => 
  array (
    0 => 'arrayiterator.append.php',
    1 => 'ArrayIterator::append',
  ),
  1 => 
  array (
    0 => 'arrayiterator.asort.php',
    1 => 'ArrayIterator::asort',
  ),
  2 => 
  array (
    0 => 'arrayiterator.construct.php',
    1 => 'ArrayIterator::__construct',
  ),
  3 => 
  array (
    0 => 'arrayiterator.count.php',
    1 => 'ArrayIterator::count',
  ),
  4 => 
  array (
    0 => 'arrayiterator.current.php',
    1 => 'ArrayIterator::current',
  ),
  5 => 
  array (
    0 => 'arrayiterator.getarraycopy.php',
    1 => 'ArrayIterator::getArrayCopy',
  ),
  6 => 
  array (
    0 => 'arrayiterator.getflags.php',
    1 => 'ArrayIterator::getFlags',
  ),
  7 => 
  array (
    0 => 'arrayiterator.key.php',
    1 => 'ArrayIterator::key',
  ),
  8 => 
  array (
    0 => 'arrayiterator.ksort.php',
    1 => 'ArrayIterator::ksort',
  ),
  9 => 
  array (
    0 => 'arrayiterator.natcasesort.php',
    1 => 'ArrayIterator::natcasesort',
  ),
  10 => 
  array (
    0 => 'arrayiterator.natsort.php',
    1 => 'ArrayIterator::natsort',
  ),
  11 => 
  array (
    0 => 'arrayiterator.next.php',
    1 => 'ArrayIterator::next',
  ),
  12 => 
  array (
    0 => 'arrayiterator.offsetexists.php',
    1 => 'ArrayIterator::offsetExists',
  ),
  13 => 
  array (
    0 => 'arrayiterator.offsetget.php',
    1 => 'ArrayIterator::offsetGet',
  ),
  14 => 
  array (
    0 => 'arrayiterator.offsetset.php',
    1 => 'ArrayIterator::offsetSet',
  ),
  15 => 
  array (
    0 => 'arrayiterator.offsetunset.php',
    1 => 'ArrayIterator::offsetUnset',
  ),
  16 => 
  array (
    0 => 'arrayiterator.rewind.php',
    1 => 'ArrayIterator::rewind',
  ),
  17 => 
  array (
    0 => 'arrayiterator.seek.php',
    1 => 'ArrayIterator::seek',
  ),
  18 => 
  array (
    0 => 'arrayiterator.serialize.php',
    1 => 'ArrayIterator::serialize',
  ),
  19 => 
  array (
    0 => 'arrayiterator.setflags.php',
    1 => 'ArrayIterator::setFlags',
  ),
  20 => 
  array (
    0 => 'arrayiterator.uasort.php',
    1 => 'ArrayIterator::uasort',
  ),
  21 => 
  array (
    0 => 'arrayiterator.uksort.php',
    1 => 'ArrayIterator::uksort',
  ),
  22 => 
  array (
    0 => 'arrayiterator.unserialize.php',
    1 => 'ArrayIterator::unserialize',
  ),
  23 => 
  array (
    0 => 'arrayiterator.valid.php',
    1 => 'ArrayIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);