<?php
$TOC = array (
  0 => 
  array (
    0 => 'mysqli-stmt.affected-rows.php',
    1 => 'mysqli_stmt-&gt;affected_rows',
  ),
  1 => 
  array (
    0 => 'mysqli-stmt.attr-get.php',
    1 => 'mysqli_stmt::attr_get',
  ),
  2 => 
  array (
    0 => 'mysqli-stmt.attr-set.php',
    1 => 'mysqli_stmt::attr_set',
  ),
  3 => 
  array (
    0 => 'mysqli-stmt.bind-param.php',
    1 => 'mysqli_stmt::bind_param',
  ),
  4 => 
  array (
    0 => 'mysqli-stmt.bind-result.php',
    1 => 'mysqli_stmt::bind_result',
  ),
  5 => 
  array (
    0 => 'mysqli-stmt.close.php',
    1 => 'mysqli_stmt::close',
  ),
  6 => 
  array (
    0 => 'mysqli-stmt.data-seek.php',
    1 => 'mysqli_stmt::data_seek',
  ),
  7 => 
  array (
    0 => 'mysqli-stmt.errno.php',
    1 => 'mysqli_stmt-&gt;errno',
  ),
  8 => 
  array (
    0 => 'mysqli-stmt.error.php',
    1 => 'mysqli_stmt-&gt;error',
  ),
  9 => 
  array (
    0 => 'mysqli-stmt.execute.php',
    1 => 'mysqli_stmt::execute',
  ),
  10 => 
  array (
    0 => 'mysqli-stmt.fetch.php',
    1 => 'mysqli_stmt::fetch',
  ),
  11 => 
  array (
    0 => 'mysqli-stmt.field-count.php',
    1 => 'mysqli_stmt-&gt;field_count',
  ),
  12 => 
  array (
    0 => 'mysqli-stmt.free-result.php',
    1 => 'mysqli_stmt::free_result',
  ),
  13 => 
  array (
    0 => 'mysqli-stmt.get-warnings.php',
    1 => 'mysqli_stmt::get_warnings',
  ),
  14 => 
  array (
    0 => 'mysqli-stmt.insert-id.php',
    1 => 'mysqli_stmt-&gt;insert_id',
  ),
  15 => 
  array (
    0 => 'mysqli-stmt.num-rows.php',
    1 => 'mysqli_stmt::num_rows',
  ),
  16 => 
  array (
    0 => 'mysqli-stmt.param-count.php',
    1 => 'mysqli_stmt-&gt;param_count',
  ),
  17 => 
  array (
    0 => 'mysqli-stmt.prepare.php',
    1 => 'mysqli_stmt::prepare',
  ),
  18 => 
  array (
    0 => 'mysqli-stmt.reset.php',
    1 => 'mysqli_stmt::reset',
  ),
  19 => 
  array (
    0 => 'mysqli-stmt.result-metadata.php',
    1 => 'mysqli_stmt::result_metadata',
  ),
  20 => 
  array (
    0 => 'mysqli-stmt.send-long-data.php',
    1 => 'mysqli_stmt::send_long_data',
  ),
  21 => 
  array (
    0 => 'mysqli-stmt.sqlstate.php',
    1 => 'mysqli_stmt::sqlstate',
  ),
  22 => 
  array (
    0 => 'mysqli-stmt.store-result.php',
    1 => 'mysqli_stmt::store_result',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mysqli.php',
    1 => 'Mysqli',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);