<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.httpresponse-capture.php',
    1 => 'HttpResponse::capture',
  ),
  1 => 
  array (
    0 => 'function.httpresponse-getbuffersize.php',
    1 => 'HttpResponse::getBufferSize',
  ),
  2 => 
  array (
    0 => 'function.httpresponse-getcache.php',
    1 => 'HttpResponse::getCache',
  ),
  3 => 
  array (
    0 => 'function.httpresponse-getcachecontrol.php',
    1 => 'HttpResponse::getCacheControl',
  ),
  4 => 
  array (
    0 => 'function.httpresponse-getcontentdisposition.php',
    1 => 'HttpResponse::getContentDisposition',
  ),
  5 => 
  array (
    0 => 'function.httpresponse-getcontenttype.php',
    1 => 'HttpResponse::getContentType',
  ),
  6 => 
  array (
    0 => 'function.httpresponse-getdata.php',
    1 => 'HttpResponse::getData',
  ),
  7 => 
  array (
    0 => 'function.httpresponse-getetag.php',
    1 => 'HttpResponse::getETag',
  ),
  8 => 
  array (
    0 => 'function.httpresponse-getfile.php',
    1 => 'HttpResponse::getFile',
  ),
  9 => 
  array (
    0 => 'function.httpresponse-getgzip.php',
    1 => 'HttpResponse::getGzip',
  ),
  10 => 
  array (
    0 => 'function.httpresponse-getheader.php',
    1 => 'HttpResponse::getHeader',
  ),
  11 => 
  array (
    0 => 'function.httpresponse-getlastmodified.php',
    1 => 'HttpResponse::getLastModified',
  ),
  12 => 
  array (
    0 => 'function.httpresponse-getrequestbody.php',
    1 => 'HttpResponse::getRequestBody',
  ),
  13 => 
  array (
    0 => 'function.httpresponse-getrequestbodystream.php',
    1 => 'HttpResponse::getRequestBodyStream',
  ),
  14 => 
  array (
    0 => 'function.httpresponse-getrequestheaders.php',
    1 => 'HttpResponse::getRequestHeaders',
  ),
  15 => 
  array (
    0 => 'function.httpresponse-getstream.php',
    1 => 'HttpResponse::getStream',
  ),
  16 => 
  array (
    0 => 'function.httpresponse-getthrottledelay.php',
    1 => 'HttpResponse::getThrottleDelay',
  ),
  17 => 
  array (
    0 => 'function.httpresponse-guesscontenttype.php',
    1 => 'HttpResponse::guessContentType',
  ),
  18 => 
  array (
    0 => 'function.httpresponse-redirect.php',
    1 => 'HttpResponse::redirect',
  ),
  19 => 
  array (
    0 => 'function.httpresponse-send.php',
    1 => 'HttpResponse::send',
  ),
  20 => 
  array (
    0 => 'function.httpresponse-setbuffersize.php',
    1 => 'HttpResponse::setBufferSize',
  ),
  21 => 
  array (
    0 => 'function.httpresponse-setcache.php',
    1 => 'HttpResponse::setCache',
  ),
  22 => 
  array (
    0 => 'function.httpresponse-setcachecontrol.php',
    1 => 'HttpResponse::setCacheControl',
  ),
  23 => 
  array (
    0 => 'function.httpresponse-setcontentdisposition.php',
    1 => 'HttpResponse::setContentDisposition',
  ),
  24 => 
  array (
    0 => 'function.httpresponse-setcontenttype.php',
    1 => 'HttpResponse::setContentType',
  ),
  25 => 
  array (
    0 => 'function.httpresponse-setdata.php',
    1 => 'HttpResponse::setData',
  ),
  26 => 
  array (
    0 => 'function.httpresponse-setetag.php',
    1 => 'HttpResponse::setETag',
  ),
  27 => 
  array (
    0 => 'function.httpresponse-setfile.php',
    1 => 'HttpResponse::setFile',
  ),
  28 => 
  array (
    0 => 'function.httpresponse-setgzip.php',
    1 => 'HttpResponse::setGzip',
  ),
  29 => 
  array (
    0 => 'function.httpresponse-setheader.php',
    1 => 'HttpResponse::setHeader',
  ),
  30 => 
  array (
    0 => 'function.httpresponse-setlastmodified.php',
    1 => 'HttpResponse::setLastModified',
  ),
  31 => 
  array (
    0 => 'function.httpresponse-setstream.php',
    1 => 'HttpResponse::setStream',
  ),
  32 => 
  array (
    0 => 'function.httpresponse-setthrottledelay.php',
    1 => 'HttpResponse::setThrottleDelay',
  ),
  33 => 
  array (
    0 => 'function.httpresponse-status.php',
    1 => 'HttpResponse::status',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.http.php',
    1 => 'HTTP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);