<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.httpmessage-addheaders.php',
    1 => 'HttpMessage::addHeaders',
  ),
  1 => 
  array (
    0 => 'function.httpmessage-construct.php',
    1 => 'HttpMessage::__construct',
  ),
  2 => 
  array (
    0 => 'function.httpmessage-detach.php',
    1 => 'HttpMessage::detach',
  ),
  3 => 
  array (
    0 => 'function.httpmessage-factory.php',
    1 => 'HttpMessage::factory',
  ),
  4 => 
  array (
    0 => 'function.httpmessage-fromenv.php',
    1 => 'HttpMessage::fromEnv',
  ),
  5 => 
  array (
    0 => 'function.httpmessage-fromstring.php',
    1 => 'HttpMessage::fromString',
  ),
  6 => 
  array (
    0 => 'function.httpmessage-getbody.php',
    1 => 'HttpMessage::getBody',
  ),
  7 => 
  array (
    0 => 'function.httpmessage-getheader.php',
    1 => 'HttpMessage::getHeader',
  ),
  8 => 
  array (
    0 => 'function.httpmessage-getheaders.php',
    1 => 'HttpMessage::getHeaders',
  ),
  9 => 
  array (
    0 => 'function.httpmessage-gethttpversion.php',
    1 => 'HttpMessage::getHttpVersion',
  ),
  10 => 
  array (
    0 => 'function.httpmessage-getparentmessage.php',
    1 => 'HttpMessage::getParentMessage',
  ),
  11 => 
  array (
    0 => 'function.httpmessage-getrequestmethod.php',
    1 => 'HttpMessage::getRequestMethod',
  ),
  12 => 
  array (
    0 => 'function.httpmessage-getrequesturl.php',
    1 => 'HttpMessage::getRequestUrl',
  ),
  13 => 
  array (
    0 => 'function.httpmessage-getresponsecode.php',
    1 => 'HttpMessage::getResponseCode',
  ),
  14 => 
  array (
    0 => 'function.httpmessage-getresponsestatus.php',
    1 => 'HttpMessage::getResponseStatus',
  ),
  15 => 
  array (
    0 => 'function.httpmessage-gettype.php',
    1 => 'HttpMessage::getType',
  ),
  16 => 
  array (
    0 => 'function.httpmessage-guesscontenttype.php',
    1 => 'HttpMessage::guessContentType',
  ),
  17 => 
  array (
    0 => 'function.httpmessage-prepend.php',
    1 => 'HttpMessage::prepend',
  ),
  18 => 
  array (
    0 => 'function.httpmessage-reverse.php',
    1 => 'HttpMessage::reverse',
  ),
  19 => 
  array (
    0 => 'function.httpmessage-send.php',
    1 => 'HttpMessage::send',
  ),
  20 => 
  array (
    0 => 'function.httpmessage-setbody.php',
    1 => 'HttpMessage::setBody',
  ),
  21 => 
  array (
    0 => 'function.httpmessage-setheaders.php',
    1 => 'HttpMessage::setHeaders',
  ),
  22 => 
  array (
    0 => 'function.httpmessage-sethttpversion.php',
    1 => 'HttpMessage::setHttpVersion',
  ),
  23 => 
  array (
    0 => 'function.httpmessage-setrequestmethod.php',
    1 => 'HttpMessage::setRequestMethod',
  ),
  24 => 
  array (
    0 => 'function.httpmessage-setrequesturl.php',
    1 => 'HttpMessage::setRequestUrl',
  ),
  25 => 
  array (
    0 => 'function.httpmessage-setresponsecode.php',
    1 => 'HttpMessage::setResponseCode',
  ),
  26 => 
  array (
    0 => 'function.httpmessage-setresponsestatus.php',
    1 => 'HttpMessage::setResponseStatus',
  ),
  27 => 
  array (
    0 => 'function.httpmessage-settype.php',
    1 => 'HttpMessage::setType',
  ),
  28 => 
  array (
    0 => 'function.httpmessage-tomessagetypeobject.php',
    1 => 'HttpMessage::toMessageTypeObject',
  ),
  29 => 
  array (
    0 => 'function.httpmessage-tostring.php',
    1 => 'HttpMessage::toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.http.php',
    1 => 'HTTP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);