<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.harudoc-addpage.php',
    1 => 'HaruDoc::addPage',
  ),
  1 => 
  array (
    0 => 'function.harudoc-addpagelabel.php',
    1 => 'HaruDoc::addPageLabel',
  ),
  2 => 
  array (
    0 => 'function.harudoc-construct.php',
    1 => 'HaruDoc::__construct',
  ),
  3 => 
  array (
    0 => 'function.harudoc-createoutline.php',
    1 => 'HaruDoc::createOutline',
  ),
  4 => 
  array (
    0 => 'function.harudoc-getcurrentencoder.php',
    1 => 'HaruDoc::getCurrentEncoder',
  ),
  5 => 
  array (
    0 => 'function.harudoc-getcurrentpage.php',
    1 => 'HaruDoc::getCurrentPage',
  ),
  6 => 
  array (
    0 => 'function.harudoc-getencoder.php',
    1 => 'HaruDoc::getEncoder',
  ),
  7 => 
  array (
    0 => 'function.harudoc-getfont.php',
    1 => 'HaruDoc::getFont',
  ),
  8 => 
  array (
    0 => 'function.harudoc-getinfoattr.php',
    1 => 'HaruDoc::getInfoAttr',
  ),
  9 => 
  array (
    0 => 'function.harudoc-getpagelayout.php',
    1 => 'HaruDoc::getPageLayout',
  ),
  10 => 
  array (
    0 => 'function.harudoc-getpagemode.php',
    1 => 'HaruDoc::getPageMode',
  ),
  11 => 
  array (
    0 => 'function.harudoc-getstreamsize.php',
    1 => 'HaruDoc::getStreamSize',
  ),
  12 => 
  array (
    0 => 'function.harudoc-insertpage.php',
    1 => 'HaruDoc::insertPage',
  ),
  13 => 
  array (
    0 => 'function.harudoc-loadjpeg.php',
    1 => 'HaruDoc::loadJPEG',
  ),
  14 => 
  array (
    0 => 'function.harudoc-loadpng.php',
    1 => 'HaruDoc::loadPNG',
  ),
  15 => 
  array (
    0 => 'function.harudoc-loadraw.php',
    1 => 'HaruDoc::loadRaw',
  ),
  16 => 
  array (
    0 => 'function.harudoc-loadttc.php',
    1 => 'HaruDoc::loadTTC',
  ),
  17 => 
  array (
    0 => 'function.harudoc-loadttf.php',
    1 => 'HaruDoc::loadTTF',
  ),
  18 => 
  array (
    0 => 'function.harudoc-loadtype1.php',
    1 => 'HaruDoc::loadType1',
  ),
  19 => 
  array (
    0 => 'function.harudoc-output.php',
    1 => 'HaruDoc::output',
  ),
  20 => 
  array (
    0 => 'function.harudoc-readfromstream.php',
    1 => 'HaruDoc::readFromStream',
  ),
  21 => 
  array (
    0 => 'function.harudoc-reseterror.php',
    1 => 'HaruDoc::resetError',
  ),
  22 => 
  array (
    0 => 'function.harudoc-resetstream.php',
    1 => 'HaruDoc::resetStream',
  ),
  23 => 
  array (
    0 => 'function.harudoc-save.php',
    1 => 'HaruDoc::save',
  ),
  24 => 
  array (
    0 => 'function.harudoc-savetostream.php',
    1 => 'HaruDoc::saveToStream',
  ),
  25 => 
  array (
    0 => 'function.harudoc-setcompressionmode.php',
    1 => 'HaruDoc::setCompressionMode',
  ),
  26 => 
  array (
    0 => 'function.harudoc-setcurrentencoder.php',
    1 => 'HaruDoc::setCurrentEncoder',
  ),
  27 => 
  array (
    0 => 'function.harudoc-setencryptionmode.php',
    1 => 'HaruDoc::setEncryptionMode',
  ),
  28 => 
  array (
    0 => 'function.harudoc-setinfoattr.php',
    1 => 'HaruDoc::setInfoAttr',
  ),
  29 => 
  array (
    0 => 'function.harudoc-setinfodateattr.php',
    1 => 'HaruDoc::setInfoDateAttr',
  ),
  30 => 
  array (
    0 => 'function.harudoc-setopenaction.php',
    1 => 'HaruDoc::setOpenAction',
  ),
  31 => 
  array (
    0 => 'function.harudoc-setpagelayout.php',
    1 => 'HaruDoc::setPageLayout',
  ),
  32 => 
  array (
    0 => 'function.harudoc-setpagemode.php',
    1 => 'HaruDoc::setPageMode',
  ),
  33 => 
  array (
    0 => 'function.harudoc-setpagesconfiguration.php',
    1 => 'HaruDoc::setPagesConfiguration',
  ),
  34 => 
  array (
    0 => 'function.harudoc-setpassword.php',
    1 => 'HaruDoc::setPassword',
  ),
  35 => 
  array (
    0 => 'function.harudoc-setpermission.php',
    1 => 'HaruDoc::setPermission',
  ),
  36 => 
  array (
    0 => 'function.harudoc-usecnsencodings.php',
    1 => 'HaruDoc::useCNSEncodings',
  ),
  37 => 
  array (
    0 => 'function.harudoc-usecnsfonts.php',
    1 => 'HaruDoc::useCNSFonts',
  ),
  38 => 
  array (
    0 => 'function.harudoc-usecntencodings.php',
    1 => 'HaruDoc::useCNTEncodings',
  ),
  39 => 
  array (
    0 => 'function.harudoc-usecntfonts.php',
    1 => 'HaruDoc::useCNTFonts',
  ),
  40 => 
  array (
    0 => 'function.harudoc-usejpencodings.php',
    1 => 'HaruDoc::useJPEncodings',
  ),
  41 => 
  array (
    0 => 'function.harudoc-usejpfonts.php',
    1 => 'HaruDoc::useJPFonts',
  ),
  42 => 
  array (
    0 => 'function.harudoc-usekrencodings.php',
    1 => 'HaruDoc::useKREncodings',
  ),
  43 => 
  array (
    0 => 'function.harudoc-usekrfonts.php',
    1 => 'HaruDoc::useKRFonts',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.haru.php',
    1 => 'haru',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);