<?php
$TOC = array (
  0 => 
  array (
    0 => 'apciterator.construct.php',
    1 => 'APCIterator::__construct',
  ),
  1 => 
  array (
    0 => 'apciterator.current.php',
    1 => 'APCIterator::current',
  ),
  2 => 
  array (
    0 => 'apciterator.gettotalcount.php',
    1 => 'APCIterator::getTotalCount',
  ),
  3 => 
  array (
    0 => 'apciterator.gettotalhits.php',
    1 => 'APCIterator::getTotalHits',
  ),
  4 => 
  array (
    0 => 'apciterator.gettotalsize.php',
    1 => 'APCIterator::getTotalSize',
  ),
  5 => 
  array (
    0 => 'apciterator.key.php',
    1 => 'APCIterator::key',
  ),
  6 => 
  array (
    0 => 'apciterator.next.php',
    1 => 'APCIterator::next',
  ),
  7 => 
  array (
    0 => 'apciterator.rewind.php',
    1 => 'APCIterator::rewind',
  ),
  8 => 
  array (
    0 => 'apciterator.valid.php',
    1 => 'APCIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.apc.php',
    1 => 'APC',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);