<?php
$TOC = array (
  0 => 
  array (
    0 => 'splheap.compare.php',
    1 => 'SplHeap::compare',
  ),
  1 => 
  array (
    0 => 'splheap.construct.php',
    1 => 'SplHeap::__construct',
  ),
  2 => 
  array (
    0 => 'splheap.count.php',
    1 => 'SplHeap::count',
  ),
  3 => 
  array (
    0 => 'splheap.current.php',
    1 => 'SplHeap::current',
  ),
  4 => 
  array (
    0 => 'splheap.extract.php',
    1 => 'SplHeap::extract',
  ),
  5 => 
  array (
    0 => 'splheap.insert.php',
    1 => 'SplHeap::insert',
  ),
  6 => 
  array (
    0 => 'splheap.isempty.php',
    1 => 'SplHeap::isEmpty',
  ),
  7 => 
  array (
    0 => 'splheap.key.php',
    1 => 'SplHeap::key',
  ),
  8 => 
  array (
    0 => 'splheap.next.php',
    1 => 'SplHeap::next',
  ),
  9 => 
  array (
    0 => 'splheap.recoverfromcorruption.php',
    1 => 'SplHeap::recoverFromCorruption',
  ),
  10 => 
  array (
    0 => 'splheap.rewind.php',
    1 => 'SplHeap::rewind',
  ),
  11 => 
  array (
    0 => 'splheap.top.php',
    1 => 'SplHeap::top',
  ),
  12 => 
  array (
    0 => 'splheap.valid.php',
    1 => 'SplHeap::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.datastructures.php',
    1 => 'Datastructures',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);