<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.imagickdraw-affine.php',
    1 => 'ImagickDraw::affine',
  ),
  1 => 
  array (
    0 => 'function.imagickdraw-annotation.php',
    1 => 'ImagickDraw::annotation',
  ),
  2 => 
  array (
    0 => 'function.imagickdraw-arc.php',
    1 => 'ImagickDraw::arc',
  ),
  3 => 
  array (
    0 => 'function.imagickdraw-bezier.php',
    1 => 'ImagickDraw::bezier',
  ),
  4 => 
  array (
    0 => 'function.imagickdraw-circle.php',
    1 => 'ImagickDraw::circle',
  ),
  5 => 
  array (
    0 => 'function.imagickdraw-clear.php',
    1 => 'ImagickDraw::clear',
  ),
  6 => 
  array (
    0 => 'function.imagickdraw-clone.php',
    1 => 'ImagickDraw::clone',
  ),
  7 => 
  array (
    0 => 'function.imagickdraw-color.php',
    1 => 'ImagickDraw::color',
  ),
  8 => 
  array (
    0 => 'function.imagickdraw-comment.php',
    1 => 'ImagickDraw::comment',
  ),
  9 => 
  array (
    0 => 'function.imagickdraw-composite.php',
    1 => 'ImagickDraw::composite',
  ),
  10 => 
  array (
    0 => 'function.imagickdraw-construct.php',
    1 => 'ImagickDraw::__construct',
  ),
  11 => 
  array (
    0 => 'function.imagickdraw-destroy.php',
    1 => 'ImagickDraw::destroy',
  ),
  12 => 
  array (
    0 => 'function.imagickdraw-ellipse.php',
    1 => 'ImagickDraw::ellipse',
  ),
  13 => 
  array (
    0 => 'function.imagickdraw-getclippath.php',
    1 => 'ImagickDraw::getClipPath',
  ),
  14 => 
  array (
    0 => 'function.imagickdraw-getcliprule.php',
    1 => 'ImagickDraw::getClipRule',
  ),
  15 => 
  array (
    0 => 'function.imagickdraw-getclipunits.php',
    1 => 'ImagickDraw::getClipUnits',
  ),
  16 => 
  array (
    0 => 'function.imagickdraw-getfillcolor.php',
    1 => 'ImagickDraw::getFillColor',
  ),
  17 => 
  array (
    0 => 'function.imagickdraw-getfillopacity.php',
    1 => 'ImagickDraw::getFillOpacity',
  ),
  18 => 
  array (
    0 => 'function.imagickdraw-getfillrule.php',
    1 => 'ImagickDraw::getFillRule',
  ),
  19 => 
  array (
    0 => 'function.imagickdraw-getfont.php',
    1 => 'ImagickDraw::getFont',
  ),
  20 => 
  array (
    0 => 'function.imagickdraw-getfontfamily.php',
    1 => 'ImagickDraw::getFontFamily',
  ),
  21 => 
  array (
    0 => 'function.imagickdraw-getfontsize.php',
    1 => 'ImagickDraw::getFontSize',
  ),
  22 => 
  array (
    0 => 'function.imagickdraw-getfontstyle.php',
    1 => 'ImagickDraw::getFontStyle',
  ),
  23 => 
  array (
    0 => 'function.imagickdraw-getfontweight.php',
    1 => 'ImagickDraw::getFontWeight',
  ),
  24 => 
  array (
    0 => 'function.imagickdraw-getgravity.php',
    1 => 'ImagickDraw::getGravity',
  ),
  25 => 
  array (
    0 => 'function.imagickdraw-getstrokeantialias.php',
    1 => 'ImagickDraw::getStrokeAntialias',
  ),
  26 => 
  array (
    0 => 'function.imagickdraw-getstrokecolor.php',
    1 => 'ImagickDraw::getStrokeColor',
  ),
  27 => 
  array (
    0 => 'function.imagickdraw-getstrokedasharray.php',
    1 => 'ImagickDraw::getStrokeDashArray',
  ),
  28 => 
  array (
    0 => 'function.imagickdraw-getstrokedashoffset.php',
    1 => 'ImagickDraw::getStrokeDashOffset',
  ),
  29 => 
  array (
    0 => 'function.imagickdraw-getstrokelinecap.php',
    1 => 'ImagickDraw::getStrokeLineCap',
  ),
  30 => 
  array (
    0 => 'function.imagickdraw-getstrokelinejoin.php',
    1 => 'ImagickDraw::getStrokeLineJoin',
  ),
  31 => 
  array (
    0 => 'function.imagickdraw-getstrokemiterlimit.php',
    1 => 'ImagickDraw::getStrokeMiterLimit',
  ),
  32 => 
  array (
    0 => 'function.imagickdraw-getstrokeopacity.php',
    1 => 'ImagickDraw::getStrokeOpacity',
  ),
  33 => 
  array (
    0 => 'function.imagickdraw-getstrokewidth.php',
    1 => 'ImagickDraw::getStrokeWidth',
  ),
  34 => 
  array (
    0 => 'function.imagickdraw-gettextalignment.php',
    1 => 'ImagickDraw::getTextAlignment',
  ),
  35 => 
  array (
    0 => 'function.imagickdraw-gettextantialias.php',
    1 => 'ImagickDraw::getTextAntialias',
  ),
  36 => 
  array (
    0 => 'function.imagickdraw-gettextdecoration.php',
    1 => 'ImagickDraw::getTextDecoration',
  ),
  37 => 
  array (
    0 => 'function.imagickdraw-gettextencoding.php',
    1 => 'ImagickDraw::getTextEncoding',
  ),
  38 => 
  array (
    0 => 'function.imagickdraw-gettextundercolor.php',
    1 => 'ImagickDraw::getTextUnderColor',
  ),
  39 => 
  array (
    0 => 'function.imagickdraw-getvectorgraphics.php',
    1 => 'ImagickDraw::getVectorGraphics',
  ),
  40 => 
  array (
    0 => 'function.imagickdraw-line.php',
    1 => 'ImagickDraw::line',
  ),
  41 => 
  array (
    0 => 'function.imagickdraw-matte.php',
    1 => 'ImagickDraw::matte',
  ),
  42 => 
  array (
    0 => 'function.imagickdraw-pathclose.php',
    1 => 'ImagickDraw::pathClose',
  ),
  43 => 
  array (
    0 => 'function.imagickdraw-pathcurvetoabsolute.php',
    1 => 'ImagickDraw::pathCurveToAbsolute',
  ),
  44 => 
  array (
    0 => 'function.imagickdraw-pathcurvetoquadraticbezierabsolute.php',
    1 => 'ImagickDraw::pathCurveToQuadraticBezierAbsolute',
  ),
  45 => 
  array (
    0 => 'function.imagickdraw-pathcurvetoquadraticbezierrelative.php',
    1 => 'ImagickDraw::pathCurveToQuadraticBezierRelative',
  ),
  46 => 
  array (
    0 => 'function.imagickdraw-pathcurvetoquadraticbeziersmoothabsolute.php',
    1 => 'ImagickDraw::pathCurveToQuadraticBezierSmoothAbsolute',
  ),
  47 => 
  array (
    0 => 'function.imagickdraw-pathcurvetoquadraticbeziersmoothrelative.php',
    1 => 'ImagickDraw::pathCurveToQuadraticBezierSmoothRelative',
  ),
  48 => 
  array (
    0 => 'function.imagickdraw-pathcurvetorelative.php',
    1 => 'ImagickDraw::pathCurveToRelative',
  ),
  49 => 
  array (
    0 => 'function.imagickdraw-pathcurvetosmoothabsolute.php',
    1 => 'ImagickDraw::pathCurveToSmoothAbsolute',
  ),
  50 => 
  array (
    0 => 'function.imagickdraw-pathcurvetosmoothrelative.php',
    1 => 'ImagickDraw::pathCurveToSmoothRelative',
  ),
  51 => 
  array (
    0 => 'function.imagickdraw-pathellipticarcabsolute.php',
    1 => 'ImagickDraw::pathEllipticArcAbsolute',
  ),
  52 => 
  array (
    0 => 'function.imagickdraw-pathellipticarcrelative.php',
    1 => 'ImagickDraw::pathEllipticArcRelative',
  ),
  53 => 
  array (
    0 => 'function.imagickdraw-pathfinish.php',
    1 => 'ImagickDraw::pathFinish',
  ),
  54 => 
  array (
    0 => 'function.imagickdraw-pathlinetoabsolute.php',
    1 => 'ImagickDraw::pathLineToAbsolute',
  ),
  55 => 
  array (
    0 => 'function.imagickdraw-pathlinetohorizontalabsolute.php',
    1 => 'ImagickDraw::pathLineToHorizontalAbsolute',
  ),
  56 => 
  array (
    0 => 'function.imagickdraw-pathlinetohorizontalrelative.php',
    1 => 'ImagickDraw::pathLineToHorizontalRelative',
  ),
  57 => 
  array (
    0 => 'function.imagickdraw-pathlinetorelative.php',
    1 => 'ImagickDraw::pathLineToRelative',
  ),
  58 => 
  array (
    0 => 'function.imagickdraw-pathlinetoverticalabsolute.php',
    1 => 'ImagickDraw::pathLineToVerticalAbsolute',
  ),
  59 => 
  array (
    0 => 'function.imagickdraw-pathlinetoverticalrelative.php',
    1 => 'ImagickDraw::pathLineToVerticalRelative',
  ),
  60 => 
  array (
    0 => 'function.imagickdraw-pathmovetoabsolute.php',
    1 => 'ImagickDraw::pathMoveToAbsolute',
  ),
  61 => 
  array (
    0 => 'function.imagickdraw-pathmovetorelative.php',
    1 => 'ImagickDraw::pathMoveToRelative',
  ),
  62 => 
  array (
    0 => 'function.imagickdraw-pathstart.php',
    1 => 'ImagickDraw::pathStart',
  ),
  63 => 
  array (
    0 => 'function.imagickdraw-point.php',
    1 => 'ImagickDraw::point',
  ),
  64 => 
  array (
    0 => 'function.imagickdraw-polygon.php',
    1 => 'ImagickDraw::polygon',
  ),
  65 => 
  array (
    0 => 'function.imagickdraw-polyline.php',
    1 => 'ImagickDraw::polyline',
  ),
  66 => 
  array (
    0 => 'function.imagickdraw-pop.php',
    1 => 'ImagickDraw::pop',
  ),
  67 => 
  array (
    0 => 'function.imagickdraw-popclippath.php',
    1 => 'ImagickDraw::popClipPath',
  ),
  68 => 
  array (
    0 => 'function.imagickdraw-popdefs.php',
    1 => 'ImagickDraw::popDefs',
  ),
  69 => 
  array (
    0 => 'function.imagickdraw-poppattern.php',
    1 => 'ImagickDraw::popPattern',
  ),
  70 => 
  array (
    0 => 'function.imagickdraw-push.php',
    1 => 'ImagickDraw::push',
  ),
  71 => 
  array (
    0 => 'function.imagickdraw-pushclippath.php',
    1 => 'ImagickDraw::pushClipPath',
  ),
  72 => 
  array (
    0 => 'function.imagickdraw-pushdefs.php',
    1 => 'ImagickDraw::pushDefs',
  ),
  73 => 
  array (
    0 => 'function.imagickdraw-pushpattern.php',
    1 => 'ImagickDraw::pushPattern',
  ),
  74 => 
  array (
    0 => 'function.imagickdraw-rectangle.php',
    1 => 'ImagickDraw::rectangle',
  ),
  75 => 
  array (
    0 => 'function.imagickdraw-render.php',
    1 => 'ImagickDraw::render',
  ),
  76 => 
  array (
    0 => 'function.imagickdraw-rotate.php',
    1 => 'ImagickDraw::rotate',
  ),
  77 => 
  array (
    0 => 'function.imagickdraw-roundrectangle.php',
    1 => 'ImagickDraw::roundRectangle',
  ),
  78 => 
  array (
    0 => 'function.imagickdraw-scale.php',
    1 => 'ImagickDraw::scale',
  ),
  79 => 
  array (
    0 => 'function.imagickdraw-setclippath.php',
    1 => 'ImagickDraw::setClipPath',
  ),
  80 => 
  array (
    0 => 'function.imagickdraw-setcliprule.php',
    1 => 'ImagickDraw::setClipRule',
  ),
  81 => 
  array (
    0 => 'function.imagickdraw-setclipunits.php',
    1 => 'ImagickDraw::setClipUnits',
  ),
  82 => 
  array (
    0 => 'function.imagickdraw-setfillalpha.php',
    1 => 'ImagickDraw::setFillAlpha',
  ),
  83 => 
  array (
    0 => 'function.imagickdraw-setfillcolor.php',
    1 => 'ImagickDraw::setFillColor',
  ),
  84 => 
  array (
    0 => 'function.imagickdraw-setfillopacity.php',
    1 => 'ImagickDraw::setFillOpacity',
  ),
  85 => 
  array (
    0 => 'function.imagickdraw-setfillpatternurl.php',
    1 => 'ImagickDraw::setFillPatternURL',
  ),
  86 => 
  array (
    0 => 'function.imagickdraw-setfillrule.php',
    1 => 'ImagickDraw::setFillRule',
  ),
  87 => 
  array (
    0 => 'function.imagickdraw-setfont.php',
    1 => 'ImagickDraw::setFont',
  ),
  88 => 
  array (
    0 => 'function.imagickdraw-setfontfamily.php',
    1 => 'ImagickDraw::setFontFamily',
  ),
  89 => 
  array (
    0 => 'function.imagickdraw-setfontsize.php',
    1 => 'ImagickDraw::setFontSize',
  ),
  90 => 
  array (
    0 => 'function.imagickdraw-setfontstretch.php',
    1 => 'ImagickDraw::setFontStretch',
  ),
  91 => 
  array (
    0 => 'function.imagickdraw-setfontstyle.php',
    1 => 'ImagickDraw::setFontStyle',
  ),
  92 => 
  array (
    0 => 'function.imagickdraw-setfontweight.php',
    1 => 'ImagickDraw::setFontWeight',
  ),
  93 => 
  array (
    0 => 'function.imagickdraw-setgravity.php',
    1 => 'ImagickDraw::setGravity',
  ),
  94 => 
  array (
    0 => 'function.imagickdraw-setstrokealpha.php',
    1 => 'ImagickDraw::setStrokeAlpha',
  ),
  95 => 
  array (
    0 => 'function.imagickdraw-setstrokeantialias.php',
    1 => 'ImagickDraw::setStrokeAntialias',
  ),
  96 => 
  array (
    0 => 'function.imagickdraw-setstrokecolor.php',
    1 => 'ImagickDraw::setStrokeColor',
  ),
  97 => 
  array (
    0 => 'function.imagickdraw-setstrokedasharray.php',
    1 => 'ImagickDraw::setStrokeDashArray',
  ),
  98 => 
  array (
    0 => 'function.imagickdraw-setstrokedashoffset.php',
    1 => 'ImagickDraw::setStrokeDashOffset',
  ),
  99 => 
  array (
    0 => 'function.imagickdraw-setstrokelinecap.php',
    1 => 'ImagickDraw::setStrokeLineCap',
  ),
  100 => 
  array (
    0 => 'function.imagickdraw-setstrokelinejoin.php',
    1 => 'ImagickDraw::setStrokeLineJoin',
  ),
  101 => 
  array (
    0 => 'function.imagickdraw-setstrokemiterlimit.php',
    1 => 'ImagickDraw::setStrokeMiterLimit',
  ),
  102 => 
  array (
    0 => 'function.imagickdraw-setstrokeopacity.php',
    1 => 'ImagickDraw::setStrokeOpacity',
  ),
  103 => 
  array (
    0 => 'function.imagickdraw-setstrokepatternurl.php',
    1 => 'ImagickDraw::setStrokePatternURL',
  ),
  104 => 
  array (
    0 => 'function.imagickdraw-setstrokewidth.php',
    1 => 'ImagickDraw::setStrokeWidth',
  ),
  105 => 
  array (
    0 => 'function.imagickdraw-settextalignment.php',
    1 => 'ImagickDraw::setTextAlignment',
  ),
  106 => 
  array (
    0 => 'function.imagickdraw-settextantialias.php',
    1 => 'ImagickDraw::setTextAntialias',
  ),
  107 => 
  array (
    0 => 'function.imagickdraw-settextdecoration.php',
    1 => 'ImagickDraw::setTextDecoration',
  ),
  108 => 
  array (
    0 => 'function.imagickdraw-settextencoding.php',
    1 => 'ImagickDraw::setTextEncoding',
  ),
  109 => 
  array (
    0 => 'function.imagickdraw-settextundercolor.php',
    1 => 'ImagickDraw::setTextUnderColor',
  ),
  110 => 
  array (
    0 => 'function.imagickdraw-setvectorgraphics.php',
    1 => 'ImagickDraw::setVectorGraphics',
  ),
  111 => 
  array (
    0 => 'function.imagickdraw-setviewbox.php',
    1 => 'ImagickDraw::setViewbox',
  ),
  112 => 
  array (
    0 => 'function.imagickdraw-skewx.php',
    1 => 'ImagickDraw::skewX',
  ),
  113 => 
  array (
    0 => 'function.imagickdraw-skewy.php',
    1 => 'ImagickDraw::skewY',
  ),
  114 => 
  array (
    0 => 'function.imagickdraw-translate.php',
    1 => 'ImagickDraw::translate',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.imagick.php',
    1 => 'ImageMagick',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);