<?php
$TOC = array (
  0 => 
  array (
    0 => 'solrclient.adddocument.php',
    1 => 'SolrClient::addDocument',
  ),
  1 => 
  array (
    0 => 'solrclient.adddocuments.php',
    1 => 'SolrClient::addDocuments',
  ),
  2 => 
  array (
    0 => 'solrclient.commit.php',
    1 => 'SolrClient::commit',
  ),
  3 => 
  array (
    0 => 'solrclient.construct.php',
    1 => 'SolrClient::__construct',
  ),
  4 => 
  array (
    0 => 'solrclient.deletebyid.php',
    1 => 'SolrClient::deleteById',
  ),
  5 => 
  array (
    0 => 'solrclient.deletebyids.php',
    1 => 'SolrClient::deleteByIds',
  ),
  6 => 
  array (
    0 => 'solrclient.deletebyqueries.php',
    1 => 'SolrClient::deleteByQueries',
  ),
  7 => 
  array (
    0 => 'solrclient.deletebyquery.php',
    1 => 'SolrClient::deleteByQuery',
  ),
  8 => 
  array (
    0 => 'solrclient.destruct.php',
    1 => 'SolrClient::__destruct',
  ),
  9 => 
  array (
    0 => 'solrclient.getdebug.php',
    1 => 'SolrClient::getDebug',
  ),
  10 => 
  array (
    0 => 'solrclient.getoptions.php',
    1 => 'SolrClient::getOptions',
  ),
  11 => 
  array (
    0 => 'solrclient.optimize.php',
    1 => 'SolrClient::optimize',
  ),
  12 => 
  array (
    0 => 'solrclient.ping.php',
    1 => 'SolrClient::ping',
  ),
  13 => 
  array (
    0 => 'solrclient.query.php',
    1 => 'SolrClient::query',
  ),
  14 => 
  array (
    0 => 'solrclient.request.php',
    1 => 'SolrClient::request',
  ),
  15 => 
  array (
    0 => 'solrclient.rollback.php',
    1 => 'SolrClient::rollback',
  ),
  16 => 
  array (
    0 => 'solrclient.setresponsewriter.php',
    1 => 'SolrClient::setResponseWriter',
  ),
  17 => 
  array (
    0 => 'solrclient.setservlet.php',
    1 => 'SolrClient::setServlet',
  ),
  18 => 
  array (
    0 => 'solrclient.threads.php',
    1 => 'SolrClient::threads',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.solr.php',
    1 => 'Solr',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);