<?php
$TOC = array (
  0 => 
  array (
    0 => 'mongocursor.addoption.php',
    1 => 'MongoCursor::addOption',
  ),
  1 => 
  array (
    0 => 'mongocursor.batchsize.php',
    1 => 'MongoCursor::batchSize',
  ),
  2 => 
  array (
    0 => 'mongocursor.construct.php',
    1 => 'MongoCursor::__construct',
  ),
  3 => 
  array (
    0 => 'mongocursor.count.php',
    1 => 'MongoCursor::count',
  ),
  4 => 
  array (
    0 => 'mongocursor.current.php',
    1 => 'MongoCursor::current',
  ),
  5 => 
  array (
    0 => 'mongocursor.dead.php',
    1 => 'MongoCursor::dead',
  ),
  6 => 
  array (
    0 => 'mongocursor.doquery.php',
    1 => 'MongoCursor::doQuery',
  ),
  7 => 
  array (
    0 => 'mongocursor.explain.php',
    1 => 'MongoCursor::explain',
  ),
  8 => 
  array (
    0 => 'mongocursor.fields.php',
    1 => 'MongoCursor::fields',
  ),
  9 => 
  array (
    0 => 'mongocursor.getnext.php',
    1 => 'MongoCursor::getNext',
  ),
  10 => 
  array (
    0 => 'mongocursor.hasnext.php',
    1 => 'MongoCursor::hasNext',
  ),
  11 => 
  array (
    0 => 'mongocursor.hint.php',
    1 => 'MongoCursor::hint',
  ),
  12 => 
  array (
    0 => 'mongocursor.immortal.php',
    1 => 'MongoCursor::immortal',
  ),
  13 => 
  array (
    0 => 'mongocursor.info.php',
    1 => 'MongoCursor::info',
  ),
  14 => 
  array (
    0 => 'mongocursor.key.php',
    1 => 'MongoCursor::key',
  ),
  15 => 
  array (
    0 => 'mongocursor.limit.php',
    1 => 'MongoCursor::limit',
  ),
  16 => 
  array (
    0 => 'mongocursor.next.php',
    1 => 'MongoCursor::next',
  ),
  17 => 
  array (
    0 => 'mongocursor.reset.php',
    1 => 'MongoCursor::reset',
  ),
  18 => 
  array (
    0 => 'mongocursor.rewind.php',
    1 => 'MongoCursor::rewind',
  ),
  19 => 
  array (
    0 => 'mongocursor.skip.php',
    1 => 'MongoCursor::skip',
  ),
  20 => 
  array (
    0 => 'mongocursor.slaveokay.php',
    1 => 'MongoCursor::slaveOkay',
  ),
  21 => 
  array (
    0 => 'mongocursor.snapshot.php',
    1 => 'MongoCursor::snapshot',
  ),
  22 => 
  array (
    0 => 'mongocursor.sort.php',
    1 => 'MongoCursor::sort',
  ),
  23 => 
  array (
    0 => 'mongocursor.tailable.php',
    1 => 'MongoCursor::tailable',
  ),
  24 => 
  array (
    0 => 'mongocursor.timeout.php',
    1 => 'MongoCursor::timeout',
  ),
  25 => 
  array (
    0 => 'mongocursor.valid.php',
    1 => 'MongoCursor::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'mongo.core.php',
    1 => 'Core Classes',
  ),
  1 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  2 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  3 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  4 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  5 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);