<?php
$TOC = array (
  0 => 
  array (
    0 => 'iterator.current.php',
    1 => 'Iterator::current',
  ),
  1 => 
  array (
    0 => 'iterator.key.php',
    1 => 'Iterator::key',
  ),
  2 => 
  array (
    0 => 'iterator.next.php',
    1 => 'Iterator::next',
  ),
  3 => 
  array (
    0 => 'iterator.rewind.php',
    1 => 'Iterator::rewind',
  ),
  4 => 
  array (
    0 => 'iterator.valid.php',
    1 => 'Iterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'reserved.interfaces.php',
    1 => 'Predefined Interfaces',
  ),
  1 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);