<?php
$TOC = array (
  0 => 
  array (
    0 => 'messageformatter.create.php',
    1 => 'MessageFormatter::create',
  ),
  1 => 
  array (
    0 => 'messageformatter.formatmessage.php',
    1 => 'MessageFormatter::formatMessage',
  ),
  2 => 
  array (
    0 => 'messageformatter.format.php',
    1 => 'MessageFormatter::format',
  ),
  3 => 
  array (
    0 => 'messageformatter.geterrorcode.php',
    1 => 'MessageFormatter::getErrorCode',
  ),
  4 => 
  array (
    0 => 'messageformatter.geterrormessage.php',
    1 => 'MessageFormatter::getErrorMessage',
  ),
  5 => 
  array (
    0 => 'messageformatter.getlocale.php',
    1 => 'MessageFormatter::getLocale',
  ),
  6 => 
  array (
    0 => 'messageformatter.getpattern.php',
    1 => 'MessageFormatter::getPattern',
  ),
  7 => 
  array (
    0 => 'messageformatter.parsemessage.php',
    1 => 'MessageFormatter::parseMessage',
  ),
  8 => 
  array (
    0 => 'messageformatter.parse.php',
    1 => 'MessageFormatter::parse',
  ),
  9 => 
  array (
    0 => 'messageformatter.setpattern.php',
    1 => 'MessageFormatter::setPattern',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.intl.php',
    1 => 'intl',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);