<?php
$TOC = array (
  0 => 
  array (
    0 => 'recursivecachingiterator.construct.php',
    1 => 'RecursiveCachingIterator::__construct',
  ),
  1 => 
  array (
    0 => 'recursivecachingiterator.getchildren.php',
    1 => 'RecursiveCachingIterator::getChildren',
  ),
  2 => 
  array (
    0 => 'recursivecachingiterator.haschildren.php',
    1 => 'RecursiveCachingIterator::hasChildren',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);