<?php
$TOC = array (
  0 => 
  array (
    0 => 'splsubject.attach.php',
    1 => 'SplSubject::attach',
  ),
  1 => 
  array (
    0 => 'splsubject.detach.php',
    1 => 'SplSubject::detach',
  ),
  2 => 
  array (
    0 => 'splsubject.notify.php',
    1 => 'SplSubject::notify',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.misc.php',
    1 => 'Miscellaneous Classes and Interfaces',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);