<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairomatrix.construct.php',
    1 => 'CairoMatrix::__construct',
  ),
  1 => 
  array (
    0 => 'cairomatrix.initidentity.php',
    1 => 'CairoMatrix::initIdentity',
  ),
  2 => 
  array (
    0 => 'cairomatrix.initrotate.php',
    1 => 'CairoMatrix::initRotate',
  ),
  3 => 
  array (
    0 => 'cairomatrix.initscale.php',
    1 => 'CairoMatrix::initScale',
  ),
  4 => 
  array (
    0 => 'cairomatrix.inittranslate.php',
    1 => 'CairoMatrix::initTranslate',
  ),
  5 => 
  array (
    0 => 'cairomatrix.invert.php',
    1 => 'CairoMatrix::invert',
  ),
  6 => 
  array (
    0 => 'cairomatrix.multiply.php',
    1 => 'CairoMatrix::multiply',
  ),
  7 => 
  array (
    0 => 'cairomatrix.rotate.php',
    1 => 'CairoMatrix::rotate',
  ),
  8 => 
  array (
    0 => 'cairomatrix.scale.php',
    1 => 'CairoMatrix::scale',
  ),
  9 => 
  array (
    0 => 'cairomatrix.transformdistance.php',
    1 => 'CairoMatrix::transformDistance',
  ),
  10 => 
  array (
    0 => 'cairomatrix.transformpoint.php',
    1 => 'CairoMatrix::transformPoint',
  ),
  11 => 
  array (
    0 => 'cairomatrix.translate.php',
    1 => 'CairoMatrix::translate',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);