<?php
$TOC = array (
  0 => 
  array (
    0 => 'reflectionextension.clone.php',
    1 => 'ReflectionExtension::__clone',
  ),
  1 => 
  array (
    0 => 'reflectionextension.construct.php',
    1 => 'ReflectionExtension::__construct',
  ),
  2 => 
  array (
    0 => 'reflectionextension.export.php',
    1 => 'ReflectionExtension::export',
  ),
  3 => 
  array (
    0 => 'reflectionextension.getclasses.php',
    1 => 'ReflectionExtension::getClasses',
  ),
  4 => 
  array (
    0 => 'reflectionextension.getclassnames.php',
    1 => 'ReflectionExtension::getClassNames',
  ),
  5 => 
  array (
    0 => 'reflectionextension.getconstants.php',
    1 => 'ReflectionExtension::getConstants',
  ),
  6 => 
  array (
    0 => 'reflectionextension.getdependencies.php',
    1 => 'ReflectionExtension::getDependencies',
  ),
  7 => 
  array (
    0 => 'reflectionextension.getfunctions.php',
    1 => 'ReflectionExtension::getFunctions',
  ),
  8 => 
  array (
    0 => 'reflectionextension.getinientries.php',
    1 => 'ReflectionExtension::getINIEntries',
  ),
  9 => 
  array (
    0 => 'reflectionextension.getname.php',
    1 => 'ReflectionExtension::getName',
  ),
  10 => 
  array (
    0 => 'reflectionextension.getversion.php',
    1 => 'ReflectionExtension::getVersion',
  ),
  11 => 
  array (
    0 => 'reflectionextension.info.php',
    1 => 'ReflectionExtension::info',
  ),
  12 => 
  array (
    0 => 'reflectionextension.tostring.php',
    1 => 'ReflectionExtension::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.reflection.php',
    1 => 'Reflection',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);