<?php
$TOC = array (
  0 => 
  array (
    0 => 'gearmantask.construct.php',
    1 => 'GearmanTask::__construct',
  ),
  1 => 
  array (
    0 => 'gearmantask.create.php',
    1 => 'GearmanTask::create',
  ),
  2 => 
  array (
    0 => 'gearmantask.data.php',
    1 => 'GearmanTask::data',
  ),
  3 => 
  array (
    0 => 'gearmantask.datasize.php',
    1 => 'GearmanTask::dataSize',
  ),
  4 => 
  array (
    0 => 'gearmantask.function.php',
    1 => 'GearmanTask::function',
  ),
  5 => 
  array (
    0 => 'gearmantask.functionname.php',
    1 => 'GearmanTask::functionName',
  ),
  6 => 
  array (
    0 => 'gearmantask.isknown.php',
    1 => 'GearmanTask::isKnown',
  ),
  7 => 
  array (
    0 => 'gearmantask.isrunning.php',
    1 => 'GearmanTask::isRunning',
  ),
  8 => 
  array (
    0 => 'gearmantask.jobhandle.php',
    1 => 'GearmanTask::jobHandle',
  ),
  9 => 
  array (
    0 => 'gearmantask.recvdata.php',
    1 => 'GearmanTask::recvData',
  ),
  10 => 
  array (
    0 => 'gearmantask.returncode.php',
    1 => 'GearmanTask::returnCode',
  ),
  11 => 
  array (
    0 => 'gearmantask.senddata.php',
    1 => 'GearmanTask::sendData',
  ),
  12 => 
  array (
    0 => 'gearmantask.sendworkload.php',
    1 => 'GearmanTask::sendWorkload',
  ),
  13 => 
  array (
    0 => 'gearmantask.taskdenominator.php',
    1 => 'GearmanTask::taskDenominator',
  ),
  14 => 
  array (
    0 => 'gearmantask.tasknumerator.php',
    1 => 'GearmanTask::taskNumerator',
  ),
  15 => 
  array (
    0 => 'gearmantask.unique.php',
    1 => 'GearmanTask::unique',
  ),
  16 => 
  array (
    0 => 'gearmantask.uuid.php',
    1 => 'GearmanTask::uuid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gearman.php',
    1 => 'Gearman',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);