<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.harupage-arc.php',
    1 => 'HaruPage::arc',
  ),
  1 => 
  array (
    0 => 'function.harupage-begintext.php',
    1 => 'HaruPage::beginText',
  ),
  2 => 
  array (
    0 => 'function.harupage-circle.php',
    1 => 'HaruPage::circle',
  ),
  3 => 
  array (
    0 => 'function.harupage-closepath.php',
    1 => 'HaruPage::closePath',
  ),
  4 => 
  array (
    0 => 'function.harupage-concat.php',
    1 => 'HaruPage::concat',
  ),
  5 => 
  array (
    0 => 'function.harupage-createdestination.php',
    1 => 'HaruPage::createDestination',
  ),
  6 => 
  array (
    0 => 'function.harupage-createlinkannotation.php',
    1 => 'HaruPage::createLinkAnnotation',
  ),
  7 => 
  array (
    0 => 'function.harupage-createtextannotation.php',
    1 => 'HaruPage::createTextAnnotation',
  ),
  8 => 
  array (
    0 => 'function.harupage-createurlannotation.php',
    1 => 'HaruPage::createURLAnnotation',
  ),
  9 => 
  array (
    0 => 'function.harupage-curveto2.php',
    1 => 'HaruPage::curveTo2',
  ),
  10 => 
  array (
    0 => 'function.harupage-curveto3.php',
    1 => 'HaruPage::curveTo3',
  ),
  11 => 
  array (
    0 => 'function.harupage-curveto.php',
    1 => 'HaruPage::curveTo',
  ),
  12 => 
  array (
    0 => 'function.harupage-drawimage.php',
    1 => 'HaruPage::drawImage',
  ),
  13 => 
  array (
    0 => 'function.harupage-ellipse.php',
    1 => 'HaruPage::ellipse',
  ),
  14 => 
  array (
    0 => 'function.harupage-endpath.php',
    1 => 'HaruPage::endPath',
  ),
  15 => 
  array (
    0 => 'function.harupage-endtext.php',
    1 => 'HaruPage::endText',
  ),
  16 => 
  array (
    0 => 'function.harupage-eofill.php',
    1 => 'HaruPage::eofill',
  ),
  17 => 
  array (
    0 => 'function.harupage-eofillstroke.php',
    1 => 'HaruPage::eoFillStroke',
  ),
  18 => 
  array (
    0 => 'function.harupage-fill.php',
    1 => 'HaruPage::fill',
  ),
  19 => 
  array (
    0 => 'function.harupage-fillstroke.php',
    1 => 'HaruPage::fillStroke',
  ),
  20 => 
  array (
    0 => 'function.harupage-getcharspace.php',
    1 => 'HaruPage::getCharSpace',
  ),
  21 => 
  array (
    0 => 'function.harupage-getcmykfill.php',
    1 => 'HaruPage::getCMYKFill',
  ),
  22 => 
  array (
    0 => 'function.harupage-getcmykstroke.php',
    1 => 'HaruPage::getCMYKStroke',
  ),
  23 => 
  array (
    0 => 'function.harupage-getcurrentfont.php',
    1 => 'HaruPage::getCurrentFont',
  ),
  24 => 
  array (
    0 => 'function.harupage-getcurrentfontsize.php',
    1 => 'HaruPage::getCurrentFontSize',
  ),
  25 => 
  array (
    0 => 'function.harupage-getcurrentpos.php',
    1 => 'HaruPage::getCurrentPos',
  ),
  26 => 
  array (
    0 => 'function.harupage-getcurrenttextpos.php',
    1 => 'HaruPage::getCurrentTextPos',
  ),
  27 => 
  array (
    0 => 'function.harupage-getdash.php',
    1 => 'HaruPage::getDash',
  ),
  28 => 
  array (
    0 => 'function.harupage-getfillingcolorspace.php',
    1 => 'HaruPage::getFillingColorSpace',
  ),
  29 => 
  array (
    0 => 'function.harupage-getflatness.php',
    1 => 'HaruPage::getFlatness',
  ),
  30 => 
  array (
    0 => 'function.harupage-getgmode.php',
    1 => 'HaruPage::getGMode',
  ),
  31 => 
  array (
    0 => 'function.harupage-getgrayfill.php',
    1 => 'HaruPage::getGrayFill',
  ),
  32 => 
  array (
    0 => 'function.harupage-getgraystroke.php',
    1 => 'HaruPage::getGrayStroke',
  ),
  33 => 
  array (
    0 => 'function.harupage-getheight.php',
    1 => 'HaruPage::getHeight',
  ),
  34 => 
  array (
    0 => 'function.harupage-gethorizontalscaling.php',
    1 => 'HaruPage::getHorizontalScaling',
  ),
  35 => 
  array (
    0 => 'function.harupage-getlinecap.php',
    1 => 'HaruPage::getLineCap',
  ),
  36 => 
  array (
    0 => 'function.harupage-getlinejoin.php',
    1 => 'HaruPage::getLineJoin',
  ),
  37 => 
  array (
    0 => 'function.harupage-getlinewidth.php',
    1 => 'HaruPage::getLineWidth',
  ),
  38 => 
  array (
    0 => 'function.harupage-getmiterlimit.php',
    1 => 'HaruPage::getMiterLimit',
  ),
  39 => 
  array (
    0 => 'function.harupage-getrgbfill.php',
    1 => 'HaruPage::getRGBFill',
  ),
  40 => 
  array (
    0 => 'function.harupage-getrgbstroke.php',
    1 => 'HaruPage::getRGBStroke',
  ),
  41 => 
  array (
    0 => 'function.harupage-getstrokingcolorspace.php',
    1 => 'HaruPage::getStrokingColorSpace',
  ),
  42 => 
  array (
    0 => 'function.harupage-gettextleading.php',
    1 => 'HaruPage::getTextLeading',
  ),
  43 => 
  array (
    0 => 'function.harupage-gettextmatrix.php',
    1 => 'HaruPage::getTextMatrix',
  ),
  44 => 
  array (
    0 => 'function.harupage-gettextrenderingmode.php',
    1 => 'HaruPage::getTextRenderingMode',
  ),
  45 => 
  array (
    0 => 'function.harupage-gettextrise.php',
    1 => 'HaruPage::getTextRise',
  ),
  46 => 
  array (
    0 => 'function.harupage-gettextwidth.php',
    1 => 'HaruPage::getTextWidth',
  ),
  47 => 
  array (
    0 => 'function.harupage-gettransmatrix.php',
    1 => 'HaruPage::getTransMatrix',
  ),
  48 => 
  array (
    0 => 'function.harupage-getwidth.php',
    1 => 'HaruPage::getWidth',
  ),
  49 => 
  array (
    0 => 'function.harupage-getwordspace.php',
    1 => 'HaruPage::getWordSpace',
  ),
  50 => 
  array (
    0 => 'function.harupage-lineto.php',
    1 => 'HaruPage::lineTo',
  ),
  51 => 
  array (
    0 => 'function.harupage-measuretext.php',
    1 => 'HaruPage::measureText',
  ),
  52 => 
  array (
    0 => 'function.harupage-movetextpos.php',
    1 => 'HaruPage::moveTextPos',
  ),
  53 => 
  array (
    0 => 'function.harupage-moveto.php',
    1 => 'HaruPage::moveTo',
  ),
  54 => 
  array (
    0 => 'function.harupage-movetonextline.php',
    1 => 'HaruPage::moveToNextLine',
  ),
  55 => 
  array (
    0 => 'function.harupage-rectangle.php',
    1 => 'HaruPage::rectangle',
  ),
  56 => 
  array (
    0 => 'function.harupage-setcharspace.php',
    1 => 'HaruPage::setCharSpace',
  ),
  57 => 
  array (
    0 => 'function.harupage-setcmykfill.php',
    1 => 'HaruPage::setCMYKFill',
  ),
  58 => 
  array (
    0 => 'function.harupage-setcmykstroke.php',
    1 => 'HaruPage::setCMYKStroke',
  ),
  59 => 
  array (
    0 => 'function.harupage-setdash.php',
    1 => 'HaruPage::setDash',
  ),
  60 => 
  array (
    0 => 'function.harupage-setflatness.php',
    1 => 'HaruPage::setFlatness',
  ),
  61 => 
  array (
    0 => 'function.harupage-setfontandsize.php',
    1 => 'HaruPage::setFontAndSize',
  ),
  62 => 
  array (
    0 => 'function.harupage-setgrayfill.php',
    1 => 'HaruPage::setGrayFill',
  ),
  63 => 
  array (
    0 => 'function.harupage-setgraystroke.php',
    1 => 'HaruPage::setGrayStroke',
  ),
  64 => 
  array (
    0 => 'function.harupage-setheight.php',
    1 => 'HaruPage::setHeight',
  ),
  65 => 
  array (
    0 => 'function.harupage-sethorizontalscaling.php',
    1 => 'HaruPage::setHorizontalScaling',
  ),
  66 => 
  array (
    0 => 'function.harupage-setlinecap.php',
    1 => 'HaruPage::setLineCap',
  ),
  67 => 
  array (
    0 => 'function.harupage-setlinejoin.php',
    1 => 'HaruPage::setLineJoin',
  ),
  68 => 
  array (
    0 => 'function.harupage-setlinewidth.php',
    1 => 'HaruPage::setLineWidth',
  ),
  69 => 
  array (
    0 => 'function.harupage-setmiterlimit.php',
    1 => 'HaruPage::setMiterLimit',
  ),
  70 => 
  array (
    0 => 'function.harupage-setrgbfill.php',
    1 => 'HaruPage::setRGBFill',
  ),
  71 => 
  array (
    0 => 'function.harupage-setrgbstroke.php',
    1 => 'HaruPage::setRGBStroke',
  ),
  72 => 
  array (
    0 => 'function.harupage-setrotate.php',
    1 => 'HaruPage::setRotate',
  ),
  73 => 
  array (
    0 => 'function.harupage-setsize.php',
    1 => 'HaruPage::setSize',
  ),
  74 => 
  array (
    0 => 'function.harupage-setslideshow.php',
    1 => 'HaruPage::setSlideShow',
  ),
  75 => 
  array (
    0 => 'function.harupage-settextleading.php',
    1 => 'HaruPage::setTextLeading',
  ),
  76 => 
  array (
    0 => 'function.harupage-settextmatrix.php',
    1 => 'HaruPage::setTextMatrix',
  ),
  77 => 
  array (
    0 => 'function.harupage-settextrenderingmode.php',
    1 => 'HaruPage::setTextRenderingMode',
  ),
  78 => 
  array (
    0 => 'function.harupage-settextrise.php',
    1 => 'HaruPage::setTextRise',
  ),
  79 => 
  array (
    0 => 'function.harupage-setwidth.php',
    1 => 'HaruPage::setWidth',
  ),
  80 => 
  array (
    0 => 'function.harupage-setwordspace.php',
    1 => 'HaruPage::setWordSpace',
  ),
  81 => 
  array (
    0 => 'function.harupage-showtext.php',
    1 => 'HaruPage::showText',
  ),
  82 => 
  array (
    0 => 'function.harupage-showtextnextline.php',
    1 => 'HaruPage::showTextNextLine',
  ),
  83 => 
  array (
    0 => 'function.harupage-stroke.php',
    1 => 'HaruPage::stroke',
  ),
  84 => 
  array (
    0 => 'function.harupage-textout.php',
    1 => 'HaruPage::textOut',
  ),
  85 => 
  array (
    0 => 'function.harupage-textrect.php',
    1 => 'HaruPage::textRect',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.haru.php',
    1 => 'haru',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);