<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.haruoutline-setdestination.php',
    1 => 'HaruOutline::setDestination',
  ),
  1 => 
  array (
    0 => 'function.haruoutline-setopened.php',
    1 => 'HaruOutline::setOpened',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.haru.php',
    1 => 'haru',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);