<?php
$TOC = array (
  0 => 
  array (
    0 => 'splfileinfo.construct.php',
    1 => 'SplFileInfo::__construct',
  ),
  1 => 
  array (
    0 => 'splfileinfo.getatime.php',
    1 => 'SplFileInfo::getATime',
  ),
  2 => 
  array (
    0 => 'splfileinfo.getbasename.php',
    1 => 'SplFileInfo::getBasename',
  ),
  3 => 
  array (
    0 => 'splfileinfo.getctime.php',
    1 => 'SplFileInfo::getCTime',
  ),
  4 => 
  array (
    0 => 'splfileinfo.getfileinfo.php',
    1 => 'SplFileInfo::getFileInfo',
  ),
  5 => 
  array (
    0 => 'splfileinfo.getfilename.php',
    1 => 'SplFileInfo::getFilename',
  ),
  6 => 
  array (
    0 => 'splfileinfo.getgroup.php',
    1 => 'SplFileInfo::getGroup',
  ),
  7 => 
  array (
    0 => 'splfileinfo.getinode.php',
    1 => 'SplFileInfo::getInode',
  ),
  8 => 
  array (
    0 => 'splfileinfo.getlinktarget.php',
    1 => 'SplFileInfo::getLinkTarget',
  ),
  9 => 
  array (
    0 => 'splfileinfo.getmtime.php',
    1 => 'SplFileInfo::getMTime',
  ),
  10 => 
  array (
    0 => 'splfileinfo.getowner.php',
    1 => 'SplFileInfo::getOwner',
  ),
  11 => 
  array (
    0 => 'splfileinfo.getpath.php',
    1 => 'SplFileInfo::getPath',
  ),
  12 => 
  array (
    0 => 'splfileinfo.getpathinfo.php',
    1 => 'SplFileInfo::getPathInfo',
  ),
  13 => 
  array (
    0 => 'splfileinfo.getpathname.php',
    1 => 'SplFileInfo::getPathname',
  ),
  14 => 
  array (
    0 => 'splfileinfo.getperms.php',
    1 => 'SplFileInfo::getPerms',
  ),
  15 => 
  array (
    0 => 'splfileinfo.getrealpath.php',
    1 => 'SplFileInfo::getRealPath',
  ),
  16 => 
  array (
    0 => 'splfileinfo.getsize.php',
    1 => 'SplFileInfo::getSize',
  ),
  17 => 
  array (
    0 => 'splfileinfo.gettype.php',
    1 => 'SplFileInfo::getType',
  ),
  18 => 
  array (
    0 => 'splfileinfo.isdir.php',
    1 => 'SplFileInfo::isDir',
  ),
  19 => 
  array (
    0 => 'splfileinfo.isexecutable.php',
    1 => 'SplFileInfo::isExecutable',
  ),
  20 => 
  array (
    0 => 'splfileinfo.isfile.php',
    1 => 'SplFileInfo::isFile',
  ),
  21 => 
  array (
    0 => 'splfileinfo.islink.php',
    1 => 'SplFileInfo::isLink',
  ),
  22 => 
  array (
    0 => 'splfileinfo.isreadable.php',
    1 => 'SplFileInfo::isReadable',
  ),
  23 => 
  array (
    0 => 'splfileinfo.iswritable.php',
    1 => 'SplFileInfo::isWritable',
  ),
  24 => 
  array (
    0 => 'splfileinfo.openfile.php',
    1 => 'SplFileInfo::openFile',
  ),
  25 => 
  array (
    0 => 'splfileinfo.setfileclass.php',
    1 => 'SplFileInfo::setFileClass',
  ),
  26 => 
  array (
    0 => 'splfileinfo.setinfoclass.php',
    1 => 'SplFileInfo::setInfoClass',
  ),
  27 => 
  array (
    0 => 'splfileinfo.tostring.php',
    1 => 'SplFileInfo::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.files.php',
    1 => 'File Handling',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);