<?php
$TOC = array (
  0 => 
  array (
    0 => 'domtext.construct.php',
    1 => 'DOMText::__construct',
  ),
  1 => 
  array (
    0 => 'domtext.iswhitespaceinelementcontent.php',
    1 => 'DOMText::isWhitespaceInElementContent',
  ),
  2 => 
  array (
    0 => 'domtext.splittext.php',
    1 => 'DOMText::splitText',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dom.php',
    1 => 'DOM',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);