<?php
$TOC = array (
  0 => 
  array (
    0 => 'reflectionfunction.construct.php',
    1 => 'ReflectionFunction::__construct',
  ),
  1 => 
  array (
    0 => 'reflectionfunction.export.php',
    1 => 'ReflectionFunction::export',
  ),
  2 => 
  array (
    0 => 'reflectionfunction.invoke.php',
    1 => 'ReflectionFunction::invoke',
  ),
  3 => 
  array (
    0 => 'reflectionfunction.invokeargs.php',
    1 => 'ReflectionFunction::invokeArgs',
  ),
  4 => 
  array (
    0 => 'reflectionfunction.isdisabled.php',
    1 => 'ReflectionFunction::isDisabled',
  ),
  5 => 
  array (
    0 => 'reflectionfunction.tostring.php',
    1 => 'ReflectionFunction::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.reflection.php',
    1 => 'Reflection',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);