<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ziparchive-addemptydir.php',
    1 => 'ZipArchive::addEmptyDir',
  ),
  1 => 
  array (
    0 => 'function.ziparchive-addfile.php',
    1 => 'ZipArchive::addFile',
  ),
  2 => 
  array (
    0 => 'function.ziparchive-addfromstring.php',
    1 => 'ZipArchive::addFromString',
  ),
  3 => 
  array (
    0 => 'function.ziparchive-close.php',
    1 => 'ZipArchive::close',
  ),
  4 => 
  array (
    0 => 'function.ziparchive-deleteindex.php',
    1 => 'ZipArchive::deleteIndex',
  ),
  5 => 
  array (
    0 => 'function.ziparchive-deletename.php',
    1 => 'ZipArchive::deleteName',
  ),
  6 => 
  array (
    0 => 'function.ziparchive-extractto.php',
    1 => 'ZipArchive::extractTo',
  ),
  7 => 
  array (
    0 => 'function.ziparchive-getarchivecomment.php',
    1 => 'ZipArchive::getArchiveComment',
  ),
  8 => 
  array (
    0 => 'function.ziparchive-getcommentindex.php',
    1 => 'ZipArchive::getCommentIndex',
  ),
  9 => 
  array (
    0 => 'function.ziparchive-getcommentname.php',
    1 => 'ZipArchive::getCommentName',
  ),
  10 => 
  array (
    0 => 'function.ziparchive-getfromindex.php',
    1 => 'ZipArchive::getFromIndex',
  ),
  11 => 
  array (
    0 => 'function.ziparchive-getfromname.php',
    1 => 'ZipArchive::getFromName',
  ),
  12 => 
  array (
    0 => 'function.ziparchive-getnameindex.php',
    1 => 'ZipArchive::getNameIndex',
  ),
  13 => 
  array (
    0 => 'function.ziparchive-getstatusstring.php',
    1 => 'ZipArchive::getStatusString',
  ),
  14 => 
  array (
    0 => 'function.ziparchive-getstream.php',
    1 => 'ZipArchive::getStream',
  ),
  15 => 
  array (
    0 => 'function.ziparchive-locatename.php',
    1 => 'ZipArchive::locateName',
  ),
  16 => 
  array (
    0 => 'function.ziparchive-open.php',
    1 => 'ZipArchive::open',
  ),
  17 => 
  array (
    0 => 'function.ziparchive-renameindex.php',
    1 => 'ZipArchive::renameIndex',
  ),
  18 => 
  array (
    0 => 'function.ziparchive-renamename.php',
    1 => 'ZipArchive::renameName',
  ),
  19 => 
  array (
    0 => 'function.ziparchive-setarchivecomment.php',
    1 => 'ZipArchive::setArchiveComment',
  ),
  20 => 
  array (
    0 => 'function.ziparchive-setcommentindex.php',
    1 => 'ZipArchive::setCommentIndex',
  ),
  21 => 
  array (
    0 => 'function.ziparchive-setCommentName.php',
    1 => 'ZipArchive::setCommentName',
  ),
  22 => 
  array (
    0 => 'function.ziparchive-statindex.php',
    1 => 'ZipArchive::statIndex',
  ),
  23 => 
  array (
    0 => 'function.ziparchive-statname.php',
    1 => 'ZipArchive::statName',
  ),
  24 => 
  array (
    0 => 'function.ziparchive-unchangeall.php',
    1 => 'ZipArchive::unchangeAll',
  ),
  25 => 
  array (
    0 => 'function.ziparchive-unchangearchive.php',
    1 => 'ZipArchive::unchangeArchive',
  ),
  26 => 
  array (
    0 => 'function.ziparchive-unchangeindex.php',
    1 => 'ZipArchive::unchangeIndex',
  ),
  27 => 
  array (
    0 => 'function.ziparchive-unchangename.php',
    1 => 'ZipArchive::unchangeName',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.zip.php',
    1 => 'Zip',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);