<?php
$TOC = array (
  0 => 
  array (
    0 => 'mongogridfsfile.construct.php',
    1 => 'MongoGridfsFile::__construct',
  ),
  1 => 
  array (
    0 => 'mongogridfsfile.getbytes.php',
    1 => 'MongoGridFSFile::getBytes',
  ),
  2 => 
  array (
    0 => 'mongogridfsfile.getfilename.php',
    1 => 'MongoGridFSFile::getFilename',
  ),
  3 => 
  array (
    0 => 'mongogridfsfile.getsize.php',
    1 => 'MongoGridFSFile::getSize',
  ),
  4 => 
  array (
    0 => 'mongogridfsfile.write.php',
    1 => 'MongoGridFSFile::write',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'mongo.gridfs.php',
    1 => 'GridFS Classes',
  ),
  1 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  2 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  3 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  4 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  5 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);