<?php
$TOC = array (
  0 => 
  array (
    0 => 'reflectionparameter.allowsnull.php',
    1 => 'ReflectionParameter::allowsNull',
  ),
  1 => 
  array (
    0 => 'reflectionparameter.clone.php',
    1 => 'ReflectionParameter::__clone',
  ),
  2 => 
  array (
    0 => 'reflectionparameter.construct.php',
    1 => 'ReflectionParameter::__construct',
  ),
  3 => 
  array (
    0 => 'reflectionparameter.export.php',
    1 => 'ReflectionParameter::export',
  ),
  4 => 
  array (
    0 => 'reflectionparameter.getclass.php',
    1 => 'ReflectionParameter::getClass',
  ),
  5 => 
  array (
    0 => 'reflectionparameter.getdeclaringclass.php',
    1 => 'ReflectionParameter::getDeclaringClass',
  ),
  6 => 
  array (
    0 => 'reflectionparameter.getdeclaringfunction.php',
    1 => 'ReflectionParameter::getDeclaringFunction',
  ),
  7 => 
  array (
    0 => 'reflectionparameter.getdefaultvalue.php',
    1 => 'ReflectionParameter::getDefaultValue',
  ),
  8 => 
  array (
    0 => 'reflectionparameter.getname.php',
    1 => 'ReflectionParameter::getName',
  ),
  9 => 
  array (
    0 => 'reflectionparameter.getposition.php',
    1 => 'ReflectionParameter::getPosition',
  ),
  10 => 
  array (
    0 => 'reflectionparameter.isarray.php',
    1 => 'ReflectionParameter::isArray',
  ),
  11 => 
  array (
    0 => 'reflectionparameter.isdefaultvalueavailable.php',
    1 => 'ReflectionParameter::isDefaultValueAvailable',
  ),
  12 => 
  array (
    0 => 'reflectionparameter.isoptional.php',
    1 => 'ReflectionParameter::isOptional',
  ),
  13 => 
  array (
    0 => 'reflectionparameter.ispassedbyreference.php',
    1 => 'ReflectionParameter::isPassedByReference',
  ),
  14 => 
  array (
    0 => 'reflectionparameter.tostring.php',
    1 => 'ReflectionParameter::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.reflection.php',
    1 => 'Reflection',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);