<?php
$TOC = array (
  0 => 
  array (
    0 => 'memcache.add.php',
    1 => 'Memcache::add',
  ),
  1 => 
  array (
    0 => 'memcache.addserver.php',
    1 => 'Memcache::addServer',
  ),
  2 => 
  array (
    0 => 'memcache.close.php',
    1 => 'Memcache::close',
  ),
  3 => 
  array (
    0 => 'memcache.connect.php',
    1 => 'Memcache::connect',
  ),
  4 => 
  array (
    0 => 'memcache.decrement.php',
    1 => 'Memcache::decrement',
  ),
  5 => 
  array (
    0 => 'memcache.delete.php',
    1 => 'Memcache::delete',
  ),
  6 => 
  array (
    0 => 'memcache.flush.php',
    1 => 'Memcache::flush',
  ),
  7 => 
  array (
    0 => 'memcache.get.php',
    1 => 'Memcache::get',
  ),
  8 => 
  array (
    0 => 'memcache.getextendedstats.php',
    1 => 'Memcache::getExtendedStats',
  ),
  9 => 
  array (
    0 => 'memcache.getserverstatus.php',
    1 => 'Memcache::getServerStatus',
  ),
  10 => 
  array (
    0 => 'memcache.getstats.php',
    1 => 'Memcache::getStats',
  ),
  11 => 
  array (
    0 => 'memcache.getversion.php',
    1 => 'Memcache::getVersion',
  ),
  12 => 
  array (
    0 => 'memcache.increment.php',
    1 => 'Memcache::increment',
  ),
  13 => 
  array (
    0 => 'memcache.pconnect.php',
    1 => 'Memcache::pconnect',
  ),
  14 => 
  array (
    0 => 'memcache.replace.php',
    1 => 'Memcache::replace',
  ),
  15 => 
  array (
    0 => 'memcache.set.php',
    1 => 'Memcache::set',
  ),
  16 => 
  array (
    0 => 'memcache.setcompressthreshold.php',
    1 => 'Memcache::setCompressThreshold',
  ),
  17 => 
  array (
    0 => 'memcache.setserverparams.php',
    1 => 'Memcache::setServerParams',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.memcache.php',
    1 => 'Memcache',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);