<?php
$TOC = array (
  0 => 
  array (
    0 => 'cachingiterator.construct.php',
    1 => 'CachingIterator::__construct',
  ),
  1 => 
  array (
    0 => 'cachingiterator.count.php',
    1 => 'CachingIterator::count',
  ),
  2 => 
  array (
    0 => 'cachingiterator.current.php',
    1 => 'CachingIterator::current',
  ),
  3 => 
  array (
    0 => 'cachingiterator.getcache.php',
    1 => 'CachingIterator::getCache',
  ),
  4 => 
  array (
    0 => 'cachingiterator.getflags.php',
    1 => 'CachingIterator::getFlags',
  ),
  5 => 
  array (
    0 => 'cachingiterator.getinneriterator.php',
    1 => 'CachingIterator::getInnerIterator',
  ),
  6 => 
  array (
    0 => 'cachingiterator.hasnext.php',
    1 => 'CachingIterator::hasNext',
  ),
  7 => 
  array (
    0 => 'cachingiterator.key.php',
    1 => 'CachingIterator::key',
  ),
  8 => 
  array (
    0 => 'cachingiterator.next.php',
    1 => 'CachingIterator::next',
  ),
  9 => 
  array (
    0 => 'cachingiterator.offsetexists.php',
    1 => 'CachingIterator::offsetExists',
  ),
  10 => 
  array (
    0 => 'cachingiterator.offsetget.php',
    1 => 'CachingIterator::offsetGet',
  ),
  11 => 
  array (
    0 => 'cachingiterator.offsetset.php',
    1 => 'CachingIterator::offsetSet',
  ),
  12 => 
  array (
    0 => 'cachingiterator.offsetunset.php',
    1 => 'CachingIterator::offsetUnset',
  ),
  13 => 
  array (
    0 => 'cachingiterator.rewind.php',
    1 => 'CachingIterator::rewind',
  ),
  14 => 
  array (
    0 => 'cachingiterator.setflags.php',
    1 => 'CachingIterator::setFlags',
  ),
  15 => 
  array (
    0 => 'cachingiterator.tostring.php',
    1 => 'CachingIterator::__toString',
  ),
  16 => 
  array (
    0 => 'cachingiterator.valid.php',
    1 => 'CachingIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);