<?php
$TOC = array (
  0 => 
  array (
    0 => 'gmagickpixel.construct.php',
    1 => 'GmagickPixel::__construct',
  ),
  1 => 
  array (
    0 => 'gmagickpixel.getcolor.php',
    1 => 'GmagickPixel::getcolor',
  ),
  2 => 
  array (
    0 => 'gmagickpixel.getcolorcount.php',
    1 => 'GmagickPixel::getcolorcount',
  ),
  3 => 
  array (
    0 => 'gmagickpixel.getcolorvalue.php',
    1 => 'GmagickPixel::getcolorvalue',
  ),
  4 => 
  array (
    0 => 'gmagickpixel.setcolor.php',
    1 => 'GmagickPixel::setcolor',
  ),
  5 => 
  array (
    0 => 'gmagickpixel.setcolorvalue.php',
    1 => 'GmagickPixel::setcolorvalue',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gmagick.php',
    1 => 'Gmagick',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);