<?php
$TOC = array (
  0 => 
  array (
    0 => 'emptyiterator.current.php',
    1 => 'EmptyIterator::current',
  ),
  1 => 
  array (
    0 => 'emptyiterator.key.php',
    1 => 'EmptyIterator::key',
  ),
  2 => 
  array (
    0 => 'emptyiterator.next.php',
    1 => 'EmptyIterator::next',
  ),
  3 => 
  array (
    0 => 'emptyiterator.rewind.php',
    1 => 'EmptyIterator::rewind',
  ),
  4 => 
  array (
    0 => 'emptyiterator.valid.php',
    1 => 'EmptyIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);