<?php
$TOC = array (
  0 => 
  array (
    0 => 'multipleiterator.attachiterator.php',
    1 => 'MultipleIterator::attachIterator',
  ),
  1 => 
  array (
    0 => 'multipleiterator.construct.php',
    1 => 'MultipleIterator::__construct',
  ),
  2 => 
  array (
    0 => 'multipleiterator.containsiterator.php',
    1 => 'MultipleIterator::containsIterator',
  ),
  3 => 
  array (
    0 => 'multipleiterator.countiterators.php',
    1 => 'MultipleIterator::countIterators',
  ),
  4 => 
  array (
    0 => 'multipleiterator.current.php',
    1 => 'MultipleIterator::current',
  ),
  5 => 
  array (
    0 => 'multipleiterator.detachiterator.php',
    1 => 'MultipleIterator::detachIterator',
  ),
  6 => 
  array (
    0 => 'multipleiterator.getflags.php',
    1 => 'MultipleIterator::getFlags',
  ),
  7 => 
  array (
    0 => 'multipleiterator.key.php',
    1 => 'MultipleIterator::key',
  ),
  8 => 
  array (
    0 => 'multipleiterator.next.php',
    1 => 'MultipleIterator::next',
  ),
  9 => 
  array (
    0 => 'multipleiterator.rewind.php',
    1 => 'MultipleIterator::rewind',
  ),
  10 => 
  array (
    0 => 'multipleiterator.setflags.php',
    1 => 'MultipleIterator::setFlags',
  ),
  11 => 
  array (
    0 => 'multipleiterator.valid.php',
    1 => 'MultipleIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);