<?php
$TOC = array (
  0 => 
  array (
    0 => 'pdostatement.bindcolumn.php',
    1 => 'PDOStatement-&gt;bindColumn',
  ),
  1 => 
  array (
    0 => 'pdostatement.bindparam.php',
    1 => 'PDOStatement-&gt;bindParam',
  ),
  2 => 
  array (
    0 => 'pdostatement.bindvalue.php',
    1 => 'PDOStatement-&gt;bindValue',
  ),
  3 => 
  array (
    0 => 'pdostatement.closecursor.php',
    1 => 'PDOStatement-&gt;closeCursor',
  ),
  4 => 
  array (
    0 => 'pdostatement.columncount.php',
    1 => 'PDOStatement-&gt;columnCount',
  ),
  5 => 
  array (
    0 => 'pdostatement.debugdumpparams.php',
    1 => 'PDOStatement-&gt;debugDumpParams',
  ),
  6 => 
  array (
    0 => 'pdostatement.errorcode.php',
    1 => 'PDOStatement-&gt;errorCode',
  ),
  7 => 
  array (
    0 => 'pdostatement.errorinfo.php',
    1 => 'PDOStatement-&gt;errorInfo',
  ),
  8 => 
  array (
    0 => 'pdostatement.execute.php',
    1 => 'PDOStatement-&gt;execute',
  ),
  9 => 
  array (
    0 => 'pdostatement.fetch.php',
    1 => 'PDOStatement-&gt;fetch',
  ),
  10 => 
  array (
    0 => 'pdostatement.fetchall.php',
    1 => 'PDOStatement-&gt;fetchAll',
  ),
  11 => 
  array (
    0 => 'pdostatement.fetchcolumn.php',
    1 => 'PDOStatement-&gt;fetchColumn',
  ),
  12 => 
  array (
    0 => 'pdostatement.fetchobject.php',
    1 => 'PDOStatement-&gt;fetchObject',
  ),
  13 => 
  array (
    0 => 'pdostatement.getattribute.php',
    1 => 'PDOStatement-&gt;getAttribute',
  ),
  14 => 
  array (
    0 => 'pdostatement.getcolumnmeta.php',
    1 => 'PDOStatement-&gt;getColumnMeta',
  ),
  15 => 
  array (
    0 => 'pdostatement.nextrowset.php',
    1 => 'PDOStatement-&gt;nextRowset',
  ),
  16 => 
  array (
    0 => 'pdostatement.rowcount.php',
    1 => 'PDOStatement-&gt;rowCount',
  ),
  17 => 
  array (
    0 => 'pdostatement.setattribute.php',
    1 => 'PDOStatement-&gt;setAttribute',
  ),
  18 => 
  array (
    0 => 'pdostatement.setfetchmode.php',
    1 => 'PDOStatement-&gt;setFetchMode',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.pdo.php',
    1 => 'PDO',
  ),
  1 => 
  array (
    0 => 'refs.database.abstract.php',
    1 => 'Abstraction Layers',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);