<?php
$TOC = array (
  0 => 
  array (
    0 => 'reflectionfunctionabstract.clone.php',
    1 => 'ReflectionFunctionAbstract::__clone',
  ),
  1 => 
  array (
    0 => 'reflectionfunctionabstract.getdoccomment.php',
    1 => 'ReflectionFunctionAbstract::getDocComment',
  ),
  2 => 
  array (
    0 => 'reflectionfunctionabstract.getendline.php',
    1 => 'ReflectionFunctionAbstract::getEndLine',
  ),
  3 => 
  array (
    0 => 'reflectionfunctionabstract.getextension.php',
    1 => 'ReflectionFunctionAbstract::getExtension',
  ),
  4 => 
  array (
    0 => 'reflectionfunctionabstract.getextensionname.php',
    1 => 'ReflectionFunctionAbstract::getExtensionName',
  ),
  5 => 
  array (
    0 => 'reflectionfunctionabstract.getfilename.php',
    1 => 'ReflectionFunctionAbstract::getFileName',
  ),
  6 => 
  array (
    0 => 'reflectionfunctionabstract.getname.php',
    1 => 'ReflectionFunctionAbstract::getName',
  ),
  7 => 
  array (
    0 => 'reflectionfunctionabstract.getnamespacename.php',
    1 => 'ReflectionFunctionAbstract::getNamespaceName',
  ),
  8 => 
  array (
    0 => 'reflectionfunctionabstract.getnumberofparameters.php',
    1 => 'ReflectionFunctionAbstract::getNumberOfParameters',
  ),
  9 => 
  array (
    0 => 'reflectionfunctionabstract.getnumberofrequiredparameters.php',
    1 => 'ReflectionFunctionAbstract::getNumberOfRequiredParameters',
  ),
  10 => 
  array (
    0 => 'reflectionfunctionabstract.getparameters.php',
    1 => 'ReflectionFunctionAbstract::getParameters',
  ),
  11 => 
  array (
    0 => 'reflectionfunctionabstract.getshortname.php',
    1 => 'ReflectionFunctionAbstract::getShortName',
  ),
  12 => 
  array (
    0 => 'reflectionfunctionabstract.getstartline.php',
    1 => 'ReflectionFunctionAbstract::getStartLine',
  ),
  13 => 
  array (
    0 => 'reflectionfunctionabstract.getstaticvariables.php',
    1 => 'ReflectionFunctionAbstract::getStaticVariables',
  ),
  14 => 
  array (
    0 => 'reflectionfunctionabstract.innamespace.php',
    1 => 'ReflectionFunctionAbstract::inNamespace',
  ),
  15 => 
  array (
    0 => 'reflectionfunctionabstract.isclosure.php',
    1 => 'ReflectionFunctionAbstract::isClosure',
  ),
  16 => 
  array (
    0 => 'reflectionfunctionabstract.isdeprecated.php',
    1 => 'ReflectionFunctionAbstract::isDeprecated',
  ),
  17 => 
  array (
    0 => 'reflectionfunctionabstract.isinternal.php',
    1 => 'ReflectionFunctionAbstract::isInternal',
  ),
  18 => 
  array (
    0 => 'reflectionfunctionabstract.isuserdefined.php',
    1 => 'ReflectionFunctionAbstract::isUserDefined',
  ),
  19 => 
  array (
    0 => 'reflectionfunctionabstract.returnsreference.php',
    1 => 'ReflectionFunctionAbstract::returnsReference',
  ),
  20 => 
  array (
    0 => 'reflectionfunctionabstract.tostring.php',
    1 => 'ReflectionFunctionAbstract::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.reflection.php',
    1 => 'Reflection',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);