<?php
$TOC = array (
  0 => 
  array (
    0 => 'mysqli-warning.construct.php',
    1 => 'mysqli_warning::__construct',
  ),
  1 => 
  array (
    0 => 'mysqli-warning.next.php',
    1 => 'mysqli_warning::next',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mysqli.php',
    1 => 'Mysqli',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);