<?php
$TOC = array (
  0 => 
  array (
    0 => 'gmagickdraw.annotate.php',
    1 => 'GmagickDraw::annotate',
  ),
  1 => 
  array (
    0 => 'gmagickdraw.arc.php',
    1 => 'GmagickDraw::arc',
  ),
  2 => 
  array (
    0 => 'gmagickdraw.bezier.php',
    1 => 'GmagickDraw::bezier',
  ),
  3 => 
  array (
    0 => 'gmagickdraw.ellipse.php',
    1 => 'GmagickDraw::ellipse',
  ),
  4 => 
  array (
    0 => 'gmagickdraw.getfillcolor.php',
    1 => 'GmagickDraw::getfillcolor',
  ),
  5 => 
  array (
    0 => 'gmagickdraw.getfillopacity.php',
    1 => 'GmagickDraw::getfillopacity',
  ),
  6 => 
  array (
    0 => 'gmagickdraw.getfont.php',
    1 => 'GmagickDraw::getfont',
  ),
  7 => 
  array (
    0 => 'gmagickdraw.getfontsize.php',
    1 => 'GmagickDraw::getfontsize',
  ),
  8 => 
  array (
    0 => 'gmagickdraw.getfontstyle.php',
    1 => 'GmagickDraw::getfontstyle',
  ),
  9 => 
  array (
    0 => 'gmagickdraw.getfontweight.php',
    1 => 'GmagickDraw::getfontweight',
  ),
  10 => 
  array (
    0 => 'gmagickdraw.getstrokecolor.php',
    1 => 'GmagickDraw::getstrokecolor',
  ),
  11 => 
  array (
    0 => 'gmagickdraw.getstrokeopacity.php',
    1 => 'GmagickDraw::getstrokeopacity',
  ),
  12 => 
  array (
    0 => 'gmagickdraw.getstrokewidth.php',
    1 => 'GmagickDraw::getstrokewidth',
  ),
  13 => 
  array (
    0 => 'gmagickdraw.gettextdecoration.php',
    1 => 'GmagickDraw::gettextdecoration',
  ),
  14 => 
  array (
    0 => 'gmagickdraw.gettextencoding.php',
    1 => 'GmagickDraw::gettextencoding',
  ),
  15 => 
  array (
    0 => 'gmagickdraw.line.php',
    1 => 'GmagickDraw::line',
  ),
  16 => 
  array (
    0 => 'gmagickdraw.point.php',
    1 => 'GmagickDraw::point',
  ),
  17 => 
  array (
    0 => 'gmagickdraw.polygon.php',
    1 => 'GmagickDraw::polygon',
  ),
  18 => 
  array (
    0 => 'gmagickdraw.polyline.php',
    1 => 'GmagickDraw::polyline',
  ),
  19 => 
  array (
    0 => 'gmagickdraw.rectangle.php',
    1 => 'GmagickDraw::rectangle',
  ),
  20 => 
  array (
    0 => 'gmagickdraw.rotate.php',
    1 => 'GmagickDraw::rotate',
  ),
  21 => 
  array (
    0 => 'gmagickdraw.roundrectangle.php',
    1 => 'GmagickDraw::roundrectangle',
  ),
  22 => 
  array (
    0 => 'gmagickdraw.scale.php',
    1 => 'GmagickDraw::scale',
  ),
  23 => 
  array (
    0 => 'gmagickdraw.setfillcolor.php',
    1 => 'GmagickDraw::setfillcolor',
  ),
  24 => 
  array (
    0 => 'gmagickdraw.setfillopacity.php',
    1 => 'GmagickDraw::setfillopacity',
  ),
  25 => 
  array (
    0 => 'gmagickdraw.setfont.php',
    1 => 'GmagickDraw::setfont',
  ),
  26 => 
  array (
    0 => 'gmagickdraw.setfontsize.php',
    1 => 'GmagickDraw::setfontsize',
  ),
  27 => 
  array (
    0 => 'gmagickdraw.setfontstyle.php',
    1 => 'GmagickDraw::setfontstyle',
  ),
  28 => 
  array (
    0 => 'gmagickdraw.setfontweight.php',
    1 => 'GmagickDraw::setfontweight',
  ),
  29 => 
  array (
    0 => 'gmagickdraw.setstrokecolor.php',
    1 => 'GmagickDraw::setstrokecolor',
  ),
  30 => 
  array (
    0 => 'gmagickdraw.setstrokeopacity.php',
    1 => 'GmagickDraw::setstrokeopacity',
  ),
  31 => 
  array (
    0 => 'gmagickdraw.setstrokewidth.php',
    1 => 'GmagickDraw::setstrokewidth',
  ),
  32 => 
  array (
    0 => 'gmagickdraw.settextdecoration.php',
    1 => 'GmagickDraw::settextdecoration',
  ),
  33 => 
  array (
    0 => 'gmagickdraw.settextencoding.php',
    1 => 'GmagickDraw::settextencoding',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gmagick.php',
    1 => 'Gmagick',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);