<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swfdisplayitem.addaction.php',
    1 => 'SWFDisplayItem-&gt;addAction',
  ),
  1 => 
  array (
    0 => 'function.swfdisplayitem.addcolor.php',
    1 => 'SWFDisplayItem-&gt;addColor',
  ),
  2 => 
  array (
    0 => 'function.swfdisplayitem.endmask.php',
    1 => 'SWFDisplayItem-&gt;endMask',
  ),
  3 => 
  array (
    0 => 'function.swfdisplayitem.getrot.php',
    1 => 'SWFDisplayItem-&gt;getRot',
  ),
  4 => 
  array (
    0 => 'function.swfdisplayitem.getx.php',
    1 => 'SWFDisplayItem-&gt;getX',
  ),
  5 => 
  array (
    0 => 'function.swfdisplayitem.getxscale.php',
    1 => 'SWFDisplayItem-&gt;getXScale',
  ),
  6 => 
  array (
    0 => 'function.swfdisplayitem.getxskew.php',
    1 => 'SWFDisplayItem-&gt;getXSkew',
  ),
  7 => 
  array (
    0 => 'function.swfdisplayitem.gety.php',
    1 => 'SWFDisplayItem-&gt;getY',
  ),
  8 => 
  array (
    0 => 'function.swfdisplayitem.getyscale.php',
    1 => 'SWFDisplayItem-&gt;getYScale',
  ),
  9 => 
  array (
    0 => 'function.swfdisplayitem.getyskew.php',
    1 => 'SWFDisplayItem-&gt;getYSkew',
  ),
  10 => 
  array (
    0 => 'function.swfdisplayitem.move.php',
    1 => 'SWFDisplayItem-&gt;move',
  ),
  11 => 
  array (
    0 => 'function.swfdisplayitem.moveto.php',
    1 => 'SWFDisplayItem-&gt;moveTo',
  ),
  12 => 
  array (
    0 => 'function.swfdisplayitem.multcolor.php',
    1 => 'SWFDisplayItem-&gt;multColor',
  ),
  13 => 
  array (
    0 => 'function.swfdisplayitem.remove.php',
    1 => 'SWFDisplayItem-&gt;remove',
  ),
  14 => 
  array (
    0 => 'function.swfdisplayitem.rotate.php',
    1 => 'SWFDisplayItem-&gt;rotate',
  ),
  15 => 
  array (
    0 => 'function.swfdisplayitem.rotateto.php',
    1 => 'SWFDisplayItem-&gt;rotateTo',
  ),
  16 => 
  array (
    0 => 'function.swfdisplayitem.scale.php',
    1 => 'SWFDisplayItem-&gt;scale',
  ),
  17 => 
  array (
    0 => 'function.swfdisplayitem.scaleto.php',
    1 => 'SWFDisplayItem-&gt;scaleTo',
  ),
  18 => 
  array (
    0 => 'function.swfdisplayitem.setdepth.php',
    1 => 'SWFDisplayItem-&gt;setDepth',
  ),
  19 => 
  array (
    0 => 'function.swfdisplayitem.setmasklevel.php',
    1 => 'SWFDisplayItem-&gt;setMaskLevel',
  ),
  20 => 
  array (
    0 => 'function.swfdisplayitem.setmatrix.php',
    1 => 'SWFDisplayItem-&gt;setMatrix',
  ),
  21 => 
  array (
    0 => 'function.swfdisplayitem.setname.php',
    1 => 'SWFDisplayItem-&gt;setName',
  ),
  22 => 
  array (
    0 => 'function.swfdisplayitem.setratio.php',
    1 => 'SWFDisplayItem-&gt;setRatio',
  ),
  23 => 
  array (
    0 => 'function.swfdisplayitem.skewx.php',
    1 => 'SWFDisplayItem-&gt;skewX',
  ),
  24 => 
  array (
    0 => 'function.swfdisplayitem.skewxto.php',
    1 => 'SWFDisplayItem-&gt;skewXTo',
  ),
  25 => 
  array (
    0 => 'function.swfdisplayitem.skewy.php',
    1 => 'SWFDisplayItem-&gt;skewY',
  ),
  26 => 
  array (
    0 => 'function.swfdisplayitem.skewyto.php',
    1 => 'SWFDisplayItem-&gt;skewYTo',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);