<?php
$TOC = array (
  0 => 
  array (
    0 => 'mongogridfs.--construct.php',
    1 => 'MongoGridFS::__construct',
  ),
  1 => 
  array (
    0 => 'mongogridfs.delete.php',
    1 => 'MongoGridFS::delete',
  ),
  2 => 
  array (
    0 => 'mongogridfs.drop.php',
    1 => 'MongoGridFS::drop',
  ),
  3 => 
  array (
    0 => 'mongogridfs.find.php',
    1 => 'MongoGridFS::find',
  ),
  4 => 
  array (
    0 => 'mongogridfs.findone.php',
    1 => 'MongoGridFS::findOne',
  ),
  5 => 
  array (
    0 => 'mongogridfs.get.php',
    1 => 'MongoGridFS::get',
  ),
  6 => 
  array (
    0 => 'mongogridfs.put.php',
    1 => 'MongoGridFS::put',
  ),
  7 => 
  array (
    0 => 'mongogridfs.remove.php',
    1 => 'MongoGridFS::remove',
  ),
  8 => 
  array (
    0 => 'mongogridfs.storebytes.php',
    1 => 'MongoGridFS::storeBytes',
  ),
  9 => 
  array (
    0 => 'mongogridfs.storefile.php',
    1 => 'MongoGridFS::storeFile',
  ),
  10 => 
  array (
    0 => 'mongogridfs.storeupload.php',
    1 => 'MongoGridFS::storeUpload',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'mongo.gridfs.php',
    1 => 'GridFS Classes',
  ),
  1 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  2 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  3 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  4 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  5 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);