<?php
$TOC = array (
  0 => 
  array (
    0 => 'id3v2frame.getSize.php',
    1 => 'KTaglib_ID3v2_Frame::getSize',
  ),
  1 => 
  array (
    0 => 'id3v2frame.toString.php',
    1 => 'KTaglib_ID3v2_Frame::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ktaglib.php',
    1 => 'KTaglib',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);