<?php
$TOC = array (
  0 => 
  array (
    0 => 'mongogridfscursor.construct.php',
    1 => 'MongoGridFSCursor::__construct',
  ),
  1 => 
  array (
    0 => 'mongogridfscursor.current.php',
    1 => 'MongoGridFSCursor::current',
  ),
  2 => 
  array (
    0 => 'mongogridfscursor.getnext.php',
    1 => 'MongoGridFSCursor::getNext',
  ),
  3 => 
  array (
    0 => 'mongogridfscursor.key.php',
    1 => 'MongoGridFSCursor::key',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'mongo.gridfs.php',
    1 => 'GridFS Classes',
  ),
  1 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  2 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  3 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  4 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  5 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);