<?php
$TOC = array (
  0 => 
  array (
    0 => 'audioproperties.getBitrate.php',
    1 => 'KTaglib_MPEG_AudioProperties::getBitrate',
  ),
  1 => 
  array (
    0 => 'audioproperties.getChannels.php',
    1 => 'KTaglib_MPEG_AudioProperties::getChannels',
  ),
  2 => 
  array (
    0 => 'audioproperties.getLayer.php',
    1 => 'KTaglib_MPEG_AudioProperties::getLayer',
  ),
  3 => 
  array (
    0 => 'audioproperties.getLength.php',
    1 => 'KTaglib_MPEG_AudioProperties::getLength',
  ),
  4 => 
  array (
    0 => 'audioproperties.getSampleBitrate.php',
    1 => 'KTaglib_MPEG_AudioProperties::getSampleBitrate',
  ),
  5 => 
  array (
    0 => 'audioproperties.getVersion.php',
    1 => 'KTaglib_MPEG_AudioProperties::getVersion',
  ),
  6 => 
  array (
    0 => 'audioproperties.isCopyrighted.php',
    1 => 'KTaglib_MPEG_AudioProperties::isCopyrighted',
  ),
  7 => 
  array (
    0 => 'audioproperties.isOriginal.php',
    1 => 'KTaglib_MPEG_AudioProperties::isOriginal',
  ),
  8 => 
  array (
    0 => 'audioproperties.isProtectionEnabled.php',
    1 => 'KTaglib_MPEG_AudioProperties::isProtectionEnabled',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ktaglib.php',
    1 => 'KTaglib',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);