<?php
$TOC = array (
  0 => 
  array (
    0 => 'domcharacterdata.appenddata.php',
    1 => 'DOMCharacterData::appendData',
  ),
  1 => 
  array (
    0 => 'domcharacterdata.deletedata.php',
    1 => 'DOMCharacterData::deleteData',
  ),
  2 => 
  array (
    0 => 'domcharacterdata.insertdata.php',
    1 => 'DOMCharacterData::insertData',
  ),
  3 => 
  array (
    0 => 'domcharacterdata.replacedata.php',
    1 => 'DOMCharacterData::replaceData',
  ),
  4 => 
  array (
    0 => 'domcharacterdata.substringdata.php',
    1 => 'DOMCharacterData::substringData',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dom.php',
    1 => 'DOM',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);