<?php
$TOC = array (
  0 => 
  array (
    0 => 'soapheader.construct.php',
    1 => 'SoapHeader::__construct',
  ),
  1 => 
  array (
    0 => 'soapheader.soapheader.php',
    1 => 'SoapHeader::SoapHeader',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.soap.php',
    1 => 'SOAP',
  ),
  1 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);