<?php
$TOC = array (
  0 => 
  array (
    0 => 'tokyotyrantquery.addcond.php',
    1 => 'TokyoTyrantQuery::addCond',
  ),
  1 => 
  array (
    0 => 'tokyotyrantquery.__construct.php',
    1 => 'TokyoTyrantQuery::__construct',
  ),
  2 => 
  array (
    0 => 'tokyotyrantquery.count.php',
    1 => 'TokyoTyrantQuery::count',
  ),
  3 => 
  array (
    0 => 'tokyotyrantquery.current.php',
    1 => 'TokyoTyrantQuery::current',
  ),
  4 => 
  array (
    0 => 'tokyotyrantquery.hint.php',
    1 => 'TokyoTyrantQuery::hint',
  ),
  5 => 
  array (
    0 => 'tokyotyrantquery.key.php',
    1 => 'TokyoTyrantQuery::key',
  ),
  6 => 
  array (
    0 => 'tokyotyrantquery.metasearch.php',
    1 => 'TokyoTyrantQuery::metaSearch',
  ),
  7 => 
  array (
    0 => 'tokyotyrantquery.next.php',
    1 => 'TokyoTyrantQuery::next',
  ),
  8 => 
  array (
    0 => 'tokyotyrantquery.out.php',
    1 => 'TokyoTyrantQuery::out',
  ),
  9 => 
  array (
    0 => 'tokyotyrantquery.rewind.php',
    1 => 'TokyoTyrantQuery::rewind',
  ),
  10 => 
  array (
    0 => 'tokyotyrantquery.search.php',
    1 => 'TokyoTyrantQuery::search',
  ),
  11 => 
  array (
    0 => 'tokyotyrantquery.setlimit.php',
    1 => 'TokyoTyrantQuery::setLimit',
  ),
  12 => 
  array (
    0 => 'tokyotyrantquery.setorder.php',
    1 => 'TokyoTyrantQuery::setOrder',
  ),
  13 => 
  array (
    0 => 'tokyotyrantquery.valid.php',
    1 => 'TokyoTyrantQuery::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.tokyo-tyrant.php',
    1 => 'tokyo_tyrant',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);