<?php
$TOC = array (
  0 => 
  array (
    0 => 'amqpexchange.bind.php',
    1 => 'AMQPExchange::bind',
  ),
  1 => 
  array (
    0 => 'amqpexchange.construct.php',
    1 => 'AMQPExchange::__construct',
  ),
  2 => 
  array (
    0 => 'amqpexchange.declare.php',
    1 => 'AMQPExchange::declare',
  ),
  3 => 
  array (
    0 => 'amqpexchange.delete.php',
    1 => 'AMQPExchange::delete',
  ),
  4 => 
  array (
    0 => 'amqpexchange.publish.php',
    1 => 'AMQPExchange::publish',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.amqp.php',
    1 => 'AMQP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);