<?php
$TOC = array (
  0 => 
  array (
    0 => 'datetime.add.php',
    1 => 'DateTime::add',
  ),
  1 => 
  array (
    0 => 'datetime.construct.php',
    1 => 'DateTime::__construct',
  ),
  2 => 
  array (
    0 => 'datetime.createfromformat.php',
    1 => 'DateTime::createFromFormat',
  ),
  3 => 
  array (
    0 => 'datetime.diff.php',
    1 => 'DateTime::diff',
  ),
  4 => 
  array (
    0 => 'datetime.format.php',
    1 => 'DateTime::format',
  ),
  5 => 
  array (
    0 => 'datetime.getlasterrors.php',
    1 => 'DateTime::getLastErrors',
  ),
  6 => 
  array (
    0 => 'datetime.getoffset.php',
    1 => 'DateTime::getOffset',
  ),
  7 => 
  array (
    0 => 'datetime.gettimestamp.php',
    1 => 'DateTime::getTimestamp',
  ),
  8 => 
  array (
    0 => 'datetime.gettimezone.php',
    1 => 'DateTime::getTimezone',
  ),
  9 => 
  array (
    0 => 'datetime.modify.php',
    1 => 'DateTime::modify',
  ),
  10 => 
  array (
    0 => 'datetime.set-state.php',
    1 => 'DateTime::__set_state',
  ),
  11 => 
  array (
    0 => 'datetime.setdate.php',
    1 => 'DateTime::setDate',
  ),
  12 => 
  array (
    0 => 'datetime.setisodate.php',
    1 => 'DateTime::setISODate',
  ),
  13 => 
  array (
    0 => 'datetime.settime.php',
    1 => 'DateTime::setTime',
  ),
  14 => 
  array (
    0 => 'datetime.settimestamp.php',
    1 => 'DateTime::setTimestamp',
  ),
  15 => 
  array (
    0 => 'datetime.settimezone.php',
    1 => 'DateTime::setTimezone',
  ),
  16 => 
  array (
    0 => 'datetime.sub.php',
    1 => 'DateTime::sub',
  ),
  17 => 
  array (
    0 => 'datetime.wakeup.php',
    1 => 'DateTime::__wakeup',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.datetime.php',
    1 => 'Date/Time',
  ),
  1 => 
  array (
    0 => 'refs.calendar.php',
    1 => 'Date and Time Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);