<?php
$TOC = array (
  0 => 
  array (
    0 => 'mongocollection.batchinsert.php',
    1 => 'MongoCollection::batchInsert',
  ),
  1 => 
  array (
    0 => 'mongocollection.construct.php',
    1 => 'MongoCollection::__construct',
  ),
  2 => 
  array (
    0 => 'mongocollection.count.php',
    1 => 'MongoCollection::count',
  ),
  3 => 
  array (
    0 => 'mongocollection.createdbref.php',
    1 => 'MongoCollection::createDBRef',
  ),
  4 => 
  array (
    0 => 'mongocollection.deleteindex.php',
    1 => 'MongoCollection::deleteIndex',
  ),
  5 => 
  array (
    0 => 'mongocollection.deleteindexes.php',
    1 => 'MongoCollection::deleteIndexes',
  ),
  6 => 
  array (
    0 => 'mongocollection.drop.php',
    1 => 'MongoCollection::drop',
  ),
  7 => 
  array (
    0 => 'mongocollection.ensureindex.php',
    1 => 'MongoCollection::ensureIndex',
  ),
  8 => 
  array (
    0 => 'mongocollection.find.php',
    1 => 'MongoCollection::find',
  ),
  9 => 
  array (
    0 => 'mongocollection.findone.php',
    1 => 'MongoCollection::findOne',
  ),
  10 => 
  array (
    0 => 'mongocollection.get.php',
    1 => 'MongoCollection::__get',
  ),
  11 => 
  array (
    0 => 'mongocollection.getdbref.php',
    1 => 'MongoCollection::getDBRef',
  ),
  12 => 
  array (
    0 => 'mongocollection.getindexinfo.php',
    1 => 'MongoCollection::getIndexInfo',
  ),
  13 => 
  array (
    0 => 'mongocollection.getname.php',
    1 => 'MongoCollection::getName',
  ),
  14 => 
  array (
    0 => 'mongocollection.getslaveokay.php',
    1 => 'MongoCollection::getSlaveOkay',
  ),
  15 => 
  array (
    0 => 'mongocollection.group.php',
    1 => 'MongoCollection::group',
  ),
  16 => 
  array (
    0 => 'mongocollection.insert.php',
    1 => 'MongoCollection::insert',
  ),
  17 => 
  array (
    0 => 'mongocollection.remove.php',
    1 => 'MongoCollection::remove',
  ),
  18 => 
  array (
    0 => 'mongocollection.save.php',
    1 => 'MongoCollection::save',
  ),
  19 => 
  array (
    0 => 'mongocollection.setslaveokay.php',
    1 => 'MongoCollection::setSlaveOkay',
  ),
  20 => 
  array (
    0 => 'mongocollection.--tostring.php',
    1 => 'MongoCollection::__toString',
  ),
  21 => 
  array (
    0 => 'mongocollection.update.php',
    1 => 'MongoCollection::update',
  ),
  22 => 
  array (
    0 => 'mongocollection.validate.php',
    1 => 'MongoCollection::validate',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'mongo.core.php',
    1 => 'Core Classes',
  ),
  1 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  2 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  3 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  4 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  5 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);