<?php
$TOC = array (
  0 => 
  array (
    0 => 'pharfileinfo.chmod.php',
    1 => 'PharFileInfo::chmod',
  ),
  1 => 
  array (
    0 => 'pharfileinfo.compress.php',
    1 => 'PharFileInfo::compress',
  ),
  2 => 
  array (
    0 => 'pharfileinfo.construct.php',
    1 => 'PharFileInfo::__construct',
  ),
  3 => 
  array (
    0 => 'pharfileinfo.decompress.php',
    1 => 'PharFileInfo::decompress',
  ),
  4 => 
  array (
    0 => 'pharfileinfo.delmetadata.php',
    1 => 'PharFileInfo::delMetadata',
  ),
  5 => 
  array (
    0 => 'pharfileinfo.getcrc32.php',
    1 => 'PharFileInfo::getCRC32',
  ),
  6 => 
  array (
    0 => 'pharfileinfo.getcompressedsize.php',
    1 => 'PharFileInfo::getCompressedSize',
  ),
  7 => 
  array (
    0 => 'pharfileinfo.getmetadata.php',
    1 => 'PharFileInfo::getMetaData',
  ),
  8 => 
  array (
    0 => 'pharfileinfo.getpharflags.php',
    1 => 'PharFileInfo::getPharFlags',
  ),
  9 => 
  array (
    0 => 'pharfileinfo.hasmetadata.php',
    1 => 'PharFileInfo::hasMetadata',
  ),
  10 => 
  array (
    0 => 'pharfileinfo.iscrcchecked.php',
    1 => 'PharFileInfo::isCRCChecked',
  ),
  11 => 
  array (
    0 => 'pharfileinfo.iscompressed.php',
    1 => 'PharFileInfo::isCompressed',
  ),
  12 => 
  array (
    0 => 'pharfileinfo.iscompressedbzip2.php',
    1 => 'PharFileInfo::isCompressedBZIP2',
  ),
  13 => 
  array (
    0 => 'pharfileinfo.iscompressedgz.php',
    1 => 'PharFileInfo::isCompressedGZ',
  ),
  14 => 
  array (
    0 => 'pharfileinfo.setcompressedbzip2.php',
    1 => 'PharFileInfo::setCompressedBZIP2',
  ),
  15 => 
  array (
    0 => 'pharfileinfo.setcompressedgz.php',
    1 => 'PharFileInfo::setCompressedGZ',
  ),
  16 => 
  array (
    0 => 'pharfileinfo.setmetadata.php',
    1 => 'PharFileInfo::setMetaData',
  ),
  17 => 
  array (
    0 => 'pharfileinfo.setuncompressed.php',
    1 => 'PharFileInfo::setUncompressed',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.phar.php',
    1 => 'Phar',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);