<?php
$TOC = array (
  0 => 
  array (
    0 => 'parentiterator.accept.php',
    1 => 'ParentIterator::accept',
  ),
  1 => 
  array (
    0 => 'parentiterator.construct.php',
    1 => 'ParentIterator::__construct',
  ),
  2 => 
  array (
    0 => 'parentiterator.getchildren.php',
    1 => 'ParentIterator::getChildren',
  ),
  3 => 
  array (
    0 => 'parentiterator.haschildren.php',
    1 => 'ParentIterator::hasChildren',
  ),
  4 => 
  array (
    0 => 'parentiterator.next.php',
    1 => 'ParentIterator::next',
  ),
  5 => 
  array (
    0 => 'parentiterator.rewind.php',
    1 => 'ParentIterator::rewind',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);