<?php
$TOC = array (
  0 => 
  array (
    0 => 'sqlite3.busytimeout.php',
    1 => 'SQLite3::busyTimeout',
  ),
  1 => 
  array (
    0 => 'sqlite3.changes.php',
    1 => 'SQLite3::changes',
  ),
  2 => 
  array (
    0 => 'sqlite3.close.php',
    1 => 'SQLite3::close',
  ),
  3 => 
  array (
    0 => 'sqlite3.construct.php',
    1 => 'SQLite3::__construct',
  ),
  4 => 
  array (
    0 => 'sqlite3.createaggregate.php',
    1 => 'SQLite3::createAggregate',
  ),
  5 => 
  array (
    0 => 'sqlite3.createfunction.php',
    1 => 'SQLite3::createFunction',
  ),
  6 => 
  array (
    0 => 'sqlite3.escapestring.php',
    1 => 'SQLite3::escapeString',
  ),
  7 => 
  array (
    0 => 'sqlite3.exec.php',
    1 => 'SQLite3::exec',
  ),
  8 => 
  array (
    0 => 'sqlite3.lasterrorcode.php',
    1 => 'SQLite3::lastErrorCode',
  ),
  9 => 
  array (
    0 => 'sqlite3.lasterrormsg.php',
    1 => 'SQLite3::lastErrorMsg',
  ),
  10 => 
  array (
    0 => 'sqlite3.lastinsertrowid.php',
    1 => 'SQLite3::lastInsertRowID',
  ),
  11 => 
  array (
    0 => 'sqlite3.loadextension.php',
    1 => 'SQLite3::loadExtension',
  ),
  12 => 
  array (
    0 => 'sqlite3.open.php',
    1 => 'SQLite3::open',
  ),
  13 => 
  array (
    0 => 'sqlite3.prepare.php',
    1 => 'SQLite3::prepare',
  ),
  14 => 
  array (
    0 => 'sqlite3.query.php',
    1 => 'SQLite3::query',
  ),
  15 => 
  array (
    0 => 'sqlite3.querysingle.php',
    1 => 'SQLite3::querySingle',
  ),
  16 => 
  array (
    0 => 'sqlite3.version.php',
    1 => 'SQLite3::version',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sqlite3.php',
    1 => 'SQLite3',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);