<?php
$TOC = array (
  0 => 
  array (
    0 => 'collator.asort.php',
    1 => 'Collator::asort',
  ),
  1 => 
  array (
    0 => 'collator.compare.php',
    1 => 'Collator::compare',
  ),
  2 => 
  array (
    0 => 'collator.construct.php',
    1 => 'Collator::__construct',
  ),
  3 => 
  array (
    0 => 'collator.create.php',
    1 => 'Collator::create',
  ),
  4 => 
  array (
    0 => 'collator.getattribute.php',
    1 => 'Collator::getAttribute',
  ),
  5 => 
  array (
    0 => 'collator.geterrorcode.php',
    1 => 'Collator::getErrorCode',
  ),
  6 => 
  array (
    0 => 'collator.geterrormessage.php',
    1 => 'Collator::getErrorMessage',
  ),
  7 => 
  array (
    0 => 'collator.getlocale.php',
    1 => 'Collator::getLocale',
  ),
  8 => 
  array (
    0 => 'collator.getsortkey.php',
    1 => 'Collator::getSortKey',
  ),
  9 => 
  array (
    0 => 'collator.getstrength.php',
    1 => 'Collator::getStrength',
  ),
  10 => 
  array (
    0 => 'collator.setattribute.php',
    1 => 'Collator::setAttribute',
  ),
  11 => 
  array (
    0 => 'collator.setstrength.php',
    1 => 'Collator::setStrength',
  ),
  12 => 
  array (
    0 => 'collator.sortwithsortkeys.php',
    1 => 'Collator::sortWithSortKeys',
  ),
  13 => 
  array (
    0 => 'collator.sort.php',
    1 => 'Collator::sort',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.intl.php',
    1 => 'intl',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);