<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.haruencoder-getbytetype.php',
    1 => 'HaruEncoder::getByteType',
  ),
  1 => 
  array (
    0 => 'function.haruencoder-gettype.php',
    1 => 'HaruEncoder::getType',
  ),
  2 => 
  array (
    0 => 'function.haruencoder-getunicode.php',
    1 => 'HaruEncoder::getUnicode',
  ),
  3 => 
  array (
    0 => 'function.haruencoder-getwritingmode.php',
    1 => 'HaruEncoder::getWritingMode',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.haru.php',
    1 => 'haru',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);