<?php
$TOC = array (
  0 => 
  array (
    0 => 'solrparams.add.php',
    1 => 'SolrParams::add',
  ),
  1 => 
  array (
    0 => 'solrparams.addparam.php',
    1 => 'SolrParams::addParam',
  ),
  2 => 
  array (
    0 => 'solrparams.get.php',
    1 => 'SolrParams::get',
  ),
  3 => 
  array (
    0 => 'solrparams.getparam.php',
    1 => 'SolrParams::getParam',
  ),
  4 => 
  array (
    0 => 'solrparams.getparams.php',
    1 => 'SolrParams::getParams',
  ),
  5 => 
  array (
    0 => 'solrparams.getpreparedparams.php',
    1 => 'SolrParams::getPreparedParams',
  ),
  6 => 
  array (
    0 => 'solrparams.serialize.php',
    1 => 'SolrParams::serialize',
  ),
  7 => 
  array (
    0 => 'solrparams.set.php',
    1 => 'SolrParams::set',
  ),
  8 => 
  array (
    0 => 'solrparams.setparam.php',
    1 => 'SolrParams::setParam',
  ),
  9 => 
  array (
    0 => 'solrparams.tostring.php',
    1 => 'SolrParams::toString',
  ),
  10 => 
  array (
    0 => 'solrparams.unserialize.php',
    1 => 'SolrParams::unserialize',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.solr.php',
    1 => 'Solr',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);