<?php
$TOC = array (
  0 => 
  array (
    0 => 'id3v2attachedpictureframe.getDescription.php',
    1 => 'KTaglib_ID3v2_AttachedPictureFrame::getDescription',
  ),
  1 => 
  array (
    0 => 'id3v2attachedpictureframe.getMimeType.php',
    1 => 'KTaglib_ID3v2_AttachedPictureFrame::getMimeType',
  ),
  2 => 
  array (
    0 => 'id3v2attachedpictureframe.getType.php',
    1 => 'KTaglib_ID3v2_AttachedPictureFrame::getType',
  ),
  3 => 
  array (
    0 => 'id3v2attachedpictureframe.savePicture.php',
    1 => 'KTaglib_ID3v2_AttachedPictureFrame::savePicture',
  ),
  4 => 
  array (
    0 => 'id3v2attachedpictureframe.setMimeType.php',
    1 => 'KTaglib_ID3v2_AttachedPictureFrame::setMimeType',
  ),
  5 => 
  array (
    0 => 'id3v2attachedpictureframe.setPicture.php',
    1 => 'KTaglib_ID3v2_AttachedPictureFrame::setPicture',
  ),
  6 => 
  array (
    0 => 'id3v2attachedpictureframe.setType.php',
    1 => 'KTaglib_ID3v2_AttachedPictureFrame::setType',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ktaglib.php',
    1 => 'KTaglib',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);