<?php
$TOC = array (
  0 => 
  array (
    0 => 'tokyotyrant.add.php',
    1 => 'TokyoTyrant::add',
  ),
  1 => 
  array (
    0 => 'tokyotyrant.connect.php',
    1 => 'TokyoTyrant::connect',
  ),
  2 => 
  array (
    0 => 'tokyotyrant.connecturi.php',
    1 => 'TokyoTyrant::connectUri',
  ),
  3 => 
  array (
    0 => 'tokyotyrant.__construct.php',
    1 => 'TokyoTyrant::__construct',
  ),
  4 => 
  array (
    0 => 'tokyotyrant.copy.php',
    1 => 'TokyoTyrant::copy',
  ),
  5 => 
  array (
    0 => 'tokyotyrant.ext.php',
    1 => 'TokyoTyrant::ext',
  ),
  6 => 
  array (
    0 => 'tokyotyrant.fwmkeys.php',
    1 => 'TokyoTyrant::fwmKeys',
  ),
  7 => 
  array (
    0 => 'tokyotyrant.get.php',
    1 => 'TokyoTyrant::get',
  ),
  8 => 
  array (
    0 => 'tokyotyrant.getiterator.php',
    1 => 'TokyoTyrant::getIterator',
  ),
  9 => 
  array (
    0 => 'tokyotyrant.num.php',
    1 => 'TokyoTyrant::num',
  ),
  10 => 
  array (
    0 => 'tokyotyrant.out.php',
    1 => 'TokyoTyrant::out',
  ),
  11 => 
  array (
    0 => 'tokyotyrant.put.php',
    1 => 'TokyoTyrant::put',
  ),
  12 => 
  array (
    0 => 'tokyotyrant.putcat.php',
    1 => 'TokyoTyrant::putCat',
  ),
  13 => 
  array (
    0 => 'tokyotyrant.putkeep.php',
    1 => 'TokyoTyrant::putKeep',
  ),
  14 => 
  array (
    0 => 'tokyotyrant.putnr.php',
    1 => 'TokyoTyrant::putNr',
  ),
  15 => 
  array (
    0 => 'tokyotyrant.putshl.php',
    1 => 'TokyoTyrant::putShl',
  ),
  16 => 
  array (
    0 => 'tokyotyrant.restore.php',
    1 => 'TokyoTyrant::restore',
  ),
  17 => 
  array (
    0 => 'tokyotyrant.setmaster.php',
    1 => 'TokyoTyrant::setMaster',
  ),
  18 => 
  array (
    0 => 'tokyotyrant.size.php',
    1 => 'TokyoTyrant::size',
  ),
  19 => 
  array (
    0 => 'tokyotyrant.stat.php',
    1 => 'TokyoTyrant::stat',
  ),
  20 => 
  array (
    0 => 'tokyotyrant.sync.php',
    1 => 'TokyoTyrant::sync',
  ),
  21 => 
  array (
    0 => 'tokyotyrant.tune.php',
    1 => 'TokyoTyrant::tune',
  ),
  22 => 
  array (
    0 => 'tokyotyrant.vanish.php',
    1 => 'TokyoTyrant::vanish',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.tokyo-tyrant.php',
    1 => 'tokyo_tyrant',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);