<?php
$TOC = array (
  0 => 
  array (
    0 => 'recursivedirectoryiterator.construct.php',
    1 => 'RecursiveDirectoryIterator::__construct',
  ),
  1 => 
  array (
    0 => 'recursivedirectoryiterator.getchildren.php',
    1 => 'RecursiveDirectoryIterator::getChildren',
  ),
  2 => 
  array (
    0 => 'recursivedirectoryiterator.getsubpath.php',
    1 => 'RecursiveDirectoryIterator::getSubPath',
  ),
  3 => 
  array (
    0 => 'recursivedirectoryiterator.getsubpathname.php',
    1 => 'RecursiveDirectoryIterator::getSubPathname',
  ),
  4 => 
  array (
    0 => 'recursivedirectoryiterator.haschildren.php',
    1 => 'RecursiveDirectoryIterator::hasChildren',
  ),
  5 => 
  array (
    0 => 'recursivedirectoryiterator.key.php',
    1 => 'RecursiveDirectoryIterator::key',
  ),
  6 => 
  array (
    0 => 'recursivedirectoryiterator.next.php',
    1 => 'RecursiveDirectoryIterator::next',
  ),
  7 => 
  array (
    0 => 'recursivedirectoryiterator.rewind.php',
    1 => 'RecursiveDirectoryIterator::rewind',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);