<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swfmovie.add.php',
    1 => 'SWFMovie-&gt;add',
  ),
  1 => 
  array (
    0 => 'function.swfmovie.addexport.php',
    1 => 'SWFMovie-&gt;addExport',
  ),
  2 => 
  array (
    0 => 'function.swfmovie.addfont.php',
    1 => 'SWFMovie-&gt;addFont',
  ),
  3 => 
  array (
    0 => 'function.swfmovie.construct.php',
    1 => 'SWFMovie-&gt;__construct',
  ),
  4 => 
  array (
    0 => 'function.swfmovie.importchar.php',
    1 => 'SWFMovie-&gt;importChar',
  ),
  5 => 
  array (
    0 => 'function.swfmovie.importfont.php',
    1 => 'SWFMovie-&gt;importFont',
  ),
  6 => 
  array (
    0 => 'function.swfmovie.labelframe.php',
    1 => 'SWFMovie-&gt;labelFrame',
  ),
  7 => 
  array (
    0 => 'function.swfmovie.nextframe.php',
    1 => 'SWFMovie-&gt;nextFrame',
  ),
  8 => 
  array (
    0 => 'function.swfmovie.output.php',
    1 => 'SWFMovie-&gt;output',
  ),
  9 => 
  array (
    0 => 'function.swfmovie.remove.php',
    1 => 'SWFMovie-&gt;remove',
  ),
  10 => 
  array (
    0 => 'function.swfmovie.save.php',
    1 => 'SWFMovie-&gt;save',
  ),
  11 => 
  array (
    0 => 'function.swfmovie.savetofile.php',
    1 => 'SWFMovie-&gt;saveToFile',
  ),
  12 => 
  array (
    0 => 'function.swfmovie.setbackground.php',
    1 => 'SWFMovie-&gt;setbackground',
  ),
  13 => 
  array (
    0 => 'function.swfmovie.setdimension.php',
    1 => 'SWFMovie-&gt;setDimension',
  ),
  14 => 
  array (
    0 => 'function.swfmovie.setframes.php',
    1 => 'SWFMovie-&gt;setFrames',
  ),
  15 => 
  array (
    0 => 'function.swfmovie.setrate.php',
    1 => 'SWFMovie-&gt;setRate',
  ),
  16 => 
  array (
    0 => 'function.swfmovie.startsound.php',
    1 => 'SWFMovie-&gt;startSound',
  ),
  17 => 
  array (
    0 => 'function.swfmovie.stopsound.php',
    1 => 'SWFMovie-&gt;stopSound',
  ),
  18 => 
  array (
    0 => 'function.swfmovie.streammp3.php',
    1 => 'SWFMovie-&gt;streamMP3',
  ),
  19 => 
  array (
    0 => 'function.swfmovie.writeexports.php',
    1 => 'SWFMovie-&gt;writeExports',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);