<?php
$TOC = array (
  0 => 
  array (
    0 => 'gearmanjob.complete.php',
    1 => 'GearmanJob::complete',
  ),
  1 => 
  array (
    0 => 'gearmanjob.construct.php',
    1 => 'GearmanJob::__construct',
  ),
  2 => 
  array (
    0 => 'gearmanjob.data.php',
    1 => 'GearmanJob::data',
  ),
  3 => 
  array (
    0 => 'gearmanjob.exception.php',
    1 => 'GearmanJob::exception',
  ),
  4 => 
  array (
    0 => 'gearmanjob.fail.php',
    1 => 'GearmanJob::fail',
  ),
  5 => 
  array (
    0 => 'gearmanjob.functionname.php',
    1 => 'GearmanJob::functionName',
  ),
  6 => 
  array (
    0 => 'gearmanjob.handle.php',
    1 => 'GearmanJob::handle',
  ),
  7 => 
  array (
    0 => 'gearmanjob.returncode.php',
    1 => 'GearmanJob::returnCode',
  ),
  8 => 
  array (
    0 => 'gearmanjob.sendcomplete.php',
    1 => 'GearmanJob::sendComplete',
  ),
  9 => 
  array (
    0 => 'gearmanjob.senddata.php',
    1 => 'GearmanJob::sendData',
  ),
  10 => 
  array (
    0 => 'gearmanjob.sendexception.php',
    1 => 'GearmanJob::sendException',
  ),
  11 => 
  array (
    0 => 'gearmanjob.sendfail.php',
    1 => 'GearmanJob::sendFail',
  ),
  12 => 
  array (
    0 => 'gearmanjob.sendstatus.php',
    1 => 'GearmanJob::sendStatus',
  ),
  13 => 
  array (
    0 => 'gearmanjob.sendwarning.php',
    1 => 'GearmanJob::sendWarning',
  ),
  14 => 
  array (
    0 => 'gearmanjob.setreturn.php',
    1 => 'GearmanJob::setReturn',
  ),
  15 => 
  array (
    0 => 'gearmanjob.status.php',
    1 => 'GearmanJob::status',
  ),
  16 => 
  array (
    0 => 'gearmanjob.unique.php',
    1 => 'GearmanJob::unique',
  ),
  17 => 
  array (
    0 => 'gearmanjob.warning.php',
    1 => 'GearmanJob::warning',
  ),
  18 => 
  array (
    0 => 'gearmanjob.workload.php',
    1 => 'GearmanJob::workload',
  ),
  19 => 
  array (
    0 => 'gearmanjob.workloadsize.php',
    1 => 'GearmanJob::workloadSize',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gearman.php',
    1 => 'Gearman',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);