<?php
$TOC = array (
  0 => 
  array (
    0 => 'id3v2tag.addFrame.php',
    1 => 'KTaglib_ID3v2_Tag::addFrame',
  ),
  1 => 
  array (
    0 => 'id3v2tag.getFrameList.php',
    1 => 'KTaglib_ID3v2_Tag::getFrameList',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ktaglib.php',
    1 => 'KTaglib',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);