<?php
$TOC = array (
  0 => 
  array (
    0 => 'rarentry.extract.php',
    1 => 'RarEntry::extract',
  ),
  1 => 
  array (
    0 => 'rarentry.getattr.php',
    1 => 'RarEntry::getAttr',
  ),
  2 => 
  array (
    0 => 'rarentry.getcrc.php',
    1 => 'RarEntry::getCrc',
  ),
  3 => 
  array (
    0 => 'rarentry.getfiletime.php',
    1 => 'RarEntry::getFileTime',
  ),
  4 => 
  array (
    0 => 'rarentry.gethostos.php',
    1 => 'RarEntry::getHostOs',
  ),
  5 => 
  array (
    0 => 'rarentry.getmethod.php',
    1 => 'RarEntry::getMethod',
  ),
  6 => 
  array (
    0 => 'rarentry.getname.php',
    1 => 'RarEntry::getName',
  ),
  7 => 
  array (
    0 => 'rarentry.getpackedsize.php',
    1 => 'RarEntry::getPackedSize',
  ),
  8 => 
  array (
    0 => 'rarentry.getstream.php',
    1 => 'RarEntry::getStream',
  ),
  9 => 
  array (
    0 => 'rarentry.getunpackedsize.php',
    1 => 'RarEntry::getUnpackedSize',
  ),
  10 => 
  array (
    0 => 'rarentry.getversion.php',
    1 => 'RarEntry::getVersion',
  ),
  11 => 
  array (
    0 => 'rarentry.isdirectory.php',
    1 => 'RarEntry::isDirectory',
  ),
  12 => 
  array (
    0 => 'rarentry.isencrypted.php',
    1 => 'RarEntry::isEncrypted',
  ),
  13 => 
  array (
    0 => 'rarentry.tostring.php',
    1 => 'RarEntry::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.rar.php',
    1 => 'Rar',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);