<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairopattern.construct.php',
    1 => 'CairoPattern::__construct',
  ),
  1 => 
  array (
    0 => 'cairopattern.getmatrix.php',
    1 => 'CairoPattern::getMatrix',
  ),
  2 => 
  array (
    0 => 'cairopattern.gettype.php',
    1 => 'CairoPattern::getType',
  ),
  3 => 
  array (
    0 => 'cairopattern.setmatrix.php',
    1 => 'CairoPattern::setMatrix',
  ),
  4 => 
  array (
    0 => 'cairopattern.status.php',
    1 => 'CairoPattern::status',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);