<?php
$TOC = array (
  0 => 
  array (
    0 => 'mpegfile.construct.php',
    1 => 'KTaglib_MPEG_File::__construct',
  ),
  1 => 
  array (
    0 => 'mpegfile.getAudioProperties.php',
    1 => 'KTaglib_MPEG_File::getAudioProperties',
  ),
  2 => 
  array (
    0 => 'mpegfile.getID3v1Tag.php',
    1 => 'KTaglib_MPEG_File::getID3v1Tag',
  ),
  3 => 
  array (
    0 => 'mpegfile.getId3v2Tag.php',
    1 => 'KTaglib_MPEG_File::getID3v2Tag',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ktaglib.php',
    1 => 'KTaglib',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);