<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swftext.addstring.php',
    1 => 'SWFText-&gt;addString',
  ),
  1 => 
  array (
    0 => 'function.swftext.addutf8string.php',
    1 => 'SWFText-&gt;addUTF8String',
  ),
  2 => 
  array (
    0 => 'function.swftext.construct.php',
    1 => 'SWFText-&gt;__construct',
  ),
  3 => 
  array (
    0 => 'function.swftext.getascent.php',
    1 => 'SWFText-&gt;getAscent',
  ),
  4 => 
  array (
    0 => 'function.swftext.getdescent.php',
    1 => 'SWFText-&gt;getDescent',
  ),
  5 => 
  array (
    0 => 'function.swftext.getleading.php',
    1 => 'SWFText-&gt;getLeading',
  ),
  6 => 
  array (
    0 => 'function.swftext.getutf8width.php',
    1 => 'SWFText-&gt;getUTF8Width',
  ),
  7 => 
  array (
    0 => 'function.swftext.getwidth.php',
    1 => 'SWFText-&gt;getWidth',
  ),
  8 => 
  array (
    0 => 'function.swftext.moveto.php',
    1 => 'SWFText-&gt;moveTo',
  ),
  9 => 
  array (
    0 => 'function.swftext.setcolor.php',
    1 => 'SWFText-&gt;setColor',
  ),
  10 => 
  array (
    0 => 'function.swftext.setfont.php',
    1 => 'SWFText-&gt;setFont',
  ),
  11 => 
  array (
    0 => 'function.swftext.setheight.php',
    1 => 'SWFText-&gt;setHeight',
  ),
  12 => 
  array (
    0 => 'function.swftext.setspacing.php',
    1 => 'SWFText-&gt;setSpacing',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);