<?php
$TOC = array (
  0 => 
  array (
    0 => 'datetimezone.construct.php',
    1 => 'DateTimeZone::__construct',
  ),
  1 => 
  array (
    0 => 'datetimezone.getlocation.php',
    1 => 'DateTimeZone::getLocation',
  ),
  2 => 
  array (
    0 => 'datetimezone.getname.php',
    1 => 'DateTimeZone::getName',
  ),
  3 => 
  array (
    0 => 'datetimezone.getoffset.php',
    1 => 'DateTimeZone::getOffset',
  ),
  4 => 
  array (
    0 => 'datetimezone.gettransitions.php',
    1 => 'DateTimeZone::getTransitions',
  ),
  5 => 
  array (
    0 => 'datetimezone.listabbreviations.php',
    1 => 'DateTimeZone::listAbbreviations',
  ),
  6 => 
  array (
    0 => 'datetimezone.listidentifiers.php',
    1 => 'DateTimeZone::listIdentifiers',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.datetime.php',
    1 => 'Date/Time',
  ),
  1 => 
  array (
    0 => 'refs.calendar.php',
    1 => 'Date and Time Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);