<?php
$TOC = array (
  0 => 
  array (
    0 => 'tokyotyranttable.add.php',
    1 => 'TokyoTyrantTable::add',
  ),
  1 => 
  array (
    0 => 'tokyotyranttable.genuid.php',
    1 => 'TokyoTyrantTable::genUid',
  ),
  2 => 
  array (
    0 => 'tokyotyranttable.get.php',
    1 => 'TokyoTyrantTable::get',
  ),
  3 => 
  array (
    0 => 'tokyotyranttable.getiterator.php',
    1 => 'TokyoTyrantTable::getIterator',
  ),
  4 => 
  array (
    0 => 'tokyotyranttable.getquery.php',
    1 => 'TokyoTyrantTable::getQuery',
  ),
  5 => 
  array (
    0 => 'tokyotyranttable.out.php',
    1 => 'TokyoTyrantTable::out',
  ),
  6 => 
  array (
    0 => 'tokyotyranttable.put.php',
    1 => 'TokyoTyrantTable::put',
  ),
  7 => 
  array (
    0 => 'tokyotyranttable.putcat.php',
    1 => 'TokyoTyrantTable::putCat',
  ),
  8 => 
  array (
    0 => 'tokyotyranttable.putkeep.php',
    1 => 'TokyoTyrantTable::putKeep',
  ),
  9 => 
  array (
    0 => 'tokyotyranttable.putnr.php',
    1 => 'TokyoTyrantTable::putNr',
  ),
  10 => 
  array (
    0 => 'tokyotyranttable.putshl.php',
    1 => 'TokyoTyrantTable::putShl',
  ),
  11 => 
  array (
    0 => 'tokyotyranttable.setindex.php',
    1 => 'TokyoTyrantTable::setIndex',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.tokyo-tyrant.php',
    1 => 'tokyo_tyrant',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);