<?php
$TOC = array (
  0 => 
  array (
    0 => 'limititerator.construct.php',
    1 => 'LimitIterator::__construct',
  ),
  1 => 
  array (
    0 => 'limititerator.current.php',
    1 => 'LimitIterator::current',
  ),
  2 => 
  array (
    0 => 'limititerator.getinneriterator.php',
    1 => 'LimitIterator::getInnerIterator',
  ),
  3 => 
  array (
    0 => 'limititerator.getposition.php',
    1 => 'LimitIterator::getPosition',
  ),
  4 => 
  array (
    0 => 'limititerator.key.php',
    1 => 'LimitIterator::key',
  ),
  5 => 
  array (
    0 => 'limititerator.next.php',
    1 => 'LimitIterator::next',
  ),
  6 => 
  array (
    0 => 'limititerator.rewind.php',
    1 => 'LimitIterator::rewind',
  ),
  7 => 
  array (
    0 => 'limititerator.seek.php',
    1 => 'LimitIterator::seek',
  ),
  8 => 
  array (
    0 => 'limititerator.valid.php',
    1 => 'LimitIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);