<?php
$TOC = array (
  0 => 
  array (
    0 => 'domdocument.construct.php',
    1 => 'DOMDocument::__construct',
  ),
  1 => 
  array (
    0 => 'domdocument.createattribute.php',
    1 => 'DOMDocument::createAttribute',
  ),
  2 => 
  array (
    0 => 'domdocument.createattributens.php',
    1 => 'DOMDocument::createAttributeNS',
  ),
  3 => 
  array (
    0 => 'domdocument.createcdatasection.php',
    1 => 'DOMDocument::createCDATASection',
  ),
  4 => 
  array (
    0 => 'domdocument.createcomment.php',
    1 => 'DOMDocument::createComment',
  ),
  5 => 
  array (
    0 => 'domdocument.createdocumentfragment.php',
    1 => 'DOMDocument::createDocumentFragment',
  ),
  6 => 
  array (
    0 => 'domdocument.createelement.php',
    1 => 'DOMDocument::createElement',
  ),
  7 => 
  array (
    0 => 'domdocument.createelementns.php',
    1 => 'DOMDocument::createElementNS',
  ),
  8 => 
  array (
    0 => 'domdocument.createentityreference.php',
    1 => 'DOMDocument::createEntityReference',
  ),
  9 => 
  array (
    0 => 'domdocument.createprocessinginstruction.php',
    1 => 'DOMDocument::createProcessingInstruction',
  ),
  10 => 
  array (
    0 => 'domdocument.createtextnode.php',
    1 => 'DOMDocument::createTextNode',
  ),
  11 => 
  array (
    0 => 'domdocument.getelementbyid.php',
    1 => 'DOMDocument::getElementById',
  ),
  12 => 
  array (
    0 => 'domdocument.getelementsbytagname.php',
    1 => 'DOMDocument::getElementsByTagName',
  ),
  13 => 
  array (
    0 => 'domdocument.getelementsbytagnamens.php',
    1 => 'DOMDocument::getElementsByTagNameNS',
  ),
  14 => 
  array (
    0 => 'domdocument.importnode.php',
    1 => 'DOMDocument::importNode',
  ),
  15 => 
  array (
    0 => 'domdocument.load.php',
    1 => 'DOMDocument::load',
  ),
  16 => 
  array (
    0 => 'domdocument.loadhtml.php',
    1 => 'DOMDocument::loadHTML',
  ),
  17 => 
  array (
    0 => 'domdocument.loadhtmlfile.php',
    1 => 'DOMDocument::loadHTMLFile',
  ),
  18 => 
  array (
    0 => 'domdocument.loadxml.php',
    1 => 'DOMDocument::loadXML',
  ),
  19 => 
  array (
    0 => 'domdocument.normalizedocument.php',
    1 => 'DOMDocument::normalizeDocument',
  ),
  20 => 
  array (
    0 => 'domdocument.registernodeclass.php',
    1 => 'DOMDocument::registerNodeClass',
  ),
  21 => 
  array (
    0 => 'domdocument.relaxngvalidate.php',
    1 => 'DOMDocument::relaxNGValidate',
  ),
  22 => 
  array (
    0 => 'domdocument.relaxngvalidatesource.php',
    1 => 'DOMDocument::relaxNGValidateSource',
  ),
  23 => 
  array (
    0 => 'domdocument.save.php',
    1 => 'DOMDocument::save',
  ),
  24 => 
  array (
    0 => 'domdocument.savehtml.php',
    1 => 'DOMDocument::saveHTML',
  ),
  25 => 
  array (
    0 => 'domdocument.savehtmlfile.php',
    1 => 'DOMDocument::saveHTMLFile',
  ),
  26 => 
  array (
    0 => 'domdocument.savexml.php',
    1 => 'DOMDocument::saveXML',
  ),
  27 => 
  array (
    0 => 'domdocument.schemavalidate.php',
    1 => 'DOMDocument::schemaValidate',
  ),
  28 => 
  array (
    0 => 'domdocument.schemavalidatesource.php',
    1 => 'DOMDocument::schemaValidateSource',
  ),
  29 => 
  array (
    0 => 'domdocument.validate.php',
    1 => 'DOMDocument::validate',
  ),
  30 => 
  array (
    0 => 'domdocument.xinclude.php',
    1 => 'DOMDocument::xinclude',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dom.php',
    1 => 'DOM',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);