<?php
$TOC = array (
  0 => 
  array (
    0 => 'tag.getAlbum.php',
    1 => 'KTaglib_Tag::getAlbum',
  ),
  1 => 
  array (
    0 => 'tag.getArtist.php',
    1 => 'KTaglib_Tag::getArtist',
  ),
  2 => 
  array (
    0 => 'tag.getComment.php',
    1 => 'KTaglib_Tag::getComment',
  ),
  3 => 
  array (
    0 => 'tag.getGenre.php',
    1 => 'KTaglib_Tag::getGenre',
  ),
  4 => 
  array (
    0 => 'tag.getTitle.php',
    1 => 'KTaglib_Tag::getTitle',
  ),
  5 => 
  array (
    0 => 'tag.getTrack.php',
    1 => 'KTaglib_Tag::getTrack',
  ),
  6 => 
  array (
    0 => 'tag.getYear.php',
    1 => 'KTaglib_Tag::getYear',
  ),
  7 => 
  array (
    0 => 'tag.isEmpty.php',
    1 => 'KTaglib_Tag::isEmpty',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ktaglib.php',
    1 => 'KTaglib',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);