<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairolineargradient.construct.php',
    1 => 'CairoLinearGradient::__construct',
  ),
  1 => 
  array (
    0 => 'cairolineargradient.getpoints.php',
    1 => 'CairoLinearGradient::getPoints',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);