<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swftextfield.addchars.php',
    1 => 'SWFTextField-&gt;addChars',
  ),
  1 => 
  array (
    0 => 'function.swftextfield.addstring.php',
    1 => 'SWFTextField-&gt;addString',
  ),
  2 => 
  array (
    0 => 'function.swftextfield.align.php',
    1 => 'SWFTextField-&gt;align',
  ),
  3 => 
  array (
    0 => 'function.swftextfield.construct.php',
    1 => 'SWFTextField-&gt;__construct',
  ),
  4 => 
  array (
    0 => 'function.swftextfield.setbounds.php',
    1 => 'SWFTextField-&gt;setBounds',
  ),
  5 => 
  array (
    0 => 'function.swftextfield.setcolor.php',
    1 => 'SWFTextField-&gt;setColor',
  ),
  6 => 
  array (
    0 => 'function.swftextfield.setfont.php',
    1 => 'SWFTextField-&gt;setFont',
  ),
  7 => 
  array (
    0 => 'function.swftextfield.setheight.php',
    1 => 'SWFTextField-&gt;setHeight',
  ),
  8 => 
  array (
    0 => 'function.swftextfield.setindentation.php',
    1 => 'SWFTextField-&gt;setIndentation',
  ),
  9 => 
  array (
    0 => 'function.swftextfield.setleftmargin.php',
    1 => 'SWFTextField-&gt;setLeftMargin',
  ),
  10 => 
  array (
    0 => 'function.swftextfield.setlinespacing.php',
    1 => 'SWFTextField-&gt;setLineSpacing',
  ),
  11 => 
  array (
    0 => 'function.swftextfield.setmargins.php',
    1 => 'SWFTextField-&gt;setMargins',
  ),
  12 => 
  array (
    0 => 'function.swftextfield.setname.php',
    1 => 'SWFTextField-&gt;setName',
  ),
  13 => 
  array (
    0 => 'function.swftextfield.setpadding.php',
    1 => 'SWFTextField-&gt;setPadding',
  ),
  14 => 
  array (
    0 => 'function.swftextfield.setrightmargin.php',
    1 => 'SWFTextField-&gt;setRightMargin',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);