<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.httprequest-addcookies.php',
    1 => 'HttpRequest::addCookies',
  ),
  1 => 
  array (
    0 => 'function.httprequest-addheaders.php',
    1 => 'HttpRequest::addHeaders',
  ),
  2 => 
  array (
    0 => 'function.httprequest-addpostfields.php',
    1 => 'HttpRequest::addPostFields',
  ),
  3 => 
  array (
    0 => 'function.httprequest-addpostfile.php',
    1 => 'HttpRequest::addPostFile',
  ),
  4 => 
  array (
    0 => 'function.httprequest-addputdata.php',
    1 => 'HttpRequest::addPutData',
  ),
  5 => 
  array (
    0 => 'function.httprequest-addquerydata.php',
    1 => 'HttpRequest::addQueryData',
  ),
  6 => 
  array (
    0 => 'function.httprequest-addrawpostdata.php',
    1 => 'HttpRequest::addRawPostData',
  ),
  7 => 
  array (
    0 => 'function.httprequest-addssloptions.php',
    1 => 'HttpRequest::addSslOptions',
  ),
  8 => 
  array (
    0 => 'function.httprequest-clearhistory.php',
    1 => 'HttpRequest::clearHistory',
  ),
  9 => 
  array (
    0 => 'function.httprequest-construct.php',
    1 => 'HttpRequest::__construct',
  ),
  10 => 
  array (
    0 => 'function.httprequest-enablecookies.php',
    1 => 'HttpRequest::enableCookies',
  ),
  11 => 
  array (
    0 => 'function.httprequest-getcontenttype.php',
    1 => 'HttpRequest::getContentType',
  ),
  12 => 
  array (
    0 => 'function.httprequest-getcookies.php',
    1 => 'HttpRequest::getCookies',
  ),
  13 => 
  array (
    0 => 'function.httprequest-getheaders.php',
    1 => 'HttpRequest::getHeaders',
  ),
  14 => 
  array (
    0 => 'function.httprequest-gethistory.php',
    1 => 'HttpRequest::getHistory',
  ),
  15 => 
  array (
    0 => 'function.httprequest-getmethod.php',
    1 => 'HttpRequest::getMethod',
  ),
  16 => 
  array (
    0 => 'function.httprequest-getoptions.php',
    1 => 'HttpRequest::getOptions',
  ),
  17 => 
  array (
    0 => 'function.httprequest-getpostfields.php',
    1 => 'HttpRequest::getPostFields',
  ),
  18 => 
  array (
    0 => 'function.httprequest-getpostfiles.php',
    1 => 'HttpRequest::getPostFiles',
  ),
  19 => 
  array (
    0 => 'function.httprequest-getputdata.php',
    1 => 'HttpRequest::getPutData',
  ),
  20 => 
  array (
    0 => 'function.httprequest-getputfile.php',
    1 => 'HttpRequest::getPutFile',
  ),
  21 => 
  array (
    0 => 'function.httprequest-getquerydata.php',
    1 => 'HttpRequest::getQueryData',
  ),
  22 => 
  array (
    0 => 'function.httprequest-getrawpostdata.php',
    1 => 'HttpRequest::getRawPostData',
  ),
  23 => 
  array (
    0 => 'function.httprequest-getrawrequestmessage.php',
    1 => 'HttpRequest::getRawRequestMessage',
  ),
  24 => 
  array (
    0 => 'function.httprequest-getrawresponsemessage.php',
    1 => 'HttpRequest::getRawResponseMessage',
  ),
  25 => 
  array (
    0 => 'function.httprequest-getrequestmessage.php',
    1 => 'HttpRequest::getRequestMessage',
  ),
  26 => 
  array (
    0 => 'function.httprequest-getresponsebody.php',
    1 => 'HttpRequest::getResponseBody',
  ),
  27 => 
  array (
    0 => 'function.httprequest-getresponsecode.php',
    1 => 'HttpRequest::getResponseCode',
  ),
  28 => 
  array (
    0 => 'function.httprequest-getresponsecookies.php',
    1 => 'HttpRequest::getResponseCookies',
  ),
  29 => 
  array (
    0 => 'function.httprequest-getresponsedata.php',
    1 => 'HttpRequest::getResponseData',
  ),
  30 => 
  array (
    0 => 'function.httprequest-getresponseheader.php',
    1 => 'HttpRequest::getResponseHeader',
  ),
  31 => 
  array (
    0 => 'function.httprequest-getresponseinfo.php',
    1 => 'HttpRequest::getResponseInfo',
  ),
  32 => 
  array (
    0 => 'function.httprequest-getresponsemessage.php',
    1 => 'HttpRequest::getResponseMessage',
  ),
  33 => 
  array (
    0 => 'function.httprequest-getresponsestatus.php',
    1 => 'HttpRequest::getResponseStatus',
  ),
  34 => 
  array (
    0 => 'function.httprequest-getssloptions.php',
    1 => 'HttpRequest::getSslOptions',
  ),
  35 => 
  array (
    0 => 'function.httprequest-geturl.php',
    1 => 'HttpRequest::getUrl',
  ),
  36 => 
  array (
    0 => 'function.httprequest-resetcookies.php',
    1 => 'HttpRequest::resetCookies',
  ),
  37 => 
  array (
    0 => 'function.httprequest-send.php',
    1 => 'HttpRequest::send',
  ),
  38 => 
  array (
    0 => 'function.httprequest-setcontenttype.php',
    1 => 'HttpRequest::setContentType',
  ),
  39 => 
  array (
    0 => 'function.httprequest-setcookies.php',
    1 => 'HttpRequest::setCookies',
  ),
  40 => 
  array (
    0 => 'function.httprequest-setheaders.php',
    1 => 'HttpRequest::setHeaders',
  ),
  41 => 
  array (
    0 => 'function.httprequest-setmethod.php',
    1 => 'HttpRequest::setMethod',
  ),
  42 => 
  array (
    0 => 'function.httprequest-setoptions.php',
    1 => 'HttpRequest::setOptions',
  ),
  43 => 
  array (
    0 => 'function.httprequest-setpostfields.php',
    1 => 'HttpRequest::setPostFields',
  ),
  44 => 
  array (
    0 => 'function.httprequest-setpostfiles.php',
    1 => 'HttpRequest::setPostFiles',
  ),
  45 => 
  array (
    0 => 'function.httprequest-setputdata.php',
    1 => 'HttpRequest::setPutData',
  ),
  46 => 
  array (
    0 => 'function.httprequest-setputfile.php',
    1 => 'HttpRequest::setPutFile',
  ),
  47 => 
  array (
    0 => 'function.httprequest-setquerydata.php',
    1 => 'HttpRequest::setQueryData',
  ),
  48 => 
  array (
    0 => 'function.httprequest-setrawpostdata.php',
    1 => 'HttpRequest::setRawPostData',
  ),
  49 => 
  array (
    0 => 'function.httprequest-setssloptions.php',
    1 => 'HttpRequest::setSslOptions',
  ),
  50 => 
  array (
    0 => 'function.httprequest-seturl.php',
    1 => 'HttpRequest::setUrl',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.http.php',
    1 => 'HTTP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);