<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swffill.moveto.php',
    1 => 'SWFFill-&gt;moveTo',
  ),
  1 => 
  array (
    0 => 'function.swffill.rotateto.php',
    1 => 'SWFFill-&gt;rotateTo',
  ),
  2 => 
  array (
    0 => 'function.swffill.scaleto.php',
    1 => 'SWFFill-&gt;scaleTo',
  ),
  3 => 
  array (
    0 => 'function.swffill.skewxto.php',
    1 => 'SWFFill-&gt;skewXTo',
  ),
  4 => 
  array (
    0 => 'function.swffill.skewyto.php',
    1 => 'SWFFill-&gt;skewYTo',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);