<?php
$TOC = array (
  0 => 
  array (
    0 => 'mongodb.authenticate.php',
    1 => 'MongoDB::authenticate',
  ),
  1 => 
  array (
    0 => 'mongodb.command.php',
    1 => 'MongoDB::command',
  ),
  2 => 
  array (
    0 => 'mongodb.construct.php',
    1 => 'MongoDB::__construct',
  ),
  3 => 
  array (
    0 => 'mongodb.createcollection.php',
    1 => 'MongoDB::createCollection',
  ),
  4 => 
  array (
    0 => 'mongodb.createdbref.php',
    1 => 'MongoDB::createDBRef',
  ),
  5 => 
  array (
    0 => 'mongodb.drop.php',
    1 => 'MongoDB::drop',
  ),
  6 => 
  array (
    0 => 'mongodb.dropcollection.php',
    1 => 'MongoDB::dropCollection',
  ),
  7 => 
  array (
    0 => 'mongodb.execute.php',
    1 => 'MongoDB::execute',
  ),
  8 => 
  array (
    0 => 'mongodb.forceerror.php',
    1 => 'MongoDB::forceError',
  ),
  9 => 
  array (
    0 => 'mongodb.get.php',
    1 => 'MongoDB::__get',
  ),
  10 => 
  array (
    0 => 'mongodb.getdbref.php',
    1 => 'MongoDB::getDBRef',
  ),
  11 => 
  array (
    0 => 'mongodb.getgridfs.php',
    1 => 'MongoDB::getGridFS',
  ),
  12 => 
  array (
    0 => 'mongodb.getprofilinglevel.php',
    1 => 'MongoDB::getProfilingLevel',
  ),
  13 => 
  array (
    0 => 'mongodb.getslaveokay.php',
    1 => 'MongoDB::getSlaveOkay',
  ),
  14 => 
  array (
    0 => 'mongodb.lasterror.php',
    1 => 'MongoDB::lastError',
  ),
  15 => 
  array (
    0 => 'mongodb.listcollections.php',
    1 => 'MongoDB::listCollections',
  ),
  16 => 
  array (
    0 => 'mongodb.preverror.php',
    1 => 'MongoDB::prevError',
  ),
  17 => 
  array (
    0 => 'mongodb.repair.php',
    1 => 'MongoDB::repair',
  ),
  18 => 
  array (
    0 => 'mongodb.reseterror.php',
    1 => 'MongoDB::resetError',
  ),
  19 => 
  array (
    0 => 'mongodb.selectcollection.php',
    1 => 'MongoDB::selectCollection',
  ),
  20 => 
  array (
    0 => 'mongodb.setprofilinglevel.php',
    1 => 'MongoDB::setProfilingLevel',
  ),
  21 => 
  array (
    0 => 'mongodb.setslaveokay.php',
    1 => 'MongoDB::setSlaveOkay',
  ),
  22 => 
  array (
    0 => 'mongodb.--tostring.php',
    1 => 'MongoDB::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'mongo.core.php',
    1 => 'Core Classes',
  ),
  1 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  2 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  3 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  4 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  5 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);