<?php
$TOC = array (
  0 => 
  array (
    0 => 'splfixedarray.construct.php',
    1 => 'SplFixedArray::__construct',
  ),
  1 => 
  array (
    0 => 'splfixedarray.count.php',
    1 => 'SplFixedArray::count',
  ),
  2 => 
  array (
    0 => 'splfixedarray.current.php',
    1 => 'SplFixedArray::current',
  ),
  3 => 
  array (
    0 => 'splfixedarray.fromarray.php',
    1 => 'SplFixedArray::fromArray',
  ),
  4 => 
  array (
    0 => 'splfixedarray.getsize.php',
    1 => 'SplFixedArray::getSize',
  ),
  5 => 
  array (
    0 => 'splfixedarray.key.php',
    1 => 'SplFixedArray::key',
  ),
  6 => 
  array (
    0 => 'splfixedarray.next.php',
    1 => 'SplFixedArray::next',
  ),
  7 => 
  array (
    0 => 'splfixedarray.offsetexists.php',
    1 => 'SplFixedArray::offsetExists',
  ),
  8 => 
  array (
    0 => 'splfixedarray.offsetget.php',
    1 => 'SplFixedArray::offsetGet',
  ),
  9 => 
  array (
    0 => 'splfixedarray.offsetset.php',
    1 => 'SplFixedArray::offsetSet',
  ),
  10 => 
  array (
    0 => 'splfixedarray.offsetunset.php',
    1 => 'SplFixedArray::offsetUnset',
  ),
  11 => 
  array (
    0 => 'splfixedarray.rewind.php',
    1 => 'SplFixedArray::rewind',
  ),
  12 => 
  array (
    0 => 'splfixedarray.setsize.php',
    1 => 'SplFixedArray::setSize',
  ),
  13 => 
  array (
    0 => 'splfixedarray.toarray.php',
    1 => 'SplFixedArray::toArray',
  ),
  14 => 
  array (
    0 => 'splfixedarray.valid.php',
    1 => 'SplFixedArray::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.datastructures.php',
    1 => 'Datastructures',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);