<?php
$TOC = array (
  0 => 
  array (
    0 => 'seekableiterator.seek.php',
    1 => 'SeekableIterator::seek',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.interfaces.php',
    1 => 'Interfaces',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);