<?php
$TOC = array (
  0 => 
  array (
    0 => 'stomp.abort.php',
    1 => 'Stomp::abort',
  ),
  1 => 
  array (
    0 => 'stomp.ack.php',
    1 => 'Stomp::ack',
  ),
  2 => 
  array (
    0 => 'stomp.begin.php',
    1 => 'Stomp::begin',
  ),
  3 => 
  array (
    0 => 'stomp.commit.php',
    1 => 'Stomp::commit',
  ),
  4 => 
  array (
    0 => 'stomp.construct.php',
    1 => 'Stomp::__construct',
  ),
  5 => 
  array (
    0 => 'stomp.destruct.php',
    1 => 'Stomp::__destruct',
  ),
  6 => 
  array (
    0 => 'stomp.error.php',
    1 => 'Stomp::error',
  ),
  7 => 
  array (
    0 => 'stomp.getreadtimeout.php',
    1 => 'Stomp::getReadTimeout',
  ),
  8 => 
  array (
    0 => 'stomp.getsessionid.php',
    1 => 'Stomp::getSessionId',
  ),
  9 => 
  array (
    0 => 'stomp.hasframe.php',
    1 => 'Stomp::hasFrame',
  ),
  10 => 
  array (
    0 => 'stomp.readframe.php',
    1 => 'Stomp::readFrame',
  ),
  11 => 
  array (
    0 => 'stomp.send.php',
    1 => 'Stomp::send',
  ),
  12 => 
  array (
    0 => 'stomp.setreadtimeout.php',
    1 => 'Stomp::setReadTimeout',
  ),
  13 => 
  array (
    0 => 'stomp.subscribe.php',
    1 => 'Stomp::subscribe',
  ),
  14 => 
  array (
    0 => 'stomp.unsubscribe.php',
    1 => 'Stomp::unsubscribe',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.stomp.php',
    1 => 'Stomp',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);