<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairoimagesurface.construct.php',
    1 => 'CairoImageSurface::__construct',
  ),
  1 => 
  array (
    0 => 'cairoimagesurface.createfordata.php',
    1 => 'CairoImageSurface::createForData',
  ),
  2 => 
  array (
    0 => 'cairoimagesurface.createfrompng.php',
    1 => 'CairoImageSurface::createFromPng',
  ),
  3 => 
  array (
    0 => 'cairoimagesurface.getdata.php',
    1 => 'CairoImageSurface::getData',
  ),
  4 => 
  array (
    0 => 'cairoimagesurface.getformat.php',
    1 => 'CairoImageSurface::getFormat',
  ),
  5 => 
  array (
    0 => 'cairoimagesurface.getheight.php',
    1 => 'CairoImageSurface::getHeight',
  ),
  6 => 
  array (
    0 => 'cairoimagesurface.getstride.php',
    1 => 'CairoImageSurface::getStride',
  ),
  7 => 
  array (
    0 => 'cairoimagesurface.getwidth.php',
    1 => 'CairoImageSurface::getWidth',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);