<?php
$TOC = array (
  0 => 
  array (
    0 => 'spldoublylinkedlist.bottom.php',
    1 => 'SplDoublyLinkedList::bottom',
  ),
  1 => 
  array (
    0 => 'spldoublylinkedlist.construct.php',
    1 => 'SplDoublyLinkedList::__construct',
  ),
  2 => 
  array (
    0 => 'spldoublylinkedlist.count.php',
    1 => 'SplDoublyLinkedList::count',
  ),
  3 => 
  array (
    0 => 'spldoublylinkedlist.current.php',
    1 => 'SplDoublyLinkedList::current',
  ),
  4 => 
  array (
    0 => 'spldoublylinkedlist.getiteratormode.php',
    1 => 'SplDoublyLinkedList::getIteratorMode',
  ),
  5 => 
  array (
    0 => 'spldoublylinkedlist.isempty.php',
    1 => 'SplDoublyLinkedList::isEmpty',
  ),
  6 => 
  array (
    0 => 'spldoublylinkedlist.key.php',
    1 => 'SplDoublyLinkedList::key',
  ),
  7 => 
  array (
    0 => 'spldoublylinkedlist.next.php',
    1 => 'SplDoublyLinkedList::next',
  ),
  8 => 
  array (
    0 => 'spldoublylinkedlist.offsetexists.php',
    1 => 'SplDoublyLinkedList::offsetExists',
  ),
  9 => 
  array (
    0 => 'spldoublylinkedlist.offsetget.php',
    1 => 'SplDoublyLinkedList::offsetGet',
  ),
  10 => 
  array (
    0 => 'spldoublylinkedlist.offsetset.php',
    1 => 'SplDoublyLinkedList::offsetSet',
  ),
  11 => 
  array (
    0 => 'spldoublylinkedlist.offsetunset.php',
    1 => 'SplDoublyLinkedList::offsetUnset',
  ),
  12 => 
  array (
    0 => 'spldoublylinkedlist.pop.php',
    1 => 'SplDoublyLinkedList::pop',
  ),
  13 => 
  array (
    0 => 'spldoublylinkedlist.prev.php',
    1 => 'SplDoublyLinkedList::prev',
  ),
  14 => 
  array (
    0 => 'spldoublylinkedlist.push.php',
    1 => 'SplDoublyLinkedList::push',
  ),
  15 => 
  array (
    0 => 'spldoublylinkedlist.rewind.php',
    1 => 'SplDoublyLinkedList::rewind',
  ),
  16 => 
  array (
    0 => 'spldoublylinkedlist.setiteratormode.php',
    1 => 'SplDoublyLinkedList::setIteratorMode',
  ),
  17 => 
  array (
    0 => 'spldoublylinkedlist.shift.php',
    1 => 'SplDoublyLinkedList::shift',
  ),
  18 => 
  array (
    0 => 'spldoublylinkedlist.top.php',
    1 => 'SplDoublyLinkedList::top',
  ),
  19 => 
  array (
    0 => 'spldoublylinkedlist.unshift.php',
    1 => 'SplDoublyLinkedList::unshift',
  ),
  20 => 
  array (
    0 => 'spldoublylinkedlist.valid.php',
    1 => 'SplDoublyLinkedList::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.datastructures.php',
    1 => 'Datastructures',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);