<?php
$TOC = array (
  0 => 
  array (
    0 => 'soapclient.call.php',
    1 => 'SoapClient::__call',
  ),
  1 => 
  array (
    0 => 'soapclient.construct.php',
    1 => 'SoapClient::__construct',
  ),
  2 => 
  array (
    0 => 'soapclient.dorequest.php',
    1 => 'SoapClient::__doRequest',
  ),
  3 => 
  array (
    0 => 'soapclient.getfunctions.php',
    1 => 'SoapClient::__getFunctions',
  ),
  4 => 
  array (
    0 => 'soapclient.getlastrequest.php',
    1 => 'SoapClient::__getLastRequest',
  ),
  5 => 
  array (
    0 => 'soapclient.getlastrequestheaders.php',
    1 => 'SoapClient::__getLastRequestHeaders',
  ),
  6 => 
  array (
    0 => 'soapclient.getlastresponse.php',
    1 => 'SoapClient::__getLastResponse',
  ),
  7 => 
  array (
    0 => 'soapclient.getlastresponseheaders.php',
    1 => 'SoapClient::__getLastResponseHeaders',
  ),
  8 => 
  array (
    0 => 'soapclient.gettypes.php',
    1 => 'SoapClient::__getTypes',
  ),
  9 => 
  array (
    0 => 'soapclient.setcookie.php',
    1 => 'SoapClient::__setCookie',
  ),
  10 => 
  array (
    0 => 'soapclient.setlocation.php',
    1 => 'SoapClient::__setLocation',
  ),
  11 => 
  array (
    0 => 'soapclient.setsoapheaders.php',
    1 => 'SoapClient::__setSoapHeaders',
  ),
  12 => 
  array (
    0 => 'soapclient.soapcall.php',
    1 => 'SoapClient::__soapCall',
  ),
  13 => 
  array (
    0 => 'soapclient.soapclient.php',
    1 => 'SoapClient::SoapClient',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.soap.php',
    1 => 'SOAP',
  ),
  1 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);