<?php
$TOC = array (
  0 => 
  array (
    0 => 'splpriorityqueue.compare.php',
    1 => 'SplPriorityQueue::compare',
  ),
  1 => 
  array (
    0 => 'splpriorityqueue.construct.php',
    1 => 'SplPriorityQueue::__construct',
  ),
  2 => 
  array (
    0 => 'splpriorityqueue.count.php',
    1 => 'SplPriorityQueue::count',
  ),
  3 => 
  array (
    0 => 'splpriorityqueue.current.php',
    1 => 'SplPriorityQueue::current',
  ),
  4 => 
  array (
    0 => 'splpriorityqueue.extract.php',
    1 => 'SplPriorityQueue::extract',
  ),
  5 => 
  array (
    0 => 'splpriorityqueue.insert.php',
    1 => 'SplPriorityQueue::insert',
  ),
  6 => 
  array (
    0 => 'splpriorityqueue.isempty.php',
    1 => 'SplPriorityQueue::isEmpty',
  ),
  7 => 
  array (
    0 => 'splpriorityqueue.key.php',
    1 => 'SplPriorityQueue::key',
  ),
  8 => 
  array (
    0 => 'splpriorityqueue.next.php',
    1 => 'SplPriorityQueue::next',
  ),
  9 => 
  array (
    0 => 'splpriorityqueue.recoverfromcorruption.php',
    1 => 'SplPriorityQueue::recoverFromCorruption',
  ),
  10 => 
  array (
    0 => 'splpriorityqueue.rewind.php',
    1 => 'SplPriorityQueue::rewind',
  ),
  11 => 
  array (
    0 => 'splpriorityqueue.setextractflags.php',
    1 => 'SplPriorityQueue::setExtractFlags',
  ),
  12 => 
  array (
    0 => 'splpriorityqueue.top.php',
    1 => 'SplPriorityQueue::top',
  ),
  13 => 
  array (
    0 => 'splpriorityqueue.valid.php',
    1 => 'SplPriorityQueue::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.datastructures.php',
    1 => 'Datastructures',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);