<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.httpquerystring-construct.php',
    1 => 'HttpQueryString::__construct',
  ),
  1 => 
  array (
    0 => 'function.httpquerystring-get.php',
    1 => 'HttpQueryString::get',
  ),
  2 => 
  array (
    0 => 'function.httpquerystring-mod.php',
    1 => 'HttpQueryString::mod',
  ),
  3 => 
  array (
    0 => 'function.httpquerystring-set.php',
    1 => 'HttpQueryString::set',
  ),
  4 => 
  array (
    0 => 'function.httpquerystring-singleton.php',
    1 => 'HttpQueryString::singleton',
  ),
  5 => 
  array (
    0 => 'function.httpquerystring-toarray.php',
    1 => 'HttpQueryString::toArray',
  ),
  6 => 
  array (
    0 => 'function.httpquerystring-tostring.php',
    1 => 'HttpQueryString::toString',
  ),
  7 => 
  array (
    0 => 'function.httpquerystring-xlate.php',
    1 => 'HttpQueryString::xlate',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.http.php',
    1 => 'HTTP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);