<?php
$TOC = array (
  0 => 
  array (
    0 => 'domimplementation.construct.php',
    1 => 'DOMImplementation::__construct',
  ),
  1 => 
  array (
    0 => 'domimplementation.createdocument.php',
    1 => 'DOMImplementation::createDocument',
  ),
  2 => 
  array (
    0 => 'domimplementation.createdocumenttype.php',
    1 => 'DOMImplementation::createDocumentType',
  ),
  3 => 
  array (
    0 => 'domimplementation.hasfeature.php',
    1 => 'DOMImplementation::hasFeature',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dom.php',
    1 => 'DOM',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);