<?php
$TOC = array (
  0 => 
  array (
    0 => 'splfloat.construct.php',
    1 => 'SplFloat::__construct',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.spl-types.php',
    1 => 'SPL Types',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);