<?php
$TOC = array (
  0 => 
  array (
    0 => 'solrutils.digestxmlresponse.php',
    1 => 'SolrUtils::digestXmlResponse',
  ),
  1 => 
  array (
    0 => 'solrutils.escapequerychars.php',
    1 => 'SolrUtils::escapeQueryChars',
  ),
  2 => 
  array (
    0 => 'solrutils.getsolrversion.php',
    1 => 'SolrUtils::getSolrVersion',
  ),
  3 => 
  array (
    0 => 'solrutils.queryphrase.php',
    1 => 'SolrUtils::queryPhrase',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.solr.php',
    1 => 'Solr',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);