<?php
$TOC = array (
  0 => 
  array (
    0 => 'dateperiod.construct.php',
    1 => 'DatePeriod::__construct',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.datetime.php',
    1 => 'Date/Time',
  ),
  1 => 
  array (
    0 => 'refs.calendar.php',
    1 => 'Date and Time Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);