<?php
$TOC = array (
  0 => 
  array (
    0 => 'stompframe.construct.php',
    1 => 'StompFrame::__construct',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.stomp.php',
    1 => 'Stomp',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);