<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.harudestination-setfit.php',
    1 => 'HaruDestination::setFit',
  ),
  1 => 
  array (
    0 => 'function.harudestination-setfitb.php',
    1 => 'HaruDestination::setFitB',
  ),
  2 => 
  array (
    0 => 'function.harudestination-setfitbh.php',
    1 => 'HaruDestination::setFitBH',
  ),
  3 => 
  array (
    0 => 'function.harudestination-setfitbv.php',
    1 => 'HaruDestination::setFitBV',
  ),
  4 => 
  array (
    0 => 'function.harudestination-setfith.php',
    1 => 'HaruDestination::setFitH',
  ),
  5 => 
  array (
    0 => 'function.harudestination-setfitr.php',
    1 => 'HaruDestination::setFitR',
  ),
  6 => 
  array (
    0 => 'function.harudestination-setfitv.php',
    1 => 'HaruDestination::setFitV',
  ),
  7 => 
  array (
    0 => 'function.harudestination-setxyz.php',
    1 => 'HaruDestination::setXYZ',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.haru.php',
    1 => 'haru',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);