<?php
$TOC = array (
  0 => 
  array (
    0 => 'filteriterator.accept.php',
    1 => 'FilterIterator::accept',
  ),
  1 => 
  array (
    0 => 'filteriterator.construct.php',
    1 => 'FilterIterator::__construct',
  ),
  2 => 
  array (
    0 => 'filteriterator.current.php',
    1 => 'FilterIterator::current',
  ),
  3 => 
  array (
    0 => 'filteriterator.getinneriterator.php',
    1 => 'FilterIterator::getInnerIterator',
  ),
  4 => 
  array (
    0 => 'filteriterator.key.php',
    1 => 'FilterIterator::key',
  ),
  5 => 
  array (
    0 => 'filteriterator.next.php',
    1 => 'FilterIterator::next',
  ),
  6 => 
  array (
    0 => 'filteriterator.rewind.php',
    1 => 'FilterIterator::rewind',
  ),
  7 => 
  array (
    0 => 'filteriterator.valid.php',
    1 => 'FilterIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);