<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swfsprite.add.php',
    1 => 'SWFSprite-&gt;add',
  ),
  1 => 
  array (
    0 => 'function.swfsprite.construct.php',
    1 => 'SWFSprite-&gt;__construct',
  ),
  2 => 
  array (
    0 => 'function.swfsprite.labelframe.php',
    1 => 'SWFSprite-&gt;labelFrame',
  ),
  3 => 
  array (
    0 => 'function.swfsprite.nextframe.php',
    1 => 'SWFSprite-&gt;nextFrame',
  ),
  4 => 
  array (
    0 => 'function.swfsprite.remove.php',
    1 => 'SWFSprite-&gt;remove',
  ),
  5 => 
  array (
    0 => 'function.swfsprite.setframes.php',
    1 => 'SWFSprite-&gt;setFrames',
  ),
  6 => 
  array (
    0 => 'function.swfsprite.startsound.php',
    1 => 'SWFSprite-&gt;startSound',
  ),
  7 => 
  array (
    0 => 'function.swfsprite.stopsound.php',
    1 => 'SWFSprite-&gt;stopSound',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);