<?php
$TOC = array (
  0 => 
  array (
    0 => 'simplexmliterator.current.php',
    1 => 'SimpleXMLIterator::current',
  ),
  1 => 
  array (
    0 => 'simplexmliterator.getchildren.php',
    1 => 'SimpleXMLIterator::getChildren',
  ),
  2 => 
  array (
    0 => 'simplexmliterator.haschildren.php',
    1 => 'SimpleXMLIterator::hasChildren',
  ),
  3 => 
  array (
    0 => 'simplexmliterator.key.php',
    1 => 'SimpleXMLIterator::key',
  ),
  4 => 
  array (
    0 => 'simplexmliterator.next.php',
    1 => 'SimpleXMLIterator::next',
  ),
  5 => 
  array (
    0 => 'simplexmliterator.rewind.php',
    1 => 'SimpleXMLIterator::rewind',
  ),
  6 => 
  array (
    0 => 'simplexmliterator.valid.php',
    1 => 'SimpleXMLIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);