<?php
$TOC = array (
  0 => 
  array (
    0 => 'solrobject.construct.php',
    1 => 'SolrObject::__construct',
  ),
  1 => 
  array (
    0 => 'solrobject.destruct.php',
    1 => 'SolrObject::__destruct',
  ),
  2 => 
  array (
    0 => 'solrobject.getpropertynames.php',
    1 => 'SolrObject::getPropertyNames',
  ),
  3 => 
  array (
    0 => 'solrobject.offsetexists.php',
    1 => 'SolrObject::offsetExists',
  ),
  4 => 
  array (
    0 => 'solrobject.offsetget.php',
    1 => 'SolrObject::offsetGet',
  ),
  5 => 
  array (
    0 => 'solrobject.offsetset.php',
    1 => 'SolrObject::offsetSet',
  ),
  6 => 
  array (
    0 => 'solrobject.offsetunset.php',
    1 => 'SolrObject::offsetUnset',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.solr.php',
    1 => 'Solr',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);