<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairosurfacepattern.construct.php',
    1 => 'CairoSurfacePattern::__construct',
  ),
  1 => 
  array (
    0 => 'cairosurfacepattern.getextend.php',
    1 => 'CairoSurfacePattern::getExtend',
  ),
  2 => 
  array (
    0 => 'cairosurfacepattern.getfilter.php',
    1 => 'CairoSurfacePattern::getFilter',
  ),
  3 => 
  array (
    0 => 'cairosurfacepattern.getsurface.php',
    1 => 'CairoSurfacePattern::getSurface',
  ),
  4 => 
  array (
    0 => 'cairosurfacepattern.setextend.php',
    1 => 'CairoSurfacePattern::setExtend',
  ),
  5 => 
  array (
    0 => 'cairosurfacepattern.setfilter.php',
    1 => 'CairoSurfacePattern::setFilter',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);