<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swffont.construct.php',
    1 => 'SWFFont-&gt;__construct',
  ),
  1 => 
  array (
    0 => 'function.swffont.getascent.php',
    1 => 'SWFFont-&gt;getAscent',
  ),
  2 => 
  array (
    0 => 'function.swffont.getdescent.php',
    1 => 'SWFFont-&gt;getDescent',
  ),
  3 => 
  array (
    0 => 'function.swffont.getleading.php',
    1 => 'SWFFont-&gt;getLeading',
  ),
  4 => 
  array (
    0 => 'function.swffont.getshape.php',
    1 => 'SWFFont-&gt;getShape',
  ),
  5 => 
  array (
    0 => 'function.swffont.getutf8width.php',
    1 => 'SWFFont-&gt;getUTF8Width',
  ),
  6 => 
  array (
    0 => 'function.swffont.getwidth.php',
    1 => 'SWFFont-&gt;getWidth',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);