<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairopssurface.construct.php',
    1 => 'CairoPsSurface::__construct',
  ),
  1 => 
  array (
    0 => 'cairopssurface.dscbeginpagesetup.php',
    1 => 'CairoPsSurface::dscBeginPageSetup',
  ),
  2 => 
  array (
    0 => 'cairopssurface.dscbeginsetup.php',
    1 => 'CairoPsSurface::dscBeginSetup',
  ),
  3 => 
  array (
    0 => 'cairopssurface.dsccomment.php',
    1 => 'CairoPsSurface::dscComment',
  ),
  4 => 
  array (
    0 => 'cairopssurface.geteps.php',
    1 => 'CairoPsSurface::getEps',
  ),
  5 => 
  array (
    0 => 'cairopssurface.getlevels.php',
    1 => 'CairoPsSurface::getLevels',
  ),
  6 => 
  array (
    0 => 'cairopssurface.leveltostring.php',
    1 => 'CairoPsSurface::levelToString',
  ),
  7 => 
  array (
    0 => 'cairopssurface.restricttolevel.php',
    1 => 'CairoPsSurface::restrictToLevel',
  ),
  8 => 
  array (
    0 => 'cairopssurface.seteps.php',
    1 => 'CairoPsSurface::setEps',
  ),
  9 => 
  array (
    0 => 'cairopssurface.setsize.php',
    1 => 'CairoPsSurface::setSize',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);