<?php
$TOC = array (
  0 => 
  array (
    0 => 'errorexception.construct.php',
    1 => 'ErrorException::__construct',
  ),
  1 => 
  array (
    0 => 'errorexception.getseverity.php',
    1 => 'ErrorException::getSeverity',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'reserved.exceptions.php',
    1 => 'Predefined Exceptions',
  ),
  1 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);