<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.harufont-getascent.php',
    1 => 'HaruFont::getAscent',
  ),
  1 => 
  array (
    0 => 'function.harufont-getcapheight.php',
    1 => 'HaruFont::getCapHeight',
  ),
  2 => 
  array (
    0 => 'function.harufont-getdescent.php',
    1 => 'HaruFont::getDescent',
  ),
  3 => 
  array (
    0 => 'function.harufont-getencodingname.php',
    1 => 'HaruFont::getEncodingName',
  ),
  4 => 
  array (
    0 => 'function.harufont-getfontname.php',
    1 => 'HaruFont::getFontName',
  ),
  5 => 
  array (
    0 => 'function.harufont-gettextwidth.php',
    1 => 'HaruFont::getTextWidth',
  ),
  6 => 
  array (
    0 => 'function.harufont-getunicodewidth.php',
    1 => 'HaruFont::getUnicodeWidth',
  ),
  7 => 
  array (
    0 => 'function.harufont-getxheight.php',
    1 => 'HaruFont::getXHeight',
  ),
  8 => 
  array (
    0 => 'function.harufont-measuretext.php',
    1 => 'HaruFont::measureText',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.haru.php',
    1 => 'haru',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);