<?php
$TOC = array (
  0 => 
  array (
    0 => 'mysqli.affected-rows.php',
    1 => 'mysqli-&gt;affected_rows',
  ),
  1 => 
  array (
    0 => 'mysqli.autocommit.php',
    1 => 'mysqli::autocommit',
  ),
  2 => 
  array (
    0 => 'mysqli.change-user.php',
    1 => 'mysqli::change_user',
  ),
  3 => 
  array (
    0 => 'mysqli.character-set-name.php',
    1 => 'mysqli::character_set_name',
  ),
  4 => 
  array (
    0 => 'mysqli.client-info.php',
    1 => 'mysqli-&gt;client_info',
  ),
  5 => 
  array (
    0 => 'mysqli.client-version.php',
    1 => 'mysqli-&gt;client_version',
  ),
  6 => 
  array (
    0 => 'mysqli.close.php',
    1 => 'mysqli::close',
  ),
  7 => 
  array (
    0 => 'mysqli.commit.php',
    1 => 'mysqli::commit',
  ),
  8 => 
  array (
    0 => 'mysqli.connect-errno.php',
    1 => 'mysqli-&gt;connect_errno',
  ),
  9 => 
  array (
    0 => 'mysqli.connect-error.php',
    1 => 'mysqli-&gt;connect_error',
  ),
  10 => 
  array (
    0 => 'mysqli.connect.php',
    1 => 'mysqli::__construct',
  ),
  11 => 
  array (
    0 => 'mysqli.debug.php',
    1 => 'mysqli::debug',
  ),
  12 => 
  array (
    0 => 'mysqli.dump-debug-info.php',
    1 => 'mysqli::dump_debug_info',
  ),
  13 => 
  array (
    0 => 'mysqli.errno.php',
    1 => 'mysqli-&gt;errno',
  ),
  14 => 
  array (
    0 => 'mysqli.error.php',
    1 => 'mysqli-&gt;error',
  ),
  15 => 
  array (
    0 => 'mysqli.field-count.php',
    1 => 'mysqli-&gt;field_count',
  ),
  16 => 
  array (
    0 => 'mysqli.get-charset.php',
    1 => 'mysqli::get_charset',
  ),
  17 => 
  array (
    0 => 'mysqli.get-client-info.php',
    1 => 'mysqli-&gt;get_client_info',
  ),
  18 => 
  array (
    0 => 'mysqli.get-client-stats.php',
    1 => 'mysqli_get_client_stats',
  ),
  19 => 
  array (
    0 => 'mysqli.get-client-version.php',
    1 => 'mysqli-&gt;client_version',
  ),
  20 => 
  array (
    0 => 'mysqli.get-connection-stats.php',
    1 => 'mysqli::get_connection_stats',
  ),
  21 => 
  array (
    0 => 'mysqli.get-host-info.php',
    1 => 'mysqli-&gt;host_info',
  ),
  22 => 
  array (
    0 => 'mysqli.get-proto-info.php',
    1 => 'mysqli-&gt;protocol_version',
  ),
  23 => 
  array (
    0 => 'mysqli.get-server-info.php',
    1 => 'mysqli-&gt;server_info',
  ),
  24 => 
  array (
    0 => 'mysqli.get-server-version.php',
    1 => 'mysqli-&gt;server_version',
  ),
  25 => 
  array (
    0 => 'mysqli.get-warnings.php',
    1 => 'mysqli::get_warnings',
  ),
  26 => 
  array (
    0 => 'mysqli.info.php',
    1 => 'mysqli-&gt;info',
  ),
  27 => 
  array (
    0 => 'mysqli.init.php',
    1 => 'mysqli::init',
  ),
  28 => 
  array (
    0 => 'mysqli.insert-id.php',
    1 => 'mysqli-&gt;insert_id',
  ),
  29 => 
  array (
    0 => 'mysqli.kill.php',
    1 => 'mysqli::kill',
  ),
  30 => 
  array (
    0 => 'mysqli.more-results.php',
    1 => 'mysqli::more_results',
  ),
  31 => 
  array (
    0 => 'mysqli.multi-query.php',
    1 => 'mysqli::multi_query',
  ),
  32 => 
  array (
    0 => 'mysqli.next-result.php',
    1 => 'mysqli::next_result',
  ),
  33 => 
  array (
    0 => 'mysqli.options.php',
    1 => 'mysqli::options',
  ),
  34 => 
  array (
    0 => 'mysqli.ping.php',
    1 => 'mysqli::ping',
  ),
  35 => 
  array (
    0 => 'mysqli.poll.php',
    1 => 'mysqli::poll',
  ),
  36 => 
  array (
    0 => 'mysqli.prepare.php',
    1 => 'mysqli::prepare',
  ),
  37 => 
  array (
    0 => 'mysqli.query.php',
    1 => 'mysqli::query',
  ),
  38 => 
  array (
    0 => 'mysqli.real-connect.php',
    1 => 'mysqli::real_connect',
  ),
  39 => 
  array (
    0 => 'mysqli.real-escape-string.php',
    1 => 'mysqli::real_escape_string',
  ),
  40 => 
  array (
    0 => 'mysqli.real-query.php',
    1 => 'mysqli::real_query',
  ),
  41 => 
  array (
    0 => 'mysqli.reap-async-query.php',
    1 => 'mysqli::reap_async_query',
  ),
  42 => 
  array (
    0 => 'mysqli.rollback.php',
    1 => 'mysqli::rollback',
  ),
  43 => 
  array (
    0 => 'mysqli.select-db.php',
    1 => 'mysqli::select_db',
  ),
  44 => 
  array (
    0 => 'mysqli.set-charset.php',
    1 => 'mysqli::set_charset',
  ),
  45 => 
  array (
    0 => 'mysqli.set-local-infile-default.php',
    1 => 'mysqli::set_local_infile_default',
  ),
  46 => 
  array (
    0 => 'mysqli.set-local-infile-handler.php',
    1 => 'mysqli::set_local_infile_handler',
  ),
  47 => 
  array (
    0 => 'mysqli.sqlstate.php',
    1 => 'mysqli-&gt;sqlstate',
  ),
  48 => 
  array (
    0 => 'mysqli.ssl-set.php',
    1 => 'mysqli::ssl_set',
  ),
  49 => 
  array (
    0 => 'mysqli.stat.php',
    1 => 'mysqli::stat',
  ),
  50 => 
  array (
    0 => 'mysqli.stmt-init.php',
    1 => 'mysqli::stmt_init',
  ),
  51 => 
  array (
    0 => 'mysqli.store-result.php',
    1 => 'mysqli::store_result',
  ),
  52 => 
  array (
    0 => 'mysqli.thread-id.php',
    1 => 'mysqli-&gt;thread_id',
  ),
  53 => 
  array (
    0 => 'mysqli.thread-safe.php',
    1 => 'mysqli::thread_safe',
  ),
  54 => 
  array (
    0 => 'mysqli.use-result.php',
    1 => 'mysqli::use_result',
  ),
  55 => 
  array (
    0 => 'mysqli.warning-count.php',
    1 => 'mysqli-&gt;warning_count',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mysqli.php',
    1 => 'Mysqli',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);