<?php
$TOC = array (
  0 => 
  array (
    0 => 'gearmanclient.addoptions.php',
    1 => 'GearmanClient::addOptions',
  ),
  1 => 
  array (
    0 => 'gearmanclient.addserver.php',
    1 => 'GearmanClient::addServer',
  ),
  2 => 
  array (
    0 => 'gearmanclient.addservers.php',
    1 => 'GearmanClient::addServers',
  ),
  3 => 
  array (
    0 => 'gearmanclient.addtask.php',
    1 => 'GearmanClient::addTask',
  ),
  4 => 
  array (
    0 => 'gearmanclient.addtaskbackground.php',
    1 => 'GearmanClient::addTaskBackground',
  ),
  5 => 
  array (
    0 => 'gearmanclient.addtaskhigh.php',
    1 => 'GearmanClient::addTaskHigh',
  ),
  6 => 
  array (
    0 => 'gearmanclient.addtaskhighbackground.php',
    1 => 'GearmanClient::addTaskHighBackground',
  ),
  7 => 
  array (
    0 => 'gearmanclient.addtasklow.php',
    1 => 'GearmanClient::addTaskLow',
  ),
  8 => 
  array (
    0 => 'gearmanclient.addtasklowbackground.php',
    1 => 'GearmanClient::addTaskLowBackground',
  ),
  9 => 
  array (
    0 => 'gearmanclient.addtaskstatus.php',
    1 => 'GearmanClient::addTaskStatus',
  ),
  10 => 
  array (
    0 => 'gearmanclient.clearcallbacks.php',
    1 => 'GearmanClient::clearCallbacks',
  ),
  11 => 
  array (
    0 => 'gearmanclient.clone.php',
    1 => 'GearmanClient::clone',
  ),
  12 => 
  array (
    0 => 'gearmanclient.construct.php',
    1 => 'GearmanClient::__construct',
  ),
  13 => 
  array (
    0 => 'gearmanclient.context.php',
    1 => 'GearmanClient::context',
  ),
  14 => 
  array (
    0 => 'gearmanclient.data.php',
    1 => 'GearmanClient::data',
  ),
  15 => 
  array (
    0 => 'gearmanclient.do.php',
    1 => 'GearmanClient::do',
  ),
  16 => 
  array (
    0 => 'gearmanclient.dobackground.php',
    1 => 'GearmanClient::doBackground',
  ),
  17 => 
  array (
    0 => 'gearmanclient.dohigh.php',
    1 => 'GearmanClient::doHigh',
  ),
  18 => 
  array (
    0 => 'gearmanclient.dohighbackground.php',
    1 => 'GearmanClient::doHighBackground',
  ),
  19 => 
  array (
    0 => 'gearmanclient.dojobhandle.php',
    1 => 'GearmanClient::doJobHandle',
  ),
  20 => 
  array (
    0 => 'gearmanclient.dolow.php',
    1 => 'GearmanClient::doLow',
  ),
  21 => 
  array (
    0 => 'gearmanclient.dolowbackground.php',
    1 => 'GearmanClient::doLowBackground',
  ),
  22 => 
  array (
    0 => 'gearmanclient.dostatus.php',
    1 => 'GearmanClient::doStatus',
  ),
  23 => 
  array (
    0 => 'gearmanclient.echo.php',
    1 => 'GearmanClient::echo',
  ),
  24 => 
  array (
    0 => 'gearmanclient.error.php',
    1 => 'GearmanClient::error',
  ),
  25 => 
  array (
    0 => 'gearmanclient.geterrno.php',
    1 => 'GearmanClient::getErrno',
  ),
  26 => 
  array (
    0 => 'gearmanclient.jobstatus.php',
    1 => 'GearmanClient::jobStatus',
  ),
  27 => 
  array (
    0 => 'gearmanclient.removeoptions.php',
    1 => 'GearmanClient::removeOptions',
  ),
  28 => 
  array (
    0 => 'gearmanclient.returncode.php',
    1 => 'GearmanClient::returnCode',
  ),
  29 => 
  array (
    0 => 'gearmanclient.runtasks.php',
    1 => 'GearmanClient::runTasks',
  ),
  30 => 
  array (
    0 => 'gearmanclient.setclientcallback.php',
    1 => 'GearmanClient::setClientCallback',
  ),
  31 => 
  array (
    0 => 'gearmanclient.setcompletecallback.php',
    1 => 'GearmanClient::setCompleteCallback',
  ),
  32 => 
  array (
    0 => 'gearmanclient.setcontext.php',
    1 => 'GearmanClient::setContext',
  ),
  33 => 
  array (
    0 => 'gearmanclient.setcreatedcallback.php',
    1 => 'GearmanClient::setCreatedCallback',
  ),
  34 => 
  array (
    0 => 'gearmanclient.setdata.php',
    1 => 'GearmanClient::setData',
  ),
  35 => 
  array (
    0 => 'gearmanclient.setdatacallback.php',
    1 => 'GearmanClient::setDataCallback',
  ),
  36 => 
  array (
    0 => 'gearmanclient.setexceptioncallback.php',
    1 => 'GearmanClient::setExceptionCallback',
  ),
  37 => 
  array (
    0 => 'gearmanclient.setfailcallback.php',
    1 => 'GearmanClient::setFailCallback',
  ),
  38 => 
  array (
    0 => 'gearmanclient.setoptions.php',
    1 => 'GearmanClient::setOptions',
  ),
  39 => 
  array (
    0 => 'gearmanclient.setstatuscallback.php',
    1 => 'GearmanClient::setStatusCallback',
  ),
  40 => 
  array (
    0 => 'gearmanclient.settimeout.php',
    1 => 'GearmanClient::setTimeout',
  ),
  41 => 
  array (
    0 => 'gearmanclient.setwarningcallback.php',
    1 => 'GearmanClient::setWarningCallback',
  ),
  42 => 
  array (
    0 => 'gearmanclient.setworkloadcallback.php',
    1 => 'GearmanClient::setWorkloadCallback',
  ),
  43 => 
  array (
    0 => 'gearmanclient.timeout.php',
    1 => 'GearmanClient::timeout',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gearman.php',
    1 => 'Gearman',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);