<?php
$TOC = array (
  0 => 
  array (
    0 => 'recursivetreeiterator.beginchildren.php',
    1 => 'RecursiveTreeIterator::beginChildren',
  ),
  1 => 
  array (
    0 => 'recursivetreeiterator.beginiteration.php',
    1 => 'RecursiveTreeIterator::beginIteration',
  ),
  2 => 
  array (
    0 => 'recursivetreeiterator.callgetchildren.php',
    1 => 'RecursiveTreeIterator::callGetChildren',
  ),
  3 => 
  array (
    0 => 'recursivetreeiterator.callhaschildren.php',
    1 => 'RecursiveTreeIterator::callHasChildren',
  ),
  4 => 
  array (
    0 => 'recursivetreeiterator.construct.php',
    1 => 'RecursiveTreeIterator::__construct',
  ),
  5 => 
  array (
    0 => 'recursivetreeiterator.current.php',
    1 => 'RecursiveTreeIterator::current',
  ),
  6 => 
  array (
    0 => 'recursivetreeiterator.endchildren.php',
    1 => 'RecursiveTreeIterator::endChildren',
  ),
  7 => 
  array (
    0 => 'recursivetreeiterator.enditeration.php',
    1 => 'RecursiveTreeIterator::endIteration',
  ),
  8 => 
  array (
    0 => 'recursivetreeiterator.getentry.php',
    1 => 'RecursiveTreeIterator::getEntry',
  ),
  9 => 
  array (
    0 => 'recursivetreeiterator.getpostfix.php',
    1 => 'RecursiveTreeIterator::getPostfix',
  ),
  10 => 
  array (
    0 => 'recursivetreeiterator.getprefix.php',
    1 => 'RecursiveTreeIterator::getPrefix',
  ),
  11 => 
  array (
    0 => 'recursivetreeiterator.key.php',
    1 => 'RecursiveTreeIterator::key',
  ),
  12 => 
  array (
    0 => 'recursivetreeiterator.next.php',
    1 => 'RecursiveTreeIterator::next',
  ),
  13 => 
  array (
    0 => 'recursivetreeiterator.nextelement.php',
    1 => 'RecursiveTreeIterator::nextElement',
  ),
  14 => 
  array (
    0 => 'recursivetreeiterator.rewind.php',
    1 => 'RecursiveTreeIterator::rewind',
  ),
  15 => 
  array (
    0 => 'recursivetreeiterator.setprefixpart.php',
    1 => 'RecursiveTreeIterator::setPrefixPart',
  ),
  16 => 
  array (
    0 => 'recursivetreeiterator.valid.php',
    1 => 'RecursiveTreeIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);