<?php
$TOC = array (
  0 => 
  array (
    0 => 'splqueue.construct.php',
    1 => 'SplQueue::__construct',
  ),
  1 => 
  array (
    0 => 'splqueue.dequeue.php',
    1 => 'SplQueue::dequeue',
  ),
  2 => 
  array (
    0 => 'splqueue.enqueue.php',
    1 => 'SplQueue::enqueue',
  ),
  3 => 
  array (
    0 => 'splqueue.setiteratormode.php',
    1 => 'SplQueue::setIteratorMode',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.datastructures.php',
    1 => 'Datastructures',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);