<?php
$TOC = array (
  0 => 
  array (
    0 => 'directoryiterator.construct.php',
    1 => 'DirectoryIterator::__construct',
  ),
  1 => 
  array (
    0 => 'directoryiterator.current.php',
    1 => 'DirectoryIterator::current',
  ),
  2 => 
  array (
    0 => 'directoryiterator.getatime.php',
    1 => 'DirectoryIterator::getATime',
  ),
  3 => 
  array (
    0 => 'directoryiterator.getbasename.php',
    1 => 'DirectoryIterator::getBasename',
  ),
  4 => 
  array (
    0 => 'directoryiterator.getctime.php',
    1 => 'DirectoryIterator::getCTime',
  ),
  5 => 
  array (
    0 => 'directoryiterator.getfilename.php',
    1 => 'DirectoryIterator::getFilename',
  ),
  6 => 
  array (
    0 => 'directoryiterator.getgroup.php',
    1 => 'DirectoryIterator::getGroup',
  ),
  7 => 
  array (
    0 => 'directoryiterator.getinode.php',
    1 => 'DirectoryIterator::getInode',
  ),
  8 => 
  array (
    0 => 'directoryiterator.getmtime.php',
    1 => 'DirectoryIterator::getMTime',
  ),
  9 => 
  array (
    0 => 'directoryiterator.getowner.php',
    1 => 'DirectoryIterator::getOwner',
  ),
  10 => 
  array (
    0 => 'directoryiterator.getpath.php',
    1 => 'DirectoryIterator::getPath',
  ),
  11 => 
  array (
    0 => 'directoryiterator.getpathname.php',
    1 => 'DirectoryIterator::getPathname',
  ),
  12 => 
  array (
    0 => 'directoryiterator.getperms.php',
    1 => 'DirectoryIterator::getPerms',
  ),
  13 => 
  array (
    0 => 'directoryiterator.getsize.php',
    1 => 'DirectoryIterator::getSize',
  ),
  14 => 
  array (
    0 => 'directoryiterator.gettype.php',
    1 => 'DirectoryIterator::getType',
  ),
  15 => 
  array (
    0 => 'directoryiterator.isdir.php',
    1 => 'DirectoryIterator::isDir',
  ),
  16 => 
  array (
    0 => 'directoryiterator.isdot.php',
    1 => 'DirectoryIterator::isDot',
  ),
  17 => 
  array (
    0 => 'directoryiterator.isexecutable.php',
    1 => 'DirectoryIterator::isExecutable',
  ),
  18 => 
  array (
    0 => 'directoryiterator.isfile.php',
    1 => 'DirectoryIterator::isFile',
  ),
  19 => 
  array (
    0 => 'directoryiterator.islink.php',
    1 => 'DirectoryIterator::isLink',
  ),
  20 => 
  array (
    0 => 'directoryiterator.isreadable.php',
    1 => 'DirectoryIterator::isReadable',
  ),
  21 => 
  array (
    0 => 'directoryiterator.iswritable.php',
    1 => 'DirectoryIterator::isWritable',
  ),
  22 => 
  array (
    0 => 'directoryiterator.key.php',
    1 => 'DirectoryIterator::key',
  ),
  23 => 
  array (
    0 => 'directoryiterator.next.php',
    1 => 'DirectoryIterator::next',
  ),
  24 => 
  array (
    0 => 'directoryiterator.rewind.php',
    1 => 'DirectoryIterator::rewind',
  ),
  25 => 
  array (
    0 => 'directoryiterator.seek.php',
    1 => 'DirectoryIterator::seek',
  ),
  26 => 
  array (
    0 => 'directoryiterator.tostring.php',
    1 => 'DirectoryIterator::__toString',
  ),
  27 => 
  array (
    0 => 'directoryiterator.valid.php',
    1 => 'DirectoryIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);