<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairosvgsurface.construct.php',
    1 => 'CairoSvgSurface::__construct',
  ),
  1 => 
  array (
    0 => 'cairosvgsurface.getversions.php',
    1 => 'CairoSvgSurface::getVersions',
  ),
  2 => 
  array (
    0 => 'cairosvgsurface.restricttoversion.php',
    1 => 'CairoSvgSurface::restrictToVersion',
  ),
  3 => 
  array (
    0 => 'cairosvgsurface.versiontostring.php',
    1 => 'CairoSvgSurface::versionToString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);