<?php
$TOC = array (
  0 => 
  array (
    0 => 'solrresponse.getdigestedresponse.php',
    1 => 'SolrResponse::getDigestedResponse',
  ),
  1 => 
  array (
    0 => 'solrresponse.gethttpstatus.php',
    1 => 'SolrResponse::getHttpStatus',
  ),
  2 => 
  array (
    0 => 'solrresponse.gethttpstatusmessage.php',
    1 => 'SolrResponse::getHttpStatusMessage',
  ),
  3 => 
  array (
    0 => 'solrresponse.getrawrequest.php',
    1 => 'SolrResponse::getRawRequest',
  ),
  4 => 
  array (
    0 => 'solrresponse.getrawrequestheaders.php',
    1 => 'SolrResponse::getRawRequestHeaders',
  ),
  5 => 
  array (
    0 => 'solrresponse.getrawresponse.php',
    1 => 'SolrResponse::getRawResponse',
  ),
  6 => 
  array (
    0 => 'solrresponse.getrawresponseheaders.php',
    1 => 'SolrResponse::getRawResponseHeaders',
  ),
  7 => 
  array (
    0 => 'solrresponse.getrequesturl.php',
    1 => 'SolrResponse::getRequestUrl',
  ),
  8 => 
  array (
    0 => 'solrresponse.getresponse.php',
    1 => 'SolrResponse::getResponse',
  ),
  9 => 
  array (
    0 => 'solrresponse.setparsemode.php',
    1 => 'SolrResponse::setParseMode',
  ),
  10 => 
  array (
    0 => 'solrresponse.success.php',
    1 => 'SolrResponse::success',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.solr.php',
    1 => 'Solr',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);