<?php
$TOC = array (
  0 => 
  array (
    0 => 'domxpath.construct.php',
    1 => 'DOMXPath::__construct',
  ),
  1 => 
  array (
    0 => 'domxpath.evaluate.php',
    1 => 'DOMXPath::evaluate',
  ),
  2 => 
  array (
    0 => 'domxpath.query.php',
    1 => 'DOMXPath::query',
  ),
  3 => 
  array (
    0 => 'domxpath.registernamespace.php',
    1 => 'DOMXPath::registerNamespace',
  ),
  4 => 
  array (
    0 => 'domxpath.registerphpfunctions.php',
    1 => 'DOMXPath::registerPhpFunctions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dom.php',
    1 => 'DOM',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);