<?php
$TOC = array (
  0 => 
  array (
    0 => 'resourcebundle.count.php',
    1 => 'ResourceBundle::count',
  ),
  1 => 
  array (
    0 => 'resourcebundle.create.php',
    1 => 'ResourceBundle::create',
  ),
  2 => 
  array (
    0 => 'resourcebundle.geterrorcode.php',
    1 => 'ResourceBundle::getErrorCode',
  ),
  3 => 
  array (
    0 => 'resourcebundle.geterrormessage.php',
    1 => 'ResourceBundle::getErrorMessage',
  ),
  4 => 
  array (
    0 => 'resourcebundle.get.php',
    1 => 'ResourceBundle::get',
  ),
  5 => 
  array (
    0 => 'resourcebundle.locales.php',
    1 => 'ResourceBundle::getLocales',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.intl.php',
    1 => 'intl',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);