<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swfbitmap.construct.php',
    1 => 'SWFBitmap-&gt;__construct',
  ),
  1 => 
  array (
    0 => 'function.swfbitmap.getheight.php',
    1 => 'SWFBitmap-&gt;getHeight',
  ),
  2 => 
  array (
    0 => 'function.swfbitmap.getwidth.php',
    1 => 'SWFBitmap-&gt;getWidth',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);