<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swfvideostream.construct.php',
    1 => 'SWFVideoStream-&gt;__construct',
  ),
  1 => 
  array (
    0 => 'function.swfvideostream.getnumframes.php',
    1 => 'SWFVideoStream-&gt;getNumFrames',
  ),
  2 => 
  array (
    0 => 'function.swfvideostream.setdimension.php',
    1 => 'SWFVideoStream-&gt;setDimension',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);