<?php
$TOC = array (
  0 => 
  array (
    0 => 'exception.construct.php',
    1 => 'Exception::__construct',
  ),
  1 => 
  array (
    0 => 'exception.getmessage.php',
    1 => 'Exception::getMessage',
  ),
  2 => 
  array (
    0 => 'exception.getprevious.php',
    1 => 'Exception::getPrevious',
  ),
  3 => 
  array (
    0 => 'exception.getcode.php',
    1 => 'Exception::getCode',
  ),
  4 => 
  array (
    0 => 'exception.getfile.php',
    1 => 'Exception::getFile',
  ),
  5 => 
  array (
    0 => 'exception.getline.php',
    1 => 'Exception::getLine',
  ),
  6 => 
  array (
    0 => 'exception.gettrace.php',
    1 => 'Exception::getTrace',
  ),
  7 => 
  array (
    0 => 'exception.gettraceasstring.php',
    1 => 'Exception::getTraceAsString',
  ),
  8 => 
  array (
    0 => 'exception.tostring.php',
    1 => 'Exception::__toString',
  ),
  9 => 
  array (
    0 => 'exception.clone.php',
    1 => 'Exception::__clone',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'reserved.exceptions.php',
    1 => 'Predefined Exceptions',
  ),
  1 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);