<?php
$TOC = array (
  0 => 
  array (
    0 => 'filesystemiterator.construct.php',
    1 => 'FilesystemIterator::__construct',
  ),
  1 => 
  array (
    0 => 'filesystemiterator.current.php',
    1 => 'FilesystemIterator::current',
  ),
  2 => 
  array (
    0 => 'filesystemiterator.getflags.php',
    1 => 'FilesystemIterator::getFlags',
  ),
  3 => 
  array (
    0 => 'filesystemiterator.key.php',
    1 => 'FilesystemIterator::key',
  ),
  4 => 
  array (
    0 => 'filesystemiterator.next.php',
    1 => 'FilesystemIterator::next',
  ),
  5 => 
  array (
    0 => 'filesystemiterator.rewind.php',
    1 => 'FilesystemIterator::rewind',
  ),
  6 => 
  array (
    0 => 'filesystemiterator.setflags.php',
    1 => 'FilesystemIterator::setFlags',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);