<?php
$TOC = array (
  0 => 
  array (
    0 => 'mongo.close.php',
    1 => 'Mongo::close',
  ),
  1 => 
  array (
    0 => 'mongo.connect.php',
    1 => 'Mongo::connect',
  ),
  2 => 
  array (
    0 => 'mongo.connectutil.php',
    1 => 'Mongo::connectUtil',
  ),
  3 => 
  array (
    0 => 'mongo.construct.php',
    1 => 'Mongo::__construct',
  ),
  4 => 
  array (
    0 => 'mongo.dropdb.php',
    1 => 'Mongo::dropDB',
  ),
  5 => 
  array (
    0 => 'mongo.get.php',
    1 => 'Mongo::__get',
  ),
  6 => 
  array (
    0 => 'mongo.getHosts.php',
    1 => 'Mongo::getHosts',
  ),
  7 => 
  array (
    0 => 'mongo.getslave.php',
    1 => 'Mongo::getSlave',
  ),
  8 => 
  array (
    0 => 'mongo.getslaveokay.php',
    1 => 'Mongo::getSlaveOkay',
  ),
  9 => 
  array (
    0 => 'mongo.listdbs.php',
    1 => 'Mongo::listDBs',
  ),
  10 => 
  array (
    0 => 'mongo.selectcollection.php',
    1 => 'Mongo::selectCollection',
  ),
  11 => 
  array (
    0 => 'mongo.selectdb.php',
    1 => 'Mongo::selectDB',
  ),
  12 => 
  array (
    0 => 'mongo.setslaveokay.php',
    1 => 'Mongo::setSlaveOkay',
  ),
  13 => 
  array (
    0 => 'mongo.switchslave.php',
    1 => 'Mongo::switchSlave',
  ),
  14 => 
  array (
    0 => 'mongo.tostring.php',
    1 => 'Mongo::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'mongo.core.php',
    1 => 'Core Classes',
  ),
  1 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  2 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  3 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  4 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  5 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);