<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swfmorph.construct.php',
    1 => 'SWFMorph-&gt;__construct',
  ),
  1 => 
  array (
    0 => 'function.swfmorph.getshape1.php',
    1 => 'SWFMorph-&gt;getShape1',
  ),
  2 => 
  array (
    0 => 'function.swfmorph.getshape2.php',
    1 => 'SWFMorph-&gt;getShape2',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);