<?php
$TOC = array (
  0 => 
  array (
    0 => 'memcached.add.php',
    1 => 'Memcached::add',
  ),
  1 => 
  array (
    0 => 'memcached.addbykey.php',
    1 => 'Memcached::addByKey',
  ),
  2 => 
  array (
    0 => 'memcached.addserver.php',
    1 => 'Memcached::addServer',
  ),
  3 => 
  array (
    0 => 'memcached.addservers.php',
    1 => 'Memcached::addServers',
  ),
  4 => 
  array (
    0 => 'memcached.append.php',
    1 => 'Memcached::append',
  ),
  5 => 
  array (
    0 => 'memcached.appendbykey.php',
    1 => 'Memcached::appendByKey',
  ),
  6 => 
  array (
    0 => 'memcached.cas.php',
    1 => 'Memcached::cas',
  ),
  7 => 
  array (
    0 => 'memcached.casbykey.php',
    1 => 'Memcached::casByKey',
  ),
  8 => 
  array (
    0 => 'memcached.construct.php',
    1 => 'Memcached::__construct',
  ),
  9 => 
  array (
    0 => 'memcached.decrement.php',
    1 => 'Memcached::decrement',
  ),
  10 => 
  array (
    0 => 'memcached.delete.php',
    1 => 'Memcached::delete',
  ),
  11 => 
  array (
    0 => 'memcached.deletebykey.php',
    1 => 'Memcached::deleteByKey',
  ),
  12 => 
  array (
    0 => 'memcached.fetch.php',
    1 => 'Memcached::fetch',
  ),
  13 => 
  array (
    0 => 'memcached.fetchall.php',
    1 => 'Memcached::fetchAll',
  ),
  14 => 
  array (
    0 => 'memcached.flush.php',
    1 => 'Memcached::flush',
  ),
  15 => 
  array (
    0 => 'memcached.get.php',
    1 => 'Memcached::get',
  ),
  16 => 
  array (
    0 => 'memcached.getbykey.php',
    1 => 'Memcached::getByKey',
  ),
  17 => 
  array (
    0 => 'memcached.getdelayed.php',
    1 => 'Memcached::getDelayed',
  ),
  18 => 
  array (
    0 => 'memcached.getdelayedbykey.php',
    1 => 'Memcached::getDelayedByKey',
  ),
  19 => 
  array (
    0 => 'memcached.getmulti.php',
    1 => 'Memcached::getMulti',
  ),
  20 => 
  array (
    0 => 'memcached.getmultibykey.php',
    1 => 'Memcached::getMultiByKey',
  ),
  21 => 
  array (
    0 => 'memcached.getoption.php',
    1 => 'Memcached::getOption',
  ),
  22 => 
  array (
    0 => 'memcached.getresultcode.php',
    1 => 'Memcached::getResultCode',
  ),
  23 => 
  array (
    0 => 'memcached.getresultmessage.php',
    1 => 'Memcached::getResultMessage',
  ),
  24 => 
  array (
    0 => 'memcached.getserverbykey.php',
    1 => 'Memcached::getServerByKey',
  ),
  25 => 
  array (
    0 => 'memcached.getserverlist.php',
    1 => 'Memcached::getServerList',
  ),
  26 => 
  array (
    0 => 'memcached.getstats.php',
    1 => 'Memcached::getStats',
  ),
  27 => 
  array (
    0 => 'memcached.getversion.php',
    1 => 'Memcached::getVersion',
  ),
  28 => 
  array (
    0 => 'memcached.increment.php',
    1 => 'Memcached::increment',
  ),
  29 => 
  array (
    0 => 'memcached.prepend.php',
    1 => 'Memcached::prepend',
  ),
  30 => 
  array (
    0 => 'memcached.prependbykey.php',
    1 => 'Memcached::prependByKey',
  ),
  31 => 
  array (
    0 => 'memcached.replace.php',
    1 => 'Memcached::replace',
  ),
  32 => 
  array (
    0 => 'memcached.replacebykey.php',
    1 => 'Memcached::replaceByKey',
  ),
  33 => 
  array (
    0 => 'memcached.set.php',
    1 => 'Memcached::set',
  ),
  34 => 
  array (
    0 => 'memcached.setbykey.php',
    1 => 'Memcached::setByKey',
  ),
  35 => 
  array (
    0 => 'memcached.setmulti.php',
    1 => 'Memcached::setMulti',
  ),
  36 => 
  array (
    0 => 'memcached.setmultibykey.php',
    1 => 'Memcached::setMultiByKey',
  ),
  37 => 
  array (
    0 => 'memcached.setoption.php',
    1 => 'Memcached::setOption',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.memcached.php',
    1 => 'Memcached',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);