<?php
$TOC = array (
  0 => 
  array (
    0 => 'sqlite3stmt.bindparam.php',
    1 => 'SQLite3Stmt::bindParam',
  ),
  1 => 
  array (
    0 => 'sqlite3stmt.bindvalue.php',
    1 => 'SQLite3Stmt::bindValue',
  ),
  2 => 
  array (
    0 => 'sqlite3stmt.clear.php',
    1 => 'SQLite3Stmt::clear',
  ),
  3 => 
  array (
    0 => 'sqlite3stmt.close.php',
    1 => 'SQLite3Stmt::close',
  ),
  4 => 
  array (
    0 => 'sqlite3stmt.execute.php',
    1 => 'SQLite3Stmt::execute',
  ),
  5 => 
  array (
    0 => 'sqlite3stmt.paramcount.php',
    1 => 'SQLite3Stmt::paramCount',
  ),
  6 => 
  array (
    0 => 'sqlite3stmt.reset.php',
    1 => 'SQLite3Stmt::reset',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sqlite3.php',
    1 => 'SQLite3',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);