<?php
$TOC = array (
  0 => 
  array (
    0 => 'amqpconnection.connect.php',
    1 => 'AMQPConnection::connect',
  ),
  1 => 
  array (
    0 => 'amqpconnection.construct.php',
    1 => 'AMQPConnection::__construct',
  ),
  2 => 
  array (
    0 => 'amqpconnection.disconnect.php',
    1 => 'AMQPConnection::disconnect',
  ),
  3 => 
  array (
    0 => 'amqpconnection.isconnected.php',
    1 => 'AMQPConnection::isConnected',
  ),
  4 => 
  array (
    0 => 'amqpconnection.reconnect.php',
    1 => 'AMQPConnection::reconnect',
  ),
  5 => 
  array (
    0 => 'amqpconnection.sethost.php',
    1 => 'AMQPConnection::setHost',
  ),
  6 => 
  array (
    0 => 'amqpconnection.setlogin.php',
    1 => 'AMQPConnection::setLogin',
  ),
  7 => 
  array (
    0 => 'amqpconnection.setpassword.php',
    1 => 'AMQPConnection::setPassword',
  ),
  8 => 
  array (
    0 => 'amqpconnection.setport.php',
    1 => 'AMQPConnection::setPort',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.amqp.php',
    1 => 'AMQP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);