<?php
$TOC = array (
  0 => 
  array (
    0 => 'splfileobject.construct.php',
    1 => 'SplFileObject::__construct',
  ),
  1 => 
  array (
    0 => 'splfileobject.current.php',
    1 => 'SplFileObject::current',
  ),
  2 => 
  array (
    0 => 'splfileobject.eof.php',
    1 => 'SplFileObject::eof',
  ),
  3 => 
  array (
    0 => 'splfileobject.fflush.php',
    1 => 'SplFileObject::fflush',
  ),
  4 => 
  array (
    0 => 'splfileobject.fgetc.php',
    1 => 'SplFileObject::fgetc',
  ),
  5 => 
  array (
    0 => 'splfileobject.fgetcsv.php',
    1 => 'SplFileObject::fgetcsv',
  ),
  6 => 
  array (
    0 => 'splfileobject.fgets.php',
    1 => 'SplFileObject::fgets',
  ),
  7 => 
  array (
    0 => 'splfileobject.fgetss.php',
    1 => 'SplFileObject::fgetss',
  ),
  8 => 
  array (
    0 => 'splfileobject.flock.php',
    1 => 'SplFileObject::flock',
  ),
  9 => 
  array (
    0 => 'splfileobject.fpassthru.php',
    1 => 'SplFileObject::fpassthru',
  ),
  10 => 
  array (
    0 => 'splfileobject.fscanf.php',
    1 => 'SplFileObject::fscanf',
  ),
  11 => 
  array (
    0 => 'splfileobject.fseek.php',
    1 => 'SplFileObject::fseek',
  ),
  12 => 
  array (
    0 => 'splfileobject.fstat.php',
    1 => 'SplFileObject::fstat',
  ),
  13 => 
  array (
    0 => 'splfileobject.ftell.php',
    1 => 'SplFileObject::ftell',
  ),
  14 => 
  array (
    0 => 'splfileobject.ftruncate.php',
    1 => 'SplFileObject::ftruncate',
  ),
  15 => 
  array (
    0 => 'splfileobject.fwrite.php',
    1 => 'SplFileObject::fwrite',
  ),
  16 => 
  array (
    0 => 'splfileobject.getchildren.php',
    1 => 'SplFileObject::getChildren',
  ),
  17 => 
  array (
    0 => 'splfileobject.getcsvcontrol.php',
    1 => 'SplFileObject::getCsvControl',
  ),
  18 => 
  array (
    0 => 'splfileobject.getcurrentline.php',
    1 => 'SplFileObject::getCurrentLine',
  ),
  19 => 
  array (
    0 => 'splfileobject.getflags.php',
    1 => 'SplFileObject::getFlags',
  ),
  20 => 
  array (
    0 => 'splfileobject.getmaxlinelen.php',
    1 => 'SplFileObject::getMaxLineLen',
  ),
  21 => 
  array (
    0 => 'splfileobject.haschildren.php',
    1 => 'SplFileObject::hasChildren',
  ),
  22 => 
  array (
    0 => 'splfileobject.key.php',
    1 => 'SplFileObject::key',
  ),
  23 => 
  array (
    0 => 'splfileobject.next.php',
    1 => 'SplFileObject::next',
  ),
  24 => 
  array (
    0 => 'splfileobject.rewind.php',
    1 => 'SplFileObject::rewind',
  ),
  25 => 
  array (
    0 => 'splfileobject.seek.php',
    1 => 'SplFileObject::seek',
  ),
  26 => 
  array (
    0 => 'splfileobject.setcsvcontrol.php',
    1 => 'SplFileObject::setCsvControl',
  ),
  27 => 
  array (
    0 => 'splfileobject.setflags.php',
    1 => 'SplFileObject::setFlags',
  ),
  28 => 
  array (
    0 => 'splfileobject.setmaxlinelen.php',
    1 => 'SplFileObject::setMaxLineLen',
  ),
  29 => 
  array (
    0 => 'splfileobject.tostring.php',
    1 => 'SplFileObject::__toString',
  ),
  30 => 
  array (
    0 => 'splfileobject.valid.php',
    1 => 'SplFileObject::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.files.php',
    1 => 'File Handling',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);