<?php
$TOC = array (
  0 => 
  array (
    0 => 'cairogradientpattern.addcolorstoprgb.php',
    1 => 'CairoGradientPattern::addColorStopRgb',
  ),
  1 => 
  array (
    0 => 'cairogradientpattern.addcolorstoprgba.php',
    1 => 'CairoGradientPattern::addColorStopRgba',
  ),
  2 => 
  array (
    0 => 'cairogradientpattern.getcolorstopcount.php',
    1 => 'CairoGradientPattern::getColorStopCount',
  ),
  3 => 
  array (
    0 => 'cairogradientpattern.getcolorstoprgba.php',
    1 => 'CairoGradientPattern::getColorStopRgba',
  ),
  4 => 
  array (
    0 => 'cairogradientpattern.getextend.php',
    1 => 'CairoGradientPattern::getExtend',
  ),
  5 => 
  array (
    0 => 'cairogradientpattern.setextend.php',
    1 => 'CairoGradientPattern::setExtend',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);