<?php
$TOC = array (
  0 => 
  array (
    0 => 'solrquery.addfacetdatefield.php',
    1 => 'SolrQuery::addFacetDateField',
  ),
  1 => 
  array (
    0 => 'solrquery.addfacetdateother.php',
    1 => 'SolrQuery::addFacetDateOther',
  ),
  2 => 
  array (
    0 => 'solrquery.addfacetfield.php',
    1 => 'SolrQuery::addFacetField',
  ),
  3 => 
  array (
    0 => 'solrquery.addfacetquery.php',
    1 => 'SolrQuery::addFacetQuery',
  ),
  4 => 
  array (
    0 => 'solrquery.addfield.php',
    1 => 'SolrQuery::addField',
  ),
  5 => 
  array (
    0 => 'solrquery.addfilterquery.php',
    1 => 'SolrQuery::addFilterQuery',
  ),
  6 => 
  array (
    0 => 'solrquery.addhighlightfield.php',
    1 => 'SolrQuery::addHighlightField',
  ),
  7 => 
  array (
    0 => 'solrquery.addmltfield.php',
    1 => 'SolrQuery::addMltField',
  ),
  8 => 
  array (
    0 => 'solrquery.addmltqueryfield.php',
    1 => 'SolrQuery::addMltQueryField',
  ),
  9 => 
  array (
    0 => 'solrquery.addsortfield.php',
    1 => 'SolrQuery::addSortField',
  ),
  10 => 
  array (
    0 => 'solrquery.addstatsfacet.php',
    1 => 'SolrQuery::addStatsFacet',
  ),
  11 => 
  array (
    0 => 'solrquery.addstatsfield.php',
    1 => 'SolrQuery::addStatsField',
  ),
  12 => 
  array (
    0 => 'solrquery.construct.php',
    1 => 'SolrQuery::__construct',
  ),
  13 => 
  array (
    0 => 'solrquery.destruct.php',
    1 => 'SolrQuery::__destruct',
  ),
  14 => 
  array (
    0 => 'solrquery.getfacet.php',
    1 => 'SolrQuery::getFacet',
  ),
  15 => 
  array (
    0 => 'solrquery.getfacetdateend.php',
    1 => 'SolrQuery::getFacetDateEnd',
  ),
  16 => 
  array (
    0 => 'solrquery.getfacetdatefields.php',
    1 => 'SolrQuery::getFacetDateFields',
  ),
  17 => 
  array (
    0 => 'solrquery.getfacetdategap.php',
    1 => 'SolrQuery::getFacetDateGap',
  ),
  18 => 
  array (
    0 => 'solrquery.getfacetdatehardend.php',
    1 => 'SolrQuery::getFacetDateHardEnd',
  ),
  19 => 
  array (
    0 => 'solrquery.getfacetdateother.php',
    1 => 'SolrQuery::getFacetDateOther',
  ),
  20 => 
  array (
    0 => 'solrquery.getfacetdatestart.php',
    1 => 'SolrQuery::getFacetDateStart',
  ),
  21 => 
  array (
    0 => 'solrquery.getfacetfields.php',
    1 => 'SolrQuery::getFacetFields',
  ),
  22 => 
  array (
    0 => 'solrquery.getfacetlimit.php',
    1 => 'SolrQuery::getFacetLimit',
  ),
  23 => 
  array (
    0 => 'solrquery.getfacetmethod.php',
    1 => 'SolrQuery::getFacetMethod',
  ),
  24 => 
  array (
    0 => 'solrquery.getfacetmincount.php',
    1 => 'SolrQuery::getFacetMinCount',
  ),
  25 => 
  array (
    0 => 'solrquery.getfacetmissing.php',
    1 => 'SolrQuery::getFacetMissing',
  ),
  26 => 
  array (
    0 => 'solrquery.getfacetoffset.php',
    1 => 'SolrQuery::getFacetOffset',
  ),
  27 => 
  array (
    0 => 'solrquery.getfacetprefix.php',
    1 => 'SolrQuery::getFacetPrefix',
  ),
  28 => 
  array (
    0 => 'solrquery.getfacetqueries.php',
    1 => 'SolrQuery::getFacetQueries',
  ),
  29 => 
  array (
    0 => 'solrquery.getfacetsort.php',
    1 => 'SolrQuery::getFacetSort',
  ),
  30 => 
  array (
    0 => 'solrquery.getfields.php',
    1 => 'SolrQuery::getFields',
  ),
  31 => 
  array (
    0 => 'solrquery.getfilterqueries.php',
    1 => 'SolrQuery::getFilterQueries',
  ),
  32 => 
  array (
    0 => 'solrquery.gethighlight.php',
    1 => 'SolrQuery::getHighlight',
  ),
  33 => 
  array (
    0 => 'solrquery.gethighlightalternatefield.php',
    1 => 'SolrQuery::getHighlightAlternateField',
  ),
  34 => 
  array (
    0 => 'solrquery.gethighlightfields.php',
    1 => 'SolrQuery::getHighlightFields',
  ),
  35 => 
  array (
    0 => 'solrquery.gethighlightformatter.php',
    1 => 'SolrQuery::getHighlightFormatter',
  ),
  36 => 
  array (
    0 => 'solrquery.gethighlightfragmenter.php',
    1 => 'SolrQuery::getHighlightFragmenter',
  ),
  37 => 
  array (
    0 => 'solrquery.gethighlightfragsize.php',
    1 => 'SolrQuery::getHighlightFragsize',
  ),
  38 => 
  array (
    0 => 'solrquery.gethighlighthighlightmultiterm.php',
    1 => 'SolrQuery::getHighlightHighlightMultiTerm',
  ),
  39 => 
  array (
    0 => 'solrquery.gethighlightmaxalternatefieldlength.php',
    1 => 'SolrQuery::getHighlightMaxAlternateFieldLength',
  ),
  40 => 
  array (
    0 => 'solrquery.gethighlightmaxanalyzedchars.php',
    1 => 'SolrQuery::getHighlightMaxAnalyzedChars',
  ),
  41 => 
  array (
    0 => 'solrquery.gethighlightmergecontiguous.php',
    1 => 'SolrQuery::getHighlightMergeContiguous',
  ),
  42 => 
  array (
    0 => 'solrquery.gethighlightregexmaxanalyzedchars.php',
    1 => 'SolrQuery::getHighlightRegexMaxAnalyzedChars',
  ),
  43 => 
  array (
    0 => 'solrquery.gethighlightregexpattern.php',
    1 => 'SolrQuery::getHighlightRegexPattern',
  ),
  44 => 
  array (
    0 => 'solrquery.gethighlightregexslop.php',
    1 => 'SolrQuery::getHighlightRegexSlop',
  ),
  45 => 
  array (
    0 => 'solrquery.gethighlightrequirefieldmatch.php',
    1 => 'SolrQuery::getHighlightRequireFieldMatch',
  ),
  46 => 
  array (
    0 => 'solrquery.gethighlightsimplepost.php',
    1 => 'SolrQuery::getHighlightSimplePost',
  ),
  47 => 
  array (
    0 => 'solrquery.gethighlightsimplepre.php',
    1 => 'SolrQuery::getHighlightSimplePre',
  ),
  48 => 
  array (
    0 => 'solrquery.gethighlightsnippets.php',
    1 => 'SolrQuery::getHighlightSnippets',
  ),
  49 => 
  array (
    0 => 'solrquery.gethighlightusephrasehighlighter.php',
    1 => 'SolrQuery::getHighlightUsePhraseHighlighter',
  ),
  50 => 
  array (
    0 => 'solrquery.getmlt.php',
    1 => 'SolrQuery::getMlt',
  ),
  51 => 
  array (
    0 => 'solrquery.getmltboost.php',
    1 => 'SolrQuery::getMltBoost',
  ),
  52 => 
  array (
    0 => 'solrquery.getmltcount.php',
    1 => 'SolrQuery::getMltCount',
  ),
  53 => 
  array (
    0 => 'solrquery.getmltfields.php',
    1 => 'SolrQuery::getMltFields',
  ),
  54 => 
  array (
    0 => 'solrquery.getmltmaxnumqueryterms.php',
    1 => 'SolrQuery::getMltMaxNumQueryTerms',
  ),
  55 => 
  array (
    0 => 'solrquery.getmltmaxnumtokens.php',
    1 => 'SolrQuery::getMltMaxNumTokens',
  ),
  56 => 
  array (
    0 => 'solrquery.getmltmaxwordlength.php',
    1 => 'SolrQuery::getMltMaxWordLength',
  ),
  57 => 
  array (
    0 => 'solrquery.getmltmindocfrequency.php',
    1 => 'SolrQuery::getMltMinDocFrequency',
  ),
  58 => 
  array (
    0 => 'solrquery.getmltmintermfrequency.php',
    1 => 'SolrQuery::getMltMinTermFrequency',
  ),
  59 => 
  array (
    0 => 'solrquery.getmltminwordlength.php',
    1 => 'SolrQuery::getMltMinWordLength',
  ),
  60 => 
  array (
    0 => 'solrquery.getmltqueryfields.php',
    1 => 'SolrQuery::getMltQueryFields',
  ),
  61 => 
  array (
    0 => 'solrquery.getquery.php',
    1 => 'SolrQuery::getQuery',
  ),
  62 => 
  array (
    0 => 'solrquery.getrows.php',
    1 => 'SolrQuery::getRows',
  ),
  63 => 
  array (
    0 => 'solrquery.getsortfields.php',
    1 => 'SolrQuery::getSortFields',
  ),
  64 => 
  array (
    0 => 'solrquery.getstart.php',
    1 => 'SolrQuery::getStart',
  ),
  65 => 
  array (
    0 => 'solrquery.getstats.php',
    1 => 'SolrQuery::getStats',
  ),
  66 => 
  array (
    0 => 'solrquery.getstatsfacets.php',
    1 => 'SolrQuery::getStatsFacets',
  ),
  67 => 
  array (
    0 => 'solrquery.getstatsfields.php',
    1 => 'SolrQuery::getStatsFields',
  ),
  68 => 
  array (
    0 => 'solrquery.getterms.php',
    1 => 'SolrQuery::getTerms',
  ),
  69 => 
  array (
    0 => 'solrquery.gettermsfield.php',
    1 => 'SolrQuery::getTermsField',
  ),
  70 => 
  array (
    0 => 'solrquery.gettermsincludelowerbound.php',
    1 => 'SolrQuery::getTermsIncludeLowerBound',
  ),
  71 => 
  array (
    0 => 'solrquery.gettermsincludeupperbound.php',
    1 => 'SolrQuery::getTermsIncludeUpperBound',
  ),
  72 => 
  array (
    0 => 'solrquery.gettermslimit.php',
    1 => 'SolrQuery::getTermsLimit',
  ),
  73 => 
  array (
    0 => 'solrquery.gettermslowerbound.php',
    1 => 'SolrQuery::getTermsLowerBound',
  ),
  74 => 
  array (
    0 => 'solrquery.gettermsmaxcount.php',
    1 => 'SolrQuery::getTermsMaxCount',
  ),
  75 => 
  array (
    0 => 'solrquery.gettermsmincount.php',
    1 => 'SolrQuery::getTermsMinCount',
  ),
  76 => 
  array (
    0 => 'solrquery.gettermsprefix.php',
    1 => 'SolrQuery::getTermsPrefix',
  ),
  77 => 
  array (
    0 => 'solrquery.gettermsreturnraw.php',
    1 => 'SolrQuery::getTermsReturnRaw',
  ),
  78 => 
  array (
    0 => 'solrquery.gettermssort.php',
    1 => 'SolrQuery::getTermsSort',
  ),
  79 => 
  array (
    0 => 'solrquery.gettermsupperbound.php',
    1 => 'SolrQuery::getTermsUpperBound',
  ),
  80 => 
  array (
    0 => 'solrquery.gettimeallowed.php',
    1 => 'SolrQuery::getTimeAllowed',
  ),
  81 => 
  array (
    0 => 'solrquery.removefacetdatefield.php',
    1 => 'SolrQuery::removeFacetDateField',
  ),
  82 => 
  array (
    0 => 'solrquery.removefacetdateother.php',
    1 => 'SolrQuery::removeFacetDateOther',
  ),
  83 => 
  array (
    0 => 'solrquery.removefacetfield.php',
    1 => 'SolrQuery::removeFacetField',
  ),
  84 => 
  array (
    0 => 'solrquery.removefacetquery.php',
    1 => 'SolrQuery::removeFacetQuery',
  ),
  85 => 
  array (
    0 => 'solrquery.removefield.php',
    1 => 'SolrQuery::removeField',
  ),
  86 => 
  array (
    0 => 'solrquery.removefilterquery.php',
    1 => 'SolrQuery::removeFilterQuery',
  ),
  87 => 
  array (
    0 => 'solrquery.removehighlightfield.php',
    1 => 'SolrQuery::removeHighlightField',
  ),
  88 => 
  array (
    0 => 'solrquery.removemltfield.php',
    1 => 'SolrQuery::removeMltField',
  ),
  89 => 
  array (
    0 => 'solrquery.removemltqueryfield.php',
    1 => 'SolrQuery::removeMltQueryField',
  ),
  90 => 
  array (
    0 => 'solrquery.removesortfield.php',
    1 => 'SolrQuery::removeSortField',
  ),
  91 => 
  array (
    0 => 'solrquery.removestatsfacet.php',
    1 => 'SolrQuery::removeStatsFacet',
  ),
  92 => 
  array (
    0 => 'solrquery.removestatsfield.php',
    1 => 'SolrQuery::removeStatsField',
  ),
  93 => 
  array (
    0 => 'solrquery.setechohandler.php',
    1 => 'SolrQuery::setEchoHandler',
  ),
  94 => 
  array (
    0 => 'solrquery.setechoparams.php',
    1 => 'SolrQuery::setEchoParams',
  ),
  95 => 
  array (
    0 => 'solrquery.setexplainother.php',
    1 => 'SolrQuery::setExplainOther',
  ),
  96 => 
  array (
    0 => 'solrquery.setfacet.php',
    1 => 'SolrQuery::setFacet',
  ),
  97 => 
  array (
    0 => 'solrquery.setfacetdateend.php',
    1 => 'SolrQuery::setFacetDateEnd',
  ),
  98 => 
  array (
    0 => 'solrquery.setfacetdategap.php',
    1 => 'SolrQuery::setFacetDateGap',
  ),
  99 => 
  array (
    0 => 'solrquery.setfacetdatehardend.php',
    1 => 'SolrQuery::setFacetDateHardEnd',
  ),
  100 => 
  array (
    0 => 'solrquery.setfacetdatestart.php',
    1 => 'SolrQuery::setFacetDateStart',
  ),
  101 => 
  array (
    0 => 'solrquery.setfacetenumcachemindefaultfrequency.php',
    1 => 'SolrQuery::setFacetEnumCacheMinDefaultFrequency',
  ),
  102 => 
  array (
    0 => 'solrquery.setfacetlimit.php',
    1 => 'SolrQuery::setFacetLimit',
  ),
  103 => 
  array (
    0 => 'solrquery.setfacetmethod.php',
    1 => 'SolrQuery::setFacetMethod',
  ),
  104 => 
  array (
    0 => 'solrquery.setfacetmincount.php',
    1 => 'SolrQuery::setFacetMinCount',
  ),
  105 => 
  array (
    0 => 'solrquery.setfacetmissing.php',
    1 => 'SolrQuery::setFacetMissing',
  ),
  106 => 
  array (
    0 => 'solrquery.setfacetoffset.php',
    1 => 'SolrQuery::setFacetOffset',
  ),
  107 => 
  array (
    0 => 'solrquery.setfacetprefix.php',
    1 => 'SolrQuery::setFacetPrefix',
  ),
  108 => 
  array (
    0 => 'solrquery.setfacetsort.php',
    1 => 'SolrQuery::setFacetSort',
  ),
  109 => 
  array (
    0 => 'solrquery.sethighlight.php',
    1 => 'SolrQuery::setHighlight',
  ),
  110 => 
  array (
    0 => 'solrquery.sethighlightalternatefield.php',
    1 => 'SolrQuery::setHighlightAlternateField',
  ),
  111 => 
  array (
    0 => 'solrquery.sethighlightformatter.php',
    1 => 'SolrQuery::setHighlightFormatter',
  ),
  112 => 
  array (
    0 => 'solrquery.sethighlightfragmenter.php',
    1 => 'SolrQuery::setHighlightFragmenter',
  ),
  113 => 
  array (
    0 => 'solrquery.sethighlightfragsize.php',
    1 => 'SolrQuery::setHighlightFragsize',
  ),
  114 => 
  array (
    0 => 'solrquery.sethighlighthighlightmultiterm.php',
    1 => 'SolrQuery::setHighlightHighlightMultiTerm',
  ),
  115 => 
  array (
    0 => 'solrquery.sethighlightmaxalternatefieldlength.php',
    1 => 'SolrQuery::setHighlightMaxAlternateFieldLength',
  ),
  116 => 
  array (
    0 => 'solrquery.sethighlightmaxanalyzedchars.php',
    1 => 'SolrQuery::setHighlightMaxAnalyzedChars',
  ),
  117 => 
  array (
    0 => 'solrquery.sethighlightmergecontiguous.php',
    1 => 'SolrQuery::setHighlightMergeContiguous',
  ),
  118 => 
  array (
    0 => 'solrquery.sethighlightregexmaxanalyzedchars.php',
    1 => 'SolrQuery::setHighlightRegexMaxAnalyzedChars',
  ),
  119 => 
  array (
    0 => 'solrquery.sethighlightregexpattern.php',
    1 => 'SolrQuery::setHighlightRegexPattern',
  ),
  120 => 
  array (
    0 => 'solrquery.sethighlightregexslop.php',
    1 => 'SolrQuery::setHighlightRegexSlop',
  ),
  121 => 
  array (
    0 => 'solrquery.sethighlightrequirefieldmatch.php',
    1 => 'SolrQuery::setHighlightRequireFieldMatch',
  ),
  122 => 
  array (
    0 => 'solrquery.sethighlightsimplepost.php',
    1 => 'SolrQuery::setHighlightSimplePost',
  ),
  123 => 
  array (
    0 => 'solrquery.sethighlightsimplepre.php',
    1 => 'SolrQuery::setHighlightSimplePre',
  ),
  124 => 
  array (
    0 => 'solrquery.sethighlightsnippets.php',
    1 => 'SolrQuery::setHighlightSnippets',
  ),
  125 => 
  array (
    0 => 'solrquery.sethighlightusephrasehighlighter.php',
    1 => 'SolrQuery::setHighlightUsePhraseHighlighter',
  ),
  126 => 
  array (
    0 => 'solrquery.setmlt.php',
    1 => 'SolrQuery::setMlt',
  ),
  127 => 
  array (
    0 => 'solrquery.setmltboost.php',
    1 => 'SolrQuery::setMltBoost',
  ),
  128 => 
  array (
    0 => 'solrquery.setmltcount.php',
    1 => 'SolrQuery::setMltCount',
  ),
  129 => 
  array (
    0 => 'solrquery.setmltmaxnumqueryterms.php',
    1 => 'SolrQuery::setMltMaxNumQueryTerms',
  ),
  130 => 
  array (
    0 => 'solrquery.setmltmaxnumtokens.php',
    1 => 'SolrQuery::setMltMaxNumTokens',
  ),
  131 => 
  array (
    0 => 'solrquery.setmltmaxwordlength.php',
    1 => 'SolrQuery::setMltMaxWordLength',
  ),
  132 => 
  array (
    0 => 'solrquery.setmltmindocfrequency.php',
    1 => 'SolrQuery::setMltMinDocFrequency',
  ),
  133 => 
  array (
    0 => 'solrquery.setmltmintermfrequency.php',
    1 => 'SolrQuery::setMltMinTermFrequency',
  ),
  134 => 
  array (
    0 => 'solrquery.setmltminwordlength.php',
    1 => 'SolrQuery::setMltMinWordLength',
  ),
  135 => 
  array (
    0 => 'solrquery.setomitheader.php',
    1 => 'SolrQuery::setOmitHeader',
  ),
  136 => 
  array (
    0 => 'solrquery.setquery.php',
    1 => 'SolrQuery::setQuery',
  ),
  137 => 
  array (
    0 => 'solrquery.setrows.php',
    1 => 'SolrQuery::setRows',
  ),
  138 => 
  array (
    0 => 'solrquery.setshowdebuginfo.php',
    1 => 'SolrQuery::setShowDebugInfo',
  ),
  139 => 
  array (
    0 => 'solrquery.setstart.php',
    1 => 'SolrQuery::setStart',
  ),
  140 => 
  array (
    0 => 'solrquery.setstats.php',
    1 => 'SolrQuery::setStats',
  ),
  141 => 
  array (
    0 => 'solrquery.setterms.php',
    1 => 'SolrQuery::setTerms',
  ),
  142 => 
  array (
    0 => 'solrquery.settermsfield.php',
    1 => 'SolrQuery::setTermsField',
  ),
  143 => 
  array (
    0 => 'solrquery.settermsincludelowerbound.php',
    1 => 'SolrQuery::setTermsIncludeLowerBound',
  ),
  144 => 
  array (
    0 => 'solrquery.settermsincludeupperbound.php',
    1 => 'SolrQuery::setTermsIncludeUpperBound',
  ),
  145 => 
  array (
    0 => 'solrquery.settermslimit.php',
    1 => 'SolrQuery::setTermsLimit',
  ),
  146 => 
  array (
    0 => 'solrquery.settermslowerbound.php',
    1 => 'SolrQuery::setTermsLowerBound',
  ),
  147 => 
  array (
    0 => 'solrquery.settermsmaxcount.php',
    1 => 'SolrQuery::setTermsMaxCount',
  ),
  148 => 
  array (
    0 => 'solrquery.settermsmincount.php',
    1 => 'SolrQuery::setTermsMinCount',
  ),
  149 => 
  array (
    0 => 'solrquery.settermsprefix.php',
    1 => 'SolrQuery::setTermsPrefix',
  ),
  150 => 
  array (
    0 => 'solrquery.settermsreturnraw.php',
    1 => 'SolrQuery::setTermsReturnRaw',
  ),
  151 => 
  array (
    0 => 'solrquery.settermssort.php',
    1 => 'SolrQuery::setTermsSort',
  ),
  152 => 
  array (
    0 => 'solrquery.settermsupperbound.php',
    1 => 'SolrQuery::setTermsUpperBound',
  ),
  153 => 
  array (
    0 => 'solrquery.settimeallowed.php',
    1 => 'SolrQuery::setTimeAllowed',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.solr.php',
    1 => 'Solr',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);