<?php
$TOC = array (
  0 => 
  array (
    0 => 'arrayaccess.offsetexists.php',
    1 => 'ArrayAccess::offsetExists',
  ),
  1 => 
  array (
    0 => 'arrayaccess.offsetget.php',
    1 => 'ArrayAccess::offsetGet',
  ),
  2 => 
  array (
    0 => 'arrayaccess.offsetset.php',
    1 => 'ArrayAccess::offsetSet',
  ),
  3 => 
  array (
    0 => 'arrayaccess.offsetunset.php',
    1 => 'ArrayAccess::offsetUnset',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'reserved.interfaces.php',
    1 => 'Predefined Interfaces',
  ),
  1 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);