<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.httprequestpool-attach.php',
    1 => 'HttpRequestPool::attach',
  ),
  1 => 
  array (
    0 => 'function.httprequestpool-construct.php',
    1 => 'HttpRequestPool::__construct',
  ),
  2 => 
  array (
    0 => 'function.httprequestpool-destruct.php',
    1 => 'HttpRequestPool::__destruct',
  ),
  3 => 
  array (
    0 => 'function.httprequestpool-detach.php',
    1 => 'HttpRequestPool::detach',
  ),
  4 => 
  array (
    0 => 'function.httprequestpool-getattachedrequests.php',
    1 => 'HttpRequestPool::getAttachedRequests',
  ),
  5 => 
  array (
    0 => 'function.httprequestpool-getfinishedrequests.php',
    1 => 'HttpRequestPool::getFinishedRequests',
  ),
  6 => 
  array (
    0 => 'function.httprequestpool-reset.php',
    1 => 'HttpRequestPool::reset',
  ),
  7 => 
  array (
    0 => 'function.httprequestpool-send.php',
    1 => 'HttpRequestPool::send',
  ),
  8 => 
  array (
    0 => 'function.httprequestpool-socketperform.php',
    1 => 'HttpRequestPool::socketPerform',
  ),
  9 => 
  array (
    0 => 'function.httprequestpool-socketselect.php',
    1 => 'HttpRequestPool::socketSelect',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.http.php',
    1 => 'HTTP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);