<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.httpdeflatestream-construct.php',
    1 => 'HttpDeflateStream::__construct',
  ),
  1 => 
  array (
    0 => 'function.httpdeflatestream-factory.php',
    1 => 'HttpDeflateStream::factory',
  ),
  2 => 
  array (
    0 => 'function.httpdeflatestream-finish.php',
    1 => 'HttpDeflateStream::finish',
  ),
  3 => 
  array (
    0 => 'function.httpdeflatestream-flush.php',
    1 => 'HttpDeflateStream::flush',
  ),
  4 => 
  array (
    0 => 'function.httpdeflatestream-update.php',
    1 => 'HttpDeflateStream::update',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.http.php',
    1 => 'HTTP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);