<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swfsoundinstance.loopcount.php',
    1 => 'SWFSoundInstance-&gt;loopCount',
  ),
  1 => 
  array (
    0 => 'function.swfsoundinstance.loopinpoint.php',
    1 => 'SWFSoundInstance-&gt;loopInPoint',
  ),
  2 => 
  array (
    0 => 'function.swfsoundinstance.loopoutpoint.php',
    1 => 'SWFSoundInstance-&gt;loopOutPoint',
  ),
  3 => 
  array (
    0 => 'function.swfsoundinstance.nomultiple.php',
    1 => 'SWFSoundInstance-&gt;noMultiple',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);