<?php
$TOC = array (
  0 => 
  array (
    0 => 'splobjectstorage.addall.php',
    1 => 'SplObjectStorage::addAll',
  ),
  1 => 
  array (
    0 => 'splobjectstorage.attach.php',
    1 => 'SplObjectStorage::attach',
  ),
  2 => 
  array (
    0 => 'splobjectstorage.contains.php',
    1 => 'SplObjectStorage::contains',
  ),
  3 => 
  array (
    0 => 'splobjectstorage.count.php',
    1 => 'SplObjectStorage::count',
  ),
  4 => 
  array (
    0 => 'splobjectstorage.current.php',
    1 => 'SplObjectStorage::current',
  ),
  5 => 
  array (
    0 => 'splobjectstorage.detach.php',
    1 => 'SplObjectStorage::detach',
  ),
  6 => 
  array (
    0 => 'splobjectstorage.getinfo.php',
    1 => 'SplObjectStorage::getInfo',
  ),
  7 => 
  array (
    0 => 'splobjectstorage.key.php',
    1 => 'SplObjectStorage::key',
  ),
  8 => 
  array (
    0 => 'splobjectstorage.next.php',
    1 => 'SplObjectStorage::next',
  ),
  9 => 
  array (
    0 => 'splobjectstorage.offsetexists.php',
    1 => 'SplObjectStorage::offsetExists',
  ),
  10 => 
  array (
    0 => 'splobjectstorage.offsetget.php',
    1 => 'SplObjectStorage::offsetGet',
  ),
  11 => 
  array (
    0 => 'splobjectstorage.offsetset.php',
    1 => 'SplObjectStorage::offsetSet',
  ),
  12 => 
  array (
    0 => 'splobjectstorage.offsetunset.php',
    1 => 'SplObjectStorage::offsetUnset',
  ),
  13 => 
  array (
    0 => 'splobjectstorage.removeall.php',
    1 => 'SplObjectStorage::removeAll',
  ),
  14 => 
  array (
    0 => 'splobjectstorage.rewind.php',
    1 => 'SplObjectStorage::rewind',
  ),
  15 => 
  array (
    0 => 'splobjectstorage.serialize.php',
    1 => 'SplObjectStorage::serialize',
  ),
  16 => 
  array (
    0 => 'splobjectstorage.setinfo.php',
    1 => 'SplObjectStorage::setInfo',
  ),
  17 => 
  array (
    0 => 'splobjectstorage.unserialize.php',
    1 => 'SplObjectStorage::unserialize',
  ),
  18 => 
  array (
    0 => 'splobjectstorage.valid.php',
    1 => 'SplObjectStorage::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.datastructures.php',
    1 => 'Datastructures',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);