<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swfbutton.addaction.php',
    1 => 'SWFButton-&gt;addAction',
  ),
  1 => 
  array (
    0 => 'function.swfbutton.addasound.php',
    1 => 'SWFButton-&gt;addASound',
  ),
  2 => 
  array (
    0 => 'function.swfbutton.addshape.php',
    1 => 'SWFButton-&gt;addShape',
  ),
  3 => 
  array (
    0 => 'function.swfbutton.construct.php',
    1 => 'SWFButton-&gt;__construct',
  ),
  4 => 
  array (
    0 => 'function.swfbutton.setaction.php',
    1 => 'SWFButton-&gt;setAction',
  ),
  5 => 
  array (
    0 => 'function.swfbutton.setdown.php',
    1 => 'SWFButton-&gt;setDown',
  ),
  6 => 
  array (
    0 => 'function.swfbutton.sethit.php',
    1 => 'SWFButton-&gt;setHit',
  ),
  7 => 
  array (
    0 => 'function.swfbutton.setmenu.php',
    1 => 'SWFButton-&gt;setMenu',
  ),
  8 => 
  array (
    0 => 'function.swfbutton.setover.php',
    1 => 'SWFButton-&gt;setOver',
  ),
  9 => 
  array (
    0 => 'function.swfbutton.setup.php',
    1 => 'SWFButton-&gt;setUp',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);