<?php
$TOC = array (
  0 => 
  array (
    0 => 'tidynode.getparent.php',
    1 => 'tidyNode::getParent',
  ),
  1 => 
  array (
    0 => 'tidynode.haschildren.php',
    1 => 'tidyNode::hasChildren',
  ),
  2 => 
  array (
    0 => 'tidynode.hassiblings.php',
    1 => 'tidyNode::hasSiblings',
  ),
  3 => 
  array (
    0 => 'tidynode.isasp.php',
    1 => 'tidyNode::isAsp',
  ),
  4 => 
  array (
    0 => 'tidynode.iscomment.php',
    1 => 'tidyNode::isComment',
  ),
  5 => 
  array (
    0 => 'tidynode.ishtml.php',
    1 => 'tidyNode::isHtml',
  ),
  6 => 
  array (
    0 => 'tidynode.isjste.php',
    1 => 'tidyNode::isJste',
  ),
  7 => 
  array (
    0 => 'tidynode.isphp.php',
    1 => 'tidyNode::isPhp',
  ),
  8 => 
  array (
    0 => 'tidynode.istext.php',
    1 => 'tidyNode::isText',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.tidy.php',
    1 => 'Tidy',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);