<?php
$TOC = array (
  0 => 
  array (
    0 => 'oauthprovider.addrequiredparameter.php',
    1 => 'OAuthProvider::addRequiredParameter',
  ),
  1 => 
  array (
    0 => 'oauthprovider.callconsumerhandler.php',
    1 => 'OAuthProvider::callconsumerHandler',
  ),
  2 => 
  array (
    0 => 'oauthprovider.calltimestampnoncehandler.php',
    1 => 'OAuthProvider::callTimestampNonceHandler',
  ),
  3 => 
  array (
    0 => 'oauthprovider.calltokenhandler.php',
    1 => 'OAuthProvider::calltokenHandler',
  ),
  4 => 
  array (
    0 => 'oauthprovider.checkoauthrequest.php',
    1 => 'OAuthProvider::checkOAuthRequest',
  ),
  5 => 
  array (
    0 => 'oauthprovider.construct.php',
    1 => 'OAuthProvider::__construct',
  ),
  6 => 
  array (
    0 => 'oauthprovider.consumerhandler.php',
    1 => 'OAuthProvider::consumerHandler',
  ),
  7 => 
  array (
    0 => 'oauthprovider.generatetoken.php',
    1 => 'OAuthProvider::generateToken',
  ),
  8 => 
  array (
    0 => 'oauthprovider.is2leggedendpoint.php',
    1 => 'OAuthProvider::is2LeggedEndpoint',
  ),
  9 => 
  array (
    0 => 'oauthprovider.isrequesttokenendpoint.php',
    1 => 'OAuthProvider::isRequestTokenEndpoint',
  ),
  10 => 
  array (
    0 => 'oauthprovider.removerequiredparameter.php',
    1 => 'OAuthProvider::removeRequiredParameter',
  ),
  11 => 
  array (
    0 => 'oauthprovider.reportproblem.php',
    1 => 'OAuthProvider::reportProblem',
  ),
  12 => 
  array (
    0 => 'oauthprovider.setparam.php',
    1 => 'OAuthProvider::setParam',
  ),
  13 => 
  array (
    0 => 'oauthprovider.setrequesttokenpath.php',
    1 => 'OAuthProvider::setRequestTokenPath',
  ),
  14 => 
  array (
    0 => 'oauthprovider.timestampnoncehandler.php',
    1 => 'OAuthProvider::timestampNonceHandler',
  ),
  15 => 
  array (
    0 => 'oauthprovider.tokenhandler.php',
    1 => 'OAuthProvider::tokenHandler',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.oauth.php',
    1 => 'OAuth',
  ),
  1 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);