<?php
$TOC = array (
  0 => 
  array (
    0 => 'phardata.addemptydir.php',
    1 => 'PharData::addEmptyDir',
  ),
  1 => 
  array (
    0 => 'phardata.addfile.php',
    1 => 'PharData::addFile',
  ),
  2 => 
  array (
    0 => 'phardata.addfromstring.php',
    1 => 'PharData::addFromString',
  ),
  3 => 
  array (
    0 => 'phardata.buildfromdirectory.php',
    1 => 'PharData::buildFromDirectory',
  ),
  4 => 
  array (
    0 => 'phardata.buildfromiterator.php',
    1 => 'PharData::buildFromIterator',
  ),
  5 => 
  array (
    0 => 'phardata.compress.php',
    1 => 'PharData::compress',
  ),
  6 => 
  array (
    0 => 'phardata.compressfiles.php',
    1 => 'PharData::compressFiles',
  ),
  7 => 
  array (
    0 => 'phardata.construct.php',
    1 => 'PharData::__construct',
  ),
  8 => 
  array (
    0 => 'phardata.converttodata.php',
    1 => 'PharData::convertToData',
  ),
  9 => 
  array (
    0 => 'phardata.converttoexecutable.php',
    1 => 'PharData::convertToExecutable',
  ),
  10 => 
  array (
    0 => 'phardata.copy.php',
    1 => 'PharData::copy',
  ),
  11 => 
  array (
    0 => 'phardata.decompress.php',
    1 => 'PharData::decompress',
  ),
  12 => 
  array (
    0 => 'phardata.decompressfiles.php',
    1 => 'PharData::decompressFiles',
  ),
  13 => 
  array (
    0 => 'phardata.delmetadata.php',
    1 => 'PharData::delMetadata',
  ),
  14 => 
  array (
    0 => 'phardata.delete.php',
    1 => 'PharData::delete',
  ),
  15 => 
  array (
    0 => 'phardata.extractto.php',
    1 => 'PharData::extractTo',
  ),
  16 => 
  array (
    0 => 'phardata.iswritable.php',
    1 => 'PharData::isWritable',
  ),
  17 => 
  array (
    0 => 'phardata.offsetset.php',
    1 => 'PharData::offsetSet',
  ),
  18 => 
  array (
    0 => 'phardata.offsetunset.php',
    1 => 'PharData::offsetUnset',
  ),
  19 => 
  array (
    0 => 'phardata.setalias.php',
    1 => 'PharData::setAlias',
  ),
  20 => 
  array (
    0 => 'phardata.setdefaultstub.php',
    1 => 'PharData::setDefaultStub',
  ),
  21 => 
  array (
    0 => 'phardata.setmetadata.php',
    1 => 'Phar::setMetadata',
  ),
  22 => 
  array (
    0 => 'phardata.setsignaturealgorithm.php',
    1 => 'Phar::setSignatureAlgorithm',
  ),
  23 => 
  array (
    0 => 'phardata.setstub.php',
    1 => 'PharData::setStub',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.phar.php',
    1 => 'Phar',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);