<?php
$TOC = array (
  0 => 
  array (
    0 => 'numberformatter.create.php',
    1 => 'NumberFormatter::create',
  ),
  1 => 
  array (
    0 => 'numberformatter.formatcurrency.php',
    1 => 'NumberFormatter::formatCurrency',
  ),
  2 => 
  array (
    0 => 'numberformatter.format.php',
    1 => 'NumberFormatter::format',
  ),
  3 => 
  array (
    0 => 'numberformatter.getattribute.php',
    1 => 'NumberFormatter::getAttribute',
  ),
  4 => 
  array (
    0 => 'numberformatter.geterrorcode.php',
    1 => 'NumberFormatter::getErrorCode',
  ),
  5 => 
  array (
    0 => 'numberformatter.geterrormessage.php',
    1 => 'NumberFormatter::getErrorMessage',
  ),
  6 => 
  array (
    0 => 'numberformatter.getlocale.php',
    1 => 'NumberFormatter::getLocale',
  ),
  7 => 
  array (
    0 => 'numberformatter.getpattern.php',
    1 => 'NumberFormatter::getPattern',
  ),
  8 => 
  array (
    0 => 'numberformatter.getsymbol.php',
    1 => 'NumberFormatter::getSymbol',
  ),
  9 => 
  array (
    0 => 'numberformatter.gettextattribute.php',
    1 => 'NumberFormatter::getTextAttribute',
  ),
  10 => 
  array (
    0 => 'numberformatter.parsecurrency.php',
    1 => 'NumberFormatter::parseCurrency',
  ),
  11 => 
  array (
    0 => 'numberformatter.parse.php',
    1 => 'NumberFormatter::parse',
  ),
  12 => 
  array (
    0 => 'numberformatter.setattribute.php',
    1 => 'NumberFormatter::setAttribute',
  ),
  13 => 
  array (
    0 => 'numberformatter.setpattern.php',
    1 => 'NumberFormatter::setPattern',
  ),
  14 => 
  array (
    0 => 'numberformatter.setsymbol.php',
    1 => 'NumberFormatter::setSymbol',
  ),
  15 => 
  array (
    0 => 'numberformatter.settextattribute.php',
    1 => 'NumberFormatter::setTextAttribute',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.intl.php',
    1 => 'intl',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);