<?php
$TOC = array (
  0 => 
  array (
    0 => 'soapparam.construct.php',
    1 => 'SoapParam::__construct',
  ),
  1 => 
  array (
    0 => 'soapparam.soapparam.php',
    1 => 'SoapParam::SoapParam',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.soap.php',
    1 => 'SOAP',
  ),
  1 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);