<?php
$TOC = array (
  0 => 
  array (
    0 => 'pdo.begintransaction.php',
    1 => 'PDO::beginTransaction',
  ),
  1 => 
  array (
    0 => 'pdo.commit.php',
    1 => 'PDO::commit',
  ),
  2 => 
  array (
    0 => 'pdo.construct.php',
    1 => 'PDO::__construct',
  ),
  3 => 
  array (
    0 => 'pdo.errorcode.php',
    1 => 'PDO::errorCode',
  ),
  4 => 
  array (
    0 => 'pdo.errorinfo.php',
    1 => 'PDO::errorInfo',
  ),
  5 => 
  array (
    0 => 'pdo.exec.php',
    1 => 'PDO::exec',
  ),
  6 => 
  array (
    0 => 'pdo.getattribute.php',
    1 => 'PDO::getAttribute',
  ),
  7 => 
  array (
    0 => 'pdo.getavailabledrivers.php',
    1 => 'PDO::getAvailableDrivers',
  ),
  8 => 
  array (
    0 => 'pdo.intransaction.php',
    1 => 'PDO::inTransaction',
  ),
  9 => 
  array (
    0 => 'pdo.lastinsertid.php',
    1 => 'PDO::lastInsertId',
  ),
  10 => 
  array (
    0 => 'pdo.prepare.php',
    1 => 'PDO::prepare',
  ),
  11 => 
  array (
    0 => 'pdo.query.php',
    1 => 'PDO::query',
  ),
  12 => 
  array (
    0 => 'pdo.quote.php',
    1 => 'PDO::quote',
  ),
  13 => 
  array (
    0 => 'pdo.rollback.php',
    1 => 'PDO::rollBack',
  ),
  14 => 
  array (
    0 => 'pdo.setattribute.php',
    1 => 'PDO::setAttribute',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.pdo.php',
    1 => 'PDO',
  ),
  1 => 
  array (
    0 => 'refs.database.abstract.php',
    1 => 'Abstraction Layers',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);