<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.imagickpixel-clear.php',
    1 => 'ImagickPixel::clear',
  ),
  1 => 
  array (
    0 => 'function.imagickpixel-construct.php',
    1 => 'ImagickPixel::__construct',
  ),
  2 => 
  array (
    0 => 'function.imagickpixel-destroy.php',
    1 => 'ImagickPixel::destroy',
  ),
  3 => 
  array (
    0 => 'function.imagickpixel-getcolor.php',
    1 => 'ImagickPixel::getColor',
  ),
  4 => 
  array (
    0 => 'function.imagickpixel-getcolorasstring.php',
    1 => 'ImagickPixel::getColorAsString',
  ),
  5 => 
  array (
    0 => 'function.imagickpixel-getcolorcount.php',
    1 => 'ImagickPixel::getColorCount',
  ),
  6 => 
  array (
    0 => 'function.imagickpixel-getcolorvalue.php',
    1 => 'ImagickPixel::getColorValue',
  ),
  7 => 
  array (
    0 => 'function.imagickpixel-gethsl.php',
    1 => 'ImagickPixel::getHSL',
  ),
  8 => 
  array (
    0 => 'function.imagickpixel-issimilar.php',
    1 => 'ImagickPixel::isSimilar',
  ),
  9 => 
  array (
    0 => 'function.imagickpixel-setcolor.php',
    1 => 'ImagickPixel::setColor',
  ),
  10 => 
  array (
    0 => 'function.imagickpixel-setcolorvalue.php',
    1 => 'ImagickPixel::setColorValue',
  ),
  11 => 
  array (
    0 => 'function.imagickpixel-sethsl.php',
    1 => 'ImagickPixel::setHSL',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.imagick.php',
    1 => 'ImageMagick',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);