<?php
$TOC = array (
  0 => 
  array (
    0 => 'xsltprocessor.construct.php',
    1 => 'XSLTProcessor::__construct',
  ),
  1 => 
  array (
    0 => 'xsltprocessor.getparameter.php',
    1 => 'XSLTProcessor::getParameter',
  ),
  2 => 
  array (
    0 => 'xsltprocessor.hasexsltsupport.php',
    1 => 'XSLTProcessor::hasExsltSupport',
  ),
  3 => 
  array (
    0 => 'xsltprocessor.importstylesheet.php',
    1 => 'XSLTProcessor::importStylesheet',
  ),
  4 => 
  array (
    0 => 'xsltprocessor.registerphpfunctions.php',
    1 => 'XSLTProcessor::registerPHPFunctions',
  ),
  5 => 
  array (
    0 => 'xsltprocessor.removeparameter.php',
    1 => 'XSLTProcessor::removeParameter',
  ),
  6 => 
  array (
    0 => 'xsltprocessor.setparameter.php',
    1 => 'XSLTProcessor::setParameter',
  ),
  7 => 
  array (
    0 => 'xsltprocessor.setprofiling.php',
    1 => 'XSLTProcessor::setProfiling',
  ),
  8 => 
  array (
    0 => 'xsltprocessor.transformtodoc.php',
    1 => 'XSLTProcessor::transformToDoc',
  ),
  9 => 
  array (
    0 => 'xsltprocessor.transformtouri.php',
    1 => 'XSLTProcessor::transformToUri',
  ),
  10 => 
  array (
    0 => 'xsltprocessor.transformtoxml.php',
    1 => 'XSLTProcessor::transformToXML',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.xsl.php',
    1 => 'XSL',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);