<?php
$TOC = array (
  0 => 
  array (
    0 => 'gearmanworker.addfunction.php',
    1 => 'GearmanWorker::addFunction',
  ),
  1 => 
  array (
    0 => 'gearmanworker.addoptions.php',
    1 => 'GearmanWorker::addOptions',
  ),
  2 => 
  array (
    0 => 'gearmanworker.addserver.php',
    1 => 'GearmanWorker::addServer',
  ),
  3 => 
  array (
    0 => 'gearmanworker.addservers.php',
    1 => 'GearmanWorker::addServers',
  ),
  4 => 
  array (
    0 => 'gearmanworker.clone.php',
    1 => 'GearmanWorker::clone',
  ),
  5 => 
  array (
    0 => 'gearmanworker.construct.php',
    1 => 'GearmanWorker::__construct',
  ),
  6 => 
  array (
    0 => 'gearmanworker.echo.php',
    1 => 'GearmanWorker::echo',
  ),
  7 => 
  array (
    0 => 'gearmanworker.error.php',
    1 => 'GearmanWorker::error',
  ),
  8 => 
  array (
    0 => 'gearmanworker.geterrno.php',
    1 => 'GearmanWorker::getErrno',
  ),
  9 => 
  array (
    0 => 'gearmanworker.options.php',
    1 => 'GearmanWorker::options',
  ),
  10 => 
  array (
    0 => 'gearmanworker.register.php',
    1 => 'GearmanWorker::register',
  ),
  11 => 
  array (
    0 => 'gearmanworker.removeoptions.php',
    1 => 'GearmanWorker::removeOptions',
  ),
  12 => 
  array (
    0 => 'gearmanworker.returncode.php',
    1 => 'GearmanWorker::returnCode',
  ),
  13 => 
  array (
    0 => 'gearmanworker.setoptions.php',
    1 => 'GearmanWorker::setOptions',
  ),
  14 => 
  array (
    0 => 'gearmanworker.settimeout.php',
    1 => 'GearmanWorker::setTimeout',
  ),
  15 => 
  array (
    0 => 'gearmanworker.timeout.php',
    1 => 'GearmanWorker::timeout',
  ),
  16 => 
  array (
    0 => 'gearmanworker.unregister.php',
    1 => 'GearmanWorker::unregister',
  ),
  17 => 
  array (
    0 => 'gearmanworker.unregisterall.php',
    1 => 'GearmanWorker::unregisterAll',
  ),
  18 => 
  array (
    0 => 'gearmanworker.wait.php',
    1 => 'GearmanWorker::wait',
  ),
  19 => 
  array (
    0 => 'gearmanworker.work.php',
    1 => 'GearmanWorker::work',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gearman.php',
    1 => 'Gearman',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);