<?php
$TOC = array (
  0 => 
  array (
    0 => 'soapserver.addfunction.php',
    1 => 'SoapServer::addFunction',
  ),
  1 => 
  array (
    0 => 'soapserver.addsoapheader.php',
    1 => 'SoapServer::addSoapHeader',
  ),
  2 => 
  array (
    0 => 'soapserver.construct.php',
    1 => 'SoapServer::__construct',
  ),
  3 => 
  array (
    0 => 'soapserver.fault.php',
    1 => 'SoapServer::fault',
  ),
  4 => 
  array (
    0 => 'soapserver.getfunctions.php',
    1 => 'SoapServer::getFunctions',
  ),
  5 => 
  array (
    0 => 'soapserver.handle.php',
    1 => 'SoapServer::handle',
  ),
  6 => 
  array (
    0 => 'soapserver.setclass.php',
    1 => 'SoapServer::setClass',
  ),
  7 => 
  array (
    0 => 'soapserver.setobject.php',
    1 => 'SoapServer::setObject',
  ),
  8 => 
  array (
    0 => 'soapserver.setpersistence.php',
    1 => 'SoapServer::setPersistence',
  ),
  9 => 
  array (
    0 => 'soapserver.soapserver.php',
    1 => 'SoapServer::SoapServer',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.soap.php',
    1 => 'SOAP',
  ),
  1 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);