<?php
$TOC = array (
  0 => 
  array (
    0 => 'solrinputdocument.addfield.php',
    1 => 'SolrInputDocument::addField',
  ),
  1 => 
  array (
    0 => 'solrinputdocument.clear.php',
    1 => 'SolrInputDocument::clear',
  ),
  2 => 
  array (
    0 => 'solrinputdocument.clone.php',
    1 => 'SolrInputDocument::__clone',
  ),
  3 => 
  array (
    0 => 'solrinputdocument.construct.php',
    1 => 'SolrInputDocument::__construct',
  ),
  4 => 
  array (
    0 => 'solrinputdocument.deletefield.php',
    1 => 'SolrInputDocument::deleteField',
  ),
  5 => 
  array (
    0 => 'solrinputdocument.destruct.php',
    1 => 'SolrInputDocument::__destruct',
  ),
  6 => 
  array (
    0 => 'solrinputdocument.fieldexists.php',
    1 => 'SolrInputDocument::fieldExists',
  ),
  7 => 
  array (
    0 => 'solrinputdocument.getboost.php',
    1 => 'SolrInputDocument::getBoost',
  ),
  8 => 
  array (
    0 => 'solrinputdocument.getfield.php',
    1 => 'SolrInputDocument::getField',
  ),
  9 => 
  array (
    0 => 'solrinputdocument.getfieldboost.php',
    1 => 'SolrInputDocument::getFieldBoost',
  ),
  10 => 
  array (
    0 => 'solrinputdocument.getfieldcount.php',
    1 => 'SolrInputDocument::getFieldCount',
  ),
  11 => 
  array (
    0 => 'solrinputdocument.getfieldnames.php',
    1 => 'SolrInputDocument::getFieldNames',
  ),
  12 => 
  array (
    0 => 'solrinputdocument.merge.php',
    1 => 'SolrInputDocument::merge',
  ),
  13 => 
  array (
    0 => 'solrinputdocument.reset.php',
    1 => 'SolrInputDocument::reset',
  ),
  14 => 
  array (
    0 => 'solrinputdocument.setboost.php',
    1 => 'SolrInputDocument::setBoost',
  ),
  15 => 
  array (
    0 => 'solrinputdocument.setfieldboost.php',
    1 => 'SolrInputDocument::setFieldBoost',
  ),
  16 => 
  array (
    0 => 'solrinputdocument.sort.php',
    1 => 'SolrInputDocument::sort',
  ),
  17 => 
  array (
    0 => 'solrinputdocument.toarray.php',
    1 => 'SolrInputDocument::toArray',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.solr.php',
    1 => 'Solr',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);