<?php
$TOC = array (
  0 => 
  array (
    0 => 'appenditerator.append.php',
    1 => 'AppendIterator::append',
  ),
  1 => 
  array (
    0 => 'appenditerator.construct.php',
    1 => 'AppendIterator::__construct',
  ),
  2 => 
  array (
    0 => 'appenditerator.current.php',
    1 => 'AppendIterator::current',
  ),
  3 => 
  array (
    0 => 'appenditerator.getarrayiterator.php',
    1 => 'AppendIterator::getArrayIterator',
  ),
  4 => 
  array (
    0 => 'appenditerator.getinneriterator.php',
    1 => 'AppendIterator::getInnerIterator',
  ),
  5 => 
  array (
    0 => 'appenditerator.getiteratorindex.php',
    1 => 'AppendIterator::getIteratorIndex',
  ),
  6 => 
  array (
    0 => 'appenditerator.key.php',
    1 => 'AppendIterator::key',
  ),
  7 => 
  array (
    0 => 'appenditerator.next.php',
    1 => 'AppendIterator::next',
  ),
  8 => 
  array (
    0 => 'appenditerator.rewind.php',
    1 => 'AppendIterator::rewind',
  ),
  9 => 
  array (
    0 => 'appenditerator.valid.php',
    1 => 'AppendIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);