<?php
$TOC = array (
  0 => 
  array (
    0 => 'intldateformatter.create.php',
    1 => 'IntlDateFormatter::create',
  ),
  1 => 
  array (
    0 => 'intldateformatter.format.php',
    1 => 'IntlDateFormatter::format',
  ),
  2 => 
  array (
    0 => 'intldateformatter.getcalendar.php',
    1 => 'IntlDateFormatter::getCalendar',
  ),
  3 => 
  array (
    0 => 'intldateformatter.getdatetype.php',
    1 => 'IntlDateFormatter::getDateType',
  ),
  4 => 
  array (
    0 => 'intldateformatter.geterrorcode.php',
    1 => 'IntlDateFormatter::getErrorCode',
  ),
  5 => 
  array (
    0 => 'intldateformatter.geterrormessage.php',
    1 => 'IntlDateFormatter::getErrorMessage',
  ),
  6 => 
  array (
    0 => 'intldateformatter.getlocale.php',
    1 => 'IntlDateFormatter::getLocale',
  ),
  7 => 
  array (
    0 => 'intldateformatter.getpattern.php',
    1 => 'IntlDateFormatter::getPattern',
  ),
  8 => 
  array (
    0 => 'intldateformatter.gettimetype.php',
    1 => 'IntlDateFormatter::getTimeType',
  ),
  9 => 
  array (
    0 => 'intldateformatter.gettimezoneid.php',
    1 => 'IntlDateFormatter::getTimeZoneId',
  ),
  10 => 
  array (
    0 => 'intldateformatter.islenient.php',
    1 => 'IntlDateFormatter::isLenient',
  ),
  11 => 
  array (
    0 => 'intldateformatter.localtime.php',
    1 => 'IntlDateFormatter::localtime',
  ),
  12 => 
  array (
    0 => 'intldateformatter.parse.php',
    1 => 'IntlDateFormatter::parse',
  ),
  13 => 
  array (
    0 => 'intldateformatter.setcalendar.php',
    1 => 'IntlDateFormatter::setCalendar',
  ),
  14 => 
  array (
    0 => 'intldateformatter.setlenient.php',
    1 => 'IntlDateFormatter::setLenient',
  ),
  15 => 
  array (
    0 => 'intldateformatter.setpattern.php',
    1 => 'IntlDateFormatter::setPattern',
  ),
  16 => 
  array (
    0 => 'intldateformatter.settimezoneid.php',
    1 => 'IntlDateFormatter::setTimeZoneId',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.intl.php',
    1 => 'intl',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);