<?php
$TOC = array (
  0 => 
  array (
    0 => 'oauth.construct.php',
    1 => 'OAuth::__construct',
  ),
  1 => 
  array (
    0 => 'oauth.destruct.php',
    1 => 'OAuth::__destruct',
  ),
  2 => 
  array (
    0 => 'oauth.disabledebug.php',
    1 => 'OAuth::disableDebug',
  ),
  3 => 
  array (
    0 => 'oauth.disableredirects.php',
    1 => 'OAuth::disableRedirects',
  ),
  4 => 
  array (
    0 => 'oauth.disablesslchecks.php',
    1 => 'OAuth::disableSSLChecks',
  ),
  5 => 
  array (
    0 => 'oauth.enabledebug.php',
    1 => 'OAuth::enableDebug',
  ),
  6 => 
  array (
    0 => 'oauth.enableredirects.php',
    1 => 'OAuth::enableRedirects',
  ),
  7 => 
  array (
    0 => 'oauth.enablesslchecks.php',
    1 => 'OAuth::enableSSLChecks',
  ),
  8 => 
  array (
    0 => 'oauth.fetch.php',
    1 => 'OAuth::fetch',
  ),
  9 => 
  array (
    0 => 'oauth.getaccesstoken.php',
    1 => 'OAuth::getAccessToken',
  ),
  10 => 
  array (
    0 => 'oauth.getcapath.php',
    1 => 'OAuth::getCAPath',
  ),
  11 => 
  array (
    0 => 'oauth.getlastresponse.php',
    1 => 'OAuth::getLastResponse',
  ),
  12 => 
  array (
    0 => 'oauth.getlastresponseinfo.php',
    1 => 'OAuth::getLastResponseInfo',
  ),
  13 => 
  array (
    0 => 'oauth.getrequesttoken.php',
    1 => 'OAuth::getRequestToken',
  ),
  14 => 
  array (
    0 => 'oauth.setauthtype.php',
    1 => 'OAuth::setAuthType',
  ),
  15 => 
  array (
    0 => 'oauth.setcapath.php',
    1 => 'OAuth::setCAPath',
  ),
  16 => 
  array (
    0 => 'oauth.setnonce.php',
    1 => 'OAuth::setNonce',
  ),
  17 => 
  array (
    0 => 'oauth.setrequestengine.php',
    1 => 'OAuth::setRequestEngine',
  ),
  18 => 
  array (
    0 => 'oauth.setrsacertificate.php',
    1 => 'OAuth::setRSACertificate',
  ),
  19 => 
  array (
    0 => 'oauth.settimestamp.php',
    1 => 'OAuth::setTimestamp',
  ),
  20 => 
  array (
    0 => 'oauth.settoken.php',
    1 => 'OAuth::setToken',
  ),
  21 => 
  array (
    0 => 'oauth.setversion.php',
    1 => 'OAuth::setVersion',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.oauth.php',
    1 => 'OAuth',
  ),
  1 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);