<?php
$TOC = array (
  0 => 
  array (
    0 => 'recursiveiteratoriterator.beginchildren.php',
    1 => 'RecursiveIteratorIterator::beginChildren',
  ),
  1 => 
  array (
    0 => 'recursiveiteratoriterator.beginiteration.php',
    1 => 'RecursiveIteratorIterator::beginIteration',
  ),
  2 => 
  array (
    0 => 'recursiveiteratoriterator.callgetchildren.php',
    1 => 'RecursiveIteratorIterator::callGetChildren',
  ),
  3 => 
  array (
    0 => 'recursiveiteratoriterator.callhaschildren.php',
    1 => 'RecursiveIteratorIterator::callHasChildren',
  ),
  4 => 
  array (
    0 => 'recursiveiteratoriterator.construct.php',
    1 => 'RecursiveIteratorIterator::__construct',
  ),
  5 => 
  array (
    0 => 'recursiveiteratoriterator.current.php',
    1 => 'RecursiveIteratorIterator::current',
  ),
  6 => 
  array (
    0 => 'recursiveiteratoriterator.endchildren.php',
    1 => 'RecursiveIteratorIterator::endChildren',
  ),
  7 => 
  array (
    0 => 'recursiveiteratoriterator.enditeration.php',
    1 => 'RecursiveIteratorIterator::endIteration',
  ),
  8 => 
  array (
    0 => 'recursiveiteratoriterator.getdepth.php',
    1 => 'RecursiveIteratorIterator::getDepth',
  ),
  9 => 
  array (
    0 => 'recursiveiteratoriterator.getinneriterator.php',
    1 => 'RecursiveIteratorIterator::getInnerIterator',
  ),
  10 => 
  array (
    0 => 'recursiveiteratoriterator.getmaxdepth.php',
    1 => 'RecursiveIteratorIterator::getMaxDepth',
  ),
  11 => 
  array (
    0 => 'recursiveiteratoriterator.getsubiterator.php',
    1 => 'RecursiveIteratorIterator::getSubIterator',
  ),
  12 => 
  array (
    0 => 'recursiveiteratoriterator.key.php',
    1 => 'RecursiveIteratorIterator::key',
  ),
  13 => 
  array (
    0 => 'recursiveiteratoriterator.next.php',
    1 => 'RecursiveIteratorIterator::next',
  ),
  14 => 
  array (
    0 => 'recursiveiteratoriterator.nextelement.php',
    1 => 'RecursiveIteratorIterator::nextElement',
  ),
  15 => 
  array (
    0 => 'recursiveiteratoriterator.rewind.php',
    1 => 'RecursiveIteratorIterator::rewind',
  ),
  16 => 
  array (
    0 => 'recursiveiteratoriterator.setmaxdepth.php',
    1 => 'RecursiveIteratorIterator::setMaxDepth',
  ),
  17 => 
  array (
    0 => 'recursiveiteratoriterator.valid.php',
    1 => 'RecursiveIteratorIterator::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);