<?php
$TOC = array (
  0 => 
  array (
    0 => 'tidy.body.php',
    1 => 'tidy::body',
  ),
  1 => 
  array (
    0 => 'tidy.cleanrepair.php',
    1 => 'tidy::cleanRepair',
  ),
  2 => 
  array (
    0 => 'tidy.construct.php',
    1 => 'tidy::__construct',
  ),
  3 => 
  array (
    0 => 'function.tidy-diagnose.php',
    1 => 'tidy::diagnose',
  ),
  4 => 
  array (
    0 => 'tidy.getconfig.php',
    1 => 'tidy::getConfig',
  ),
  5 => 
  array (
    0 => 'tidy.gethtmlver.php',
    1 => 'tidy::htmlver',
  ),
  6 => 
  array (
    0 => 'tidy.getopt.php',
    1 => 'tidy::getOpt',
  ),
  7 => 
  array (
    0 => 'tidy.getoptdoc.php',
    1 => 'tidy::getoptdoc',
  ),
  8 => 
  array (
    0 => 'tidy.getrelease.php',
    1 => 'tidy::getRelease',
  ),
  9 => 
  array (
    0 => 'tidy.getstatus.php',
    1 => 'tidy::getStatus',
  ),
  10 => 
  array (
    0 => 'tidy.head.php',
    1 => 'tidy::head',
  ),
  11 => 
  array (
    0 => 'tidy.html.php',
    1 => 'tidy::html',
  ),
  12 => 
  array (
    0 => 'tidy.isxhtml.php',
    1 => 'tidy::isXhtml',
  ),
  13 => 
  array (
    0 => 'tidy.isxml.php',
    1 => 'tidy::isXml',
  ),
  14 => 
  array (
    0 => 'tidy.parsefile.php',
    1 => 'tidy::parseFile',
  ),
  15 => 
  array (
    0 => 'tidy.parsestring.php',
    1 => 'tidy::parseString',
  ),
  16 => 
  array (
    0 => 'tidy.repairfile.php',
    1 => 'tidy::repairFile',
  ),
  17 => 
  array (
    0 => 'tidy.repairstring.php',
    1 => 'tidy::repairString',
  ),
  18 => 
  array (
    0 => 'tidy.root.php',
    1 => 'tidy::root',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.tidy.php',
    1 => 'Tidy',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);