<?php
$TOC = array (
  0 => 
  array (
    0 => 'normalizer.isnormalized.php',
    1 => 'Normalizer::isNormalized',
  ),
  1 => 
  array (
    0 => 'normalizer.normalize.php',
    1 => 'Normalizer::normalize',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.intl.php',
    1 => 'intl',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);