<?php
$TOC = array (
  0 => 
  array (
    0 => 'reflectionobject.construct.php',
    1 => 'ReflectionObject::__construct',
  ),
  1 => 
  array (
    0 => 'reflectionobject.export.php',
    1 => 'ReflectionObject::export',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.reflection.php',
    1 => 'Reflection',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);