<?php
$TOC = array (
  0 => 
  array (
    0 => 'simplexmlelement.addattribute.php',
    1 => 'SimpleXMLElement::addAttribute',
  ),
  1 => 
  array (
    0 => 'simplexmlelement.addchild.php',
    1 => 'SimpleXMLElement::addChild',
  ),
  2 => 
  array (
    0 => 'simplexmlelement.asxml.php',
    1 => 'SimpleXMLElement::asXML',
  ),
  3 => 
  array (
    0 => 'simplexmlelement.attributes.php',
    1 => 'SimpleXMLElement::attributes',
  ),
  4 => 
  array (
    0 => 'simplexmlelement.children.php',
    1 => 'SimpleXMLElement::children',
  ),
  5 => 
  array (
    0 => 'simplexmlelement.construct.php',
    1 => 'SimpleXMLElement::__construct',
  ),
  6 => 
  array (
    0 => 'simplexmlelement.count.php',
    1 => 'SimpleXMLElement::count',
  ),
  7 => 
  array (
    0 => 'simplexmlelement.getdocnamespaces.php',
    1 => 'SimpleXMLElement::getDocNamespaces',
  ),
  8 => 
  array (
    0 => 'simplexmlelement.getname.php',
    1 => 'SimpleXMLElement::getName',
  ),
  9 => 
  array (
    0 => 'simplexmlelement.getnamespaces.php',
    1 => 'SimpleXMLElement::getNamespaces',
  ),
  10 => 
  array (
    0 => 'simplexmlelement.registerxpathnamespace.php',
    1 => 'SimpleXMLElement::registerXPathNamespace',
  ),
  11 => 
  array (
    0 => 'simplexmlelement.savexml.php',
    1 => 'SimpleXMLElement::saveXML',
  ),
  12 => 
  array (
    0 => 'simplexmlelement.xpath.php',
    1 => 'SimpleXMLElement::xpath',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.simplexml.php',
    1 => 'SimpleXML',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);