<?php
$TOC = array (
  0 => 
  array (
    0 => 'regexiterator.accept.php',
    1 => 'RegexIterator::accept',
  ),
  1 => 
  array (
    0 => 'regexiterator.construct.php',
    1 => 'RegexIterator::__construct',
  ),
  2 => 
  array (
    0 => 'regexiterator.getflags.php',
    1 => 'RegexIterator::getFlags',
  ),
  3 => 
  array (
    0 => 'regexiterator.getmode.php',
    1 => 'RegexIterator::getMode',
  ),
  4 => 
  array (
    0 => 'regexiterator.getpregflags.php',
    1 => 'RegexIterator::getPregFlags',
  ),
  5 => 
  array (
    0 => 'regexiterator.setflags.php',
    1 => 'RegexIterator::setFlags',
  ),
  6 => 
  array (
    0 => 'regexiterator.setmode.php',
    1 => 'RegexIterator::setMode',
  ),
  7 => 
  array (
    0 => 'regexiterator.setpregflags.php',
    1 => 'RegexIterator::setPregFlags',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'spl.iterators.php',
    1 => 'Iterators',
  ),
  1 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  2 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);