<?php
$TOC = array (
  0 => 
  array (
    0 => 'com.examples.foreach.php',
    1 => 'For Each',
  ),
  1 => 
  array (
    0 => 'com.examples.arrays.php',
    1 => 'Arrays and Array-style COM properties',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.com.php',
    1 => 'COM',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);