<?php
$TOC = array (
  0 => 
  array (
    0 => 'configuration.file.php',
    1 => 'The configuration file',
  ),
  1 => 
  array (
    0 => 'configuration.file.per-user.php',
    1 => '.user.ini files',
  ),
  2 => 
  array (
    0 => 'configuration.changes.modes.php',
    1 => 'Where a configuration setting may be set',
  ),
  3 => 
  array (
    0 => 'configuration.changes.php',
    1 => 'How to change configuration settings',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'install.php',
    1 => 'Installation and Configuration',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);