<?php
$TOC = array (
  0 => 
  array (
    0 => 'context.socket.php',
    1 => 'Socket context options',
  ),
  1 => 
  array (
    0 => 'context.http.php',
    1 => 'HTTP context options',
  ),
  2 => 
  array (
    0 => 'context.ftp.php',
    1 => 'FTP context options',
  ),
  3 => 
  array (
    0 => 'context.ssl.php',
    1 => 'SSL context options',
  ),
  4 => 
  array (
    0 => 'context.curl.php',
    1 => 'CURL context options',
  ),
  5 => 
  array (
    0 => 'context.phar.php',
    1 => 'Phar context options',
  ),
  6 => 
  array (
    0 => 'context.params.php',
    1 => 'Context parameters',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);