<?php
$TOC = array (
  0 => 
  array (
    0 => 'crack.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'crack.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'crack.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'crack.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.crack.php',
    1 => 'Crack',
  ),
  1 => 
  array (
    0 => 'refs.crypto.php',
    1 => 'Cryptography Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);