<?php
$TOC = array (
  0 => 
  array (
    0 => 'curl.examples-basic.php',
    1 => 'Using PHP\'s cURL module to fetch the example.com homepage',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.curl.php',
    1 => 'cURL',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);