<?php
$TOC = array (
  0 => 
  array (
    0 => 'datetime.formats.time.php',
    1 => 'Time Formats',
  ),
  1 => 
  array (
    0 => 'datetime.formats.date.php',
    1 => 'Date Formats',
  ),
  2 => 
  array (
    0 => 'datetime.formats.compound.php',
    1 => 'Compound Formats',
  ),
  3 => 
  array (
    0 => 'datetime.formats.relative.php',
    1 => 'Relative Formats',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.datetime.php',
    1 => 'Date/Time',
  ),
  1 => 
  array (
    0 => 'refs.calendar.php',
    1 => 'Date and Time Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);