<?php
$TOC = array (
  0 => 
  array (
    0 => 'datetime.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'datetime.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'datetime.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'datetime.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.datetime.php',
    1 => 'Date/Time',
  ),
  1 => 
  array (
    0 => 'refs.calendar.php',
    1 => 'Date and Time Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);