<?php
$TOC = array (
  0 => 
  array (
    0 => 'dba.example.php',
    1 => 'Basic usage',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dba.php',
    1 => 'DBA',
  ),
  1 => 
  array (
    0 => 'refs.database.abstract.php',
    1 => 'Abstraction Layers',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);