<?php
$TOC = array (
  0 => 
  array (
    0 => 'dir.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'dir.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'dir.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'dir.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dir.php',
    1 => 'Directories',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.file.php',
    1 => 'File System Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);