<?php
$TOC = array (
  0 => 
  array (
    0 => 'domxml.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'domxml.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'domxml.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'domxml.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.domxml.php',
    1 => 'DOM XML (PHP 4)',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);