<?php
$TOC = array (
  0 => 
  array (
    0 => 'expect.examples-usage.php',
    1 => 'Expect Usage Examples',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.expect.php',
    1 => 'Expect',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);