<?php
$TOC = array (
  0 => 
  array (
    0 => 'extensions.alphabetical.php',
    1 => 'Alphabetical',
  ),
  1 => 
  array (
    0 => 'extensions.membership.php',
    1 => 'Membership',
  ),
  2 => 
  array (
    0 => 'extensions.state.php',
    1 => 'State',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'appendices.php',
    1 => 'Appendices',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);