<?php
$TOC = array (
  0 => 
  array (
    0 => 'faq.general.php',
    1 => 'General Information',
  ),
  1 => 
  array (
    0 => 'faq.mailinglist.php',
    1 => 'Mailing lists',
  ),
  2 => 
  array (
    0 => 'faq.obtaining.php',
    1 => 'Obtaining PHP',
  ),
  3 => 
  array (
    0 => 'faq.databases.php',
    1 => 'Database issues',
  ),
  4 => 
  array (
    0 => 'faq.installation.php',
    1 => 'Installation',
  ),
  5 => 
  array (
    0 => 'faq.build.php',
    1 => 'Build Problems',
  ),
  6 => 
  array (
    0 => 'faq.using.php',
    1 => 'Using PHP',
  ),
  7 => 
  array (
    0 => 'faq.html.php',
    1 => 'PHP and HTML',
  ),
  8 => 
  array (
    0 => 'faq.com.php',
    1 => 'PHP and COM',
  ),
  9 => 
  array (
    0 => 'faq.languages.php',
    1 => 'PHP and other languages',
  ),
  10 => 
  array (
    0 => 'faq.migration5.php',
    1 => 'Migrating from PHP 4 to PHP 5',
  ),
  11 => 
  array (
    0 => 'faq.misc.php',
    1 => 'Miscellaneous Questions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);