<?php
$TOC = array (
  0 => 
  array (
    0 => 'features.commandline.introduction.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'features.commandline.differences.php',
    1 => 'Differences to other SAPIs',
  ),
  2 => 
  array (
    0 => 'features.commandline.options.php',
    1 => 'Options',
  ),
  3 => 
  array (
    0 => 'features.commandline.usage.php',
    1 => 'Usage',
  ),
  4 => 
  array (
    0 => 'features.commandline.io-streams.php',
    1 => 'I/O streams',
  ),
  5 => 
  array (
    0 => 'features.commandline.interactive.php',
    1 => 'Interactive shell',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'features.php',
    1 => 'Features',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);