<?php
$TOC = array (
  0 => 
  array (
    0 => 'features.http-auth.php',
    1 => 'HTTP authentication with PHP',
  ),
  1 => 
  array (
    0 => 'features.cookies.php',
    1 => 'Cookies',
  ),
  2 => 
  array (
    0 => 'features.sessions.php',
    1 => 'Sessions',
  ),
  3 => 
  array (
    0 => 'features.xforms.php',
    1 => 'Dealing with XForms',
  ),
  4 => 
  array (
    0 => 'features.file-upload.php',
    1 => 'Handling file uploads',
  ),
  5 => 
  array (
    0 => 'features.remote-files.php',
    1 => 'Using remote files',
  ),
  6 => 
  array (
    0 => 'features.connection-handling.php',
    1 => 'Connection handling',
  ),
  7 => 
  array (
    0 => 'features.persistent-connections.php',
    1 => 'Persistent Database Connections',
  ),
  8 => 
  array (
    0 => 'features.safe-mode.php',
    1 => 'Safe Mode',
  ),
  9 => 
  array (
    0 => 'features.commandline.php',
    1 => 'Command line usage',
  ),
  10 => 
  array (
    0 => 'features.gc.php',
    1 => 'Garbage Collection',
  ),
  11 => 
  array (
    0 => 'features.dtrace.php',
    1 => 'DTrace Dynamic Tracing',
  ),
);
$TOC_DEPRECATED = array (
);
$PARENTS = array (
  0 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);