<?php
$TOC = array (
  0 => 
  array (
    0 => 'features.file-upload.post-method.php',
    1 => 'POST method uploads',
  ),
  1 => 
  array (
    0 => 'features.file-upload.errors.php',
    1 => 'Error Messages Explained',
  ),
  2 => 
  array (
    0 => 'features.file-upload.common-pitfalls.php',
    1 => 'Common Pitfalls',
  ),
  3 => 
  array (
    0 => 'features.file-upload.multiple.php',
    1 => 'Uploading multiple files',
  ),
  4 => 
  array (
    0 => 'features.file-upload.put-method.php',
    1 => 'PUT method support',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'features.php',
    1 => 'Features',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);