<?php
$TOC = array (
  0 => 
  array (
    0 => 'features.gc.refcounting-basics.php',
    1 => 'Reference Counting Basics',
  ),
  1 => 
  array (
    0 => 'features.gc.collecting-cycles.php',
    1 => 'Collecting Cycles',
  ),
  2 => 
  array (
    0 => 'features.gc.performance-considerations.php',
    1 => 'Performance Considerations',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'features.php',
    1 => 'Features',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);