<?php
$TOC = array (
  0 => 
  array (
    0 => 'filter.examples.validation.php',
    1 => 'Validation',
  ),
  1 => 
  array (
    0 => 'filter.examples.sanitization.php',
    1 => 'Sanitization',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.filter.php',
    1 => 'Filter',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);