<?php
$TOC = array (
  0 => 
  array (
    0 => 'filter.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'filter.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'filter.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'filter.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.filter.php',
    1 => 'Filter',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);