<?php
$TOC = array (
  0 => 
  array (
    0 => 'filter.filters.validate.php',
    1 => 'Validate filters',
  ),
  1 => 
  array (
    0 => 'filter.filters.sanitize.php',
    1 => 'Sanitize filters',
  ),
  2 => 
  array (
    0 => 'filter.filters.misc.php',
    1 => 'Other filters',
  ),
  3 => 
  array (
    0 => 'filter.filters.flags.php',
    1 => 'Filter flags',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.filter.php',
    1 => 'Filter',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);