<?php
$TOC = array (
  0 => 
  array (
    0 => 'filters.string.php',
    1 => 'String Filters',
  ),
  1 => 
  array (
    0 => 'filters.convert.php',
    1 => 'Conversion Filters',
  ),
  2 => 
  array (
    0 => 'filters.compression.php',
    1 => 'Compression Filters',
  ),
  3 => 
  array (
    0 => 'filters.encryption.php',
    1 => 'Encryption Filters',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'appendices.php',
    1 => 'Appendices',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);