<?php
$TOC = array (
  0 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  2 => 
  array (
    0 => 'refs.remote.auth.php',
    1 => 'Authentication Services',
  ),
  3 => 
  array (
    0 => 'refs.utilspec.cmdline.php',
    1 => 'Command Line Specific Extensions',
  ),
  4 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  5 => 
  array (
    0 => 'refs.creditcard.php',
    1 => 'Credit Card Processing',
  ),
  6 => 
  array (
    0 => 'refs.crypto.php',
    1 => 'Cryptography Extensions',
  ),
  7 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  8 => 
  array (
    0 => 'refs.calendar.php',
    1 => 'Date and Time Related Extensions',
  ),
  9 => 
  array (
    0 => 'refs.fileprocess.file.php',
    1 => 'File System Related Extensions',
  ),
  10 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  11 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  12 => 
  array (
    0 => 'refs.remote.mail.php',
    1 => 'Mail Related Extensions',
  ),
  13 => 
  array (
    0 => 'refs.math.php',
    1 => 'Mathematical Extensions',
  ),
  14 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  15 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  16 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  17 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  18 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  19 => 
  array (
    0 => 'refs.utilspec.server.php',
    1 => 'Server Specific Extensions',
  ),
  20 => 
  array (
    0 => 'refs.basic.session.php',
    1 => 'Session Extensions',
  ),
  21 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'Text Processing',
  ),
  22 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  23 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  24 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  25 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);