<?php
$TOC = array (
  0 => 
  array (
    0 => 'gearman.examples-reverse.php',
    1 => 'Basic Gearman client and worker',
  ),
  1 => 
  array (
    0 => 'gearman.examples-reverse-bg.php',
    1 => 'Basic Gearman client and worker, background',
  ),
  2 => 
  array (
    0 => 'gearman.examples-reverse-task.php',
    1 => 'Basic Gearman client and worker, submitting tasks',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gearman.php',
    1 => 'Gearman',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);