<?php
$TOC = array (
  0 => 
  array (
    0 => 'gmagick.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'gmagick.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'gmagick.configuration.php',
    1 => 'Runtime Configuration',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gmagick.php',
    1 => 'Gmagick',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);