<?php
$TOC = array (
  0 => 
  array (
    0 => 'gnupg.examples-clearsign.php',
    1 => 'Clearsign text',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gnupg.php',
    1 => 'GnuPG',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);