<?php
$TOC = array (
  0 => 
  array (
    0 => 'gupnp.browsing.php',
    1 => 'Browsing devices and services',
  ),
  1 => 
  array (
    0 => 'gupnp.binary-light.php',
    1 => 'Implementing the BinaryLight device',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gupnp.php',
    1 => 'Gupnp',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);