<?php
$TOC = array (
  0 => 
  array (
    0 => 'haru.builtin.fonts.php',
    1 => 'Builtin Fonts',
  ),
  1 => 
  array (
    0 => 'haru.builtin.encodings.php',
    1 => 'Builtin Encodings',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.haru.php',
    1 => 'haru',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);