<?php
$TOC = array (
  0 => 
  array (
    0 => 'hash.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'hash.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'hash.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'hash.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.hash.php',
    1 => 'Hash',
  ),
  1 => 
  array (
    0 => 'refs.crypto.php',
    1 => 'Cryptography Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);