<?php
$TOC = array (
  0 => 
  array (
    0 => 'history.php.php',
    1 => 'History of PHP',
  ),
  1 => 
  array (
    0 => 'history.php.related.php',
    1 => 'History of PHP related projects',
  ),
  2 => 
  array (
    0 => 'history.php.books.php',
    1 => 'Books about PHP',
  ),
  3 => 
  array (
    0 => 'history.php.publications.php',
    1 => 'Publications about PHP',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'appendices.php',
    1 => 'Appendices',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);