<?php
$TOC = array (
  0 => 
  array (
    0 => 'http.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'http.install.php',
    1 => 'Installing the HTTP extension',
  ),
  2 => 
  array (
    0 => 'http.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'http.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.http.php',
    1 => 'HTTP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);