<?php
$TOC = array (
  0 => 
  array (
    0 => 'iisfunc.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'iisfunc.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'iisfunc.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'iisfunc.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.iisfunc.php',
    1 => 'IIS',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.server.php',
    1 => 'Server Specific Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);