<?php
$TOC = array (
  0 => 
  array (
    0 => 'image.examples-png.php',
    1 => 'PNG creation with PHP',
  ),
  1 => 
  array (
    0 => 'image.examples-watermark.php',
    1 => 'Adding watermarks to images using alpha channels',
  ),
  2 => 
  array (
    0 => 'image.examples.merged-watermark.php',
    1 => 'Using imagecopymerge to create a translucent watermark',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.image.php',
    1 => 'GD',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);