<?php
$TOC = array (
  0 => 
  array (
    0 => 'imagick.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'imagick.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'imagick.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'imagick.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.imagick.php',
    1 => 'ImageMagick',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);