<?php
$TOC = array (
  0 => 
  array (
    0 => 'inclued.examples-implementation.php',
    1 => 'Example that implements inclued into an application',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.inclued.php',
    1 => 'inclued',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);