<?php
$TOC = array (
  0 => 
  array (
    0 => 'inclued.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'inclued.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'inclued.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'inclued.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.inclued.php',
    1 => 'inclued',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);