<?php
$TOC = array (
  0 => 
  array (
    0 => 'copyright.php',
    1 => 'Copyright',
  ),
  1 => 
  array (
    0 => 'manual.php',
    1 => 'PHP Manual',
  ),
  2 => 
  array (
    0 => 'getting-started.php',
    1 => 'Getting Started',
  ),
  3 => 
  array (
    0 => 'install.php',
    1 => 'Installation and Configuration',
  ),
  4 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  5 => 
  array (
    0 => 'security.php',
    1 => 'Security',
  ),
  6 => 
  array (
    0 => 'features.php',
    1 => 'Features',
  ),
  7 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  8 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide',
  ),
  9 => 
  array (
    0 => 'faq.php',
    1 => 'FAQ',
  ),
  10 => 
  array (
    0 => 'appendices.php',
    1 => 'Appendices',
  ),
);
$PARENTS = array (
);