<?php
$TOC = array (
  0 => 
  array (
    0 => 'ini.list.php',
    1 => 'List of php.ini directives',
  ),
  1 => 
  array (
    0 => 'ini.sections.php',
    1 => 'List of php.ini sections',
  ),
  2 => 
  array (
    0 => 'ini.core.php',
    1 => 'Description of core php.ini directives',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'appendices.php',
    1 => 'Appendices',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);