<?php
$TOC = array (
  0 => 
  array (
    0 => 'inotify.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'inotify.install.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'inotify.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'inotify.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.inotify.php',
    1 => 'Inotify',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.file.php',
    1 => 'File System Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);