<?php
$TOC = array (
  0 => 
  array (
    0 => 'install.unix.apache.php',
    1 => 'Apache 1.3.x on Unix systems',
  ),
  1 => 
  array (
    0 => 'install.unix.apache2.php',
    1 => 'Apache 2.x on Unix systems',
  ),
  2 => 
  array (
    0 => 'install.unix.lighttpd-14.php',
    1 => 'Lighttpd 1.4 on Unix systems',
  ),
  3 => 
  array (
    0 => 'install.unix.sun.php',
    1 => 'Sun, iPlanet and Netscape servers on Sun Solaris',
  ),
  4 => 
  array (
    0 => 'install.unix.commandline.php',
    1 => 'CGI and command line setups',
  ),
  5 => 
  array (
    0 => 'install.unix.hpux.php',
    1 => 'HP-UX specific installation notes',
  ),
  6 => 
  array (
    0 => 'install.unix.openbsd.php',
    1 => 'OpenBSD installation notes',
  ),
  7 => 
  array (
    0 => 'install.unix.solaris.php',
    1 => 'Solaris specific installation tips',
  ),
  8 => 
  array (
    0 => 'install.unix.debian.php',
    1 => 'Debian GNU/Linux installation notes',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'install.php',
    1 => 'Installation and Configuration',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);