<?php
$TOC = array (
  0 => 
  array (
    0 => 'install.windows.installer.php',
    1 => 'Windows Installer (PHP 5.1.0 and earlier)',
  ),
  1 => 
  array (
    0 => 'install.windows.installer.msi.php',
    1 => 'Windows Installer (PHP 5.2 and later)',
  ),
  2 => 
  array (
    0 => 'install.windows.manual.php',
    1 => 'Manual Installation Steps',
  ),
  3 => 
  array (
    0 => 'install.windows.activescript.php',
    1 => 'ActiveScript',
  ),
  4 => 
  array (
    0 => 'install.windows.iis.php',
    1 => 'Microsoft IIS',
  ),
  5 => 
  array (
    0 => 'install.windows.iis6.php',
    1 => 'Microsoft IIS 5.1 and IIS 6.0',
  ),
  6 => 
  array (
    0 => 'install.windows.iis7.php',
    1 => 'Microsoft IIS 7.0 and later',
  ),
  7 => 
  array (
    0 => 'install.windows.apache1.php',
    1 => 'Apache 1.3.x on Microsoft Windows',
  ),
  8 => 
  array (
    0 => 'install.windows.apache2.php',
    1 => 'Apache 2.x on Microsoft Windows',
  ),
  9 => 
  array (
    0 => 'install.windows.sun.php',
    1 => 'Sun, iPlanet and Netscape servers on Microsoft Windows',
  ),
  10 => 
  array (
    0 => 'install.windows.omnihttpd.php',
    1 => 'OmniHTTPd Server',
  ),
  11 => 
  array (
    0 => 'install.windows.sambar.php',
    1 => 'Sambar Server on Microsoft Windows',
  ),
  12 => 
  array (
    0 => 'install.windows.xitami.php',
    1 => 'Xitami on Microsoft Windows',
  ),
  13 => 
  array (
    0 => 'install.windows.building.php',
    1 => 'Building from source',
  ),
  14 => 
  array (
    0 => 'install.windows.extensions.php',
    1 => 'Installation of extensions on Windows',
  ),
  15 => 
  array (
    0 => 'install.windows.commandline.php',
    1 => 'Command Line PHP on Microsoft Windows',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'install.php',
    1 => 'Installation and Configuration',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);