<?php
$TOC = array (
  0 => 
  array (
    0 => 'install.general.php',
    1 => 'General Installation Considerations',
  ),
  1 => 
  array (
    0 => 'install.unix.php',
    1 => 'Installation on Unix systems',
  ),
  2 => 
  array (
    0 => 'install.macosx.php',
    1 => 'Installation on Mac OS X',
  ),
  3 => 
  array (
    0 => 'install.windows.php',
    1 => 'Installation on Windows systems',
  ),
  4 => 
  array (
    0 => 'install.fpm.php',
    1 => 'FastCGI Process Manager (FPM)',
  ),
  5 => 
  array (
    0 => 'install.pecl.php',
    1 => 'Installation of PECL extensions',
  ),
  6 => 
  array (
    0 => 'install.problems.php',
    1 => 'Problems?',
  ),
  7 => 
  array (
    0 => 'configuration.php',
    1 => 'Runtime Configuration',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);