<?php
$TOC = array (
  0 => 
  array (
    0 => 'install.macosx.packages.php',
    1 => 'Using Packages',
  ),
  1 => 
  array (
    0 => 'install.macosx.bundled.php',
    1 => 'Using the bundled PHP',
  ),
  2 => 
  array (
    0 => 'install.macosx.compile.php',
    1 => 'Compiling PHP on Mac OS X',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'install.php',
    1 => 'Installation and Configuration',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);