<?php
$TOC = array (
  0 => 
  array (
    0 => 'install.problems.faq.php',
    1 => 'Read the FAQ',
  ),
  1 => 
  array (
    0 => 'install.problems.support.php',
    1 => 'Other problems',
  ),
  2 => 
  array (
    0 => 'install.problems.bugs.php',
    1 => 'Bug reports',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'install.php',
    1 => 'Installation and Configuration',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);