<?php
$TOC = array (
  0 => 
  array (
    0 => 'install.pecl.intro.php',
    1 => 'Introduction to PECL Installations',
  ),
  1 => 
  array (
    0 => 'install.pecl.downloads.php',
    1 => 'Downloading PECL extensions',
  ),
  2 => 
  array (
    0 => 'install.pecl.windows.php',
    1 => 'Installing a PHP extension on Windows',
  ),
  3 => 
  array (
    0 => 'install.pecl.pear.php',
    1 => 'Compiling shared PECL extensions with the pecl command',
  ),
  4 => 
  array (
    0 => 'install.pecl.phpize.php',
    1 => 'Compiling shared PECL extensions with phpize',
  ),
  5 => 
  array (
    0 => 'install.pecl.static.php',
    1 => 'Compiling PECL extensions statically into PHP',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'install.php',
    1 => 'Installation and Configuration',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);