<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.counter.function.counter-create.php',
    1 => 'counter_create',
  ),
  1 => 
  array (
    0 => 'internals2.counter.function.counter-get-value.php',
    1 => 'counter_get_value',
  ),
  2 => 
  array (
    0 => 'internals2.counter.function.counter-bump-value.php',
    1 => 'counter_bump_value',
  ),
  3 => 
  array (
    0 => 'internals2.counter.function.counter-reset-value.php',
    1 => 'counter_reset_value',
  ),
  4 => 
  array (
    0 => 'internals2.counter.function.counter-get-meta.php',
    1 => 'counter_get_meta',
  ),
  5 => 
  array (
    0 => 'internals2.counter.function.counter-get-named.php',
    1 => 'counter_get_named',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'internals2.counter.php',
    1 => 'The &quot;counter&quot; Extension - A Continuing Example',
  ),
  1 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide to the Zend Engine',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);