<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.ze1.intro.php',
    1 => 'Old introduction',
  ),
  1 => 
  array (
    0 => 'internals2.ze1.streams.php',
    1 => 'Streams API for PHP Extension Authors',
  ),
  2 => 
  array (
    0 => 'internals2.ze1.zendapi.php',
    1 => 'Zend API: Hacking the Core of PHP',
  ),
  3 => 
  array (
    0 => 'internals2.ze1.tsrm.php',
    1 => 'TSRM API',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide to the Zend Engine',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);