<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.counter.function.counter-get.php',
    1 => 'counter_get',
  ),
  1 => 
  array (
    0 => 'internals2.counter.function.counter-bump.php',
    1 => 'counter_bump',
  ),
  2 => 
  array (
    0 => 'internals2.counter.function.counter-reset.php',
    1 => 'counter_reset',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'internals2.counter.php',
    1 => 'The &quot;counter&quot; Extension - A Continuing Example',
  ),
  1 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide to the Zend Engine',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);