<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.counter.examples.basic.php',
    1 => 'Basic interface',
  ),
  1 => 
  array (
    0 => 'internals2.counter.examples.extended.php',
    1 => 'Extended interface',
  ),
  2 => 
  array (
    0 => 'internals2.counter.examples.objective.php',
    1 => 'Objective interface',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'internals2.counter.php',
    1 => 'The &quot;counter&quot; Extension - A Continuing Example',
  ),
  1 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide to the Zend Engine',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);