<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.counter.intro.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'internals2.counter.ini.php',
    1 => 'Runtime Configuration',
  ),
  2 => 
  array (
    0 => 'internals2.counter.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'internals2.counter.php',
    1 => 'The &quot;counter&quot; Extension - A Continuing Example',
  ),
  1 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide to the Zend Engine',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);