<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.memory.management.php',
    1 => 'Basic memory management',
  ),
  1 => 
  array (
    0 => 'internals2.memory.persistence.php',
    1 => 'Data persistence',
  ),
  2 => 
  array (
    0 => 'internals2.memory.TSRM.php',
    1 => 'Thread-Safe Resource Manager',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide to the Zend Engine',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);