<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.structure.files.php',
    1 => 'Files which make up an extension',
  ),
  1 => 
  array (
    0 => 'internals2.structure.basics.php',
    1 => 'Basic constructs',
  ),
  2 => 
  array (
    0 => 'internals2.structure.modstruct.php',
    1 => 'The zend_module structure',
  ),
  3 => 
  array (
    0 => 'internals2.structure.globals.php',
    1 => 'Extension globals',
  ),
  4 => 
  array (
    0 => 'internals2.structure.lifecycle.php',
    1 => 'Life cycle of an extension',
  ),
  5 => 
  array (
    0 => 'internals2.structure.tests.php',
    1 => 'Testing an extension',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide to the Zend Engine',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);