<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.counter.setup.php',
    1 => 'Installing/Configuring',
  ),
  1 => 
  array (
    0 => 'internals2.counter.constants.php',
    1 => 'Predefined Constants',
  ),
  2 => 
  array (
    0 => 'internals2.counter.examples.php',
    1 => 'Examples',
  ),
  3 => 
  array (
    0 => 'internals2.counter.counter-class.php',
    1 => 'Counter',
  ),
  4 => 
  array (
    0 => 'internals2.counter.basic-interface.php',
    1 => 'Basic',
  ),
  5 => 
  array (
    0 => 'internals2.counter.extended-interface.php',
    1 => 'Extended',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide to the Zend Engine',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);