<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.counter.counter-class.construct.php',
    1 => 'Counter::__construct',
  ),
  1 => 
  array (
    0 => 'internals2.counter.counter-class.getValue.php',
    1 => 'Counter::getValue',
  ),
  2 => 
  array (
    0 => 'internals2.counter.counter-class.bumpValue.php',
    1 => 'Counter::bumpValue',
  ),
  3 => 
  array (
    0 => 'internals2.counter.counter-class.resetValue.php',
    1 => 'Counter::resetValue',
  ),
  4 => 
  array (
    0 => 'internals2.counter.counter-class.getMeta.php',
    1 => 'Counter::getMeta',
  ),
  5 => 
  array (
    0 => 'internals2.counter.counter-class.getNamed.php',
    1 => 'Counter::getNamed',
  ),
  6 => 
  array (
    0 => 'internals2.counter.counter-class.setCounterClass.php',
    1 => 'Counter::setCounterClass',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'internals2.counter.php',
    1 => 'The &quot;counter&quot; Extension - A Continuing Example',
  ),
  1 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide to the Zend Engine',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);