<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.opcodes.list.php',
    1 => 'Opcode list',
  ),
  1 => 
  array (
    0 => 'internals2.opcodes.add.php',
    1 => 'ADD',
  ),
  2 => 
  array (
    0 => 'internals2.opcodes.add-array-element.php',
    1 => 'ADD_ARRAY_ELEMENT',
  ),
  3 => 
  array (
    0 => 'internals2.opcodes.add-char.php',
    1 => 'ADD_CHAR',
  ),
  4 => 
  array (
    0 => 'internals2.opcodes.add-interface.php',
    1 => 'ADD_INTERFACE',
  ),
  5 => 
  array (
    0 => 'internals2.opcodes.add-string.php',
    1 => 'ADD_STRING',
  ),
  6 => 
  array (
    0 => 'internals2.opcodes.add-var.php',
    1 => 'ADD_VAR',
  ),
  7 => 
  array (
    0 => 'internals2.opcodes.assign.php',
    1 => 'ASSIGN',
  ),
  8 => 
  array (
    0 => 'internals2.opcodes.assign-add.php',
    1 => 'ASSIGN_ADD',
  ),
  9 => 
  array (
    0 => 'internals2.opcodes.assign-bw-and.php',
    1 => 'ASSIGN_BW_AND',
  ),
  10 => 
  array (
    0 => 'internals2.opcodes.assign-bw-or.php',
    1 => 'ASSIGN_BW_OR',
  ),
  11 => 
  array (
    0 => 'internals2.opcodes.assign-bw-xor.php',
    1 => 'ASSIGN_BW_XOR',
  ),
  12 => 
  array (
    0 => 'internals2.opcodes.assign-concat.php',
    1 => 'ASSIGN_CONCAT',
  ),
  13 => 
  array (
    0 => 'internals2.opcodes.assign-dim.php',
    1 => 'ASSIGN_DIM',
  ),
  14 => 
  array (
    0 => 'internals2.opcodes.assign-div.php',
    1 => 'ASSIGN_DIV',
  ),
  15 => 
  array (
    0 => 'internals2.opcodes.assign-mod.php',
    1 => 'ASSIGN_MOD',
  ),
  16 => 
  array (
    0 => 'internals2.opcodes.assign-mul.php',
    1 => 'ASSIGN_MUL',
  ),
  17 => 
  array (
    0 => 'internals2.opcodes.assign-obj.php',
    1 => 'ASSIGN_OBJ',
  ),
  18 => 
  array (
    0 => 'internals2.opcodes.assign-ref.php',
    1 => 'ASSIGN_REF',
  ),
  19 => 
  array (
    0 => 'internals2.opcodes.assign-sl.php',
    1 => 'ASSIGN_SL',
  ),
  20 => 
  array (
    0 => 'internals2.opcodes.assign-sr.php',
    1 => 'ASSIGN_SR',
  ),
  21 => 
  array (
    0 => 'internals2.opcodes.assign-sub.php',
    1 => 'ASSIGN_SUB',
  ),
  22 => 
  array (
    0 => 'internals2.opcodes.begin-silence.php',
    1 => 'BEGIN_SILENCE',
  ),
  23 => 
  array (
    0 => 'internals2.opcodes.bool.php',
    1 => 'BOOL',
  ),
  24 => 
  array (
    0 => 'internals2.opcodes.bool-not.php',
    1 => 'BOOL_NOT',
  ),
  25 => 
  array (
    0 => 'internals2.opcodes.bool-xor.php',
    1 => 'BOOL_XOR',
  ),
  26 => 
  array (
    0 => 'internals2.opcodes.brk.php',
    1 => 'BRK',
  ),
  27 => 
  array (
    0 => 'internals2.opcodes.bw-and.php',
    1 => 'BW_AND',
  ),
  28 => 
  array (
    0 => 'internals2.opcodes.bw-not.php',
    1 => 'BW_NOT',
  ),
  29 => 
  array (
    0 => 'internals2.opcodes.bw-or.php',
    1 => 'BW_OR',
  ),
  30 => 
  array (
    0 => 'internals2.opcodes.bw-xor.php',
    1 => 'BW_XOR',
  ),
  31 => 
  array (
    0 => 'internals2.opcodes.case.php',
    1 => 'CASE',
  ),
  32 => 
  array (
    0 => 'internals2.opcodes.cast.php',
    1 => 'CAST',
  ),
  33 => 
  array (
    0 => 'internals2.opcodes.catch.php',
    1 => 'CATCH',
  ),
  34 => 
  array (
    0 => 'internals2.opcodes.clone.php',
    1 => 'CLONE',
  ),
  35 => 
  array (
    0 => 'internals2.opcodes.concat.php',
    1 => 'CONCAT',
  ),
  36 => 
  array (
    0 => 'internals2.opcodes.declare-class.php',
    1 => 'DECLARE_CLASS',
  ),
  37 => 
  array (
    0 => 'internals2.opcodes.declare-function.php',
    1 => 'DECLARE_FUNCTION',
  ),
  38 => 
  array (
    0 => 'internals2.opcodes.declare-inherited-class.php',
    1 => 'DECLARE_INHERITED_CLASS',
  ),
  39 => 
  array (
    0 => 'internals2.opcodes.div.php',
    1 => 'DIV',
  ),
  40 => 
  array (
    0 => 'internals2.opcodes.do-fcall.php',
    1 => 'DO_FCALL',
  ),
  41 => 
  array (
    0 => 'internals2.opcodes.do-fcall-by-name.php',
    1 => 'DO_FCALL_BY_NAME',
  ),
  42 => 
  array (
    0 => 'internals2.opcodes.echo.php',
    1 => 'ECHO',
  ),
  43 => 
  array (
    0 => 'internals2.opcodes.end-silence.php',
    1 => 'END_SILENCE',
  ),
  44 => 
  array (
    0 => 'internals2.opcodes.exit.php',
    1 => 'EXIT',
  ),
  45 => 
  array (
    0 => 'internals2.opcodes.ext-fcall-begin.php',
    1 => 'EXT_FCALL_BEGIN',
  ),
  46 => 
  array (
    0 => 'internals2.opcodes.ext-fcall-end.php',
    1 => 'EXT_FCALL_END',
  ),
  47 => 
  array (
    0 => 'internals2.opcodes.ext-nop.php',
    1 => 'EXT_NOP',
  ),
  48 => 
  array (
    0 => 'internals2.opcodes.ext-stmt.php',
    1 => 'EXT_STMT',
  ),
  49 => 
  array (
    0 => 'internals2.opcodes.fetch-class.php',
    1 => 'FETCH_CLASS',
  ),
  50 => 
  array (
    0 => 'internals2.opcodes.fetch-constant.php',
    1 => 'FETCH_CONSTANT',
  ),
  51 => 
  array (
    0 => 'internals2.opcodes.fetch-dim-func-arg.php',
    1 => 'FETCH_DIM_FUNC_ARG',
  ),
  52 => 
  array (
    0 => 'internals2.opcodes.fetch-dim-is.php',
    1 => 'FETCH_DIM_IS',
  ),
  53 => 
  array (
    0 => 'internals2.opcodes.fetch-dim-r.php',
    1 => 'FETCH_DIM_R',
  ),
  54 => 
  array (
    0 => 'internals2.opcodes.fetch-dim-rw.php',
    1 => 'FETCH_DIM_RW',
  ),
  55 => 
  array (
    0 => 'internals2.opcodes.fetch-dim-tmp-var.php',
    1 => 'FETCH_DIM_TMP_VAR',
  ),
  56 => 
  array (
    0 => 'internals2.opcodes.fetch-dim-unset.php',
    1 => 'FETCH_DIM_UNSET',
  ),
  57 => 
  array (
    0 => 'internals2.opcodes.fetch-dim-w.php',
    1 => 'FETCH_DIM_W',
  ),
  58 => 
  array (
    0 => 'internals2.opcodes.fetch-func-arg.php',
    1 => 'FETCH_FUNC_ARG',
  ),
  59 => 
  array (
    0 => 'internals2.opcodes.fetch-is.php',
    1 => 'FETCH_IS',
  ),
  60 => 
  array (
    0 => 'internals2.opcodes.fetch-obj-func-arg.php',
    1 => 'FETCH_OBJ_FUNC_ARG',
  ),
  61 => 
  array (
    0 => 'internals2.opcodes.fetch-obj-is.php',
    1 => 'FETCH_OBJ_IS',
  ),
  62 => 
  array (
    0 => 'internals2.opcodes.fetch-obj-r.php',
    1 => 'FETCH_OBJ_R',
  ),
  63 => 
  array (
    0 => 'internals2.opcodes.fetch-obj-rw.php',
    1 => 'FETCH_OBJ_RW',
  ),
  64 => 
  array (
    0 => 'internals2.opcodes.fetch-obj-unset.php',
    1 => 'FETCH_OBJ_UNSET',
  ),
  65 => 
  array (
    0 => 'internals2.opcodes.fetch-obj-w.php',
    1 => 'FETCH_OBJ_W',
  ),
  66 => 
  array (
    0 => 'internals2.opcodes.fetch-r.php',
    1 => 'FETCH_R',
  ),
  67 => 
  array (
    0 => 'internals2.opcodes.fetch-rw.php',
    1 => 'FETCH_RW',
  ),
  68 => 
  array (
    0 => 'internals2.opcodes.fetch-unset.php',
    1 => 'FETCH_UNSET',
  ),
  69 => 
  array (
    0 => 'internals2.opcodes.fetch-w.php',
    1 => 'FETCH_W',
  ),
  70 => 
  array (
    0 => 'internals2.opcodes.fe-fetch.php',
    1 => 'FE_FETCH',
  ),
  71 => 
  array (
    0 => 'internals2.opcodes.fe-reset.php',
    1 => 'FE_RESET',
  ),
  72 => 
  array (
    0 => 'internals2.opcodes.free.php',
    1 => 'FREE',
  ),
  73 => 
  array (
    0 => 'internals2.opcodes.handle-exception.php',
    1 => 'HANDLE_EXCEPTION',
  ),
  74 => 
  array (
    0 => 'internals2.opcodes.include-or-eval.php',
    1 => 'INCLUDE_OR_EVAL',
  ),
  75 => 
  array (
    0 => 'internals2.opcodes.init-array.php',
    1 => 'INIT_ARRAY',
  ),
  76 => 
  array (
    0 => 'internals2.opcodes.init-fcall-by-name.php',
    1 => 'INIT_FCALL_BY_NAME',
  ),
  77 => 
  array (
    0 => 'internals2.opcodes.init-method-call.php',
    1 => 'INIT_METHOD_CALL',
  ),
  78 => 
  array (
    0 => 'internals2.opcodes.init-static-method-call.php',
    1 => 'INIT_STATIC_METHOD_CALL',
  ),
  79 => 
  array (
    0 => 'internals2.opcodes.init-string.php',
    1 => 'INIT_STRING',
  ),
  80 => 
  array (
    0 => 'internals2.opcodes.instanceof.php',
    1 => 'INSTANCEOF',
  ),
  81 => 
  array (
    0 => 'internals2.opcodes.isset-isempty-dim-obj.php',
    1 => 'ISSET_ISEMPTY_DIM_OBJ',
  ),
  82 => 
  array (
    0 => 'internals2.opcodes.isset-isempty-prop-obj.php',
    1 => 'ISSET_ISEMPTY_PROP_OBJ',
  ),
  83 => 
  array (
    0 => 'internals2.opcodes.isset-isempty-var.php',
    1 => 'ISSET_ISEMPTY_VAR',
  ),
  84 => 
  array (
    0 => 'internals2.opcodes.is-equal.php',
    1 => 'IS_EQUAL',
  ),
  85 => 
  array (
    0 => 'internals2.opcodes.is-identical.php',
    1 => 'IS_IDENTICAL',
  ),
  86 => 
  array (
    0 => 'internals2.opcodes.is-not-equal.php',
    1 => 'IS_NOT_EQUAL',
  ),
  87 => 
  array (
    0 => 'internals2.opcodes.is-not-identical.php',
    1 => 'IS_NOT_IDENTICAL',
  ),
  88 => 
  array (
    0 => 'internals2.opcodes.is-smaller.php',
    1 => 'IS_SMALLER',
  ),
  89 => 
  array (
    0 => 'internals2.opcodes.is-smaller-or-equal.php',
    1 => 'IS_SMALLER_OR_EQUAL',
  ),
  90 => 
  array (
    0 => 'internals2.opcodes.jmpnz.php',
    1 => 'JMPNZ',
  ),
  91 => 
  array (
    0 => 'internals2.opcodes.jmpnz-ex.php',
    1 => 'JMPNZ_EX',
  ),
  92 => 
  array (
    0 => 'internals2.opcodes.jmpz.php',
    1 => 'JMPZ',
  ),
  93 => 
  array (
    0 => 'internals2.opcodes.jmpznz.php',
    1 => 'JMPZNZ',
  ),
  94 => 
  array (
    0 => 'internals2.opcodes.jmpz-ex.php',
    1 => 'JMPZ_EX',
  ),
  95 => 
  array (
    0 => 'internals2.opcodes.mod.php',
    1 => 'MOD',
  ),
  96 => 
  array (
    0 => 'internals2.opcodes.mul.php',
    1 => 'MUL',
  ),
  97 => 
  array (
    0 => 'internals2.opcodes.new.php',
    1 => 'NEW',
  ),
  98 => 
  array (
    0 => 'internals2.opcodes.nop.php',
    1 => 'NOP',
  ),
  99 => 
  array (
    0 => 'internals2.opcodes.post-dec.php',
    1 => 'POST_DEC',
  ),
  100 => 
  array (
    0 => 'internals2.opcodes.post-dec-obj.php',
    1 => 'POST_DEC_OBJ',
  ),
  101 => 
  array (
    0 => 'internals2.opcodes.post-inc.php',
    1 => 'POST_INC',
  ),
  102 => 
  array (
    0 => 'internals2.opcodes.post-inc-obj.php',
    1 => 'POST_INC_OBJ',
  ),
  103 => 
  array (
    0 => 'internals2.opcodes.pre-dec.php',
    1 => 'PRE_DEC',
  ),
  104 => 
  array (
    0 => 'internals2.opcodes.pre-dec-obj.php',
    1 => 'PRE_DEC_OBJ',
  ),
  105 => 
  array (
    0 => 'internals2.opcodes.pre-inc.php',
    1 => 'PRE_INC',
  ),
  106 => 
  array (
    0 => 'internals2.opcodes.pre-inc-obj.php',
    1 => 'PRE_INC_OBJ',
  ),
  107 => 
  array (
    0 => 'internals2.opcodes.print.php',
    1 => 'PRINT',
  ),
  108 => 
  array (
    0 => 'internals2.opcodes.qm-assign.php',
    1 => 'QM_ASSIGN',
  ),
  109 => 
  array (
    0 => 'internals2.opcodes.raise-abstract-error.php',
    1 => 'RAISE_ABSTRACT_ERROR',
  ),
  110 => 
  array (
    0 => 'internals2.opcodes.recv.php',
    1 => 'RECV',
  ),
  111 => 
  array (
    0 => 'internals2.opcodes.recv-init.php',
    1 => 'RECV_INIT',
  ),
  112 => 
  array (
    0 => 'internals2.opcodes.return.php',
    1 => 'RETURN',
  ),
  113 => 
  array (
    0 => 'internals2.opcodes.send-ref.php',
    1 => 'SEND_REF',
  ),
  114 => 
  array (
    0 => 'internals2.opcodes.send-val.php',
    1 => 'SEND_VAL',
  ),
  115 => 
  array (
    0 => 'internals2.opcodes.send-var.php',
    1 => 'SEND_VAR',
  ),
  116 => 
  array (
    0 => 'internals2.opcodes.send-var-no-ref.php',
    1 => 'SEND_VAR_NO_REF',
  ),
  117 => 
  array (
    0 => 'internals2.opcodes.sl.php',
    1 => 'SL',
  ),
  118 => 
  array (
    0 => 'internals2.opcodes.sr.php',
    1 => 'SR',
  ),
  119 => 
  array (
    0 => 'internals2.opcodes.sub.php',
    1 => 'SUB',
  ),
  120 => 
  array (
    0 => 'internals2.opcodes.switch-free.php',
    1 => 'SWITCH_FREE',
  ),
  121 => 
  array (
    0 => 'internals2.opcodes.throw.php',
    1 => 'THROW',
  ),
  122 => 
  array (
    0 => 'internals2.opcodes.ticks.php',
    1 => 'TICKS',
  ),
  123 => 
  array (
    0 => 'internals2.opcodes.unset-dim.php',
    1 => 'UNSET_DIM',
  ),
  124 => 
  array (
    0 => 'internals2.opcodes.unset-obj.php',
    1 => 'UNSET_OBJ',
  ),
  125 => 
  array (
    0 => 'internals2.opcodes.unset-var.php',
    1 => 'UNSET_VAR',
  ),
  126 => 
  array (
    0 => 'internals2.opcodes.user-opcode.php',
    1 => 'USER_OPCODE',
  ),
  127 => 
  array (
    0 => 'internals2.opcodes.verify-abstract-class.php',
    1 => 'VERIFY_ABSTRACT_CLASS',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'internals2.opcodes.php',
    1 => 'Zend Engine 2 opcode list',
  ),
  1 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide to the Zend Engine',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);