<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.buildsys.environment.php',
    1 => 'Building PHP for extension development',
  ),
  1 => 
  array (
    0 => 'internals2.buildsys.skeleton.php',
    1 => 'The ext_skel script',
  ),
  2 => 
  array (
    0 => 'internals2.buildsys.configunix.php',
    1 => 'Talking to the UNIX build system: config.m4',
  ),
  3 => 
  array (
    0 => 'internals2.buildsys.configwin.php',
    1 => 'Talking to the Windows build system: config.w32',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide to the Zend Engine',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);