<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.preface.php',
    1 => 'Preface',
  ),
  1 => 
  array (
    0 => 'internals2.counter.php',
    1 => 'The &quot;counter&quot; Extension - A Continuing Example',
  ),
  2 => 
  array (
    0 => 'internals2.buildsys.php',
    1 => 'The PHP 5 build system',
  ),
  3 => 
  array (
    0 => 'internals2.structure.php',
    1 => 'Extension structure',
  ),
  4 => 
  array (
    0 => 'internals2.memory.php',
    1 => 'Memory management',
  ),
  5 => 
  array (
    0 => 'internals2.variables.php',
    1 => 'Working with variables',
  ),
  6 => 
  array (
    0 => 'internals2.funcs.php',
    1 => 'Writing functions',
  ),
  7 => 
  array (
    0 => 'internals2.objects.php',
    1 => 'Working with classes and objects',
  ),
  8 => 
  array (
    0 => 'internals2.resources.php',
    1 => 'Working with resources',
  ),
  9 => 
  array (
    0 => 'internals2.ini.php',
    1 => 'Working with INI settings',
  ),
  10 => 
  array (
    0 => 'internals2.streams.php',
    1 => 'Working with streams',
  ),
  11 => 
  array (
    0 => 'internals2.pdo.php',
    1 => 'PDO Driver How-To',
  ),
  12 => 
  array (
    0 => 'internals2.faq.php',
    1 => 'Extension FAQs',
  ),
  13 => 
  array (
    0 => 'internals2.apiref.php',
    1 => 'Zend Engine 2 API reference',
  ),
  14 => 
  array (
    0 => 'internals2.opcodes.php',
    1 => 'Zend Engine 2 opcode list',
  ),
  15 => 
  array (
    0 => 'internals2.ze1.php',
    1 => 'Zend Engine 1',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);