<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.pdo.prerequisites.php',
    1 => 'Prerequisites',
  ),
  1 => 
  array (
    0 => 'internals2.pdo.preparation.php',
    1 => 'Preparation and Housekeeping',
  ),
  2 => 
  array (
    0 => 'internals2.pdo.implementing.php',
    1 => 'Fleshing out your skeleton',
  ),
  3 => 
  array (
    0 => 'internals2.pdo.building.php',
    1 => 'Building',
  ),
  4 => 
  array (
    0 => 'internals2.pdo.testing.php',
    1 => 'Testing',
  ),
  5 => 
  array (
    0 => 'internals2.pdo.packaging.php',
    1 => 'Packaging and distribution',
  ),
  6 => 
  array (
    0 => 'internals2.pdo.pdo-dbh-t.php',
    1 => 'pdo_dbh_t definition',
  ),
  7 => 
  array (
    0 => 'internals2.pdo.pdo-stmt-t.php',
    1 => 'pdo_stmt_t definition',
  ),
  8 => 
  array (
    0 => 'internals2.pdo.constants.php',
    1 => 'Constants',
  ),
  9 => 
  array (
    0 => 'internals2.pdo.error-handling.php',
    1 => 'Error handling',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide to the Zend Engine',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);