<?php
$TOC = array (
  0 => 
  array (
    0 => 'internals2.variables.intro.php',
    1 => 'Intro',
  ),
  1 => 
  array (
    0 => 'internals2.variables.creating.php',
    1 => 'Creating variables and setting values',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'internals2.php',
    1 => 'PHP at the Core: A Hacker\'s Guide to the Zend Engine',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);