<?php
$TOC = array (
  0 => 
  array (
    0 => 'kadm5.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'kadm5.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'kadm5.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'kadm5.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.kadm5.php',
    1 => 'KADM5',
  ),
  1 => 
  array (
    0 => 'refs.remote.auth.php',
    1 => 'Authentication Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);