<?php
$TOC = array (
  0 => 
  array (
    0 => 'kadm5.constantsAF.php',
    1 => 'Constants for Attribute Flags',
  ),
  1 => 
  array (
    0 => 'pecl.kadm5.constantsOP.php',
    1 => 'Constants for Options',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.kadm5.php',
    1 => 'KADM5',
  ),
  1 => 
  array (
    0 => 'refs.remote.auth.php',
    1 => 'Authentication Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);