<?php
$TOC = array (
  0 => 
  array (
    0 => 'ktaglib.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'ktaglib.installation.php',
    1 => 'Installation',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ktaglib.php',
    1 => 'KTaglib',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);