<?php
$TOC = array (
  0 => 
  array (
    0 => 'oop5.intro.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'language.oop5.basic.php',
    1 => 'The Basics',
  ),
  2 => 
  array (
    0 => 'language.oop5.properties.php',
    1 => 'Properties',
  ),
  3 => 
  array (
    0 => 'language.oop5.constants.php',
    1 => 'Class Constants',
  ),
  4 => 
  array (
    0 => 'language.oop5.autoload.php',
    1 => 'Autoloading Classes',
  ),
  5 => 
  array (
    0 => 'language.oop5.decon.php',
    1 => 'Constructors and Destructors',
  ),
  6 => 
  array (
    0 => 'language.oop5.visibility.php',
    1 => 'Visibility',
  ),
  7 => 
  array (
    0 => 'language.oop5.inheritance.php',
    1 => 'Object Inheritance',
  ),
  8 => 
  array (
    0 => 'language.oop5.paamayim-nekudotayim.php',
    1 => 'Scope Resolution Operator (::)',
  ),
  9 => 
  array (
    0 => 'language.oop5.static.php',
    1 => 'Static Keyword',
  ),
  10 => 
  array (
    0 => 'language.oop5.abstract.php',
    1 => 'Class Abstraction',
  ),
  11 => 
  array (
    0 => 'language.oop5.interfaces.php',
    1 => 'Object Interfaces',
  ),
  12 => 
  array (
    0 => 'language.oop5.overloading.php',
    1 => 'Overloading',
  ),
  13 => 
  array (
    0 => 'language.oop5.iterations.php',
    1 => 'Object Iteration',
  ),
  14 => 
  array (
    0 => 'language.oop5.patterns.php',
    1 => 'Patterns',
  ),
  15 => 
  array (
    0 => 'language.oop5.magic.php',
    1 => 'Magic Methods',
  ),
  16 => 
  array (
    0 => 'language.oop5.final.php',
    1 => 'Final Keyword',
  ),
  17 => 
  array (
    0 => 'language.oop5.cloning.php',
    1 => 'Object Cloning',
  ),
  18 => 
  array (
    0 => 'language.oop5.object-comparison.php',
    1 => 'Comparing Objects',
  ),
  19 => 
  array (
    0 => 'language.oop5.typehinting.php',
    1 => 'Type Hinting',
  ),
  20 => 
  array (
    0 => 'language.oop5.late-static-bindings.php',
    1 => 'Late Static Bindings',
  ),
  21 => 
  array (
    0 => 'language.oop5.references.php',
    1 => 'Objects and references',
  ),
  22 => 
  array (
    0 => 'language.oop5.serialization.php',
    1 => 'Object Serialization',
  ),
  23 => 
  array (
    0 => 'language.oop5.changelog.php',
    1 => 'OOP Changelog',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);