<?php
$TOC = array (
  0 => 
  array (
    0 => 'language.references.whatare.php',
    1 => 'What References Are',
  ),
  1 => 
  array (
    0 => 'language.references.whatdo.php',
    1 => 'What References Do',
  ),
  2 => 
  array (
    0 => 'language.references.arent.php',
    1 => 'What References Are Not',
  ),
  3 => 
  array (
    0 => 'language.references.pass.php',
    1 => 'Passing by Reference',
  ),
  4 => 
  array (
    0 => 'language.references.return.php',
    1 => 'Returning References',
  ),
  5 => 
  array (
    0 => 'language.references.unset.php',
    1 => 'Unsetting References',
  ),
  6 => 
  array (
    0 => 'language.references.spot.php',
    1 => 'Spotting References',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);