<?php
$TOC = array (
  0 => 
  array (
    0 => 'language.basic-syntax.phpmode.php',
    1 => 'Escaping from HTML',
  ),
  1 => 
  array (
    0 => 'language.basic-syntax.instruction-separation.php',
    1 => 'Instruction separation',
  ),
  2 => 
  array (
    0 => 'language.basic-syntax.comments.php',
    1 => 'Comments',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);