<?php
$TOC = array (
  0 => 
  array (
    0 => 'functions.user-defined.php',
    1 => 'User-defined functions',
  ),
  1 => 
  array (
    0 => 'functions.arguments.php',
    1 => 'Function arguments',
  ),
  2 => 
  array (
    0 => 'functions.returning-values.php',
    1 => 'Returning values',
  ),
  3 => 
  array (
    0 => 'functions.variable-functions.php',
    1 => 'Variable functions',
  ),
  4 => 
  array (
    0 => 'functions.internal.php',
    1 => 'Internal (built-in) functions',
  ),
  5 => 
  array (
    0 => 'functions.anonymous.php',
    1 => 'Anonymous functions',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);