<?php
$TOC = array (
  0 => 
  array (
    0 => 'language.variables.basics.php',
    1 => 'Basics',
  ),
  1 => 
  array (
    0 => 'language.variables.predefined.php',
    1 => 'Predefined Variables',
  ),
  2 => 
  array (
    0 => 'language.variables.scope.php',
    1 => 'Variable scope',
  ),
  3 => 
  array (
    0 => 'language.variables.variable.php',
    1 => 'Variable variables',
  ),
  4 => 
  array (
    0 => 'language.variables.external.php',
    1 => 'Variables From External Sources',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);