<?php
$TOC = array (
  0 => 
  array (
    0 => 'language.basic-syntax.php',
    1 => 'Basic syntax',
  ),
  1 => 
  array (
    0 => 'language.types.php',
    1 => 'Types',
  ),
  2 => 
  array (
    0 => 'language.variables.php',
    1 => 'Variables',
  ),
  3 => 
  array (
    0 => 'language.constants.php',
    1 => 'Constants',
  ),
  4 => 
  array (
    0 => 'language.expressions.php',
    1 => 'Expressions',
  ),
  5 => 
  array (
    0 => 'language.operators.php',
    1 => 'Operators',
  ),
  6 => 
  array (
    0 => 'language.control-structures.php',
    1 => 'Control Structures',
  ),
  7 => 
  array (
    0 => 'language.functions.php',
    1 => 'Functions',
  ),
  8 => 
  array (
    0 => 'language.oop5.php',
    1 => 'Classes and Objects',
  ),
  9 => 
  array (
    0 => 'language.namespaces.php',
    1 => 'Namespaces',
  ),
  10 => 
  array (
    0 => 'language.exceptions.php',
    1 => 'Exceptions',
  ),
  11 => 
  array (
    0 => 'language.generators.php',
    1 => 'Generators',
  ),
  12 => 
  array (
    0 => 'language.references.php',
    1 => 'References Explained',
  ),
  13 => 
  array (
    0 => 'reserved.variables.php',
    1 => 'Predefined Variables',
  ),
  14 => 
  array (
    0 => 'reserved.exceptions.php',
    1 => 'Predefined Exceptions',
  ),
  15 => 
  array (
    0 => 'reserved.interfaces.php',
    1 => 'Predefined Interfaces and Classes',
  ),
  16 => 
  array (
    0 => 'context.php',
    1 => 'Context options and parameters',
  ),
  17 => 
  array (
    0 => 'wrappers.php',
    1 => 'Supported Protocols and Wrappers',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);