<?php
$TOC = array (
  0 => 
  array (
    0 => 'language.types.intro.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'language.types.boolean.php',
    1 => 'Booleans',
  ),
  2 => 
  array (
    0 => 'language.types.integer.php',
    1 => 'Integers',
  ),
  3 => 
  array (
    0 => 'language.types.float.php',
    1 => 'Floating point numbers',
  ),
  4 => 
  array (
    0 => 'language.types.string.php',
    1 => 'Strings',
  ),
  5 => 
  array (
    0 => 'language.types.array.php',
    1 => 'Arrays',
  ),
  6 => 
  array (
    0 => 'language.types.object.php',
    1 => 'Objects',
  ),
  7 => 
  array (
    0 => 'language.types.resource.php',
    1 => 'Resources',
  ),
  8 => 
  array (
    0 => 'language.types.null.php',
    1 => 'NULL',
  ),
  9 => 
  array (
    0 => 'language.pseudo-types.php',
    1 => 'Pseudo-types and variables used in this documentation',
  ),
  10 => 
  array (
    0 => 'language.types.type-juggling.php',
    1 => 'Type Juggling',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);