<?php
$TOC = array (
  0 => 
  array (
    0 => 'language.operators.precedence.php',
    1 => 'Operator Precedence',
  ),
  1 => 
  array (
    0 => 'language.operators.arithmetic.php',
    1 => 'Arithmetic Operators',
  ),
  2 => 
  array (
    0 => 'language.operators.assignment.php',
    1 => 'Assignment Operators',
  ),
  3 => 
  array (
    0 => 'language.operators.bitwise.php',
    1 => 'Bitwise Operators',
  ),
  4 => 
  array (
    0 => 'language.operators.comparison.php',
    1 => 'Comparison Operators',
  ),
  5 => 
  array (
    0 => 'language.operators.errorcontrol.php',
    1 => 'Error Control Operators',
  ),
  6 => 
  array (
    0 => 'language.operators.execution.php',
    1 => 'Execution Operators',
  ),
  7 => 
  array (
    0 => 'language.operators.increment.php',
    1 => 'Incrementing/Decrementing Operators',
  ),
  8 => 
  array (
    0 => 'language.operators.logical.php',
    1 => 'Logical Operators',
  ),
  9 => 
  array (
    0 => 'language.operators.string.php',
    1 => 'String Operators',
  ),
  10 => 
  array (
    0 => 'language.operators.array.php',
    1 => 'Array Operators',
  ),
  11 => 
  array (
    0 => 'language.operators.type.php',
    1 => 'Type Operators',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);