<?php
$TOC = array (
  0 => 
  array (
    0 => 'language.namespaces.rationale.php',
    1 => 'Namespaces overview',
  ),
  1 => 
  array (
    0 => 'language.namespaces.definition.php',
    1 => 'Defining namespaces',
  ),
  2 => 
  array (
    0 => 'language.namespaces.nested.php',
    1 => 'Declaring sub-namespaces',
  ),
  3 => 
  array (
    0 => 'language.namespaces.definitionmultiple.php',
    1 => 'Defining multiple namespaces in the same file',
  ),
  4 => 
  array (
    0 => 'language.namespaces.basics.php',
    1 => 'Using namespaces: Basics',
  ),
  5 => 
  array (
    0 => 'language.namespaces.dynamic.php',
    1 => 'Namespaces and dynamic language features',
  ),
  6 => 
  array (
    0 => 'language.namespaces.nsconstants.php',
    1 => 'namespace keyword and __NAMESPACE__ constant',
  ),
  7 => 
  array (
    0 => 'language.namespaces.importing.php',
    1 => 'Using namespaces: Aliasing/Importing',
  ),
  8 => 
  array (
    0 => 'language.namespaces.global.php',
    1 => 'Global space',
  ),
  9 => 
  array (
    0 => 'language.namespaces.fallback.php',
    1 => 'Using namespaces: fallback to global function/constant',
  ),
  10 => 
  array (
    0 => 'language.namespaces.rules.php',
    1 => 'Name resolution rules',
  ),
  11 => 
  array (
    0 => 'language.namespaces.faq.php',
    1 => 'FAQ: things you need to know about namespaces',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);