<?php
$TOC = array (
  0 => 
  array (
    0 => 'control-structures.intro.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'control-structures.if.php',
    1 => 'if',
  ),
  2 => 
  array (
    0 => 'control-structures.else.php',
    1 => 'else',
  ),
  3 => 
  array (
    0 => 'control-structures.elseif.php',
    1 => 'elseif/else if',
  ),
  4 => 
  array (
    0 => 'control-structures.alternative-syntax.php',
    1 => 'Alternative syntax for control structures',
  ),
  5 => 
  array (
    0 => 'control-structures.while.php',
    1 => 'while',
  ),
  6 => 
  array (
    0 => 'control-structures.do.while.php',
    1 => 'do-while',
  ),
  7 => 
  array (
    0 => 'control-structures.for.php',
    1 => 'for',
  ),
  8 => 
  array (
    0 => 'control-structures.foreach.php',
    1 => 'foreach',
  ),
  9 => 
  array (
    0 => 'control-structures.break.php',
    1 => 'break',
  ),
  10 => 
  array (
    0 => 'control-structures.continue.php',
    1 => 'continue',
  ),
  11 => 
  array (
    0 => 'control-structures.switch.php',
    1 => 'switch',
  ),
  12 => 
  array (
    0 => 'control-structures.declare.php',
    1 => 'declare',
  ),
  13 => 
  array (
    0 => 'function.return.php',
    1 => 'return',
  ),
  14 => 
  array (
    0 => 'function.require.php',
    1 => 'require',
  ),
  15 => 
  array (
    0 => 'function.include.php',
    1 => 'include',
  ),
  16 => 
  array (
    0 => 'function.require-once.php',
    1 => 'require_once',
  ),
  17 => 
  array (
    0 => 'function.include-once.php',
    1 => 'include_once',
  ),
  18 => 
  array (
    0 => 'control-structures.goto.php',
    1 => 'goto',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);