<?php
$TOC = array (
  0 => 
  array (
    0 => 'ldap.examples-basic.php',
    1 => 'LDAP search example',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ldap.php',
    1 => 'LDAP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);