<?php
$TOC = array (
  0 => 
  array (
    0 => 'libevent.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'libevent.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'libevent.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'libevent.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.libevent.php',
    1 => 'Libevent',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);