<?php
$TOC = array (
  0 => 
  array (
    0 => 'libxml.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'libxml.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'libxml.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'libxml.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.libxml.php',
    1 => 'libxml',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);