<?php
$TOC = array (
  0 => 
  array (
    0 => 'mail.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'mail.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'mail.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'mail.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mail.php',
    1 => 'Mail',
  ),
  1 => 
  array (
    0 => 'refs.remote.mail.php',
    1 => 'Mail Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);