<?php
$TOC = array (
  0 => 
  array (
    0 => 'mcve.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'mcve.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'mcve.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'mcve.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mcve.php',
    1 => 'MCVE',
  ),
  1 => 
  array (
    0 => 'refs.creditcard.php',
    1 => 'Credit Card Processing',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);