<?php
$TOC = array (
  0 => 
  array (
    0 => 'memcache.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'memcache.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'memcache.ini.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'memcache.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.memcache.php',
    1 => 'Memcache',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);