<?php
$TOC = array (
  0 => 
  array (
    0 => 'memcached.callbacks.result.php',
    1 => 'Result callbacks',
  ),
  1 => 
  array (
    0 => 'memcached.callbacks.read-through.php',
    1 => 'Read-through cache callbacks',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.memcached.php',
    1 => 'Memcached',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);