<?php
$TOC = array (
  0 => 
  array (
    0 => 'memtrack.examples.basic.php',
    1 => 'Creating large array in a function',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.memtrack.php',
    1 => 'Memtrack',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);