<?php
$TOC = array (
  0 => 
  array (
    0 => 'migration5.changes.php',
    1 => 'What has changed in PHP 5.0.x',
  ),
  1 => 
  array (
    0 => 'migration5.incompatible.php',
    1 => 'Backward Incompatible Changes',
  ),
  2 => 
  array (
    0 => 'migration5.cli-cgi.php',
    1 => 'CLI and CGI',
  ),
  3 => 
  array (
    0 => 'migration5.configuration.php',
    1 => 'Migrating Configuration Files',
  ),
  4 => 
  array (
    0 => 'migration5.functions.php',
    1 => 'New Functions',
  ),
  5 => 
  array (
    0 => 'migration5.newconf.php',
    1 => 'New Directives',
  ),
  6 => 
  array (
    0 => 'migration5.databases.php',
    1 => 'Databases',
  ),
  7 => 
  array (
    0 => 'migration5.oop.php',
    1 => 'New Object Model',
  ),
  8 => 
  array (
    0 => 'migrating5.errorrep.php',
    1 => 'Error Reporting',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'appendices.php',
    1 => 'Appendices',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);