<?php
$TOC = array (
  0 => 
  array (
    0 => 'migration52.changes.php',
    1 => 'What has changed in PHP 5.2.x',
  ),
  1 => 
  array (
    0 => 'migration52.incompatible.php',
    1 => 'Backward Incompatible Changes',
  ),
  2 => 
  array (
    0 => 'migration52.error-messages.php',
    1 => 'New Error Messages',
  ),
  3 => 
  array (
    0 => 'migration52.datetime.php',
    1 => 'Changes in PHP datetime
   support',
  ),
  4 => 
  array (
    0 => 'migration52.parameters.php',
    1 => 'New Parameters',
  ),
  5 => 
  array (
    0 => 'migration52.functions.php',
    1 => 'New Functions',
  ),
  6 => 
  array (
    0 => 'migration52.methods.php',
    1 => 'New Methods',
  ),
  7 => 
  array (
    0 => 'migration52.removed-extensions.php',
    1 => 'Removed Extensions',
  ),
  8 => 
  array (
    0 => 'migration52.new-extensions.php',
    1 => 'New Extensions',
  ),
  9 => 
  array (
    0 => 'migration52.classes.php',
    1 => 'New Classes',
  ),
  10 => 
  array (
    0 => 'migration52.global-constants.php',
    1 => 'New Global Constants',
  ),
  11 => 
  array (
    0 => 'migration52.class-constants.php',
    1 => 'New Class Constants',
  ),
  12 => 
  array (
    0 => 'migration52.newconf.php',
    1 => 'New INI Configuration Directives',
  ),
  13 => 
  array (
    0 => 'migration52.errorrep.php',
    1 => 'Error Reporting',
  ),
  14 => 
  array (
    0 => 'migration52.other.php',
    1 => 'Other Enhancements',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'appendices.php',
    1 => 'Appendices',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);