<?php
$TOC = array (
  0 => 
  array (
    0 => 'migration51.changes.php',
    1 => 'Key PHP 5.1.x features',
  ),
  1 => 
  array (
    0 => 'migration51.references.php',
    1 => 'Changes in reference handling',
  ),
  2 => 
  array (
    0 => 'migration51.reading.php',
    1 => 'Reading []',
  ),
  3 => 
  array (
    0 => 'migration51.integer-parameters.php',
    1 => 'Integer values in function parameters',
  ),
  4 => 
  array (
    0 => 'migration51.oop.php',
    1 => 'Class and object changes',
  ),
  5 => 
  array (
    0 => 'migration51.extensions.php',
    1 => 'Extensions',
  ),
  6 => 
  array (
    0 => 'migration51.datetime.php',
    1 => 'Date/time support',
  ),
  7 => 
  array (
    0 => 'migration51.databases.php',
    1 => 'Changes in database support',
  ),
  8 => 
  array (
    0 => 'migration51.errorcheck.php',
    1 => 'Checking for E_STRICT',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'appendices.php',
    1 => 'Appendices',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);