<?php
$TOC = array (
  0 => 
  array (
    0 => 'migration53.changes.php',
    1 => 'What has changed in PHP 5.3.x',
  ),
  1 => 
  array (
    0 => 'migration53.incompatible.php',
    1 => 'Backward Incompatible Changes',
  ),
  2 => 
  array (
    0 => 'migration53.new-features.php',
    1 => 'New features',
  ),
  3 => 
  array (
    0 => 'migration53.windows.php',
    1 => 'Changes made to Windows support',
  ),
  4 => 
  array (
    0 => 'migration53.sapi.php',
    1 => 'Changes in SAPI modules',
  ),
  5 => 
  array (
    0 => 'migration53.deprecated.php',
    1 => 'Deprecated features in PHP 5.3.x',
  ),
  6 => 
  array (
    0 => 'migration53.undeprecated.php',
    1 => 'Undeprecated features in PHP 5.3.x',
  ),
  7 => 
  array (
    0 => 'migration53.parameters.php',
    1 => 'New Parameters',
  ),
  8 => 
  array (
    0 => 'migration53.functions.php',
    1 => 'New Functions',
  ),
  9 => 
  array (
    0 => 'migration53.new-stream-wrappers.php',
    1 => 'New stream wrappers',
  ),
  10 => 
  array (
    0 => 'migration53.new-stream-filters.php',
    1 => 'New stream filters',
  ),
  11 => 
  array (
    0 => 'migration53.class-constants.php',
    1 => 'New Class Constants',
  ),
  12 => 
  array (
    0 => 'migration53.methods.php',
    1 => 'New Methods',
  ),
  13 => 
  array (
    0 => 'migration53.new-extensions.php',
    1 => 'New Extensions',
  ),
  14 => 
  array (
    0 => 'migration53.removed-extensions.php',
    1 => 'Removed Extensions',
  ),
  15 => 
  array (
    0 => 'migration53.extensions-other.php',
    1 => 'Other changes to extensions',
  ),
  16 => 
  array (
    0 => 'migration53.classes.php',
    1 => 'New Classes',
  ),
  17 => 
  array (
    0 => 'migration53.global-constants.php',
    1 => 'New Global Constants',
  ),
  18 => 
  array (
    0 => 'migration53.ini.php',
    1 => 'Changes to INI file handling',
  ),
  19 => 
  array (
    0 => 'migration53.other.php',
    1 => 'Other changes',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'appendices.php',
    1 => 'Appendices',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);