<?php
$TOC = array (
  0 => 
  array (
    0 => 'ming.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'ming.install.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'ming.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'ming.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);