<?php
$TOC = array (
  0 => 
  array (
    0 => 'mnogosearch.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'mnogosearch.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'mnogosearch.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'mnogosearch.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mnogosearch.php',
    1 => 'mnoGoSearch',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);