<?php
$TOC = array (
  0 => 
  array (
    0 => 'class.mongogridfs.php',
    1 => 'MongoGridFS',
  ),
  1 => 
  array (
    0 => 'class.mongogridfsfile.php',
    1 => 'MongoGridFSFile',
  ),
  2 => 
  array (
    0 => 'class.mongogridfscursor.php',
    1 => 'MongoGridFSCursor',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);