<?php
$TOC = array (
  0 => 
  array (
    0 => 'class.mongoid.php',
    1 => 'MongoId',
  ),
  1 => 
  array (
    0 => 'class.mongocode.php',
    1 => 'MongoCode',
  ),
  2 => 
  array (
    0 => 'class.mongodate.php',
    1 => 'MongoDate',
  ),
  3 => 
  array (
    0 => 'class.mongoregex.php',
    1 => 'MongoRegex',
  ),
  4 => 
  array (
    0 => 'class.mongobindata.php',
    1 => 'MongoBinData',
  ),
  5 => 
  array (
    0 => 'class.mongoint32.php',
    1 => 'MongoInt32',
  ),
  6 => 
  array (
    0 => 'class.mongoint64.php',
    1 => 'MongoInt64',
  ),
  7 => 
  array (
    0 => 'class.mongodbref.php',
    1 => 'MongoDBRef',
  ),
  8 => 
  array (
    0 => 'class.mongominkey.php',
    1 => 'MongoMinKey',
  ),
  9 => 
  array (
    0 => 'class.mongomaxkey.php',
    1 => 'MongoMaxKey',
  ),
  10 => 
  array (
    0 => 'class.mongotimestamp.php',
    1 => 'MongoTimestamp',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);