<?php
$TOC = array (
  0 => 
  array (
    0 => 'class.mongoexception.php',
    1 => 'MongoException',
  ),
  1 => 
  array (
    0 => 'class.mongocursorexception.php',
    1 => 'MongoCursorException',
  ),
  2 => 
  array (
    0 => 'class.mongocursortimeoutexception.php',
    1 => 'MongoCursorTimeoutException',
  ),
  3 => 
  array (
    0 => 'class.mongoconnectionexception.php',
    1 => 'MongoConnectionException',
  ),
  4 => 
  array (
    0 => 'class.mongogridfsexception.php',
    1 => 'MongoGridFSException',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);