<?php
$TOC = array (
  0 => 
  array (
    0 => 'mongo.installation.php',
    1 => 'Installation',
  ),
  1 => 
  array (
    0 => 'mongo.configuration.php',
    1 => 'php.ini Options',
  ),
  2 => 
  array (
    0 => 'mongo.tutorial.php',
    1 => 'Tutorial',
  ),
  3 => 
  array (
    0 => 'mongo.connecting.php',
    1 => 'Connecting',
  ),
  4 => 
  array (
    0 => 'mongo.writes.php',
    1 => 'Writes',
  ),
  5 => 
  array (
    0 => 'mongo.queries.php',
    1 => 'Querying',
  ),
  6 => 
  array (
    0 => 'mongo.updates.php',
    1 => 'Updates',
  ),
  7 => 
  array (
    0 => 'mongo.security.php',
    1 => 'Security',
  ),
  8 => 
  array (
    0 => 'mongo.testing.php',
    1 => 'Running the Driver\'s Tests',
  ),
  9 => 
  array (
    0 => 'mongo.trouble.php',
    1 => 'Troubleshooting',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);