<?php
$TOC = array (
  0 => 
  array (
    0 => 'mqseries.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'mqseries.configure.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'mqseries.ini.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'mqseries.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mqseries.php',
    1 => 'mqseries',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);