<?php
$TOC = array (
  0 => 
  array (
    0 => 'msql.examples-basic.php',
    1 => 'mSQL usage example',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.msql.php',
    1 => 'mSQL',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);