<?php
$TOC = array (
  0 => 
  array (
    0 => 'mssql.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'mssql.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'mssql.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'mssql.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mssql.php',
    1 => 'Mssql',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);