<?php
$TOC = array (
  0 => 
  array (
    0 => 'mysqlnd-qc.basic_usage.php',
    1 => 'Basic usage',
  ),
  1 => 
  array (
    0 => 'mysqlnd-qc.per_query_ttl.php',
    1 => 'Setting the TTL',
  ),
  2 => 
  array (
    0 => 'mysqlnd-qc.cache_by_default.php',
    1 => 'Cache by default',
  ),
  3 => 
  array (
    0 => 'mysqlnd-qc.set_user_handlers.php',
    1 => 'Procedural user-defined storage handler',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mysqlnd-qc.php',
    1 => 'mysqlnd_qc',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);