<?php
$TOC = array (
  0 => 
  array (
    0 => 'mysqlnd.plugin.mysql-proxy.php',
    1 => 'A comparison of mysqlnd plugins with MySQL Proxy',
  ),
  1 => 
  array (
    0 => 'mysqlnd.plugin.obtaining.php',
    1 => 'Obtaining the mysqlnd plugin API',
  ),
  2 => 
  array (
    0 => 'mysqlnd.plugin.architecture.php',
    1 => 'MySQL Native Driver Plugin Architecture',
  ),
  3 => 
  array (
    0 => 'mysqlnd.plugin.api.php',
    1 => 'The mysqlnd plugin API',
  ),
  4 => 
  array (
    0 => 'mysqlnd.plugin.developing.php',
    1 => 'Getting started building a mysqlnd plugin',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mysqlnd.php',
    1 => 'Mysqlnd',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);