<?php
$TOC = array (
  0 => 
  array (
    0 => 'ncurses.errconsts.php',
    1 => 'Error codes',
  ),
  1 => 
  array (
    0 => 'ncurses.colorconsts.php',
    1 => 'Colors',
  ),
  2 => 
  array (
    0 => 'ncurses.keyconsts.php',
    1 => 'Keys',
  ),
  3 => 
  array (
    0 => 'ncurses.mouseconsts.php',
    1 => 'Mouse',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ncurses.php',
    1 => 'Ncurses',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.cmdline.php',
    1 => 'Command Line Specific Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);