<?php
$TOC = array (
  0 => 
  array (
    0 => 'net-gopher.examples-basic.php',
    1 => 'Basic Example',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.net-gopher.php',
    1 => 'Gopher',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);