<?php
$TOC = array (
  0 => 
  array (
    0 => 'newt.examples-usage.php',
    1 => 'Basic usage',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.newt.php',
    1 => 'Newt',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.cmdline.php',
    1 => 'Command Line Specific Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);