<?php
$TOC = array (
  0 => 
  array (
    0 => 'constants.newt.reasons.php',
    1 => 'Newt form exit reasons',
  ),
  1 => 
  array (
    0 => 'constants.newt.colorsets.php',
    1 => 'Newt colorsets',
  ),
  2 => 
  array (
    0 => 'constants.newt.args-flags.php',
    1 => 'Newt argument flags',
  ),
  3 => 
  array (
    0 => 'constants.newt.sense-flags.php',
    1 => 'Newt Flags Sense',
  ),
  4 => 
  array (
    0 => 'constants.newt.components-flags.php',
    1 => 'Newt Components Flags',
  ),
  5 => 
  array (
    0 => 'constants.newt.fd-flags.php',
    1 => 'File Descriptor Flags',
  ),
  6 => 
  array (
    0 => 'constants.newt.cbtree-flags.php',
    1 => 'Checkbox Tree Flags',
  ),
  7 => 
  array (
    0 => 'constants.newt.entry-flags.php',
    1 => 'Entry Flags',
  ),
  8 => 
  array (
    0 => 'constants.newt.listbox-flags.php',
    1 => 'Listbox Flags',
  ),
  9 => 
  array (
    0 => 'constants.newt.textbox-flags.php',
    1 => 'Textbox Flags',
  ),
  10 => 
  array (
    0 => 'constants.newt.form-flags.php',
    1 => 'Form Flags',
  ),
  11 => 
  array (
    0 => 'constants.newt.keys.php',
    1 => 'Newt Keys',
  ),
  12 => 
  array (
    0 => 'constants.newt.anchor.php',
    1 => 'Newt Anchors',
  ),
  13 => 
  array (
    0 => 'constants.newt.grid-flags.php',
    1 => 'Grid Flags',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.newt.php',
    1 => 'Newt',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.cmdline.php',
    1 => 'Command Line Specific Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);