<?php
$TOC = array (
  0 => 
  array (
    0 => 'oauth.examples.fireeagle.php',
    1 => 'FireEagle',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.oauth.php',
    1 => 'OAuth',
  ),
  1 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);