<?php
$TOC = array (
  0 => 
  array (
    0 => 'objaggregation.examples.association.php',
    1 => 'Object Aggregation examples',
  ),
  1 => 
  array (
    0 => 'objaggregation.examples2.php',
    1 => 'Examples',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.objaggregation.php',
    1 => 'Object Aggregation',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);