<?php
$TOC = array (
  0 => 
  array (
    0 => 'oci8.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'oci8.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'oci8.test.php',
    1 => 'Testing',
  ),
  3 => 
  array (
    0 => 'oci8.configuration.php',
    1 => 'Runtime Configuration',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.oci8.php',
    1 => 'OCI8',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);