<?php
$TOC = array (
  0 => 
  array (
    0 => 'oggvorbis.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'oggvorbis.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'oggvorbis.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'oggvorbis.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.oggvorbis.php',
    1 => 'oggvorbis',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);