<?php
$TOC = array (
  0 => 
  array (
    0 => 'oggvorbis.examples-basisc.php',
    1 => 'Examples on using the ogg:// wrapper.',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.oggvorbis.php',
    1 => 'oggvorbis',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);