<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ocibindbyname.php',
    1 => 'ocibindbyname',
  ),
  1 => 
  array (
    0 => 'function.ocicancel.php',
    1 => 'ocicancel',
  ),
  2 => 
  array (
    0 => 'function.ocicloselob.php',
    1 => 'ocicloselob',
  ),
  3 => 
  array (
    0 => 'function.ocicollappend.php',
    1 => 'ocicollappend',
  ),
  4 => 
  array (
    0 => 'function.ocicollassign.php',
    1 => 'ocicollassign',
  ),
  5 => 
  array (
    0 => 'function.ocicollassignelem.php',
    1 => 'ocicollassignelem',
  ),
  6 => 
  array (
    0 => 'function.ocicollgetelem.php',
    1 => 'ocicollgetelem',
  ),
  7 => 
  array (
    0 => 'function.ocicollmax.php',
    1 => 'ocicollmax',
  ),
  8 => 
  array (
    0 => 'function.ocicollsize.php',
    1 => 'ocicollsize',
  ),
  9 => 
  array (
    0 => 'function.ocicolltrim.php',
    1 => 'ocicolltrim',
  ),
  10 => 
  array (
    0 => 'function.ocicolumnisnull.php',
    1 => 'ocicolumnisnull',
  ),
  11 => 
  array (
    0 => 'function.ocicolumnname.php',
    1 => 'ocicolumnname',
  ),
  12 => 
  array (
    0 => 'function.ocicolumnprecision.php',
    1 => 'ocicolumnprecision',
  ),
  13 => 
  array (
    0 => 'function.ocicolumnscale.php',
    1 => 'ocicolumnscale',
  ),
  14 => 
  array (
    0 => 'function.ocicolumnsize.php',
    1 => 'ocicolumnsize',
  ),
  15 => 
  array (
    0 => 'function.ocicolumntype.php',
    1 => 'ocicolumntype',
  ),
  16 => 
  array (
    0 => 'function.ocicolumntyperaw.php',
    1 => 'ocicolumntyperaw',
  ),
  17 => 
  array (
    0 => 'function.ocicommit.php',
    1 => 'ocicommit',
  ),
  18 => 
  array (
    0 => 'function.ocidefinebyname.php',
    1 => 'ocidefinebyname',
  ),
  19 => 
  array (
    0 => 'function.ocierror.php',
    1 => 'ocierror',
  ),
  20 => 
  array (
    0 => 'function.ociexecute.php',
    1 => 'ociexecute',
  ),
  21 => 
  array (
    0 => 'function.ocifetch.php',
    1 => 'ocifetch',
  ),
  22 => 
  array (
    0 => 'function.ocifetchinto.php',
    1 => 'ocifetchinto',
  ),
  23 => 
  array (
    0 => 'function.ocifetchstatement.php',
    1 => 'ocifetchstatement',
  ),
  24 => 
  array (
    0 => 'function.ocifreecollection.php',
    1 => 'ocifreecollection',
  ),
  25 => 
  array (
    0 => 'function.ocifreecursor.php',
    1 => 'ocifreecursor',
  ),
  26 => 
  array (
    0 => 'function.ocifreedesc.php',
    1 => 'ocifreedesc',
  ),
  27 => 
  array (
    0 => 'function.ocifreestatement.php',
    1 => 'ocifreestatement',
  ),
  28 => 
  array (
    0 => 'function.ociinternaldebug.php',
    1 => 'ociinternaldebug',
  ),
  29 => 
  array (
    0 => 'function.ociloadlob.php',
    1 => 'ociloadlob',
  ),
  30 => 
  array (
    0 => 'function.ocilogoff.php',
    1 => 'ocilogoff',
  ),
  31 => 
  array (
    0 => 'function.ocilogon.php',
    1 => 'ocilogon',
  ),
  32 => 
  array (
    0 => 'function.ocinewcollection.php',
    1 => 'ocinewcollection',
  ),
  33 => 
  array (
    0 => 'function.ocinewcursor.php',
    1 => 'ocinewcursor',
  ),
  34 => 
  array (
    0 => 'function.ocinewdescriptor.php',
    1 => 'ocinewdescriptor',
  ),
  35 => 
  array (
    0 => 'function.ocinlogon.php',
    1 => 'ocinlogon',
  ),
  36 => 
  array (
    0 => 'function.ocinumcols.php',
    1 => 'ocinumcols',
  ),
  37 => 
  array (
    0 => 'function.ociparse.php',
    1 => 'ociparse',
  ),
  38 => 
  array (
    0 => 'function.ociplogon.php',
    1 => 'ociplogon',
  ),
  39 => 
  array (
    0 => 'function.ociresult.php',
    1 => 'ociresult',
  ),
  40 => 
  array (
    0 => 'function.ocirollback.php',
    1 => 'ocirollback',
  ),
  41 => 
  array (
    0 => 'function.ocirowcount.php',
    1 => 'ocirowcount',
  ),
  42 => 
  array (
    0 => 'function.ocisavelob.php',
    1 => 'ocisavelob',
  ),
  43 => 
  array (
    0 => 'function.ocisavelobfile.php',
    1 => 'ocisavelobfile',
  ),
  44 => 
  array (
    0 => 'function.ociserverversion.php',
    1 => 'ociserverversion',
  ),
  45 => 
  array (
    0 => 'function.ocisetprefetch.php',
    1 => 'ocisetprefetch',
  ),
  46 => 
  array (
    0 => 'function.ocistatementtype.php',
    1 => 'ocistatementtype',
  ),
  47 => 
  array (
    0 => 'function.ociwritelobtofile.php',
    1 => 'ociwritelobtofile',
  ),
  48 => 
  array (
    0 => 'function.ociwritetemporarylob.php',
    1 => 'ociwritetemporarylob',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.oci8.php',
    1 => 'OCI8',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);