<?php
$TOC = array (
  0 => 
  array (
    0 => 'keyword.class.php',
    1 => 'class',
  ),
  1 => 
  array (
    0 => 'keyword.extends.php',
    1 => 'extends',
  ),
  2 => 
  array (
    0 => 'oop4.constructor.php',
    1 => 'Constructors',
  ),
  3 => 
  array (
    0 => 'keyword.paamayim-nekudotayim.php',
    1 => 'Scope Resolution Operator (::)',
  ),
  4 => 
  array (
    0 => 'keyword.parent.php',
    1 => 'parent',
  ),
  5 => 
  array (
    0 => 'oop4.serialization.php',
    1 => 'Serializing objects - objects in sessions',
  ),
  6 => 
  array (
    0 => 'oop4.magic-functions.php',
    1 => 'The magic functions __sleep and __wakeup',
  ),
  7 => 
  array (
    0 => 'oop4.newref.php',
    1 => 'References inside the constructor',
  ),
  8 => 
  array (
    0 => 'oop4.object-comparison.php',
    1 => 'Comparing objects',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'appendices.php',
    1 => 'Appendices',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);