<?php
$TOC = array (
  0 => 
  array (
    0 => 'openssl.purpose-check.php',
    1 => 'Purpose checking flags',
  ),
  1 => 
  array (
    0 => 'openssl.padding.php',
    1 => 'Padding flags',
  ),
  2 => 
  array (
    0 => 'openssl.key-types.php',
    1 => 'Key types',
  ),
  3 => 
  array (
    0 => 'openssl.pkcs7.flags.php',
    1 => 'PKCS7 Flags/Constants',
  ),
  4 => 
  array (
    0 => 'openssl.signature-algos.php',
    1 => 'Signature Algorithms',
  ),
  5 => 
  array (
    0 => 'openssl.ciphers.php',
    1 => 'Ciphers',
  ),
  6 => 
  array (
    0 => 'openssl.constversion.php',
    1 => 'Version constants',
  ),
  7 => 
  array (
    0 => 'openssl.constsni.php',
    1 => 'Server Name Indication constants',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.openssl.php',
    1 => 'OpenSSL',
  ),
  1 => 
  array (
    0 => 'refs.crypto.php',
    1 => 'Cryptography Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);