<?php
$TOC = array (
  0 => 
  array (
    0 => 'outcontrol.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'outcontrol.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'outcontrol.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'outcontrol.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.outcontrol.php',
    1 => 'Output Control',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);