<?php
$TOC = array (
  0 => 
  array (
    0 => 'outcontrol.examples.basic.php',
    1 => 'Examples',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.outcontrol.php',
    1 => 'Output Control',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);