<?php
$TOC = array (
  0 => 
  array (
    0 => 'ovrimos.examples-basic.php',
    1 => 'Connect to Ovrimos SQL Server and select from a system table',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ovrimos.php',
    1 => 'Ovrimos SQL',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);