<?php
$TOC = array (
  0 => 
  array (
    0 => 'pcntl.example.php',
    1 => 'Process Control Example',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.pcntl.php',
    1 => 'PCNTL',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);