<?php
$TOC = array (
  0 => 
  array (
    0 => 'reference.pcre.pattern.modifiers.php',
    1 => 'Possible modifiers in regex patterns',
  ),
  1 => 
  array (
    0 => 'reference.pcre.pattern.differences.php',
    1 => 'Differences From Perl',
  ),
  2 => 
  array (
    0 => 'reference.pcre.pattern.posix.php',
    1 => 'Differences from POSIX regex',
  ),
  3 => 
  array (
    0 => 'reference.pcre.pattern.syntax.php',
    1 => 'PCRE regex syntax',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.pcre.php',
    1 => 'PCRE',
  ),
  1 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'Text Processing',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);