<?php
$TOC = array (
  0 => 
  array (
    0 => 'ref.pdo-cubrid.php',
    1 => 'CUBRID (PDO)',
  ),
  1 => 
  array (
    0 => 'ref.pdo-dblib.php',
    1 => 'MS SQL Server (PDO)',
  ),
  2 => 
  array (
    0 => 'ref.pdo-firebird.php',
    1 => 'Firebird/Interbase (PDO)',
  ),
  3 => 
  array (
    0 => 'ref.pdo-ibm.php',
    1 => 'IBM (PDO)',
  ),
  4 => 
  array (
    0 => 'ref.pdo-informix.php',
    1 => 'Informix (PDO)',
  ),
  5 => 
  array (
    0 => 'ref.pdo-mysql.php',
    1 => 'MySQL (PDO)',
  ),
  6 => 
  array (
    0 => 'ref.pdo-oci.php',
    1 => 'Oracle (PDO)',
  ),
  7 => 
  array (
    0 => 'ref.pdo-odbc.php',
    1 => 'ODBC and DB2 (PDO)',
  ),
  8 => 
  array (
    0 => 'ref.pdo-pgsql.php',
    1 => 'PostgreSQL (PDO)',
  ),
  9 => 
  array (
    0 => 'ref.pdo-sqlite.php',
    1 => 'SQLite (PDO)',
  ),
  10 => 
  array (
    0 => 'ref.pdo-4d.php',
    1 => '4D (PDO)',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.pdo.php',
    1 => 'PDO',
  ),
  1 => 
  array (
    0 => 'refs.database.abstract.php',
    1 => 'Abstraction Layers',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);