<?php
$TOC = array (
  0 => 
  array (
    0 => 'pdo.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'pdo.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'pdo.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'pdo.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.pdo.php',
    1 => 'PDO',
  ),
  1 => 
  array (
    0 => 'refs.database.abstract.php',
    1 => 'Abstraction Layers',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);