<?php
$TOC = array (
  0 => 
  array (
    0 => 'phar.fileformat.ingredients.php',
    1 => 'Ingredients of all Phar archives, independent of file format',
  ),
  1 => 
  array (
    0 => 'phar.fileformat.stub.php',
    1 => 'Phar file stub',
  ),
  2 => 
  array (
    0 => 'phar.fileformat.comparison.php',
    1 => 'Head-to-head comparison of Phar, Tar and Zip',
  ),
  3 => 
  array (
    0 => 'phar.fileformat.tar.php',
    1 => 'Tar-based phars',
  ),
  4 => 
  array (
    0 => 'phar.fileformat.zip.php',
    1 => 'Zip-based phars',
  ),
  5 => 
  array (
    0 => 'phar.fileformat.phar.php',
    1 => 'Phar File Format',
  ),
  6 => 
  array (
    0 => 'phar.fileformat.flags.php',
    1 => 'Global Phar bitmapped flags',
  ),
  7 => 
  array (
    0 => 'phar.fileformat.manifestfile.php',
    1 => 'Phar manifest file entry definition',
  ),
  8 => 
  array (
    0 => 'phar.fileformat.signature.php',
    1 => 'Phar Signature format',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.phar.php',
    1 => 'Phar',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);