<?php
$TOC = array (
  0 => 
  array (
    0 => 'phar.using.intro.php',
    1 => 'Using Phar Archives: Introduction',
  ),
  1 => 
  array (
    0 => 'phar.using.stream.php',
    1 => 'Using Phar Archives: the phar stream wrapper',
  ),
  2 => 
  array (
    0 => 'phar.using.object.php',
    1 => 'Using Phar Archives: the Phar and PharData class',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.phar.php',
    1 => 'Phar',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);