<?php
$TOC = array (
  0 => 
  array (
    0 => 'printer.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'printer.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'printer.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'printer.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.printer.php',
    1 => 'Printer',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);