<?php
$TOC = array (
  0 => 
  array (
    0 => 'readline.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'readline.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'readline.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'readline.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.readline.php',
    1 => 'Readline',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.cmdline.php',
    1 => 'Command Line Specific Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);