<?php
$TOC = array (
  0 => 
  array (
    0 => 'recode.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'recode.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'recode.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'recode.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.recode.php',
    1 => 'Recode',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);