<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.intl-error-name.php',
    1 => 'intl_error_name',
  ),
  1 => 
  array (
    0 => 'function.intl-get-error-code.php',
    1 => 'intl_get_error_code',
  ),
  2 => 
  array (
    0 => 'function.intl-get-error-message.php',
    1 => 'intl_get_error_message',
  ),
  3 => 
  array (
    0 => 'function.intl-is-failure.php',
    1 => 'intl_is_failure',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.intl.php',
    1 => 'intl',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);