<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.bind-textdomain-codeset.php',
    1 => 'bind_textdomain_codeset',
  ),
  1 => 
  array (
    0 => 'function.bindtextdomain.php',
    1 => 'bindtextdomain',
  ),
  2 => 
  array (
    0 => 'function.dcgettext.php',
    1 => 'dcgettext',
  ),
  3 => 
  array (
    0 => 'function.dcngettext.php',
    1 => 'dcngettext',
  ),
  4 => 
  array (
    0 => 'function.dgettext.php',
    1 => 'dgettext',
  ),
  5 => 
  array (
    0 => 'function.dngettext.php',
    1 => 'dngettext',
  ),
  6 => 
  array (
    0 => 'function.gettext.php',
    1 => 'gettext',
  ),
  7 => 
  array (
    0 => 'function.ngettext.php',
    1 => 'ngettext',
  ),
  8 => 
  array (
    0 => 'function.textdomain.php',
    1 => 'textdomain',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gettext.php',
    1 => 'Gettext',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);