<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.stomp-connect-error.php',
    1 => 'stomp_connect_error',
  ),
  1 => 
  array (
    0 => 'function.stomp-version.php',
    1 => 'stomp_version',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.stomp.php',
    1 => 'Stomp',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);