<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.dotnet-load.php',
    1 => 'dotnet_load',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dotnet.php',
    1 => '.NET',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);