<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swish-construct.php',
    1 => 'Swish::__construct',
  ),
  1 => 
  array (
    0 => 'function.swish-getmetalist.php',
    1 => 'Swish-&gt;getMetaList',
  ),
  2 => 
  array (
    0 => 'function.swish-getpropertylist.php',
    1 => 'Swish-&gt;getPropertyList',
  ),
  3 => 
  array (
    0 => 'function.swish-prepare.php',
    1 => 'Swish-&gt;prepare',
  ),
  4 => 
  array (
    0 => 'function.swish-query.php',
    1 => 'Swish-&gt;query',
  ),
  5 => 
  array (
    0 => 'function.swishresult-getmetalist.php',
    1 => 'SwishResult-&gt;getMetaList',
  ),
  6 => 
  array (
    0 => 'function.swishresult-stem.php',
    1 => 'SwishResult-&gt;stem',
  ),
  7 => 
  array (
    0 => 'function.swishresults-getparsedwords.php',
    1 => 'SwishResults-&gt;getParsedWords',
  ),
  8 => 
  array (
    0 => 'function.swishresults-getremovedstopwords.php',
    1 => 'SwishResults-&gt;getRemovedStopwords',
  ),
  9 => 
  array (
    0 => 'function.swishresults-nextresult.php',
    1 => 'SwishResults-&gt;nextResult',
  ),
  10 => 
  array (
    0 => 'function.swishresults-seekresult.php',
    1 => 'SwishResults-&gt;seekResult',
  ),
  11 => 
  array (
    0 => 'function.swishsearch-execute.php',
    1 => 'SwishSearch-&gt;execute',
  ),
  12 => 
  array (
    0 => 'function.swishsearch-resetlimit.php',
    1 => 'SwishSearch-&gt;resetLimit',
  ),
  13 => 
  array (
    0 => 'function.swishsearch-setlimit.php',
    1 => 'SwishSearch-&gt;setLimit',
  ),
  14 => 
  array (
    0 => 'function.swishsearch-setphrasedelimiter.php',
    1 => 'SwishSearch-&gt;setPhraseDelimiter',
  ),
  15 => 
  array (
    0 => 'function.swishsearch-setsort.php',
    1 => 'SwishSearch-&gt;setSort',
  ),
  16 => 
  array (
    0 => 'function.swishsearch-setstructure.php',
    1 => 'SwishSearch-&gt;setStructure',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.swish.php',
    1 => 'Swish',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);