<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.cal-days-in-month.php',
    1 => 'cal_days_in_month',
  ),
  1 => 
  array (
    0 => 'function.cal-from-jd.php',
    1 => 'cal_from_jd',
  ),
  2 => 
  array (
    0 => 'function.cal-info.php',
    1 => 'cal_info',
  ),
  3 => 
  array (
    0 => 'function.cal-to-jd.php',
    1 => 'cal_to_jd',
  ),
  4 => 
  array (
    0 => 'function.easter-date.php',
    1 => 'easter_date',
  ),
  5 => 
  array (
    0 => 'function.easter-days.php',
    1 => 'easter_days',
  ),
  6 => 
  array (
    0 => 'function.frenchtojd.php',
    1 => 'FrenchToJD',
  ),
  7 => 
  array (
    0 => 'function.gregoriantojd.php',
    1 => 'GregorianToJD',
  ),
  8 => 
  array (
    0 => 'function.jddayofweek.php',
    1 => 'JDDayOfWeek',
  ),
  9 => 
  array (
    0 => 'function.jdmonthname.php',
    1 => 'JDMonthName',
  ),
  10 => 
  array (
    0 => 'function.jdtofrench.php',
    1 => 'JDToFrench',
  ),
  11 => 
  array (
    0 => 'function.jdtogregorian.php',
    1 => 'JDToGregorian',
  ),
  12 => 
  array (
    0 => 'function.jdtojewish.php',
    1 => 'jdtojewish',
  ),
  13 => 
  array (
    0 => 'function.jdtojulian.php',
    1 => 'JDToJulian',
  ),
  14 => 
  array (
    0 => 'function.jdtounix.php',
    1 => 'jdtounix',
  ),
  15 => 
  array (
    0 => 'function.jewishtojd.php',
    1 => 'JewishToJD',
  ),
  16 => 
  array (
    0 => 'function.juliantojd.php',
    1 => 'JulianToJD',
  ),
  17 => 
  array (
    0 => 'function.unixtojd.php',
    1 => 'unixtojd',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.calendar.php',
    1 => 'Calendar',
  ),
  1 => 
  array (
    0 => 'refs.calendar.php',
    1 => 'Date and Time Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);