<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.enchant-broker-describe.php',
    1 => 'enchant_broker_describe',
  ),
  1 => 
  array (
    0 => 'function.enchant-broker-dict-exists.php',
    1 => 'enchant_broker_dict_exists',
  ),
  2 => 
  array (
    0 => 'function.enchant-broker-free-dict.php',
    1 => 'enchant_broker_free_dict',
  ),
  3 => 
  array (
    0 => 'function.enchant-broker-free.php',
    1 => 'enchant_broker_free',
  ),
  4 => 
  array (
    0 => 'function.enchant-broker-get-error.php',
    1 => 'enchant_broker_get_error',
  ),
  5 => 
  array (
    0 => 'function.enchant-broker-init.php',
    1 => 'enchant_broker_init',
  ),
  6 => 
  array (
    0 => 'function.enchant-broker-list-dicts.php',
    1 => 'enchant_broker_list_dicts',
  ),
  7 => 
  array (
    0 => 'function.enchant-broker-request-dict.php',
    1 => 'enchant_broker_request_dict',
  ),
  8 => 
  array (
    0 => 'function.enchant-broker-request-pwl-dict.php',
    1 => 'enchant_broker_request_pwl_dict',
  ),
  9 => 
  array (
    0 => 'function.enchant-broker-set-ordering.php',
    1 => 'enchant_broker_set_ordering',
  ),
  10 => 
  array (
    0 => 'function.enchant-dict-add-to-personal.php',
    1 => 'enchant_dict_add_to_personal',
  ),
  11 => 
  array (
    0 => 'function.enchant-dict-add-to-session.php',
    1 => 'enchant_dict_add_to_session',
  ),
  12 => 
  array (
    0 => 'function.enchant-dict-check.php',
    1 => 'enchant_dict_check',
  ),
  13 => 
  array (
    0 => 'function.enchant-dict-describe.php',
    1 => 'enchant_dict_describe',
  ),
  14 => 
  array (
    0 => 'function.enchant-dict-get-error.php',
    1 => 'enchant_dict_get_error',
  ),
  15 => 
  array (
    0 => 'function.enchant-dict-is-in-session.php',
    1 => 'enchant_dict_is_in_session',
  ),
  16 => 
  array (
    0 => 'function.enchant-dict-quick-check.php',
    1 => 'enchant_dict_quick_check',
  ),
  17 => 
  array (
    0 => 'function.enchant-dict-store-replacement.php',
    1 => 'enchant_dict_store_replacement',
  ),
  18 => 
  array (
    0 => 'function.enchant-dict-suggest.php',
    1 => 'enchant_dict_suggest',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.enchant.php',
    1 => 'Enchant',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);