<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.snmp-get-quick-print.php',
    1 => 'snmp_get_quick_print',
  ),
  1 => 
  array (
    0 => 'function.snmp-get-valueretrieval.php',
    1 => 'snmp_get_valueretrieval',
  ),
  2 => 
  array (
    0 => 'function.snmp-read-mib.php',
    1 => 'snmp_read_mib',
  ),
  3 => 
  array (
    0 => 'function.snmp-set-enum-print.php',
    1 => 'snmp_set_enum_print',
  ),
  4 => 
  array (
    0 => 'function.snmp-set-oid-numeric-print.php',
    1 => 'snmp_set_oid_numeric_print',
  ),
  5 => 
  array (
    0 => 'function.snmp-set-oid-output-format.php',
    1 => 'snmp_set_oid_output_format',
  ),
  6 => 
  array (
    0 => 'function.snmp-set-quick-print.php',
    1 => 'snmp_set_quick_print',
  ),
  7 => 
  array (
    0 => 'function.snmp-set-valueretrieval.php',
    1 => 'snmp_set_valueretrieval',
  ),
  8 => 
  array (
    0 => 'function.snmp2-get.php',
    1 => 'snmp2_get',
  ),
  9 => 
  array (
    0 => 'function.snmp2-getnext.php',
    1 => 'snmp2_getnext',
  ),
  10 => 
  array (
    0 => 'function.snmp2-real-walk.php',
    1 => 'snmp2_real_walk',
  ),
  11 => 
  array (
    0 => 'function.snmp2-set.php',
    1 => 'snmp2_set',
  ),
  12 => 
  array (
    0 => 'function.snmp2-walk.php',
    1 => 'snmp2_walk',
  ),
  13 => 
  array (
    0 => 'function.snmp3-get.php',
    1 => 'snmp3_get',
  ),
  14 => 
  array (
    0 => 'function.snmp3-getnext.php',
    1 => 'snmp3_getnext',
  ),
  15 => 
  array (
    0 => 'function.snmp3-real-walk.php',
    1 => 'snmp3_real_walk',
  ),
  16 => 
  array (
    0 => 'function.snmp3-set.php',
    1 => 'snmp3_set',
  ),
  17 => 
  array (
    0 => 'function.snmp3-walk.php',
    1 => 'snmp3_walk',
  ),
  18 => 
  array (
    0 => 'function.snmpget.php',
    1 => 'snmpget',
  ),
  19 => 
  array (
    0 => 'function.snmpgetnext.php',
    1 => 'snmpgetnext',
  ),
  20 => 
  array (
    0 => 'function.snmprealwalk.php',
    1 => 'snmprealwalk',
  ),
  21 => 
  array (
    0 => 'function.snmpset.php',
    1 => 'snmpset',
  ),
  22 => 
  array (
    0 => 'function.snmpwalk.php',
    1 => 'snmpwalk',
  ),
  23 => 
  array (
    0 => 'function.snmpwalkoid.php',
    1 => 'snmpwalkoid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.snmp.php',
    1 => 'SNMP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);