<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.hw-array2objrec.php',
    1 => 'hw_Array2Objrec',
  ),
  1 => 
  array (
    0 => 'function.hw-changeobject.php',
    1 => 'hw_changeobject',
  ),
  2 => 
  array (
    0 => 'function.hw-children.php',
    1 => 'hw_Children',
  ),
  3 => 
  array (
    0 => 'function.hw-childrenobj.php',
    1 => 'hw_ChildrenObj',
  ),
  4 => 
  array (
    0 => 'function.hw-close.php',
    1 => 'hw_Close',
  ),
  5 => 
  array (
    0 => 'function.hw-connect.php',
    1 => 'hw_Connect',
  ),
  6 => 
  array (
    0 => 'function.hw-connection-info.php',
    1 => 'hw_connection_info',
  ),
  7 => 
  array (
    0 => 'function.hw-cp.php',
    1 => 'hw_cp',
  ),
  8 => 
  array (
    0 => 'function.hw-deleteobject.php',
    1 => 'hw_Deleteobject',
  ),
  9 => 
  array (
    0 => 'function.hw-docbyanchor.php',
    1 => 'hw_DocByAnchor',
  ),
  10 => 
  array (
    0 => 'function.hw-docbyanchorobj.php',
    1 => 'hw_DocByAnchorObj',
  ),
  11 => 
  array (
    0 => 'function.hw-document-attributes.php',
    1 => 'hw_Document_Attributes',
  ),
  12 => 
  array (
    0 => 'function.hw-document-bodytag.php',
    1 => 'hw_Document_BodyTag',
  ),
  13 => 
  array (
    0 => 'function.hw-document-content.php',
    1 => 'hw_Document_Content',
  ),
  14 => 
  array (
    0 => 'function.hw-document-setcontent.php',
    1 => 'hw_Document_SetContent',
  ),
  15 => 
  array (
    0 => 'function.hw-document-size.php',
    1 => 'hw_Document_Size',
  ),
  16 => 
  array (
    0 => 'function.hw-dummy.php',
    1 => 'hw_dummy',
  ),
  17 => 
  array (
    0 => 'function.hw-edittext.php',
    1 => 'hw_EditText',
  ),
  18 => 
  array (
    0 => 'function.hw-error.php',
    1 => 'hw_Error',
  ),
  19 => 
  array (
    0 => 'function.hw-errormsg.php',
    1 => 'hw_ErrorMsg',
  ),
  20 => 
  array (
    0 => 'function.hw-free-document.php',
    1 => 'hw_Free_Document',
  ),
  21 => 
  array (
    0 => 'function.hw-getanchors.php',
    1 => 'hw_GetAnchors',
  ),
  22 => 
  array (
    0 => 'function.hw-getanchorsobj.php',
    1 => 'hw_GetAnchorsObj',
  ),
  23 => 
  array (
    0 => 'function.hw-getandlock.php',
    1 => 'hw_GetAndLock',
  ),
  24 => 
  array (
    0 => 'function.hw-getchildcoll.php',
    1 => 'hw_GetChildColl',
  ),
  25 => 
  array (
    0 => 'function.hw-getchildcollobj.php',
    1 => 'hw_GetChildCollObj',
  ),
  26 => 
  array (
    0 => 'function.hw-getchilddoccoll.php',
    1 => 'hw_GetChildDocColl',
  ),
  27 => 
  array (
    0 => 'function.hw-getchilddoccollobj.php',
    1 => 'hw_GetChildDocCollObj',
  ),
  28 => 
  array (
    0 => 'function.hw-getobject.php',
    1 => 'hw_GetObject',
  ),
  29 => 
  array (
    0 => 'function.hw-getobjectbyquery.php',
    1 => 'hw_GetObjectByQuery',
  ),
  30 => 
  array (
    0 => 'function.hw-getobjectbyquerycoll.php',
    1 => 'hw_GetObjectByQueryColl',
  ),
  31 => 
  array (
    0 => 'function.hw-getobjectbyquerycollobj.php',
    1 => 'hw_GetObjectByQueryCollObj',
  ),
  32 => 
  array (
    0 => 'function.hw-getobjectbyqueryobj.php',
    1 => 'hw_GetObjectByQueryObj',
  ),
  33 => 
  array (
    0 => 'function.hw-getparents.php',
    1 => 'hw_GetParents',
  ),
  34 => 
  array (
    0 => 'function.hw-getparentsobj.php',
    1 => 'hw_GetParentsObj',
  ),
  35 => 
  array (
    0 => 'function.hw-getrellink.php',
    1 => 'hw_getrellink',
  ),
  36 => 
  array (
    0 => 'function.hw-getremote.php',
    1 => 'hw_GetRemote',
  ),
  37 => 
  array (
    0 => 'function.hw-getremotechildren.php',
    1 => 'hw_getremotechildren',
  ),
  38 => 
  array (
    0 => 'function.hw-getsrcbydestobj.php',
    1 => 'hw_GetSrcByDestObj',
  ),
  39 => 
  array (
    0 => 'function.hw-gettext.php',
    1 => 'hw_GetText',
  ),
  40 => 
  array (
    0 => 'function.hw-getusername.php',
    1 => 'hw_getusername',
  ),
  41 => 
  array (
    0 => 'function.hw-identify.php',
    1 => 'hw_Identify',
  ),
  42 => 
  array (
    0 => 'function.hw-incollections.php',
    1 => 'hw_InCollections',
  ),
  43 => 
  array (
    0 => 'function.hw-info.php',
    1 => 'hw_Info',
  ),
  44 => 
  array (
    0 => 'function.hw-inscoll.php',
    1 => 'hw_InsColl',
  ),
  45 => 
  array (
    0 => 'function.hw-insdoc.php',
    1 => 'hw_InsDoc',
  ),
  46 => 
  array (
    0 => 'function.hw-insertanchors.php',
    1 => 'hw_insertanchors',
  ),
  47 => 
  array (
    0 => 'function.hw-insertdocument.php',
    1 => 'hw_InsertDocument',
  ),
  48 => 
  array (
    0 => 'function.hw-insertobject.php',
    1 => 'hw_InsertObject',
  ),
  49 => 
  array (
    0 => 'function.hw-mapid.php',
    1 => 'hw_mapid',
  ),
  50 => 
  array (
    0 => 'function.hw-modifyobject.php',
    1 => 'hw_Modifyobject',
  ),
  51 => 
  array (
    0 => 'function.hw-mv.php',
    1 => 'hw_mv',
  ),
  52 => 
  array (
    0 => 'function.hw-new-document.php',
    1 => 'hw_New_Document',
  ),
  53 => 
  array (
    0 => 'function.hw-objrec2array.php',
    1 => 'hw_objrec2array',
  ),
  54 => 
  array (
    0 => 'function.hw-output-document.php',
    1 => 'hw_Output_Document',
  ),
  55 => 
  array (
    0 => 'function.hw-pconnect.php',
    1 => 'hw_pConnect',
  ),
  56 => 
  array (
    0 => 'function.hw-pipedocument.php',
    1 => 'hw_PipeDocument',
  ),
  57 => 
  array (
    0 => 'function.hw-root.php',
    1 => 'hw_Root',
  ),
  58 => 
  array (
    0 => 'function.hw-setlinkroot.php',
    1 => 'hw_setlinkroot',
  ),
  59 => 
  array (
    0 => 'function.hw-stat.php',
    1 => 'hw_stat',
  ),
  60 => 
  array (
    0 => 'function.hw-unlock.php',
    1 => 'hw_Unlock',
  ),
  61 => 
  array (
    0 => 'function.hw-who.php',
    1 => 'hw_Who',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.hw.php',
    1 => 'Hyperwave',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);