<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.exif-imagetype.php',
    1 => 'exif_imagetype',
  ),
  1 => 
  array (
    0 => 'function.exif-read-data.php',
    1 => 'exif_read_data',
  ),
  2 => 
  array (
    0 => 'function.exif-tagname.php',
    1 => 'exif_tagname',
  ),
  3 => 
  array (
    0 => 'function.exif-thumbnail.php',
    1 => 'exif_thumbnail',
  ),
  4 => 
  array (
    0 => 'function.read-exif-data.php',
    1 => 'read_exif_data',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.exif.php',
    1 => 'Exif',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);