<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.tcpwrap-check.php',
    1 => 'tcpwrap_check',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.tcpwrap.php',
    1 => 'TCP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);