<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.yaz-addinfo.php',
    1 => 'yaz_addinfo',
  ),
  1 => 
  array (
    0 => 'function.yaz-ccl-conf.php',
    1 => 'yaz_ccl_conf',
  ),
  2 => 
  array (
    0 => 'function.yaz-ccl-parse.php',
    1 => 'yaz_ccl_parse',
  ),
  3 => 
  array (
    0 => 'function.yaz-close.php',
    1 => 'yaz_close',
  ),
  4 => 
  array (
    0 => 'function.yaz-connect.php',
    1 => 'yaz_connect',
  ),
  5 => 
  array (
    0 => 'function.yaz-database.php',
    1 => 'yaz_database',
  ),
  6 => 
  array (
    0 => 'function.yaz-element.php',
    1 => 'yaz_element',
  ),
  7 => 
  array (
    0 => 'function.yaz-errno.php',
    1 => 'yaz_errno',
  ),
  8 => 
  array (
    0 => 'function.yaz-error.php',
    1 => 'yaz_error',
  ),
  9 => 
  array (
    0 => 'function.yaz-es-result.php',
    1 => 'yaz_es_result',
  ),
  10 => 
  array (
    0 => 'function.yaz-es.php',
    1 => 'yaz_es',
  ),
  11 => 
  array (
    0 => 'function.yaz-get-option.php',
    1 => 'yaz_get_option',
  ),
  12 => 
  array (
    0 => 'function.yaz-hits.php',
    1 => 'yaz_hits',
  ),
  13 => 
  array (
    0 => 'function.yaz-itemorder.php',
    1 => 'yaz_itemorder',
  ),
  14 => 
  array (
    0 => 'function.yaz-present.php',
    1 => 'yaz_present',
  ),
  15 => 
  array (
    0 => 'function.yaz-range.php',
    1 => 'yaz_range',
  ),
  16 => 
  array (
    0 => 'function.yaz-record.php',
    1 => 'yaz_record',
  ),
  17 => 
  array (
    0 => 'function.yaz-scan-result.php',
    1 => 'yaz_scan_result',
  ),
  18 => 
  array (
    0 => 'function.yaz-scan.php',
    1 => 'yaz_scan',
  ),
  19 => 
  array (
    0 => 'function.yaz-schema.php',
    1 => 'yaz_schema',
  ),
  20 => 
  array (
    0 => 'function.yaz-search.php',
    1 => 'yaz_search',
  ),
  21 => 
  array (
    0 => 'function.yaz-set-option.php',
    1 => 'yaz_set_option',
  ),
  22 => 
  array (
    0 => 'function.yaz-sort.php',
    1 => 'yaz_sort',
  ),
  23 => 
  array (
    0 => 'function.yaz-syntax.php',
    1 => 'yaz_syntax',
  ),
  24 => 
  array (
    0 => 'function.yaz-wait.php',
    1 => 'yaz_wait',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaz.php',
    1 => 'YAZ',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);