<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.aggregate-info.php',
    1 => 'aggregate_info',
  ),
  1 => 
  array (
    0 => 'function.aggregate-methods-by-list.php',
    1 => 'aggregate_methods_by_list',
  ),
  2 => 
  array (
    0 => 'function.aggregate-methods-by-regexp.php',
    1 => 'aggregate_methods_by_regexp',
  ),
  3 => 
  array (
    0 => 'function.aggregate-methods.php',
    1 => 'aggregate_methods',
  ),
  4 => 
  array (
    0 => 'function.aggregate-properties-by-list.php',
    1 => 'aggregate_properties_by_list',
  ),
  5 => 
  array (
    0 => 'function.aggregate-properties-by-regexp.php',
    1 => 'aggregate_properties_by_regexp',
  ),
  6 => 
  array (
    0 => 'function.aggregate-properties.php',
    1 => 'aggregate_properties',
  ),
  7 => 
  array (
    0 => 'function.aggregate.php',
    1 => 'aggregate',
  ),
  8 => 
  array (
    0 => 'function.aggregation-info.php',
    1 => 'aggregation_info',
  ),
  9 => 
  array (
    0 => 'function.deaggregate.php',
    1 => 'deaggregate',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.objaggregation.php',
    1 => 'Object Aggregation',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);