<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.is-soap-fault.php',
    1 => 'is_soap_fault',
  ),
  1 => 
  array (
    0 => 'function.use-soap-error-handler.php',
    1 => 'use_soap_error_handler',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.soap.php',
    1 => 'SOAP',
  ),
  1 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);