<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.pspell-add-to-personal.php',
    1 => 'pspell_add_to_personal',
  ),
  1 => 
  array (
    0 => 'function.pspell-add-to-session.php',
    1 => 'pspell_add_to_session',
  ),
  2 => 
  array (
    0 => 'function.pspell-check.php',
    1 => 'pspell_check',
  ),
  3 => 
  array (
    0 => 'function.pspell-clear-session.php',
    1 => 'pspell_clear_session',
  ),
  4 => 
  array (
    0 => 'function.pspell-config-create.php',
    1 => 'pspell_config_create',
  ),
  5 => 
  array (
    0 => 'function.pspell-config-data-dir.php',
    1 => 'pspell_config_data_dir',
  ),
  6 => 
  array (
    0 => 'function.pspell-config-dict-dir.php',
    1 => 'pspell_config_dict_dir',
  ),
  7 => 
  array (
    0 => 'function.pspell-config-ignore.php',
    1 => 'pspell_config_ignore',
  ),
  8 => 
  array (
    0 => 'function.pspell-config-mode.php',
    1 => 'pspell_config_mode',
  ),
  9 => 
  array (
    0 => 'function.pspell-config-personal.php',
    1 => 'pspell_config_personal',
  ),
  10 => 
  array (
    0 => 'function.pspell-config-repl.php',
    1 => 'pspell_config_repl',
  ),
  11 => 
  array (
    0 => 'function.pspell-config-runtogether.php',
    1 => 'pspell_config_runtogether',
  ),
  12 => 
  array (
    0 => 'function.pspell-config-save-repl.php',
    1 => 'pspell_config_save_repl',
  ),
  13 => 
  array (
    0 => 'function.pspell-new-config.php',
    1 => 'pspell_new_config',
  ),
  14 => 
  array (
    0 => 'function.pspell-new-personal.php',
    1 => 'pspell_new_personal',
  ),
  15 => 
  array (
    0 => 'function.pspell-new.php',
    1 => 'pspell_new',
  ),
  16 => 
  array (
    0 => 'function.pspell-save-wordlist.php',
    1 => 'pspell_save_wordlist',
  ),
  17 => 
  array (
    0 => 'function.pspell-store-replacement.php',
    1 => 'pspell_store_replacement',
  ),
  18 => 
  array (
    0 => 'function.pspell-suggest.php',
    1 => 'pspell_suggest',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.pspell.php',
    1 => 'Pspell',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);