<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.array-change-key-case.php',
    1 => 'array_change_key_case',
  ),
  1 => 
  array (
    0 => 'function.array-chunk.php',
    1 => 'array_chunk',
  ),
  2 => 
  array (
    0 => 'function.array-combine.php',
    1 => 'array_combine',
  ),
  3 => 
  array (
    0 => 'function.array-count-values.php',
    1 => 'array_count_values',
  ),
  4 => 
  array (
    0 => 'function.array-diff-assoc.php',
    1 => 'array_diff_assoc',
  ),
  5 => 
  array (
    0 => 'function.array-diff-key.php',
    1 => 'array_diff_key',
  ),
  6 => 
  array (
    0 => 'function.array-diff-uassoc.php',
    1 => 'array_diff_uassoc',
  ),
  7 => 
  array (
    0 => 'function.array-diff-ukey.php',
    1 => 'array_diff_ukey',
  ),
  8 => 
  array (
    0 => 'function.array-diff.php',
    1 => 'array_diff',
  ),
  9 => 
  array (
    0 => 'function.array-fill-keys.php',
    1 => 'array_fill_keys',
  ),
  10 => 
  array (
    0 => 'function.array-fill.php',
    1 => 'array_fill',
  ),
  11 => 
  array (
    0 => 'function.array-filter.php',
    1 => 'array_filter',
  ),
  12 => 
  array (
    0 => 'function.array-flip.php',
    1 => 'array_flip',
  ),
  13 => 
  array (
    0 => 'function.array-intersect-assoc.php',
    1 => 'array_intersect_assoc',
  ),
  14 => 
  array (
    0 => 'function.array-intersect-key.php',
    1 => 'array_intersect_key',
  ),
  15 => 
  array (
    0 => 'function.array-intersect-uassoc.php',
    1 => 'array_intersect_uassoc',
  ),
  16 => 
  array (
    0 => 'function.array-intersect-ukey.php',
    1 => 'array_intersect_ukey',
  ),
  17 => 
  array (
    0 => 'function.array-intersect.php',
    1 => 'array_intersect',
  ),
  18 => 
  array (
    0 => 'function.array-key-exists.php',
    1 => 'array_key_exists',
  ),
  19 => 
  array (
    0 => 'function.array-keys.php',
    1 => 'array_keys',
  ),
  20 => 
  array (
    0 => 'function.array-map.php',
    1 => 'array_map',
  ),
  21 => 
  array (
    0 => 'function.array-merge-recursive.php',
    1 => 'array_merge_recursive',
  ),
  22 => 
  array (
    0 => 'function.array-merge.php',
    1 => 'array_merge',
  ),
  23 => 
  array (
    0 => 'function.array-multisort.php',
    1 => 'array_multisort',
  ),
  24 => 
  array (
    0 => 'function.array-pad.php',
    1 => 'array_pad',
  ),
  25 => 
  array (
    0 => 'function.array-pop.php',
    1 => 'array_pop',
  ),
  26 => 
  array (
    0 => 'function.array-product.php',
    1 => 'array_product',
  ),
  27 => 
  array (
    0 => 'function.array-push.php',
    1 => 'array_push',
  ),
  28 => 
  array (
    0 => 'function.array-rand.php',
    1 => 'array_rand',
  ),
  29 => 
  array (
    0 => 'function.array-reduce.php',
    1 => 'array_reduce',
  ),
  30 => 
  array (
    0 => 'function.array-replace-recursive.php',
    1 => 'array_replace_recursive',
  ),
  31 => 
  array (
    0 => 'function.array-replace.php',
    1 => 'array_replace',
  ),
  32 => 
  array (
    0 => 'function.array-reverse.php',
    1 => 'array_reverse',
  ),
  33 => 
  array (
    0 => 'function.array-search.php',
    1 => 'array_search',
  ),
  34 => 
  array (
    0 => 'function.array-shift.php',
    1 => 'array_shift',
  ),
  35 => 
  array (
    0 => 'function.array-slice.php',
    1 => 'array_slice',
  ),
  36 => 
  array (
    0 => 'function.array-splice.php',
    1 => 'array_splice',
  ),
  37 => 
  array (
    0 => 'function.array-sum.php',
    1 => 'array_sum',
  ),
  38 => 
  array (
    0 => 'function.array-udiff-assoc.php',
    1 => 'array_udiff_assoc',
  ),
  39 => 
  array (
    0 => 'function.array-udiff-uassoc.php',
    1 => 'array_udiff_uassoc',
  ),
  40 => 
  array (
    0 => 'function.array-udiff.php',
    1 => 'array_udiff',
  ),
  41 => 
  array (
    0 => 'function.array-uintersect-assoc.php',
    1 => 'array_uintersect_assoc',
  ),
  42 => 
  array (
    0 => 'function.array-uintersect-uassoc.php',
    1 => 'array_uintersect_uassoc',
  ),
  43 => 
  array (
    0 => 'function.array-uintersect.php',
    1 => 'array_uintersect',
  ),
  44 => 
  array (
    0 => 'function.array-unique.php',
    1 => 'array_unique',
  ),
  45 => 
  array (
    0 => 'function.array-unshift.php',
    1 => 'array_unshift',
  ),
  46 => 
  array (
    0 => 'function.array-values.php',
    1 => 'array_values',
  ),
  47 => 
  array (
    0 => 'function.array-walk-recursive.php',
    1 => 'array_walk_recursive',
  ),
  48 => 
  array (
    0 => 'function.array-walk.php',
    1 => 'array_walk',
  ),
  49 => 
  array (
    0 => 'function.array.php',
    1 => 'array',
  ),
  50 => 
  array (
    0 => 'function.arsort.php',
    1 => 'arsort',
  ),
  51 => 
  array (
    0 => 'function.asort.php',
    1 => 'asort',
  ),
  52 => 
  array (
    0 => 'function.compact.php',
    1 => 'compact',
  ),
  53 => 
  array (
    0 => 'function.count.php',
    1 => 'count',
  ),
  54 => 
  array (
    0 => 'function.current.php',
    1 => 'current',
  ),
  55 => 
  array (
    0 => 'function.each.php',
    1 => 'each',
  ),
  56 => 
  array (
    0 => 'function.end.php',
    1 => 'end',
  ),
  57 => 
  array (
    0 => 'function.extract.php',
    1 => 'extract',
  ),
  58 => 
  array (
    0 => 'function.in-array.php',
    1 => 'in_array',
  ),
  59 => 
  array (
    0 => 'function.key.php',
    1 => 'key',
  ),
  60 => 
  array (
    0 => 'function.krsort.php',
    1 => 'krsort',
  ),
  61 => 
  array (
    0 => 'function.ksort.php',
    1 => 'ksort',
  ),
  62 => 
  array (
    0 => 'function.list.php',
    1 => 'list',
  ),
  63 => 
  array (
    0 => 'function.natcasesort.php',
    1 => 'natcasesort',
  ),
  64 => 
  array (
    0 => 'function.natsort.php',
    1 => 'natsort',
  ),
  65 => 
  array (
    0 => 'function.next.php',
    1 => 'next',
  ),
  66 => 
  array (
    0 => 'function.pos.php',
    1 => 'pos',
  ),
  67 => 
  array (
    0 => 'function.prev.php',
    1 => 'prev',
  ),
  68 => 
  array (
    0 => 'function.range.php',
    1 => 'range',
  ),
  69 => 
  array (
    0 => 'function.reset.php',
    1 => 'reset',
  ),
  70 => 
  array (
    0 => 'function.rsort.php',
    1 => 'rsort',
  ),
  71 => 
  array (
    0 => 'function.shuffle.php',
    1 => 'shuffle',
  ),
  72 => 
  array (
    0 => 'function.sizeof.php',
    1 => 'sizeof',
  ),
  73 => 
  array (
    0 => 'function.sort.php',
    1 => 'sort',
  ),
  74 => 
  array (
    0 => 'function.uasort.php',
    1 => 'uasort',
  ),
  75 => 
  array (
    0 => 'function.uksort.php',
    1 => 'uksort',
  ),
  76 => 
  array (
    0 => 'function.usort.php',
    1 => 'usort',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.array.php',
    1 => 'Arrays',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);