<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.zip-close.php',
    1 => 'zip_close',
  ),
  1 => 
  array (
    0 => 'function.zip-entry-close.php',
    1 => 'zip_entry_close',
  ),
  2 => 
  array (
    0 => 'function.zip-entry-compressedsize.php',
    1 => 'zip_entry_compressedsize',
  ),
  3 => 
  array (
    0 => 'function.zip-entry-compressionmethod.php',
    1 => 'zip_entry_compressionmethod',
  ),
  4 => 
  array (
    0 => 'function.zip-entry-filesize.php',
    1 => 'zip_entry_filesize',
  ),
  5 => 
  array (
    0 => 'function.zip-entry-name.php',
    1 => 'zip_entry_name',
  ),
  6 => 
  array (
    0 => 'function.zip-entry-open.php',
    1 => 'zip_entry_open',
  ),
  7 => 
  array (
    0 => 'function.zip-entry-read.php',
    1 => 'zip_entry_read',
  ),
  8 => 
  array (
    0 => 'function.zip-open.php',
    1 => 'zip_open',
  ),
  9 => 
  array (
    0 => 'function.zip-read.php',
    1 => 'zip_read',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.zip.php',
    1 => 'Zip',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);