<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.mhash-count.php',
    1 => 'mhash_count',
  ),
  1 => 
  array (
    0 => 'function.mhash-get-block-size.php',
    1 => 'mhash_get_block_size',
  ),
  2 => 
  array (
    0 => 'function.mhash-get-hash-name.php',
    1 => 'mhash_get_hash_name',
  ),
  3 => 
  array (
    0 => 'function.mhash-keygen-s2k.php',
    1 => 'mhash_keygen_s2k',
  ),
  4 => 
  array (
    0 => 'function.mhash.php',
    1 => 'mhash',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mhash.php',
    1 => 'Mhash',
  ),
  1 => 
  array (
    0 => 'refs.crypto.php',
    1 => 'Cryptography Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);