<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ftok.php',
    1 => 'ftok',
  ),
  1 => 
  array (
    0 => 'function.msg-get-queue.php',
    1 => 'msg_get_queue',
  ),
  2 => 
  array (
    0 => 'function.msg-queue-exists.php',
    1 => 'msg_queue_exists',
  ),
  3 => 
  array (
    0 => 'function.msg-receive.php',
    1 => 'msg_receive',
  ),
  4 => 
  array (
    0 => 'function.msg-remove-queue.php',
    1 => 'msg_remove_queue',
  ),
  5 => 
  array (
    0 => 'function.msg-send.php',
    1 => 'msg_send',
  ),
  6 => 
  array (
    0 => 'function.msg-set-queue.php',
    1 => 'msg_set_queue',
  ),
  7 => 
  array (
    0 => 'function.msg-stat-queue.php',
    1 => 'msg_stat_queue',
  ),
  8 => 
  array (
    0 => 'function.sem-acquire.php',
    1 => 'sem_acquire',
  ),
  9 => 
  array (
    0 => 'function.sem-get.php',
    1 => 'sem_get',
  ),
  10 => 
  array (
    0 => 'function.sem-release.php',
    1 => 'sem_release',
  ),
  11 => 
  array (
    0 => 'function.sem-remove.php',
    1 => 'sem_remove',
  ),
  12 => 
  array (
    0 => 'function.shm-attach.php',
    1 => 'shm_attach',
  ),
  13 => 
  array (
    0 => 'function.shm-detach.php',
    1 => 'shm_detach',
  ),
  14 => 
  array (
    0 => 'function.shm-get-var.php',
    1 => 'shm_get_var',
  ),
  15 => 
  array (
    0 => 'function.shm-has-var.php',
    1 => 'shm_has_var',
  ),
  16 => 
  array (
    0 => 'function.shm-put-var.php',
    1 => 'shm_put_var',
  ),
  17 => 
  array (
    0 => 'function.shm-remove-var.php',
    1 => 'shm_remove_var',
  ),
  18 => 
  array (
    0 => 'function.shm-remove.php',
    1 => 'shm_remove',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sem.php',
    1 => 'Semaphore',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);