<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.pg-affected-rows.php',
    1 => 'pg_affected_rows',
  ),
  1 => 
  array (
    0 => 'function.pg-cancel-query.php',
    1 => 'pg_cancel_query',
  ),
  2 => 
  array (
    0 => 'function.pg-client-encoding.php',
    1 => 'pg_client_encoding',
  ),
  3 => 
  array (
    0 => 'function.pg-close.php',
    1 => 'pg_close',
  ),
  4 => 
  array (
    0 => 'function.pg-connect.php',
    1 => 'pg_connect',
  ),
  5 => 
  array (
    0 => 'function.pg-connection-busy.php',
    1 => 'pg_connection_busy',
  ),
  6 => 
  array (
    0 => 'function.pg-connection-reset.php',
    1 => 'pg_connection_reset',
  ),
  7 => 
  array (
    0 => 'function.pg-connection-status.php',
    1 => 'pg_connection_status',
  ),
  8 => 
  array (
    0 => 'function.pg-convert.php',
    1 => 'pg_convert',
  ),
  9 => 
  array (
    0 => 'function.pg-copy-from.php',
    1 => 'pg_copy_from',
  ),
  10 => 
  array (
    0 => 'function.pg-copy-to.php',
    1 => 'pg_copy_to',
  ),
  11 => 
  array (
    0 => 'function.pg-dbname.php',
    1 => 'pg_dbname',
  ),
  12 => 
  array (
    0 => 'function.pg-delete.php',
    1 => 'pg_delete',
  ),
  13 => 
  array (
    0 => 'function.pg-end-copy.php',
    1 => 'pg_end_copy',
  ),
  14 => 
  array (
    0 => 'function.pg-escape-bytea.php',
    1 => 'pg_escape_bytea',
  ),
  15 => 
  array (
    0 => 'function.pg-escape-string.php',
    1 => 'pg_escape_string',
  ),
  16 => 
  array (
    0 => 'function.pg-execute.php',
    1 => 'pg_execute',
  ),
  17 => 
  array (
    0 => 'function.pg-fetch-all-columns.php',
    1 => 'pg_fetch_all_columns',
  ),
  18 => 
  array (
    0 => 'function.pg-fetch-all.php',
    1 => 'pg_fetch_all',
  ),
  19 => 
  array (
    0 => 'function.pg-fetch-array.php',
    1 => 'pg_fetch_array',
  ),
  20 => 
  array (
    0 => 'function.pg-fetch-assoc.php',
    1 => 'pg_fetch_assoc',
  ),
  21 => 
  array (
    0 => 'function.pg-fetch-object.php',
    1 => 'pg_fetch_object',
  ),
  22 => 
  array (
    0 => 'function.pg-fetch-result.php',
    1 => 'pg_fetch_result',
  ),
  23 => 
  array (
    0 => 'function.pg-fetch-row.php',
    1 => 'pg_fetch_row',
  ),
  24 => 
  array (
    0 => 'function.pg-field-is-null.php',
    1 => 'pg_field_is_null',
  ),
  25 => 
  array (
    0 => 'function.pg-field-name.php',
    1 => 'pg_field_name',
  ),
  26 => 
  array (
    0 => 'function.pg-field-num.php',
    1 => 'pg_field_num',
  ),
  27 => 
  array (
    0 => 'function.pg-field-prtlen.php',
    1 => 'pg_field_prtlen',
  ),
  28 => 
  array (
    0 => 'function.pg-field-size.php',
    1 => 'pg_field_size',
  ),
  29 => 
  array (
    0 => 'function.pg-field-table.php',
    1 => 'pg_field_table',
  ),
  30 => 
  array (
    0 => 'function.pg-field-type-oid.php',
    1 => 'pg_field_type_oid',
  ),
  31 => 
  array (
    0 => 'function.pg-field-type.php',
    1 => 'pg_field_type',
  ),
  32 => 
  array (
    0 => 'function.pg-free-result.php',
    1 => 'pg_free_result',
  ),
  33 => 
  array (
    0 => 'function.pg-get-notify.php',
    1 => 'pg_get_notify',
  ),
  34 => 
  array (
    0 => 'function.pg-get-pid.php',
    1 => 'pg_get_pid',
  ),
  35 => 
  array (
    0 => 'function.pg-get-result.php',
    1 => 'pg_get_result',
  ),
  36 => 
  array (
    0 => 'function.pg-host.php',
    1 => 'pg_host',
  ),
  37 => 
  array (
    0 => 'function.pg-insert.php',
    1 => 'pg_insert',
  ),
  38 => 
  array (
    0 => 'function.pg-last-error.php',
    1 => 'pg_last_error',
  ),
  39 => 
  array (
    0 => 'function.pg-last-notice.php',
    1 => 'pg_last_notice',
  ),
  40 => 
  array (
    0 => 'function.pg-last-oid.php',
    1 => 'pg_last_oid',
  ),
  41 => 
  array (
    0 => 'function.pg-lo-close.php',
    1 => 'pg_lo_close',
  ),
  42 => 
  array (
    0 => 'function.pg-lo-create.php',
    1 => 'pg_lo_create',
  ),
  43 => 
  array (
    0 => 'function.pg-lo-export.php',
    1 => 'pg_lo_export',
  ),
  44 => 
  array (
    0 => 'function.pg-lo-import.php',
    1 => 'pg_lo_import',
  ),
  45 => 
  array (
    0 => 'function.pg-lo-open.php',
    1 => 'pg_lo_open',
  ),
  46 => 
  array (
    0 => 'function.pg-lo-read-all.php',
    1 => 'pg_lo_read_all',
  ),
  47 => 
  array (
    0 => 'function.pg-lo-read.php',
    1 => 'pg_lo_read',
  ),
  48 => 
  array (
    0 => 'function.pg-lo-seek.php',
    1 => 'pg_lo_seek',
  ),
  49 => 
  array (
    0 => 'function.pg-lo-tell.php',
    1 => 'pg_lo_tell',
  ),
  50 => 
  array (
    0 => 'function.pg-lo-unlink.php',
    1 => 'pg_lo_unlink',
  ),
  51 => 
  array (
    0 => 'function.pg-lo-write.php',
    1 => 'pg_lo_write',
  ),
  52 => 
  array (
    0 => 'function.pg-meta-data.php',
    1 => 'pg_meta_data',
  ),
  53 => 
  array (
    0 => 'function.pg-num-fields.php',
    1 => 'pg_num_fields',
  ),
  54 => 
  array (
    0 => 'function.pg-num-rows.php',
    1 => 'pg_num_rows',
  ),
  55 => 
  array (
    0 => 'function.pg-options.php',
    1 => 'pg_options',
  ),
  56 => 
  array (
    0 => 'function.pg-parameter-status.php',
    1 => 'pg_parameter_status',
  ),
  57 => 
  array (
    0 => 'function.pg-pconnect.php',
    1 => 'pg_pconnect',
  ),
  58 => 
  array (
    0 => 'function.pg-ping.php',
    1 => 'pg_ping',
  ),
  59 => 
  array (
    0 => 'function.pg-port.php',
    1 => 'pg_port',
  ),
  60 => 
  array (
    0 => 'function.pg-prepare.php',
    1 => 'pg_prepare',
  ),
  61 => 
  array (
    0 => 'function.pg-put-line.php',
    1 => 'pg_put_line',
  ),
  62 => 
  array (
    0 => 'function.pg-query-params.php',
    1 => 'pg_query_params',
  ),
  63 => 
  array (
    0 => 'function.pg-query.php',
    1 => 'pg_query',
  ),
  64 => 
  array (
    0 => 'function.pg-result-error-field.php',
    1 => 'pg_result_error_field',
  ),
  65 => 
  array (
    0 => 'function.pg-result-error.php',
    1 => 'pg_result_error',
  ),
  66 => 
  array (
    0 => 'function.pg-result-seek.php',
    1 => 'pg_result_seek',
  ),
  67 => 
  array (
    0 => 'function.pg-result-status.php',
    1 => 'pg_result_status',
  ),
  68 => 
  array (
    0 => 'function.pg-select.php',
    1 => 'pg_select',
  ),
  69 => 
  array (
    0 => 'function.pg-send-execute.php',
    1 => 'pg_send_execute',
  ),
  70 => 
  array (
    0 => 'function.pg-send-prepare.php',
    1 => 'pg_send_prepare',
  ),
  71 => 
  array (
    0 => 'function.pg-send-query-params.php',
    1 => 'pg_send_query_params',
  ),
  72 => 
  array (
    0 => 'function.pg-send-query.php',
    1 => 'pg_send_query',
  ),
  73 => 
  array (
    0 => 'function.pg-set-client-encoding.php',
    1 => 'pg_set_client_encoding',
  ),
  74 => 
  array (
    0 => 'function.pg-set-error-verbosity.php',
    1 => 'pg_set_error_verbosity',
  ),
  75 => 
  array (
    0 => 'function.pg-trace.php',
    1 => 'pg_trace',
  ),
  76 => 
  array (
    0 => 'function.pg-transaction-status.php',
    1 => 'pg_transaction_status',
  ),
  77 => 
  array (
    0 => 'function.pg-tty.php',
    1 => 'pg_tty',
  ),
  78 => 
  array (
    0 => 'function.pg-unescape-bytea.php',
    1 => 'pg_unescape_bytea',
  ),
  79 => 
  array (
    0 => 'function.pg-untrace.php',
    1 => 'pg_untrace',
  ),
  80 => 
  array (
    0 => 'function.pg-update.php',
    1 => 'pg_update',
  ),
  81 => 
  array (
    0 => 'function.pg-version.php',
    1 => 'pg_version',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.pgsql.php',
    1 => 'PostgreSQL',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);