<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.hwapi-attribute-key.php',
    1 => 'hw_api_attribute-&gt;key',
  ),
  1 => 
  array (
    0 => 'function.hwapi-attribute-langdepvalue.php',
    1 => 'hw_api_attribute-&gt;langdepvalue',
  ),
  2 => 
  array (
    0 => 'function.hwapi-attribute-value.php',
    1 => 'hw_api_attribute-&gt;value',
  ),
  3 => 
  array (
    0 => 'function.hwapi-attribute-values.php',
    1 => 'hw_api_attribute-&gt;values',
  ),
  4 => 
  array (
    0 => 'function.hwapi-attribute.php',
    1 => 'hw_api_attribute',
  ),
  5 => 
  array (
    0 => 'function.hwapi-checkin.php',
    1 => 'hw_api-&gt;checkin',
  ),
  6 => 
  array (
    0 => 'function.hwapi-checkout.php',
    1 => 'hw_api-&gt;checkout',
  ),
  7 => 
  array (
    0 => 'function.hwapi-children.php',
    1 => 'hw_api-&gt;children',
  ),
  8 => 
  array (
    0 => 'function.hwapi-content-mimetype.php',
    1 => 'hw_api_content-&gt;mimetype',
  ),
  9 => 
  array (
    0 => 'function.hwapi-content-read.php',
    1 => 'hw_api_content-&gt;read',
  ),
  10 => 
  array (
    0 => 'function.hwapi-content.php',
    1 => 'hw_api-&gt;content',
  ),
  11 => 
  array (
    0 => 'function.hwapi-copy.php',
    1 => 'hw_api-&gt;copy',
  ),
  12 => 
  array (
    0 => 'function.hwapi-dbstat.php',
    1 => 'hw_api-&gt;dbstat',
  ),
  13 => 
  array (
    0 => 'function.hwapi-dcstat.php',
    1 => 'hw_api-&gt;dcstat',
  ),
  14 => 
  array (
    0 => 'function.hwapi-dstanchors.php',
    1 => 'hw_api-&gt;dstanchors',
  ),
  15 => 
  array (
    0 => 'function.hwapi-dstofsrcanchor.php',
    1 => 'hw_api-&gt;dstofsrcanchor',
  ),
  16 => 
  array (
    0 => 'function.hwapi-error-count.php',
    1 => 'hw_api_error-&gt;count',
  ),
  17 => 
  array (
    0 => 'function.hwapi-error-reason.php',
    1 => 'hw_api_error-&gt;reason',
  ),
  18 => 
  array (
    0 => 'function.hwapi-find.php',
    1 => 'hw_api-&gt;find',
  ),
  19 => 
  array (
    0 => 'function.hwapi-ftstat.php',
    1 => 'hw_api-&gt;ftstat',
  ),
  20 => 
  array (
    0 => 'function.hwapi-hgcsp.php',
    1 => 'hwapi_hgcsp',
  ),
  21 => 
  array (
    0 => 'function.hwapi-hwstat.php',
    1 => 'hw_api-&gt;hwstat',
  ),
  22 => 
  array (
    0 => 'function.hwapi-identify.php',
    1 => 'hw_api-&gt;identify',
  ),
  23 => 
  array (
    0 => 'function.hwapi-info.php',
    1 => 'hw_api-&gt;info',
  ),
  24 => 
  array (
    0 => 'function.hwapi-insert.php',
    1 => 'hw_api-&gt;insert',
  ),
  25 => 
  array (
    0 => 'function.hwapi-insertanchor.php',
    1 => 'hw_api-&gt;insertanchor',
  ),
  26 => 
  array (
    0 => 'function.hwapi-insertcollection.php',
    1 => 'hw_api-&gt;insertcollection',
  ),
  27 => 
  array (
    0 => 'function.hwapi-insertdocument.php',
    1 => 'hw_api-&gt;insertdocument',
  ),
  28 => 
  array (
    0 => 'function.hwapi-link.php',
    1 => 'hw_api-&gt;link',
  ),
  29 => 
  array (
    0 => 'function.hwapi-lock.php',
    1 => 'hw_api-&gt;lock',
  ),
  30 => 
  array (
    0 => 'function.hwapi-move.php',
    1 => 'hw_api-&gt;move',
  ),
  31 => 
  array (
    0 => 'function.hwapi-new-content.php',
    1 => 'hw_api_content',
  ),
  32 => 
  array (
    0 => 'function.hwapi-object-assign.php',
    1 => 'hw_api_object-&gt;assign',
  ),
  33 => 
  array (
    0 => 'function.hwapi-object-attreditable.php',
    1 => 'hw_api_object-&gt;attreditable',
  ),
  34 => 
  array (
    0 => 'function.hwapi-object-count.php',
    1 => 'hw_api_object-&gt;count',
  ),
  35 => 
  array (
    0 => 'function.hwapi-object-insert.php',
    1 => 'hw_api_object-&gt;insert',
  ),
  36 => 
  array (
    0 => 'function.hwapi-object-new.php',
    1 => 'hw_api_object',
  ),
  37 => 
  array (
    0 => 'function.hwapi-object-remove.php',
    1 => 'hw_api_object-&gt;remove',
  ),
  38 => 
  array (
    0 => 'function.hwapi-object-title.php',
    1 => 'hw_api_object-&gt;title',
  ),
  39 => 
  array (
    0 => 'function.hwapi-object-value.php',
    1 => 'hw_api_object-&gt;value',
  ),
  40 => 
  array (
    0 => 'function.hwapi-object.php',
    1 => 'hw_api-&gt;object',
  ),
  41 => 
  array (
    0 => 'function.hwapi-objectbyanchor.php',
    1 => 'hw_api-&gt;objectbyanchor',
  ),
  42 => 
  array (
    0 => 'function.hwapi-parents.php',
    1 => 'hw_api-&gt;parents',
  ),
  43 => 
  array (
    0 => 'function.hwapi-reason-description.php',
    1 => 'hw_api_reason-&gt;description',
  ),
  44 => 
  array (
    0 => 'function.hwapi-reason-type.php',
    1 => 'hw_api_reason-&gt;type',
  ),
  45 => 
  array (
    0 => 'function.hwapi-remove.php',
    1 => 'hw_api-&gt;remove',
  ),
  46 => 
  array (
    0 => 'function.hwapi-replace.php',
    1 => 'hw_api-&gt;replace',
  ),
  47 => 
  array (
    0 => 'function.hwapi-setcommittedversion.php',
    1 => 'hw_api-&gt;setcommittedversion',
  ),
  48 => 
  array (
    0 => 'function.hwapi-srcanchors.php',
    1 => 'hw_api-&gt;srcanchors',
  ),
  49 => 
  array (
    0 => 'function.hwapi-srcsofdst.php',
    1 => 'hw_api-&gt;srcsofdst',
  ),
  50 => 
  array (
    0 => 'function.hwapi-unlock.php',
    1 => 'hw_api-&gt;unlock',
  ),
  51 => 
  array (
    0 => 'function.hwapi-user.php',
    1 => 'hw_api-&gt;user',
  ),
  52 => 
  array (
    0 => 'function.hwapi-userlist.php',
    1 => 'hw_api-&gt;userlist',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.hwapi.php',
    1 => 'Hyperwave API',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);