<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.mssql-bind.php',
    1 => 'mssql_bind',
  ),
  1 => 
  array (
    0 => 'function.mssql-close.php',
    1 => 'mssql_close',
  ),
  2 => 
  array (
    0 => 'function.mssql-connect.php',
    1 => 'mssql_connect',
  ),
  3 => 
  array (
    0 => 'function.mssql-data-seek.php',
    1 => 'mssql_data_seek',
  ),
  4 => 
  array (
    0 => 'function.mssql-execute.php',
    1 => 'mssql_execute',
  ),
  5 => 
  array (
    0 => 'function.mssql-fetch-array.php',
    1 => 'mssql_fetch_array',
  ),
  6 => 
  array (
    0 => 'function.mssql-fetch-assoc.php',
    1 => 'mssql_fetch_assoc',
  ),
  7 => 
  array (
    0 => 'function.mssql-fetch-batch.php',
    1 => 'mssql_fetch_batch',
  ),
  8 => 
  array (
    0 => 'function.mssql-fetch-field.php',
    1 => 'mssql_fetch_field',
  ),
  9 => 
  array (
    0 => 'function.mssql-fetch-object.php',
    1 => 'mssql_fetch_object',
  ),
  10 => 
  array (
    0 => 'function.mssql-fetch-row.php',
    1 => 'mssql_fetch_row',
  ),
  11 => 
  array (
    0 => 'function.mssql-field-length.php',
    1 => 'mssql_field_length',
  ),
  12 => 
  array (
    0 => 'function.mssql-field-name.php',
    1 => 'mssql_field_name',
  ),
  13 => 
  array (
    0 => 'function.mssql-field-seek.php',
    1 => 'mssql_field_seek',
  ),
  14 => 
  array (
    0 => 'function.mssql-field-type.php',
    1 => 'mssql_field_type',
  ),
  15 => 
  array (
    0 => 'function.mssql-free-result.php',
    1 => 'mssql_free_result',
  ),
  16 => 
  array (
    0 => 'function.mssql-free-statement.php',
    1 => 'mssql_free_statement',
  ),
  17 => 
  array (
    0 => 'function.mssql-get-last-message.php',
    1 => 'mssql_get_last_message',
  ),
  18 => 
  array (
    0 => 'function.mssql-guid-string.php',
    1 => 'mssql_guid_string',
  ),
  19 => 
  array (
    0 => 'function.mssql-init.php',
    1 => 'mssql_init',
  ),
  20 => 
  array (
    0 => 'function.mssql-min-error-severity.php',
    1 => 'mssql_min_error_severity',
  ),
  21 => 
  array (
    0 => 'function.mssql-min-message-severity.php',
    1 => 'mssql_min_message_severity',
  ),
  22 => 
  array (
    0 => 'function.mssql-next-result.php',
    1 => 'mssql_next_result',
  ),
  23 => 
  array (
    0 => 'function.mssql-num-fields.php',
    1 => 'mssql_num_fields',
  ),
  24 => 
  array (
    0 => 'function.mssql-num-rows.php',
    1 => 'mssql_num_rows',
  ),
  25 => 
  array (
    0 => 'function.mssql-pconnect.php',
    1 => 'mssql_pconnect',
  ),
  26 => 
  array (
    0 => 'function.mssql-query.php',
    1 => 'mssql_query',
  ),
  27 => 
  array (
    0 => 'function.mssql-result.php',
    1 => 'mssql_result',
  ),
  28 => 
  array (
    0 => 'function.mssql-rows-affected.php',
    1 => 'mssql_rows_affected',
  ),
  29 => 
  array (
    0 => 'function.mssql-select-db.php',
    1 => 'mssql_select_db',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mssql.php',
    1 => 'Mssql',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);