<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.fbsql-affected-rows.php',
    1 => 'fbsql_affected_rows',
  ),
  1 => 
  array (
    0 => 'function.fbsql-autocommit.php',
    1 => 'fbsql_autocommit',
  ),
  2 => 
  array (
    0 => 'function.fbsql-blob-size.php',
    1 => 'fbsql_blob_size',
  ),
  3 => 
  array (
    0 => 'function.fbsql-change-user.php',
    1 => 'fbsql_change_user',
  ),
  4 => 
  array (
    0 => 'function.fbsql-clob-size.php',
    1 => 'fbsql_clob_size',
  ),
  5 => 
  array (
    0 => 'function.fbsql-close.php',
    1 => 'fbsql_close',
  ),
  6 => 
  array (
    0 => 'function.fbsql-commit.php',
    1 => 'fbsql_commit',
  ),
  7 => 
  array (
    0 => 'function.fbsql-connect.php',
    1 => 'fbsql_connect',
  ),
  8 => 
  array (
    0 => 'function.fbsql-create-blob.php',
    1 => 'fbsql_create_blob',
  ),
  9 => 
  array (
    0 => 'function.fbsql-create-clob.php',
    1 => 'fbsql_create_clob',
  ),
  10 => 
  array (
    0 => 'function.fbsql-create-db.php',
    1 => 'fbsql_create_db',
  ),
  11 => 
  array (
    0 => 'function.fbsql-data-seek.php',
    1 => 'fbsql_data_seek',
  ),
  12 => 
  array (
    0 => 'function.fbsql-database-password.php',
    1 => 'fbsql_database_password',
  ),
  13 => 
  array (
    0 => 'function.fbsql-database.php',
    1 => 'fbsql_database',
  ),
  14 => 
  array (
    0 => 'function.fbsql-db-query.php',
    1 => 'fbsql_db_query',
  ),
  15 => 
  array (
    0 => 'function.fbsql-db-status.php',
    1 => 'fbsql_db_status',
  ),
  16 => 
  array (
    0 => 'function.fbsql-drop-db.php',
    1 => 'fbsql_drop_db',
  ),
  17 => 
  array (
    0 => 'function.fbsql-errno.php',
    1 => 'fbsql_errno',
  ),
  18 => 
  array (
    0 => 'function.fbsql-error.php',
    1 => 'fbsql_error',
  ),
  19 => 
  array (
    0 => 'function.fbsql-fetch-array.php',
    1 => 'fbsql_fetch_array',
  ),
  20 => 
  array (
    0 => 'function.fbsql-fetch-assoc.php',
    1 => 'fbsql_fetch_assoc',
  ),
  21 => 
  array (
    0 => 'function.fbsql-fetch-field.php',
    1 => 'fbsql_fetch_field',
  ),
  22 => 
  array (
    0 => 'function.fbsql-fetch-lengths.php',
    1 => 'fbsql_fetch_lengths',
  ),
  23 => 
  array (
    0 => 'function.fbsql-fetch-object.php',
    1 => 'fbsql_fetch_object',
  ),
  24 => 
  array (
    0 => 'function.fbsql-fetch-row.php',
    1 => 'fbsql_fetch_row',
  ),
  25 => 
  array (
    0 => 'function.fbsql-field-flags.php',
    1 => 'fbsql_field_flags',
  ),
  26 => 
  array (
    0 => 'function.fbsql-field-len.php',
    1 => 'fbsql_field_len',
  ),
  27 => 
  array (
    0 => 'function.fbsql-field-name.php',
    1 => 'fbsql_field_name',
  ),
  28 => 
  array (
    0 => 'function.fbsql-field-seek.php',
    1 => 'fbsql_field_seek',
  ),
  29 => 
  array (
    0 => 'function.fbsql-field-table.php',
    1 => 'fbsql_field_table',
  ),
  30 => 
  array (
    0 => 'function.fbsql-field-type.php',
    1 => 'fbsql_field_type',
  ),
  31 => 
  array (
    0 => 'function.fbsql-free-result.php',
    1 => 'fbsql_free_result',
  ),
  32 => 
  array (
    0 => 'function.fbsql-get-autostart-info.php',
    1 => 'fbsql_get_autostart_info',
  ),
  33 => 
  array (
    0 => 'function.fbsql-hostname.php',
    1 => 'fbsql_hostname',
  ),
  34 => 
  array (
    0 => 'function.fbsql-insert-id.php',
    1 => 'fbsql_insert_id',
  ),
  35 => 
  array (
    0 => 'function.fbsql-list-dbs.php',
    1 => 'fbsql_list_dbs',
  ),
  36 => 
  array (
    0 => 'function.fbsql-list-fields.php',
    1 => 'fbsql_list_fields',
  ),
  37 => 
  array (
    0 => 'function.fbsql-list-tables.php',
    1 => 'fbsql_list_tables',
  ),
  38 => 
  array (
    0 => 'function.fbsql-next-result.php',
    1 => 'fbsql_next_result',
  ),
  39 => 
  array (
    0 => 'function.fbsql-num-fields.php',
    1 => 'fbsql_num_fields',
  ),
  40 => 
  array (
    0 => 'function.fbsql-num-rows.php',
    1 => 'fbsql_num_rows',
  ),
  41 => 
  array (
    0 => 'function.fbsql-password.php',
    1 => 'fbsql_password',
  ),
  42 => 
  array (
    0 => 'function.fbsql-pconnect.php',
    1 => 'fbsql_pconnect',
  ),
  43 => 
  array (
    0 => 'function.fbsql-query.php',
    1 => 'fbsql_query',
  ),
  44 => 
  array (
    0 => 'function.fbsql-read-blob.php',
    1 => 'fbsql_read_blob',
  ),
  45 => 
  array (
    0 => 'function.fbsql-read-clob.php',
    1 => 'fbsql_read_clob',
  ),
  46 => 
  array (
    0 => 'function.fbsql-result.php',
    1 => 'fbsql_result',
  ),
  47 => 
  array (
    0 => 'function.fbsql-rollback.php',
    1 => 'fbsql_rollback',
  ),
  48 => 
  array (
    0 => 'function.fbsql-rows-fetched.php',
    1 => 'fbsql_rows_fetched',
  ),
  49 => 
  array (
    0 => 'function.fbsql-select-db.php',
    1 => 'fbsql_select_db',
  ),
  50 => 
  array (
    0 => 'function.fbsql-set-characterset.php',
    1 => 'fbsql_set_characterset',
  ),
  51 => 
  array (
    0 => 'function.fbsql-set-lob-mode.php',
    1 => 'fbsql_set_lob_mode',
  ),
  52 => 
  array (
    0 => 'function.fbsql-set-password.php',
    1 => 'fbsql_set_password',
  ),
  53 => 
  array (
    0 => 'function.fbsql-set-transaction.php',
    1 => 'fbsql_set_transaction',
  ),
  54 => 
  array (
    0 => 'function.fbsql-start-db.php',
    1 => 'fbsql_start_db',
  ),
  55 => 
  array (
    0 => 'function.fbsql-stop-db.php',
    1 => 'fbsql_stop_db',
  ),
  56 => 
  array (
    0 => 'function.fbsql-table-name.php',
    1 => 'fbsql_table_name',
  ),
  57 => 
  array (
    0 => 'function.fbsql-tablename.php',
    1 => 'fbsql_tablename',
  ),
  58 => 
  array (
    0 => 'function.fbsql-username.php',
    1 => 'fbsql_username',
  ),
  59 => 
  array (
    0 => 'function.fbsql-warnings.php',
    1 => 'fbsql_warnings',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.fbsql.php',
    1 => 'FrontBase',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);