<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.mysql-affected-rows.php',
    1 => 'mysql_affected_rows',
  ),
  1 => 
  array (
    0 => 'function.mysql-client-encoding.php',
    1 => 'mysql_client_encoding',
  ),
  2 => 
  array (
    0 => 'function.mysql-close.php',
    1 => 'mysql_close',
  ),
  3 => 
  array (
    0 => 'function.mysql-connect.php',
    1 => 'mysql_connect',
  ),
  4 => 
  array (
    0 => 'function.mysql-create-db.php',
    1 => 'mysql_create_db',
  ),
  5 => 
  array (
    0 => 'function.mysql-data-seek.php',
    1 => 'mysql_data_seek',
  ),
  6 => 
  array (
    0 => 'function.mysql-db-name.php',
    1 => 'mysql_db_name',
  ),
  7 => 
  array (
    0 => 'function.mysql-db-query.php',
    1 => 'mysql_db_query',
  ),
  8 => 
  array (
    0 => 'function.mysql-drop-db.php',
    1 => 'mysql_drop_db',
  ),
  9 => 
  array (
    0 => 'function.mysql-errno.php',
    1 => 'mysql_errno',
  ),
  10 => 
  array (
    0 => 'function.mysql-error.php',
    1 => 'mysql_error',
  ),
  11 => 
  array (
    0 => 'function.mysql-escape-string.php',
    1 => 'mysql_escape_string',
  ),
  12 => 
  array (
    0 => 'function.mysql-fetch-array.php',
    1 => 'mysql_fetch_array',
  ),
  13 => 
  array (
    0 => 'function.mysql-fetch-assoc.php',
    1 => 'mysql_fetch_assoc',
  ),
  14 => 
  array (
    0 => 'function.mysql-fetch-field.php',
    1 => 'mysql_fetch_field',
  ),
  15 => 
  array (
    0 => 'function.mysql-fetch-lengths.php',
    1 => 'mysql_fetch_lengths',
  ),
  16 => 
  array (
    0 => 'function.mysql-fetch-object.php',
    1 => 'mysql_fetch_object',
  ),
  17 => 
  array (
    0 => 'function.mysql-fetch-row.php',
    1 => 'mysql_fetch_row',
  ),
  18 => 
  array (
    0 => 'function.mysql-field-flags.php',
    1 => 'mysql_field_flags',
  ),
  19 => 
  array (
    0 => 'function.mysql-field-len.php',
    1 => 'mysql_field_len',
  ),
  20 => 
  array (
    0 => 'function.mysql-field-name.php',
    1 => 'mysql_field_name',
  ),
  21 => 
  array (
    0 => 'function.mysql-field-seek.php',
    1 => 'mysql_field_seek',
  ),
  22 => 
  array (
    0 => 'function.mysql-field-table.php',
    1 => 'mysql_field_table',
  ),
  23 => 
  array (
    0 => 'function.mysql-field-type.php',
    1 => 'mysql_field_type',
  ),
  24 => 
  array (
    0 => 'function.mysql-free-result.php',
    1 => 'mysql_free_result',
  ),
  25 => 
  array (
    0 => 'function.mysql-get-client-info.php',
    1 => 'mysql_get_client_info',
  ),
  26 => 
  array (
    0 => 'function.mysql-get-host-info.php',
    1 => 'mysql_get_host_info',
  ),
  27 => 
  array (
    0 => 'function.mysql-get-proto-info.php',
    1 => 'mysql_get_proto_info',
  ),
  28 => 
  array (
    0 => 'function.mysql-get-server-info.php',
    1 => 'mysql_get_server_info',
  ),
  29 => 
  array (
    0 => 'function.mysql-info.php',
    1 => 'mysql_info',
  ),
  30 => 
  array (
    0 => 'function.mysql-insert-id.php',
    1 => 'mysql_insert_id',
  ),
  31 => 
  array (
    0 => 'function.mysql-list-dbs.php',
    1 => 'mysql_list_dbs',
  ),
  32 => 
  array (
    0 => 'function.mysql-list-fields.php',
    1 => 'mysql_list_fields',
  ),
  33 => 
  array (
    0 => 'function.mysql-list-processes.php',
    1 => 'mysql_list_processes',
  ),
  34 => 
  array (
    0 => 'function.mysql-list-tables.php',
    1 => 'mysql_list_tables',
  ),
  35 => 
  array (
    0 => 'function.mysql-num-fields.php',
    1 => 'mysql_num_fields',
  ),
  36 => 
  array (
    0 => 'function.mysql-num-rows.php',
    1 => 'mysql_num_rows',
  ),
  37 => 
  array (
    0 => 'function.mysql-pconnect.php',
    1 => 'mysql_pconnect',
  ),
  38 => 
  array (
    0 => 'function.mysql-ping.php',
    1 => 'mysql_ping',
  ),
  39 => 
  array (
    0 => 'function.mysql-query.php',
    1 => 'mysql_query',
  ),
  40 => 
  array (
    0 => 'function.mysql-real-escape-string.php',
    1 => 'mysql_real_escape_string',
  ),
  41 => 
  array (
    0 => 'function.mysql-result.php',
    1 => 'mysql_result',
  ),
  42 => 
  array (
    0 => 'function.mysql-select-db.php',
    1 => 'mysql_select_db',
  ),
  43 => 
  array (
    0 => 'function.mysql-set-charset.php',
    1 => 'mysql_set_charset',
  ),
  44 => 
  array (
    0 => 'function.mysql-stat.php',
    1 => 'mysql_stat',
  ),
  45 => 
  array (
    0 => 'function.mysql-tablename.php',
    1 => 'mysql_tablename',
  ),
  46 => 
  array (
    0 => 'function.mysql-thread-id.php',
    1 => 'mysql_thread_id',
  ),
  47 => 
  array (
    0 => 'function.mysql-unbuffered-query.php',
    1 => 'mysql_unbuffered_query',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mysql.php',
    1 => 'MySQL',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);