<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.bbcode-add-element.php',
    1 => 'bbcode_add_element',
  ),
  1 => 
  array (
    0 => 'function.bbcode-add-smiley.php',
    1 => 'bbcode_add_smiley',
  ),
  2 => 
  array (
    0 => 'function.bbcode-create.php',
    1 => 'bbcode_create',
  ),
  3 => 
  array (
    0 => 'function.bbcode-destroy.php',
    1 => 'bbcode_destroy',
  ),
  4 => 
  array (
    0 => 'function.bbcode-parse.php',
    1 => 'bbcode_parse',
  ),
  5 => 
  array (
    0 => 'function.bbcode-set-arg-parser.php',
    1 => 'bbcode_set_arg_parser',
  ),
  6 => 
  array (
    0 => 'function.bbcode-set-flags.php',
    1 => 'bbcode_set_flags',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.bbcode.php',
    1 => 'BBCode',
  ),
  1 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'Text Processing',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);