<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.recode-file.php',
    1 => 'recode_file',
  ),
  1 => 
  array (
    0 => 'function.recode-string.php',
    1 => 'recode_string',
  ),
  2 => 
  array (
    0 => 'function.recode.php',
    1 => 'recode',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.recode.php',
    1 => 'Recode',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);