<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.kadm5-chpass-principal.php',
    1 => 'kadm5_chpass_principal',
  ),
  1 => 
  array (
    0 => 'function.kadm5-create-principal.php',
    1 => 'kadm5_create_principal',
  ),
  2 => 
  array (
    0 => 'function.kadm5-delete-principal.php',
    1 => 'kadm5_delete_principal',
  ),
  3 => 
  array (
    0 => 'function.kadm5-destroy.php',
    1 => 'kadm5_destroy',
  ),
  4 => 
  array (
    0 => 'function.kadm5-flush.php',
    1 => 'kadm5_flush',
  ),
  5 => 
  array (
    0 => 'function.kadm5-get-policies.php',
    1 => 'kadm5_get_policies',
  ),
  6 => 
  array (
    0 => 'function.kadm5-get-principal.php',
    1 => 'kadm5_get_principal',
  ),
  7 => 
  array (
    0 => 'function.kadm5-get-principals.php',
    1 => 'kadm5_get_principals',
  ),
  8 => 
  array (
    0 => 'function.kadm5-init-with-password.php',
    1 => 'kadm5_init_with_password',
  ),
  9 => 
  array (
    0 => 'function.kadm5-modify-principal.php',
    1 => 'kadm5_modify_principal',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.kadm5.php',
    1 => 'KADM5',
  ),
  1 => 
  array (
    0 => 'refs.remote.auth.php',
    1 => 'Authentication Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);