<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.checkdate.php',
    1 => 'checkdate',
  ),
  1 => 
  array (
    0 => 'function.date-add.php',
    1 => 'date_add',
  ),
  2 => 
  array (
    0 => 'function.date-create-from-format.php',
    1 => 'date_create_from_format',
  ),
  3 => 
  array (
    0 => 'function.date-create.php',
    1 => 'date_create',
  ),
  4 => 
  array (
    0 => 'function.date-date-set.php',
    1 => 'date_date_set',
  ),
  5 => 
  array (
    0 => 'function.date-default-timezone-get.php',
    1 => 'date_default_timezone_get',
  ),
  6 => 
  array (
    0 => 'function.date-default-timezone-set.php',
    1 => 'date_default_timezone_set',
  ),
  7 => 
  array (
    0 => 'function.date-diff.php',
    1 => 'date_diff',
  ),
  8 => 
  array (
    0 => 'function.date-format.php',
    1 => 'date_format',
  ),
  9 => 
  array (
    0 => 'function.date-get-last-errors.php',
    1 => 'date_get_last_errors',
  ),
  10 => 
  array (
    0 => 'function.date-interval-create-from-date-string.php',
    1 => 'date_interval_create_from_date_string',
  ),
  11 => 
  array (
    0 => 'function.date-interval-format.php',
    1 => 'date_interval_format',
  ),
  12 => 
  array (
    0 => 'function.date-isodate-set.php',
    1 => 'date_isodate_set',
  ),
  13 => 
  array (
    0 => 'function.date-modify.php',
    1 => 'date_modify',
  ),
  14 => 
  array (
    0 => 'function.date-offset-get.php',
    1 => 'date_offset_get',
  ),
  15 => 
  array (
    0 => 'function.date-parse-from-format.php',
    1 => 'date_parse_from_format',
  ),
  16 => 
  array (
    0 => 'function.date-parse.php',
    1 => 'date_parse',
  ),
  17 => 
  array (
    0 => 'function.date-sub.php',
    1 => 'date_sub',
  ),
  18 => 
  array (
    0 => 'function.date-sun-info.php',
    1 => 'date_sun_info',
  ),
  19 => 
  array (
    0 => 'function.date-sunrise.php',
    1 => 'date_sunrise',
  ),
  20 => 
  array (
    0 => 'function.date-sunset.php',
    1 => 'date_sunset',
  ),
  21 => 
  array (
    0 => 'function.date-time-set.php',
    1 => 'date_time_set',
  ),
  22 => 
  array (
    0 => 'function.date-timestamp-get.php',
    1 => 'date_timestamp_get',
  ),
  23 => 
  array (
    0 => 'function.date-timestamp-set.php',
    1 => 'date_timestamp_set',
  ),
  24 => 
  array (
    0 => 'function.date-timezone-get.php',
    1 => 'date_timezone_get',
  ),
  25 => 
  array (
    0 => 'function.date-timezone-set.php',
    1 => 'date_timezone_set',
  ),
  26 => 
  array (
    0 => 'function.date.php',
    1 => 'date',
  ),
  27 => 
  array (
    0 => 'function.getdate.php',
    1 => 'getdate',
  ),
  28 => 
  array (
    0 => 'function.gettimeofday.php',
    1 => 'gettimeofday',
  ),
  29 => 
  array (
    0 => 'function.gmdate.php',
    1 => 'gmdate',
  ),
  30 => 
  array (
    0 => 'function.gmmktime.php',
    1 => 'gmmktime',
  ),
  31 => 
  array (
    0 => 'function.gmstrftime.php',
    1 => 'gmstrftime',
  ),
  32 => 
  array (
    0 => 'function.idate.php',
    1 => 'idate',
  ),
  33 => 
  array (
    0 => 'function.localtime.php',
    1 => 'localtime',
  ),
  34 => 
  array (
    0 => 'function.microtime.php',
    1 => 'microtime',
  ),
  35 => 
  array (
    0 => 'function.mktime.php',
    1 => 'mktime',
  ),
  36 => 
  array (
    0 => 'function.strftime.php',
    1 => 'strftime',
  ),
  37 => 
  array (
    0 => 'function.strptime.php',
    1 => 'strptime',
  ),
  38 => 
  array (
    0 => 'function.strtotime.php',
    1 => 'strtotime',
  ),
  39 => 
  array (
    0 => 'function.time.php',
    1 => 'time',
  ),
  40 => 
  array (
    0 => 'function.timezone-abbreviations-list.php',
    1 => 'timezone_abbreviations_list',
  ),
  41 => 
  array (
    0 => 'function.timezone-identifiers-list.php',
    1 => 'timezone_identifiers_list',
  ),
  42 => 
  array (
    0 => 'function.timezone-location-get.php',
    1 => 'timezone_location_get',
  ),
  43 => 
  array (
    0 => 'function.timezone-name-from-abbr.php',
    1 => 'timezone_name_from_abbr',
  ),
  44 => 
  array (
    0 => 'function.timezone-name-get.php',
    1 => 'timezone_name_get',
  ),
  45 => 
  array (
    0 => 'function.timezone-offset-get.php',
    1 => 'timezone_offset_get',
  ),
  46 => 
  array (
    0 => 'function.timezone-open.php',
    1 => 'timezone_open',
  ),
  47 => 
  array (
    0 => 'function.timezone-transitions-get.php',
    1 => 'timezone_transitions_get',
  ),
  48 => 
  array (
    0 => 'function.timezone-version-get.php',
    1 => 'timezone_version_get',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.datetime.php',
    1 => 'Date/Time',
  ),
  1 => 
  array (
    0 => 'refs.calendar.php',
    1 => 'Date and Time Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);