<?php
$TOC = array (
  0 => 
  array (
    0 => 'ref.pdo-4d.connection.php',
    1 => 'PDO_4D DSN',
  ),
  1 => 
  array (
    0 => 'pdo-4d.constants.php',
    1 => 'Constants for PDO_4D',
  ),
  2 => 
  array (
    0 => 'pdo-4d.sqltypes.php',
    1 => 'SQL types with PDO_4D and PHP',
  ),
  3 => 
  array (
    0 => 'ref.pdo-4d.sql4d.php',
    1 => 'SQL acceptable by 4D',
  ),
  4 => 
  array (
    0 => 'pdo-4d.examples.php',
    1 => 'Examples with PDO_4D',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'pdo.drivers.php',
    1 => 'PDO Drivers',
  ),
  1 => 
  array (
    0 => 'book.pdo.php',
    1 => 'PDO',
  ),
  2 => 
  array (
    0 => 'refs.database.abstract.php',
    1 => 'Abstraction Layers',
  ),
  3 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  4 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  5 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);