<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.idn-to-ascii.php',
    1 => 'idn_to_ascii',
  ),
  1 => 
  array (
    0 => 'function.idn-to-unicode.php',
    1 => 'idn_to_unicode',
  ),
  2 => 
  array (
    0 => 'function.idn-to-utf8.php',
    1 => 'idn_to_utf8',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.intl.php',
    1 => 'intl',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);