<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ifx-affected-rows.php',
    1 => 'ifx_affected_rows',
  ),
  1 => 
  array (
    0 => 'function.ifx-blobinfile-mode.php',
    1 => 'ifx_blobinfile_mode',
  ),
  2 => 
  array (
    0 => 'function.ifx-byteasvarchar.php',
    1 => 'ifx_byteasvarchar',
  ),
  3 => 
  array (
    0 => 'function.ifx-close.php',
    1 => 'ifx_close',
  ),
  4 => 
  array (
    0 => 'function.ifx-connect.php',
    1 => 'ifx_connect',
  ),
  5 => 
  array (
    0 => 'function.ifx-copy-blob.php',
    1 => 'ifx_copy_blob',
  ),
  6 => 
  array (
    0 => 'function.ifx-create-blob.php',
    1 => 'ifx_create_blob',
  ),
  7 => 
  array (
    0 => 'function.ifx-create-char.php',
    1 => 'ifx_create_char',
  ),
  8 => 
  array (
    0 => 'function.ifx-do.php',
    1 => 'ifx_do',
  ),
  9 => 
  array (
    0 => 'function.ifx-error.php',
    1 => 'ifx_error',
  ),
  10 => 
  array (
    0 => 'function.ifx-errormsg.php',
    1 => 'ifx_errormsg',
  ),
  11 => 
  array (
    0 => 'function.ifx-fetch-row.php',
    1 => 'ifx_fetch_row',
  ),
  12 => 
  array (
    0 => 'function.ifx-fieldproperties.php',
    1 => 'ifx_fieldproperties',
  ),
  13 => 
  array (
    0 => 'function.ifx-fieldtypes.php',
    1 => 'ifx_fieldtypes',
  ),
  14 => 
  array (
    0 => 'function.ifx-free-blob.php',
    1 => 'ifx_free_blob',
  ),
  15 => 
  array (
    0 => 'function.ifx-free-char.php',
    1 => 'ifx_free_char',
  ),
  16 => 
  array (
    0 => 'function.ifx-free-result.php',
    1 => 'ifx_free_result',
  ),
  17 => 
  array (
    0 => 'function.ifx-get-blob.php',
    1 => 'ifx_get_blob',
  ),
  18 => 
  array (
    0 => 'function.ifx-get-char.php',
    1 => 'ifx_get_char',
  ),
  19 => 
  array (
    0 => 'function.ifx-getsqlca.php',
    1 => 'ifx_getsqlca',
  ),
  20 => 
  array (
    0 => 'function.ifx-htmltbl-result.php',
    1 => 'ifx_htmltbl_result',
  ),
  21 => 
  array (
    0 => 'function.ifx-nullformat.php',
    1 => 'ifx_nullformat',
  ),
  22 => 
  array (
    0 => 'function.ifx-num-fields.php',
    1 => 'ifx_num_fields',
  ),
  23 => 
  array (
    0 => 'function.ifx-num-rows.php',
    1 => 'ifx_num_rows',
  ),
  24 => 
  array (
    0 => 'function.ifx-pconnect.php',
    1 => 'ifx_pconnect',
  ),
  25 => 
  array (
    0 => 'function.ifx-prepare.php',
    1 => 'ifx_prepare',
  ),
  26 => 
  array (
    0 => 'function.ifx-query.php',
    1 => 'ifx_query',
  ),
  27 => 
  array (
    0 => 'function.ifx-textasvarchar.php',
    1 => 'ifx_textasvarchar',
  ),
  28 => 
  array (
    0 => 'function.ifx-update-blob.php',
    1 => 'ifx_update_blob',
  ),
  29 => 
  array (
    0 => 'function.ifx-update-char.php',
    1 => 'ifx_update_char',
  ),
  30 => 
  array (
    0 => 'function.ifxus-close-slob.php',
    1 => 'ifxus_close_slob',
  ),
  31 => 
  array (
    0 => 'function.ifxus-create-slob.php',
    1 => 'ifxus_create_slob',
  ),
  32 => 
  array (
    0 => 'function.ifxus-free-slob.php',
    1 => 'ifxus_free_slob',
  ),
  33 => 
  array (
    0 => 'function.ifxus-open-slob.php',
    1 => 'ifxus_open_slob',
  ),
  34 => 
  array (
    0 => 'function.ifxus-read-slob.php',
    1 => 'ifxus_read_slob',
  ),
  35 => 
  array (
    0 => 'function.ifxus-seek-slob.php',
    1 => 'ifxus_seek_slob',
  ),
  36 => 
  array (
    0 => 'function.ifxus-tell-slob.php',
    1 => 'ifxus_tell_slob',
  ),
  37 => 
  array (
    0 => 'function.ifxus-write-slob.php',
    1 => 'ifxus_write_slob',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ifx.php',
    1 => 'Informix',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);