<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.wincache-fcache-fileinfo.php',
    1 => 'wincache_fcache_fileinfo',
  ),
  1 => 
  array (
    0 => 'function.wincache-fcache-meminfo.php',
    1 => 'wincache_fcache_meminfo',
  ),
  2 => 
  array (
    0 => 'function.wincache-lock.php',
    1 => 'wincache_lock',
  ),
  3 => 
  array (
    0 => 'function.wincache-ocache-fileinfo.php',
    1 => 'wincache_ocache_fileinfo',
  ),
  4 => 
  array (
    0 => 'function.wincache-ocache-meminfo.php',
    1 => 'wincache_ocache_meminfo',
  ),
  5 => 
  array (
    0 => 'function.wincache-refresh-if-changed.php',
    1 => 'wincache_refresh_if_changed',
  ),
  6 => 
  array (
    0 => 'function.wincache-rplist-fileinfo.php',
    1 => 'wincache_rplist_fileinfo',
  ),
  7 => 
  array (
    0 => 'function.wincache-rplist-meminfo.php',
    1 => 'wincache_rplist_meminfo',
  ),
  8 => 
  array (
    0 => 'function.wincache-scache-info.php',
    1 => 'wincache_scache_info',
  ),
  9 => 
  array (
    0 => 'function.wincache-scache-meminfo.php',
    1 => 'wincache_scache_meminfo',
  ),
  10 => 
  array (
    0 => 'function.wincache-ucache-add.php',
    1 => 'wincache_ucache_add',
  ),
  11 => 
  array (
    0 => 'function.wincache-ucache-cas.php',
    1 => 'wincache_ucache_cas',
  ),
  12 => 
  array (
    0 => 'function.wincache-ucache-clear.php',
    1 => 'wincache_ucache_clear',
  ),
  13 => 
  array (
    0 => 'function.wincache-ucache-dec.php',
    1 => 'wincache_ucache_dec',
  ),
  14 => 
  array (
    0 => 'function.wincache-ucache-delete.php',
    1 => 'wincache_ucache_delete',
  ),
  15 => 
  array (
    0 => 'function.wincache-ucache-exists.php',
    1 => 'wincache_ucache_exists',
  ),
  16 => 
  array (
    0 => 'function.wincache-ucache-get.php',
    1 => 'wincache_ucache_get',
  ),
  17 => 
  array (
    0 => 'function.wincache-ucache-inc.php',
    1 => 'wincache_ucache_inc',
  ),
  18 => 
  array (
    0 => 'function.wincache-ucache-info.php',
    1 => 'wincache_ucache_info',
  ),
  19 => 
  array (
    0 => 'function.wincache-ucache-meminfo.php',
    1 => 'wincache_ucache_meminfo',
  ),
  20 => 
  array (
    0 => 'function.wincache-ucache-set.php',
    1 => 'wincache_ucache_set',
  ),
  21 => 
  array (
    0 => 'function.wincache-unlock.php',
    1 => 'wincache_unlock',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.wincache.php',
    1 => 'WinCache',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);