<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.fribidi-log2vis.php',
    1 => 'fribidi_log2vis',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.fribidi.php',
    1 => 'FriBiDi',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);