<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.mysqlnd_qc_change_handler.php',
    1 => 'mysqlnd_qc_change_handler',
  ),
  1 => 
  array (
    0 => 'function.mysqlnd_qc_clear_cache.php',
    1 => 'mysqlnd_qc_clear_cache',
  ),
  2 => 
  array (
    0 => 'function.mysqlnd_qc_get_cache_info.php',
    1 => 'mysqlnd_qc_get_cache_info',
  ),
  3 => 
  array (
    0 => 'function.mysqlnd_qc_get_core_stats.php',
    1 => 'mysqlnd_qc_get_core_stats',
  ),
  4 => 
  array (
    0 => 'function.mysqlnd_qc_get_handler.php',
    1 => 'mysqlnd_qc_get_handler',
  ),
  5 => 
  array (
    0 => 'function.mysqlnd_qc_get_query_trace_log.php',
    1 => 'mysqlnd_qc_get_query_trace_log',
  ),
  6 => 
  array (
    0 => 'function.mysqlnd_qc_set_user_handlers.php',
    1 => 'mysqlnd_qc_set_user_handlers',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mysqlnd-qc.php',
    1 => 'mysqlnd_qc',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);