<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.rpm-close.php',
    1 => 'rpm_close',
  ),
  1 => 
  array (
    0 => 'function.rpm-get-tag.php',
    1 => 'rpm_get_tag',
  ),
  2 => 
  array (
    0 => 'function.rpm-is-valid.php',
    1 => 'rpm_is_valid',
  ),
  3 => 
  array (
    0 => 'function.rpm-open.php',
    1 => 'rpm_open',
  ),
  4 => 
  array (
    0 => 'function.rpm-version.php',
    1 => 'rpm_version',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.rpmreader.php',
    1 => 'RPM Reader',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);