<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.dbplus-add.php',
    1 => 'dbplus_add',
  ),
  1 => 
  array (
    0 => 'function.dbplus-aql.php',
    1 => 'dbplus_aql',
  ),
  2 => 
  array (
    0 => 'function.dbplus-chdir.php',
    1 => 'dbplus_chdir',
  ),
  3 => 
  array (
    0 => 'function.dbplus-close.php',
    1 => 'dbplus_close',
  ),
  4 => 
  array (
    0 => 'function.dbplus-curr.php',
    1 => 'dbplus_curr',
  ),
  5 => 
  array (
    0 => 'function.dbplus-errcode.php',
    1 => 'dbplus_errcode',
  ),
  6 => 
  array (
    0 => 'function.dbplus-errno.php',
    1 => 'dbplus_errno',
  ),
  7 => 
  array (
    0 => 'function.dbplus-find.php',
    1 => 'dbplus_find',
  ),
  8 => 
  array (
    0 => 'function.dbplus-first.php',
    1 => 'dbplus_first',
  ),
  9 => 
  array (
    0 => 'function.dbplus-flush.php',
    1 => 'dbplus_flush',
  ),
  10 => 
  array (
    0 => 'function.dbplus-freealllocks.php',
    1 => 'dbplus_freealllocks',
  ),
  11 => 
  array (
    0 => 'function.dbplus-freelock.php',
    1 => 'dbplus_freelock',
  ),
  12 => 
  array (
    0 => 'function.dbplus-freerlocks.php',
    1 => 'dbplus_freerlocks',
  ),
  13 => 
  array (
    0 => 'function.dbplus-getlock.php',
    1 => 'dbplus_getlock',
  ),
  14 => 
  array (
    0 => 'function.dbplus-getunique.php',
    1 => 'dbplus_getunique',
  ),
  15 => 
  array (
    0 => 'function.dbplus-info.php',
    1 => 'dbplus_info',
  ),
  16 => 
  array (
    0 => 'function.dbplus-last.php',
    1 => 'dbplus_last',
  ),
  17 => 
  array (
    0 => 'function.dbplus-lockrel.php',
    1 => 'dbplus_lockrel',
  ),
  18 => 
  array (
    0 => 'function.dbplus-next.php',
    1 => 'dbplus_next',
  ),
  19 => 
  array (
    0 => 'function.dbplus-open.php',
    1 => 'dbplus_open',
  ),
  20 => 
  array (
    0 => 'function.dbplus-prev.php',
    1 => 'dbplus_prev',
  ),
  21 => 
  array (
    0 => 'function.dbplus-rchperm.php',
    1 => 'dbplus_rchperm',
  ),
  22 => 
  array (
    0 => 'function.dbplus-rcreate.php',
    1 => 'dbplus_rcreate',
  ),
  23 => 
  array (
    0 => 'function.dbplus-rcrtexact.php',
    1 => 'dbplus_rcrtexact',
  ),
  24 => 
  array (
    0 => 'function.dbplus-rcrtlike.php',
    1 => 'dbplus_rcrtlike',
  ),
  25 => 
  array (
    0 => 'function.dbplus-resolve.php',
    1 => 'dbplus_resolve',
  ),
  26 => 
  array (
    0 => 'function.dbplus-restorepos.php',
    1 => 'dbplus_restorepos',
  ),
  27 => 
  array (
    0 => 'function.dbplus-rkeys.php',
    1 => 'dbplus_rkeys',
  ),
  28 => 
  array (
    0 => 'function.dbplus-ropen.php',
    1 => 'dbplus_ropen',
  ),
  29 => 
  array (
    0 => 'function.dbplus-rquery.php',
    1 => 'dbplus_rquery',
  ),
  30 => 
  array (
    0 => 'function.dbplus-rrename.php',
    1 => 'dbplus_rrename',
  ),
  31 => 
  array (
    0 => 'function.dbplus-rsecindex.php',
    1 => 'dbplus_rsecindex',
  ),
  32 => 
  array (
    0 => 'function.dbplus-runlink.php',
    1 => 'dbplus_runlink',
  ),
  33 => 
  array (
    0 => 'function.dbplus-rzap.php',
    1 => 'dbplus_rzap',
  ),
  34 => 
  array (
    0 => 'function.dbplus-savepos.php',
    1 => 'dbplus_savepos',
  ),
  35 => 
  array (
    0 => 'function.dbplus-setindex.php',
    1 => 'dbplus_setindex',
  ),
  36 => 
  array (
    0 => 'function.dbplus-setindexbynumber.php',
    1 => 'dbplus_setindexbynumber',
  ),
  37 => 
  array (
    0 => 'function.dbplus-sql.php',
    1 => 'dbplus_sql',
  ),
  38 => 
  array (
    0 => 'function.dbplus-tcl.php',
    1 => 'dbplus_tcl',
  ),
  39 => 
  array (
    0 => 'function.dbplus-tremove.php',
    1 => 'dbplus_tremove',
  ),
  40 => 
  array (
    0 => 'function.dbplus-undo.php',
    1 => 'dbplus_undo',
  ),
  41 => 
  array (
    0 => 'function.dbplus-undoprepare.php',
    1 => 'dbplus_undoprepare',
  ),
  42 => 
  array (
    0 => 'function.dbplus-unlockrel.php',
    1 => 'dbplus_unlockrel',
  ),
  43 => 
  array (
    0 => 'function.dbplus-unselect.php',
    1 => 'dbplus_unselect',
  ),
  44 => 
  array (
    0 => 'function.dbplus-update.php',
    1 => 'dbplus_update',
  ),
  45 => 
  array (
    0 => 'function.dbplus-xlockrel.php',
    1 => 'dbplus_xlockrel',
  ),
  46 => 
  array (
    0 => 'function.dbplus-xunlockrel.php',
    1 => 'dbplus_xunlockrel',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dbplus.php',
    1 => 'DB++',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);