<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.win32-continue-service.php',
    1 => 'win32_continue_service',
  ),
  1 => 
  array (
    0 => 'function.win32-create-service.php',
    1 => 'win32_create_service',
  ),
  2 => 
  array (
    0 => 'function.win32-delete-service.php',
    1 => 'win32_delete_service',
  ),
  3 => 
  array (
    0 => 'function.win32-get-last-control-message.php',
    1 => 'win32_get_last_control_message',
  ),
  4 => 
  array (
    0 => 'function.win32-pause-service.php',
    1 => 'win32_pause_service',
  ),
  5 => 
  array (
    0 => 'function.win32-query-service-status.php',
    1 => 'win32_query_service_status',
  ),
  6 => 
  array (
    0 => 'function.win32-set-service-status.php',
    1 => 'win32_set_service_status',
  ),
  7 => 
  array (
    0 => 'function.win32-start-service-ctrl-dispatcher.php',
    1 => 'win32_start_service_ctrl_dispatcher',
  ),
  8 => 
  array (
    0 => 'function.win32-start-service.php',
    1 => 'win32_start_service',
  ),
  9 => 
  array (
    0 => 'function.win32-stop-service.php',
    1 => 'win32_stop_service',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.win32service.php',
    1 => 'win32service',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);