<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.set-socket-blocking.php',
    1 => 'set_socket_blocking',
  ),
  1 => 
  array (
    0 => 'function.stream-bucket-append.php',
    1 => 'stream_bucket_append',
  ),
  2 => 
  array (
    0 => 'function.stream-bucket-make-writeable.php',
    1 => 'stream_bucket_make_writeable',
  ),
  3 => 
  array (
    0 => 'function.stream-bucket-new.php',
    1 => 'stream_bucket_new',
  ),
  4 => 
  array (
    0 => 'function.stream-bucket-prepend.php',
    1 => 'stream_bucket_prepend',
  ),
  5 => 
  array (
    0 => 'function.stream-context-create.php',
    1 => 'stream_context_create',
  ),
  6 => 
  array (
    0 => 'function.stream-context-get-default.php',
    1 => 'stream_context_get_default',
  ),
  7 => 
  array (
    0 => 'function.stream-context-get-options.php',
    1 => 'stream_context_get_options',
  ),
  8 => 
  array (
    0 => 'function.stream-context-get-params.php',
    1 => 'stream_context_get_params',
  ),
  9 => 
  array (
    0 => 'function.stream-context-set-default.php',
    1 => 'stream_context_set_default',
  ),
  10 => 
  array (
    0 => 'function.stream-context-set-option.php',
    1 => 'stream_context_set_option',
  ),
  11 => 
  array (
    0 => 'function.stream-context-set-params.php',
    1 => 'stream_context_set_params',
  ),
  12 => 
  array (
    0 => 'function.stream-copy-to-stream.php',
    1 => 'stream_copy_to_stream',
  ),
  13 => 
  array (
    0 => 'function.stream-encoding.php',
    1 => 'stream_encoding',
  ),
  14 => 
  array (
    0 => 'function.stream-filter-append.php',
    1 => 'stream_filter_append',
  ),
  15 => 
  array (
    0 => 'function.stream-filter-prepend.php',
    1 => 'stream_filter_prepend',
  ),
  16 => 
  array (
    0 => 'function.stream-filter-register.php',
    1 => 'stream_filter_register',
  ),
  17 => 
  array (
    0 => 'function.stream-filter-remove.php',
    1 => 'stream_filter_remove',
  ),
  18 => 
  array (
    0 => 'function.stream-get-contents.php',
    1 => 'stream_get_contents',
  ),
  19 => 
  array (
    0 => 'function.stream-get-filters.php',
    1 => 'stream_get_filters',
  ),
  20 => 
  array (
    0 => 'function.stream-get-line.php',
    1 => 'stream_get_line',
  ),
  21 => 
  array (
    0 => 'function.stream-get-meta-data.php',
    1 => 'stream_get_meta_data',
  ),
  22 => 
  array (
    0 => 'function.stream-get-transports.php',
    1 => 'stream_get_transports',
  ),
  23 => 
  array (
    0 => 'function.stream-get-wrappers.php',
    1 => 'stream_get_wrappers',
  ),
  24 => 
  array (
    0 => 'function.stream-is-local.php',
    1 => 'stream_is_local',
  ),
  25 => 
  array (
    0 => 'function.stream-notification-callback.php',
    1 => 'stream_notification_callback',
  ),
  26 => 
  array (
    0 => 'function.stream-register-wrapper.php',
    1 => 'stream_register_wrapper',
  ),
  27 => 
  array (
    0 => 'function.stream-resolve-include-path.php',
    1 => 'stream_resolve_include_path',
  ),
  28 => 
  array (
    0 => 'function.stream-select.php',
    1 => 'stream_select',
  ),
  29 => 
  array (
    0 => 'function.stream-set-blocking.php',
    1 => 'stream_set_blocking',
  ),
  30 => 
  array (
    0 => 'function.stream-set-read-buffer.php',
    1 => 'stream_set_read_buffer',
  ),
  31 => 
  array (
    0 => 'function.stream-set-timeout.php',
    1 => 'stream_set_timeout',
  ),
  32 => 
  array (
    0 => 'function.stream-set-write-buffer.php',
    1 => 'stream_set_write_buffer',
  ),
  33 => 
  array (
    0 => 'function.stream-socket-accept.php',
    1 => 'stream_socket_accept',
  ),
  34 => 
  array (
    0 => 'function.stream-socket-client.php',
    1 => 'stream_socket_client',
  ),
  35 => 
  array (
    0 => 'function.stream-socket-enable-crypto.php',
    1 => 'stream_socket_enable_crypto',
  ),
  36 => 
  array (
    0 => 'function.stream-socket-get-name.php',
    1 => 'stream_socket_get_name',
  ),
  37 => 
  array (
    0 => 'function.stream-socket-pair.php',
    1 => 'stream_socket_pair',
  ),
  38 => 
  array (
    0 => 'function.stream-socket-recvfrom.php',
    1 => 'stream_socket_recvfrom',
  ),
  39 => 
  array (
    0 => 'function.stream-socket-sendto.php',
    1 => 'stream_socket_sendto',
  ),
  40 => 
  array (
    0 => 'function.stream-socket-server.php',
    1 => 'stream_socket_server',
  ),
  41 => 
  array (
    0 => 'function.stream-socket-shutdown.php',
    1 => 'stream_socket_shutdown',
  ),
  42 => 
  array (
    0 => 'function.stream-supports-lock.php',
    1 => 'stream_supports_lock',
  ),
  43 => 
  array (
    0 => 'function.stream-wrapper-register.php',
    1 => 'stream_wrapper_register',
  ),
  44 => 
  array (
    0 => 'function.stream-wrapper-restore.php',
    1 => 'stream_wrapper_restore',
  ),
  45 => 
  array (
    0 => 'function.stream-wrapper-unregister.php',
    1 => 'stream_wrapper_unregister',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.stream.php',
    1 => 'Streams',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);