<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.maxdb-affected-rows.php',
    1 => 'maxdb_affected_rows',
  ),
  1 => 
  array (
    0 => 'function.maxdb-autocommit.php',
    1 => 'maxdb_autocommit',
  ),
  2 => 
  array (
    0 => 'function.maxdb-bind-param.php',
    1 => 'maxdb_bind_param',
  ),
  3 => 
  array (
    0 => 'function.maxdb-bind-result.php',
    1 => 'maxdb_bind_result',
  ),
  4 => 
  array (
    0 => 'function.maxdb-change-user.php',
    1 => 'maxdb_change_user',
  ),
  5 => 
  array (
    0 => 'function.maxdb-character-set-name.php',
    1 => 'maxdb_character_set_name',
  ),
  6 => 
  array (
    0 => 'function.maxdb-client-encoding.php',
    1 => 'maxdb_client_encoding',
  ),
  7 => 
  array (
    0 => 'function.maxdb-close-long-data.php',
    1 => 'maxdb_close_long_data',
  ),
  8 => 
  array (
    0 => 'function.maxdb-close.php',
    1 => 'maxdb_close',
  ),
  9 => 
  array (
    0 => 'function.maxdb-commit.php',
    1 => 'maxdb_commit',
  ),
  10 => 
  array (
    0 => 'function.maxdb-connect-errno.php',
    1 => 'maxdb_connect_errno',
  ),
  11 => 
  array (
    0 => 'function.maxdb-connect-error.php',
    1 => 'maxdb_connect_error',
  ),
  12 => 
  array (
    0 => 'function.maxdb-connect.php',
    1 => 'maxdb_connect',
  ),
  13 => 
  array (
    0 => 'function.maxdb-data-seek.php',
    1 => 'maxdb_data_seek',
  ),
  14 => 
  array (
    0 => 'function.maxdb-debug.php',
    1 => 'maxdb_debug',
  ),
  15 => 
  array (
    0 => 'function.maxdb-disable-reads-from-master.php',
    1 => 'maxdb_disable_reads_from_master',
  ),
  16 => 
  array (
    0 => 'function.maxdb-disable-rpl-parse.php',
    1 => 'maxdb_disable_rpl_parse',
  ),
  17 => 
  array (
    0 => 'function.maxdb-dump-debug-info.php',
    1 => 'maxdb_dump_debug_info',
  ),
  18 => 
  array (
    0 => 'function.maxdb-embedded-connect.php',
    1 => 'maxdb_embedded_connect',
  ),
  19 => 
  array (
    0 => 'function.maxdb-enable-reads-from-master.php',
    1 => 'maxdb_enable_reads_from_master',
  ),
  20 => 
  array (
    0 => 'function.maxdb-enable-rpl-parse.php',
    1 => 'maxdb_enable_rpl_parse',
  ),
  21 => 
  array (
    0 => 'function.maxdb-errno.php',
    1 => 'maxdb_errno',
  ),
  22 => 
  array (
    0 => 'function.maxdb-error.php',
    1 => 'maxdb_error',
  ),
  23 => 
  array (
    0 => 'function.maxdb-escape-string.php',
    1 => 'maxdb_escape_string',
  ),
  24 => 
  array (
    0 => 'function.maxdb-execute.php',
    1 => 'maxdb_execute',
  ),
  25 => 
  array (
    0 => 'function.maxdb-fetch-array.php',
    1 => 'maxdb_fetch_array',
  ),
  26 => 
  array (
    0 => 'function.maxdb-fetch-assoc.php',
    1 => 'maxdb_fetch_assoc',
  ),
  27 => 
  array (
    0 => 'function.maxdb-fetch-field-direct.php',
    1 => 'maxdb_fetch_field_direct',
  ),
  28 => 
  array (
    0 => 'function.maxdb-fetch-field.php',
    1 => 'maxdb_fetch_field',
  ),
  29 => 
  array (
    0 => 'function.maxdb-fetch-fields.php',
    1 => 'maxdb_fetch_fields',
  ),
  30 => 
  array (
    0 => 'function.maxdb-fetch-lengths.php',
    1 => 'maxdb_fetch_lengths',
  ),
  31 => 
  array (
    0 => 'function.maxdb-fetch-object.php',
    1 => 'maxdb_fetch_object',
  ),
  32 => 
  array (
    0 => 'function.maxdb-fetch-row.php',
    1 => 'maxdb_fetch_row',
  ),
  33 => 
  array (
    0 => 'function.maxdb-fetch.php',
    1 => 'maxdb_fetch',
  ),
  34 => 
  array (
    0 => 'function.maxdb-field-count.php',
    1 => 'maxdb_field_count',
  ),
  35 => 
  array (
    0 => 'function.maxdb-field-seek.php',
    1 => 'maxdb_field_seek',
  ),
  36 => 
  array (
    0 => 'function.maxdb-field-tell.php',
    1 => 'maxdb_field_tell',
  ),
  37 => 
  array (
    0 => 'function.maxdb-free-result.php',
    1 => 'maxdb_free_result',
  ),
  38 => 
  array (
    0 => 'function.maxdb-get-client-info.php',
    1 => 'maxdb_get_client_info',
  ),
  39 => 
  array (
    0 => 'function.maxdb-get-client-version.php',
    1 => 'maxdb_get_client_version',
  ),
  40 => 
  array (
    0 => 'function.maxdb-get-host-info.php',
    1 => 'maxdb_get_host_info',
  ),
  41 => 
  array (
    0 => 'function.maxdb-get-metadata.php',
    1 => 'maxdb_get_metadata',
  ),
  42 => 
  array (
    0 => 'function.maxdb-get-proto-info.php',
    1 => 'maxdb_get_proto_info',
  ),
  43 => 
  array (
    0 => 'function.maxdb-get-server-info.php',
    1 => 'maxdb_get_server_info',
  ),
  44 => 
  array (
    0 => 'function.maxdb-get-server-version.php',
    1 => 'maxdb_get_server_version',
  ),
  45 => 
  array (
    0 => 'function.maxdb-info.php',
    1 => 'maxdb_info',
  ),
  46 => 
  array (
    0 => 'function.maxdb-init.php',
    1 => 'maxdb_init',
  ),
  47 => 
  array (
    0 => 'function.maxdb-insert-id.php',
    1 => 'maxdb_insert_id',
  ),
  48 => 
  array (
    0 => 'function.maxdb-kill.php',
    1 => 'maxdb_kill',
  ),
  49 => 
  array (
    0 => 'function.maxdb-master-query.php',
    1 => 'maxdb_master_query',
  ),
  50 => 
  array (
    0 => 'function.maxdb-more-results.php',
    1 => 'maxdb_more_results',
  ),
  51 => 
  array (
    0 => 'function.maxdb-multi-query.php',
    1 => 'maxdb_multi_query',
  ),
  52 => 
  array (
    0 => 'function.maxdb-next-result.php',
    1 => 'maxdb_next_result',
  ),
  53 => 
  array (
    0 => 'function.maxdb-num-fields.php',
    1 => 'maxdb_num_fields',
  ),
  54 => 
  array (
    0 => 'function.maxdb-num-rows.php',
    1 => 'maxdb_num_rows',
  ),
  55 => 
  array (
    0 => 'function.maxdb-options.php',
    1 => 'maxdb_options',
  ),
  56 => 
  array (
    0 => 'function.maxdb-param-count.php',
    1 => 'maxdb_param_count',
  ),
  57 => 
  array (
    0 => 'function.maxdb-ping.php',
    1 => 'maxdb_ping',
  ),
  58 => 
  array (
    0 => 'function.maxdb-prepare.php',
    1 => 'maxdb_prepare',
  ),
  59 => 
  array (
    0 => 'function.maxdb-query.php',
    1 => 'maxdb_query',
  ),
  60 => 
  array (
    0 => 'function.maxdb-real-connect.php',
    1 => 'maxdb_real_connect',
  ),
  61 => 
  array (
    0 => 'function.maxdb-real-escape-string.php',
    1 => 'maxdb_real_escape_string',
  ),
  62 => 
  array (
    0 => 'function.maxdb-real-query.php',
    1 => 'maxdb_real_query',
  ),
  63 => 
  array (
    0 => 'function.maxdb-report.php',
    1 => 'maxdb_report',
  ),
  64 => 
  array (
    0 => 'function.maxdb-rollback.php',
    1 => 'maxdb_rollback',
  ),
  65 => 
  array (
    0 => 'function.maxdb-rpl-parse-enabled.php',
    1 => 'maxdb_rpl_parse_enabled',
  ),
  66 => 
  array (
    0 => 'function.maxdb-rpl-probe.php',
    1 => 'maxdb_rpl_probe',
  ),
  67 => 
  array (
    0 => 'function.maxdb-rpl-query-type.php',
    1 => 'maxdb_rpl_query_type',
  ),
  68 => 
  array (
    0 => 'function.maxdb-select-db.php',
    1 => 'maxdb_select_db',
  ),
  69 => 
  array (
    0 => 'function.maxdb-send-long-data.php',
    1 => 'maxdb_send_long_data',
  ),
  70 => 
  array (
    0 => 'function.maxdb-send-query.php',
    1 => 'maxdb_send_query',
  ),
  71 => 
  array (
    0 => 'function.maxdb-server-end.php',
    1 => 'maxdb_server_end',
  ),
  72 => 
  array (
    0 => 'function.maxdb-server-init.php',
    1 => 'maxdb_server_init',
  ),
  73 => 
  array (
    0 => 'function.maxdb-set-opt.php',
    1 => 'maxdb_set_opt',
  ),
  74 => 
  array (
    0 => 'function.maxdb-sqlstate.php',
    1 => 'maxdb_sqlstate',
  ),
  75 => 
  array (
    0 => 'function.maxdb-ssl-set.php',
    1 => 'maxdb_ssl_set',
  ),
  76 => 
  array (
    0 => 'function.maxdb-stat.php',
    1 => 'maxdb_stat',
  ),
  77 => 
  array (
    0 => 'function.maxdb-stmt-affected-rows.php',
    1 => 'maxdb_stmt_affected_rows',
  ),
  78 => 
  array (
    0 => 'function.maxdb-stmt-bind-param.php',
    1 => 'maxdb_stmt_bind_param',
  ),
  79 => 
  array (
    0 => 'function.maxdb-stmt-bind-result.php',
    1 => 'maxdb_stmt_bind_result',
  ),
  80 => 
  array (
    0 => 'function.maxdb-stmt-close-long-data.php',
    1 => 'maxdb_stmt_close_long_data',
  ),
  81 => 
  array (
    0 => 'function.maxdb-stmt-close.php',
    1 => 'maxdb_stmt_close',
  ),
  82 => 
  array (
    0 => 'function.maxdb-stmt-data-seek.php',
    1 => 'maxdb_stmt_data_seek',
  ),
  83 => 
  array (
    0 => 'function.maxdb-stmt-errno.php',
    1 => 'maxdb_stmt_errno',
  ),
  84 => 
  array (
    0 => 'function.maxdb-stmt-error.php',
    1 => 'maxdb_stmt_error',
  ),
  85 => 
  array (
    0 => 'function.maxdb-stmt-execute.php',
    1 => 'maxdb_stmt_execute',
  ),
  86 => 
  array (
    0 => 'function.maxdb-stmt-fetch.php',
    1 => 'maxdb_stmt_fetch',
  ),
  87 => 
  array (
    0 => 'function.maxdb-stmt-free-result.php',
    1 => 'maxdb_stmt_free_result',
  ),
  88 => 
  array (
    0 => 'function.maxdb-stmt-init.php',
    1 => 'maxdb_stmt_init',
  ),
  89 => 
  array (
    0 => 'function.maxdb-stmt-num-rows.php',
    1 => 'maxdb_stmt_num_rows',
  ),
  90 => 
  array (
    0 => 'function.maxdb-stmt-param-count.php',
    1 => 'maxdb_stmt_param_count',
  ),
  91 => 
  array (
    0 => 'function.maxdb-stmt-prepare.php',
    1 => 'maxdb_stmt_prepare',
  ),
  92 => 
  array (
    0 => 'function.maxdb-stmt-reset.php',
    1 => 'maxdb_stmt_reset',
  ),
  93 => 
  array (
    0 => 'function.maxdb-stmt-result-metadata.php',
    1 => 'maxdb_stmt_result_metadata',
  ),
  94 => 
  array (
    0 => 'function.maxdb-stmt-send-long-data.php',
    1 => 'maxdb_stmt_send_long_data',
  ),
  95 => 
  array (
    0 => 'function.maxdb-stmt-sqlstate.php',
    1 => 'maxdb_stmt_sqlstate',
  ),
  96 => 
  array (
    0 => 'function.maxdb-stmt-store-result.php',
    1 => 'maxdb_stmt_store_result',
  ),
  97 => 
  array (
    0 => 'function.maxdb-store-result.php',
    1 => 'maxdb_store_result',
  ),
  98 => 
  array (
    0 => 'function.maxdb-thread-id.php',
    1 => 'maxdb_thread_id',
  ),
  99 => 
  array (
    0 => 'function.maxdb-thread-safe.php',
    1 => 'maxdb_thread_safe',
  ),
  100 => 
  array (
    0 => 'function.maxdb-use-result.php',
    1 => 'maxdb_use_result',
  ),
  101 => 
  array (
    0 => 'function.maxdb-warning-count.php',
    1 => 'maxdb_warning_count',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.maxdb.php',
    1 => 'MaxDB',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);