<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.session-cache-expire.php',
    1 => 'session_cache_expire',
  ),
  1 => 
  array (
    0 => 'function.session-cache-limiter.php',
    1 => 'session_cache_limiter',
  ),
  2 => 
  array (
    0 => 'function.session-commit.php',
    1 => 'session_commit',
  ),
  3 => 
  array (
    0 => 'function.session-decode.php',
    1 => 'session_decode',
  ),
  4 => 
  array (
    0 => 'function.session-destroy.php',
    1 => 'session_destroy',
  ),
  5 => 
  array (
    0 => 'function.session-encode.php',
    1 => 'session_encode',
  ),
  6 => 
  array (
    0 => 'function.session-get-cookie-params.php',
    1 => 'session_get_cookie_params',
  ),
  7 => 
  array (
    0 => 'function.session-id.php',
    1 => 'session_id',
  ),
  8 => 
  array (
    0 => 'function.session-is-registered.php',
    1 => 'session_is_registered',
  ),
  9 => 
  array (
    0 => 'function.session-module-name.php',
    1 => 'session_module_name',
  ),
  10 => 
  array (
    0 => 'function.session-name.php',
    1 => 'session_name',
  ),
  11 => 
  array (
    0 => 'function.session-regenerate-id.php',
    1 => 'session_regenerate_id',
  ),
  12 => 
  array (
    0 => 'function.session-register.php',
    1 => 'session_register',
  ),
  13 => 
  array (
    0 => 'function.session-save-path.php',
    1 => 'session_save_path',
  ),
  14 => 
  array (
    0 => 'function.session-set-cookie-params.php',
    1 => 'session_set_cookie_params',
  ),
  15 => 
  array (
    0 => 'function.session-set-save-handler.php',
    1 => 'session_set_save_handler',
  ),
  16 => 
  array (
    0 => 'function.session-start.php',
    1 => 'session_start',
  ),
  17 => 
  array (
    0 => 'function.session-unregister.php',
    1 => 'session_unregister',
  ),
  18 => 
  array (
    0 => 'function.session-unset.php',
    1 => 'session_unset',
  ),
  19 => 
  array (
    0 => 'function.session-write-close.php',
    1 => 'session_write_close',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.session.php',
    1 => 'Sessions',
  ),
  1 => 
  array (
    0 => 'refs.basic.session.php',
    1 => 'Session Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);