<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.id3-get-frame-long-name.php',
    1 => 'id3_get_frame_long_name',
  ),
  1 => 
  array (
    0 => 'function.id3-get-frame-short-name.php',
    1 => 'id3_get_frame_short_name',
  ),
  2 => 
  array (
    0 => 'function.id3-get-genre-id.php',
    1 => 'id3_get_genre_id',
  ),
  3 => 
  array (
    0 => 'function.id3-get-genre-list.php',
    1 => 'id3_get_genre_list',
  ),
  4 => 
  array (
    0 => 'function.id3-get-genre-name.php',
    1 => 'id3_get_genre_name',
  ),
  5 => 
  array (
    0 => 'function.id3-get-tag.php',
    1 => 'id3_get_tag',
  ),
  6 => 
  array (
    0 => 'function.id3-get-version.php',
    1 => 'id3_get_version',
  ),
  7 => 
  array (
    0 => 'function.id3-remove-tag.php',
    1 => 'id3_remove_tag',
  ),
  8 => 
  array (
    0 => 'function.id3-set-tag.php',
    1 => 'id3_set_tag',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.id3.php',
    1 => 'ID3',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);