<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.cyrus-authenticate.php',
    1 => 'cyrus_authenticate',
  ),
  1 => 
  array (
    0 => 'function.cyrus-bind.php',
    1 => 'cyrus_bind',
  ),
  2 => 
  array (
    0 => 'function.cyrus-close.php',
    1 => 'cyrus_close',
  ),
  3 => 
  array (
    0 => 'function.cyrus-connect.php',
    1 => 'cyrus_connect',
  ),
  4 => 
  array (
    0 => 'function.cyrus-query.php',
    1 => 'cyrus_query',
  ),
  5 => 
  array (
    0 => 'function.cyrus-unbind.php',
    1 => 'cyrus_unbind',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cyrus.php',
    1 => 'Cyrus',
  ),
  1 => 
  array (
    0 => 'refs.remote.mail.php',
    1 => 'Mail Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);