<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.base64-decode.php',
    1 => 'base64_decode',
  ),
  1 => 
  array (
    0 => 'function.base64-encode.php',
    1 => 'base64_encode',
  ),
  2 => 
  array (
    0 => 'function.get-headers.php',
    1 => 'get_headers',
  ),
  3 => 
  array (
    0 => 'function.get-meta-tags.php',
    1 => 'get_meta_tags',
  ),
  4 => 
  array (
    0 => 'function.http-build-query.php',
    1 => 'http_build_query',
  ),
  5 => 
  array (
    0 => 'function.parse-url.php',
    1 => 'parse_url',
  ),
  6 => 
  array (
    0 => 'function.rawurldecode.php',
    1 => 'rawurldecode',
  ),
  7 => 
  array (
    0 => 'function.rawurlencode.php',
    1 => 'rawurlencode',
  ),
  8 => 
  array (
    0 => 'function.urldecode.php',
    1 => 'urldecode',
  ),
  9 => 
  array (
    0 => 'function.urlencode.php',
    1 => 'urlencode',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.url.php',
    1 => 'URLs',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);