<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.printer-abort.php',
    1 => 'printer_abort',
  ),
  1 => 
  array (
    0 => 'function.printer-close.php',
    1 => 'printer_close',
  ),
  2 => 
  array (
    0 => 'function.printer-create-brush.php',
    1 => 'printer_create_brush',
  ),
  3 => 
  array (
    0 => 'function.printer-create-dc.php',
    1 => 'printer_create_dc',
  ),
  4 => 
  array (
    0 => 'function.printer-create-font.php',
    1 => 'printer_create_font',
  ),
  5 => 
  array (
    0 => 'function.printer-create-pen.php',
    1 => 'printer_create_pen',
  ),
  6 => 
  array (
    0 => 'function.printer-delete-brush.php',
    1 => 'printer_delete_brush',
  ),
  7 => 
  array (
    0 => 'function.printer-delete-dc.php',
    1 => 'printer_delete_dc',
  ),
  8 => 
  array (
    0 => 'function.printer-delete-font.php',
    1 => 'printer_delete_font',
  ),
  9 => 
  array (
    0 => 'function.printer-delete-pen.php',
    1 => 'printer_delete_pen',
  ),
  10 => 
  array (
    0 => 'function.printer-draw-bmp.php',
    1 => 'printer_draw_bmp',
  ),
  11 => 
  array (
    0 => 'function.printer-draw-chord.php',
    1 => 'printer_draw_chord',
  ),
  12 => 
  array (
    0 => 'function.printer-draw-elipse.php',
    1 => 'printer_draw_elipse',
  ),
  13 => 
  array (
    0 => 'function.printer-draw-line.php',
    1 => 'printer_draw_line',
  ),
  14 => 
  array (
    0 => 'function.printer-draw-pie.php',
    1 => 'printer_draw_pie',
  ),
  15 => 
  array (
    0 => 'function.printer-draw-rectangle.php',
    1 => 'printer_draw_rectangle',
  ),
  16 => 
  array (
    0 => 'function.printer-draw-roundrect.php',
    1 => 'printer_draw_roundrect',
  ),
  17 => 
  array (
    0 => 'function.printer-draw-text.php',
    1 => 'printer_draw_text',
  ),
  18 => 
  array (
    0 => 'function.printer-end-doc.php',
    1 => 'printer_end_doc',
  ),
  19 => 
  array (
    0 => 'function.printer-end-page.php',
    1 => 'printer_end_page',
  ),
  20 => 
  array (
    0 => 'function.printer-get-option.php',
    1 => 'printer_get_option',
  ),
  21 => 
  array (
    0 => 'function.printer-list.php',
    1 => 'printer_list',
  ),
  22 => 
  array (
    0 => 'function.printer-logical-fontheight.php',
    1 => 'printer_logical_fontheight',
  ),
  23 => 
  array (
    0 => 'function.printer-open.php',
    1 => 'printer_open',
  ),
  24 => 
  array (
    0 => 'function.printer-select-brush.php',
    1 => 'printer_select_brush',
  ),
  25 => 
  array (
    0 => 'function.printer-select-font.php',
    1 => 'printer_select_font',
  ),
  26 => 
  array (
    0 => 'function.printer-select-pen.php',
    1 => 'printer_select_pen',
  ),
  27 => 
  array (
    0 => 'function.printer-set-option.php',
    1 => 'printer_set_option',
  ),
  28 => 
  array (
    0 => 'function.printer-start-doc.php',
    1 => 'printer_start_doc',
  ),
  29 => 
  array (
    0 => 'function.printer-start-page.php',
    1 => 'printer_start_page',
  ),
  30 => 
  array (
    0 => 'function.printer-write.php',
    1 => 'printer_write',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.printer.php',
    1 => 'Printer',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);