<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.simplexml-import-dom.php',
    1 => 'simplexml_import_dom',
  ),
  1 => 
  array (
    0 => 'function.simplexml-load-file.php',
    1 => 'simplexml_load_file',
  ),
  2 => 
  array (
    0 => 'function.simplexml-load-string.php',
    1 => 'simplexml_load_string',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.simplexml.php',
    1 => 'SimpleXML',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);