<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.debug-zval-dump.php',
    1 => 'debug_zval_dump',
  ),
  1 => 
  array (
    0 => 'function.doubleval.php',
    1 => 'doubleval',
  ),
  2 => 
  array (
    0 => 'function.empty.php',
    1 => 'empty',
  ),
  3 => 
  array (
    0 => 'function.floatval.php',
    1 => 'floatval',
  ),
  4 => 
  array (
    0 => 'function.get-defined-vars.php',
    1 => 'get_defined_vars',
  ),
  5 => 
  array (
    0 => 'function.get-resource-type.php',
    1 => 'get_resource_type',
  ),
  6 => 
  array (
    0 => 'function.gettype.php',
    1 => 'gettype',
  ),
  7 => 
  array (
    0 => 'function.import-request-variables.php',
    1 => 'import_request_variables',
  ),
  8 => 
  array (
    0 => 'function.intval.php',
    1 => 'intval',
  ),
  9 => 
  array (
    0 => 'function.is-array.php',
    1 => 'is_array',
  ),
  10 => 
  array (
    0 => 'function.is-bool.php',
    1 => 'is_bool',
  ),
  11 => 
  array (
    0 => 'function.is-callable.php',
    1 => 'is_callable',
  ),
  12 => 
  array (
    0 => 'function.is-double.php',
    1 => 'is_double',
  ),
  13 => 
  array (
    0 => 'function.is-float.php',
    1 => 'is_float',
  ),
  14 => 
  array (
    0 => 'function.is-int.php',
    1 => 'is_int',
  ),
  15 => 
  array (
    0 => 'function.is-integer.php',
    1 => 'is_integer',
  ),
  16 => 
  array (
    0 => 'function.is-long.php',
    1 => 'is_long',
  ),
  17 => 
  array (
    0 => 'function.is-null.php',
    1 => 'is_null',
  ),
  18 => 
  array (
    0 => 'function.is-numeric.php',
    1 => 'is_numeric',
  ),
  19 => 
  array (
    0 => 'function.is-object.php',
    1 => 'is_object',
  ),
  20 => 
  array (
    0 => 'function.is-real.php',
    1 => 'is_real',
  ),
  21 => 
  array (
    0 => 'function.is-resource.php',
    1 => 'is_resource',
  ),
  22 => 
  array (
    0 => 'function.is-scalar.php',
    1 => 'is_scalar',
  ),
  23 => 
  array (
    0 => 'function.is-string.php',
    1 => 'is_string',
  ),
  24 => 
  array (
    0 => 'function.isset.php',
    1 => 'isset',
  ),
  25 => 
  array (
    0 => 'function.print-r.php',
    1 => 'print_r',
  ),
  26 => 
  array (
    0 => 'function.serialize.php',
    1 => 'serialize',
  ),
  27 => 
  array (
    0 => 'function.settype.php',
    1 => 'settype',
  ),
  28 => 
  array (
    0 => 'function.strval.php',
    1 => 'strval',
  ),
  29 => 
  array (
    0 => 'function.unserialize.php',
    1 => 'unserialize',
  ),
  30 => 
  array (
    0 => 'function.unset.php',
    1 => 'unset',
  ),
  31 => 
  array (
    0 => 'function.var-dump.php',
    1 => 'var_dump',
  ),
  32 => 
  array (
    0 => 'function.var-export.php',
    1 => 'var_export',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.var.php',
    1 => 'Variable handling',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);