<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.hash-algos.php',
    1 => 'hash_algos',
  ),
  1 => 
  array (
    0 => 'function.hash-copy.php',
    1 => 'hash_copy',
  ),
  2 => 
  array (
    0 => 'function.hash-file.php',
    1 => 'hash_file',
  ),
  3 => 
  array (
    0 => 'function.hash-final.php',
    1 => 'hash_final',
  ),
  4 => 
  array (
    0 => 'function.hash-hmac-file.php',
    1 => 'hash_hmac_file',
  ),
  5 => 
  array (
    0 => 'function.hash-hmac.php',
    1 => 'hash_hmac',
  ),
  6 => 
  array (
    0 => 'function.hash-init.php',
    1 => 'hash_init',
  ),
  7 => 
  array (
    0 => 'function.hash-update-file.php',
    1 => 'hash_update_file',
  ),
  8 => 
  array (
    0 => 'function.hash-update-stream.php',
    1 => 'hash_update_stream',
  ),
  9 => 
  array (
    0 => 'function.hash-update.php',
    1 => 'hash_update',
  ),
  10 => 
  array (
    0 => 'function.hash.php',
    1 => 'hash',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.hash.php',
    1 => 'Hash',
  ),
  1 => 
  array (
    0 => 'refs.crypto.php',
    1 => 'Cryptography Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);