<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.gmp-abs.php',
    1 => 'gmp_abs',
  ),
  1 => 
  array (
    0 => 'function.gmp-add.php',
    1 => 'gmp_add',
  ),
  2 => 
  array (
    0 => 'function.gmp-and.php',
    1 => 'gmp_and',
  ),
  3 => 
  array (
    0 => 'function.gmp-clrbit.php',
    1 => 'gmp_clrbit',
  ),
  4 => 
  array (
    0 => 'function.gmp-cmp.php',
    1 => 'gmp_cmp',
  ),
  5 => 
  array (
    0 => 'function.gmp-com.php',
    1 => 'gmp_com',
  ),
  6 => 
  array (
    0 => 'function.gmp-div-q.php',
    1 => 'gmp_div_q',
  ),
  7 => 
  array (
    0 => 'function.gmp-div-qr.php',
    1 => 'gmp_div_qr',
  ),
  8 => 
  array (
    0 => 'function.gmp-div-r.php',
    1 => 'gmp_div_r',
  ),
  9 => 
  array (
    0 => 'function.gmp-div.php',
    1 => 'gmp_div',
  ),
  10 => 
  array (
    0 => 'function.gmp-divexact.php',
    1 => 'gmp_divexact',
  ),
  11 => 
  array (
    0 => 'function.gmp-fact.php',
    1 => 'gmp_fact',
  ),
  12 => 
  array (
    0 => 'function.gmp-gcd.php',
    1 => 'gmp_gcd',
  ),
  13 => 
  array (
    0 => 'function.gmp-gcdext.php',
    1 => 'gmp_gcdext',
  ),
  14 => 
  array (
    0 => 'function.gmp-hamdist.php',
    1 => 'gmp_hamdist',
  ),
  15 => 
  array (
    0 => 'function.gmp-init.php',
    1 => 'gmp_init',
  ),
  16 => 
  array (
    0 => 'function.gmp-intval.php',
    1 => 'gmp_intval',
  ),
  17 => 
  array (
    0 => 'function.gmp-invert.php',
    1 => 'gmp_invert',
  ),
  18 => 
  array (
    0 => 'function.gmp-jacobi.php',
    1 => 'gmp_jacobi',
  ),
  19 => 
  array (
    0 => 'function.gmp-legendre.php',
    1 => 'gmp_legendre',
  ),
  20 => 
  array (
    0 => 'function.gmp-mod.php',
    1 => 'gmp_mod',
  ),
  21 => 
  array (
    0 => 'function.gmp-mul.php',
    1 => 'gmp_mul',
  ),
  22 => 
  array (
    0 => 'function.gmp-neg.php',
    1 => 'gmp_neg',
  ),
  23 => 
  array (
    0 => 'function.gmp-nextprime.php',
    1 => 'gmp_nextprime',
  ),
  24 => 
  array (
    0 => 'function.gmp-or.php',
    1 => 'gmp_or',
  ),
  25 => 
  array (
    0 => 'function.gmp-perfect-square.php',
    1 => 'gmp_perfect_square',
  ),
  26 => 
  array (
    0 => 'function.gmp-popcount.php',
    1 => 'gmp_popcount',
  ),
  27 => 
  array (
    0 => 'function.gmp-pow.php',
    1 => 'gmp_pow',
  ),
  28 => 
  array (
    0 => 'function.gmp-powm.php',
    1 => 'gmp_powm',
  ),
  29 => 
  array (
    0 => 'function.gmp-prob-prime.php',
    1 => 'gmp_prob_prime',
  ),
  30 => 
  array (
    0 => 'function.gmp-random.php',
    1 => 'gmp_random',
  ),
  31 => 
  array (
    0 => 'function.gmp-scan0.php',
    1 => 'gmp_scan0',
  ),
  32 => 
  array (
    0 => 'function.gmp-scan1.php',
    1 => 'gmp_scan1',
  ),
  33 => 
  array (
    0 => 'function.gmp-setbit.php',
    1 => 'gmp_setbit',
  ),
  34 => 
  array (
    0 => 'function.gmp-sign.php',
    1 => 'gmp_sign',
  ),
  35 => 
  array (
    0 => 'function.gmp-sqrt.php',
    1 => 'gmp_sqrt',
  ),
  36 => 
  array (
    0 => 'function.gmp-sqrtrem.php',
    1 => 'gmp_sqrtrem',
  ),
  37 => 
  array (
    0 => 'function.gmp-strval.php',
    1 => 'gmp_strval',
  ),
  38 => 
  array (
    0 => 'function.gmp-sub.php',
    1 => 'gmp_sub',
  ),
  39 => 
  array (
    0 => 'function.gmp-testbit.php',
    1 => 'gmp_testbit',
  ),
  40 => 
  array (
    0 => 'function.gmp-xor.php',
    1 => 'gmp_xor',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gmp.php',
    1 => 'GMP',
  ),
  1 => 
  array (
    0 => 'refs.math.php',
    1 => 'Mathematical Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);