<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ming-keypress.php',
    1 => 'ming_keypress',
  ),
  1 => 
  array (
    0 => 'function.ming-setcubicthreshold.php',
    1 => 'ming_setcubicthreshold',
  ),
  2 => 
  array (
    0 => 'function.ming-setscale.php',
    1 => 'ming_setscale',
  ),
  3 => 
  array (
    0 => 'function.ming-setswfcompression.php',
    1 => 'ming_setswfcompression',
  ),
  4 => 
  array (
    0 => 'function.ming-useconstants.php',
    1 => 'ming_useconstants',
  ),
  5 => 
  array (
    0 => 'function.ming-useswfversion.php',
    1 => 'ming_useswfversion',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);