<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.geoip-continent-code-by-name.php',
    1 => 'geoip_continent_code_by_name',
  ),
  1 => 
  array (
    0 => 'function.geoip-country-code-by-name.php',
    1 => 'geoip_country_code_by_name',
  ),
  2 => 
  array (
    0 => 'function.geoip-country-code3-by-name.php',
    1 => 'geoip_country_code3_by_name',
  ),
  3 => 
  array (
    0 => 'function.geoip-country-name-by-name.php',
    1 => 'geoip_country_name_by_name',
  ),
  4 => 
  array (
    0 => 'function.geoip-database-info.php',
    1 => 'geoip_database_info',
  ),
  5 => 
  array (
    0 => 'function.geoip-db-avail.php',
    1 => 'geoip_db_avail',
  ),
  6 => 
  array (
    0 => 'function.geoip-db-filename.php',
    1 => 'geoip_db_filename',
  ),
  7 => 
  array (
    0 => 'function.geoip-db-get-all-info.php',
    1 => 'geoip_db_get_all_info',
  ),
  8 => 
  array (
    0 => 'function.geoip-id-by-name.php',
    1 => 'geoip_id_by_name',
  ),
  9 => 
  array (
    0 => 'function.geoip-isp-by-name.php',
    1 => 'geoip_isp_by_name',
  ),
  10 => 
  array (
    0 => 'function.geoip-org-by-name.php',
    1 => 'geoip_org_by_name',
  ),
  11 => 
  array (
    0 => 'function.geoip-record-by-name.php',
    1 => 'geoip_record_by_name',
  ),
  12 => 
  array (
    0 => 'function.geoip-region-by-name.php',
    1 => 'geoip_region_by_name',
  ),
  13 => 
  array (
    0 => 'function.geoip-region-name-by-code.php',
    1 => 'geoip_region_name_by_code',
  ),
  14 => 
  array (
    0 => 'function.geoip-time-zone-by-country-and-region.php',
    1 => 'geoip_time_zone_by_country_and_region',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.geoip.php',
    1 => 'GeoIP',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);