<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.parsekit-compile-file.php',
    1 => 'parsekit_compile_file',
  ),
  1 => 
  array (
    0 => 'function.parsekit-compile-string.php',
    1 => 'parsekit_compile_string',
  ),
  2 => 
  array (
    0 => 'function.parsekit-func-arginfo.php',
    1 => 'parsekit_func_arginfo',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.parsekit.php',
    1 => 'Parsekit',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);