<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.xattr-get.php',
    1 => 'xattr_get',
  ),
  1 => 
  array (
    0 => 'function.xattr-list.php',
    1 => 'xattr_list',
  ),
  2 => 
  array (
    0 => 'function.xattr-remove.php',
    1 => 'xattr_remove',
  ),
  3 => 
  array (
    0 => 'function.xattr-set.php',
    1 => 'xattr_set',
  ),
  4 => 
  array (
    0 => 'function.xattr-supported.php',
    1 => 'xattr_supported',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.xattr.php',
    1 => 'xattr',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.file.php',
    1 => 'File System Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);