<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.judy-type.php',
    1 => 'judy_type',
  ),
  1 => 
  array (
    0 => 'function.judy-version.php',
    1 => 'judy_version',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.judy.php',
    1 => 'Judy',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);