<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ezmlm-hash.php',
    1 => 'ezmlm_hash',
  ),
  1 => 
  array (
    0 => 'function.mail.php',
    1 => 'mail',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mail.php',
    1 => 'Mail',
  ),
  1 => 
  array (
    0 => 'refs.remote.mail.php',
    1 => 'Mail Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);