<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.swf-actiongeturl.php',
    1 => 'swf_actiongeturl',
  ),
  1 => 
  array (
    0 => 'function.swf-actiongotoframe.php',
    1 => 'swf_actiongotoframe',
  ),
  2 => 
  array (
    0 => 'function.swf-actiongotolabel.php',
    1 => 'swf_actiongotolabel',
  ),
  3 => 
  array (
    0 => 'function.swf-actionnextframe.php',
    1 => 'swf_actionnextframe',
  ),
  4 => 
  array (
    0 => 'function.swf-actionplay.php',
    1 => 'swf_actionplay',
  ),
  5 => 
  array (
    0 => 'function.swf-actionprevframe.php',
    1 => 'swf_actionprevframe',
  ),
  6 => 
  array (
    0 => 'function.swf-actionsettarget.php',
    1 => 'swf_actionsettarget',
  ),
  7 => 
  array (
    0 => 'function.swf-actionstop.php',
    1 => 'swf_actionstop',
  ),
  8 => 
  array (
    0 => 'function.swf-actiontogglequality.php',
    1 => 'swf_actiontogglequality',
  ),
  9 => 
  array (
    0 => 'function.swf-actionwaitforframe.php',
    1 => 'swf_actionwaitforframe',
  ),
  10 => 
  array (
    0 => 'function.swf-addbuttonrecord.php',
    1 => 'swf_addbuttonrecord',
  ),
  11 => 
  array (
    0 => 'function.swf-addcolor.php',
    1 => 'swf_addcolor',
  ),
  12 => 
  array (
    0 => 'function.swf-closefile.php',
    1 => 'swf_closefile',
  ),
  13 => 
  array (
    0 => 'function.swf-definebitmap.php',
    1 => 'swf_definebitmap',
  ),
  14 => 
  array (
    0 => 'function.swf-definefont.php',
    1 => 'swf_definefont',
  ),
  15 => 
  array (
    0 => 'function.swf-defineline.php',
    1 => 'swf_defineline',
  ),
  16 => 
  array (
    0 => 'function.swf-definepoly.php',
    1 => 'swf_definepoly',
  ),
  17 => 
  array (
    0 => 'function.swf-definerect.php',
    1 => 'swf_definerect',
  ),
  18 => 
  array (
    0 => 'function.swf-definetext.php',
    1 => 'swf_definetext',
  ),
  19 => 
  array (
    0 => 'function.swf-endbutton.php',
    1 => 'swf_endbutton',
  ),
  20 => 
  array (
    0 => 'function.swf-enddoaction.php',
    1 => 'swf_enddoaction',
  ),
  21 => 
  array (
    0 => 'function.swf-endshape.php',
    1 => 'swf_endshape',
  ),
  22 => 
  array (
    0 => 'function.swf-endsymbol.php',
    1 => 'swf_endsymbol',
  ),
  23 => 
  array (
    0 => 'function.swf-fontsize.php',
    1 => 'swf_fontsize',
  ),
  24 => 
  array (
    0 => 'function.swf-fontslant.php',
    1 => 'swf_fontslant',
  ),
  25 => 
  array (
    0 => 'function.swf-fonttracking.php',
    1 => 'swf_fonttracking',
  ),
  26 => 
  array (
    0 => 'function.swf-getbitmapinfo.php',
    1 => 'swf_getbitmapinfo',
  ),
  27 => 
  array (
    0 => 'function.swf-getfontinfo.php',
    1 => 'swf_getfontinfo',
  ),
  28 => 
  array (
    0 => 'function.swf-getframe.php',
    1 => 'swf_getframe',
  ),
  29 => 
  array (
    0 => 'function.swf-labelframe.php',
    1 => 'swf_labelframe',
  ),
  30 => 
  array (
    0 => 'function.swf-lookat.php',
    1 => 'swf_lookat',
  ),
  31 => 
  array (
    0 => 'function.swf-modifyobject.php',
    1 => 'swf_modifyobject',
  ),
  32 => 
  array (
    0 => 'function.swf-mulcolor.php',
    1 => 'swf_mulcolor',
  ),
  33 => 
  array (
    0 => 'function.swf-nextid.php',
    1 => 'swf_nextid',
  ),
  34 => 
  array (
    0 => 'function.swf-oncondition.php',
    1 => 'swf_oncondition',
  ),
  35 => 
  array (
    0 => 'function.swf-openfile.php',
    1 => 'swf_openfile',
  ),
  36 => 
  array (
    0 => 'function.swf-ortho2.php',
    1 => 'swf_ortho2',
  ),
  37 => 
  array (
    0 => 'function.swf-ortho.php',
    1 => 'swf_ortho',
  ),
  38 => 
  array (
    0 => 'function.swf-perspective.php',
    1 => 'swf_perspective',
  ),
  39 => 
  array (
    0 => 'function.swf-placeobject.php',
    1 => 'swf_placeobject',
  ),
  40 => 
  array (
    0 => 'function.swf-polarview.php',
    1 => 'swf_polarview',
  ),
  41 => 
  array (
    0 => 'function.swf-popmatrix.php',
    1 => 'swf_popmatrix',
  ),
  42 => 
  array (
    0 => 'function.swf-posround.php',
    1 => 'swf_posround',
  ),
  43 => 
  array (
    0 => 'function.swf-pushmatrix.php',
    1 => 'swf_pushmatrix',
  ),
  44 => 
  array (
    0 => 'function.swf-removeobject.php',
    1 => 'swf_removeobject',
  ),
  45 => 
  array (
    0 => 'function.swf-rotate.php',
    1 => 'swf_rotate',
  ),
  46 => 
  array (
    0 => 'function.swf-scale.php',
    1 => 'swf_scale',
  ),
  47 => 
  array (
    0 => 'function.swf-setfont.php',
    1 => 'swf_setfont',
  ),
  48 => 
  array (
    0 => 'function.swf-setframe.php',
    1 => 'swf_setframe',
  ),
  49 => 
  array (
    0 => 'function.swf-shapearc.php',
    1 => 'swf_shapearc',
  ),
  50 => 
  array (
    0 => 'function.swf-shapecurveto3.php',
    1 => 'swf_shapecurveto3',
  ),
  51 => 
  array (
    0 => 'function.swf-shapecurveto.php',
    1 => 'swf_shapecurveto',
  ),
  52 => 
  array (
    0 => 'function.swf-shapefillbitmapclip.php',
    1 => 'swf_shapefillbitmapclip',
  ),
  53 => 
  array (
    0 => 'function.swf-shapefillbitmaptile.php',
    1 => 'swf_shapefillbitmaptile',
  ),
  54 => 
  array (
    0 => 'function.swf-shapefilloff.php',
    1 => 'swf_shapefilloff',
  ),
  55 => 
  array (
    0 => 'function.swf-shapefillsolid.php',
    1 => 'swf_shapefillsolid',
  ),
  56 => 
  array (
    0 => 'function.swf-shapelinesolid.php',
    1 => 'swf_shapelinesolid',
  ),
  57 => 
  array (
    0 => 'function.swf-shapelineto.php',
    1 => 'swf_shapelineto',
  ),
  58 => 
  array (
    0 => 'function.swf-shapemoveto.php',
    1 => 'swf_shapemoveto',
  ),
  59 => 
  array (
    0 => 'function.swf-showframe.php',
    1 => 'swf_showframe',
  ),
  60 => 
  array (
    0 => 'function.swf-startbutton.php',
    1 => 'swf_startbutton',
  ),
  61 => 
  array (
    0 => 'function.swf-startdoaction.php',
    1 => 'swf_startdoaction',
  ),
  62 => 
  array (
    0 => 'function.swf-startshape.php',
    1 => 'swf_startshape',
  ),
  63 => 
  array (
    0 => 'function.swf-startsymbol.php',
    1 => 'swf_startsymbol',
  ),
  64 => 
  array (
    0 => 'function.swf-textwidth.php',
    1 => 'swf_textwidth',
  ),
  65 => 
  array (
    0 => 'function.swf-translate.php',
    1 => 'swf_translate',
  ),
  66 => 
  array (
    0 => 'function.swf-viewport.php',
    1 => 'swf_viewport',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.swf.php',
    1 => 'SWF',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);