<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.mailparse-determine-best-xfer-encoding.php',
    1 => 'mailparse_determine_best_xfer_encoding',
  ),
  1 => 
  array (
    0 => 'function.mailparse-msg-create.php',
    1 => 'mailparse_msg_create',
  ),
  2 => 
  array (
    0 => 'function.mailparse-msg-extract-part-file.php',
    1 => 'mailparse_msg_extract_part_file',
  ),
  3 => 
  array (
    0 => 'function.mailparse-msg-extract-part.php',
    1 => 'mailparse_msg_extract_part',
  ),
  4 => 
  array (
    0 => 'function.mailparse-msg-extract-whole-part-file.php',
    1 => 'mailparse_msg_extract_whole_part_file',
  ),
  5 => 
  array (
    0 => 'function.mailparse-msg-free.php',
    1 => 'mailparse_msg_free',
  ),
  6 => 
  array (
    0 => 'function.mailparse-msg-get-part-data.php',
    1 => 'mailparse_msg_get_part_data',
  ),
  7 => 
  array (
    0 => 'function.mailparse-msg-get-part.php',
    1 => 'mailparse_msg_get_part',
  ),
  8 => 
  array (
    0 => 'function.mailparse-msg-get-structure.php',
    1 => 'mailparse_msg_get_structure',
  ),
  9 => 
  array (
    0 => 'function.mailparse-msg-parse-file.php',
    1 => 'mailparse_msg_parse_file',
  ),
  10 => 
  array (
    0 => 'function.mailparse-msg-parse.php',
    1 => 'mailparse_msg_parse',
  ),
  11 => 
  array (
    0 => 'function.mailparse-rfc822-parse-addresses.php',
    1 => 'mailparse_rfc822_parse_addresses',
  ),
  12 => 
  array (
    0 => 'function.mailparse-stream-encode.php',
    1 => 'mailparse_stream_encode',
  ),
  13 => 
  array (
    0 => 'function.mailparse-uudecode-all.php',
    1 => 'mailparse_uudecode_all',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mailparse.php',
    1 => 'Mailparse',
  ),
  1 => 
  array (
    0 => 'refs.remote.mail.php',
    1 => 'Mail Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);