<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.mysqli-bind-param.php',
    1 => 'mysqli_bind_param',
  ),
  1 => 
  array (
    0 => 'function.mysqli-bind-result.php',
    1 => 'mysqli_bind_result',
  ),
  2 => 
  array (
    0 => 'function.mysqli-client-encoding.php',
    1 => 'mysqli_client_encoding',
  ),
  3 => 
  array (
    0 => 'function.mysqli-connect.php',
    1 => 'mysqli_connect',
  ),
  4 => 
  array (
    0 => 'function.mysqli-disable-reads-from-master.php',
    1 => 'mysqli_disable_reads_from_master',
  ),
  5 => 
  array (
    0 => 'function.mysqli-disable-rpl-parse.php',
    1 => 'mysqli_disable_rpl_parse',
  ),
  6 => 
  array (
    0 => 'function.mysqli-enable-reads-from-master.php',
    1 => 'mysqli_enable_reads_from_master',
  ),
  7 => 
  array (
    0 => 'function.mysqli-enable-rpl-parse.php',
    1 => 'mysqli_enable_rpl_parse',
  ),
  8 => 
  array (
    0 => 'function.mysqli-escape-string.php',
    1 => 'mysqli_escape_string',
  ),
  9 => 
  array (
    0 => 'function.mysqli-execute.php',
    1 => 'mysqli_execute',
  ),
  10 => 
  array (
    0 => 'function.mysqli-fetch.php',
    1 => 'mysqli_fetch',
  ),
  11 => 
  array (
    0 => 'mysqli.get-cache-stats.php',
    1 => 'mysqli_get_cache_stats',
  ),
  12 => 
  array (
    0 => 'function.mysqli-get-metadata.php',
    1 => 'mysqli_get_metadata',
  ),
  13 => 
  array (
    0 => 'function.mysqli-master-query.php',
    1 => 'mysqli_master_query',
  ),
  14 => 
  array (
    0 => 'function.mysqli-param-count.php',
    1 => 'mysqli_param_count',
  ),
  15 => 
  array (
    0 => 'function.mysqli-report.php',
    1 => 'mysqli_report',
  ),
  16 => 
  array (
    0 => 'function.mysqli-rpl-parse-enabled.php',
    1 => 'mysqli_rpl_parse_enabled',
  ),
  17 => 
  array (
    0 => 'function.mysqli-rpl-probe.php',
    1 => 'mysqli_rpl_probe',
  ),
  18 => 
  array (
    0 => 'function.mysqli-rpl-query-type.php',
    1 => 'mysqli_rpl_query_type',
  ),
  19 => 
  array (
    0 => 'function.mysqli-send-long-data.php',
    1 => 'mysqli_send_long_data',
  ),
  20 => 
  array (
    0 => 'function.mysqli-send-query.php',
    1 => 'mysqli_send_query',
  ),
  21 => 
  array (
    0 => 'function.mysqli-set-opt.php',
    1 => 'mysqli_set_opt',
  ),
  22 => 
  array (
    0 => 'function.mysqli-slave-query.php',
    1 => 'mysqli_slave_query',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mysqli.php',
    1 => 'Mysqli',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);