<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ps-add-bookmark.php',
    1 => 'ps_add_bookmark',
  ),
  1 => 
  array (
    0 => 'function.ps-add-launchlink.php',
    1 => 'ps_add_launchlink',
  ),
  2 => 
  array (
    0 => 'function.ps-add-locallink.php',
    1 => 'ps_add_locallink',
  ),
  3 => 
  array (
    0 => 'function.ps-add-note.php',
    1 => 'ps_add_note',
  ),
  4 => 
  array (
    0 => 'function.ps-add-pdflink.php',
    1 => 'ps_add_pdflink',
  ),
  5 => 
  array (
    0 => 'function.ps-add-weblink.php',
    1 => 'ps_add_weblink',
  ),
  6 => 
  array (
    0 => 'function.ps-arc.php',
    1 => 'ps_arc',
  ),
  7 => 
  array (
    0 => 'function.ps-arcn.php',
    1 => 'ps_arcn',
  ),
  8 => 
  array (
    0 => 'function.ps-begin-page.php',
    1 => 'ps_begin_page',
  ),
  9 => 
  array (
    0 => 'function.ps-begin-pattern.php',
    1 => 'ps_begin_pattern',
  ),
  10 => 
  array (
    0 => 'function.ps-begin-template.php',
    1 => 'ps_begin_template',
  ),
  11 => 
  array (
    0 => 'function.ps-circle.php',
    1 => 'ps_circle',
  ),
  12 => 
  array (
    0 => 'function.ps-clip.php',
    1 => 'ps_clip',
  ),
  13 => 
  array (
    0 => 'function.ps-close-image.php',
    1 => 'ps_close_image',
  ),
  14 => 
  array (
    0 => 'function.ps-close.php',
    1 => 'ps_close',
  ),
  15 => 
  array (
    0 => 'function.ps-closepath-stroke.php',
    1 => 'ps_closepath_stroke',
  ),
  16 => 
  array (
    0 => 'function.ps-closepath.php',
    1 => 'ps_closepath',
  ),
  17 => 
  array (
    0 => 'function.ps-continue-text.php',
    1 => 'ps_continue_text',
  ),
  18 => 
  array (
    0 => 'function.ps-curveto.php',
    1 => 'ps_curveto',
  ),
  19 => 
  array (
    0 => 'function.ps-delete.php',
    1 => 'ps_delete',
  ),
  20 => 
  array (
    0 => 'function.ps-end-page.php',
    1 => 'ps_end_page',
  ),
  21 => 
  array (
    0 => 'function.ps-end-pattern.php',
    1 => 'ps_end_pattern',
  ),
  22 => 
  array (
    0 => 'function.ps-end-template.php',
    1 => 'ps_end_template',
  ),
  23 => 
  array (
    0 => 'function.ps-fill-stroke.php',
    1 => 'ps_fill_stroke',
  ),
  24 => 
  array (
    0 => 'function.ps-fill.php',
    1 => 'ps_fill',
  ),
  25 => 
  array (
    0 => 'function.ps-findfont.php',
    1 => 'ps_findfont',
  ),
  26 => 
  array (
    0 => 'function.ps-get-buffer.php',
    1 => 'ps_get_buffer',
  ),
  27 => 
  array (
    0 => 'function.ps-get-parameter.php',
    1 => 'ps_get_parameter',
  ),
  28 => 
  array (
    0 => 'function.ps-get-value.php',
    1 => 'ps_get_value',
  ),
  29 => 
  array (
    0 => 'function.ps-hyphenate.php',
    1 => 'ps_hyphenate',
  ),
  30 => 
  array (
    0 => 'function.ps-include-file.php',
    1 => 'ps_include_file',
  ),
  31 => 
  array (
    0 => 'function.ps-lineto.php',
    1 => 'ps_lineto',
  ),
  32 => 
  array (
    0 => 'function.ps-makespotcolor.php',
    1 => 'ps_makespotcolor',
  ),
  33 => 
  array (
    0 => 'function.ps-moveto.php',
    1 => 'ps_moveto',
  ),
  34 => 
  array (
    0 => 'function.ps-new.php',
    1 => 'ps_new',
  ),
  35 => 
  array (
    0 => 'function.ps-open-file.php',
    1 => 'ps_open_file',
  ),
  36 => 
  array (
    0 => 'function.ps-open-image-file.php',
    1 => 'ps_open_image_file',
  ),
  37 => 
  array (
    0 => 'function.ps-open-image.php',
    1 => 'ps_open_image',
  ),
  38 => 
  array (
    0 => 'function.ps-open-memory-image.php',
    1 => 'ps_open_memory_image',
  ),
  39 => 
  array (
    0 => 'function.ps-place-image.php',
    1 => 'ps_place_image',
  ),
  40 => 
  array (
    0 => 'function.ps-rect.php',
    1 => 'ps_rect',
  ),
  41 => 
  array (
    0 => 'function.ps-restore.php',
    1 => 'ps_restore',
  ),
  42 => 
  array (
    0 => 'function.ps-rotate.php',
    1 => 'ps_rotate',
  ),
  43 => 
  array (
    0 => 'function.ps-save.php',
    1 => 'ps_save',
  ),
  44 => 
  array (
    0 => 'function.ps-scale.php',
    1 => 'ps_scale',
  ),
  45 => 
  array (
    0 => 'function.ps-set-border-color.php',
    1 => 'ps_set_border_color',
  ),
  46 => 
  array (
    0 => 'function.ps-set-border-dash.php',
    1 => 'ps_set_border_dash',
  ),
  47 => 
  array (
    0 => 'function.ps-set-border-style.php',
    1 => 'ps_set_border_style',
  ),
  48 => 
  array (
    0 => 'function.ps-set-info.php',
    1 => 'ps_set_info',
  ),
  49 => 
  array (
    0 => 'function.ps-set-parameter.php',
    1 => 'ps_set_parameter',
  ),
  50 => 
  array (
    0 => 'function.ps-set-text-pos.php',
    1 => 'ps_set_text_pos',
  ),
  51 => 
  array (
    0 => 'function.ps-set-value.php',
    1 => 'ps_set_value',
  ),
  52 => 
  array (
    0 => 'function.ps-setcolor.php',
    1 => 'ps_setcolor',
  ),
  53 => 
  array (
    0 => 'function.ps-setdash.php',
    1 => 'ps_setdash',
  ),
  54 => 
  array (
    0 => 'function.ps-setflat.php',
    1 => 'ps_setflat',
  ),
  55 => 
  array (
    0 => 'function.ps-setfont.php',
    1 => 'ps_setfont',
  ),
  56 => 
  array (
    0 => 'function.ps-setgray.php',
    1 => 'ps_setgray',
  ),
  57 => 
  array (
    0 => 'function.ps-setlinecap.php',
    1 => 'ps_setlinecap',
  ),
  58 => 
  array (
    0 => 'function.ps-setlinejoin.php',
    1 => 'ps_setlinejoin',
  ),
  59 => 
  array (
    0 => 'function.ps-setlinewidth.php',
    1 => 'ps_setlinewidth',
  ),
  60 => 
  array (
    0 => 'function.ps-setmiterlimit.php',
    1 => 'ps_setmiterlimit',
  ),
  61 => 
  array (
    0 => 'function.ps-setoverprintmode.php',
    1 => 'ps_setoverprintmode',
  ),
  62 => 
  array (
    0 => 'function.ps-setpolydash.php',
    1 => 'ps_setpolydash',
  ),
  63 => 
  array (
    0 => 'function.ps-shading-pattern.php',
    1 => 'ps_shading_pattern',
  ),
  64 => 
  array (
    0 => 'function.ps-shading.php',
    1 => 'ps_shading',
  ),
  65 => 
  array (
    0 => 'function.ps-shfill.php',
    1 => 'ps_shfill',
  ),
  66 => 
  array (
    0 => 'function.ps-show-boxed.php',
    1 => 'ps_show_boxed',
  ),
  67 => 
  array (
    0 => 'function.ps-show-xy2.php',
    1 => 'ps_show_xy2',
  ),
  68 => 
  array (
    0 => 'function.ps-show-xy.php',
    1 => 'ps_show_xy',
  ),
  69 => 
  array (
    0 => 'function.ps-show2.php',
    1 => 'ps_show2',
  ),
  70 => 
  array (
    0 => 'function.ps-show.php',
    1 => 'ps_show',
  ),
  71 => 
  array (
    0 => 'function.ps-string-geometry.php',
    1 => 'ps_string_geometry',
  ),
  72 => 
  array (
    0 => 'function.ps-stringwidth.php',
    1 => 'ps_stringwidth',
  ),
  73 => 
  array (
    0 => 'function.ps-stroke.php',
    1 => 'ps_stroke',
  ),
  74 => 
  array (
    0 => 'function.ps-symbol-name.php',
    1 => 'ps_symbol_name',
  ),
  75 => 
  array (
    0 => 'function.ps-symbol-width.php',
    1 => 'ps_symbol_width',
  ),
  76 => 
  array (
    0 => 'function.ps-symbol.php',
    1 => 'ps_symbol',
  ),
  77 => 
  array (
    0 => 'function.ps-translate.php',
    1 => 'ps_translate',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ps.php',
    1 => 'PS',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);