<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.socket-accept.php',
    1 => 'socket_accept',
  ),
  1 => 
  array (
    0 => 'function.socket-bind.php',
    1 => 'socket_bind',
  ),
  2 => 
  array (
    0 => 'function.socket-clear-error.php',
    1 => 'socket_clear_error',
  ),
  3 => 
  array (
    0 => 'function.socket-close.php',
    1 => 'socket_close',
  ),
  4 => 
  array (
    0 => 'function.socket-connect.php',
    1 => 'socket_connect',
  ),
  5 => 
  array (
    0 => 'function.socket-create-listen.php',
    1 => 'socket_create_listen',
  ),
  6 => 
  array (
    0 => 'function.socket-create-pair.php',
    1 => 'socket_create_pair',
  ),
  7 => 
  array (
    0 => 'function.socket-create.php',
    1 => 'socket_create',
  ),
  8 => 
  array (
    0 => 'function.socket-get-option.php',
    1 => 'socket_get_option',
  ),
  9 => 
  array (
    0 => 'function.socket-getpeername.php',
    1 => 'socket_getpeername',
  ),
  10 => 
  array (
    0 => 'function.socket-getsockname.php',
    1 => 'socket_getsockname',
  ),
  11 => 
  array (
    0 => 'function.socket-last-error.php',
    1 => 'socket_last_error',
  ),
  12 => 
  array (
    0 => 'function.socket-listen.php',
    1 => 'socket_listen',
  ),
  13 => 
  array (
    0 => 'function.socket-read.php',
    1 => 'socket_read',
  ),
  14 => 
  array (
    0 => 'function.socket-recv.php',
    1 => 'socket_recv',
  ),
  15 => 
  array (
    0 => 'function.socket-recvfrom.php',
    1 => 'socket_recvfrom',
  ),
  16 => 
  array (
    0 => 'function.socket-select.php',
    1 => 'socket_select',
  ),
  17 => 
  array (
    0 => 'function.socket-send.php',
    1 => 'socket_send',
  ),
  18 => 
  array (
    0 => 'function.socket-sendto.php',
    1 => 'socket_sendto',
  ),
  19 => 
  array (
    0 => 'function.socket-set-block.php',
    1 => 'socket_set_block',
  ),
  20 => 
  array (
    0 => 'function.socket-set-nonblock.php',
    1 => 'socket_set_nonblock',
  ),
  21 => 
  array (
    0 => 'function.socket-set-option.php',
    1 => 'socket_set_option',
  ),
  22 => 
  array (
    0 => 'function.socket-shutdown.php',
    1 => 'socket_shutdown',
  ),
  23 => 
  array (
    0 => 'function.socket-strerror.php',
    1 => 'socket_strerror',
  ),
  24 => 
  array (
    0 => 'function.socket-write.php',
    1 => 'socket_write',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sockets.php',
    1 => 'Sockets',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);