<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.gd-info.php',
    1 => 'gd_info',
  ),
  1 => 
  array (
    0 => 'function.getimagesize.php',
    1 => 'getimagesize',
  ),
  2 => 
  array (
    0 => 'function.image-type-to-extension.php',
    1 => 'image_type_to_extension',
  ),
  3 => 
  array (
    0 => 'function.image-type-to-mime-type.php',
    1 => 'image_type_to_mime_type',
  ),
  4 => 
  array (
    0 => 'function.image2wbmp.php',
    1 => 'image2wbmp',
  ),
  5 => 
  array (
    0 => 'function.imagealphablending.php',
    1 => 'imagealphablending',
  ),
  6 => 
  array (
    0 => 'function.imageantialias.php',
    1 => 'imageantialias',
  ),
  7 => 
  array (
    0 => 'function.imagearc.php',
    1 => 'imagearc',
  ),
  8 => 
  array (
    0 => 'function.imagechar.php',
    1 => 'imagechar',
  ),
  9 => 
  array (
    0 => 'function.imagecharup.php',
    1 => 'imagecharup',
  ),
  10 => 
  array (
    0 => 'function.imagecolorallocate.php',
    1 => 'imagecolorallocate',
  ),
  11 => 
  array (
    0 => 'function.imagecolorallocatealpha.php',
    1 => 'imagecolorallocatealpha',
  ),
  12 => 
  array (
    0 => 'function.imagecolorat.php',
    1 => 'imagecolorat',
  ),
  13 => 
  array (
    0 => 'function.imagecolorclosest.php',
    1 => 'imagecolorclosest',
  ),
  14 => 
  array (
    0 => 'function.imagecolorclosestalpha.php',
    1 => 'imagecolorclosestalpha',
  ),
  15 => 
  array (
    0 => 'function.imagecolorclosesthwb.php',
    1 => 'imagecolorclosesthwb',
  ),
  16 => 
  array (
    0 => 'function.imagecolordeallocate.php',
    1 => 'imagecolordeallocate',
  ),
  17 => 
  array (
    0 => 'function.imagecolorexact.php',
    1 => 'imagecolorexact',
  ),
  18 => 
  array (
    0 => 'function.imagecolorexactalpha.php',
    1 => 'imagecolorexactalpha',
  ),
  19 => 
  array (
    0 => 'function.imagecolormatch.php',
    1 => 'imagecolormatch',
  ),
  20 => 
  array (
    0 => 'function.imagecolorresolve.php',
    1 => 'imagecolorresolve',
  ),
  21 => 
  array (
    0 => 'function.imagecolorresolvealpha.php',
    1 => 'imagecolorresolvealpha',
  ),
  22 => 
  array (
    0 => 'function.imagecolorset.php',
    1 => 'imagecolorset',
  ),
  23 => 
  array (
    0 => 'function.imagecolorsforindex.php',
    1 => 'imagecolorsforindex',
  ),
  24 => 
  array (
    0 => 'function.imagecolorstotal.php',
    1 => 'imagecolorstotal',
  ),
  25 => 
  array (
    0 => 'function.imagecolortransparent.php',
    1 => 'imagecolortransparent',
  ),
  26 => 
  array (
    0 => 'function.imageconvolution.php',
    1 => 'imageconvolution',
  ),
  27 => 
  array (
    0 => 'function.imagecopy.php',
    1 => 'imagecopy',
  ),
  28 => 
  array (
    0 => 'function.imagecopymerge.php',
    1 => 'imagecopymerge',
  ),
  29 => 
  array (
    0 => 'function.imagecopymergegray.php',
    1 => 'imagecopymergegray',
  ),
  30 => 
  array (
    0 => 'function.imagecopyresampled.php',
    1 => 'imagecopyresampled',
  ),
  31 => 
  array (
    0 => 'function.imagecopyresized.php',
    1 => 'imagecopyresized',
  ),
  32 => 
  array (
    0 => 'function.imagecreate.php',
    1 => 'imagecreate',
  ),
  33 => 
  array (
    0 => 'function.imagecreatefromgd2.php',
    1 => 'imagecreatefromgd2',
  ),
  34 => 
  array (
    0 => 'function.imagecreatefromgd2part.php',
    1 => 'imagecreatefromgd2part',
  ),
  35 => 
  array (
    0 => 'function.imagecreatefromgd.php',
    1 => 'imagecreatefromgd',
  ),
  36 => 
  array (
    0 => 'function.imagecreatefromgif.php',
    1 => 'imagecreatefromgif',
  ),
  37 => 
  array (
    0 => 'function.imagecreatefromjpeg.php',
    1 => 'imagecreatefromjpeg',
  ),
  38 => 
  array (
    0 => 'function.imagecreatefrompng.php',
    1 => 'imagecreatefrompng',
  ),
  39 => 
  array (
    0 => 'function.imagecreatefromstring.php',
    1 => 'imagecreatefromstring',
  ),
  40 => 
  array (
    0 => 'function.imagecreatefromwbmp.php',
    1 => 'imagecreatefromwbmp',
  ),
  41 => 
  array (
    0 => 'function.imagecreatefromxbm.php',
    1 => 'imagecreatefromxbm',
  ),
  42 => 
  array (
    0 => 'function.imagecreatefromxpm.php',
    1 => 'imagecreatefromxpm',
  ),
  43 => 
  array (
    0 => 'function.imagecreatetruecolor.php',
    1 => 'imagecreatetruecolor',
  ),
  44 => 
  array (
    0 => 'function.imagedashedline.php',
    1 => 'imagedashedline',
  ),
  45 => 
  array (
    0 => 'function.imagedestroy.php',
    1 => 'imagedestroy',
  ),
  46 => 
  array (
    0 => 'function.imageellipse.php',
    1 => 'imageellipse',
  ),
  47 => 
  array (
    0 => 'function.imagefill.php',
    1 => 'imagefill',
  ),
  48 => 
  array (
    0 => 'function.imagefilledarc.php',
    1 => 'imagefilledarc',
  ),
  49 => 
  array (
    0 => 'function.imagefilledellipse.php',
    1 => 'imagefilledellipse',
  ),
  50 => 
  array (
    0 => 'function.imagefilledpolygon.php',
    1 => 'imagefilledpolygon',
  ),
  51 => 
  array (
    0 => 'function.imagefilledrectangle.php',
    1 => 'imagefilledrectangle',
  ),
  52 => 
  array (
    0 => 'function.imagefilltoborder.php',
    1 => 'imagefilltoborder',
  ),
  53 => 
  array (
    0 => 'function.imagefilter.php',
    1 => 'imagefilter',
  ),
  54 => 
  array (
    0 => 'function.imagefontheight.php',
    1 => 'imagefontheight',
  ),
  55 => 
  array (
    0 => 'function.imagefontwidth.php',
    1 => 'imagefontwidth',
  ),
  56 => 
  array (
    0 => 'function.imageftbbox.php',
    1 => 'imageftbbox',
  ),
  57 => 
  array (
    0 => 'function.imagefttext.php',
    1 => 'imagefttext',
  ),
  58 => 
  array (
    0 => 'function.imagegammacorrect.php',
    1 => 'imagegammacorrect',
  ),
  59 => 
  array (
    0 => 'function.imagegd2.php',
    1 => 'imagegd2',
  ),
  60 => 
  array (
    0 => 'function.imagegd.php',
    1 => 'imagegd',
  ),
  61 => 
  array (
    0 => 'function.imagegif.php',
    1 => 'imagegif',
  ),
  62 => 
  array (
    0 => 'function.imagegrabscreen.php',
    1 => 'imagegrabscreen',
  ),
  63 => 
  array (
    0 => 'function.imagegrabwindow.php',
    1 => 'imagegrabwindow',
  ),
  64 => 
  array (
    0 => 'function.imageinterlace.php',
    1 => 'imageinterlace',
  ),
  65 => 
  array (
    0 => 'function.imageistruecolor.php',
    1 => 'imageistruecolor',
  ),
  66 => 
  array (
    0 => 'function.imagejpeg.php',
    1 => 'imagejpeg',
  ),
  67 => 
  array (
    0 => 'function.imagelayereffect.php',
    1 => 'imagelayereffect',
  ),
  68 => 
  array (
    0 => 'function.imageline.php',
    1 => 'imageline',
  ),
  69 => 
  array (
    0 => 'function.imageloadfont.php',
    1 => 'imageloadfont',
  ),
  70 => 
  array (
    0 => 'function.imagepalettecopy.php',
    1 => 'imagepalettecopy',
  ),
  71 => 
  array (
    0 => 'function.imagepng.php',
    1 => 'imagepng',
  ),
  72 => 
  array (
    0 => 'function.imagepolygon.php',
    1 => 'imagepolygon',
  ),
  73 => 
  array (
    0 => 'function.imagepsbbox.php',
    1 => 'imagepsbbox',
  ),
  74 => 
  array (
    0 => 'function.imagepsencodefont.php',
    1 => 'imagepsencodefont',
  ),
  75 => 
  array (
    0 => 'function.imagepsextendfont.php',
    1 => 'imagepsextendfont',
  ),
  76 => 
  array (
    0 => 'function.imagepsfreefont.php',
    1 => 'imagepsfreefont',
  ),
  77 => 
  array (
    0 => 'function.imagepsloadfont.php',
    1 => 'imagepsloadfont',
  ),
  78 => 
  array (
    0 => 'function.imagepsslantfont.php',
    1 => 'imagepsslantfont',
  ),
  79 => 
  array (
    0 => 'function.imagepstext.php',
    1 => 'imagepstext',
  ),
  80 => 
  array (
    0 => 'function.imagerectangle.php',
    1 => 'imagerectangle',
  ),
  81 => 
  array (
    0 => 'function.imagerotate.php',
    1 => 'imagerotate',
  ),
  82 => 
  array (
    0 => 'function.imagesavealpha.php',
    1 => 'imagesavealpha',
  ),
  83 => 
  array (
    0 => 'function.imagesetbrush.php',
    1 => 'imagesetbrush',
  ),
  84 => 
  array (
    0 => 'function.imagesetpixel.php',
    1 => 'imagesetpixel',
  ),
  85 => 
  array (
    0 => 'function.imagesetstyle.php',
    1 => 'imagesetstyle',
  ),
  86 => 
  array (
    0 => 'function.imagesetthickness.php',
    1 => 'imagesetthickness',
  ),
  87 => 
  array (
    0 => 'function.imagesettile.php',
    1 => 'imagesettile',
  ),
  88 => 
  array (
    0 => 'function.imagestring.php',
    1 => 'imagestring',
  ),
  89 => 
  array (
    0 => 'function.imagestringup.php',
    1 => 'imagestringup',
  ),
  90 => 
  array (
    0 => 'function.imagesx.php',
    1 => 'imagesx',
  ),
  91 => 
  array (
    0 => 'function.imagesy.php',
    1 => 'imagesy',
  ),
  92 => 
  array (
    0 => 'function.imagetruecolortopalette.php',
    1 => 'imagetruecolortopalette',
  ),
  93 => 
  array (
    0 => 'function.imagettfbbox.php',
    1 => 'imagettfbbox',
  ),
  94 => 
  array (
    0 => 'function.imagettftext.php',
    1 => 'imagettftext',
  ),
  95 => 
  array (
    0 => 'function.imagetypes.php',
    1 => 'imagetypes',
  ),
  96 => 
  array (
    0 => 'function.imagewbmp.php',
    1 => 'imagewbmp',
  ),
  97 => 
  array (
    0 => 'function.imagexbm.php',
    1 => 'imagexbm',
  ),
  98 => 
  array (
    0 => 'function.iptcembed.php',
    1 => 'iptcembed',
  ),
  99 => 
  array (
    0 => 'function.iptcparse.php',
    1 => 'iptcparse',
  ),
  100 => 
  array (
    0 => 'function.jpeg2wbmp.php',
    1 => 'jpeg2wbmp',
  ),
  101 => 
  array (
    0 => 'function.png2wbmp.php',
    1 => 'png2wbmp',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.image.php',
    1 => 'GD',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);