<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.fam-cancel-monitor.php',
    1 => 'fam_cancel_monitor',
  ),
  1 => 
  array (
    0 => 'function.fam-close.php',
    1 => 'fam_close',
  ),
  2 => 
  array (
    0 => 'function.fam-monitor-collection.php',
    1 => 'fam_monitor_collection',
  ),
  3 => 
  array (
    0 => 'function.fam-monitor-directory.php',
    1 => 'fam_monitor_directory',
  ),
  4 => 
  array (
    0 => 'function.fam-monitor-file.php',
    1 => 'fam_monitor_file',
  ),
  5 => 
  array (
    0 => 'function.fam-next-event.php',
    1 => 'fam_next_event',
  ),
  6 => 
  array (
    0 => 'function.fam-open.php',
    1 => 'fam_open',
  ),
  7 => 
  array (
    0 => 'function.fam-pending.php',
    1 => 'fam_pending',
  ),
  8 => 
  array (
    0 => 'function.fam-resume-monitor.php',
    1 => 'fam_resume_monitor',
  ),
  9 => 
  array (
    0 => 'function.fam-suspend-monitor.php',
    1 => 'fam_suspend_monitor',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.fam.php',
    1 => 'FAM',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);