<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.stats-absolute-deviation.php',
    1 => 'stats_absolute_deviation',
  ),
  1 => 
  array (
    0 => 'function.stats-cdf-beta.php',
    1 => 'stats_cdf_beta',
  ),
  2 => 
  array (
    0 => 'function.stats-cdf-binomial.php',
    1 => 'stats_cdf_binomial',
  ),
  3 => 
  array (
    0 => 'function.stats-cdf-cauchy.php',
    1 => 'stats_cdf_cauchy',
  ),
  4 => 
  array (
    0 => 'function.stats-cdf-chisquare.php',
    1 => 'stats_cdf_chisquare',
  ),
  5 => 
  array (
    0 => 'function.stats-cdf-exponential.php',
    1 => 'stats_cdf_exponential',
  ),
  6 => 
  array (
    0 => 'function.stats-cdf-f.php',
    1 => 'stats_cdf_f',
  ),
  7 => 
  array (
    0 => 'function.stats-cdf-gamma.php',
    1 => 'stats_cdf_gamma',
  ),
  8 => 
  array (
    0 => 'function.stats-cdf-laplace.php',
    1 => 'stats_cdf_laplace',
  ),
  9 => 
  array (
    0 => 'function.stats-cdf-logistic.php',
    1 => 'stats_cdf_logistic',
  ),
  10 => 
  array (
    0 => 'function.stats-cdf-negative-binomial.php',
    1 => 'stats_cdf_negative_binomial',
  ),
  11 => 
  array (
    0 => 'function.stats-cdf-noncentral-chisquare.php',
    1 => 'stats_cdf_noncentral_chisquare',
  ),
  12 => 
  array (
    0 => 'function.stats-cdf-noncentral-f.php',
    1 => 'stats_cdf_noncentral_f',
  ),
  13 => 
  array (
    0 => 'function.stats-cdf-poisson.php',
    1 => 'stats_cdf_poisson',
  ),
  14 => 
  array (
    0 => 'function.stats-cdf-t.php',
    1 => 'stats_cdf_t',
  ),
  15 => 
  array (
    0 => 'function.stats-cdf-uniform.php',
    1 => 'stats_cdf_uniform',
  ),
  16 => 
  array (
    0 => 'function.stats-cdf-weibull.php',
    1 => 'stats_cdf_weibull',
  ),
  17 => 
  array (
    0 => 'function.stats-covariance.php',
    1 => 'stats_covariance',
  ),
  18 => 
  array (
    0 => 'function.stats-den-uniform.php',
    1 => 'stats_den_uniform',
  ),
  19 => 
  array (
    0 => 'function.stats-dens-beta.php',
    1 => 'stats_dens_beta',
  ),
  20 => 
  array (
    0 => 'function.stats-dens-cauchy.php',
    1 => 'stats_dens_cauchy',
  ),
  21 => 
  array (
    0 => 'function.stats-dens-chisquare.php',
    1 => 'stats_dens_chisquare',
  ),
  22 => 
  array (
    0 => 'function.stats-dens-exponential.php',
    1 => 'stats_dens_exponential',
  ),
  23 => 
  array (
    0 => 'function.stats-dens-f.php',
    1 => 'stats_dens_f',
  ),
  24 => 
  array (
    0 => 'function.stats-dens-gamma.php',
    1 => 'stats_dens_gamma',
  ),
  25 => 
  array (
    0 => 'function.stats-dens-laplace.php',
    1 => 'stats_dens_laplace',
  ),
  26 => 
  array (
    0 => 'function.stats-dens-logistic.php',
    1 => 'stats_dens_logistic',
  ),
  27 => 
  array (
    0 => 'function.stats-dens-negative-binomial.php',
    1 => 'stats_dens_negative_binomial',
  ),
  28 => 
  array (
    0 => 'function.stats-dens-normal.php',
    1 => 'stats_dens_normal',
  ),
  29 => 
  array (
    0 => 'function.stats-dens-pmf-binomial.php',
    1 => 'stats_dens_pmf_binomial',
  ),
  30 => 
  array (
    0 => 'function.stats-dens-pmf-hypergeometric.php',
    1 => 'stats_dens_pmf_hypergeometric',
  ),
  31 => 
  array (
    0 => 'function.stats-dens-pmf-poisson.php',
    1 => 'stats_dens_pmf_poisson',
  ),
  32 => 
  array (
    0 => 'function.stats-dens-t.php',
    1 => 'stats_dens_t',
  ),
  33 => 
  array (
    0 => 'function.stats-dens-weibull.php',
    1 => 'stats_dens_weibull',
  ),
  34 => 
  array (
    0 => 'function.stats-harmonic-mean.php',
    1 => 'stats_harmonic_mean',
  ),
  35 => 
  array (
    0 => 'function.stats-kurtosis.php',
    1 => 'stats_kurtosis',
  ),
  36 => 
  array (
    0 => 'function.stats-rand-gen-beta.php',
    1 => 'stats_rand_gen_beta',
  ),
  37 => 
  array (
    0 => 'function.stats-rand-gen-chisquare.php',
    1 => 'stats_rand_gen_chisquare',
  ),
  38 => 
  array (
    0 => 'function.stats-rand-gen-exponential.php',
    1 => 'stats_rand_gen_exponential',
  ),
  39 => 
  array (
    0 => 'function.stats-rand-gen-f.php',
    1 => 'stats_rand_gen_f',
  ),
  40 => 
  array (
    0 => 'function.stats-rand-gen-funiform.php',
    1 => 'stats_rand_gen_funiform',
  ),
  41 => 
  array (
    0 => 'function.stats-rand-gen-gamma.php',
    1 => 'stats_rand_gen_gamma',
  ),
  42 => 
  array (
    0 => 'function.stats-rand-gen-ibinomial-negative.php',
    1 => 'stats_rand_gen_ibinomial_negative',
  ),
  43 => 
  array (
    0 => 'function.stats-rand-gen-ibinomial.php',
    1 => 'stats_rand_gen_ibinomial',
  ),
  44 => 
  array (
    0 => 'function.stats-rand-gen-int.php',
    1 => 'stats_rand_gen_int',
  ),
  45 => 
  array (
    0 => 'function.stats-rand-gen-ipoisson.php',
    1 => 'stats_rand_gen_ipoisson',
  ),
  46 => 
  array (
    0 => 'function.stats-rand-gen-iuniform.php',
    1 => 'stats_rand_gen_iuniform',
  ),
  47 => 
  array (
    0 => 'function.stats-rand-gen-noncenral-chisquare.php',
    1 => 'stats_rand_gen_noncenral_chisquare',
  ),
  48 => 
  array (
    0 => 'function.stats-rand-gen-noncentral-f.php',
    1 => 'stats_rand_gen_noncentral_f',
  ),
  49 => 
  array (
    0 => 'function.stats-rand-gen-noncentral-t.php',
    1 => 'stats_rand_gen_noncentral_t',
  ),
  50 => 
  array (
    0 => 'function.stats-rand-gen-normal.php',
    1 => 'stats_rand_gen_normal',
  ),
  51 => 
  array (
    0 => 'function.stats-rand-gen-t.php',
    1 => 'stats_rand_gen_t',
  ),
  52 => 
  array (
    0 => 'function.stats-rand-get-seeds.php',
    1 => 'stats_rand_get_seeds',
  ),
  53 => 
  array (
    0 => 'function.stats-rand-phrase-to-seeds.php',
    1 => 'stats_rand_phrase_to_seeds',
  ),
  54 => 
  array (
    0 => 'function.stats-rand-ranf.php',
    1 => 'stats_rand_ranf',
  ),
  55 => 
  array (
    0 => 'function.stats-rand-setall.php',
    1 => 'stats_rand_setall',
  ),
  56 => 
  array (
    0 => 'function.stats-skew.php',
    1 => 'stats_skew',
  ),
  57 => 
  array (
    0 => 'function.stats-standard-deviation.php',
    1 => 'stats_standard_deviation',
  ),
  58 => 
  array (
    0 => 'function.stats-stat-binomial-coef.php',
    1 => 'stats_stat_binomial_coef',
  ),
  59 => 
  array (
    0 => 'function.stats-stat-correlation.php',
    1 => 'stats_stat_correlation',
  ),
  60 => 
  array (
    0 => 'function.stats-stat-gennch.php',
    1 => 'stats_stat_gennch',
  ),
  61 => 
  array (
    0 => 'function.stats-stat-independent-t.php',
    1 => 'stats_stat_independent_t',
  ),
  62 => 
  array (
    0 => 'function.stats-stat-innerproduct.php',
    1 => 'stats_stat_innerproduct',
  ),
  63 => 
  array (
    0 => 'function.stats-stat-noncentral-t.php',
    1 => 'stats_stat_noncentral_t',
  ),
  64 => 
  array (
    0 => 'function.stats-stat-paired-t.php',
    1 => 'stats_stat_paired_t',
  ),
  65 => 
  array (
    0 => 'function.stats-stat-percentile.php',
    1 => 'stats_stat_percentile',
  ),
  66 => 
  array (
    0 => 'function.stats-stat-powersum.php',
    1 => 'stats_stat_powersum',
  ),
  67 => 
  array (
    0 => 'function.stats-variance.php',
    1 => 'stats_variance',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.stats.php',
    1 => 'Statistics',
  ),
  1 => 
  array (
    0 => 'refs.math.php',
    1 => 'Mathematical Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);