<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.udm-add-search-limit.php',
    1 => 'udm_add_search_limit',
  ),
  1 => 
  array (
    0 => 'function.udm-alloc-agent-array.php',
    1 => 'udm_alloc_agent_array',
  ),
  2 => 
  array (
    0 => 'function.udm-alloc-agent.php',
    1 => 'udm_alloc_agent',
  ),
  3 => 
  array (
    0 => 'function.udm-api-version.php',
    1 => 'udm_api_version',
  ),
  4 => 
  array (
    0 => 'function.udm-cat-list.php',
    1 => 'udm_cat_list',
  ),
  5 => 
  array (
    0 => 'function.udm-cat-path.php',
    1 => 'udm_cat_path',
  ),
  6 => 
  array (
    0 => 'function.udm-check-charset.php',
    1 => 'udm_check_charset',
  ),
  7 => 
  array (
    0 => 'function.udm-check-stored.php',
    1 => 'udm_check_stored',
  ),
  8 => 
  array (
    0 => 'function.udm-clear-search-limits.php',
    1 => 'udm_clear_search_limits',
  ),
  9 => 
  array (
    0 => 'function.udm-close-stored.php',
    1 => 'udm_close_stored',
  ),
  10 => 
  array (
    0 => 'function.udm-crc32.php',
    1 => 'udm_crc32',
  ),
  11 => 
  array (
    0 => 'function.udm-errno.php',
    1 => 'udm_errno',
  ),
  12 => 
  array (
    0 => 'function.udm-error.php',
    1 => 'udm_error',
  ),
  13 => 
  array (
    0 => 'function.udm-find.php',
    1 => 'udm_find',
  ),
  14 => 
  array (
    0 => 'function.udm-free-agent.php',
    1 => 'udm_free_agent',
  ),
  15 => 
  array (
    0 => 'function.udm-free-ispell-data.php',
    1 => 'udm_free_ispell_data',
  ),
  16 => 
  array (
    0 => 'function.udm-free-res.php',
    1 => 'udm_free_res',
  ),
  17 => 
  array (
    0 => 'function.udm-get-doc-count.php',
    1 => 'udm_get_doc_count',
  ),
  18 => 
  array (
    0 => 'function.udm-get-res-field.php',
    1 => 'udm_get_res_field',
  ),
  19 => 
  array (
    0 => 'function.udm-get-res-param.php',
    1 => 'udm_get_res_param',
  ),
  20 => 
  array (
    0 => 'function.udm-hash32.php',
    1 => 'udm_hash32',
  ),
  21 => 
  array (
    0 => 'function.udm-load-ispell-data.php',
    1 => 'udm_load_ispell_data',
  ),
  22 => 
  array (
    0 => 'function.udm-open-stored.php',
    1 => 'udm_open_stored',
  ),
  23 => 
  array (
    0 => 'function.udm-set-agent-param.php',
    1 => 'udm_set_agent_param',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mnogosearch.php',
    1 => 'mnoGoSearch',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);