<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.bzclose.php',
    1 => 'bzclose',
  ),
  1 => 
  array (
    0 => 'function.bzcompress.php',
    1 => 'bzcompress',
  ),
  2 => 
  array (
    0 => 'function.bzdecompress.php',
    1 => 'bzdecompress',
  ),
  3 => 
  array (
    0 => 'function.bzerrno.php',
    1 => 'bzerrno',
  ),
  4 => 
  array (
    0 => 'function.bzerror.php',
    1 => 'bzerror',
  ),
  5 => 
  array (
    0 => 'function.bzerrstr.php',
    1 => 'bzerrstr',
  ),
  6 => 
  array (
    0 => 'function.bzflush.php',
    1 => 'bzflush',
  ),
  7 => 
  array (
    0 => 'function.bzopen.php',
    1 => 'bzopen',
  ),
  8 => 
  array (
    0 => 'function.bzread.php',
    1 => 'bzread',
  ),
  9 => 
  array (
    0 => 'function.bzwrite.php',
    1 => 'bzwrite',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.bzip2.php',
    1 => 'Bzip2',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);