<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.xdiff-file-bdiff-size.php',
    1 => 'xdiff_file_bdiff_size',
  ),
  1 => 
  array (
    0 => 'function.xdiff-file-bdiff.php',
    1 => 'xdiff_file_bdiff',
  ),
  2 => 
  array (
    0 => 'function.xdiff-file-bpatch.php',
    1 => 'xdiff_file_bpatch',
  ),
  3 => 
  array (
    0 => 'function.xdiff-file-diff-binary.php',
    1 => 'xdiff_file_diff_binary',
  ),
  4 => 
  array (
    0 => 'function.xdiff-file-diff.php',
    1 => 'xdiff_file_diff',
  ),
  5 => 
  array (
    0 => 'function.xdiff-file-merge3.php',
    1 => 'xdiff_file_merge3',
  ),
  6 => 
  array (
    0 => 'function.xdiff-file-patch-binary.php',
    1 => 'xdiff_file_patch_binary',
  ),
  7 => 
  array (
    0 => 'function.xdiff-file-patch.php',
    1 => 'xdiff_file_patch',
  ),
  8 => 
  array (
    0 => 'function.xdiff-file-rabdiff.php',
    1 => 'xdiff_file_rabdiff',
  ),
  9 => 
  array (
    0 => 'function.xdiff-string-bdiff-size.php',
    1 => 'xdiff_string_bdiff_size',
  ),
  10 => 
  array (
    0 => 'function.xdiff-string-bdiff.php',
    1 => 'xdiff_string_bdiff',
  ),
  11 => 
  array (
    0 => 'function.xdiff-string-bpatch.php',
    1 => 'xdiff_string_bpatch',
  ),
  12 => 
  array (
    0 => 'function.xdiff-string-diff-binary.php',
    1 => 'xdiff_string_diff_binary',
  ),
  13 => 
  array (
    0 => 'function.xdiff-string-diff.php',
    1 => 'xdiff_string_diff',
  ),
  14 => 
  array (
    0 => 'function.xdiff-string-merge3.php',
    1 => 'xdiff_string_merge3',
  ),
  15 => 
  array (
    0 => 'function.xdiff-string-patch-binary.php',
    1 => 'xdiff_string_patch_binary',
  ),
  16 => 
  array (
    0 => 'function.xdiff-string-patch.php',
    1 => 'xdiff_string_patch',
  ),
  17 => 
  array (
    0 => 'function.xdiff-string-rabdiff.php',
    1 => 'xdiff_string_rabdiff',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.xdiff.php',
    1 => 'xdiff',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.file.php',
    1 => 'File System Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);