<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.grapheme-extract.php',
    1 => 'grapheme_extract',
  ),
  1 => 
  array (
    0 => 'function.grapheme-stripos.php',
    1 => 'grapheme_stripos',
  ),
  2 => 
  array (
    0 => 'function.grapheme-stristr.php',
    1 => 'grapheme_stristr',
  ),
  3 => 
  array (
    0 => 'function.grapheme-strlen.php',
    1 => 'grapheme_strlen',
  ),
  4 => 
  array (
    0 => 'function.grapheme-strpos.php',
    1 => 'grapheme_strpos',
  ),
  5 => 
  array (
    0 => 'function.grapheme-strripos.php',
    1 => 'grapheme_strripos',
  ),
  6 => 
  array (
    0 => 'function.grapheme-strrpos.php',
    1 => 'grapheme_strrpos',
  ),
  7 => 
  array (
    0 => 'function.grapheme-strstr.php',
    1 => 'grapheme_strstr',
  ),
  8 => 
  array (
    0 => 'function.grapheme-substr.php',
    1 => 'grapheme_substr',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.intl.php',
    1 => 'intl',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);