<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.utf8-decode.php',
    1 => 'utf8_decode',
  ),
  1 => 
  array (
    0 => 'function.utf8-encode.php',
    1 => 'utf8_encode',
  ),
  2 => 
  array (
    0 => 'function.xml-error-string.php',
    1 => 'xml_error_string',
  ),
  3 => 
  array (
    0 => 'function.xml-get-current-byte-index.php',
    1 => 'xml_get_current_byte_index',
  ),
  4 => 
  array (
    0 => 'function.xml-get-current-column-number.php',
    1 => 'xml_get_current_column_number',
  ),
  5 => 
  array (
    0 => 'function.xml-get-current-line-number.php',
    1 => 'xml_get_current_line_number',
  ),
  6 => 
  array (
    0 => 'function.xml-get-error-code.php',
    1 => 'xml_get_error_code',
  ),
  7 => 
  array (
    0 => 'function.xml-parse-into-struct.php',
    1 => 'xml_parse_into_struct',
  ),
  8 => 
  array (
    0 => 'function.xml-parse.php',
    1 => 'xml_parse',
  ),
  9 => 
  array (
    0 => 'function.xml-parser-create-ns.php',
    1 => 'xml_parser_create_ns',
  ),
  10 => 
  array (
    0 => 'function.xml-parser-create.php',
    1 => 'xml_parser_create',
  ),
  11 => 
  array (
    0 => 'function.xml-parser-free.php',
    1 => 'xml_parser_free',
  ),
  12 => 
  array (
    0 => 'function.xml-parser-get-option.php',
    1 => 'xml_parser_get_option',
  ),
  13 => 
  array (
    0 => 'function.xml-parser-set-option.php',
    1 => 'xml_parser_set_option',
  ),
  14 => 
  array (
    0 => 'function.xml-set-character-data-handler.php',
    1 => 'xml_set_character_data_handler',
  ),
  15 => 
  array (
    0 => 'function.xml-set-default-handler.php',
    1 => 'xml_set_default_handler',
  ),
  16 => 
  array (
    0 => 'function.xml-set-element-handler.php',
    1 => 'xml_set_element_handler',
  ),
  17 => 
  array (
    0 => 'function.xml-set-end-namespace-decl-handler.php',
    1 => 'xml_set_end_namespace_decl_handler',
  ),
  18 => 
  array (
    0 => 'function.xml-set-external-entity-ref-handler.php',
    1 => 'xml_set_external_entity_ref_handler',
  ),
  19 => 
  array (
    0 => 'function.xml-set-notation-decl-handler.php',
    1 => 'xml_set_notation_decl_handler',
  ),
  20 => 
  array (
    0 => 'function.xml-set-object.php',
    1 => 'xml_set_object',
  ),
  21 => 
  array (
    0 => 'function.xml-set-processing-instruction-handler.php',
    1 => 'xml_set_processing_instruction_handler',
  ),
  22 => 
  array (
    0 => 'function.xml-set-start-namespace-decl-handler.php',
    1 => 'xml_set_start_namespace_decl_handler',
  ),
  23 => 
  array (
    0 => 'function.xml-set-unparsed-entity-decl-handler.php',
    1 => 'xml_set_unparsed_entity_decl_handler',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.xml.php',
    1 => 'XML Parser',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);