<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.msession-connect.php',
    1 => 'msession_connect',
  ),
  1 => 
  array (
    0 => 'function.msession-count.php',
    1 => 'msession_count',
  ),
  2 => 
  array (
    0 => 'function.msession-create.php',
    1 => 'msession_create',
  ),
  3 => 
  array (
    0 => 'function.msession-destroy.php',
    1 => 'msession_destroy',
  ),
  4 => 
  array (
    0 => 'function.msession-disconnect.php',
    1 => 'msession_disconnect',
  ),
  5 => 
  array (
    0 => 'function.msession-find.php',
    1 => 'msession_find',
  ),
  6 => 
  array (
    0 => 'function.msession-get-array.php',
    1 => 'msession_get_array',
  ),
  7 => 
  array (
    0 => 'function.msession-get-data.php',
    1 => 'msession_get_data',
  ),
  8 => 
  array (
    0 => 'function.msession-get.php',
    1 => 'msession_get',
  ),
  9 => 
  array (
    0 => 'function.msession-inc.php',
    1 => 'msession_inc',
  ),
  10 => 
  array (
    0 => 'function.msession-list.php',
    1 => 'msession_list',
  ),
  11 => 
  array (
    0 => 'function.msession-listvar.php',
    1 => 'msession_listvar',
  ),
  12 => 
  array (
    0 => 'function.msession-lock.php',
    1 => 'msession_lock',
  ),
  13 => 
  array (
    0 => 'function.msession-plugin.php',
    1 => 'msession_plugin',
  ),
  14 => 
  array (
    0 => 'function.msession-randstr.php',
    1 => 'msession_randstr',
  ),
  15 => 
  array (
    0 => 'function.msession-set-array.php',
    1 => 'msession_set_array',
  ),
  16 => 
  array (
    0 => 'function.msession-set-data.php',
    1 => 'msession_set_data',
  ),
  17 => 
  array (
    0 => 'function.msession-set.php',
    1 => 'msession_set',
  ),
  18 => 
  array (
    0 => 'function.msession-timeout.php',
    1 => 'msession_timeout',
  ),
  19 => 
  array (
    0 => 'function.msession-uniq.php',
    1 => 'msession_uniq',
  ),
  20 => 
  array (
    0 => 'function.msession-unlock.php',
    1 => 'msession_unlock',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.msession.php',
    1 => 'Msession',
  ),
  1 => 
  array (
    0 => 'refs.basic.session.php',
    1 => 'Session Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);