<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.oci-bind-array-by-name.php',
    1 => 'oci_bind_array_by_name',
  ),
  1 => 
  array (
    0 => 'function.oci-bind-by-name.php',
    1 => 'oci_bind_by_name',
  ),
  2 => 
  array (
    0 => 'function.oci-cancel.php',
    1 => 'oci_cancel',
  ),
  3 => 
  array (
    0 => 'function.oci-close.php',
    1 => 'oci_close',
  ),
  4 => 
  array (
    0 => 'function.oci-collection-append.php',
    1 => 'OCI-Collection-&gt;append',
  ),
  5 => 
  array (
    0 => 'function.oci-collection-assign.php',
    1 => 'OCI-Collection-&gt;assign',
  ),
  6 => 
  array (
    0 => 'function.oci-collection-element-assign.php',
    1 => 'OCI-Collection-&gt;assignElem',
  ),
  7 => 
  array (
    0 => 'function.oci-collection-free.php',
    1 => 'OCI-Collection-&gt;free',
  ),
  8 => 
  array (
    0 => 'function.oci-collection-element-get.php',
    1 => 'OCI-Collection-&gt;getElem',
  ),
  9 => 
  array (
    0 => 'function.oci-collection-max.php',
    1 => 'OCI-Collection-&gt;max',
  ),
  10 => 
  array (
    0 => 'function.oci-collection-size.php',
    1 => 'OCI-Collection-&gt;size',
  ),
  11 => 
  array (
    0 => 'function.oci-collection-trim.php',
    1 => 'OCI-Collection-&gt;trim',
  ),
  12 => 
  array (
    0 => 'function.oci-commit.php',
    1 => 'oci_commit',
  ),
  13 => 
  array (
    0 => 'function.oci-connect.php',
    1 => 'oci_connect',
  ),
  14 => 
  array (
    0 => 'function.oci-define-by-name.php',
    1 => 'oci_define_by_name',
  ),
  15 => 
  array (
    0 => 'function.oci-error.php',
    1 => 'oci_error',
  ),
  16 => 
  array (
    0 => 'function.oci-execute.php',
    1 => 'oci_execute',
  ),
  17 => 
  array (
    0 => 'function.oci-fetch-all.php',
    1 => 'oci_fetch_all',
  ),
  18 => 
  array (
    0 => 'function.oci-fetch-array.php',
    1 => 'oci_fetch_array',
  ),
  19 => 
  array (
    0 => 'function.oci-fetch-assoc.php',
    1 => 'oci_fetch_assoc',
  ),
  20 => 
  array (
    0 => 'function.oci-fetch-object.php',
    1 => 'oci_fetch_object',
  ),
  21 => 
  array (
    0 => 'function.oci-fetch-row.php',
    1 => 'oci_fetch_row',
  ),
  22 => 
  array (
    0 => 'function.oci-fetch.php',
    1 => 'oci_fetch',
  ),
  23 => 
  array (
    0 => 'function.oci-field-is-null.php',
    1 => 'oci_field_is_null',
  ),
  24 => 
  array (
    0 => 'function.oci-field-name.php',
    1 => 'oci_field_name',
  ),
  25 => 
  array (
    0 => 'function.oci-field-precision.php',
    1 => 'oci_field_precision',
  ),
  26 => 
  array (
    0 => 'function.oci-field-scale.php',
    1 => 'oci_field_scale',
  ),
  27 => 
  array (
    0 => 'function.oci-field-size.php',
    1 => 'oci_field_size',
  ),
  28 => 
  array (
    0 => 'function.oci-field-type-raw.php',
    1 => 'oci_field_type_raw',
  ),
  29 => 
  array (
    0 => 'function.oci-field-type.php',
    1 => 'oci_field_type',
  ),
  30 => 
  array (
    0 => 'function.oci-free-statement.php',
    1 => 'oci_free_statement',
  ),
  31 => 
  array (
    0 => 'function.oci-internal-debug.php',
    1 => 'oci_internal_debug',
  ),
  32 => 
  array (
    0 => 'function.oci-lob-append.php',
    1 => 'OCI-Lob-&gt;append',
  ),
  33 => 
  array (
    0 => 'function.oci-lob-close.php',
    1 => 'OCI-Lob-&gt;close',
  ),
  34 => 
  array (
    0 => 'function.oci-lob-copy.php',
    1 => 'oci_lob_copy',
  ),
  35 => 
  array (
    0 => 'function.oci-lob-eof.php',
    1 => 'OCI-Lob-&gt;eof',
  ),
  36 => 
  array (
    0 => 'function.oci-lob-erase.php',
    1 => 'OCI-Lob-&gt;erase',
  ),
  37 => 
  array (
    0 => 'function.oci-lob-export.php',
    1 => 'OCI-Lob-&gt;export',
  ),
  38 => 
  array (
    0 => 'function.oci-lob-flush.php',
    1 => 'OCI-Lob-&gt;flush',
  ),
  39 => 
  array (
    0 => 'function.oci-lob-free.php',
    1 => 'OCI-Lob-&gt;free',
  ),
  40 => 
  array (
    0 => 'function.oci-lob-getbuffering.php',
    1 => 'OCI-Lob-&gt;getBuffering',
  ),
  41 => 
  array (
    0 => 'function.oci-lob-import.php',
    1 => 'OCI-Lob-&gt;import',
  ),
  42 => 
  array (
    0 => 'function.oci-lob-is-equal.php',
    1 => 'oci_lob_is_equal',
  ),
  43 => 
  array (
    0 => 'function.oci-lob-load.php',
    1 => 'OCI-Lob-&gt;load',
  ),
  44 => 
  array (
    0 => 'function.oci-lob-read.php',
    1 => 'OCI-Lob-&gt;read',
  ),
  45 => 
  array (
    0 => 'function.oci-lob-rewind.php',
    1 => 'OCI-Lob-&gt;rewind',
  ),
  46 => 
  array (
    0 => 'function.oci-lob-save.php',
    1 => 'OCI-Lob-&gt;save',
  ),
  47 => 
  array (
    0 => 'function.oci-lob-savefile.php',
    1 => 'OCI-Lob-&gt;saveFile',
  ),
  48 => 
  array (
    0 => 'function.oci-lob-seek.php',
    1 => 'OCI-Lob-&gt;seek',
  ),
  49 => 
  array (
    0 => 'function.oci-lob-setbuffering.php',
    1 => 'OCI-Lob-&gt;setBuffering',
  ),
  50 => 
  array (
    0 => 'function.oci-lob-size.php',
    1 => 'OCI-Lob-&gt;size',
  ),
  51 => 
  array (
    0 => 'function.oci-lob-tell.php',
    1 => 'OCI-Lob-&gt;tell',
  ),
  52 => 
  array (
    0 => 'function.oci-lob-truncate.php',
    1 => 'OCI-Lob-&gt;truncate',
  ),
  53 => 
  array (
    0 => 'function.oci-lob-write.php',
    1 => 'OCI-Lob-&gt;write',
  ),
  54 => 
  array (
    0 => 'function.oci-lob-writetemporary.php',
    1 => 'OCI-Lob-&gt;writeTemporary',
  ),
  55 => 
  array (
    0 => 'function.oci-lob-writetofile.php',
    1 => 'OCI-Lob-&gt;writeToFile',
  ),
  56 => 
  array (
    0 => 'function.oci-new-collection.php',
    1 => 'oci_new_collection',
  ),
  57 => 
  array (
    0 => 'function.oci-new-connect.php',
    1 => 'oci_new_connect',
  ),
  58 => 
  array (
    0 => 'function.oci-new-cursor.php',
    1 => 'oci_new_cursor',
  ),
  59 => 
  array (
    0 => 'function.oci-new-descriptor.php',
    1 => 'oci_new_descriptor',
  ),
  60 => 
  array (
    0 => 'function.oci-num-fields.php',
    1 => 'oci_num_fields',
  ),
  61 => 
  array (
    0 => 'function.oci-num-rows.php',
    1 => 'oci_num_rows',
  ),
  62 => 
  array (
    0 => 'function.oci-parse.php',
    1 => 'oci_parse',
  ),
  63 => 
  array (
    0 => 'function.oci-password-change.php',
    1 => 'oci_password_change',
  ),
  64 => 
  array (
    0 => 'function.oci-pconnect.php',
    1 => 'oci_pconnect',
  ),
  65 => 
  array (
    0 => 'function.oci-result.php',
    1 => 'oci_result',
  ),
  66 => 
  array (
    0 => 'function.oci-rollback.php',
    1 => 'oci_rollback',
  ),
  67 => 
  array (
    0 => 'function.oci-server-version.php',
    1 => 'oci_server_version',
  ),
  68 => 
  array (
    0 => 'function.oci-set-action.php',
    1 => 'oci_set_action',
  ),
  69 => 
  array (
    0 => 'function.oci-set-client-identifier.php',
    1 => 'oci_set_client_identifier',
  ),
  70 => 
  array (
    0 => 'function.oci-set-client-info.php',
    1 => 'oci_set_client_info',
  ),
  71 => 
  array (
    0 => 'function.oci-set-edition.php',
    1 => 'oci_set_edition',
  ),
  72 => 
  array (
    0 => 'function.oci-set-module-name.php',
    1 => 'oci_set_module_name',
  ),
  73 => 
  array (
    0 => 'function.oci-set-prefetch.php',
    1 => 'oci_set_prefetch',
  ),
  74 => 
  array (
    0 => 'function.oci-statement-type.php',
    1 => 'oci_statement_type',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.oci8.php',
    1 => 'OCI8',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);