<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.apache-child-terminate.php',
    1 => 'apache_child_terminate',
  ),
  1 => 
  array (
    0 => 'function.apache-get-modules.php',
    1 => 'apache_get_modules',
  ),
  2 => 
  array (
    0 => 'function.apache-get-version.php',
    1 => 'apache_get_version',
  ),
  3 => 
  array (
    0 => 'function.apache-getenv.php',
    1 => 'apache_getenv',
  ),
  4 => 
  array (
    0 => 'function.apache-lookup-uri.php',
    1 => 'apache_lookup_uri',
  ),
  5 => 
  array (
    0 => 'function.apache-note.php',
    1 => 'apache_note',
  ),
  6 => 
  array (
    0 => 'function.apache-request-headers.php',
    1 => 'apache_request_headers',
  ),
  7 => 
  array (
    0 => 'function.apache-reset-timeout.php',
    1 => 'apache_reset_timeout',
  ),
  8 => 
  array (
    0 => 'function.apache-response-headers.php',
    1 => 'apache_response_headers',
  ),
  9 => 
  array (
    0 => 'function.apache-setenv.php',
    1 => 'apache_setenv',
  ),
  10 => 
  array (
    0 => 'function.getallheaders.php',
    1 => 'getallheaders',
  ),
  11 => 
  array (
    0 => 'function.virtual.php',
    1 => 'virtual',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.apache.php',
    1 => 'Apache',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.server.php',
    1 => 'Server Specific Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);