<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.basename.php',
    1 => 'basename',
  ),
  1 => 
  array (
    0 => 'function.chgrp.php',
    1 => 'chgrp',
  ),
  2 => 
  array (
    0 => 'function.chmod.php',
    1 => 'chmod',
  ),
  3 => 
  array (
    0 => 'function.chown.php',
    1 => 'chown',
  ),
  4 => 
  array (
    0 => 'function.clearstatcache.php',
    1 => 'clearstatcache',
  ),
  5 => 
  array (
    0 => 'function.copy.php',
    1 => 'copy',
  ),
  6 => 
  array (
    0 => 'function.delete.php',
    1 => 'delete',
  ),
  7 => 
  array (
    0 => 'function.dirname.php',
    1 => 'dirname',
  ),
  8 => 
  array (
    0 => 'function.disk-free-space.php',
    1 => 'disk_free_space',
  ),
  9 => 
  array (
    0 => 'function.disk-total-space.php',
    1 => 'disk_total_space',
  ),
  10 => 
  array (
    0 => 'function.diskfreespace.php',
    1 => 'diskfreespace',
  ),
  11 => 
  array (
    0 => 'function.fclose.php',
    1 => 'fclose',
  ),
  12 => 
  array (
    0 => 'function.feof.php',
    1 => 'feof',
  ),
  13 => 
  array (
    0 => 'function.fflush.php',
    1 => 'fflush',
  ),
  14 => 
  array (
    0 => 'function.fgetc.php',
    1 => 'fgetc',
  ),
  15 => 
  array (
    0 => 'function.fgetcsv.php',
    1 => 'fgetcsv',
  ),
  16 => 
  array (
    0 => 'function.fgets.php',
    1 => 'fgets',
  ),
  17 => 
  array (
    0 => 'function.fgetss.php',
    1 => 'fgetss',
  ),
  18 => 
  array (
    0 => 'function.file-exists.php',
    1 => 'file_exists',
  ),
  19 => 
  array (
    0 => 'function.file-get-contents.php',
    1 => 'file_get_contents',
  ),
  20 => 
  array (
    0 => 'function.file-put-contents.php',
    1 => 'file_put_contents',
  ),
  21 => 
  array (
    0 => 'function.file.php',
    1 => 'file',
  ),
  22 => 
  array (
    0 => 'function.fileatime.php',
    1 => 'fileatime',
  ),
  23 => 
  array (
    0 => 'function.filectime.php',
    1 => 'filectime',
  ),
  24 => 
  array (
    0 => 'function.filegroup.php',
    1 => 'filegroup',
  ),
  25 => 
  array (
    0 => 'function.fileinode.php',
    1 => 'fileinode',
  ),
  26 => 
  array (
    0 => 'function.filemtime.php',
    1 => 'filemtime',
  ),
  27 => 
  array (
    0 => 'function.fileowner.php',
    1 => 'fileowner',
  ),
  28 => 
  array (
    0 => 'function.fileperms.php',
    1 => 'fileperms',
  ),
  29 => 
  array (
    0 => 'function.filesize.php',
    1 => 'filesize',
  ),
  30 => 
  array (
    0 => 'function.filetype.php',
    1 => 'filetype',
  ),
  31 => 
  array (
    0 => 'function.flock.php',
    1 => 'flock',
  ),
  32 => 
  array (
    0 => 'function.fnmatch.php',
    1 => 'fnmatch',
  ),
  33 => 
  array (
    0 => 'function.fopen.php',
    1 => 'fopen',
  ),
  34 => 
  array (
    0 => 'function.fpassthru.php',
    1 => 'fpassthru',
  ),
  35 => 
  array (
    0 => 'function.fputcsv.php',
    1 => 'fputcsv',
  ),
  36 => 
  array (
    0 => 'function.fputs.php',
    1 => 'fputs',
  ),
  37 => 
  array (
    0 => 'function.fread.php',
    1 => 'fread',
  ),
  38 => 
  array (
    0 => 'function.fscanf.php',
    1 => 'fscanf',
  ),
  39 => 
  array (
    0 => 'function.fseek.php',
    1 => 'fseek',
  ),
  40 => 
  array (
    0 => 'function.fstat.php',
    1 => 'fstat',
  ),
  41 => 
  array (
    0 => 'function.ftell.php',
    1 => 'ftell',
  ),
  42 => 
  array (
    0 => 'function.ftruncate.php',
    1 => 'ftruncate',
  ),
  43 => 
  array (
    0 => 'function.fwrite.php',
    1 => 'fwrite',
  ),
  44 => 
  array (
    0 => 'function.glob.php',
    1 => 'glob',
  ),
  45 => 
  array (
    0 => 'function.is-dir.php',
    1 => 'is_dir',
  ),
  46 => 
  array (
    0 => 'function.is-executable.php',
    1 => 'is_executable',
  ),
  47 => 
  array (
    0 => 'function.is-file.php',
    1 => 'is_file',
  ),
  48 => 
  array (
    0 => 'function.is-link.php',
    1 => 'is_link',
  ),
  49 => 
  array (
    0 => 'function.is-readable.php',
    1 => 'is_readable',
  ),
  50 => 
  array (
    0 => 'function.is-uploaded-file.php',
    1 => 'is_uploaded_file',
  ),
  51 => 
  array (
    0 => 'function.is-writable.php',
    1 => 'is_writable',
  ),
  52 => 
  array (
    0 => 'function.is-writeable.php',
    1 => 'is_writeable',
  ),
  53 => 
  array (
    0 => 'function.lchgrp.php',
    1 => 'lchgrp',
  ),
  54 => 
  array (
    0 => 'function.lchown.php',
    1 => 'lchown',
  ),
  55 => 
  array (
    0 => 'function.link.php',
    1 => 'link',
  ),
  56 => 
  array (
    0 => 'function.linkinfo.php',
    1 => 'linkinfo',
  ),
  57 => 
  array (
    0 => 'function.lstat.php',
    1 => 'lstat',
  ),
  58 => 
  array (
    0 => 'function.mkdir.php',
    1 => 'mkdir',
  ),
  59 => 
  array (
    0 => 'function.move-uploaded-file.php',
    1 => 'move_uploaded_file',
  ),
  60 => 
  array (
    0 => 'function.parse-ini-file.php',
    1 => 'parse_ini_file',
  ),
  61 => 
  array (
    0 => 'function.parse-ini-string.php',
    1 => 'parse_ini_string',
  ),
  62 => 
  array (
    0 => 'function.pathinfo.php',
    1 => 'pathinfo',
  ),
  63 => 
  array (
    0 => 'function.pclose.php',
    1 => 'pclose',
  ),
  64 => 
  array (
    0 => 'function.popen.php',
    1 => 'popen',
  ),
  65 => 
  array (
    0 => 'function.readfile.php',
    1 => 'readfile',
  ),
  66 => 
  array (
    0 => 'function.readlink.php',
    1 => 'readlink',
  ),
  67 => 
  array (
    0 => 'function.realpath_cache_get.php',
    1 => 'realpath_cache_get',
  ),
  68 => 
  array (
    0 => 'function.realpath_cache_size.php',
    1 => 'realpath_cache_size',
  ),
  69 => 
  array (
    0 => 'function.realpath.php',
    1 => 'realpath',
  ),
  70 => 
  array (
    0 => 'function.rename.php',
    1 => 'rename',
  ),
  71 => 
  array (
    0 => 'function.rewind.php',
    1 => 'rewind',
  ),
  72 => 
  array (
    0 => 'function.rmdir.php',
    1 => 'rmdir',
  ),
  73 => 
  array (
    0 => 'function.set-file-buffer.php',
    1 => 'set_file_buffer',
  ),
  74 => 
  array (
    0 => 'function.stat.php',
    1 => 'stat',
  ),
  75 => 
  array (
    0 => 'function.symlink.php',
    1 => 'symlink',
  ),
  76 => 
  array (
    0 => 'function.tempnam.php',
    1 => 'tempnam',
  ),
  77 => 
  array (
    0 => 'function.tmpfile.php',
    1 => 'tmpfile',
  ),
  78 => 
  array (
    0 => 'function.touch.php',
    1 => 'touch',
  ),
  79 => 
  array (
    0 => 'function.umask.php',
    1 => 'umask',
  ),
  80 => 
  array (
    0 => 'function.unlink.php',
    1 => 'unlink',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.filesystem.php',
    1 => 'Filesystem',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.file.php',
    1 => 'File System Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);