<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.mcrypt-cbc.php',
    1 => 'mcrypt_cbc',
  ),
  1 => 
  array (
    0 => 'function.mcrypt-cfb.php',
    1 => 'mcrypt_cfb',
  ),
  2 => 
  array (
    0 => 'function.mcrypt-create-iv.php',
    1 => 'mcrypt_create_iv',
  ),
  3 => 
  array (
    0 => 'function.mcrypt-decrypt.php',
    1 => 'mcrypt_decrypt',
  ),
  4 => 
  array (
    0 => 'function.mcrypt-ecb.php',
    1 => 'mcrypt_ecb',
  ),
  5 => 
  array (
    0 => 'function.mcrypt-enc-get-algorithms-name.php',
    1 => 'mcrypt_enc_get_algorithms_name',
  ),
  6 => 
  array (
    0 => 'function.mcrypt-enc-get-block-size.php',
    1 => 'mcrypt_enc_get_block_size',
  ),
  7 => 
  array (
    0 => 'function.mcrypt-enc-get-iv-size.php',
    1 => 'mcrypt_enc_get_iv_size',
  ),
  8 => 
  array (
    0 => 'function.mcrypt-enc-get-key-size.php',
    1 => 'mcrypt_enc_get_key_size',
  ),
  9 => 
  array (
    0 => 'function.mcrypt-enc-get-modes-name.php',
    1 => 'mcrypt_enc_get_modes_name',
  ),
  10 => 
  array (
    0 => 'function.mcrypt-enc-get-supported-key-sizes.php',
    1 => 'mcrypt_enc_get_supported_key_sizes',
  ),
  11 => 
  array (
    0 => 'function.mcrypt-enc-is-block-algorithm-mode.php',
    1 => 'mcrypt_enc_is_block_algorithm_mode',
  ),
  12 => 
  array (
    0 => 'function.mcrypt-enc-is-block-algorithm.php',
    1 => 'mcrypt_enc_is_block_algorithm',
  ),
  13 => 
  array (
    0 => 'function.mcrypt-enc-is-block-mode.php',
    1 => 'mcrypt_enc_is_block_mode',
  ),
  14 => 
  array (
    0 => 'function.mcrypt-enc-self-test.php',
    1 => 'mcrypt_enc_self_test',
  ),
  15 => 
  array (
    0 => 'function.mcrypt-encrypt.php',
    1 => 'mcrypt_encrypt',
  ),
  16 => 
  array (
    0 => 'function.mcrypt-generic-deinit.php',
    1 => 'mcrypt_generic_deinit',
  ),
  17 => 
  array (
    0 => 'function.mcrypt-generic-end.php',
    1 => 'mcrypt_generic_end',
  ),
  18 => 
  array (
    0 => 'function.mcrypt-generic-init.php',
    1 => 'mcrypt_generic_init',
  ),
  19 => 
  array (
    0 => 'function.mcrypt-generic.php',
    1 => 'mcrypt_generic',
  ),
  20 => 
  array (
    0 => 'function.mcrypt-get-block-size.php',
    1 => 'mcrypt_get_block_size',
  ),
  21 => 
  array (
    0 => 'function.mcrypt-get-cipher-name.php',
    1 => 'mcrypt_get_cipher_name',
  ),
  22 => 
  array (
    0 => 'function.mcrypt-get-iv-size.php',
    1 => 'mcrypt_get_iv_size',
  ),
  23 => 
  array (
    0 => 'function.mcrypt-get-key-size.php',
    1 => 'mcrypt_get_key_size',
  ),
  24 => 
  array (
    0 => 'function.mcrypt-list-algorithms.php',
    1 => 'mcrypt_list_algorithms',
  ),
  25 => 
  array (
    0 => 'function.mcrypt-list-modes.php',
    1 => 'mcrypt_list_modes',
  ),
  26 => 
  array (
    0 => 'function.mcrypt-module-close.php',
    1 => 'mcrypt_module_close',
  ),
  27 => 
  array (
    0 => 'function.mcrypt-module-get-algo-block-size.php',
    1 => 'mcrypt_module_get_algo_block_size',
  ),
  28 => 
  array (
    0 => 'function.mcrypt-module-get-algo-key-size.php',
    1 => 'mcrypt_module_get_algo_key_size',
  ),
  29 => 
  array (
    0 => 'function.mcrypt-module-get-supported-key-sizes.php',
    1 => 'mcrypt_module_get_supported_key_sizes',
  ),
  30 => 
  array (
    0 => 'function.mcrypt-module-is-block-algorithm-mode.php',
    1 => 'mcrypt_module_is_block_algorithm_mode',
  ),
  31 => 
  array (
    0 => 'function.mcrypt-module-is-block-algorithm.php',
    1 => 'mcrypt_module_is_block_algorithm',
  ),
  32 => 
  array (
    0 => 'function.mcrypt-module-is-block-mode.php',
    1 => 'mcrypt_module_is_block_mode',
  ),
  33 => 
  array (
    0 => 'function.mcrypt-module-open.php',
    1 => 'mcrypt_module_open',
  ),
  34 => 
  array (
    0 => 'function.mcrypt-module-self-test.php',
    1 => 'mcrypt_module_self_test',
  ),
  35 => 
  array (
    0 => 'function.mcrypt-ofb.php',
    1 => 'mcrypt_ofb',
  ),
  36 => 
  array (
    0 => 'function.mdecrypt-generic.php',
    1 => 'mdecrypt_generic',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mcrypt.php',
    1 => 'Mcrypt',
  ),
  1 => 
  array (
    0 => 'refs.crypto.php',
    1 => 'Cryptography Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);