<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.iconv-get-encoding.php',
    1 => 'iconv_get_encoding',
  ),
  1 => 
  array (
    0 => 'function.iconv-mime-decode-headers.php',
    1 => 'iconv_mime_decode_headers',
  ),
  2 => 
  array (
    0 => 'function.iconv-mime-decode.php',
    1 => 'iconv_mime_decode',
  ),
  3 => 
  array (
    0 => 'function.iconv-mime-encode.php',
    1 => 'iconv_mime_encode',
  ),
  4 => 
  array (
    0 => 'function.iconv-set-encoding.php',
    1 => 'iconv_set_encoding',
  ),
  5 => 
  array (
    0 => 'function.iconv-strlen.php',
    1 => 'iconv_strlen',
  ),
  6 => 
  array (
    0 => 'function.iconv-strpos.php',
    1 => 'iconv_strpos',
  ),
  7 => 
  array (
    0 => 'function.iconv-strrpos.php',
    1 => 'iconv_strrpos',
  ),
  8 => 
  array (
    0 => 'function.iconv-substr.php',
    1 => 'iconv_substr',
  ),
  9 => 
  array (
    0 => 'function.iconv.php',
    1 => 'iconv',
  ),
  10 => 
  array (
    0 => 'function.ob-iconv-handler.php',
    1 => 'ob_iconv_handler',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.iconv.php',
    1 => 'iconv',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);