<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.memcache-debug.php',
    1 => 'memcache_debug',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.memcache.php',
    1 => 'Memcache',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);