<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.fdf-add-doc-javascript.php',
    1 => 'fdf_add_doc_javascript',
  ),
  1 => 
  array (
    0 => 'function.fdf-add-template.php',
    1 => 'fdf_add_template',
  ),
  2 => 
  array (
    0 => 'function.fdf-close.php',
    1 => 'fdf_close',
  ),
  3 => 
  array (
    0 => 'function.fdf-create.php',
    1 => 'fdf_create',
  ),
  4 => 
  array (
    0 => 'function.fdf-enum-values.php',
    1 => 'fdf_enum_values',
  ),
  5 => 
  array (
    0 => 'function.fdf-errno.php',
    1 => 'fdf_errno',
  ),
  6 => 
  array (
    0 => 'function.fdf-error.php',
    1 => 'fdf_error',
  ),
  7 => 
  array (
    0 => 'function.fdf-get-ap.php',
    1 => 'fdf_get_ap',
  ),
  8 => 
  array (
    0 => 'function.fdf-get-attachment.php',
    1 => 'fdf_get_attachment',
  ),
  9 => 
  array (
    0 => 'function.fdf-get-encoding.php',
    1 => 'fdf_get_encoding',
  ),
  10 => 
  array (
    0 => 'function.fdf-get-file.php',
    1 => 'fdf_get_file',
  ),
  11 => 
  array (
    0 => 'function.fdf-get-flags.php',
    1 => 'fdf_get_flags',
  ),
  12 => 
  array (
    0 => 'function.fdf-get-opt.php',
    1 => 'fdf_get_opt',
  ),
  13 => 
  array (
    0 => 'function.fdf-get-status.php',
    1 => 'fdf_get_status',
  ),
  14 => 
  array (
    0 => 'function.fdf-get-value.php',
    1 => 'fdf_get_value',
  ),
  15 => 
  array (
    0 => 'function.fdf-get-version.php',
    1 => 'fdf_get_version',
  ),
  16 => 
  array (
    0 => 'function.fdf-header.php',
    1 => 'fdf_header',
  ),
  17 => 
  array (
    0 => 'function.fdf-next-field-name.php',
    1 => 'fdf_next_field_name',
  ),
  18 => 
  array (
    0 => 'function.fdf-open-string.php',
    1 => 'fdf_open_string',
  ),
  19 => 
  array (
    0 => 'function.fdf-open.php',
    1 => 'fdf_open',
  ),
  20 => 
  array (
    0 => 'function.fdf-remove-item.php',
    1 => 'fdf_remove_item',
  ),
  21 => 
  array (
    0 => 'function.fdf-save-string.php',
    1 => 'fdf_save_string',
  ),
  22 => 
  array (
    0 => 'function.fdf-save.php',
    1 => 'fdf_save',
  ),
  23 => 
  array (
    0 => 'function.fdf-set-ap.php',
    1 => 'fdf_set_ap',
  ),
  24 => 
  array (
    0 => 'function.fdf-set-encoding.php',
    1 => 'fdf_set_encoding',
  ),
  25 => 
  array (
    0 => 'function.fdf-set-file.php',
    1 => 'fdf_set_file',
  ),
  26 => 
  array (
    0 => 'function.fdf-set-flags.php',
    1 => 'fdf_set_flags',
  ),
  27 => 
  array (
    0 => 'function.fdf-set-javascript-action.php',
    1 => 'fdf_set_javascript_action',
  ),
  28 => 
  array (
    0 => 'function.fdf-set-on-import-javascript.php',
    1 => 'fdf_set_on_import_javascript',
  ),
  29 => 
  array (
    0 => 'function.fdf-set-opt.php',
    1 => 'fdf_set_opt',
  ),
  30 => 
  array (
    0 => 'function.fdf-set-status.php',
    1 => 'fdf_set_status',
  ),
  31 => 
  array (
    0 => 'function.fdf-set-submit-form-action.php',
    1 => 'fdf_set_submit_form_action',
  ),
  32 => 
  array (
    0 => 'function.fdf-set-target-frame.php',
    1 => 'fdf_set_target_frame',
  ),
  33 => 
  array (
    0 => 'function.fdf-set-value.php',
    1 => 'fdf_set_value',
  ),
  34 => 
  array (
    0 => 'function.fdf-set-version.php',
    1 => 'fdf_set_version',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.fdf.php',
    1 => 'FDF',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);