<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.sqlite-array-query.php',
    1 => 'sqlite_array_query',
  ),
  1 => 
  array (
    0 => 'function.sqlite-busy-timeout.php',
    1 => 'sqlite_busy_timeout',
  ),
  2 => 
  array (
    0 => 'function.sqlite-changes.php',
    1 => 'sqlite_changes',
  ),
  3 => 
  array (
    0 => 'function.sqlite-close.php',
    1 => 'sqlite_close',
  ),
  4 => 
  array (
    0 => 'function.sqlite-column.php',
    1 => 'sqlite_column',
  ),
  5 => 
  array (
    0 => 'function.sqlite-create-aggregate.php',
    1 => 'sqlite_create_aggregate',
  ),
  6 => 
  array (
    0 => 'function.sqlite-create-function.php',
    1 => 'sqlite_create_function',
  ),
  7 => 
  array (
    0 => 'function.sqlite-current.php',
    1 => 'sqlite_current',
  ),
  8 => 
  array (
    0 => 'function.sqlite-error-string.php',
    1 => 'sqlite_error_string',
  ),
  9 => 
  array (
    0 => 'function.sqlite-escape-string.php',
    1 => 'sqlite_escape_string',
  ),
  10 => 
  array (
    0 => 'function.sqlite-exec.php',
    1 => 'sqlite_exec',
  ),
  11 => 
  array (
    0 => 'function.sqlite-factory.php',
    1 => 'sqlite_factory',
  ),
  12 => 
  array (
    0 => 'function.sqlite-fetch-all.php',
    1 => 'sqlite_fetch_all',
  ),
  13 => 
  array (
    0 => 'function.sqlite-fetch-array.php',
    1 => 'sqlite_fetch_array',
  ),
  14 => 
  array (
    0 => 'function.sqlite-fetch-column-types.php',
    1 => 'sqlite_fetch_column_types',
  ),
  15 => 
  array (
    0 => 'function.sqlite-fetch-object.php',
    1 => 'sqlite_fetch_object',
  ),
  16 => 
  array (
    0 => 'function.sqlite-fetch-single.php',
    1 => 'sqlite_fetch_single',
  ),
  17 => 
  array (
    0 => 'function.sqlite-fetch-string.php',
    1 => 'sqlite_fetch_string',
  ),
  18 => 
  array (
    0 => 'function.sqlite-field-name.php',
    1 => 'sqlite_field_name',
  ),
  19 => 
  array (
    0 => 'function.sqlite-has-more.php',
    1 => 'sqlite_has_more',
  ),
  20 => 
  array (
    0 => 'function.sqlite-has-prev.php',
    1 => 'sqlite_has_prev',
  ),
  21 => 
  array (
    0 => 'function.sqlite-key.php',
    1 => 'sqlite_key',
  ),
  22 => 
  array (
    0 => 'function.sqlite-last-error.php',
    1 => 'sqlite_last_error',
  ),
  23 => 
  array (
    0 => 'function.sqlite-last-insert-rowid.php',
    1 => 'sqlite_last_insert_rowid',
  ),
  24 => 
  array (
    0 => 'function.sqlite-libencoding.php',
    1 => 'sqlite_libencoding',
  ),
  25 => 
  array (
    0 => 'function.sqlite-libversion.php',
    1 => 'sqlite_libversion',
  ),
  26 => 
  array (
    0 => 'function.sqlite-next.php',
    1 => 'sqlite_next',
  ),
  27 => 
  array (
    0 => 'function.sqlite-num-fields.php',
    1 => 'sqlite_num_fields',
  ),
  28 => 
  array (
    0 => 'function.sqlite-num-rows.php',
    1 => 'sqlite_num_rows',
  ),
  29 => 
  array (
    0 => 'function.sqlite-open.php',
    1 => 'sqlite_open',
  ),
  30 => 
  array (
    0 => 'function.sqlite-popen.php',
    1 => 'sqlite_popen',
  ),
  31 => 
  array (
    0 => 'function.sqlite-prev.php',
    1 => 'sqlite_prev',
  ),
  32 => 
  array (
    0 => 'function.sqlite-query.php',
    1 => 'sqlite_query',
  ),
  33 => 
  array (
    0 => 'function.sqlite-rewind.php',
    1 => 'sqlite_rewind',
  ),
  34 => 
  array (
    0 => 'function.sqlite-seek.php',
    1 => 'sqlite_seek',
  ),
  35 => 
  array (
    0 => 'function.sqlite-single-query.php',
    1 => 'sqlite_single_query',
  ),
  36 => 
  array (
    0 => 'function.sqlite-udf-decode-binary.php',
    1 => 'sqlite_udf_decode_binary',
  ),
  37 => 
  array (
    0 => 'function.sqlite-udf-encode-binary.php',
    1 => 'sqlite_udf_encode_binary',
  ),
  38 => 
  array (
    0 => 'function.sqlite-unbuffered-query.php',
    1 => 'sqlite_unbuffered_query',
  ),
  39 => 
  array (
    0 => 'function.sqlite-valid.php',
    1 => 'sqlite_valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sqlite.php',
    1 => 'SQLite',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);