<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.mb-check-encoding.php',
    1 => 'mb_check_encoding',
  ),
  1 => 
  array (
    0 => 'function.mb-convert-case.php',
    1 => 'mb_convert_case',
  ),
  2 => 
  array (
    0 => 'function.mb-convert-encoding.php',
    1 => 'mb_convert_encoding',
  ),
  3 => 
  array (
    0 => 'function.mb-convert-kana.php',
    1 => 'mb_convert_kana',
  ),
  4 => 
  array (
    0 => 'function.mb-convert-variables.php',
    1 => 'mb_convert_variables',
  ),
  5 => 
  array (
    0 => 'function.mb-decode-mimeheader.php',
    1 => 'mb_decode_mimeheader',
  ),
  6 => 
  array (
    0 => 'function.mb-decode-numericentity.php',
    1 => 'mb_decode_numericentity',
  ),
  7 => 
  array (
    0 => 'function.mb-detect-encoding.php',
    1 => 'mb_detect_encoding',
  ),
  8 => 
  array (
    0 => 'function.mb-detect-order.php',
    1 => 'mb_detect_order',
  ),
  9 => 
  array (
    0 => 'function.mb-encode-mimeheader.php',
    1 => 'mb_encode_mimeheader',
  ),
  10 => 
  array (
    0 => 'function.mb-encode-numericentity.php',
    1 => 'mb_encode_numericentity',
  ),
  11 => 
  array (
    0 => 'function.mb-encoding-aliases.php',
    1 => 'mb_encoding_aliases',
  ),
  12 => 
  array (
    0 => 'function.mb-ereg-match.php',
    1 => 'mb_ereg_match',
  ),
  13 => 
  array (
    0 => 'function.mb-ereg-replace.php',
    1 => 'mb_ereg_replace',
  ),
  14 => 
  array (
    0 => 'function.mb-ereg-search-getpos.php',
    1 => 'mb_ereg_search_getpos',
  ),
  15 => 
  array (
    0 => 'function.mb-ereg-search-getregs.php',
    1 => 'mb_ereg_search_getregs',
  ),
  16 => 
  array (
    0 => 'function.mb-ereg-search-init.php',
    1 => 'mb_ereg_search_init',
  ),
  17 => 
  array (
    0 => 'function.mb-ereg-search-pos.php',
    1 => 'mb_ereg_search_pos',
  ),
  18 => 
  array (
    0 => 'function.mb-ereg-search-regs.php',
    1 => 'mb_ereg_search_regs',
  ),
  19 => 
  array (
    0 => 'function.mb-ereg-search-setpos.php',
    1 => 'mb_ereg_search_setpos',
  ),
  20 => 
  array (
    0 => 'function.mb-ereg-search.php',
    1 => 'mb_ereg_search',
  ),
  21 => 
  array (
    0 => 'function.mb-ereg.php',
    1 => 'mb_ereg',
  ),
  22 => 
  array (
    0 => 'function.mb-eregi-replace.php',
    1 => 'mb_eregi_replace',
  ),
  23 => 
  array (
    0 => 'function.mb-eregi.php',
    1 => 'mb_eregi',
  ),
  24 => 
  array (
    0 => 'function.mb-get-info.php',
    1 => 'mb_get_info',
  ),
  25 => 
  array (
    0 => 'function.mb-http-input.php',
    1 => 'mb_http_input',
  ),
  26 => 
  array (
    0 => 'function.mb-http-output.php',
    1 => 'mb_http_output',
  ),
  27 => 
  array (
    0 => 'function.mb-internal-encoding.php',
    1 => 'mb_internal_encoding',
  ),
  28 => 
  array (
    0 => 'function.mb-language.php',
    1 => 'mb_language',
  ),
  29 => 
  array (
    0 => 'function.mb-list-encodings.php',
    1 => 'mb_list_encodings',
  ),
  30 => 
  array (
    0 => 'function.mb-output-handler.php',
    1 => 'mb_output_handler',
  ),
  31 => 
  array (
    0 => 'function.mb-parse-str.php',
    1 => 'mb_parse_str',
  ),
  32 => 
  array (
    0 => 'function.mb-preferred-mime-name.php',
    1 => 'mb_preferred_mime_name',
  ),
  33 => 
  array (
    0 => 'function.mb-regex-encoding.php',
    1 => 'mb_regex_encoding',
  ),
  34 => 
  array (
    0 => 'function.mb-regex-set-options.php',
    1 => 'mb_regex_set_options',
  ),
  35 => 
  array (
    0 => 'function.mb-send-mail.php',
    1 => 'mb_send_mail',
  ),
  36 => 
  array (
    0 => 'function.mb-split.php',
    1 => 'mb_split',
  ),
  37 => 
  array (
    0 => 'function.mb-strcut.php',
    1 => 'mb_strcut',
  ),
  38 => 
  array (
    0 => 'function.mb-strimwidth.php',
    1 => 'mb_strimwidth',
  ),
  39 => 
  array (
    0 => 'function.mb-stripos.php',
    1 => 'mb_stripos',
  ),
  40 => 
  array (
    0 => 'function.mb-stristr.php',
    1 => 'mb_stristr',
  ),
  41 => 
  array (
    0 => 'function.mb-strlen.php',
    1 => 'mb_strlen',
  ),
  42 => 
  array (
    0 => 'function.mb-strpos.php',
    1 => 'mb_strpos',
  ),
  43 => 
  array (
    0 => 'function.mb-strrchr.php',
    1 => 'mb_strrchr',
  ),
  44 => 
  array (
    0 => 'function.mb-strrichr.php',
    1 => 'mb_strrichr',
  ),
  45 => 
  array (
    0 => 'function.mb-strripos.php',
    1 => 'mb_strripos',
  ),
  46 => 
  array (
    0 => 'function.mb-strrpos.php',
    1 => 'mb_strrpos',
  ),
  47 => 
  array (
    0 => 'function.mb-strstr.php',
    1 => 'mb_strstr',
  ),
  48 => 
  array (
    0 => 'function.mb-strtolower.php',
    1 => 'mb_strtolower',
  ),
  49 => 
  array (
    0 => 'function.mb-strtoupper.php',
    1 => 'mb_strtoupper',
  ),
  50 => 
  array (
    0 => 'function.mb-strwidth.php',
    1 => 'mb_strwidth',
  ),
  51 => 
  array (
    0 => 'function.mb-substitute-character.php',
    1 => 'mb_substitute_character',
  ),
  52 => 
  array (
    0 => 'function.mb-substr-count.php',
    1 => 'mb_substr_count',
  ),
  53 => 
  array (
    0 => 'function.mb-substr.php',
    1 => 'mb_substr',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mbstring.php',
    1 => 'Multibyte String',
  ),
  1 => 
  array (
    0 => 'refs.international.php',
    1 => 'Human Language and Character Encoding Support',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);