<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.inotify-add-watch.php',
    1 => 'inotify_add_watch',
  ),
  1 => 
  array (
    0 => 'function.inotify-init.php',
    1 => 'inotify_init',
  ),
  2 => 
  array (
    0 => 'function.inotify-queue-len.php',
    1 => 'inotify_queue_len',
  ),
  3 => 
  array (
    0 => 'function.inotify-read.php',
    1 => 'inotify_read',
  ),
  4 => 
  array (
    0 => 'function.inotify-rm-watch.php',
    1 => 'inotify_rm_watch',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.inotify.php',
    1 => 'Inotify',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.file.php',
    1 => 'File System Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);