<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.chdir.php',
    1 => 'chdir',
  ),
  1 => 
  array (
    0 => 'function.chroot.php',
    1 => 'chroot',
  ),
  2 => 
  array (
    0 => 'class.dir.php',
    1 => 'dir',
  ),
  3 => 
  array (
    0 => 'function.closedir.php',
    1 => 'closedir',
  ),
  4 => 
  array (
    0 => 'function.getcwd.php',
    1 => 'getcwd',
  ),
  5 => 
  array (
    0 => 'function.opendir.php',
    1 => 'opendir',
  ),
  6 => 
  array (
    0 => 'function.readdir.php',
    1 => 'readdir',
  ),
  7 => 
  array (
    0 => 'function.rewinddir.php',
    1 => 'rewinddir',
  ),
  8 => 
  array (
    0 => 'function.scandir.php',
    1 => 'scandir',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dir.php',
    1 => 'Directories',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.file.php',
    1 => 'File System Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);