<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.calcul-hmac.php',
    1 => 'calcul_hmac',
  ),
  1 => 
  array (
    0 => 'function.calculhmac.php',
    1 => 'calculhmac',
  ),
  2 => 
  array (
    0 => 'function.nthmac.php',
    1 => 'nthmac',
  ),
  3 => 
  array (
    0 => 'function.signeurlpaiement.php',
    1 => 'signeurlpaiement',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.spplus.php',
    1 => 'SPPLUS',
  ),
  1 => 
  array (
    0 => 'refs.creditcard.php',
    1 => 'Credit Card Processing',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);