<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ingres-autocommit-state.php',
    1 => 'ingres_autocommit_state',
  ),
  1 => 
  array (
    0 => 'function.ingres-autocommit.php',
    1 => 'ingres_autocommit',
  ),
  2 => 
  array (
    0 => 'function.ingres-charset.php',
    1 => 'ingres_charset',
  ),
  3 => 
  array (
    0 => 'function.ingres-close.php',
    1 => 'ingres_close',
  ),
  4 => 
  array (
    0 => 'function.ingres-commit.php',
    1 => 'ingres_commit',
  ),
  5 => 
  array (
    0 => 'function.ingres-connect.php',
    1 => 'ingres_connect',
  ),
  6 => 
  array (
    0 => 'function.ingres-cursor.php',
    1 => 'ingres_cursor',
  ),
  7 => 
  array (
    0 => 'function.ingres-errno.php',
    1 => 'ingres_errno',
  ),
  8 => 
  array (
    0 => 'function.ingres-error.php',
    1 => 'ingres_error',
  ),
  9 => 
  array (
    0 => 'function.ingres-errsqlstate.php',
    1 => 'ingres_errsqlstate',
  ),
  10 => 
  array (
    0 => 'function.ingres-escape-string.php',
    1 => 'ingres_escape_string',
  ),
  11 => 
  array (
    0 => 'function.ingres-execute.php',
    1 => 'ingres_execute',
  ),
  12 => 
  array (
    0 => 'function.ingres-fetch-array.php',
    1 => 'ingres_fetch_array',
  ),
  13 => 
  array (
    0 => 'function.ingres-fetch-assoc.php',
    1 => 'ingres_fetch_assoc',
  ),
  14 => 
  array (
    0 => 'function.ingres-fetch-object.php',
    1 => 'ingres_fetch_object',
  ),
  15 => 
  array (
    0 => 'function.ingres-fetch-proc-return.php',
    1 => 'ingres_fetch_proc_return',
  ),
  16 => 
  array (
    0 => 'function.ingres-fetch-row.php',
    1 => 'ingres_fetch_row',
  ),
  17 => 
  array (
    0 => 'function.ingres-field-length.php',
    1 => 'ingres_field_length',
  ),
  18 => 
  array (
    0 => 'function.ingres-field-name.php',
    1 => 'ingres_field_name',
  ),
  19 => 
  array (
    0 => 'function.ingres-field-nullable.php',
    1 => 'ingres_field_nullable',
  ),
  20 => 
  array (
    0 => 'function.ingres-field-precision.php',
    1 => 'ingres_field_precision',
  ),
  21 => 
  array (
    0 => 'function.ingres-field-scale.php',
    1 => 'ingres_field_scale',
  ),
  22 => 
  array (
    0 => 'function.ingres-field-type.php',
    1 => 'ingres_field_type',
  ),
  23 => 
  array (
    0 => 'function.ingres-free-result.php',
    1 => 'ingres_free_result',
  ),
  24 => 
  array (
    0 => 'function.ingres-next-error.php',
    1 => 'ingres_next_error',
  ),
  25 => 
  array (
    0 => 'function.ingres-num-fields.php',
    1 => 'ingres_num_fields',
  ),
  26 => 
  array (
    0 => 'function.ingres-num-rows.php',
    1 => 'ingres_num_rows',
  ),
  27 => 
  array (
    0 => 'function.ingres-pconnect.php',
    1 => 'ingres_pconnect',
  ),
  28 => 
  array (
    0 => 'function.ingres-prepare.php',
    1 => 'ingres_prepare',
  ),
  29 => 
  array (
    0 => 'function.ingres-query.php',
    1 => 'ingres_query',
  ),
  30 => 
  array (
    0 => 'function.ingres-result-seek.php',
    1 => 'ingres_result_seek',
  ),
  31 => 
  array (
    0 => 'function.ingres-rollback.php',
    1 => 'ingres_rollback',
  ),
  32 => 
  array (
    0 => 'function.ingres-set-environment.php',
    1 => 'ingres_set_environment',
  ),
  33 => 
  array (
    0 => 'function.ingres-unbuffered-query.php',
    1 => 'ingres_unbuffered_query',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ingres.php',
    1 => 'Ingres',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);