<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.dba-close.php',
    1 => 'dba_close',
  ),
  1 => 
  array (
    0 => 'function.dba-delete.php',
    1 => 'dba_delete',
  ),
  2 => 
  array (
    0 => 'function.dba-exists.php',
    1 => 'dba_exists',
  ),
  3 => 
  array (
    0 => 'function.dba-fetch.php',
    1 => 'dba_fetch',
  ),
  4 => 
  array (
    0 => 'function.dba-firstkey.php',
    1 => 'dba_firstkey',
  ),
  5 => 
  array (
    0 => 'function.dba-handlers.php',
    1 => 'dba_handlers',
  ),
  6 => 
  array (
    0 => 'function.dba-insert.php',
    1 => 'dba_insert',
  ),
  7 => 
  array (
    0 => 'function.dba-key-split.php',
    1 => 'dba_key_split',
  ),
  8 => 
  array (
    0 => 'function.dba-list.php',
    1 => 'dba_list',
  ),
  9 => 
  array (
    0 => 'function.dba-nextkey.php',
    1 => 'dba_nextkey',
  ),
  10 => 
  array (
    0 => 'function.dba-open.php',
    1 => 'dba_open',
  ),
  11 => 
  array (
    0 => 'function.dba-optimize.php',
    1 => 'dba_optimize',
  ),
  12 => 
  array (
    0 => 'function.dba-popen.php',
    1 => 'dba_popen',
  ),
  13 => 
  array (
    0 => 'function.dba-replace.php',
    1 => 'dba_replace',
  ),
  14 => 
  array (
    0 => 'function.dba-sync.php',
    1 => 'dba_sync',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dba.php',
    1 => 'DBA',
  ),
  1 => 
  array (
    0 => 'refs.database.abstract.php',
    1 => 'Abstraction Layers',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);