<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.notes-body.php',
    1 => 'notes_body',
  ),
  1 => 
  array (
    0 => 'function.notes-copy-db.php',
    1 => 'notes_copy_db',
  ),
  2 => 
  array (
    0 => 'function.notes-create-db.php',
    1 => 'notes_create_db',
  ),
  3 => 
  array (
    0 => 'function.notes-create-note.php',
    1 => 'notes_create_note',
  ),
  4 => 
  array (
    0 => 'function.notes-drop-db.php',
    1 => 'notes_drop_db',
  ),
  5 => 
  array (
    0 => 'function.notes-find-note.php',
    1 => 'notes_find_note',
  ),
  6 => 
  array (
    0 => 'function.notes-header-info.php',
    1 => 'notes_header_info',
  ),
  7 => 
  array (
    0 => 'function.notes-list-msgs.php',
    1 => 'notes_list_msgs',
  ),
  8 => 
  array (
    0 => 'function.notes-mark-read.php',
    1 => 'notes_mark_read',
  ),
  9 => 
  array (
    0 => 'function.notes-mark-unread.php',
    1 => 'notes_mark_unread',
  ),
  10 => 
  array (
    0 => 'function.notes-nav-create.php',
    1 => 'notes_nav_create',
  ),
  11 => 
  array (
    0 => 'function.notes-search.php',
    1 => 'notes_search',
  ),
  12 => 
  array (
    0 => 'function.notes-unread.php',
    1 => 'notes_unread',
  ),
  13 => 
  array (
    0 => 'function.notes-version.php',
    1 => 'notes_version',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.notes.php',
    1 => 'Lotus Notes',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);