<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ssdeep-fuzzy-compare.php',
    1 => 'ssdeep_fuzzy_compare',
  ),
  1 => 
  array (
    0 => 'function.ssdeep-fuzzy-hash-filename.php',
    1 => 'ssdeep_fuzzy_hash_filename',
  ),
  2 => 
  array (
    0 => 'function.ssdeep-fuzzy-hash.php',
    1 => 'ssdeep_fuzzy_hash',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ssdeep.php',
    1 => 'ssdeep',
  ),
  1 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'Text Processing',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);