<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.win32-ps-list-procs.php',
    1 => 'win32_ps_list_procs',
  ),
  1 => 
  array (
    0 => 'function.win32-ps-stat-mem.php',
    1 => 'win32_ps_stat_mem',
  ),
  2 => 
  array (
    0 => 'function.win32-ps-stat-proc.php',
    1 => 'win32_ps_stat_proc',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.win32ps.php',
    1 => 'win32ps',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);