<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.mqseries-back.php',
    1 => 'mqseries_back',
  ),
  1 => 
  array (
    0 => 'function.mqseries-begin.php',
    1 => 'mqseries_begin',
  ),
  2 => 
  array (
    0 => 'function.mqseries-close.php',
    1 => 'mqseries_close',
  ),
  3 => 
  array (
    0 => 'function.mqseries-cmit.php',
    1 => 'mqseries_cmit',
  ),
  4 => 
  array (
    0 => 'function.mqseries-conn.php',
    1 => 'mqseries_conn',
  ),
  5 => 
  array (
    0 => 'function.mqseries-connx.php',
    1 => 'mqseries_connx',
  ),
  6 => 
  array (
    0 => 'function.mqseries-disc.php',
    1 => 'mqseries_disc',
  ),
  7 => 
  array (
    0 => 'function.mqseries-get.php',
    1 => 'mqseries_get',
  ),
  8 => 
  array (
    0 => 'function.mqseries-inq.php',
    1 => 'mqseries_inq',
  ),
  9 => 
  array (
    0 => 'function.mqseries-open.php',
    1 => 'mqseries_open',
  ),
  10 => 
  array (
    0 => 'function.mqseries-put1.php',
    1 => 'mqseries_put1',
  ),
  11 => 
  array (
    0 => 'function.mqseries-put.php',
    1 => 'mqseries_put',
  ),
  12 => 
  array (
    0 => 'function.mqseries-set.php',
    1 => 'mqseries_set',
  ),
  13 => 
  array (
    0 => 'function.mqseries-strerror.php',
    1 => 'mqseries_strerror',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mqseries.php',
    1 => 'mqseries',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);