<?php
$TOC = array (
  0 => 
  array (
    0 => 'class.com.php',
    1 => 'COM',
  ),
  1 => 
  array (
    0 => 'class.dotnet.php',
    1 => 'DOTNET',
  ),
  2 => 
  array (
    0 => 'class.variant.php',
    1 => 'VARIANT',
  ),
  3 => 
  array (
    0 => 'function.com-addref.php',
    1 => 'com_addref',
  ),
  4 => 
  array (
    0 => 'function.com-create-guid.php',
    1 => 'com_create_guid',
  ),
  5 => 
  array (
    0 => 'function.com-event-sink.php',
    1 => 'com_event_sink',
  ),
  6 => 
  array (
    0 => 'function.com-get-active-object.php',
    1 => 'com_get_active_object',
  ),
  7 => 
  array (
    0 => 'function.com-get.php',
    1 => 'com_get',
  ),
  8 => 
  array (
    0 => 'function.com-invoke.php',
    1 => 'com_invoke',
  ),
  9 => 
  array (
    0 => 'function.com-isenum.php',
    1 => 'com_isenum',
  ),
  10 => 
  array (
    0 => 'function.com-load-typelib.php',
    1 => 'com_load_typelib',
  ),
  11 => 
  array (
    0 => 'function.com-load.php',
    1 => 'com_load',
  ),
  12 => 
  array (
    0 => 'function.com-message-pump.php',
    1 => 'com_message_pump',
  ),
  13 => 
  array (
    0 => 'function.com-print-typeinfo.php',
    1 => 'com_print_typeinfo',
  ),
  14 => 
  array (
    0 => 'function.com-propget.php',
    1 => 'com_propget',
  ),
  15 => 
  array (
    0 => 'function.com-propput.php',
    1 => 'com_propput',
  ),
  16 => 
  array (
    0 => 'function.com-propset.php',
    1 => 'com_propset',
  ),
  17 => 
  array (
    0 => 'function.com-release.php',
    1 => 'com_release',
  ),
  18 => 
  array (
    0 => 'function.com-set.php',
    1 => 'com_set',
  ),
  19 => 
  array (
    0 => 'function.variant-abs.php',
    1 => 'variant_abs',
  ),
  20 => 
  array (
    0 => 'function.variant-add.php',
    1 => 'variant_add',
  ),
  21 => 
  array (
    0 => 'function.variant-and.php',
    1 => 'variant_and',
  ),
  22 => 
  array (
    0 => 'function.variant-cast.php',
    1 => 'variant_cast',
  ),
  23 => 
  array (
    0 => 'function.variant-cat.php',
    1 => 'variant_cat',
  ),
  24 => 
  array (
    0 => 'function.variant-cmp.php',
    1 => 'variant_cmp',
  ),
  25 => 
  array (
    0 => 'function.variant-date-from-timestamp.php',
    1 => 'variant_date_from_timestamp',
  ),
  26 => 
  array (
    0 => 'function.variant-date-to-timestamp.php',
    1 => 'variant_date_to_timestamp',
  ),
  27 => 
  array (
    0 => 'function.variant-div.php',
    1 => 'variant_div',
  ),
  28 => 
  array (
    0 => 'function.variant-eqv.php',
    1 => 'variant_eqv',
  ),
  29 => 
  array (
    0 => 'function.variant-fix.php',
    1 => 'variant_fix',
  ),
  30 => 
  array (
    0 => 'function.variant-get-type.php',
    1 => 'variant_get_type',
  ),
  31 => 
  array (
    0 => 'function.variant-idiv.php',
    1 => 'variant_idiv',
  ),
  32 => 
  array (
    0 => 'function.variant-imp.php',
    1 => 'variant_imp',
  ),
  33 => 
  array (
    0 => 'function.variant-int.php',
    1 => 'variant_int',
  ),
  34 => 
  array (
    0 => 'function.variant-mod.php',
    1 => 'variant_mod',
  ),
  35 => 
  array (
    0 => 'function.variant-mul.php',
    1 => 'variant_mul',
  ),
  36 => 
  array (
    0 => 'function.variant-neg.php',
    1 => 'variant_neg',
  ),
  37 => 
  array (
    0 => 'function.variant-not.php',
    1 => 'variant_not',
  ),
  38 => 
  array (
    0 => 'function.variant-or.php',
    1 => 'variant_or',
  ),
  39 => 
  array (
    0 => 'function.variant-pow.php',
    1 => 'variant_pow',
  ),
  40 => 
  array (
    0 => 'function.variant-round.php',
    1 => 'variant_round',
  ),
  41 => 
  array (
    0 => 'function.variant-set-type.php',
    1 => 'variant_set_type',
  ),
  42 => 
  array (
    0 => 'function.variant-set.php',
    1 => 'variant_set',
  ),
  43 => 
  array (
    0 => 'function.variant-sub.php',
    1 => 'variant_sub',
  ),
  44 => 
  array (
    0 => 'function.variant-xor.php',
    1 => 'variant_xor',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.com.php',
    1 => 'COM',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);