<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.class-implements.php',
    1 => 'class_implements',
  ),
  1 => 
  array (
    0 => 'function.class-parents.php',
    1 => 'class_parents',
  ),
  2 => 
  array (
    0 => 'function.iterator-apply.php',
    1 => 'iterator_apply',
  ),
  3 => 
  array (
    0 => 'function.iterator-count.php',
    1 => 'iterator_count',
  ),
  4 => 
  array (
    0 => 'function.iterator-to-array.php',
    1 => 'iterator_to_array',
  ),
  5 => 
  array (
    0 => 'function.spl-autoload-call.php',
    1 => 'spl_autoload_call',
  ),
  6 => 
  array (
    0 => 'function.spl-autoload-extensions.php',
    1 => 'spl_autoload_extensions',
  ),
  7 => 
  array (
    0 => 'function.spl-autoload-functions.php',
    1 => 'spl_autoload_functions',
  ),
  8 => 
  array (
    0 => 'function.spl-autoload-register.php',
    1 => 'spl_autoload_register',
  ),
  9 => 
  array (
    0 => 'function.spl-autoload-unregister.php',
    1 => 'spl_autoload_unregister',
  ),
  10 => 
  array (
    0 => 'function.spl-autoload.php',
    1 => 'spl_autoload',
  ),
  11 => 
  array (
    0 => 'function.spl-classes.php',
    1 => 'spl_classes',
  ),
  12 => 
  array (
    0 => 'function.spl-object-hash.php',
    1 => 'spl_object_hash',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);