<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.cubrid-affected-rows.php',
    1 => 'cubrid_affected_rows',
  ),
  1 => 
  array (
    0 => 'function.cubrid-bind.php',
    1 => 'cubrid_bind',
  ),
  2 => 
  array (
    0 => 'function.cubrid-close-prepare.php',
    1 => 'cubrid_close_prepare',
  ),
  3 => 
  array (
    0 => 'function.cubrid-close-request.php',
    1 => 'cubrid_close_request',
  ),
  4 => 
  array (
    0 => 'function.cubrid-col-get.php',
    1 => 'cubrid_col_get',
  ),
  5 => 
  array (
    0 => 'function.cubrid-col-size.php',
    1 => 'cubrid_col_size',
  ),
  6 => 
  array (
    0 => 'function.cubrid-column-names.php',
    1 => 'cubrid_column_names',
  ),
  7 => 
  array (
    0 => 'function.cubrid-column-types.php',
    1 => 'cubrid_column_types',
  ),
  8 => 
  array (
    0 => 'function.cubrid-commit.php',
    1 => 'cubrid_commit',
  ),
  9 => 
  array (
    0 => 'function.cubrid-connect-with-url.php',
    1 => 'cubrid_connect_with_url',
  ),
  10 => 
  array (
    0 => 'function.cubrid-connect.php',
    1 => 'cubrid_connect',
  ),
  11 => 
  array (
    0 => 'function.cubrid-current-oid.php',
    1 => 'cubrid_current_oid',
  ),
  12 => 
  array (
    0 => 'function.cubrid-data-seek.php',
    1 => 'cubrid_data_seek',
  ),
  13 => 
  array (
    0 => 'function.cubrid-disconnect.php',
    1 => 'cubrid_disconnect',
  ),
  14 => 
  array (
    0 => 'function.cubrid-drop.php',
    1 => 'cubrid_drop',
  ),
  15 => 
  array (
    0 => 'function.cubrid-error-code-facility.php',
    1 => 'cubrid_error_code_facility',
  ),
  16 => 
  array (
    0 => 'function.cubrid-error-code.php',
    1 => 'cubrid_error_code',
  ),
  17 => 
  array (
    0 => 'function.cubrid-error-msg.php',
    1 => 'cubrid_error_msg',
  ),
  18 => 
  array (
    0 => 'function.cubrid-execute.php',
    1 => 'cubrid_execute',
  ),
  19 => 
  array (
    0 => 'function.cubrid-fetch-array.php',
    1 => 'cubrid_fetch_array',
  ),
  20 => 
  array (
    0 => 'function.cubrid-fetch-assoc.php',
    1 => 'cubrid_fetch_assoc',
  ),
  21 => 
  array (
    0 => 'function.cubrid-fetch-field.php',
    1 => 'cubrid_fetch_field',
  ),
  22 => 
  array (
    0 => 'function.cubrid-fetch-lengths.php',
    1 => 'cubrid_fetch_lengths',
  ),
  23 => 
  array (
    0 => 'function.cubrid-fetch-object.php',
    1 => 'cubrid_fetch_object',
  ),
  24 => 
  array (
    0 => 'function.cubrid-fetch-row.php',
    1 => 'cubrid_fetch_row',
  ),
  25 => 
  array (
    0 => 'function.cubrid-fetch.php',
    1 => 'cubrid_fetch',
  ),
  26 => 
  array (
    0 => 'function.cubrid-field-flags.php',
    1 => 'cubrid_field_flags',
  ),
  27 => 
  array (
    0 => 'function.cubrid-field-len.php',
    1 => 'cubrid_field_len',
  ),
  28 => 
  array (
    0 => 'function.cubrid-field-name.php',
    1 => 'cubrid_field_name',
  ),
  29 => 
  array (
    0 => 'function.cubrid-field-seek.php',
    1 => 'cubrid_field_seek',
  ),
  30 => 
  array (
    0 => 'function.cubrid-field-table.php',
    1 => 'cubrid_field_table',
  ),
  31 => 
  array (
    0 => 'function.cubrid-field-type.php',
    1 => 'cubrid_field_type',
  ),
  32 => 
  array (
    0 => 'function.cubrid-free-result.php',
    1 => 'cubrid_free_result',
  ),
  33 => 
  array (
    0 => 'function.cubrid-get-charset.php',
    1 => 'cubrid_get_charset',
  ),
  34 => 
  array (
    0 => 'function.cubrid-get-class-name.php',
    1 => 'cubrid_get_class_name',
  ),
  35 => 
  array (
    0 => 'function.cubrid-get-client-info.php',
    1 => 'cubrid_get_client_info',
  ),
  36 => 
  array (
    0 => 'function.cubrid-get-db-parameter.php',
    1 => 'cubrid_get_db_parameter',
  ),
  37 => 
  array (
    0 => 'function.cubrid-get-server-info.php',
    1 => 'cubrid_get_server_info',
  ),
  38 => 
  array (
    0 => 'function.cubrid-get.php',
    1 => 'cubrid_get',
  ),
  39 => 
  array (
    0 => 'function.cubrid-insert-id.php',
    1 => 'cubrid_insert_id',
  ),
  40 => 
  array (
    0 => 'function.cubrid-is-instance.php',
    1 => 'cubrid_is_instance',
  ),
  41 => 
  array (
    0 => 'function.cubrid-list-dbs.php',
    1 => 'cubrid_list_dbs',
  ),
  42 => 
  array (
    0 => 'function.cubrid-load-from-glo.php',
    1 => 'cubrid_load_from_glo',
  ),
  43 => 
  array (
    0 => 'function.cubrid-lock-read.php',
    1 => 'cubrid_lock_read',
  ),
  44 => 
  array (
    0 => 'function.cubrid-lock-write.php',
    1 => 'cubrid_lock_write',
  ),
  45 => 
  array (
    0 => 'function.cubrid-move-cursor.php',
    1 => 'cubrid_move_cursor',
  ),
  46 => 
  array (
    0 => 'function.cubrid-new-glo.php',
    1 => 'cubrid_new_glo',
  ),
  47 => 
  array (
    0 => 'function.cubrid-num-cols.php',
    1 => 'cubrid_num_cols',
  ),
  48 => 
  array (
    0 => 'function.cubrid-num-fields.php',
    1 => 'cubrid_num_fields',
  ),
  49 => 
  array (
    0 => 'function.cubrid-num-rows.php',
    1 => 'cubrid_num_rows',
  ),
  50 => 
  array (
    0 => 'function.cubrid-prepare.php',
    1 => 'cubrid_prepare',
  ),
  51 => 
  array (
    0 => 'function.cubrid-put.php',
    1 => 'cubrid_put',
  ),
  52 => 
  array (
    0 => 'function.cubrid-real-escape-string.php',
    1 => 'cubrid_real_escape_string',
  ),
  53 => 
  array (
    0 => 'function.cubrid-result.php',
    1 => 'cubrid_result',
  ),
  54 => 
  array (
    0 => 'function.cubrid-rollback.php',
    1 => 'cubrid_rollback',
  ),
  55 => 
  array (
    0 => 'function.cubrid-save-to-glo.php',
    1 => 'cubrid_save_to_glo',
  ),
  56 => 
  array (
    0 => 'function.cubrid-schema.php',
    1 => 'cubrid_schema',
  ),
  57 => 
  array (
    0 => 'function.cubrid-send-glo.php',
    1 => 'cubrid_send_glo',
  ),
  58 => 
  array (
    0 => 'function.cubrid-seq-drop.php',
    1 => 'cubrid_seq_drop',
  ),
  59 => 
  array (
    0 => 'function.cubrid-seq-insert.php',
    1 => 'cubrid_seq_insert',
  ),
  60 => 
  array (
    0 => 'function.cubrid-seq-put.php',
    1 => 'cubrid_seq_put',
  ),
  61 => 
  array (
    0 => 'function.cubrid-set-add.php',
    1 => 'cubrid_set_add',
  ),
  62 => 
  array (
    0 => 'function.cubrid-set-drop.php',
    1 => 'cubrid_set_drop',
  ),
  63 => 
  array (
    0 => 'function.cubrid-unbuffered-query.php',
    1 => 'cubrid_unbuffered_query',
  ),
  64 => 
  array (
    0 => 'function.cubrid-version.php',
    1 => 'cubrid_version',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cubrid.php',
    1 => 'Cubrid',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);