<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.bson-decode.php',
    1 => 'bson_decode',
  ),
  1 => 
  array (
    0 => 'function.bson-encode.php',
    1 => 'bson_encode',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'mongo.functions.php',
    1 => 'Functions',
  ),
  1 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  2 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  3 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  4 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  5 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);