<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.session-pgsql-add-error.php',
    1 => 'session_pgsql_add_error',
  ),
  1 => 
  array (
    0 => 'function.session-pgsql-get-error.php',
    1 => 'session_pgsql_get_error',
  ),
  2 => 
  array (
    0 => 'function.session-pgsql-get-field.php',
    1 => 'session_pgsql_get_field',
  ),
  3 => 
  array (
    0 => 'function.session-pgsql-reset.php',
    1 => 'session_pgsql_reset',
  ),
  4 => 
  array (
    0 => 'function.session-pgsql-set-field.php',
    1 => 'session_pgsql_set_field',
  ),
  5 => 
  array (
    0 => 'function.session-pgsql-status.php',
    1 => 'session_pgsql_status',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.session-pgsql.php',
    1 => 'Session PgSQL',
  ),
  1 => 
  array (
    0 => 'refs.basic.session.php',
    1 => 'Session Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);