<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.finfo-buffer.php',
    1 => 'finfo_buffer',
  ),
  1 => 
  array (
    0 => 'function.finfo-close.php',
    1 => 'finfo_close',
  ),
  2 => 
  array (
    0 => 'function.finfo-file.php',
    1 => 'finfo_file',
  ),
  3 => 
  array (
    0 => 'function.finfo-open.php',
    1 => 'finfo_open',
  ),
  4 => 
  array (
    0 => 'function.finfo-set-flags.php',
    1 => 'finfo_set_flags',
  ),
  5 => 
  array (
    0 => 'function.mime-content-type.php',
    1 => 'mime_content_type',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.fileinfo.php',
    1 => 'Fileinfo',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.file.php',
    1 => 'File System Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);