<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.posix-access.php',
    1 => 'posix_access',
  ),
  1 => 
  array (
    0 => 'function.posix-ctermid.php',
    1 => 'posix_ctermid',
  ),
  2 => 
  array (
    0 => 'function.posix-errno.php',
    1 => 'posix_errno',
  ),
  3 => 
  array (
    0 => 'function.posix-get-last-error.php',
    1 => 'posix_get_last_error',
  ),
  4 => 
  array (
    0 => 'function.posix-getcwd.php',
    1 => 'posix_getcwd',
  ),
  5 => 
  array (
    0 => 'function.posix-getegid.php',
    1 => 'posix_getegid',
  ),
  6 => 
  array (
    0 => 'function.posix-geteuid.php',
    1 => 'posix_geteuid',
  ),
  7 => 
  array (
    0 => 'function.posix-getgid.php',
    1 => 'posix_getgid',
  ),
  8 => 
  array (
    0 => 'function.posix-getgrgid.php',
    1 => 'posix_getgrgid',
  ),
  9 => 
  array (
    0 => 'function.posix-getgrnam.php',
    1 => 'posix_getgrnam',
  ),
  10 => 
  array (
    0 => 'function.posix-getgroups.php',
    1 => 'posix_getgroups',
  ),
  11 => 
  array (
    0 => 'function.posix-getlogin.php',
    1 => 'posix_getlogin',
  ),
  12 => 
  array (
    0 => 'function.posix-getpgid.php',
    1 => 'posix_getpgid',
  ),
  13 => 
  array (
    0 => 'function.posix-getpgrp.php',
    1 => 'posix_getpgrp',
  ),
  14 => 
  array (
    0 => 'function.posix-getpid.php',
    1 => 'posix_getpid',
  ),
  15 => 
  array (
    0 => 'function.posix-getppid.php',
    1 => 'posix_getppid',
  ),
  16 => 
  array (
    0 => 'function.posix-getpwnam.php',
    1 => 'posix_getpwnam',
  ),
  17 => 
  array (
    0 => 'function.posix-getpwuid.php',
    1 => 'posix_getpwuid',
  ),
  18 => 
  array (
    0 => 'function.posix-getrlimit.php',
    1 => 'posix_getrlimit',
  ),
  19 => 
  array (
    0 => 'function.posix-getsid.php',
    1 => 'posix_getsid',
  ),
  20 => 
  array (
    0 => 'function.posix-getuid.php',
    1 => 'posix_getuid',
  ),
  21 => 
  array (
    0 => 'function.posix-initgroups.php',
    1 => 'posix_initgroups',
  ),
  22 => 
  array (
    0 => 'function.posix-isatty.php',
    1 => 'posix_isatty',
  ),
  23 => 
  array (
    0 => 'function.posix-kill.php',
    1 => 'posix_kill',
  ),
  24 => 
  array (
    0 => 'function.posix-mkfifo.php',
    1 => 'posix_mkfifo',
  ),
  25 => 
  array (
    0 => 'function.posix-mknod.php',
    1 => 'posix_mknod',
  ),
  26 => 
  array (
    0 => 'function.posix-setegid.php',
    1 => 'posix_setegid',
  ),
  27 => 
  array (
    0 => 'function.posix-seteuid.php',
    1 => 'posix_seteuid',
  ),
  28 => 
  array (
    0 => 'function.posix-setgid.php',
    1 => 'posix_setgid',
  ),
  29 => 
  array (
    0 => 'function.posix-setpgid.php',
    1 => 'posix_setpgid',
  ),
  30 => 
  array (
    0 => 'function.posix-setsid.php',
    1 => 'posix_setsid',
  ),
  31 => 
  array (
    0 => 'function.posix-setuid.php',
    1 => 'posix_setuid',
  ),
  32 => 
  array (
    0 => 'function.posix-strerror.php',
    1 => 'posix_strerror',
  ),
  33 => 
  array (
    0 => 'function.posix-times.php',
    1 => 'posix_times',
  ),
  34 => 
  array (
    0 => 'function.posix-ttyname.php',
    1 => 'posix_ttyname',
  ),
  35 => 
  array (
    0 => 'function.posix-uname.php',
    1 => 'posix_uname',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.posix.php',
    1 => 'POSIX',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);