<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.readline-add-history.php',
    1 => 'readline_add_history',
  ),
  1 => 
  array (
    0 => 'function.readline-callback-handler-install.php',
    1 => 'readline_callback_handler_install',
  ),
  2 => 
  array (
    0 => 'function.readline-callback-handler-remove.php',
    1 => 'readline_callback_handler_remove',
  ),
  3 => 
  array (
    0 => 'function.readline-callback-read-char.php',
    1 => 'readline_callback_read_char',
  ),
  4 => 
  array (
    0 => 'function.readline-clear-history.php',
    1 => 'readline_clear_history',
  ),
  5 => 
  array (
    0 => 'function.readline-completion-function.php',
    1 => 'readline_completion_function',
  ),
  6 => 
  array (
    0 => 'function.readline-info.php',
    1 => 'readline_info',
  ),
  7 => 
  array (
    0 => 'function.readline-list-history.php',
    1 => 'readline_list_history',
  ),
  8 => 
  array (
    0 => 'function.readline-on-new-line.php',
    1 => 'readline_on_new_line',
  ),
  9 => 
  array (
    0 => 'function.readline-read-history.php',
    1 => 'readline_read_history',
  ),
  10 => 
  array (
    0 => 'function.readline-redisplay.php',
    1 => 'readline_redisplay',
  ),
  11 => 
  array (
    0 => 'function.readline-write-history.php',
    1 => 'readline_write_history',
  ),
  12 => 
  array (
    0 => 'function.readline.php',
    1 => 'readline',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.readline.php',
    1 => 'Readline',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.cmdline.php',
    1 => 'Command Line Specific Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);