<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.json-decode.php',
    1 => 'json_decode',
  ),
  1 => 
  array (
    0 => 'function.json-encode.php',
    1 => 'json_encode',
  ),
  2 => 
  array (
    0 => 'function.json-last-error.php',
    1 => 'json_last_error',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.json.php',
    1 => 'JSON',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);