<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.domattribute-name.php',
    1 => 'DomAttribute-&gt;name',
  ),
  1 => 
  array (
    0 => 'function.domattribute-set-value.php',
    1 => 'DomAttribute-&gt;set_value',
  ),
  2 => 
  array (
    0 => 'function.domattribute-specified.php',
    1 => 'DomAttribute-&gt;specified',
  ),
  3 => 
  array (
    0 => 'function.domattribute-value.php',
    1 => 'DomAttribute-&gt;value',
  ),
  4 => 
  array (
    0 => 'function.domdocument-add-root.php',
    1 => 'DomDocument-&gt;add_root',
  ),
  5 => 
  array (
    0 => 'function.domdocument-create-attribute.php',
    1 => 'DomDocument-&gt;create_attribute',
  ),
  6 => 
  array (
    0 => 'function.domdocument-create-cdata-section.php',
    1 => 'DomDocument-&gt;create_cdata_section',
  ),
  7 => 
  array (
    0 => 'function.domdocument-create-comment.php',
    1 => 'DomDocument-&gt;create_comment',
  ),
  8 => 
  array (
    0 => 'function.domdocument-create-element-ns.php',
    1 => 'DomDocument-&gt;create_element_ns',
  ),
  9 => 
  array (
    0 => 'function.domdocument-create-element.php',
    1 => 'DomDocument-&gt;create_element',
  ),
  10 => 
  array (
    0 => 'function.domdocument-create-entity-reference.php',
    1 => 'DomDocument-&gt;create_entity_reference',
  ),
  11 => 
  array (
    0 => 'function.domdocument-create-processing-instruction.php',
    1 => 'DomDocument-&gt;create_processing_instruction',
  ),
  12 => 
  array (
    0 => 'function.domdocument-create-text-node.php',
    1 => 'DomDocument-&gt;create_text_node',
  ),
  13 => 
  array (
    0 => 'function.domdocument-doctype.php',
    1 => 'DomDocument-&gt;doctype',
  ),
  14 => 
  array (
    0 => 'function.domdocument-document-element.php',
    1 => 'DomDocument-&gt;document_element',
  ),
  15 => 
  array (
    0 => 'function.domdocument-dump-file.php',
    1 => 'DomDocument-&gt;dump_file',
  ),
  16 => 
  array (
    0 => 'function.domdocument-dump-mem.php',
    1 => 'DomDocument-&gt;dump_mem',
  ),
  17 => 
  array (
    0 => 'function.domdocument-get-element-by-id.php',
    1 => 'DomDocument-&gt;get_element_by_id',
  ),
  18 => 
  array (
    0 => 'function.domdocument-get-elements-by-tagname.php',
    1 => 'DomDocument-&gt;get_elements_by_tagname',
  ),
  19 => 
  array (
    0 => 'function.domdocument-html-dump-mem.php',
    1 => 'DomDocument-&gt;html_dump_mem',
  ),
  20 => 
  array (
    0 => 'function.domdocument-xinclude.php',
    1 => 'DomDocument-&gt;xinclude',
  ),
  21 => 
  array (
    0 => 'function.domdocumenttype-entities.php',
    1 => 'DomDocumentType-&gt;entities',
  ),
  22 => 
  array (
    0 => 'function.domdocumenttype-internal-subset.php',
    1 => 'DomDocumentType-&gt;internal_subset',
  ),
  23 => 
  array (
    0 => 'function.domdocumenttype-name.php',
    1 => 'DomDocumentType-&gt;name',
  ),
  24 => 
  array (
    0 => 'function.domdocumenttype-notations.php',
    1 => 'DomDocumentType-&gt;notations',
  ),
  25 => 
  array (
    0 => 'function.domdocumenttype-public-id.php',
    1 => 'DomDocumentType-&gt;public_id',
  ),
  26 => 
  array (
    0 => 'function.domdocumenttype-system-id.php',
    1 => 'DomDocumentType-&gt;system_id',
  ),
  27 => 
  array (
    0 => 'function.domelement-get-attribute-node.php',
    1 => 'DomElement-&gt;get_attribute_node',
  ),
  28 => 
  array (
    0 => 'function.domelement-get-attribute.php',
    1 => 'DomElement-&gt;get_attribute',
  ),
  29 => 
  array (
    0 => 'function.domelement-get-elements-by-tagname.php',
    1 => 'DomElement-&gt;get_elements_by_tagname',
  ),
  30 => 
  array (
    0 => 'function.domelement-has-attribute.php',
    1 => 'DomElement-&gt;has_attribute',
  ),
  31 => 
  array (
    0 => 'function.domelement-remove-attribute.php',
    1 => 'DomElement-&gt;remove_attribute',
  ),
  32 => 
  array (
    0 => 'function.domelement-set-attribute-node.php',
    1 => 'DomElement-&gt;set_attribute_node',
  ),
  33 => 
  array (
    0 => 'function.domelement-set-attribute.php',
    1 => 'DomElement-&gt;set_attribute',
  ),
  34 => 
  array (
    0 => 'function.domelement-tagname.php',
    1 => 'DomElement-&gt;tagname',
  ),
  35 => 
  array (
    0 => 'function.domnode-add-namespace.php',
    1 => 'DomNode-&gt;add_namespace',
  ),
  36 => 
  array (
    0 => 'function.domnode-append-child.php',
    1 => 'DomNode-&gt;append_child',
  ),
  37 => 
  array (
    0 => 'function.domnode-append-sibling.php',
    1 => 'DomNode-&gt;append_sibling',
  ),
  38 => 
  array (
    0 => 'function.domnode-attributes.php',
    1 => 'DomNode-&gt;attributes',
  ),
  39 => 
  array (
    0 => 'function.domnode-child-nodes.php',
    1 => 'DomNode-&gt;child_nodes',
  ),
  40 => 
  array (
    0 => 'function.domnode-clone-node.php',
    1 => 'DomNode-&gt;clone_node',
  ),
  41 => 
  array (
    0 => 'function.domnode-dump-node.php',
    1 => 'DomNode-&gt;dump_node',
  ),
  42 => 
  array (
    0 => 'function.domnode-first-child.php',
    1 => 'DomNode-&gt;first_child',
  ),
  43 => 
  array (
    0 => 'function.domnode-get-content.php',
    1 => 'DomNode-&gt;get_content',
  ),
  44 => 
  array (
    0 => 'function.domnode-has-attributes.php',
    1 => 'DomNode-&gt;has_attributes',
  ),
  45 => 
  array (
    0 => 'function.domnode-has-child-nodes.php',
    1 => 'DomNode-&gt;has_child_nodes',
  ),
  46 => 
  array (
    0 => 'function.domnode-insert-before.php',
    1 => 'DomNode-&gt;insert_before',
  ),
  47 => 
  array (
    0 => 'function.domnode-is-blank-node.php',
    1 => 'DomNode-&gt;is_blank_node',
  ),
  48 => 
  array (
    0 => 'function.domnode-last-child.php',
    1 => 'DomNode-&gt;last_child',
  ),
  49 => 
  array (
    0 => 'function.domnode-next-sibling.php',
    1 => 'DomNode-&gt;next_sibling',
  ),
  50 => 
  array (
    0 => 'function.domnode-node-name.php',
    1 => 'DomNode-&gt;node_name',
  ),
  51 => 
  array (
    0 => 'function.domnode-node-type.php',
    1 => 'DomNode-&gt;node_type',
  ),
  52 => 
  array (
    0 => 'function.domnode-node-value.php',
    1 => 'DomNode-&gt;node_value',
  ),
  53 => 
  array (
    0 => 'function.domnode-owner-document.php',
    1 => 'DomNode-&gt;owner_document',
  ),
  54 => 
  array (
    0 => 'function.domnode-parent-node.php',
    1 => 'DomNode-&gt;parent_node',
  ),
  55 => 
  array (
    0 => 'function.domnode-prefix.php',
    1 => 'DomNode-&gt;prefix',
  ),
  56 => 
  array (
    0 => 'function.domnode-previous-sibling.php',
    1 => 'DomNode-&gt;previous_sibling',
  ),
  57 => 
  array (
    0 => 'function.domnode-remove-child.php',
    1 => 'DomNode-&gt;remove_child',
  ),
  58 => 
  array (
    0 => 'function.domnode-replace-child.php',
    1 => 'DomNode-&gt;replace_child',
  ),
  59 => 
  array (
    0 => 'function.domnode-replace-node.php',
    1 => 'DomNode-&gt;replace_node',
  ),
  60 => 
  array (
    0 => 'function.domnode-set-content.php',
    1 => 'DomNode-&gt;set_content',
  ),
  61 => 
  array (
    0 => 'function.domnode-set-name.php',
    1 => 'DomNode-&gt;set_name',
  ),
  62 => 
  array (
    0 => 'function.domnode-set-namespace.php',
    1 => 'DomNode-&gt;set_namespace',
  ),
  63 => 
  array (
    0 => 'function.domnode-unlink-node.php',
    1 => 'DomNode-&gt;unlink_node',
  ),
  64 => 
  array (
    0 => 'function.domprocessinginstruction-data.php',
    1 => 'DomProcessingInstruction-&gt;data',
  ),
  65 => 
  array (
    0 => 'function.domprocessinginstruction-target.php',
    1 => 'DomProcessingInstruction-&gt;target',
  ),
  66 => 
  array (
    0 => 'function.domxsltstylesheet-process.php',
    1 => 'DomXsltStylesheet-&gt;process',
  ),
  67 => 
  array (
    0 => 'function.domxsltstylesheet-result-dump-file.php',
    1 => 'DomXsltStylesheet-&gt;result_dump_file',
  ),
  68 => 
  array (
    0 => 'function.domxsltstylesheet-result-dump-mem.php',
    1 => 'DomXsltStylesheet-&gt;result_dump_mem',
  ),
  69 => 
  array (
    0 => 'function.domxml-new-doc.php',
    1 => 'domxml_new_doc',
  ),
  70 => 
  array (
    0 => 'function.domxml-open-file.php',
    1 => 'domxml_open_file',
  ),
  71 => 
  array (
    0 => 'function.domxml-open-mem.php',
    1 => 'domxml_open_mem',
  ),
  72 => 
  array (
    0 => 'function.domxml-version.php',
    1 => 'domxml_version',
  ),
  73 => 
  array (
    0 => 'function.domxml-xmltree.php',
    1 => 'domxml_xmltree',
  ),
  74 => 
  array (
    0 => 'function.domxml-xslt-stylesheet-doc.php',
    1 => 'domxml_xslt_stylesheet_doc',
  ),
  75 => 
  array (
    0 => 'function.domxml-xslt-stylesheet-file.php',
    1 => 'domxml_xslt_stylesheet_file',
  ),
  76 => 
  array (
    0 => 'function.domxml-xslt-stylesheet.php',
    1 => 'domxml_xslt_stylesheet',
  ),
  77 => 
  array (
    0 => 'function.domxml-xslt-version.php',
    1 => 'domxml_xslt_version',
  ),
  78 => 
  array (
    0 => 'function.xpath-eval-expression.php',
    1 => 'xpath_eval_expression',
  ),
  79 => 
  array (
    0 => 'function.xpath-eval.php',
    1 => 'xpath_eval',
  ),
  80 => 
  array (
    0 => 'function.xpath-new-context.php',
    1 => 'xpath_new_context',
  ),
  81 => 
  array (
    0 => 'function.xpath-register-ns-auto.php',
    1 => 'xpath_register_ns_auto',
  ),
  82 => 
  array (
    0 => 'function.xpath-register-ns.php',
    1 => 'xpath_register_ns',
  ),
  83 => 
  array (
    0 => 'function.xptr-eval.php',
    1 => 'xptr_eval',
  ),
  84 => 
  array (
    0 => 'function.xptr-new-context.php',
    1 => 'xptr_new_context',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.domxml.php',
    1 => 'DOM XML (PHP 4)',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);