<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.yaml-emit-file.php',
    1 => 'yaml_emit_file',
  ),
  1 => 
  array (
    0 => 'function.yaml-emit.php',
    1 => 'yaml_emit',
  ),
  2 => 
  array (
    0 => 'function.yaml-parse-file.php',
    1 => 'yaml_parse_file',
  ),
  3 => 
  array (
    0 => 'function.yaml-parse-url.php',
    1 => 'yaml_parse_url',
  ),
  4 => 
  array (
    0 => 'function.yaml-parse.php',
    1 => 'yaml_parse',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaml.php',
    1 => 'Yaml',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);