<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.w32api-deftype.php',
    1 => 'w32api_deftype',
  ),
  1 => 
  array (
    0 => 'function.w32api-init-dtype.php',
    1 => 'w32api_init_dtype',
  ),
  2 => 
  array (
    0 => 'function.w32api-invoke-function.php',
    1 => 'w32api_invoke_function',
  ),
  3 => 
  array (
    0 => 'function.w32api-register-function.php',
    1 => 'w32api_register_function',
  ),
  4 => 
  array (
    0 => 'function.w32api-set-call-method.php',
    1 => 'w32api_set_call_method',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.w32api.php',
    1 => 'W32api',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);