<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.svn-add.php',
    1 => 'svn_add',
  ),
  1 => 
  array (
    0 => 'function.svn-auth-get-parameter.php',
    1 => 'svn_auth_get_parameter',
  ),
  2 => 
  array (
    0 => 'function.svn-auth-set-parameter.php',
    1 => 'svn_auth_set_parameter',
  ),
  3 => 
  array (
    0 => 'function.svn-blame.php',
    1 => 'svn_blame',
  ),
  4 => 
  array (
    0 => 'function.svn-cat.php',
    1 => 'svn_cat',
  ),
  5 => 
  array (
    0 => 'function.svn-checkout.php',
    1 => 'svn_checkout',
  ),
  6 => 
  array (
    0 => 'function.svn-cleanup.php',
    1 => 'svn_cleanup',
  ),
  7 => 
  array (
    0 => 'function.svn-client-version.php',
    1 => 'svn_client_version',
  ),
  8 => 
  array (
    0 => 'function.svn-commit.php',
    1 => 'svn_commit',
  ),
  9 => 
  array (
    0 => 'function.svn-delete.php',
    1 => 'svn_delete',
  ),
  10 => 
  array (
    0 => 'function.svn-diff.php',
    1 => 'svn_diff',
  ),
  11 => 
  array (
    0 => 'function.svn-export.php',
    1 => 'svn_export',
  ),
  12 => 
  array (
    0 => 'function.svn-fs-abort-txn.php',
    1 => 'svn_fs_abort_txn',
  ),
  13 => 
  array (
    0 => 'function.svn-fs-apply-text.php',
    1 => 'svn_fs_apply_text',
  ),
  14 => 
  array (
    0 => 'function.svn-fs-begin-txn2.php',
    1 => 'svn_fs_begin_txn2',
  ),
  15 => 
  array (
    0 => 'function.svn-fs-change-node-prop.php',
    1 => 'svn_fs_change_node_prop',
  ),
  16 => 
  array (
    0 => 'function.svn-fs-check-path.php',
    1 => 'svn_fs_check_path',
  ),
  17 => 
  array (
    0 => 'function.svn-fs-contents-changed.php',
    1 => 'svn_fs_contents_changed',
  ),
  18 => 
  array (
    0 => 'function.svn-fs-copy.php',
    1 => 'svn_fs_copy',
  ),
  19 => 
  array (
    0 => 'function.svn-fs-delete.php',
    1 => 'svn_fs_delete',
  ),
  20 => 
  array (
    0 => 'function.svn-fs-dir-entries.php',
    1 => 'svn_fs_dir_entries',
  ),
  21 => 
  array (
    0 => 'function.svn-fs-file-contents.php',
    1 => 'svn_fs_file_contents',
  ),
  22 => 
  array (
    0 => 'function.svn-fs-file-length.php',
    1 => 'svn_fs_file_length',
  ),
  23 => 
  array (
    0 => 'function.svn-fs-is-dir.php',
    1 => 'svn_fs_is_dir',
  ),
  24 => 
  array (
    0 => 'function.svn-fs-is-file.php',
    1 => 'svn_fs_is_file',
  ),
  25 => 
  array (
    0 => 'function.svn-fs-make-dir.php',
    1 => 'svn_fs_make_dir',
  ),
  26 => 
  array (
    0 => 'function.svn-fs-make-file.php',
    1 => 'svn_fs_make_file',
  ),
  27 => 
  array (
    0 => 'function.svn-fs-node-created-rev.php',
    1 => 'svn_fs_node_created_rev',
  ),
  28 => 
  array (
    0 => 'function.svn-fs-node-prop.php',
    1 => 'svn_fs_node_prop',
  ),
  29 => 
  array (
    0 => 'function.svn-fs-props-changed.php',
    1 => 'svn_fs_props_changed',
  ),
  30 => 
  array (
    0 => 'function.svn-fs-revision-prop.php',
    1 => 'svn_fs_revision_prop',
  ),
  31 => 
  array (
    0 => 'function.svn-fs-revision-root.php',
    1 => 'svn_fs_revision_root',
  ),
  32 => 
  array (
    0 => 'function.svn-fs-txn-root.php',
    1 => 'svn_fs_txn_root',
  ),
  33 => 
  array (
    0 => 'function.svn-fs-youngest-rev.php',
    1 => 'svn_fs_youngest_rev',
  ),
  34 => 
  array (
    0 => 'function.svn-import.php',
    1 => 'svn_import',
  ),
  35 => 
  array (
    0 => 'function.svn-log.php',
    1 => 'svn_log',
  ),
  36 => 
  array (
    0 => 'function.svn-ls.php',
    1 => 'svn_ls',
  ),
  37 => 
  array (
    0 => 'function.svn-mkdir.php',
    1 => 'svn_mkdir',
  ),
  38 => 
  array (
    0 => 'function.svn-repos-create.php',
    1 => 'svn_repos_create',
  ),
  39 => 
  array (
    0 => 'function.svn-repos-fs-begin-txn-for-commit.php',
    1 => 'svn_repos_fs_begin_txn_for_commit',
  ),
  40 => 
  array (
    0 => 'function.svn-repos-fs-commit-txn.php',
    1 => 'svn_repos_fs_commit_txn',
  ),
  41 => 
  array (
    0 => 'function.svn-repos-fs.php',
    1 => 'svn_repos_fs',
  ),
  42 => 
  array (
    0 => 'function.svn-repos-hotcopy.php',
    1 => 'svn_repos_hotcopy',
  ),
  43 => 
  array (
    0 => 'function.svn-repos-open.php',
    1 => 'svn_repos_open',
  ),
  44 => 
  array (
    0 => 'function.svn-repos-recover.php',
    1 => 'svn_repos_recover',
  ),
  45 => 
  array (
    0 => 'function.svn-revert.php',
    1 => 'svn_revert',
  ),
  46 => 
  array (
    0 => 'function.svn-status.php',
    1 => 'svn_status',
  ),
  47 => 
  array (
    0 => 'function.svn-update.php',
    1 => 'svn_update',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.svn.php',
    1 => 'SVN',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);