<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ncurses-addch.php',
    1 => 'ncurses_addch',
  ),
  1 => 
  array (
    0 => 'function.ncurses-addchnstr.php',
    1 => 'ncurses_addchnstr',
  ),
  2 => 
  array (
    0 => 'function.ncurses-addchstr.php',
    1 => 'ncurses_addchstr',
  ),
  3 => 
  array (
    0 => 'function.ncurses-addnstr.php',
    1 => 'ncurses_addnstr',
  ),
  4 => 
  array (
    0 => 'function.ncurses-addstr.php',
    1 => 'ncurses_addstr',
  ),
  5 => 
  array (
    0 => 'function.ncurses-assume-default-colors.php',
    1 => 'ncurses_assume_default_colors',
  ),
  6 => 
  array (
    0 => 'function.ncurses-attroff.php',
    1 => 'ncurses_attroff',
  ),
  7 => 
  array (
    0 => 'function.ncurses-attron.php',
    1 => 'ncurses_attron',
  ),
  8 => 
  array (
    0 => 'function.ncurses-attrset.php',
    1 => 'ncurses_attrset',
  ),
  9 => 
  array (
    0 => 'function.ncurses-baudrate.php',
    1 => 'ncurses_baudrate',
  ),
  10 => 
  array (
    0 => 'function.ncurses-beep.php',
    1 => 'ncurses_beep',
  ),
  11 => 
  array (
    0 => 'function.ncurses-bkgd.php',
    1 => 'ncurses_bkgd',
  ),
  12 => 
  array (
    0 => 'function.ncurses-bkgdset.php',
    1 => 'ncurses_bkgdset',
  ),
  13 => 
  array (
    0 => 'function.ncurses-border.php',
    1 => 'ncurses_border',
  ),
  14 => 
  array (
    0 => 'function.ncurses-bottom-panel.php',
    1 => 'ncurses_bottom_panel',
  ),
  15 => 
  array (
    0 => 'function.ncurses-can-change-color.php',
    1 => 'ncurses_can_change_color',
  ),
  16 => 
  array (
    0 => 'function.ncurses-cbreak.php',
    1 => 'ncurses_cbreak',
  ),
  17 => 
  array (
    0 => 'function.ncurses-clear.php',
    1 => 'ncurses_clear',
  ),
  18 => 
  array (
    0 => 'function.ncurses-clrtobot.php',
    1 => 'ncurses_clrtobot',
  ),
  19 => 
  array (
    0 => 'function.ncurses-clrtoeol.php',
    1 => 'ncurses_clrtoeol',
  ),
  20 => 
  array (
    0 => 'function.ncurses-color-content.php',
    1 => 'ncurses_color_content',
  ),
  21 => 
  array (
    0 => 'function.ncurses-color-set.php',
    1 => 'ncurses_color_set',
  ),
  22 => 
  array (
    0 => 'function.ncurses-curs-set.php',
    1 => 'ncurses_curs_set',
  ),
  23 => 
  array (
    0 => 'function.ncurses-def-prog-mode.php',
    1 => 'ncurses_def_prog_mode',
  ),
  24 => 
  array (
    0 => 'function.ncurses-def-shell-mode.php',
    1 => 'ncurses_def_shell_mode',
  ),
  25 => 
  array (
    0 => 'function.ncurses-define-key.php',
    1 => 'ncurses_define_key',
  ),
  26 => 
  array (
    0 => 'function.ncurses-del-panel.php',
    1 => 'ncurses_del_panel',
  ),
  27 => 
  array (
    0 => 'function.ncurses-delay-output.php',
    1 => 'ncurses_delay_output',
  ),
  28 => 
  array (
    0 => 'function.ncurses-delch.php',
    1 => 'ncurses_delch',
  ),
  29 => 
  array (
    0 => 'function.ncurses-deleteln.php',
    1 => 'ncurses_deleteln',
  ),
  30 => 
  array (
    0 => 'function.ncurses-delwin.php',
    1 => 'ncurses_delwin',
  ),
  31 => 
  array (
    0 => 'function.ncurses-doupdate.php',
    1 => 'ncurses_doupdate',
  ),
  32 => 
  array (
    0 => 'function.ncurses-echo.php',
    1 => 'ncurses_echo',
  ),
  33 => 
  array (
    0 => 'function.ncurses-echochar.php',
    1 => 'ncurses_echochar',
  ),
  34 => 
  array (
    0 => 'function.ncurses-end.php',
    1 => 'ncurses_end',
  ),
  35 => 
  array (
    0 => 'function.ncurses-erase.php',
    1 => 'ncurses_erase',
  ),
  36 => 
  array (
    0 => 'function.ncurses-erasechar.php',
    1 => 'ncurses_erasechar',
  ),
  37 => 
  array (
    0 => 'function.ncurses-filter.php',
    1 => 'ncurses_filter',
  ),
  38 => 
  array (
    0 => 'function.ncurses-flash.php',
    1 => 'ncurses_flash',
  ),
  39 => 
  array (
    0 => 'function.ncurses-flushinp.php',
    1 => 'ncurses_flushinp',
  ),
  40 => 
  array (
    0 => 'function.ncurses-getch.php',
    1 => 'ncurses_getch',
  ),
  41 => 
  array (
    0 => 'function.ncurses-getmaxyx.php',
    1 => 'ncurses_getmaxyx',
  ),
  42 => 
  array (
    0 => 'function.ncurses-getmouse.php',
    1 => 'ncurses_getmouse',
  ),
  43 => 
  array (
    0 => 'function.ncurses-getyx.php',
    1 => 'ncurses_getyx',
  ),
  44 => 
  array (
    0 => 'function.ncurses-halfdelay.php',
    1 => 'ncurses_halfdelay',
  ),
  45 => 
  array (
    0 => 'function.ncurses-has-colors.php',
    1 => 'ncurses_has_colors',
  ),
  46 => 
  array (
    0 => 'function.ncurses-has-ic.php',
    1 => 'ncurses_has_ic',
  ),
  47 => 
  array (
    0 => 'function.ncurses-has-il.php',
    1 => 'ncurses_has_il',
  ),
  48 => 
  array (
    0 => 'function.ncurses-has-key.php',
    1 => 'ncurses_has_key',
  ),
  49 => 
  array (
    0 => 'function.ncurses-hide-panel.php',
    1 => 'ncurses_hide_panel',
  ),
  50 => 
  array (
    0 => 'function.ncurses-hline.php',
    1 => 'ncurses_hline',
  ),
  51 => 
  array (
    0 => 'function.ncurses-inch.php',
    1 => 'ncurses_inch',
  ),
  52 => 
  array (
    0 => 'function.ncurses-init-color.php',
    1 => 'ncurses_init_color',
  ),
  53 => 
  array (
    0 => 'function.ncurses-init-pair.php',
    1 => 'ncurses_init_pair',
  ),
  54 => 
  array (
    0 => 'function.ncurses-init.php',
    1 => 'ncurses_init',
  ),
  55 => 
  array (
    0 => 'function.ncurses-insch.php',
    1 => 'ncurses_insch',
  ),
  56 => 
  array (
    0 => 'function.ncurses-insdelln.php',
    1 => 'ncurses_insdelln',
  ),
  57 => 
  array (
    0 => 'function.ncurses-insertln.php',
    1 => 'ncurses_insertln',
  ),
  58 => 
  array (
    0 => 'function.ncurses-insstr.php',
    1 => 'ncurses_insstr',
  ),
  59 => 
  array (
    0 => 'function.ncurses-instr.php',
    1 => 'ncurses_instr',
  ),
  60 => 
  array (
    0 => 'function.ncurses-isendwin.php',
    1 => 'ncurses_isendwin',
  ),
  61 => 
  array (
    0 => 'function.ncurses-keyok.php',
    1 => 'ncurses_keyok',
  ),
  62 => 
  array (
    0 => 'function.ncurses-keypad.php',
    1 => 'ncurses_keypad',
  ),
  63 => 
  array (
    0 => 'function.ncurses-killchar.php',
    1 => 'ncurses_killchar',
  ),
  64 => 
  array (
    0 => 'function.ncurses-longname.php',
    1 => 'ncurses_longname',
  ),
  65 => 
  array (
    0 => 'function.ncurses-meta.php',
    1 => 'ncurses_meta',
  ),
  66 => 
  array (
    0 => 'function.ncurses-mouse-trafo.php',
    1 => 'ncurses_mouse_trafo',
  ),
  67 => 
  array (
    0 => 'function.ncurses-mouseinterval.php',
    1 => 'ncurses_mouseinterval',
  ),
  68 => 
  array (
    0 => 'function.ncurses-mousemask.php',
    1 => 'ncurses_mousemask',
  ),
  69 => 
  array (
    0 => 'function.ncurses-move-panel.php',
    1 => 'ncurses_move_panel',
  ),
  70 => 
  array (
    0 => 'function.ncurses-move.php',
    1 => 'ncurses_move',
  ),
  71 => 
  array (
    0 => 'function.ncurses-mvaddch.php',
    1 => 'ncurses_mvaddch',
  ),
  72 => 
  array (
    0 => 'function.ncurses-mvaddchnstr.php',
    1 => 'ncurses_mvaddchnstr',
  ),
  73 => 
  array (
    0 => 'function.ncurses-mvaddchstr.php',
    1 => 'ncurses_mvaddchstr',
  ),
  74 => 
  array (
    0 => 'function.ncurses-mvaddnstr.php',
    1 => 'ncurses_mvaddnstr',
  ),
  75 => 
  array (
    0 => 'function.ncurses-mvaddstr.php',
    1 => 'ncurses_mvaddstr',
  ),
  76 => 
  array (
    0 => 'function.ncurses-mvcur.php',
    1 => 'ncurses_mvcur',
  ),
  77 => 
  array (
    0 => 'function.ncurses-mvdelch.php',
    1 => 'ncurses_mvdelch',
  ),
  78 => 
  array (
    0 => 'function.ncurses-mvgetch.php',
    1 => 'ncurses_mvgetch',
  ),
  79 => 
  array (
    0 => 'function.ncurses-mvhline.php',
    1 => 'ncurses_mvhline',
  ),
  80 => 
  array (
    0 => 'function.ncurses-mvinch.php',
    1 => 'ncurses_mvinch',
  ),
  81 => 
  array (
    0 => 'function.ncurses-mvvline.php',
    1 => 'ncurses_mvvline',
  ),
  82 => 
  array (
    0 => 'function.ncurses-mvwaddstr.php',
    1 => 'ncurses_mvwaddstr',
  ),
  83 => 
  array (
    0 => 'function.ncurses-napms.php',
    1 => 'ncurses_napms',
  ),
  84 => 
  array (
    0 => 'function.ncurses-new-panel.php',
    1 => 'ncurses_new_panel',
  ),
  85 => 
  array (
    0 => 'function.ncurses-newpad.php',
    1 => 'ncurses_newpad',
  ),
  86 => 
  array (
    0 => 'function.ncurses-newwin.php',
    1 => 'ncurses_newwin',
  ),
  87 => 
  array (
    0 => 'function.ncurses-nl.php',
    1 => 'ncurses_nl',
  ),
  88 => 
  array (
    0 => 'function.ncurses-nocbreak.php',
    1 => 'ncurses_nocbreak',
  ),
  89 => 
  array (
    0 => 'function.ncurses-noecho.php',
    1 => 'ncurses_noecho',
  ),
  90 => 
  array (
    0 => 'function.ncurses-nonl.php',
    1 => 'ncurses_nonl',
  ),
  91 => 
  array (
    0 => 'function.ncurses-noqiflush.php',
    1 => 'ncurses_noqiflush',
  ),
  92 => 
  array (
    0 => 'function.ncurses-noraw.php',
    1 => 'ncurses_noraw',
  ),
  93 => 
  array (
    0 => 'function.ncurses-pair-content.php',
    1 => 'ncurses_pair_content',
  ),
  94 => 
  array (
    0 => 'function.ncurses-panel-above.php',
    1 => 'ncurses_panel_above',
  ),
  95 => 
  array (
    0 => 'function.ncurses-panel-below.php',
    1 => 'ncurses_panel_below',
  ),
  96 => 
  array (
    0 => 'function.ncurses-panel-window.php',
    1 => 'ncurses_panel_window',
  ),
  97 => 
  array (
    0 => 'function.ncurses-pnoutrefresh.php',
    1 => 'ncurses_pnoutrefresh',
  ),
  98 => 
  array (
    0 => 'function.ncurses-prefresh.php',
    1 => 'ncurses_prefresh',
  ),
  99 => 
  array (
    0 => 'function.ncurses-putp.php',
    1 => 'ncurses_putp',
  ),
  100 => 
  array (
    0 => 'function.ncurses-qiflush.php',
    1 => 'ncurses_qiflush',
  ),
  101 => 
  array (
    0 => 'function.ncurses-raw.php',
    1 => 'ncurses_raw',
  ),
  102 => 
  array (
    0 => 'function.ncurses-refresh.php',
    1 => 'ncurses_refresh',
  ),
  103 => 
  array (
    0 => 'function.ncurses-replace-panel.php',
    1 => 'ncurses_replace_panel',
  ),
  104 => 
  array (
    0 => 'function.ncurses-reset-prog-mode.php',
    1 => 'ncurses_reset_prog_mode',
  ),
  105 => 
  array (
    0 => 'function.ncurses-reset-shell-mode.php',
    1 => 'ncurses_reset_shell_mode',
  ),
  106 => 
  array (
    0 => 'function.ncurses-resetty.php',
    1 => 'ncurses_resetty',
  ),
  107 => 
  array (
    0 => 'function.ncurses-savetty.php',
    1 => 'ncurses_savetty',
  ),
  108 => 
  array (
    0 => 'function.ncurses-scr-dump.php',
    1 => 'ncurses_scr_dump',
  ),
  109 => 
  array (
    0 => 'function.ncurses-scr-init.php',
    1 => 'ncurses_scr_init',
  ),
  110 => 
  array (
    0 => 'function.ncurses-scr-restore.php',
    1 => 'ncurses_scr_restore',
  ),
  111 => 
  array (
    0 => 'function.ncurses-scr-set.php',
    1 => 'ncurses_scr_set',
  ),
  112 => 
  array (
    0 => 'function.ncurses-scrl.php',
    1 => 'ncurses_scrl',
  ),
  113 => 
  array (
    0 => 'function.ncurses-show-panel.php',
    1 => 'ncurses_show_panel',
  ),
  114 => 
  array (
    0 => 'function.ncurses-slk-attr.php',
    1 => 'ncurses_slk_attr',
  ),
  115 => 
  array (
    0 => 'function.ncurses-slk-attroff.php',
    1 => 'ncurses_slk_attroff',
  ),
  116 => 
  array (
    0 => 'function.ncurses-slk-attron.php',
    1 => 'ncurses_slk_attron',
  ),
  117 => 
  array (
    0 => 'function.ncurses-slk-attrset.php',
    1 => 'ncurses_slk_attrset',
  ),
  118 => 
  array (
    0 => 'function.ncurses-slk-clear.php',
    1 => 'ncurses_slk_clear',
  ),
  119 => 
  array (
    0 => 'function.ncurses-slk-color.php',
    1 => 'ncurses_slk_color',
  ),
  120 => 
  array (
    0 => 'function.ncurses-slk-init.php',
    1 => 'ncurses_slk_init',
  ),
  121 => 
  array (
    0 => 'function.ncurses-slk-noutrefresh.php',
    1 => 'ncurses_slk_noutrefresh',
  ),
  122 => 
  array (
    0 => 'function.ncurses-slk-refresh.php',
    1 => 'ncurses_slk_refresh',
  ),
  123 => 
  array (
    0 => 'function.ncurses-slk-restore.php',
    1 => 'ncurses_slk_restore',
  ),
  124 => 
  array (
    0 => 'function.ncurses-slk-set.php',
    1 => 'ncurses_slk_set',
  ),
  125 => 
  array (
    0 => 'function.ncurses-slk-touch.php',
    1 => 'ncurses_slk_touch',
  ),
  126 => 
  array (
    0 => 'function.ncurses-standend.php',
    1 => 'ncurses_standend',
  ),
  127 => 
  array (
    0 => 'function.ncurses-standout.php',
    1 => 'ncurses_standout',
  ),
  128 => 
  array (
    0 => 'function.ncurses-start-color.php',
    1 => 'ncurses_start_color',
  ),
  129 => 
  array (
    0 => 'function.ncurses-termattrs.php',
    1 => 'ncurses_termattrs',
  ),
  130 => 
  array (
    0 => 'function.ncurses-termname.php',
    1 => 'ncurses_termname',
  ),
  131 => 
  array (
    0 => 'function.ncurses-timeout.php',
    1 => 'ncurses_timeout',
  ),
  132 => 
  array (
    0 => 'function.ncurses-top-panel.php',
    1 => 'ncurses_top_panel',
  ),
  133 => 
  array (
    0 => 'function.ncurses-typeahead.php',
    1 => 'ncurses_typeahead',
  ),
  134 => 
  array (
    0 => 'function.ncurses-ungetch.php',
    1 => 'ncurses_ungetch',
  ),
  135 => 
  array (
    0 => 'function.ncurses-ungetmouse.php',
    1 => 'ncurses_ungetmouse',
  ),
  136 => 
  array (
    0 => 'function.ncurses-update-panels.php',
    1 => 'ncurses_update_panels',
  ),
  137 => 
  array (
    0 => 'function.ncurses-use-default-colors.php',
    1 => 'ncurses_use_default_colors',
  ),
  138 => 
  array (
    0 => 'function.ncurses-use-env.php',
    1 => 'ncurses_use_env',
  ),
  139 => 
  array (
    0 => 'function.ncurses-use-extended-names.php',
    1 => 'ncurses_use_extended_names',
  ),
  140 => 
  array (
    0 => 'function.ncurses-vidattr.php',
    1 => 'ncurses_vidattr',
  ),
  141 => 
  array (
    0 => 'function.ncurses-vline.php',
    1 => 'ncurses_vline',
  ),
  142 => 
  array (
    0 => 'function.ncurses-waddch.php',
    1 => 'ncurses_waddch',
  ),
  143 => 
  array (
    0 => 'function.ncurses-waddstr.php',
    1 => 'ncurses_waddstr',
  ),
  144 => 
  array (
    0 => 'function.ncurses-wattroff.php',
    1 => 'ncurses_wattroff',
  ),
  145 => 
  array (
    0 => 'function.ncurses-wattron.php',
    1 => 'ncurses_wattron',
  ),
  146 => 
  array (
    0 => 'function.ncurses-wattrset.php',
    1 => 'ncurses_wattrset',
  ),
  147 => 
  array (
    0 => 'function.ncurses-wborder.php',
    1 => 'ncurses_wborder',
  ),
  148 => 
  array (
    0 => 'function.ncurses-wclear.php',
    1 => 'ncurses_wclear',
  ),
  149 => 
  array (
    0 => 'function.ncurses-wcolor-set.php',
    1 => 'ncurses_wcolor_set',
  ),
  150 => 
  array (
    0 => 'function.ncurses-werase.php',
    1 => 'ncurses_werase',
  ),
  151 => 
  array (
    0 => 'function.ncurses-wgetch.php',
    1 => 'ncurses_wgetch',
  ),
  152 => 
  array (
    0 => 'function.ncurses-whline.php',
    1 => 'ncurses_whline',
  ),
  153 => 
  array (
    0 => 'function.ncurses-wmouse-trafo.php',
    1 => 'ncurses_wmouse_trafo',
  ),
  154 => 
  array (
    0 => 'function.ncurses-wmove.php',
    1 => 'ncurses_wmove',
  ),
  155 => 
  array (
    0 => 'function.ncurses-wnoutrefresh.php',
    1 => 'ncurses_wnoutrefresh',
  ),
  156 => 
  array (
    0 => 'function.ncurses-wrefresh.php',
    1 => 'ncurses_wrefresh',
  ),
  157 => 
  array (
    0 => 'function.ncurses-wstandend.php',
    1 => 'ncurses_wstandend',
  ),
  158 => 
  array (
    0 => 'function.ncurses-wstandout.php',
    1 => 'ncurses_wstandout',
  ),
  159 => 
  array (
    0 => 'function.ncurses-wvline.php',
    1 => 'ncurses_wvline',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ncurses.php',
    1 => 'Ncurses',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.cmdline.php',
    1 => 'Command Line Specific Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);