<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.db2-autocommit.php',
    1 => 'db2_autocommit',
  ),
  1 => 
  array (
    0 => 'function.db2-bind-param.php',
    1 => 'db2_bind_param',
  ),
  2 => 
  array (
    0 => 'function.db2-client-info.php',
    1 => 'db2_client_info',
  ),
  3 => 
  array (
    0 => 'function.db2-close.php',
    1 => 'db2_close',
  ),
  4 => 
  array (
    0 => 'function.db2-column-privileges.php',
    1 => 'db2_column_privileges',
  ),
  5 => 
  array (
    0 => 'function.db2-columns.php',
    1 => 'db2_columns',
  ),
  6 => 
  array (
    0 => 'function.db2-commit.php',
    1 => 'db2_commit',
  ),
  7 => 
  array (
    0 => 'function.db2-conn-error.php',
    1 => 'db2_conn_error',
  ),
  8 => 
  array (
    0 => 'function.db2-conn-errormsg.php',
    1 => 'db2_conn_errormsg',
  ),
  9 => 
  array (
    0 => 'function.db2-connect.php',
    1 => 'db2_connect',
  ),
  10 => 
  array (
    0 => 'function.db2-cursor-type.php',
    1 => 'db2_cursor_type',
  ),
  11 => 
  array (
    0 => 'function.db2-escape-string.php',
    1 => 'db2_escape_string',
  ),
  12 => 
  array (
    0 => 'function.db2-exec.php',
    1 => 'db2_exec',
  ),
  13 => 
  array (
    0 => 'function.db2-execute.php',
    1 => 'db2_execute',
  ),
  14 => 
  array (
    0 => 'function.db2-fetch-array.php',
    1 => 'db2_fetch_array',
  ),
  15 => 
  array (
    0 => 'function.db2-fetch-assoc.php',
    1 => 'db2_fetch_assoc',
  ),
  16 => 
  array (
    0 => 'function.db2-fetch-both.php',
    1 => 'db2_fetch_both',
  ),
  17 => 
  array (
    0 => 'function.db2-fetch-object.php',
    1 => 'db2_fetch_object',
  ),
  18 => 
  array (
    0 => 'function.db2-fetch-row.php',
    1 => 'db2_fetch_row',
  ),
  19 => 
  array (
    0 => 'function.db2-field-display-size.php',
    1 => 'db2_field_display_size',
  ),
  20 => 
  array (
    0 => 'function.db2-field-name.php',
    1 => 'db2_field_name',
  ),
  21 => 
  array (
    0 => 'function.db2-field-num.php',
    1 => 'db2_field_num',
  ),
  22 => 
  array (
    0 => 'function.db2-field-precision.php',
    1 => 'db2_field_precision',
  ),
  23 => 
  array (
    0 => 'function.db2-field-scale.php',
    1 => 'db2_field_scale',
  ),
  24 => 
  array (
    0 => 'function.db2-field-type.php',
    1 => 'db2_field_type',
  ),
  25 => 
  array (
    0 => 'function.db2-field-width.php',
    1 => 'db2_field_width',
  ),
  26 => 
  array (
    0 => 'function.db2-foreign-keys.php',
    1 => 'db2_foreign_keys',
  ),
  27 => 
  array (
    0 => 'function.db2-free-result.php',
    1 => 'db2_free_result',
  ),
  28 => 
  array (
    0 => 'function.db2-free-stmt.php',
    1 => 'db2_free_stmt',
  ),
  29 => 
  array (
    0 => 'function.db2-get-option.php',
    1 => 'db2_get_option',
  ),
  30 => 
  array (
    0 => 'function.db2-last-insert-id.php',
    1 => 'db2_last_insert_id',
  ),
  31 => 
  array (
    0 => 'function.db2-lob-read.php',
    1 => 'db2_lob_read',
  ),
  32 => 
  array (
    0 => 'function.db2-next-result.php',
    1 => 'db2_next_result',
  ),
  33 => 
  array (
    0 => 'function.db2-num-fields.php',
    1 => 'db2_num_fields',
  ),
  34 => 
  array (
    0 => 'function.db2-num-rows.php',
    1 => 'db2_num_rows',
  ),
  35 => 
  array (
    0 => 'function.db2-pclose.php',
    1 => 'db2_pclose',
  ),
  36 => 
  array (
    0 => 'function.db2-pconnect.php',
    1 => 'db2_pconnect',
  ),
  37 => 
  array (
    0 => 'function.db2-prepare.php',
    1 => 'db2_prepare',
  ),
  38 => 
  array (
    0 => 'function.db2-primary-keys.php',
    1 => 'db2_primary_keys',
  ),
  39 => 
  array (
    0 => 'function.db2-procedure-columns.php',
    1 => 'db2_procedure_columns',
  ),
  40 => 
  array (
    0 => 'function.db2-procedures.php',
    1 => 'db2_procedures',
  ),
  41 => 
  array (
    0 => 'function.db2-result.php',
    1 => 'db2_result',
  ),
  42 => 
  array (
    0 => 'function.db2-rollback.php',
    1 => 'db2_rollback',
  ),
  43 => 
  array (
    0 => 'function.db2-server-info.php',
    1 => 'db2_server_info',
  ),
  44 => 
  array (
    0 => 'function.db2-set-option.php',
    1 => 'db2_set_option',
  ),
  45 => 
  array (
    0 => 'function.db2-special-columns.php',
    1 => 'db2_special_columns',
  ),
  46 => 
  array (
    0 => 'function.db2-statistics.php',
    1 => 'db2_statistics',
  ),
  47 => 
  array (
    0 => 'function.db2-stmt-error.php',
    1 => 'db2_stmt_error',
  ),
  48 => 
  array (
    0 => 'function.db2-stmt-errormsg.php',
    1 => 'db2_stmt_errormsg',
  ),
  49 => 
  array (
    0 => 'function.db2-table-privileges.php',
    1 => 'db2_table_privileges',
  ),
  50 => 
  array (
    0 => 'function.db2-tables.php',
    1 => 'db2_tables',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ibm-db2.php',
    1 => 'IBM DB2',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);