<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.curl-close.php',
    1 => 'curl_close',
  ),
  1 => 
  array (
    0 => 'function.curl-copy-handle.php',
    1 => 'curl_copy_handle',
  ),
  2 => 
  array (
    0 => 'function.curl-errno.php',
    1 => 'curl_errno',
  ),
  3 => 
  array (
    0 => 'function.curl-error.php',
    1 => 'curl_error',
  ),
  4 => 
  array (
    0 => 'function.curl-exec.php',
    1 => 'curl_exec',
  ),
  5 => 
  array (
    0 => 'function.curl-getinfo.php',
    1 => 'curl_getinfo',
  ),
  6 => 
  array (
    0 => 'function.curl-init.php',
    1 => 'curl_init',
  ),
  7 => 
  array (
    0 => 'function.curl-multi-add-handle.php',
    1 => 'curl_multi_add_handle',
  ),
  8 => 
  array (
    0 => 'function.curl-multi-close.php',
    1 => 'curl_multi_close',
  ),
  9 => 
  array (
    0 => 'function.curl-multi-exec.php',
    1 => 'curl_multi_exec',
  ),
  10 => 
  array (
    0 => 'function.curl-multi-getcontent.php',
    1 => 'curl_multi_getcontent',
  ),
  11 => 
  array (
    0 => 'function.curl-multi-info-read.php',
    1 => 'curl_multi_info_read',
  ),
  12 => 
  array (
    0 => 'function.curl-multi-init.php',
    1 => 'curl_multi_init',
  ),
  13 => 
  array (
    0 => 'function.curl-multi-remove-handle.php',
    1 => 'curl_multi_remove_handle',
  ),
  14 => 
  array (
    0 => 'function.curl-multi-select.php',
    1 => 'curl_multi_select',
  ),
  15 => 
  array (
    0 => 'function.curl-setopt-array.php',
    1 => 'curl_setopt_array',
  ),
  16 => 
  array (
    0 => 'function.curl-setopt.php',
    1 => 'curl_setopt',
  ),
  17 => 
  array (
    0 => 'function.curl-version.php',
    1 => 'curl_version',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.curl.php',
    1 => 'cURL',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);