<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.radius-acct-open.php',
    1 => 'radius_acct_open',
  ),
  1 => 
  array (
    0 => 'function.radius-add-server.php',
    1 => 'radius_add_server',
  ),
  2 => 
  array (
    0 => 'function.radius-auth-open.php',
    1 => 'radius_auth_open',
  ),
  3 => 
  array (
    0 => 'function.radius-close.php',
    1 => 'radius_close',
  ),
  4 => 
  array (
    0 => 'function.radius-config.php',
    1 => 'radius_config',
  ),
  5 => 
  array (
    0 => 'function.radius-create-request.php',
    1 => 'radius_create_request',
  ),
  6 => 
  array (
    0 => 'function.radius-cvt-addr.php',
    1 => 'radius_cvt_addr',
  ),
  7 => 
  array (
    0 => 'function.radius-cvt-int.php',
    1 => 'radius_cvt_int',
  ),
  8 => 
  array (
    0 => 'function.radius-cvt-string.php',
    1 => 'radius_cvt_string',
  ),
  9 => 
  array (
    0 => 'function.radius-demangle-mppe-key.php',
    1 => 'radius_demangle_mppe_key',
  ),
  10 => 
  array (
    0 => 'function.radius-demangle.php',
    1 => 'radius_demangle',
  ),
  11 => 
  array (
    0 => 'function.radius-get-attr.php',
    1 => 'radius_get_attr',
  ),
  12 => 
  array (
    0 => 'function.radius-get-vendor-attr.php',
    1 => 'radius_get_vendor_attr',
  ),
  13 => 
  array (
    0 => 'function.radius-put-addr.php',
    1 => 'radius_put_addr',
  ),
  14 => 
  array (
    0 => 'function.radius-put-attr.php',
    1 => 'radius_put_attr',
  ),
  15 => 
  array (
    0 => 'function.radius-put-int.php',
    1 => 'radius_put_int',
  ),
  16 => 
  array (
    0 => 'function.radius-put-string.php',
    1 => 'radius_put_string',
  ),
  17 => 
  array (
    0 => 'function.radius-put-vendor-addr.php',
    1 => 'radius_put_vendor_addr',
  ),
  18 => 
  array (
    0 => 'function.radius-put-vendor-attr.php',
    1 => 'radius_put_vendor_attr',
  ),
  19 => 
  array (
    0 => 'function.radius-put-vendor-int.php',
    1 => 'radius_put_vendor_int',
  ),
  20 => 
  array (
    0 => 'function.radius-put-vendor-string.php',
    1 => 'radius_put_vendor_string',
  ),
  21 => 
  array (
    0 => 'function.radius-request-authenticator.php',
    1 => 'radius_request_authenticator',
  ),
  22 => 
  array (
    0 => 'function.radius-send-request.php',
    1 => 'radius_send_request',
  ),
  23 => 
  array (
    0 => 'function.radius-server-secret.php',
    1 => 'radius_server_secret',
  ),
  24 => 
  array (
    0 => 'function.radius-strerror.php',
    1 => 'radius_strerror',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.radius.php',
    1 => 'Radius',
  ),
  1 => 
  array (
    0 => 'refs.remote.auth.php',
    1 => 'Authentication Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);