<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.cairo-create.php',
    1 => 'cairo_create',
  ),
  1 => 
  array (
    0 => 'function.cairo-font-face-get-type.php',
    1 => 'cairo_font_face_get_type',
  ),
  2 => 
  array (
    0 => 'function.cairo-font-face-status.php',
    1 => 'cairo_font_face_status',
  ),
  3 => 
  array (
    0 => 'function.cairo-font-options-create.php',
    1 => 'cairo_font_options_create',
  ),
  4 => 
  array (
    0 => 'function.cairo-font-options-equal.php',
    1 => 'cairo_font_options_equal',
  ),
  5 => 
  array (
    0 => 'function.cairo-font-options-get-antialias.php',
    1 => 'cairo_font_options_get_antialias',
  ),
  6 => 
  array (
    0 => 'function.cairo-font-options-get-hint-metrics.php',
    1 => 'cairo_font_options_get_hint_metrics',
  ),
  7 => 
  array (
    0 => 'function.cairo-font-options-get-hint-style.php',
    1 => 'cairo_font_options_get_hint_style',
  ),
  8 => 
  array (
    0 => 'function.cairo-font-options-get-subpixel-order.php',
    1 => 'cairo_font_options_get_subpixel_order',
  ),
  9 => 
  array (
    0 => 'function.cairo-font-options-hash.php',
    1 => 'cairo_font_options_hash',
  ),
  10 => 
  array (
    0 => 'function.cairo-font-options-merge.php',
    1 => 'cairo_font_options_merge',
  ),
  11 => 
  array (
    0 => 'function.cairo-font-options-set-antialias.php',
    1 => 'cairo_font_options_set_antialias',
  ),
  12 => 
  array (
    0 => 'function.cairo-font-options-set-hint-metrics.php',
    1 => 'cairo_font_options_set_hint_metrics',
  ),
  13 => 
  array (
    0 => 'function.cairo-font-options-set-hint-style.php',
    1 => 'cairo_font_options_set_hint_style',
  ),
  14 => 
  array (
    0 => 'function.cairo-font-options-set-subpixel-order.php',
    1 => 'cairo_font_options_set_subpixel_order',
  ),
  15 => 
  array (
    0 => 'function.cairo-font-options-status.php',
    1 => 'cairo_font_options_status',
  ),
  16 => 
  array (
    0 => 'function.cairo-format-stride-for-width.php',
    1 => 'cairo_format_stride_for_width',
  ),
  17 => 
  array (
    0 => 'function.cairo-image-surface-create-for-data.php',
    1 => 'cairo_image_surface_create_for_data',
  ),
  18 => 
  array (
    0 => 'function.cairo-image-surface-create-from-png.php',
    1 => 'cairo_image_surface_create_from_png',
  ),
  19 => 
  array (
    0 => 'function.cairo-image-surface-create.php',
    1 => 'cairo_image_surface_create',
  ),
  20 => 
  array (
    0 => 'function.cairo-image-surface-get-data.php',
    1 => 'cairo_image_surface_get_data',
  ),
  21 => 
  array (
    0 => 'function.cairo-image-surface-get-format.php',
    1 => 'cairo_image_surface_get_format',
  ),
  22 => 
  array (
    0 => 'function.cairo-image-surface-get-height.php',
    1 => 'cairo_image_surface_get_height',
  ),
  23 => 
  array (
    0 => 'function.cairo-image-surface-get-stride.php',
    1 => 'cairo_image_surface_get_stride',
  ),
  24 => 
  array (
    0 => 'function.cairo-image-surface-get-width.php',
    1 => 'cairo_image_surface_get_width',
  ),
  25 => 
  array (
    0 => 'function.cairo-matrix-create-scale.php',
    1 => 'cairo_matrix_create_scale',
  ),
  26 => 
  array (
    0 => 'function.cairo-matrix-create-translate.php',
    1 => 'cairo_matrix_create_translate',
  ),
  27 => 
  array (
    0 => 'function.cairo-matrix-invert.php',
    1 => 'cairo_matrix_invert',
  ),
  28 => 
  array (
    0 => 'function.cairo-matrix-multiply.php',
    1 => 'cairo_matrix_multiply',
  ),
  29 => 
  array (
    0 => 'function.cairo-matrix-rotate.php',
    1 => 'cairo_matrix_rotate',
  ),
  30 => 
  array (
    0 => 'function.cairo-matrix-transform-distance.php',
    1 => 'cairo_matrix_transform_distance',
  ),
  31 => 
  array (
    0 => 'function.cairo-matrix-transform-point.php',
    1 => 'cairo_matrix_transform_point',
  ),
  32 => 
  array (
    0 => 'function.cairo-matrix-translate.php',
    1 => 'cairo_matrix_translate',
  ),
  33 => 
  array (
    0 => 'function.cairo-pattern-add-color-stop-rgb.php',
    1 => 'cairo_pattern_add_color_stop_rgb',
  ),
  34 => 
  array (
    0 => 'function.cairo-pattern-add-color-stop-rgba.php',
    1 => 'cairo_pattern_add_color_stop_rgba',
  ),
  35 => 
  array (
    0 => 'function.cairo-pattern-create-for-surface.php',
    1 => 'cairo_pattern_create_for_surface',
  ),
  36 => 
  array (
    0 => 'function.cairo-pattern-create-linear.php',
    1 => 'cairo_pattern_create_linear',
  ),
  37 => 
  array (
    0 => 'function.cairo-pattern-create-radial.php',
    1 => 'cairo_pattern_create_radial',
  ),
  38 => 
  array (
    0 => 'function.cairo-pattern-create-rgb.php',
    1 => 'cairo_pattern_create_rgb',
  ),
  39 => 
  array (
    0 => 'function.cairo-pattern-create-rgba.php',
    1 => 'cairo_pattern_create_rgba',
  ),
  40 => 
  array (
    0 => 'function.cairo-pattern-get-color-stop-count.php',
    1 => 'cairo_pattern_get_color_stop_count',
  ),
  41 => 
  array (
    0 => 'function.cairo-pattern-get-color-stop-rgba.php',
    1 => 'cairo_pattern_get_color_stop_rgba',
  ),
  42 => 
  array (
    0 => 'function.cairo-pattern-get-extend.php',
    1 => 'cairo_pattern_get_extend',
  ),
  43 => 
  array (
    0 => 'function.cairo-pattern-get-filter.php',
    1 => 'cairo_pattern_get_filter',
  ),
  44 => 
  array (
    0 => 'function.cairo-pattern-get-linear-points.php',
    1 => 'cairo_pattern_get_linear_points',
  ),
  45 => 
  array (
    0 => 'function.cairo-pattern-get-matrix.php',
    1 => 'cairo_pattern_get_matrix',
  ),
  46 => 
  array (
    0 => 'function.cairo-pattern-get-radial-circles.php',
    1 => 'cairo_pattern_get_radial_circles',
  ),
  47 => 
  array (
    0 => 'function.cairo-pattern-get-rgba.php',
    1 => 'cairo_pattern_get_rgba',
  ),
  48 => 
  array (
    0 => 'function.cairo-pattern-get-surface.php',
    1 => 'cairo_pattern_get_surface',
  ),
  49 => 
  array (
    0 => 'function.cairo-pattern-get-type.php',
    1 => 'cairo_pattern_get_type',
  ),
  50 => 
  array (
    0 => 'function.cairo-pattern-set-extend.php',
    1 => 'cairo_pattern_set_extend',
  ),
  51 => 
  array (
    0 => 'function.cairo-pattern-set-filter.php',
    1 => 'cairo_pattern_set_filter',
  ),
  52 => 
  array (
    0 => 'function.cairo-pattern-set-matrix.php',
    1 => 'cairo_pattern_set_matrix',
  ),
  53 => 
  array (
    0 => 'function.cairo-pattern-status.php',
    1 => 'cairo_pattern_status',
  ),
  54 => 
  array (
    0 => 'function.cairo-pdf-surface-create.php',
    1 => 'cairo_pdf_surface_create',
  ),
  55 => 
  array (
    0 => 'function.cairo-pdf-surface-set-size.php',
    1 => 'cairo_pdf_surface_set_size',
  ),
  56 => 
  array (
    0 => 'function.cairo-ps-get-levels.php',
    1 => 'cairo_ps_get_levels',
  ),
  57 => 
  array (
    0 => 'function.cairo-ps-level-to-string.php',
    1 => 'cairo_ps_level_to_string',
  ),
  58 => 
  array (
    0 => 'function.cairo-ps-surface-create.php',
    1 => 'cairo_ps_surface_create',
  ),
  59 => 
  array (
    0 => 'function.cairo-ps-surface-dsc-begin-page-setup.php',
    1 => 'cairo_ps_surface_dsc_begin_page_setup',
  ),
  60 => 
  array (
    0 => 'function.cairo-ps-surface-dsc-begin-setup.php',
    1 => 'cairo_ps_surface_dsc_begin_setup',
  ),
  61 => 
  array (
    0 => 'function.cairo-ps-surface-dsc-comment.php',
    1 => 'cairo_ps_surface_dsc_comment',
  ),
  62 => 
  array (
    0 => 'function.cairo-ps-surface-get-eps.php',
    1 => 'cairo_ps_surface_get_eps',
  ),
  63 => 
  array (
    0 => 'function.cairo-ps-surface-restrict-to-level.php',
    1 => 'cairo_ps_surface_restrict_to_level',
  ),
  64 => 
  array (
    0 => 'function.cairo-ps-surface-set-eps.php',
    1 => 'cairo_ps_surface_set_eps',
  ),
  65 => 
  array (
    0 => 'function.cairo-ps-surface-set-size.php',
    1 => 'cairo_ps_surface_set_size',
  ),
  66 => 
  array (
    0 => 'function.cairo-scaled-font-create.php',
    1 => 'cairo_scaled_font_create',
  ),
  67 => 
  array (
    0 => 'function.cairo-scaled-font-extents.php',
    1 => 'cairo_scaled_font_extents',
  ),
  68 => 
  array (
    0 => 'function.cairo-scaled-font-get-ctm.php',
    1 => 'cairo_scaled_font_get_ctm',
  ),
  69 => 
  array (
    0 => 'function.cairo-scaled-font-get-font-face.php',
    1 => 'cairo_scaled_font_get_font_face',
  ),
  70 => 
  array (
    0 => 'function.cairo-scaled-font-get-font-matrix.php',
    1 => 'cairo_scaled_font_get_font_matrix',
  ),
  71 => 
  array (
    0 => 'function.cairo-scaled-font-get-font-options.php',
    1 => 'cairo_scaled_font_get_font_options',
  ),
  72 => 
  array (
    0 => 'function.cairo-scaled-font-get-scale-matrix.php',
    1 => 'cairo_scaled_font_get_scale_matrix',
  ),
  73 => 
  array (
    0 => 'function.cairo-scaled-font-get-type.php',
    1 => 'cairo_scaled_font_get_type',
  ),
  74 => 
  array (
    0 => 'function.cairo-scaled-font-glyph-extents.php',
    1 => 'cairo_scaled_font_glyph_extents',
  ),
  75 => 
  array (
    0 => 'function.cairo-scaled-font-status.php',
    1 => 'cairo_scaled_font_status',
  ),
  76 => 
  array (
    0 => 'function.cairo-scaled-font-text-extents.php',
    1 => 'cairo_scaled_font_text_extents',
  ),
  77 => 
  array (
    0 => 'function.cairo-surface-copy-page.php',
    1 => 'cairo_surface_copy_page',
  ),
  78 => 
  array (
    0 => 'function.cairo-surface-create-similar.php',
    1 => 'cairo_surface_create_similar',
  ),
  79 => 
  array (
    0 => 'function.cairo-surface-finish.php',
    1 => 'cairo_surface_finish',
  ),
  80 => 
  array (
    0 => 'function.cairo-surface-flush.php',
    1 => 'cairo_surface_flush',
  ),
  81 => 
  array (
    0 => 'function.cairo-surface-get-content.php',
    1 => 'cairo_surface_get_content',
  ),
  82 => 
  array (
    0 => 'function.cairo-surface-get-device-offset.php',
    1 => 'cairo_surface_get_device_offset',
  ),
  83 => 
  array (
    0 => 'function.cairo-surface-get-font-options.php',
    1 => 'cairo_surface_get_font_options',
  ),
  84 => 
  array (
    0 => 'function.cairo-surface-get-type.php',
    1 => 'cairo_surface_get_type',
  ),
  85 => 
  array (
    0 => 'function.cairo-surface-mark-dirty-rectangle.php',
    1 => 'cairo_surface_mark_dirty_rectangle',
  ),
  86 => 
  array (
    0 => 'function.cairo-surface-mark-dirty.php',
    1 => 'cairo_surface_mark_dirty',
  ),
  87 => 
  array (
    0 => 'function.cairo-surface-set-device-offset.php',
    1 => 'cairo_surface_set_device_offset',
  ),
  88 => 
  array (
    0 => 'function.cairo-surface-set-fallback-resolution.php',
    1 => 'cairo_surface_set_fallback_resolution',
  ),
  89 => 
  array (
    0 => 'function.cairo-surface-show-page.php',
    1 => 'cairo_surface_show_page',
  ),
  90 => 
  array (
    0 => 'function.cairo-surface-status.php',
    1 => 'cairo_surface_status',
  ),
  91 => 
  array (
    0 => 'function.cairo-surface-write-to-png.php',
    1 => 'cairo_surface_write_to_png',
  ),
  92 => 
  array (
    0 => 'function.cairo-svg-surface-create.php',
    1 => 'cairo_svg_surface_create',
  ),
  93 => 
  array (
    0 => 'function.cairo-svg-surface-restrict-to-version.php',
    1 => 'cairo_svg_surface_restrict_to_version',
  ),
  94 => 
  array (
    0 => 'function.cairo-svg-version-to-string.php',
    1 => 'cairo_svg_version_to_string',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.image.php',
    1 => 'Image Processing and Generation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);