<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.lzf-compress.php',
    1 => 'lzf_compress',
  ),
  1 => 
  array (
    0 => 'function.lzf-decompress.php',
    1 => 'lzf_decompress',
  ),
  2 => 
  array (
    0 => 'function.lzf-optimized-for.php',
    1 => 'lzf_optimized_for',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.lzf.php',
    1 => 'LZF',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);