<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ovrimos-close.php',
    1 => 'ovrimos_close',
  ),
  1 => 
  array (
    0 => 'function.ovrimos-commit.php',
    1 => 'ovrimos_commit',
  ),
  2 => 
  array (
    0 => 'function.ovrimos-connect.php',
    1 => 'ovrimos_connect',
  ),
  3 => 
  array (
    0 => 'function.ovrimos-cursor.php',
    1 => 'ovrimos_cursor',
  ),
  4 => 
  array (
    0 => 'function.ovrimos-exec.php',
    1 => 'ovrimos_exec',
  ),
  5 => 
  array (
    0 => 'function.ovrimos-execute.php',
    1 => 'ovrimos_execute',
  ),
  6 => 
  array (
    0 => 'function.ovrimos-fetch-into.php',
    1 => 'ovrimos_fetch_into',
  ),
  7 => 
  array (
    0 => 'function.ovrimos-fetch-row.php',
    1 => 'ovrimos_fetch_row',
  ),
  8 => 
  array (
    0 => 'function.ovrimos-field-len.php',
    1 => 'ovrimos_field_len',
  ),
  9 => 
  array (
    0 => 'function.ovrimos-field-name.php',
    1 => 'ovrimos_field_name',
  ),
  10 => 
  array (
    0 => 'function.ovrimos-field-num.php',
    1 => 'ovrimos_field_num',
  ),
  11 => 
  array (
    0 => 'function.ovrimos-field-type.php',
    1 => 'ovrimos_field_type',
  ),
  12 => 
  array (
    0 => 'function.ovrimos-free-result.php',
    1 => 'ovrimos_free_result',
  ),
  13 => 
  array (
    0 => 'function.ovrimos-longreadlen.php',
    1 => 'ovrimos_longreadlen',
  ),
  14 => 
  array (
    0 => 'function.ovrimos-num-fields.php',
    1 => 'ovrimos_num_fields',
  ),
  15 => 
  array (
    0 => 'function.ovrimos-num-rows.php',
    1 => 'ovrimos_num_rows',
  ),
  16 => 
  array (
    0 => 'function.ovrimos-prepare.php',
    1 => 'ovrimos_prepare',
  ),
  17 => 
  array (
    0 => 'function.ovrimos-result-all.php',
    1 => 'ovrimos_result_all',
  ),
  18 => 
  array (
    0 => 'function.ovrimos-result.php',
    1 => 'ovrimos_result',
  ),
  19 => 
  array (
    0 => 'function.ovrimos-rollback.php',
    1 => 'ovrimos_rollback',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ovrimos.php',
    1 => 'Ovrimos SQL',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);