<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.call-user-method-array.php',
    1 => 'call_user_method_array',
  ),
  1 => 
  array (
    0 => 'function.call-user-method.php',
    1 => 'call_user_method',
  ),
  2 => 
  array (
    0 => 'function.class-alias.php',
    1 => 'class_alias',
  ),
  3 => 
  array (
    0 => 'function.class-exists.php',
    1 => 'class_exists',
  ),
  4 => 
  array (
    0 => 'function.get-called-class.php',
    1 => 'get_called_class',
  ),
  5 => 
  array (
    0 => 'function.get-class-methods.php',
    1 => 'get_class_methods',
  ),
  6 => 
  array (
    0 => 'function.get-class-vars.php',
    1 => 'get_class_vars',
  ),
  7 => 
  array (
    0 => 'function.get-class.php',
    1 => 'get_class',
  ),
  8 => 
  array (
    0 => 'function.get-declared-classes.php',
    1 => 'get_declared_classes',
  ),
  9 => 
  array (
    0 => 'function.get-declared-interfaces.php',
    1 => 'get_declared_interfaces',
  ),
  10 => 
  array (
    0 => 'function.get-object-vars.php',
    1 => 'get_object_vars',
  ),
  11 => 
  array (
    0 => 'function.get-parent-class.php',
    1 => 'get_parent_class',
  ),
  12 => 
  array (
    0 => 'function.interface-exists.php',
    1 => 'interface_exists',
  ),
  13 => 
  array (
    0 => 'function.is-a.php',
    1 => 'is_a',
  ),
  14 => 
  array (
    0 => 'function.is-subclass-of.php',
    1 => 'is_subclass_of',
  ),
  15 => 
  array (
    0 => 'function.method-exists.php',
    1 => 'method_exists',
  ),
  16 => 
  array (
    0 => 'function.property-exists.php',
    1 => 'property_exists',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.classobj.php',
    1 => 'Classes/Objects',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);