<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.sdo-das-changesummary-beginlogging.php',
    1 => 'SDO_DAS_ChangeSummary::beginLogging',
  ),
  1 => 
  array (
    0 => 'function.sdo-das-changesummary-endlogging.php',
    1 => 'SDO_DAS_ChangeSummary::endLogging',
  ),
  2 => 
  array (
    0 => 'function.sdo-das-changesummary-getchangetype.php',
    1 => 'SDO_DAS_ChangeSummary::getChangeType',
  ),
  3 => 
  array (
    0 => 'function.sdo-das-changesummary-getchangeddataobjects.php',
    1 => 'SDO_DAS_ChangeSummary::getChangedDataObjects',
  ),
  4 => 
  array (
    0 => 'function.sdo-das-changesummary-getoldcontainer.php',
    1 => 'SDO_DAS_ChangeSummary::getOldContainer',
  ),
  5 => 
  array (
    0 => 'function.sdo-das-changesummary-getoldvalues.php',
    1 => 'SDO_DAS_ChangeSummary::getOldValues',
  ),
  6 => 
  array (
    0 => 'function.sdo-das-changesummary-islogging.php',
    1 => 'SDO_DAS_ChangeSummary::isLogging',
  ),
  7 => 
  array (
    0 => 'function.sdo-das-datafactory-addpropertytotype.php',
    1 => 'SDO_DAS_DataFactory::addPropertyToType',
  ),
  8 => 
  array (
    0 => 'function.sdo-das-datafactory-addtype.php',
    1 => 'SDO_DAS_DataFactory::addType',
  ),
  9 => 
  array (
    0 => 'function.sdo-das-datafactory-getdatafactory.php',
    1 => 'SDO_DAS_DataFactory::getDataFactory',
  ),
  10 => 
  array (
    0 => 'function.sdo-das-dataobject-getchangesummary.php',
    1 => 'SDO_DAS_DataObject::getChangeSummary',
  ),
  11 => 
  array (
    0 => 'function.sdo-das-setting-getlistindex.php',
    1 => 'SDO_DAS_Setting::getListIndex',
  ),
  12 => 
  array (
    0 => 'function.sdo-das-setting-getpropertyindex.php',
    1 => 'SDO_DAS_Setting::getPropertyIndex',
  ),
  13 => 
  array (
    0 => 'function.sdo-das-setting-getpropertyname.php',
    1 => 'SDO_DAS_Setting::getPropertyName',
  ),
  14 => 
  array (
    0 => 'function.sdo-das-setting-getvalue.php',
    1 => 'SDO_DAS_Setting::getValue',
  ),
  15 => 
  array (
    0 => 'function.sdo-das-setting-isset.php',
    1 => 'SDO_DAS_Setting::isSet',
  ),
  16 => 
  array (
    0 => 'function.sdo-datafactory-create.php',
    1 => 'SDO_DataFactory::create',
  ),
  17 => 
  array (
    0 => 'function.sdo-dataobject-clear.php',
    1 => 'SDO_DataObject::clear',
  ),
  18 => 
  array (
    0 => 'function.sdo-dataobject-createdataobject.php',
    1 => 'SDO_DataObject::createDataObject',
  ),
  19 => 
  array (
    0 => 'function.sdo-dataobject-getcontainer.php',
    1 => 'SDO_DataObject::getContainer',
  ),
  20 => 
  array (
    0 => 'function.sdo-dataobject-getsequence.php',
    1 => 'SDO_DataObject::getSequence',
  ),
  21 => 
  array (
    0 => 'function.sdo-dataobject-gettypename.php',
    1 => 'SDO_DataObject::getTypeName',
  ),
  22 => 
  array (
    0 => 'function.sdo-dataobject-gettypenamespaceuri.php',
    1 => 'SDO_DataObject::getTypeNamespaceURI',
  ),
  23 => 
  array (
    0 => 'function.sdo-exception-getcause.php',
    1 => 'SDO_Exception::getCause',
  ),
  24 => 
  array (
    0 => 'function.sdo-list-insert.php',
    1 => 'SDO_List::insert',
  ),
  25 => 
  array (
    0 => 'function.sdo-model-property-getcontainingtype.php',
    1 => 'SDO_Model_Property::getContainingType',
  ),
  26 => 
  array (
    0 => 'function.sdo-model-property-getdefault.php',
    1 => 'SDO_Model_Property::getDefault',
  ),
  27 => 
  array (
    0 => 'function.sdo-model-property-getname.php',
    1 => 'SDO_Model_Property::getName',
  ),
  28 => 
  array (
    0 => 'function.sdo-model-property-gettype.php',
    1 => 'SDO_Model_Property::getType',
  ),
  29 => 
  array (
    0 => 'function.sdo-model-property-iscontainment.php',
    1 => 'SDO_Model_Property::isContainment',
  ),
  30 => 
  array (
    0 => 'function.sdo-model-property-ismany.php',
    1 => 'SDO_Model_Property::isMany',
  ),
  31 => 
  array (
    0 => 'function.sdo-model-reflectiondataobject-construct.php',
    1 => 'SDO_Model_ReflectionDataObject::__construct',
  ),
  32 => 
  array (
    0 => 'function.sdo-model-reflectiondataobject-export.php',
    1 => 'SDO_Model_ReflectionDataObject::export',
  ),
  33 => 
  array (
    0 => 'function.sdo-model-reflectiondataobject-getcontainmentproperty.php',
    1 => 'SDO_Model_ReflectionDataObject::getContainmentProperty',
  ),
  34 => 
  array (
    0 => 'function.sdo-model-reflectiondataobject-getinstanceproperties.php',
    1 => 'SDO_Model_ReflectionDataObject::getInstanceProperties',
  ),
  35 => 
  array (
    0 => 'function.sdo-model-reflectiondataobject-gettype.php',
    1 => 'SDO_Model_ReflectionDataObject::getType',
  ),
  36 => 
  array (
    0 => 'function.sdo-model-type-getbasetype.php',
    1 => 'SDO_Model_Type::getBaseType',
  ),
  37 => 
  array (
    0 => 'function.sdo-model-type-getname.php',
    1 => 'SDO_Model_Type::getName',
  ),
  38 => 
  array (
    0 => 'function.sdo-model-type-getnamespaceuri.php',
    1 => 'SDO_Model_Type::getNamespaceURI',
  ),
  39 => 
  array (
    0 => 'function.sdo-model-type-getproperties.php',
    1 => 'SDO_Model_Type::getProperties',
  ),
  40 => 
  array (
    0 => 'function.sdo-model-type-getproperty.php',
    1 => 'SDO_Model_Type::getProperty',
  ),
  41 => 
  array (
    0 => 'function.sdo-model-type-isabstracttype.php',
    1 => 'SDO_Model_Type::isAbstractType',
  ),
  42 => 
  array (
    0 => 'function.sdo-model-type-isdatatype.php',
    1 => 'SDO_Model_Type::isDataType',
  ),
  43 => 
  array (
    0 => 'function.sdo-model-type-isinstance.php',
    1 => 'SDO_Model_Type::isInstance',
  ),
  44 => 
  array (
    0 => 'function.sdo-model-type-isopentype.php',
    1 => 'SDO_Model_Type::isOpenType',
  ),
  45 => 
  array (
    0 => 'function.sdo-model-type-issequencedtype.php',
    1 => 'SDO_Model_Type::isSequencedType',
  ),
  46 => 
  array (
    0 => 'function.sdo-sequence-getproperty.php',
    1 => 'SDO_Sequence::getProperty',
  ),
  47 => 
  array (
    0 => 'function.sdo-sequence-insert.php',
    1 => 'SDO_Sequence::insert',
  ),
  48 => 
  array (
    0 => 'function.sdo-sequence-move.php',
    1 => 'SDO_Sequence::move',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sdo.php',
    1 => 'SDO',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);