<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.filter-has-var.php',
    1 => 'filter_has_var',
  ),
  1 => 
  array (
    0 => 'function.filter-id.php',
    1 => 'filter_id',
  ),
  2 => 
  array (
    0 => 'function.filter-input-array.php',
    1 => 'filter_input_array',
  ),
  3 => 
  array (
    0 => 'function.filter-input.php',
    1 => 'filter_input',
  ),
  4 => 
  array (
    0 => 'function.filter-list.php',
    1 => 'filter_list',
  ),
  5 => 
  array (
    0 => 'function.filter-var-array.php',
    1 => 'filter_var_array',
  ),
  6 => 
  array (
    0 => 'function.filter-var.php',
    1 => 'filter_var',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.filter.php',
    1 => 'Filter',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);