<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.pdf-activate-item.php',
    1 => 'PDF_activate_item',
  ),
  1 => 
  array (
    0 => 'function.pdf-add-annotation.php',
    1 => 'PDF_add_annotation',
  ),
  2 => 
  array (
    0 => 'function.pdf-add-bookmark.php',
    1 => 'PDF_add_bookmark',
  ),
  3 => 
  array (
    0 => 'function.pdf-add-launchlink.php',
    1 => 'PDF_add_launchlink',
  ),
  4 => 
  array (
    0 => 'function.pdf-add-locallink.php',
    1 => 'PDF_add_locallink',
  ),
  5 => 
  array (
    0 => 'function.pdf-add-nameddest.php',
    1 => 'PDF_add_nameddest',
  ),
  6 => 
  array (
    0 => 'function.pdf-add-note.php',
    1 => 'PDF_add_note',
  ),
  7 => 
  array (
    0 => 'function.pdf-add-outline.php',
    1 => 'PDF_add_outline',
  ),
  8 => 
  array (
    0 => 'function.pdf-add-pdflink.php',
    1 => 'PDF_add_pdflink',
  ),
  9 => 
  array (
    0 => 'function.pdf-add-table-cell.php',
    1 => 'PDF_add_table_cell',
  ),
  10 => 
  array (
    0 => 'function.pdf-add-textflow.php',
    1 => 'PDF_add_textflow',
  ),
  11 => 
  array (
    0 => 'function.pdf-add-thumbnail.php',
    1 => 'PDF_add_thumbnail',
  ),
  12 => 
  array (
    0 => 'function.pdf-add-weblink.php',
    1 => 'PDF_add_weblink',
  ),
  13 => 
  array (
    0 => 'function.pdf-arc.php',
    1 => 'PDF_arc',
  ),
  14 => 
  array (
    0 => 'function.pdf-arcn.php',
    1 => 'PDF_arcn',
  ),
  15 => 
  array (
    0 => 'function.pdf-attach-file.php',
    1 => 'PDF_attach_file',
  ),
  16 => 
  array (
    0 => 'function.pdf-begin-document.php',
    1 => 'PDF_begin_document',
  ),
  17 => 
  array (
    0 => 'function.pdf-begin-font.php',
    1 => 'PDF_begin_font',
  ),
  18 => 
  array (
    0 => 'function.pdf-begin-glyph.php',
    1 => 'PDF_begin_glyph',
  ),
  19 => 
  array (
    0 => 'function.pdf-begin-item.php',
    1 => 'PDF_begin_item',
  ),
  20 => 
  array (
    0 => 'function.pdf-begin-layer.php',
    1 => 'PDF_begin_layer',
  ),
  21 => 
  array (
    0 => 'function.pdf-begin-page-ext.php',
    1 => 'PDF_begin_page_ext',
  ),
  22 => 
  array (
    0 => 'function.pdf-begin-page.php',
    1 => 'PDF_begin_page',
  ),
  23 => 
  array (
    0 => 'function.pdf-begin-pattern.php',
    1 => 'PDF_begin_pattern',
  ),
  24 => 
  array (
    0 => 'function.pdf-begin-template-ext.php',
    1 => 'PDF_begin_template_ext',
  ),
  25 => 
  array (
    0 => 'function.pdf-begin-template.php',
    1 => 'PDF_begin_template',
  ),
  26 => 
  array (
    0 => 'function.pdf-circle.php',
    1 => 'PDF_circle',
  ),
  27 => 
  array (
    0 => 'function.pdf-clip.php',
    1 => 'PDF_clip',
  ),
  28 => 
  array (
    0 => 'function.pdf-close-image.php',
    1 => 'PDF_close_image',
  ),
  29 => 
  array (
    0 => 'function.pdf-close-pdi-page.php',
    1 => 'PDF_close_pdi_page',
  ),
  30 => 
  array (
    0 => 'function.pdf-close-pdi.php',
    1 => 'PDF_close_pdi',
  ),
  31 => 
  array (
    0 => 'function.pdf-close.php',
    1 => 'PDF_close',
  ),
  32 => 
  array (
    0 => 'function.pdf-closepath-fill-stroke.php',
    1 => 'PDF_closepath_fill_stroke',
  ),
  33 => 
  array (
    0 => 'function.pdf-closepath-stroke.php',
    1 => 'PDF_closepath_stroke',
  ),
  34 => 
  array (
    0 => 'function.pdf-closepath.php',
    1 => 'PDF_closepath',
  ),
  35 => 
  array (
    0 => 'function.pdf-concat.php',
    1 => 'PDF_concat',
  ),
  36 => 
  array (
    0 => 'function.pdf-continue-text.php',
    1 => 'PDF_continue_text',
  ),
  37 => 
  array (
    0 => 'function.pdf-create-3dview.php',
    1 => 'PDF_create_3dview',
  ),
  38 => 
  array (
    0 => 'function.pdf-create-action.php',
    1 => 'PDF_create_action',
  ),
  39 => 
  array (
    0 => 'function.pdf-create-annotation.php',
    1 => 'PDF_create_annotation',
  ),
  40 => 
  array (
    0 => 'function.pdf-create-bookmark.php',
    1 => 'PDF_create_bookmark',
  ),
  41 => 
  array (
    0 => 'function.pdf-create-field.php',
    1 => 'PDF_create_field',
  ),
  42 => 
  array (
    0 => 'function.pdf-create-fieldgroup.php',
    1 => 'PDF_create_fieldgroup',
  ),
  43 => 
  array (
    0 => 'function.pdf-create-gstate.php',
    1 => 'PDF_create_gstate',
  ),
  44 => 
  array (
    0 => 'function.pdf-create-pvf.php',
    1 => 'PDF_create_pvf',
  ),
  45 => 
  array (
    0 => 'function.pdf-create-textflow.php',
    1 => 'PDF_create_textflow',
  ),
  46 => 
  array (
    0 => 'function.pdf-curveto.php',
    1 => 'PDF_curveto',
  ),
  47 => 
  array (
    0 => 'function.pdf-define-layer.php',
    1 => 'PDF_define_layer',
  ),
  48 => 
  array (
    0 => 'function.pdf-delete-pvf.php',
    1 => 'PDF_delete_pvf',
  ),
  49 => 
  array (
    0 => 'function.pdf-delete-table.php',
    1 => 'PDF_delete_table',
  ),
  50 => 
  array (
    0 => 'function.pdf-delete-textflow.php',
    1 => 'PDF_delete_textflow',
  ),
  51 => 
  array (
    0 => 'function.pdf-delete.php',
    1 => 'PDF_delete',
  ),
  52 => 
  array (
    0 => 'function.pdf-encoding-set-char.php',
    1 => 'PDF_encoding_set_char',
  ),
  53 => 
  array (
    0 => 'function.pdf-end-document.php',
    1 => 'PDF_end_document',
  ),
  54 => 
  array (
    0 => 'function.pdf-end-font.php',
    1 => 'PDF_end_font',
  ),
  55 => 
  array (
    0 => 'function.pdf-end-glyph.php',
    1 => 'PDF_end_glyph',
  ),
  56 => 
  array (
    0 => 'function.pdf-end-item.php',
    1 => 'PDF_end_item',
  ),
  57 => 
  array (
    0 => 'function.pdf-end-layer.php',
    1 => 'PDF_end_layer',
  ),
  58 => 
  array (
    0 => 'function.pdf-end-page-ext.php',
    1 => 'PDF_end_page_ext',
  ),
  59 => 
  array (
    0 => 'function.pdf-end-page.php',
    1 => 'PDF_end_page',
  ),
  60 => 
  array (
    0 => 'function.pdf-end-pattern.php',
    1 => 'PDF_end_pattern',
  ),
  61 => 
  array (
    0 => 'function.pdf-end-template.php',
    1 => 'PDF_end_template',
  ),
  62 => 
  array (
    0 => 'function.pdf-endpath.php',
    1 => 'PDF_endpath',
  ),
  63 => 
  array (
    0 => 'function.pdf-fill-imageblock.php',
    1 => 'PDF_fill_imageblock',
  ),
  64 => 
  array (
    0 => 'function.pdf-fill-pdfblock.php',
    1 => 'PDF_fill_pdfblock',
  ),
  65 => 
  array (
    0 => 'function.pdf-fill-stroke.php',
    1 => 'PDF_fill_stroke',
  ),
  66 => 
  array (
    0 => 'function.pdf-fill-textblock.php',
    1 => 'PDF_fill_textblock',
  ),
  67 => 
  array (
    0 => 'function.pdf-fill.php',
    1 => 'PDF_fill',
  ),
  68 => 
  array (
    0 => 'function.pdf-findfont.php',
    1 => 'PDF_findfont',
  ),
  69 => 
  array (
    0 => 'function.pdf-fit-image.php',
    1 => 'PDF_fit_image',
  ),
  70 => 
  array (
    0 => 'function.pdf-fit-pdi-page.php',
    1 => 'PDF_fit_pdi_page',
  ),
  71 => 
  array (
    0 => 'function.pdf-fit-table.php',
    1 => 'PDF_fit_table',
  ),
  72 => 
  array (
    0 => 'function.pdf-fit-textflow.php',
    1 => 'PDF_fit_textflow',
  ),
  73 => 
  array (
    0 => 'function.pdf-fit-textline.php',
    1 => 'PDF_fit_textline',
  ),
  74 => 
  array (
    0 => 'function.pdf-get-apiname.php',
    1 => 'PDF_get_apiname',
  ),
  75 => 
  array (
    0 => 'function.pdf-get-buffer.php',
    1 => 'PDF_get_buffer',
  ),
  76 => 
  array (
    0 => 'function.pdf-get-errmsg.php',
    1 => 'PDF_get_errmsg',
  ),
  77 => 
  array (
    0 => 'function.pdf-get-errnum.php',
    1 => 'PDF_get_errnum',
  ),
  78 => 
  array (
    0 => 'function.pdf-get-font.php',
    1 => 'PDF_get_font',
  ),
  79 => 
  array (
    0 => 'function.pdf-get-fontname.php',
    1 => 'PDF_get_fontname',
  ),
  80 => 
  array (
    0 => 'function.pdf-get-fontsize.php',
    1 => 'PDF_get_fontsize',
  ),
  81 => 
  array (
    0 => 'function.pdf-get-image-height.php',
    1 => 'PDF_get_image_height',
  ),
  82 => 
  array (
    0 => 'function.pdf-get-image-width.php',
    1 => 'PDF_get_image_width',
  ),
  83 => 
  array (
    0 => 'function.pdf-get-majorversion.php',
    1 => 'PDF_get_majorversion',
  ),
  84 => 
  array (
    0 => 'function.pdf-get-minorversion.php',
    1 => 'PDF_get_minorversion',
  ),
  85 => 
  array (
    0 => 'function.pdf-get-parameter.php',
    1 => 'PDF_get_parameter',
  ),
  86 => 
  array (
    0 => 'function.pdf-get-pdi-parameter.php',
    1 => 'PDF_get_pdi_parameter',
  ),
  87 => 
  array (
    0 => 'function.pdf-get-pdi-value.php',
    1 => 'PDF_get_pdi_value',
  ),
  88 => 
  array (
    0 => 'function.pdf-get-value.php',
    1 => 'PDF_get_value',
  ),
  89 => 
  array (
    0 => 'function.pdf-info-font.php',
    1 => 'PDF_info_font',
  ),
  90 => 
  array (
    0 => 'function.pdf-info-matchbox.php',
    1 => 'PDF_info_matchbox',
  ),
  91 => 
  array (
    0 => 'function.pdf-info-table.php',
    1 => 'PDF_info_table',
  ),
  92 => 
  array (
    0 => 'function.pdf-info-textflow.php',
    1 => 'PDF_info_textflow',
  ),
  93 => 
  array (
    0 => 'function.pdf-info-textline.php',
    1 => 'PDF_info_textline',
  ),
  94 => 
  array (
    0 => 'function.pdf-initgraphics.php',
    1 => 'PDF_initgraphics',
  ),
  95 => 
  array (
    0 => 'function.pdf-lineto.php',
    1 => 'PDF_lineto',
  ),
  96 => 
  array (
    0 => 'function.pdf-load-3ddata.php',
    1 => 'PDF_load_3ddata',
  ),
  97 => 
  array (
    0 => 'function.pdf-load-font.php',
    1 => 'PDF_load_font',
  ),
  98 => 
  array (
    0 => 'function.pdf-load-iccprofile.php',
    1 => 'PDF_load_iccprofile',
  ),
  99 => 
  array (
    0 => 'function.pdf-load-image.php',
    1 => 'PDF_load_image',
  ),
  100 => 
  array (
    0 => 'function.pdf-makespotcolor.php',
    1 => 'PDF_makespotcolor',
  ),
  101 => 
  array (
    0 => 'function.pdf-moveto.php',
    1 => 'PDF_moveto',
  ),
  102 => 
  array (
    0 => 'function.pdf-new.php',
    1 => 'PDF_new',
  ),
  103 => 
  array (
    0 => 'function.pdf-open-ccitt.php',
    1 => 'PDF_open_ccitt',
  ),
  104 => 
  array (
    0 => 'function.pdf-open-file.php',
    1 => 'PDF_open_file',
  ),
  105 => 
  array (
    0 => 'function.pdf-open-gif.php',
    1 => 'PDF_open_gif',
  ),
  106 => 
  array (
    0 => 'function.pdf-open-image-file.php',
    1 => 'PDF_open_image_file',
  ),
  107 => 
  array (
    0 => 'function.pdf-open-image.php',
    1 => 'PDF_open_image',
  ),
  108 => 
  array (
    0 => 'function.pdf-open-jpeg.php',
    1 => 'PDF_open_jpeg',
  ),
  109 => 
  array (
    0 => 'function.pdf-open-memory-image.php',
    1 => 'PDF_open_memory_image',
  ),
  110 => 
  array (
    0 => 'function.pdf-open-pdi-document.php',
    1 => 'PDF_open_pdi_document',
  ),
  111 => 
  array (
    0 => 'function.pdf-open-pdi-page.php',
    1 => 'PDF_open_pdi_page',
  ),
  112 => 
  array (
    0 => 'function.pdf-open-pdi.php',
    1 => 'PDF_open_pdi',
  ),
  113 => 
  array (
    0 => 'function.pdf-open-tiff.php',
    1 => 'PDF_open_tiff',
  ),
  114 => 
  array (
    0 => 'function.pdf-pcos-get-number.php',
    1 => 'PDF_pcos_get_number',
  ),
  115 => 
  array (
    0 => 'function.pdf-pcos-get-stream.php',
    1 => 'PDF_pcos_get_stream',
  ),
  116 => 
  array (
    0 => 'function.pdf-pcos-get-string.php',
    1 => 'PDF_pcos_get_string',
  ),
  117 => 
  array (
    0 => 'function.pdf-place-image.php',
    1 => 'PDF_place_image',
  ),
  118 => 
  array (
    0 => 'function.pdf-place-pdi-page.php',
    1 => 'PDF_place_pdi_page',
  ),
  119 => 
  array (
    0 => 'function.pdf-process-pdi.php',
    1 => 'PDF_process_pdi',
  ),
  120 => 
  array (
    0 => 'function.pdf-rect.php',
    1 => 'PDF_rect',
  ),
  121 => 
  array (
    0 => 'function.pdf-restore.php',
    1 => 'PDF_restore',
  ),
  122 => 
  array (
    0 => 'function.pdf-resume-page.php',
    1 => 'PDF_resume_page',
  ),
  123 => 
  array (
    0 => 'function.pdf-rotate.php',
    1 => 'PDF_rotate',
  ),
  124 => 
  array (
    0 => 'function.pdf-save.php',
    1 => 'PDF_save',
  ),
  125 => 
  array (
    0 => 'function.pdf-scale.php',
    1 => 'PDF_scale',
  ),
  126 => 
  array (
    0 => 'function.pdf-set-border-color.php',
    1 => 'PDF_set_border_color',
  ),
  127 => 
  array (
    0 => 'function.pdf-set-border-dash.php',
    1 => 'PDF_set_border_dash',
  ),
  128 => 
  array (
    0 => 'function.pdf-set-border-style.php',
    1 => 'PDF_set_border_style',
  ),
  129 => 
  array (
    0 => 'function.pdf-set-char-spacing.php',
    1 => 'PDF_set_char_spacing',
  ),
  130 => 
  array (
    0 => 'function.pdf-set-duration.php',
    1 => 'PDF_set_duration',
  ),
  131 => 
  array (
    0 => 'function.pdf-set-gstate.php',
    1 => 'PDF_set_gstate',
  ),
  132 => 
  array (
    0 => 'function.pdf-set-horiz-scaling.php',
    1 => 'PDF_set_horiz_scaling',
  ),
  133 => 
  array (
    0 => 'function.pdf-set-info-author.php',
    1 => 'PDF_set_info_author',
  ),
  134 => 
  array (
    0 => 'function.pdf-set-info-creator.php',
    1 => 'PDF_set_info_creator',
  ),
  135 => 
  array (
    0 => 'function.pdf-set-info-keywords.php',
    1 => 'PDF_set_info_keywords',
  ),
  136 => 
  array (
    0 => 'function.pdf-set-info-subject.php',
    1 => 'PDF_set_info_subject',
  ),
  137 => 
  array (
    0 => 'function.pdf-set-info-title.php',
    1 => 'PDF_set_info_title',
  ),
  138 => 
  array (
    0 => 'function.pdf-set-info.php',
    1 => 'PDF_set_info',
  ),
  139 => 
  array (
    0 => 'function.pdf-set-layer-dependency.php',
    1 => 'PDF_set_layer_dependency',
  ),
  140 => 
  array (
    0 => 'function.pdf-set-leading.php',
    1 => 'PDF_set_leading',
  ),
  141 => 
  array (
    0 => 'function.pdf-set-parameter.php',
    1 => 'PDF_set_parameter',
  ),
  142 => 
  array (
    0 => 'function.pdf-set-text-matrix.php',
    1 => 'PDF_set_text_matrix',
  ),
  143 => 
  array (
    0 => 'function.pdf-set-text-pos.php',
    1 => 'PDF_set_text_pos',
  ),
  144 => 
  array (
    0 => 'function.pdf-set-text-rendering.php',
    1 => 'PDF_set_text_rendering',
  ),
  145 => 
  array (
    0 => 'function.pdf-set-text-rise.php',
    1 => 'PDF_set_text_rise',
  ),
  146 => 
  array (
    0 => 'function.pdf-set-value.php',
    1 => 'PDF_set_value',
  ),
  147 => 
  array (
    0 => 'function.pdf-set-word-spacing.php',
    1 => 'PDF_set_word_spacing',
  ),
  148 => 
  array (
    0 => 'function.pdf-setcolor.php',
    1 => 'PDF_setcolor',
  ),
  149 => 
  array (
    0 => 'function.pdf-setdash.php',
    1 => 'PDF_setdash',
  ),
  150 => 
  array (
    0 => 'function.pdf-setdashpattern.php',
    1 => 'PDF_setdashpattern',
  ),
  151 => 
  array (
    0 => 'function.pdf-setflat.php',
    1 => 'PDF_setflat',
  ),
  152 => 
  array (
    0 => 'function.pdf-setfont.php',
    1 => 'PDF_setfont',
  ),
  153 => 
  array (
    0 => 'function.pdf-setgray-fill.php',
    1 => 'PDF_setgray_fill',
  ),
  154 => 
  array (
    0 => 'function.pdf-setgray-stroke.php',
    1 => 'PDF_setgray_stroke',
  ),
  155 => 
  array (
    0 => 'function.pdf-setgray.php',
    1 => 'PDF_setgray',
  ),
  156 => 
  array (
    0 => 'function.pdf-setlinecap.php',
    1 => 'PDF_setlinecap',
  ),
  157 => 
  array (
    0 => 'function.pdf-setlinejoin.php',
    1 => 'PDF_setlinejoin',
  ),
  158 => 
  array (
    0 => 'function.pdf-setlinewidth.php',
    1 => 'PDF_setlinewidth',
  ),
  159 => 
  array (
    0 => 'function.pdf-setmatrix.php',
    1 => 'PDF_setmatrix',
  ),
  160 => 
  array (
    0 => 'function.pdf-setmiterlimit.php',
    1 => 'PDF_setmiterlimit',
  ),
  161 => 
  array (
    0 => 'function.pdf-setpolydash.php',
    1 => 'PDF_setpolydash',
  ),
  162 => 
  array (
    0 => 'function.pdf-setrgbcolor-fill.php',
    1 => 'PDF_setrgbcolor_fill',
  ),
  163 => 
  array (
    0 => 'function.pdf-setrgbcolor-stroke.php',
    1 => 'PDF_setrgbcolor_stroke',
  ),
  164 => 
  array (
    0 => 'function.pdf-setrgbcolor.php',
    1 => 'PDF_setrgbcolor',
  ),
  165 => 
  array (
    0 => 'function.pdf-shading-pattern.php',
    1 => 'PDF_shading_pattern',
  ),
  166 => 
  array (
    0 => 'function.pdf-shading.php',
    1 => 'PDF_shading',
  ),
  167 => 
  array (
    0 => 'function.pdf-shfill.php',
    1 => 'PDF_shfill',
  ),
  168 => 
  array (
    0 => 'function.pdf-show-boxed.php',
    1 => 'PDF_show_boxed',
  ),
  169 => 
  array (
    0 => 'function.pdf-show-xy.php',
    1 => 'PDF_show_xy',
  ),
  170 => 
  array (
    0 => 'function.pdf-show.php',
    1 => 'PDF_show',
  ),
  171 => 
  array (
    0 => 'function.pdf-skew.php',
    1 => 'PDF_skew',
  ),
  172 => 
  array (
    0 => 'function.pdf-stringwidth.php',
    1 => 'PDF_stringwidth',
  ),
  173 => 
  array (
    0 => 'function.pdf-stroke.php',
    1 => 'PDF_stroke',
  ),
  174 => 
  array (
    0 => 'function.pdf-suspend-page.php',
    1 => 'PDF_suspend_page',
  ),
  175 => 
  array (
    0 => 'function.pdf-translate.php',
    1 => 'PDF_translate',
  ),
  176 => 
  array (
    0 => 'function.pdf-utf16-to-utf8.php',
    1 => 'PDF_utf16_to_utf8',
  ),
  177 => 
  array (
    0 => 'function.pdf-utf32-to-utf16.php',
    1 => 'PDF_utf32_to_utf16',
  ),
  178 => 
  array (
    0 => 'function.pdf-utf8-to-utf16.php',
    1 => 'PDF_utf8_to_utf16',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.pdf.php',
    1 => 'PDF',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);