<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.assert-options.php',
    1 => 'assert_options',
  ),
  1 => 
  array (
    0 => 'function.assert.php',
    1 => 'assert',
  ),
  2 => 
  array (
    0 => 'function.dl.php',
    1 => 'dl',
  ),
  3 => 
  array (
    0 => 'function.extension-loaded.php',
    1 => 'extension_loaded',
  ),
  4 => 
  array (
    0 => 'function.gc-collect-cycles.php',
    1 => 'gc_collect_cycles',
  ),
  5 => 
  array (
    0 => 'function.gc-disable.php',
    1 => 'gc_disable',
  ),
  6 => 
  array (
    0 => 'function.gc-enable.php',
    1 => 'gc_enable',
  ),
  7 => 
  array (
    0 => 'function.gc-enabled.php',
    1 => 'gc_enabled',
  ),
  8 => 
  array (
    0 => 'function.get-cfg-var.php',
    1 => 'get_cfg_var',
  ),
  9 => 
  array (
    0 => 'function.get-current-user.php',
    1 => 'get_current_user',
  ),
  10 => 
  array (
    0 => 'function.get-defined-constants.php',
    1 => 'get_defined_constants',
  ),
  11 => 
  array (
    0 => 'function.get-extension-funcs.php',
    1 => 'get_extension_funcs',
  ),
  12 => 
  array (
    0 => 'function.get-include-path.php',
    1 => 'get_include_path',
  ),
  13 => 
  array (
    0 => 'function.get-included-files.php',
    1 => 'get_included_files',
  ),
  14 => 
  array (
    0 => 'function.get-loaded-extensions.php',
    1 => 'get_loaded_extensions',
  ),
  15 => 
  array (
    0 => 'function.get-magic-quotes-gpc.php',
    1 => 'get_magic_quotes_gpc',
  ),
  16 => 
  array (
    0 => 'function.get-magic-quotes-runtime.php',
    1 => 'get_magic_quotes_runtime',
  ),
  17 => 
  array (
    0 => 'function.get-required-files.php',
    1 => 'get_required_files',
  ),
  18 => 
  array (
    0 => 'function.getenv.php',
    1 => 'getenv',
  ),
  19 => 
  array (
    0 => 'function.getlastmod.php',
    1 => 'getlastmod',
  ),
  20 => 
  array (
    0 => 'function.getmygid.php',
    1 => 'getmygid',
  ),
  21 => 
  array (
    0 => 'function.getmyinode.php',
    1 => 'getmyinode',
  ),
  22 => 
  array (
    0 => 'function.getmypid.php',
    1 => 'getmypid',
  ),
  23 => 
  array (
    0 => 'function.getmyuid.php',
    1 => 'getmyuid',
  ),
  24 => 
  array (
    0 => 'function.getopt.php',
    1 => 'getopt',
  ),
  25 => 
  array (
    0 => 'function.getrusage.php',
    1 => 'getrusage',
  ),
  26 => 
  array (
    0 => 'function.ini-alter.php',
    1 => 'ini_alter',
  ),
  27 => 
  array (
    0 => 'function.ini-get-all.php',
    1 => 'ini_get_all',
  ),
  28 => 
  array (
    0 => 'function.ini-get.php',
    1 => 'ini_get',
  ),
  29 => 
  array (
    0 => 'function.ini-restore.php',
    1 => 'ini_restore',
  ),
  30 => 
  array (
    0 => 'function.ini-set.php',
    1 => 'ini_set',
  ),
  31 => 
  array (
    0 => 'function.magic-quotes-runtime.php',
    1 => 'magic_quotes_runtime',
  ),
  32 => 
  array (
    0 => 'function.main.php',
    1 => 'main',
  ),
  33 => 
  array (
    0 => 'function.memory-get-peak-usage.php',
    1 => 'memory_get_peak_usage',
  ),
  34 => 
  array (
    0 => 'function.memory-get-usage.php',
    1 => 'memory_get_usage',
  ),
  35 => 
  array (
    0 => 'function.php-ini-loaded-file.php',
    1 => 'php_ini_loaded_file',
  ),
  36 => 
  array (
    0 => 'function.php-ini-scanned-files.php',
    1 => 'php_ini_scanned_files',
  ),
  37 => 
  array (
    0 => 'function.php-logo-guid.php',
    1 => 'php_logo_guid',
  ),
  38 => 
  array (
    0 => 'function.php-sapi-name.php',
    1 => 'php_sapi_name',
  ),
  39 => 
  array (
    0 => 'function.php-uname.php',
    1 => 'php_uname',
  ),
  40 => 
  array (
    0 => 'function.phpcredits.php',
    1 => 'phpcredits',
  ),
  41 => 
  array (
    0 => 'function.phpinfo.php',
    1 => 'phpinfo',
  ),
  42 => 
  array (
    0 => 'function.phpversion.php',
    1 => 'phpversion',
  ),
  43 => 
  array (
    0 => 'function.putenv.php',
    1 => 'putenv',
  ),
  44 => 
  array (
    0 => 'function.restore-include-path.php',
    1 => 'restore_include_path',
  ),
  45 => 
  array (
    0 => 'function.set-include-path.php',
    1 => 'set_include_path',
  ),
  46 => 
  array (
    0 => 'function.set-magic-quotes-runtime.php',
    1 => 'set_magic_quotes_runtime',
  ),
  47 => 
  array (
    0 => 'function.set-time-limit.php',
    1 => 'set_time_limit',
  ),
  48 => 
  array (
    0 => 'function.sys-get-temp-dir.php',
    1 => 'sys_get_temp_dir',
  ),
  49 => 
  array (
    0 => 'function.version-compare.php',
    1 => 'version_compare',
  ),
  50 => 
  array (
    0 => 'function.zend-logo-guid.php',
    1 => 'zend_logo_guid',
  ),
  51 => 
  array (
    0 => 'function.zend-thread-id.php',
    1 => 'zend_thread_id',
  ),
  52 => 
  array (
    0 => 'function.zend-version.php',
    1 => 'zend_version',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.info.php',
    1 => 'PHP Options/Info',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);