<?php
$TOC = array (
  0 => 
  array (
    0 => 'ref.pdo-pgsql.connection.php',
    1 => 'PDO_PGSQL DSN',
  ),
  1 => 
  array (
    0 => 'function.pdo-pgsqllobcreate.php',
    1 => 'PDO::pgsqlLOBCreate',
  ),
  2 => 
  array (
    0 => 'function.pdo-pgsqllobopen.php',
    1 => 'PDO::pgsqlLOBOpen',
  ),
  3 => 
  array (
    0 => 'function.pdo-pgsqllobunlink.php',
    1 => 'PDO::pgsqlLOBUnlink',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'pdo.drivers.php',
    1 => 'PDO Drivers',
  ),
  1 => 
  array (
    0 => 'book.pdo.php',
    1 => 'PDO',
  ),
  2 => 
  array (
    0 => 'refs.database.abstract.php',
    1 => 'Abstraction Layers',
  ),
  3 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  4 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  5 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);