<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.msql-affected-rows.php',
    1 => 'msql_affected_rows',
  ),
  1 => 
  array (
    0 => 'function.msql-close.php',
    1 => 'msql_close',
  ),
  2 => 
  array (
    0 => 'function.msql-connect.php',
    1 => 'msql_connect',
  ),
  3 => 
  array (
    0 => 'function.msql-create-db.php',
    1 => 'msql_create_db',
  ),
  4 => 
  array (
    0 => 'function.msql-createdb.php',
    1 => 'msql_createdb',
  ),
  5 => 
  array (
    0 => 'function.msql-data-seek.php',
    1 => 'msql_data_seek',
  ),
  6 => 
  array (
    0 => 'function.msql-db-query.php',
    1 => 'msql_db_query',
  ),
  7 => 
  array (
    0 => 'function.msql-dbname.php',
    1 => 'msql_dbname',
  ),
  8 => 
  array (
    0 => 'function.msql-drop-db.php',
    1 => 'msql_drop_db',
  ),
  9 => 
  array (
    0 => 'function.msql-error.php',
    1 => 'msql_error',
  ),
  10 => 
  array (
    0 => 'function.msql-fetch-array.php',
    1 => 'msql_fetch_array',
  ),
  11 => 
  array (
    0 => 'function.msql-fetch-field.php',
    1 => 'msql_fetch_field',
  ),
  12 => 
  array (
    0 => 'function.msql-fetch-object.php',
    1 => 'msql_fetch_object',
  ),
  13 => 
  array (
    0 => 'function.msql-fetch-row.php',
    1 => 'msql_fetch_row',
  ),
  14 => 
  array (
    0 => 'function.msql-field-flags.php',
    1 => 'msql_field_flags',
  ),
  15 => 
  array (
    0 => 'function.msql-field-len.php',
    1 => 'msql_field_len',
  ),
  16 => 
  array (
    0 => 'function.msql-field-name.php',
    1 => 'msql_field_name',
  ),
  17 => 
  array (
    0 => 'function.msql-field-seek.php',
    1 => 'msql_field_seek',
  ),
  18 => 
  array (
    0 => 'function.msql-field-table.php',
    1 => 'msql_field_table',
  ),
  19 => 
  array (
    0 => 'function.msql-field-type.php',
    1 => 'msql_field_type',
  ),
  20 => 
  array (
    0 => 'function.msql-fieldflags.php',
    1 => 'msql_fieldflags',
  ),
  21 => 
  array (
    0 => 'function.msql-fieldlen.php',
    1 => 'msql_fieldlen',
  ),
  22 => 
  array (
    0 => 'function.msql-fieldname.php',
    1 => 'msql_fieldname',
  ),
  23 => 
  array (
    0 => 'function.msql-fieldtable.php',
    1 => 'msql_fieldtable',
  ),
  24 => 
  array (
    0 => 'function.msql-fieldtype.php',
    1 => 'msql_fieldtype',
  ),
  25 => 
  array (
    0 => 'function.msql-free-result.php',
    1 => 'msql_free_result',
  ),
  26 => 
  array (
    0 => 'function.msql-list-dbs.php',
    1 => 'msql_list_dbs',
  ),
  27 => 
  array (
    0 => 'function.msql-list-fields.php',
    1 => 'msql_list_fields',
  ),
  28 => 
  array (
    0 => 'function.msql-list-tables.php',
    1 => 'msql_list_tables',
  ),
  29 => 
  array (
    0 => 'function.msql-num-fields.php',
    1 => 'msql_num_fields',
  ),
  30 => 
  array (
    0 => 'function.msql-num-rows.php',
    1 => 'msql_num_rows',
  ),
  31 => 
  array (
    0 => 'function.msql-numfields.php',
    1 => 'msql_numfields',
  ),
  32 => 
  array (
    0 => 'function.msql-numrows.php',
    1 => 'msql_numrows',
  ),
  33 => 
  array (
    0 => 'function.msql-pconnect.php',
    1 => 'msql_pconnect',
  ),
  34 => 
  array (
    0 => 'function.msql-query.php',
    1 => 'msql_query',
  ),
  35 => 
  array (
    0 => 'function.msql-regcase.php',
    1 => 'msql_regcase',
  ),
  36 => 
  array (
    0 => 'function.msql-result.php',
    1 => 'msql_result',
  ),
  37 => 
  array (
    0 => 'function.msql-select-db.php',
    1 => 'msql_select_db',
  ),
  38 => 
  array (
    0 => 'function.msql-tablename.php',
    1 => 'msql_tablename',
  ),
  39 => 
  array (
    0 => 'function.msql.php',
    1 => 'msql',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.msql.php',
    1 => 'mSQL',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);