<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ob-tidyhandler.php',
    1 => 'ob_tidyhandler',
  ),
  1 => 
  array (
    0 => 'function.tidy-access-count.php',
    1 => 'tidy_access_count',
  ),
  2 => 
  array (
    0 => 'function.tidy-config-count.php',
    1 => 'tidy_config_count',
  ),
  3 => 
  array (
    0 => 'function.tidy-error-count.php',
    1 => 'tidy_error_count',
  ),
  4 => 
  array (
    0 => 'function.tidy-get-error-buffer.php',
    1 => 'tidy_get_error_buffer',
  ),
  5 => 
  array (
    0 => 'function.tidy-get-output.php',
    1 => 'tidy_get_output',
  ),
  6 => 
  array (
    0 => 'function.tidy-load-config.php',
    1 => 'tidy_load_config',
  ),
  7 => 
  array (
    0 => 'function.tidy-reset-config.php',
    1 => 'tidy_reset_config',
  ),
  8 => 
  array (
    0 => 'function.tidy-save-config.php',
    1 => 'tidy_save_config',
  ),
  9 => 
  array (
    0 => 'function.tidy-set-encoding.php',
    1 => 'tidy_set_encoding',
  ),
  10 => 
  array (
    0 => 'function.tidy-setopt.php',
    1 => 'tidy_setopt',
  ),
  11 => 
  array (
    0 => 'function.tidy-warning-count.php',
    1 => 'tidy_warning_count',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.tidy.php',
    1 => 'Tidy',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);