<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.expect-expectl.php',
    1 => 'expect_expectl',
  ),
  1 => 
  array (
    0 => 'function.expect-popen.php',
    1 => 'expect_popen',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.expect.php',
    1 => 'Expect',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);