<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.inclued-get-data.php',
    1 => 'inclued_get_data',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.inclued.php',
    1 => 'inclued',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);