<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.vpopmail-add-alias-domain-ex.php',
    1 => 'vpopmail_add_alias_domain_ex',
  ),
  1 => 
  array (
    0 => 'function.vpopmail-add-alias-domain.php',
    1 => 'vpopmail_add_alias_domain',
  ),
  2 => 
  array (
    0 => 'function.vpopmail-add-domain-ex.php',
    1 => 'vpopmail_add_domain_ex',
  ),
  3 => 
  array (
    0 => 'function.vpopmail-add-domain.php',
    1 => 'vpopmail_add_domain',
  ),
  4 => 
  array (
    0 => 'function.vpopmail-add-user.php',
    1 => 'vpopmail_add_user',
  ),
  5 => 
  array (
    0 => 'function.vpopmail-alias-add.php',
    1 => 'vpopmail_alias_add',
  ),
  6 => 
  array (
    0 => 'function.vpopmail-alias-del-domain.php',
    1 => 'vpopmail_alias_del_domain',
  ),
  7 => 
  array (
    0 => 'function.vpopmail-alias-del.php',
    1 => 'vpopmail_alias_del',
  ),
  8 => 
  array (
    0 => 'function.vpopmail-alias-get-all.php',
    1 => 'vpopmail_alias_get_all',
  ),
  9 => 
  array (
    0 => 'function.vpopmail-alias-get.php',
    1 => 'vpopmail_alias_get',
  ),
  10 => 
  array (
    0 => 'function.vpopmail-auth-user.php',
    1 => 'vpopmail_auth_user',
  ),
  11 => 
  array (
    0 => 'function.vpopmail-del-domain-ex.php',
    1 => 'vpopmail_del_domain_ex',
  ),
  12 => 
  array (
    0 => 'function.vpopmail-del-domain.php',
    1 => 'vpopmail_del_domain',
  ),
  13 => 
  array (
    0 => 'function.vpopmail-del-user.php',
    1 => 'vpopmail_del_user',
  ),
  14 => 
  array (
    0 => 'function.vpopmail-error.php',
    1 => 'vpopmail_error',
  ),
  15 => 
  array (
    0 => 'function.vpopmail-passwd.php',
    1 => 'vpopmail_passwd',
  ),
  16 => 
  array (
    0 => 'function.vpopmail-set-user-quota.php',
    1 => 'vpopmail_set_user_quota',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.vpopmail.php',
    1 => 'vpopmail',
  ),
  1 => 
  array (
    0 => 'refs.remote.mail.php',
    1 => 'Mail Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);