<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ssh2-auth-hostbased-file.php',
    1 => 'ssh2_auth_hostbased_file',
  ),
  1 => 
  array (
    0 => 'function.ssh2-auth-none.php',
    1 => 'ssh2_auth_none',
  ),
  2 => 
  array (
    0 => 'function.ssh2-auth-password.php',
    1 => 'ssh2_auth_password',
  ),
  3 => 
  array (
    0 => 'function.ssh2-auth-pubkey-file.php',
    1 => 'ssh2_auth_pubkey_file',
  ),
  4 => 
  array (
    0 => 'function.ssh2-connect.php',
    1 => 'ssh2_connect',
  ),
  5 => 
  array (
    0 => 'function.ssh2-exec.php',
    1 => 'ssh2_exec',
  ),
  6 => 
  array (
    0 => 'function.ssh2-fetch-stream.php',
    1 => 'ssh2_fetch_stream',
  ),
  7 => 
  array (
    0 => 'function.ssh2-fingerprint.php',
    1 => 'ssh2_fingerprint',
  ),
  8 => 
  array (
    0 => 'function.ssh2-methods-negotiated.php',
    1 => 'ssh2_methods_negotiated',
  ),
  9 => 
  array (
    0 => 'function.ssh2-publickey-add.php',
    1 => 'ssh2_publickey_add',
  ),
  10 => 
  array (
    0 => 'function.ssh2-publickey-init.php',
    1 => 'ssh2_publickey_init',
  ),
  11 => 
  array (
    0 => 'function.ssh2-publickey-list.php',
    1 => 'ssh2_publickey_list',
  ),
  12 => 
  array (
    0 => 'function.ssh2-publickey-remove.php',
    1 => 'ssh2_publickey_remove',
  ),
  13 => 
  array (
    0 => 'function.ssh2-scp-recv.php',
    1 => 'ssh2_scp_recv',
  ),
  14 => 
  array (
    0 => 'function.ssh2-scp-send.php',
    1 => 'ssh2_scp_send',
  ),
  15 => 
  array (
    0 => 'function.ssh2-sftp-lstat.php',
    1 => 'ssh2_sftp_lstat',
  ),
  16 => 
  array (
    0 => 'function.ssh2-sftp-mkdir.php',
    1 => 'ssh2_sftp_mkdir',
  ),
  17 => 
  array (
    0 => 'function.ssh2-sftp-readlink.php',
    1 => 'ssh2_sftp_readlink',
  ),
  18 => 
  array (
    0 => 'function.ssh2-sftp-realpath.php',
    1 => 'ssh2_sftp_realpath',
  ),
  19 => 
  array (
    0 => 'function.ssh2-sftp-rename.php',
    1 => 'ssh2_sftp_rename',
  ),
  20 => 
  array (
    0 => 'function.ssh2-sftp-rmdir.php',
    1 => 'ssh2_sftp_rmdir',
  ),
  21 => 
  array (
    0 => 'function.ssh2-sftp-stat.php',
    1 => 'ssh2_sftp_stat',
  ),
  22 => 
  array (
    0 => 'function.ssh2-sftp-symlink.php',
    1 => 'ssh2_sftp_symlink',
  ),
  23 => 
  array (
    0 => 'function.ssh2-sftp-unlink.php',
    1 => 'ssh2_sftp_unlink',
  ),
  24 => 
  array (
    0 => 'function.ssh2-sftp.php',
    1 => 'ssh2_sftp',
  ),
  25 => 
  array (
    0 => 'function.ssh2-shell.php',
    1 => 'ssh2_shell',
  ),
  26 => 
  array (
    0 => 'function.ssh2-tunnel.php',
    1 => 'ssh2_tunnel',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ssh2.php',
    1 => 'SSH2',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);