<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.imap-8bit.php',
    1 => 'imap_8bit',
  ),
  1 => 
  array (
    0 => 'function.imap-alerts.php',
    1 => 'imap_alerts',
  ),
  2 => 
  array (
    0 => 'function.imap-append.php',
    1 => 'imap_append',
  ),
  3 => 
  array (
    0 => 'function.imap-base64.php',
    1 => 'imap_base64',
  ),
  4 => 
  array (
    0 => 'function.imap-binary.php',
    1 => 'imap_binary',
  ),
  5 => 
  array (
    0 => 'function.imap-body.php',
    1 => 'imap_body',
  ),
  6 => 
  array (
    0 => 'function.imap-bodystruct.php',
    1 => 'imap_bodystruct',
  ),
  7 => 
  array (
    0 => 'function.imap-check.php',
    1 => 'imap_check',
  ),
  8 => 
  array (
    0 => 'function.imap-clearflag-full.php',
    1 => 'imap_clearflag_full',
  ),
  9 => 
  array (
    0 => 'function.imap-close.php',
    1 => 'imap_close',
  ),
  10 => 
  array (
    0 => 'function.imap-createmailbox.php',
    1 => 'imap_createmailbox',
  ),
  11 => 
  array (
    0 => 'function.imap-delete.php',
    1 => 'imap_delete',
  ),
  12 => 
  array (
    0 => 'function.imap-deletemailbox.php',
    1 => 'imap_deletemailbox',
  ),
  13 => 
  array (
    0 => 'function.imap-errors.php',
    1 => 'imap_errors',
  ),
  14 => 
  array (
    0 => 'function.imap-expunge.php',
    1 => 'imap_expunge',
  ),
  15 => 
  array (
    0 => 'function.imap-fetch-overview.php',
    1 => 'imap_fetch_overview',
  ),
  16 => 
  array (
    0 => 'function.imap-fetchbody.php',
    1 => 'imap_fetchbody',
  ),
  17 => 
  array (
    0 => 'function.imap-fetchheader.php',
    1 => 'imap_fetchheader',
  ),
  18 => 
  array (
    0 => 'function.imap-fetchstructure.php',
    1 => 'imap_fetchstructure',
  ),
  19 => 
  array (
    0 => 'function.imap-gc.php',
    1 => 'imap_gc',
  ),
  20 => 
  array (
    0 => 'function.imap-get-quota.php',
    1 => 'imap_get_quota',
  ),
  21 => 
  array (
    0 => 'function.imap-get-quotaroot.php',
    1 => 'imap_get_quotaroot',
  ),
  22 => 
  array (
    0 => 'function.imap-getacl.php',
    1 => 'imap_getacl',
  ),
  23 => 
  array (
    0 => 'function.imap-getmailboxes.php',
    1 => 'imap_getmailboxes',
  ),
  24 => 
  array (
    0 => 'function.imap-getsubscribed.php',
    1 => 'imap_getsubscribed',
  ),
  25 => 
  array (
    0 => 'function.imap-header.php',
    1 => 'imap_header',
  ),
  26 => 
  array (
    0 => 'function.imap-headerinfo.php',
    1 => 'imap_headerinfo',
  ),
  27 => 
  array (
    0 => 'function.imap-headers.php',
    1 => 'imap_headers',
  ),
  28 => 
  array (
    0 => 'function.imap-last-error.php',
    1 => 'imap_last_error',
  ),
  29 => 
  array (
    0 => 'function.imap-list.php',
    1 => 'imap_list',
  ),
  30 => 
  array (
    0 => 'function.imap-listmailbox.php',
    1 => 'imap_listmailbox',
  ),
  31 => 
  array (
    0 => 'function.imap-listscan.php',
    1 => 'imap_listscan',
  ),
  32 => 
  array (
    0 => 'function.imap-listsubscribed.php',
    1 => 'imap_listsubscribed',
  ),
  33 => 
  array (
    0 => 'function.imap-lsub.php',
    1 => 'imap_lsub',
  ),
  34 => 
  array (
    0 => 'function.imap-mail-compose.php',
    1 => 'imap_mail_compose',
  ),
  35 => 
  array (
    0 => 'function.imap-mail-copy.php',
    1 => 'imap_mail_copy',
  ),
  36 => 
  array (
    0 => 'function.imap-mail-move.php',
    1 => 'imap_mail_move',
  ),
  37 => 
  array (
    0 => 'function.imap-mail.php',
    1 => 'imap_mail',
  ),
  38 => 
  array (
    0 => 'function.imap-mailboxmsginfo.php',
    1 => 'imap_mailboxmsginfo',
  ),
  39 => 
  array (
    0 => 'function.imap-mime-header-decode.php',
    1 => 'imap_mime_header_decode',
  ),
  40 => 
  array (
    0 => 'function.imap-msgno.php',
    1 => 'imap_msgno',
  ),
  41 => 
  array (
    0 => 'function.imap-num-msg.php',
    1 => 'imap_num_msg',
  ),
  42 => 
  array (
    0 => 'function.imap-num-recent.php',
    1 => 'imap_num_recent',
  ),
  43 => 
  array (
    0 => 'function.imap-open.php',
    1 => 'imap_open',
  ),
  44 => 
  array (
    0 => 'function.imap-ping.php',
    1 => 'imap_ping',
  ),
  45 => 
  array (
    0 => 'function.imap-qprint.php',
    1 => 'imap_qprint',
  ),
  46 => 
  array (
    0 => 'function.imap-renamemailbox.php',
    1 => 'imap_renamemailbox',
  ),
  47 => 
  array (
    0 => 'function.imap-reopen.php',
    1 => 'imap_reopen',
  ),
  48 => 
  array (
    0 => 'function.imap-rfc822-parse-adrlist.php',
    1 => 'imap_rfc822_parse_adrlist',
  ),
  49 => 
  array (
    0 => 'function.imap-rfc822-parse-headers.php',
    1 => 'imap_rfc822_parse_headers',
  ),
  50 => 
  array (
    0 => 'function.imap-rfc822-write-address.php',
    1 => 'imap_rfc822_write_address',
  ),
  51 => 
  array (
    0 => 'function.imap-savebody.php',
    1 => 'imap_savebody',
  ),
  52 => 
  array (
    0 => 'function.imap-scanmailbox.php',
    1 => 'imap_scanmailbox',
  ),
  53 => 
  array (
    0 => 'function.imap-search.php',
    1 => 'imap_search',
  ),
  54 => 
  array (
    0 => 'function.imap-set-quota.php',
    1 => 'imap_set_quota',
  ),
  55 => 
  array (
    0 => 'function.imap-setacl.php',
    1 => 'imap_setacl',
  ),
  56 => 
  array (
    0 => 'function.imap-setflag-full.php',
    1 => 'imap_setflag_full',
  ),
  57 => 
  array (
    0 => 'function.imap-sort.php',
    1 => 'imap_sort',
  ),
  58 => 
  array (
    0 => 'function.imap-status.php',
    1 => 'imap_status',
  ),
  59 => 
  array (
    0 => 'function.imap-subscribe.php',
    1 => 'imap_subscribe',
  ),
  60 => 
  array (
    0 => 'function.imap-thread.php',
    1 => 'imap_thread',
  ),
  61 => 
  array (
    0 => 'function.imap-timeout.php',
    1 => 'imap_timeout',
  ),
  62 => 
  array (
    0 => 'function.imap-uid.php',
    1 => 'imap_uid',
  ),
  63 => 
  array (
    0 => 'function.imap-undelete.php',
    1 => 'imap_undelete',
  ),
  64 => 
  array (
    0 => 'function.imap-unsubscribe.php',
    1 => 'imap_unsubscribe',
  ),
  65 => 
  array (
    0 => 'function.imap-utf7-decode.php',
    1 => 'imap_utf7_decode',
  ),
  66 => 
  array (
    0 => 'function.imap-utf7-encode.php',
    1 => 'imap_utf7_encode',
  ),
  67 => 
  array (
    0 => 'function.imap-utf8.php',
    1 => 'imap_utf8',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.imap.php',
    1 => 'IMAP',
  ),
  1 => 
  array (
    0 => 'refs.remote.mail.php',
    1 => 'Mail Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);