<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.sdo-das-xml-document-getrootdataobject.php',
    1 => 'SDO_DAS_XML_Document::getRootDataObject',
  ),
  1 => 
  array (
    0 => 'function.sdo-das-xml-document-getrootelementname.php',
    1 => 'SDO_DAS_XML_Document::getRootElementName',
  ),
  2 => 
  array (
    0 => 'function.sdo-das-xml-document-getrootelementuri.php',
    1 => 'SDO_DAS_XML_Document::getRootElementURI',
  ),
  3 => 
  array (
    0 => 'function.sdo-das-xml-document-setencoding.php',
    1 => 'SDO_DAS_XML_Document::setEncoding',
  ),
  4 => 
  array (
    0 => 'function.sdo-das-xml-document-setxmldeclaration.php',
    1 => 'SDO_DAS_XML_Document::setXMLDeclaration',
  ),
  5 => 
  array (
    0 => 'function.sdo-das-xml-document-setxmlversion.php',
    1 => 'SDO_DAS_XML_Document::setXMLVersion',
  ),
  6 => 
  array (
    0 => 'function.sdo-das-xml-addtypes.php',
    1 => 'SDO_DAS_XML::addTypes',
  ),
  7 => 
  array (
    0 => 'function.sdo-das-xml-create.php',
    1 => 'SDO_DAS_XML::create',
  ),
  8 => 
  array (
    0 => 'function.sdo-das-xml-createdataobject.php',
    1 => 'SDO_DAS_XML::createDataObject',
  ),
  9 => 
  array (
    0 => 'function.sdo-das-xml-createdocument.php',
    1 => 'SDO_DAS_XML::createDocument',
  ),
  10 => 
  array (
    0 => 'function.sdo-das-xml-loadfile.php',
    1 => 'SDO_DAS_XML::loadFile',
  ),
  11 => 
  array (
    0 => 'function.sdo-das-xml-loadstring.php',
    1 => 'SDO_DAS_XML::loadString',
  ),
  12 => 
  array (
    0 => 'function.sdo-das-xml-savefile.php',
    1 => 'SDO_DAS_XML::saveFile',
  ),
  13 => 
  array (
    0 => 'function.sdo-das-xml-savestring.php',
    1 => 'SDO_DAS_XML::saveString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sdo-das-xml.php',
    1 => 'SDO DAS XML',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);