<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.libxml-clear-errors.php',
    1 => 'libxml_clear_errors',
  ),
  1 => 
  array (
    0 => 'function.libxml-disable-entity-loader.php',
    1 => 'libxml_disable_entity_loader',
  ),
  2 => 
  array (
    0 => 'function.libxml-get-errors.php',
    1 => 'libxml_get_errors',
  ),
  3 => 
  array (
    0 => 'function.libxml-get-last-error.php',
    1 => 'libxml_get_last_error',
  ),
  4 => 
  array (
    0 => 'function.libxml-set-streams-context.php',
    1 => 'libxml_set_streams_context',
  ),
  5 => 
  array (
    0 => 'function.libxml-use-internal-errors.php',
    1 => 'libxml_use_internal_errors',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.libxml.php',
    1 => 'libxml',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);