<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.debug-backtrace.php',
    1 => 'debug_backtrace',
  ),
  1 => 
  array (
    0 => 'function.debug-print-backtrace.php',
    1 => 'debug_print_backtrace',
  ),
  2 => 
  array (
    0 => 'function.error-get-last.php',
    1 => 'error_get_last',
  ),
  3 => 
  array (
    0 => 'function.error-log.php',
    1 => 'error_log',
  ),
  4 => 
  array (
    0 => 'function.error-reporting.php',
    1 => 'error_reporting',
  ),
  5 => 
  array (
    0 => 'function.restore-error-handler.php',
    1 => 'restore_error_handler',
  ),
  6 => 
  array (
    0 => 'function.restore-exception-handler.php',
    1 => 'restore_exception_handler',
  ),
  7 => 
  array (
    0 => 'function.set-error-handler.php',
    1 => 'set_error_handler',
  ),
  8 => 
  array (
    0 => 'function.set-exception-handler.php',
    1 => 'set_exception_handler',
  ),
  9 => 
  array (
    0 => 'function.trigger-error.php',
    1 => 'trigger_error',
  ),
  10 => 
  array (
    0 => 'function.user-error.php',
    1 => 'user_error',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.errorfunc.php',
    1 => 'Error Handling',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);