<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.pcntl-alarm.php',
    1 => 'pcntl_alarm',
  ),
  1 => 
  array (
    0 => 'function.pcntl-exec.php',
    1 => 'pcntl_exec',
  ),
  2 => 
  array (
    0 => 'function.pcntl-fork.php',
    1 => 'pcntl_fork',
  ),
  3 => 
  array (
    0 => 'function.pcntl-getpriority.php',
    1 => 'pcntl_getpriority',
  ),
  4 => 
  array (
    0 => 'function.pcntl-setpriority.php',
    1 => 'pcntl_setpriority',
  ),
  5 => 
  array (
    0 => 'function.pcntl-signal-dispatch.php',
    1 => 'pcntl_signal_dispatch',
  ),
  6 => 
  array (
    0 => 'function.pcntl-signal.php',
    1 => 'pcntl_signal',
  ),
  7 => 
  array (
    0 => 'function.pcntl-sigprocmask.php',
    1 => 'pcntl_sigprocmask',
  ),
  8 => 
  array (
    0 => 'function.pcntl-sigtimedwait.php',
    1 => 'pcntl_sigtimedwait',
  ),
  9 => 
  array (
    0 => 'function.pcntl-sigwaitinfo.php',
    1 => 'pcntl_sigwaitinfo',
  ),
  10 => 
  array (
    0 => 'function.pcntl-wait.php',
    1 => 'pcntl_wait',
  ),
  11 => 
  array (
    0 => 'function.pcntl-waitpid.php',
    1 => 'pcntl_waitpid',
  ),
  12 => 
  array (
    0 => 'function.pcntl-wexitstatus.php',
    1 => 'pcntl_wexitstatus',
  ),
  13 => 
  array (
    0 => 'function.pcntl-wifexited.php',
    1 => 'pcntl_wifexited',
  ),
  14 => 
  array (
    0 => 'function.pcntl-wifsignaled.php',
    1 => 'pcntl_wifsignaled',
  ),
  15 => 
  array (
    0 => 'function.pcntl-wifstopped.php',
    1 => 'pcntl_wifstopped',
  ),
  16 => 
  array (
    0 => 'function.pcntl-wstopsig.php',
    1 => 'pcntl_wstopsig',
  ),
  17 => 
  array (
    0 => 'function.pcntl-wtermsig.php',
    1 => 'pcntl_wtermsig',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.pcntl.php',
    1 => 'PCNTL',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);