<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.connection-aborted.php',
    1 => 'connection_aborted',
  ),
  1 => 
  array (
    0 => 'function.connection-status.php',
    1 => 'connection_status',
  ),
  2 => 
  array (
    0 => 'function.connection-timeout.php',
    1 => 'connection_timeout',
  ),
  3 => 
  array (
    0 => 'function.constant.php',
    1 => 'constant',
  ),
  4 => 
  array (
    0 => 'function.define.php',
    1 => 'define',
  ),
  5 => 
  array (
    0 => 'function.defined.php',
    1 => 'defined',
  ),
  6 => 
  array (
    0 => 'function.die.php',
    1 => 'die',
  ),
  7 => 
  array (
    0 => 'function.eval.php',
    1 => 'eval',
  ),
  8 => 
  array (
    0 => 'function.exit.php',
    1 => 'exit',
  ),
  9 => 
  array (
    0 => 'function.get-browser.php',
    1 => 'get_browser',
  ),
  10 => 
  array (
    0 => 'function.halt-compiler.php',
    1 => '__halt_compiler',
  ),
  11 => 
  array (
    0 => 'function.highlight-file.php',
    1 => 'highlight_file',
  ),
  12 => 
  array (
    0 => 'function.highlight-string.php',
    1 => 'highlight_string',
  ),
  13 => 
  array (
    0 => 'function.ignore-user-abort.php',
    1 => 'ignore_user_abort',
  ),
  14 => 
  array (
    0 => 'function.pack.php',
    1 => 'pack',
  ),
  15 => 
  array (
    0 => 'function.php-check-syntax.php',
    1 => 'php_check_syntax',
  ),
  16 => 
  array (
    0 => 'function.php-strip-whitespace.php',
    1 => 'php_strip_whitespace',
  ),
  17 => 
  array (
    0 => 'function.show-source.php',
    1 => 'show_source',
  ),
  18 => 
  array (
    0 => 'function.sleep.php',
    1 => 'sleep',
  ),
  19 => 
  array (
    0 => 'function.sys-getloadavg.php',
    1 => 'sys_getloadavg',
  ),
  20 => 
  array (
    0 => 'function.time-nanosleep.php',
    1 => 'time_nanosleep',
  ),
  21 => 
  array (
    0 => 'function.time-sleep-until.php',
    1 => 'time_sleep_until',
  ),
  22 => 
  array (
    0 => 'function.uniqid.php',
    1 => 'uniqid',
  ),
  23 => 
  array (
    0 => 'function.unpack.php',
    1 => 'unpack',
  ),
  24 => 
  array (
    0 => 'function.usleep.php',
    1 => 'usleep',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.misc.php',
    1 => 'Misc.',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);