<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.nsapi-request-headers.php',
    1 => 'nsapi_request_headers',
  ),
  1 => 
  array (
    0 => 'function.nsapi-response-headers.php',
    1 => 'nsapi_response_headers',
  ),
  2 => 
  array (
    0 => 'function.nsapi-virtual.php',
    1 => 'nsapi_virtual',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.nsapi.php',
    1 => 'NSAPI',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.server.php',
    1 => 'Server Specific Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);