<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.sca-localproxy-createdataobject.php',
    1 => 'SCA_LocalProxy::createDataObject',
  ),
  1 => 
  array (
    0 => 'function.sca-soapproxy-createdataobject.php',
    1 => 'SCA_SoapProxy::createDataObject',
  ),
  2 => 
  array (
    0 => 'function.sca-createdataobject.php',
    1 => 'SCA::createDataObject',
  ),
  3 => 
  array (
    0 => 'function.sca-getservice.php',
    1 => 'SCA::getService',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sca.php',
    1 => 'SCA',
  ),
  1 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);