<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.iis-add-server.php',
    1 => 'iis_add_server',
  ),
  1 => 
  array (
    0 => 'function.iis-get-dir-security.php',
    1 => 'iis_get_dir_security',
  ),
  2 => 
  array (
    0 => 'function.iis-get-script-map.php',
    1 => 'iis_get_script_map',
  ),
  3 => 
  array (
    0 => 'function.iis-get-server-by-comment.php',
    1 => 'iis_get_server_by_comment',
  ),
  4 => 
  array (
    0 => 'function.iis-get-server-by-path.php',
    1 => 'iis_get_server_by_path',
  ),
  5 => 
  array (
    0 => 'function.iis-get-server-rights.php',
    1 => 'iis_get_server_rights',
  ),
  6 => 
  array (
    0 => 'function.iis-get-service-state.php',
    1 => 'iis_get_service_state',
  ),
  7 => 
  array (
    0 => 'function.iis-remove-server.php',
    1 => 'iis_remove_server',
  ),
  8 => 
  array (
    0 => 'function.iis-set-app-settings.php',
    1 => 'iis_set_app_settings',
  ),
  9 => 
  array (
    0 => 'function.iis-set-dir-security.php',
    1 => 'iis_set_dir_security',
  ),
  10 => 
  array (
    0 => 'function.iis-set-script-map.php',
    1 => 'iis_set_script_map',
  ),
  11 => 
  array (
    0 => 'function.iis-set-server-rights.php',
    1 => 'iis_set_server_rights',
  ),
  12 => 
  array (
    0 => 'function.iis-start-server.php',
    1 => 'iis_start_server',
  ),
  13 => 
  array (
    0 => 'function.iis-start-service.php',
    1 => 'iis_start_service',
  ),
  14 => 
  array (
    0 => 'function.iis-stop-server.php',
    1 => 'iis_stop_server',
  ),
  15 => 
  array (
    0 => 'function.iis-stop-service.php',
    1 => 'iis_stop_service',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.iisfunc.php',
    1 => 'IIS',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.server.php',
    1 => 'Server Specific Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);