<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.token-get-all.php',
    1 => 'token_get_all',
  ),
  1 => 
  array (
    0 => 'function.token-name.php',
    1 => 'token_name',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.tokenizer.php',
    1 => 'Tokenizer',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);