<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.sybase-affected-rows.php',
    1 => 'sybase_affected_rows',
  ),
  1 => 
  array (
    0 => 'function.sybase-close.php',
    1 => 'sybase_close',
  ),
  2 => 
  array (
    0 => 'function.sybase-connect.php',
    1 => 'sybase_connect',
  ),
  3 => 
  array (
    0 => 'function.sybase-data-seek.php',
    1 => 'sybase_data_seek',
  ),
  4 => 
  array (
    0 => 'function.sybase-deadlock-retry-count.php',
    1 => 'sybase_deadlock_retry_count',
  ),
  5 => 
  array (
    0 => 'function.sybase-fetch-array.php',
    1 => 'sybase_fetch_array',
  ),
  6 => 
  array (
    0 => 'function.sybase-fetch-assoc.php',
    1 => 'sybase_fetch_assoc',
  ),
  7 => 
  array (
    0 => 'function.sybase-fetch-field.php',
    1 => 'sybase_fetch_field',
  ),
  8 => 
  array (
    0 => 'function.sybase-fetch-object.php',
    1 => 'sybase_fetch_object',
  ),
  9 => 
  array (
    0 => 'function.sybase-fetch-row.php',
    1 => 'sybase_fetch_row',
  ),
  10 => 
  array (
    0 => 'function.sybase-field-seek.php',
    1 => 'sybase_field_seek',
  ),
  11 => 
  array (
    0 => 'function.sybase-free-result.php',
    1 => 'sybase_free_result',
  ),
  12 => 
  array (
    0 => 'function.sybase-get-last-message.php',
    1 => 'sybase_get_last_message',
  ),
  13 => 
  array (
    0 => 'function.sybase-min-client-severity.php',
    1 => 'sybase_min_client_severity',
  ),
  14 => 
  array (
    0 => 'function.sybase-min-error-severity.php',
    1 => 'sybase_min_error_severity',
  ),
  15 => 
  array (
    0 => 'function.sybase-min-message-severity.php',
    1 => 'sybase_min_message_severity',
  ),
  16 => 
  array (
    0 => 'function.sybase-min-server-severity.php',
    1 => 'sybase_min_server_severity',
  ),
  17 => 
  array (
    0 => 'function.sybase-num-fields.php',
    1 => 'sybase_num_fields',
  ),
  18 => 
  array (
    0 => 'function.sybase-num-rows.php',
    1 => 'sybase_num_rows',
  ),
  19 => 
  array (
    0 => 'function.sybase-pconnect.php',
    1 => 'sybase_pconnect',
  ),
  20 => 
  array (
    0 => 'function.sybase-query.php',
    1 => 'sybase_query',
  ),
  21 => 
  array (
    0 => 'function.sybase-result.php',
    1 => 'sybase_result',
  ),
  22 => 
  array (
    0 => 'function.sybase-select-db.php',
    1 => 'sybase_select_db',
  ),
  23 => 
  array (
    0 => 'function.sybase-set-message-handler.php',
    1 => 'sybase_set_message_handler',
  ),
  24 => 
  array (
    0 => 'function.sybase-unbuffered-query.php',
    1 => 'sybase_unbuffered_query',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sybase.php',
    1 => 'Sybase',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);