<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.wddx-add-vars.php',
    1 => 'wddx_add_vars',
  ),
  1 => 
  array (
    0 => 'function.wddx-deserialize.php',
    1 => 'wddx_deserialize',
  ),
  2 => 
  array (
    0 => 'function.wddx-packet-end.php',
    1 => 'wddx_packet_end',
  ),
  3 => 
  array (
    0 => 'function.wddx-packet-start.php',
    1 => 'wddx_packet_start',
  ),
  4 => 
  array (
    0 => 'function.wddx-serialize-value.php',
    1 => 'wddx_serialize_value',
  ),
  5 => 
  array (
    0 => 'function.wddx-serialize-vars.php',
    1 => 'wddx_serialize_vars',
  ),
  6 => 
  array (
    0 => 'function.wddx-unserialize.php',
    1 => 'wddx_unserialize',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.wddx.php',
    1 => 'WDDX',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);