<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.crack-check.php',
    1 => 'crack_check',
  ),
  1 => 
  array (
    0 => 'function.crack-closedict.php',
    1 => 'crack_closedict',
  ),
  2 => 
  array (
    0 => 'function.crack-getlastmessage.php',
    1 => 'crack_getlastmessage',
  ),
  3 => 
  array (
    0 => 'function.crack-opendict.php',
    1 => 'crack_opendict',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.crack.php',
    1 => 'Crack',
  ),
  1 => 
  array (
    0 => 'refs.crypto.php',
    1 => 'Cryptography Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);