<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.gzclose.php',
    1 => 'gzclose',
  ),
  1 => 
  array (
    0 => 'function.gzcompress.php',
    1 => 'gzcompress',
  ),
  2 => 
  array (
    0 => 'function.gzdecode.php',
    1 => 'gzdecode',
  ),
  3 => 
  array (
    0 => 'function.gzdeflate.php',
    1 => 'gzdeflate',
  ),
  4 => 
  array (
    0 => 'function.gzencode.php',
    1 => 'gzencode',
  ),
  5 => 
  array (
    0 => 'function.gzeof.php',
    1 => 'gzeof',
  ),
  6 => 
  array (
    0 => 'function.gzfile.php',
    1 => 'gzfile',
  ),
  7 => 
  array (
    0 => 'function.gzgetc.php',
    1 => 'gzgetc',
  ),
  8 => 
  array (
    0 => 'function.gzgets.php',
    1 => 'gzgets',
  ),
  9 => 
  array (
    0 => 'function.gzgetss.php',
    1 => 'gzgetss',
  ),
  10 => 
  array (
    0 => 'function.gzinflate.php',
    1 => 'gzinflate',
  ),
  11 => 
  array (
    0 => 'function.gzopen.php',
    1 => 'gzopen',
  ),
  12 => 
  array (
    0 => 'function.gzpassthru.php',
    1 => 'gzpassthru',
  ),
  13 => 
  array (
    0 => 'function.gzputs.php',
    1 => 'gzputs',
  ),
  14 => 
  array (
    0 => 'function.gzread.php',
    1 => 'gzread',
  ),
  15 => 
  array (
    0 => 'function.gzrewind.php',
    1 => 'gzrewind',
  ),
  16 => 
  array (
    0 => 'function.gzseek.php',
    1 => 'gzseek',
  ),
  17 => 
  array (
    0 => 'function.gztell.php',
    1 => 'gztell',
  ),
  18 => 
  array (
    0 => 'function.gzuncompress.php',
    1 => 'gzuncompress',
  ),
  19 => 
  array (
    0 => 'function.gzwrite.php',
    1 => 'gzwrite',
  ),
  20 => 
  array (
    0 => 'function.readgzfile.php',
    1 => 'readgzfile',
  ),
  21 => 
  array (
    0 => 'function.zlib-get-coding-type.php',
    1 => 'zlib_get_coding_type',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.zlib.php',
    1 => 'Zlib',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);