<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.call-user-func-array.php',
    1 => 'call_user_func_array',
  ),
  1 => 
  array (
    0 => 'function.call-user-func.php',
    1 => 'call_user_func',
  ),
  2 => 
  array (
    0 => 'function.create-function.php',
    1 => 'create_function',
  ),
  3 => 
  array (
    0 => 'function.forward-static-call-array.php',
    1 => 'forward_static_call_array',
  ),
  4 => 
  array (
    0 => 'function.forward-static-call.php',
    1 => 'forward_static_call',
  ),
  5 => 
  array (
    0 => 'function.func-get-arg.php',
    1 => 'func_get_arg',
  ),
  6 => 
  array (
    0 => 'function.func-get-args.php',
    1 => 'func_get_args',
  ),
  7 => 
  array (
    0 => 'function.func-num-args.php',
    1 => 'func_num_args',
  ),
  8 => 
  array (
    0 => 'function.function-exists.php',
    1 => 'function_exists',
  ),
  9 => 
  array (
    0 => 'function.get-defined-functions.php',
    1 => 'get_defined_functions',
  ),
  10 => 
  array (
    0 => 'function.register-shutdown-function.php',
    1 => 'register_shutdown_function',
  ),
  11 => 
  array (
    0 => 'function.register-tick-function.php',
    1 => 'register_tick_function',
  ),
  12 => 
  array (
    0 => 'function.unregister-tick-function.php',
    1 => 'unregister_tick_function',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.funchand.php',
    1 => 'Function Handling',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);