<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.gupnp-context-get-host-ip.php',
    1 => 'gupnp_context_get_host_ip',
  ),
  1 => 
  array (
    0 => 'function.gupnp-context-get-port.php',
    1 => 'gupnp_context_get_port',
  ),
  2 => 
  array (
    0 => 'function.gupnp-context-get-subscription-timeout.php',
    1 => 'gupnp_context_get_subscription_timeout',
  ),
  3 => 
  array (
    0 => 'function.gupnp-context-host-path.php',
    1 => 'gupnp_context_host_path',
  ),
  4 => 
  array (
    0 => 'function.gupnp-context-new.php',
    1 => 'gupnp_context_new',
  ),
  5 => 
  array (
    0 => 'function.gupnp-context-set-subscription-timeout.php',
    1 => 'gupnp_context_set_subscription_timeout',
  ),
  6 => 
  array (
    0 => 'function.gupnp-context-timeout-add.php',
    1 => 'gupnp_context_timeout_add',
  ),
  7 => 
  array (
    0 => 'function.gupnp-context-unhost-path.php',
    1 => 'gupnp_context_unhost_path',
  ),
  8 => 
  array (
    0 => 'function.gupnp-control-point-browse-start.php',
    1 => 'gupnp_control_point_browse_start',
  ),
  9 => 
  array (
    0 => 'function.gupnp-control-point-browse-stop.php',
    1 => 'gupnp_control_point_browse_stop',
  ),
  10 => 
  array (
    0 => 'function.gupnp-control-point-callback-set.php',
    1 => 'gupnp_control_point_callback_set',
  ),
  11 => 
  array (
    0 => 'function.gupnp-control-point-new.php',
    1 => 'gupnp_control_point_new',
  ),
  12 => 
  array (
    0 => 'function.gupnp-device-action-callback-set.php',
    1 => 'gupnp_device_action_callback_set',
  ),
  13 => 
  array (
    0 => 'function.gupnp-device-info-get-service.php',
    1 => 'gupnp_device_info_get_service',
  ),
  14 => 
  array (
    0 => 'function.gupnp-device-info-get.php',
    1 => 'gupnp_device_info_get',
  ),
  15 => 
  array (
    0 => 'function.gupnp-root-device-get-available.php',
    1 => 'gupnp_root_device_get_available',
  ),
  16 => 
  array (
    0 => 'function.gupnp-root-device-get-relative-location.php',
    1 => 'gupnp_root_device_get_relative_location',
  ),
  17 => 
  array (
    0 => 'function.gupnp-root-device-new.php',
    1 => 'gupnp_root_device_new',
  ),
  18 => 
  array (
    0 => 'function.gupnp-root-device-set-available.php',
    1 => 'gupnp_root_device_set_available',
  ),
  19 => 
  array (
    0 => 'function.gupnp-root-device-start.php',
    1 => 'gupnp_root_device_start',
  ),
  20 => 
  array (
    0 => 'function.gupnp-root-device-stop.php',
    1 => 'gupnp_root_device_stop',
  ),
  21 => 
  array (
    0 => 'function.gupnp-service-action-get.php',
    1 => 'gupnp_service_action_get',
  ),
  22 => 
  array (
    0 => 'function.gupnp-service-action-return-error.php',
    1 => 'gupnp_service_action_return_error',
  ),
  23 => 
  array (
    0 => 'function.gupnp-service-action-return.php',
    1 => 'gupnp_service_action_return',
  ),
  24 => 
  array (
    0 => 'function.gupnp-service-action-set.php',
    1 => 'gupnp_service_action_set',
  ),
  25 => 
  array (
    0 => 'function.gupnp-service-freeze-notify.php',
    1 => 'gupnp_service_freeze_notify',
  ),
  26 => 
  array (
    0 => 'function.gupnp-service-info-get-introspection.php',
    1 => 'gupnp_service_info_get_introspection',
  ),
  27 => 
  array (
    0 => 'function.gupnp-service-info-get.php',
    1 => 'gupnp_service_info_get',
  ),
  28 => 
  array (
    0 => 'function.gupnp-service-introspection-get-state-variable.php',
    1 => 'gupnp_service_introspection_get_state_variable',
  ),
  29 => 
  array (
    0 => 'function.gupnp-service-notify.php',
    1 => 'gupnp_service_notify',
  ),
  30 => 
  array (
    0 => 'function.gupnp-service-proxy-action-get.php',
    1 => 'gupnp_service_proxy_action_get',
  ),
  31 => 
  array (
    0 => 'function.gupnp-service-proxy-action-set.php',
    1 => 'gupnp_service_proxy_action_set',
  ),
  32 => 
  array (
    0 => 'function.gupnp-service-proxy-add-notify.php',
    1 => 'gupnp_service_proxy_add_notify',
  ),
  33 => 
  array (
    0 => 'function.gupnp-service-proxy-callback-set.php',
    1 => 'gupnp_service_proxy_callback_set',
  ),
  34 => 
  array (
    0 => 'function.gupnp-service-proxy-get-subscribed.php',
    1 => 'gupnp_service_proxy_get_subscribed',
  ),
  35 => 
  array (
    0 => 'function.gupnp-service-proxy-remove-notify.php',
    1 => 'gupnp_service_proxy_remove_notify',
  ),
  36 => 
  array (
    0 => 'gupnp_service_proxy_send_action.php',
    1 => 'gupnp_service_proxy_send_action',
  ),
  37 => 
  array (
    0 => 'function.gupnp-service-proxy-set-subscribed.php',
    1 => 'gupnp_service_proxy_set_subscribed',
  ),
  38 => 
  array (
    0 => 'function.gupnp-service-thaw-notify.php',
    1 => 'gupnp_service_thaw_notify',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gupnp.php',
    1 => 'Gupnp',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);