<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.bcompiler-load-exe.php',
    1 => 'bcompiler_load_exe',
  ),
  1 => 
  array (
    0 => 'function.bcompiler-load.php',
    1 => 'bcompiler_load',
  ),
  2 => 
  array (
    0 => 'function.bcompiler-parse-class.php',
    1 => 'bcompiler_parse_class',
  ),
  3 => 
  array (
    0 => 'function.bcompiler-read.php',
    1 => 'bcompiler_read',
  ),
  4 => 
  array (
    0 => 'function.bcompiler-write-class.php',
    1 => 'bcompiler_write_class',
  ),
  5 => 
  array (
    0 => 'function.bcompiler-write-constant.php',
    1 => 'bcompiler_write_constant',
  ),
  6 => 
  array (
    0 => 'function.bcompiler-write-exe-footer.php',
    1 => 'bcompiler_write_exe_footer',
  ),
  7 => 
  array (
    0 => 'function.bcompiler-write-file.php',
    1 => 'bcompiler_write_file',
  ),
  8 => 
  array (
    0 => 'function.bcompiler-write-footer.php',
    1 => 'bcompiler_write_footer',
  ),
  9 => 
  array (
    0 => 'function.bcompiler-write-function.php',
    1 => 'bcompiler_write_function',
  ),
  10 => 
  array (
    0 => 'function.bcompiler-write-functions-from-file.php',
    1 => 'bcompiler_write_functions_from_file',
  ),
  11 => 
  array (
    0 => 'function.bcompiler-write-header.php',
    1 => 'bcompiler_write_header',
  ),
  12 => 
  array (
    0 => 'function.bcompiler-write-included-filename.php',
    1 => 'bcompiler_write_included_filename',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.bcompiler.php',
    1 => 'bcompiler',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);