<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.classkit-import.php',
    1 => 'classkit_import',
  ),
  1 => 
  array (
    0 => 'function.classkit-method-add.php',
    1 => 'classkit_method_add',
  ),
  2 => 
  array (
    0 => 'function.classkit-method-copy.php',
    1 => 'classkit_method_copy',
  ),
  3 => 
  array (
    0 => 'function.classkit-method-redefine.php',
    1 => 'classkit_method_redefine',
  ),
  4 => 
  array (
    0 => 'function.classkit-method-remove.php',
    1 => 'classkit_method_remove',
  ),
  5 => 
  array (
    0 => 'function.classkit-method-rename.php',
    1 => 'classkit_method_rename',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.classkit.php',
    1 => 'Classkit',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);