<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.newt-bell.php',
    1 => 'newt_bell',
  ),
  1 => 
  array (
    0 => 'function.newt-button-bar.php',
    1 => 'newt_button_bar',
  ),
  2 => 
  array (
    0 => 'function.newt-button.php',
    1 => 'newt_button',
  ),
  3 => 
  array (
    0 => 'function.newt-centered-window.php',
    1 => 'newt_centered_window',
  ),
  4 => 
  array (
    0 => 'function.newt-checkbox-get-value.php',
    1 => 'newt_checkbox_get_value',
  ),
  5 => 
  array (
    0 => 'function.newt-checkbox-set-flags.php',
    1 => 'newt_checkbox_set_flags',
  ),
  6 => 
  array (
    0 => 'function.newt-checkbox-set-value.php',
    1 => 'newt_checkbox_set_value',
  ),
  7 => 
  array (
    0 => 'function.newt-checkbox-tree-add-item.php',
    1 => 'newt_checkbox_tree_add_item',
  ),
  8 => 
  array (
    0 => 'function.newt-checkbox-tree-find-item.php',
    1 => 'newt_checkbox_tree_find_item',
  ),
  9 => 
  array (
    0 => 'function.newt-checkbox-tree-get-current.php',
    1 => 'newt_checkbox_tree_get_current',
  ),
  10 => 
  array (
    0 => 'function.newt-checkbox-tree-get-entry-value.php',
    1 => 'newt_checkbox_tree_get_entry_value',
  ),
  11 => 
  array (
    0 => 'function.newt-checkbox-tree-get-multi-selection.php',
    1 => 'newt_checkbox_tree_get_multi_selection',
  ),
  12 => 
  array (
    0 => 'function.newt-checkbox-tree-get-selection.php',
    1 => 'newt_checkbox_tree_get_selection',
  ),
  13 => 
  array (
    0 => 'function.newt-checkbox-tree-multi.php',
    1 => 'newt_checkbox_tree_multi',
  ),
  14 => 
  array (
    0 => 'function.newt-checkbox-tree-set-current.php',
    1 => 'newt_checkbox_tree_set_current',
  ),
  15 => 
  array (
    0 => 'function.newt-checkbox-tree-set-entry-value.php',
    1 => 'newt_checkbox_tree_set_entry_value',
  ),
  16 => 
  array (
    0 => 'function.newt-checkbox-tree-set-entry.php',
    1 => 'newt_checkbox_tree_set_entry',
  ),
  17 => 
  array (
    0 => 'function.newt-checkbox-tree-set-width.php',
    1 => 'newt_checkbox_tree_set_width',
  ),
  18 => 
  array (
    0 => 'function.newt-checkbox-tree.php',
    1 => 'newt_checkbox_tree',
  ),
  19 => 
  array (
    0 => 'function.newt-checkbox.php',
    1 => 'newt_checkbox',
  ),
  20 => 
  array (
    0 => 'function.newt-clear-key-buffer.php',
    1 => 'newt_clear_key_buffer',
  ),
  21 => 
  array (
    0 => 'function.newt-cls.php',
    1 => 'newt_cls',
  ),
  22 => 
  array (
    0 => 'function.newt-compact-button.php',
    1 => 'newt_compact_button',
  ),
  23 => 
  array (
    0 => 'function.newt-component-add-callback.php',
    1 => 'newt_component_add_callback',
  ),
  24 => 
  array (
    0 => 'function.newt-component-takes-focus.php',
    1 => 'newt_component_takes_focus',
  ),
  25 => 
  array (
    0 => 'function.newt-create-grid.php',
    1 => 'newt_create_grid',
  ),
  26 => 
  array (
    0 => 'function.newt-cursor-off.php',
    1 => 'newt_cursor_off',
  ),
  27 => 
  array (
    0 => 'function.newt-cursor-on.php',
    1 => 'newt_cursor_on',
  ),
  28 => 
  array (
    0 => 'function.newt-delay.php',
    1 => 'newt_delay',
  ),
  29 => 
  array (
    0 => 'function.newt-draw-form.php',
    1 => 'newt_draw_form',
  ),
  30 => 
  array (
    0 => 'function.newt-draw-root-text.php',
    1 => 'newt_draw_root_text',
  ),
  31 => 
  array (
    0 => 'function.newt-entry-get-value.php',
    1 => 'newt_entry_get_value',
  ),
  32 => 
  array (
    0 => 'function.newt-entry-set-filter.php',
    1 => 'newt_entry_set_filter',
  ),
  33 => 
  array (
    0 => 'function.newt-entry-set-flags.php',
    1 => 'newt_entry_set_flags',
  ),
  34 => 
  array (
    0 => 'function.newt-entry-set.php',
    1 => 'newt_entry_set',
  ),
  35 => 
  array (
    0 => 'function.newt-entry.php',
    1 => 'newt_entry',
  ),
  36 => 
  array (
    0 => 'function.newt-finished.php',
    1 => 'newt_finished',
  ),
  37 => 
  array (
    0 => 'function.newt-form-add-component.php',
    1 => 'newt_form_add_component',
  ),
  38 => 
  array (
    0 => 'function.newt-form-add-components.php',
    1 => 'newt_form_add_components',
  ),
  39 => 
  array (
    0 => 'function.newt-form-add-hot-key.php',
    1 => 'newt_form_add_hot_key',
  ),
  40 => 
  array (
    0 => 'function.newt-form-destroy.php',
    1 => 'newt_form_destroy',
  ),
  41 => 
  array (
    0 => 'function.newt-form-get-current.php',
    1 => 'newt_form_get_current',
  ),
  42 => 
  array (
    0 => 'function.newt-form-run.php',
    1 => 'newt_form_run',
  ),
  43 => 
  array (
    0 => 'function.newt-form-set-background.php',
    1 => 'newt_form_set_background',
  ),
  44 => 
  array (
    0 => 'function.newt-form-set-height.php',
    1 => 'newt_form_set_height',
  ),
  45 => 
  array (
    0 => 'function.newt-form-set-size.php',
    1 => 'newt_form_set_size',
  ),
  46 => 
  array (
    0 => 'function.newt-form-set-timer.php',
    1 => 'newt_form_set_timer',
  ),
  47 => 
  array (
    0 => 'function.newt-form-set-width.php',
    1 => 'newt_form_set_width',
  ),
  48 => 
  array (
    0 => 'function.newt-form-watch-fd.php',
    1 => 'newt_form_watch_fd',
  ),
  49 => 
  array (
    0 => 'function.newt-form.php',
    1 => 'newt_form',
  ),
  50 => 
  array (
    0 => 'function.newt-get-screen-size.php',
    1 => 'newt_get_screen_size',
  ),
  51 => 
  array (
    0 => 'function.newt-grid-add-components-to-form.php',
    1 => 'newt_grid_add_components_to_form',
  ),
  52 => 
  array (
    0 => 'function.newt-grid-basic-window.php',
    1 => 'newt_grid_basic_window',
  ),
  53 => 
  array (
    0 => 'function.newt-grid-free.php',
    1 => 'newt_grid_free',
  ),
  54 => 
  array (
    0 => 'function.newt-grid-get-size.php',
    1 => 'newt_grid_get_size',
  ),
  55 => 
  array (
    0 => 'function.newt-grid-h-close-stacked.php',
    1 => 'newt_grid_h_close_stacked',
  ),
  56 => 
  array (
    0 => 'function.newt-grid-h-stacked.php',
    1 => 'newt_grid_h_stacked',
  ),
  57 => 
  array (
    0 => 'function.newt-grid-place.php',
    1 => 'newt_grid_place',
  ),
  58 => 
  array (
    0 => 'function.newt-grid-set-field.php',
    1 => 'newt_grid_set_field',
  ),
  59 => 
  array (
    0 => 'function.newt-grid-simple-window.php',
    1 => 'newt_grid_simple_window',
  ),
  60 => 
  array (
    0 => 'function.newt-grid-v-close-stacked.php',
    1 => 'newt_grid_v_close_stacked',
  ),
  61 => 
  array (
    0 => 'function.newt-grid-v-stacked.php',
    1 => 'newt_grid_v_stacked',
  ),
  62 => 
  array (
    0 => 'function.newt-grid-wrapped-window-at.php',
    1 => 'newt_grid_wrapped_window_at',
  ),
  63 => 
  array (
    0 => 'function.newt-grid-wrapped-window.php',
    1 => 'newt_grid_wrapped_window',
  ),
  64 => 
  array (
    0 => 'function.newt-init.php',
    1 => 'newt_init',
  ),
  65 => 
  array (
    0 => 'function.newt-label-set-text.php',
    1 => 'newt_label_set_text',
  ),
  66 => 
  array (
    0 => 'function.newt-label.php',
    1 => 'newt_label',
  ),
  67 => 
  array (
    0 => 'function.newt-listbox-append-entry.php',
    1 => 'newt_listbox_append_entry',
  ),
  68 => 
  array (
    0 => 'function.newt-listbox-clear-selection.php',
    1 => 'newt_listbox_clear_selection',
  ),
  69 => 
  array (
    0 => 'function.newt-listbox-clear.php',
    1 => 'newt_listbox_clear',
  ),
  70 => 
  array (
    0 => 'function.newt-listbox-delete-entry.php',
    1 => 'newt_listbox_delete_entry',
  ),
  71 => 
  array (
    0 => 'function.newt-listbox-get-current.php',
    1 => 'newt_listbox_get_current',
  ),
  72 => 
  array (
    0 => 'function.newt-listbox-get-selection.php',
    1 => 'newt_listbox_get_selection',
  ),
  73 => 
  array (
    0 => 'function.newt-listbox-insert-entry.php',
    1 => 'newt_listbox_insert_entry',
  ),
  74 => 
  array (
    0 => 'function.newt-listbox-item-count.php',
    1 => 'newt_listbox_item_count',
  ),
  75 => 
  array (
    0 => 'function.newt-listbox-select-item.php',
    1 => 'newt_listbox_select_item',
  ),
  76 => 
  array (
    0 => 'function.newt-listbox-set-current-by-key.php',
    1 => 'newt_listbox_set_current_by_key',
  ),
  77 => 
  array (
    0 => 'function.newt-listbox-set-current.php',
    1 => 'newt_listbox_set_current',
  ),
  78 => 
  array (
    0 => 'function.newt-listbox-set-data.php',
    1 => 'newt_listbox_set_data',
  ),
  79 => 
  array (
    0 => 'function.newt-listbox-set-entry.php',
    1 => 'newt_listbox_set_entry',
  ),
  80 => 
  array (
    0 => 'function.newt-listbox-set-width.php',
    1 => 'newt_listbox_set_width',
  ),
  81 => 
  array (
    0 => 'function.newt-listbox.php',
    1 => 'newt_listbox',
  ),
  82 => 
  array (
    0 => 'function.newt-listitem-get-data.php',
    1 => 'newt_listitem_get_data',
  ),
  83 => 
  array (
    0 => 'function.newt-listitem-set.php',
    1 => 'newt_listitem_set',
  ),
  84 => 
  array (
    0 => 'function.newt-listitem.php',
    1 => 'newt_listitem',
  ),
  85 => 
  array (
    0 => 'function.newt-open-window.php',
    1 => 'newt_open_window',
  ),
  86 => 
  array (
    0 => 'function.newt-pop-help-line.php',
    1 => 'newt_pop_help_line',
  ),
  87 => 
  array (
    0 => 'function.newt-pop-window.php',
    1 => 'newt_pop_window',
  ),
  88 => 
  array (
    0 => 'function.newt-push-help-line.php',
    1 => 'newt_push_help_line',
  ),
  89 => 
  array (
    0 => 'function.newt-radio-get-current.php',
    1 => 'newt_radio_get_current',
  ),
  90 => 
  array (
    0 => 'function.newt-radiobutton.php',
    1 => 'newt_radiobutton',
  ),
  91 => 
  array (
    0 => 'function.newt-redraw-help-line.php',
    1 => 'newt_redraw_help_line',
  ),
  92 => 
  array (
    0 => 'function.newt-reflow-text.php',
    1 => 'newt_reflow_text',
  ),
  93 => 
  array (
    0 => 'function.newt-refresh.php',
    1 => 'newt_refresh',
  ),
  94 => 
  array (
    0 => 'function.newt-resize-screen.php',
    1 => 'newt_resize_screen',
  ),
  95 => 
  array (
    0 => 'function.newt-resume.php',
    1 => 'newt_resume',
  ),
  96 => 
  array (
    0 => 'function.newt-run-form.php',
    1 => 'newt_run_form',
  ),
  97 => 
  array (
    0 => 'function.newt-scale-set.php',
    1 => 'newt_scale_set',
  ),
  98 => 
  array (
    0 => 'function.newt-scale.php',
    1 => 'newt_scale',
  ),
  99 => 
  array (
    0 => 'function.newt-scrollbar-set.php',
    1 => 'newt_scrollbar_set',
  ),
  100 => 
  array (
    0 => 'function.newt-set-help-callback.php',
    1 => 'newt_set_help_callback',
  ),
  101 => 
  array (
    0 => 'function.newt-set-suspend-callback.php',
    1 => 'newt_set_suspend_callback',
  ),
  102 => 
  array (
    0 => 'function.newt-suspend.php',
    1 => 'newt_suspend',
  ),
  103 => 
  array (
    0 => 'function.newt-textbox-get-num-lines.php',
    1 => 'newt_textbox_get_num_lines',
  ),
  104 => 
  array (
    0 => 'function.newt-textbox-reflowed.php',
    1 => 'newt_textbox_reflowed',
  ),
  105 => 
  array (
    0 => 'function.newt-textbox-set-height.php',
    1 => 'newt_textbox_set_height',
  ),
  106 => 
  array (
    0 => 'function.newt-textbox-set-text.php',
    1 => 'newt_textbox_set_text',
  ),
  107 => 
  array (
    0 => 'function.newt-textbox.php',
    1 => 'newt_textbox',
  ),
  108 => 
  array (
    0 => 'function.newt-vertical-scrollbar.php',
    1 => 'newt_vertical_scrollbar',
  ),
  109 => 
  array (
    0 => 'function.newt-wait-for-key.php',
    1 => 'newt_wait_for_key',
  ),
  110 => 
  array (
    0 => 'function.newt-win-choice.php',
    1 => 'newt_win_choice',
  ),
  111 => 
  array (
    0 => 'function.newt-win-entries.php',
    1 => 'newt_win_entries',
  ),
  112 => 
  array (
    0 => 'function.newt-win-menu.php',
    1 => 'newt_win_menu',
  ),
  113 => 
  array (
    0 => 'function.newt-win-message.php',
    1 => 'newt_win_message',
  ),
  114 => 
  array (
    0 => 'function.newt-win-messagev.php',
    1 => 'newt_win_messagev',
  ),
  115 => 
  array (
    0 => 'function.newt-win-ternary.php',
    1 => 'newt_win_ternary',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.newt.php',
    1 => 'Newt',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.cmdline.php',
    1 => 'Command Line Specific Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);