<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.http-cache-etag.php',
    1 => 'http_cache_etag',
  ),
  1 => 
  array (
    0 => 'function.http-cache-last-modified.php',
    1 => 'http_cache_last_modified',
  ),
  2 => 
  array (
    0 => 'function.http-chunked-decode.php',
    1 => 'http_chunked_decode',
  ),
  3 => 
  array (
    0 => 'function.http-deflate.php',
    1 => 'http_deflate',
  ),
  4 => 
  array (
    0 => 'function.http-inflate.php',
    1 => 'http_inflate',
  ),
  5 => 
  array (
    0 => 'function.http-build-cookie.php',
    1 => 'http_build_cookie',
  ),
  6 => 
  array (
    0 => 'function.http-date.php',
    1 => 'http_date',
  ),
  7 => 
  array (
    0 => 'function.http-get-request-body-stream.php',
    1 => 'http_get_request_body_stream',
  ),
  8 => 
  array (
    0 => 'function.http-get-request-body.php',
    1 => 'http_get_request_body',
  ),
  9 => 
  array (
    0 => 'function.http-get-request-headers.php',
    1 => 'http_get_request_headers',
  ),
  10 => 
  array (
    0 => 'function.http-match-etag.php',
    1 => 'http_match_etag',
  ),
  11 => 
  array (
    0 => 'function.http-match-modified.php',
    1 => 'http_match_modified',
  ),
  12 => 
  array (
    0 => 'function.http-match-request-header.php',
    1 => 'http_match_request_header',
  ),
  13 => 
  array (
    0 => 'function.http-support.php',
    1 => 'http_support',
  ),
  14 => 
  array (
    0 => 'function.http-negotiate-charset.php',
    1 => 'http_negotiate_charset',
  ),
  15 => 
  array (
    0 => 'function.http-negotiate-content-type.php',
    1 => 'http_negotiate_content_type',
  ),
  16 => 
  array (
    0 => 'function.http-negotiate-language.php',
    1 => 'http_negotiate_language',
  ),
  17 => 
  array (
    0 => 'function.ob-deflatehandler.php',
    1 => 'ob_deflatehandler',
  ),
  18 => 
  array (
    0 => 'function.ob-etaghandler.php',
    1 => 'ob_etaghandler',
  ),
  19 => 
  array (
    0 => 'function.ob-inflatehandler.php',
    1 => 'ob_inflatehandler',
  ),
  20 => 
  array (
    0 => 'function.http-parse-cookie.php',
    1 => 'http_parse_cookie',
  ),
  21 => 
  array (
    0 => 'function.http-parse-headers.php',
    1 => 'http_parse_headers',
  ),
  22 => 
  array (
    0 => 'function.http-parse-message.php',
    1 => 'http_parse_message',
  ),
  23 => 
  array (
    0 => 'function.http-parse-params.php',
    1 => 'http_parse_params',
  ),
  24 => 
  array (
    0 => 'function.http-persistent-handles-clean.php',
    1 => 'http_persistent_handles_clean',
  ),
  25 => 
  array (
    0 => 'function.http-persistent-handles-count.php',
    1 => 'http_persistent_handles_count',
  ),
  26 => 
  array (
    0 => 'function.http-persistent-handles-ident.php',
    1 => 'http_persistent_handles_ident',
  ),
  27 => 
  array (
    0 => 'function.http-get.php',
    1 => 'http_get',
  ),
  28 => 
  array (
    0 => 'function.http-head.php',
    1 => 'http_head',
  ),
  29 => 
  array (
    0 => 'function.http-post-data.php',
    1 => 'http_post_data',
  ),
  30 => 
  array (
    0 => 'function.http-post-fields.php',
    1 => 'http_post_fields',
  ),
  31 => 
  array (
    0 => 'function.http-put-data.php',
    1 => 'http_put_data',
  ),
  32 => 
  array (
    0 => 'function.http-put-file.php',
    1 => 'http_put_file',
  ),
  33 => 
  array (
    0 => 'function.http-put-stream.php',
    1 => 'http_put_stream',
  ),
  34 => 
  array (
    0 => 'function.http-request-body-encode.php',
    1 => 'http_request_body_encode',
  ),
  35 => 
  array (
    0 => 'function.http-request-method-exists.php',
    1 => 'http_request_method_exists',
  ),
  36 => 
  array (
    0 => 'function.http-request-method-name.php',
    1 => 'http_request_method_name',
  ),
  37 => 
  array (
    0 => 'function.http-request-method-register.php',
    1 => 'http_request_method_register',
  ),
  38 => 
  array (
    0 => 'function.http-request-method-unregister.php',
    1 => 'http_request_method_unregister',
  ),
  39 => 
  array (
    0 => 'function.http-request.php',
    1 => 'http_request',
  ),
  40 => 
  array (
    0 => 'function.http-redirect.php',
    1 => 'http_redirect',
  ),
  41 => 
  array (
    0 => 'function.http-send-content-disposition.php',
    1 => 'http_send_content_disposition',
  ),
  42 => 
  array (
    0 => 'function.http-send-content-type.php',
    1 => 'http_send_content_type',
  ),
  43 => 
  array (
    0 => 'function.http-send-data.php',
    1 => 'http_send_data',
  ),
  44 => 
  array (
    0 => 'function.http-send-file.php',
    1 => 'http_send_file',
  ),
  45 => 
  array (
    0 => 'function.http-send-last-modified.php',
    1 => 'http_send_last_modified',
  ),
  46 => 
  array (
    0 => 'function.http-send-status.php',
    1 => 'http_send_status',
  ),
  47 => 
  array (
    0 => 'function.http-send-stream.php',
    1 => 'http_send_stream',
  ),
  48 => 
  array (
    0 => 'function.http-throttle.php',
    1 => 'http_throttle',
  ),
  49 => 
  array (
    0 => 'function.http-build-str.php',
    1 => 'http_build_str',
  ),
  50 => 
  array (
    0 => 'function.http-build-url.php',
    1 => 'http_build_url',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.http.php',
    1 => 'HTTP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);