<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.bcadd.php',
    1 => 'bcadd',
  ),
  1 => 
  array (
    0 => 'function.bccomp.php',
    1 => 'bccomp',
  ),
  2 => 
  array (
    0 => 'function.bcdiv.php',
    1 => 'bcdiv',
  ),
  3 => 
  array (
    0 => 'function.bcmod.php',
    1 => 'bcmod',
  ),
  4 => 
  array (
    0 => 'function.bcmul.php',
    1 => 'bcmul',
  ),
  5 => 
  array (
    0 => 'function.bcpow.php',
    1 => 'bcpow',
  ),
  6 => 
  array (
    0 => 'function.bcpowmod.php',
    1 => 'bcpowmod',
  ),
  7 => 
  array (
    0 => 'function.bcscale.php',
    1 => 'bcscale',
  ),
  8 => 
  array (
    0 => 'function.bcsqrt.php',
    1 => 'bcsqrt',
  ),
  9 => 
  array (
    0 => 'function.bcsub.php',
    1 => 'bcsub',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.bc.php',
    1 => 'BC Math',
  ),
  1 => 
  array (
    0 => 'refs.math.php',
    1 => 'Mathematical Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);