<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.odbc-autocommit.php',
    1 => 'odbc_autocommit',
  ),
  1 => 
  array (
    0 => 'function.odbc-binmode.php',
    1 => 'odbc_binmode',
  ),
  2 => 
  array (
    0 => 'function.odbc-close-all.php',
    1 => 'odbc_close_all',
  ),
  3 => 
  array (
    0 => 'function.odbc-close.php',
    1 => 'odbc_close',
  ),
  4 => 
  array (
    0 => 'function.odbc-columnprivileges.php',
    1 => 'odbc_columnprivileges',
  ),
  5 => 
  array (
    0 => 'function.odbc-columns.php',
    1 => 'odbc_columns',
  ),
  6 => 
  array (
    0 => 'function.odbc-commit.php',
    1 => 'odbc_commit',
  ),
  7 => 
  array (
    0 => 'function.odbc-connect.php',
    1 => 'odbc_connect',
  ),
  8 => 
  array (
    0 => 'function.odbc-cursor.php',
    1 => 'odbc_cursor',
  ),
  9 => 
  array (
    0 => 'function.odbc-data-source.php',
    1 => 'odbc_data_source',
  ),
  10 => 
  array (
    0 => 'function.odbc-do.php',
    1 => 'odbc_do',
  ),
  11 => 
  array (
    0 => 'function.odbc-error.php',
    1 => 'odbc_error',
  ),
  12 => 
  array (
    0 => 'function.odbc-errormsg.php',
    1 => 'odbc_errormsg',
  ),
  13 => 
  array (
    0 => 'function.odbc-exec.php',
    1 => 'odbc_exec',
  ),
  14 => 
  array (
    0 => 'function.odbc-execute.php',
    1 => 'odbc_execute',
  ),
  15 => 
  array (
    0 => 'function.odbc-fetch-array.php',
    1 => 'odbc_fetch_array',
  ),
  16 => 
  array (
    0 => 'function.odbc-fetch-into.php',
    1 => 'odbc_fetch_into',
  ),
  17 => 
  array (
    0 => 'function.odbc-fetch-object.php',
    1 => 'odbc_fetch_object',
  ),
  18 => 
  array (
    0 => 'function.odbc-fetch-row.php',
    1 => 'odbc_fetch_row',
  ),
  19 => 
  array (
    0 => 'function.odbc-field-len.php',
    1 => 'odbc_field_len',
  ),
  20 => 
  array (
    0 => 'function.odbc-field-name.php',
    1 => 'odbc_field_name',
  ),
  21 => 
  array (
    0 => 'function.odbc-field-num.php',
    1 => 'odbc_field_num',
  ),
  22 => 
  array (
    0 => 'function.odbc-field-precision.php',
    1 => 'odbc_field_precision',
  ),
  23 => 
  array (
    0 => 'function.odbc-field-scale.php',
    1 => 'odbc_field_scale',
  ),
  24 => 
  array (
    0 => 'function.odbc-field-type.php',
    1 => 'odbc_field_type',
  ),
  25 => 
  array (
    0 => 'function.odbc-foreignkeys.php',
    1 => 'odbc_foreignkeys',
  ),
  26 => 
  array (
    0 => 'function.odbc-free-result.php',
    1 => 'odbc_free_result',
  ),
  27 => 
  array (
    0 => 'function.odbc-gettypeinfo.php',
    1 => 'odbc_gettypeinfo',
  ),
  28 => 
  array (
    0 => 'function.odbc-longreadlen.php',
    1 => 'odbc_longreadlen',
  ),
  29 => 
  array (
    0 => 'function.odbc-next-result.php',
    1 => 'odbc_next_result',
  ),
  30 => 
  array (
    0 => 'function.odbc-num-fields.php',
    1 => 'odbc_num_fields',
  ),
  31 => 
  array (
    0 => 'function.odbc-num-rows.php',
    1 => 'odbc_num_rows',
  ),
  32 => 
  array (
    0 => 'function.odbc-pconnect.php',
    1 => 'odbc_pconnect',
  ),
  33 => 
  array (
    0 => 'function.odbc-prepare.php',
    1 => 'odbc_prepare',
  ),
  34 => 
  array (
    0 => 'function.odbc-primarykeys.php',
    1 => 'odbc_primarykeys',
  ),
  35 => 
  array (
    0 => 'function.odbc-procedurecolumns.php',
    1 => 'odbc_procedurecolumns',
  ),
  36 => 
  array (
    0 => 'function.odbc-procedures.php',
    1 => 'odbc_procedures',
  ),
  37 => 
  array (
    0 => 'function.odbc-result-all.php',
    1 => 'odbc_result_all',
  ),
  38 => 
  array (
    0 => 'function.odbc-result.php',
    1 => 'odbc_result',
  ),
  39 => 
  array (
    0 => 'function.odbc-rollback.php',
    1 => 'odbc_rollback',
  ),
  40 => 
  array (
    0 => 'function.odbc-setoption.php',
    1 => 'odbc_setoption',
  ),
  41 => 
  array (
    0 => 'function.odbc-specialcolumns.php',
    1 => 'odbc_specialcolumns',
  ),
  42 => 
  array (
    0 => 'function.odbc-statistics.php',
    1 => 'odbc_statistics',
  ),
  43 => 
  array (
    0 => 'function.odbc-tableprivileges.php',
    1 => 'odbc_tableprivileges',
  ),
  44 => 
  array (
    0 => 'function.odbc-tables.php',
    1 => 'odbc_tables',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.uodbc.php',
    1 => 'ODBC',
  ),
  1 => 
  array (
    0 => 'refs.database.abstract.php',
    1 => 'Abstraction Layers',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);