<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.apd-breakpoint.php',
    1 => 'apd_breakpoint',
  ),
  1 => 
  array (
    0 => 'function.apd-callstack.php',
    1 => 'apd_callstack',
  ),
  2 => 
  array (
    0 => 'function.apd-clunk.php',
    1 => 'apd_clunk',
  ),
  3 => 
  array (
    0 => 'function.apd-continue.php',
    1 => 'apd_continue',
  ),
  4 => 
  array (
    0 => 'function.apd-croak.php',
    1 => 'apd_croak',
  ),
  5 => 
  array (
    0 => 'function.apd-dump-function-table.php',
    1 => 'apd_dump_function_table',
  ),
  6 => 
  array (
    0 => 'function.apd-dump-persistent-resources.php',
    1 => 'apd_dump_persistent_resources',
  ),
  7 => 
  array (
    0 => 'function.apd-dump-regular-resources.php',
    1 => 'apd_dump_regular_resources',
  ),
  8 => 
  array (
    0 => 'function.apd-echo.php',
    1 => 'apd_echo',
  ),
  9 => 
  array (
    0 => 'function.apd-get-active-symbols.php',
    1 => 'apd_get_active_symbols',
  ),
  10 => 
  array (
    0 => 'function.apd-set-pprof-trace.php',
    1 => 'apd_set_pprof_trace',
  ),
  11 => 
  array (
    0 => 'function.apd-set-session-trace-socket.php',
    1 => 'apd_set_session_trace_socket',
  ),
  12 => 
  array (
    0 => 'function.apd-set-session-trace.php',
    1 => 'apd_set_session_trace',
  ),
  13 => 
  array (
    0 => 'function.apd-set-session.php',
    1 => 'apd_set_session',
  ),
  14 => 
  array (
    0 => 'function.override-function.php',
    1 => 'override_function',
  ),
  15 => 
  array (
    0 => 'function.rename-function.php',
    1 => 'rename_function',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.apd.php',
    1 => 'APD',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);