<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.dbx-close.php',
    1 => 'dbx_close',
  ),
  1 => 
  array (
    0 => 'function.dbx-compare.php',
    1 => 'dbx_compare',
  ),
  2 => 
  array (
    0 => 'function.dbx-connect.php',
    1 => 'dbx_connect',
  ),
  3 => 
  array (
    0 => 'function.dbx-error.php',
    1 => 'dbx_error',
  ),
  4 => 
  array (
    0 => 'function.dbx-escape-string.php',
    1 => 'dbx_escape_string',
  ),
  5 => 
  array (
    0 => 'function.dbx-fetch-row.php',
    1 => 'dbx_fetch_row',
  ),
  6 => 
  array (
    0 => 'function.dbx-query.php',
    1 => 'dbx_query',
  ),
  7 => 
  array (
    0 => 'function.dbx-sort.php',
    1 => 'dbx_sort',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dbx.php',
    1 => 'dbx',
  ),
  1 => 
  array (
    0 => 'refs.database.abstract.php',
    1 => 'Abstraction Layers',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);