<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.px-close.php',
    1 => 'px_close',
  ),
  1 => 
  array (
    0 => 'function.px-create-fp.php',
    1 => 'px_create_fp',
  ),
  2 => 
  array (
    0 => 'function.px-date2string.php',
    1 => 'px_date2string',
  ),
  3 => 
  array (
    0 => 'function.px-delete-record.php',
    1 => 'px_delete_record',
  ),
  4 => 
  array (
    0 => 'function.px-delete.php',
    1 => 'px_delete',
  ),
  5 => 
  array (
    0 => 'function.px-get-field.php',
    1 => 'px_get_field',
  ),
  6 => 
  array (
    0 => 'function.px-get-info.php',
    1 => 'px_get_info',
  ),
  7 => 
  array (
    0 => 'function.px-get-parameter.php',
    1 => 'px_get_parameter',
  ),
  8 => 
  array (
    0 => 'function.px-get-record.php',
    1 => 'px_get_record',
  ),
  9 => 
  array (
    0 => 'function.px-get-schema.php',
    1 => 'px_get_schema',
  ),
  10 => 
  array (
    0 => 'function.px-get-value.php',
    1 => 'px_get_value',
  ),
  11 => 
  array (
    0 => 'function.px-insert-record.php',
    1 => 'px_insert_record',
  ),
  12 => 
  array (
    0 => 'function.px-new.php',
    1 => 'px_new',
  ),
  13 => 
  array (
    0 => 'function.px-numfields.php',
    1 => 'px_numfields',
  ),
  14 => 
  array (
    0 => 'function.px-numrecords.php',
    1 => 'px_numrecords',
  ),
  15 => 
  array (
    0 => 'function.px-open-fp.php',
    1 => 'px_open_fp',
  ),
  16 => 
  array (
    0 => 'function.px-put-record.php',
    1 => 'px_put_record',
  ),
  17 => 
  array (
    0 => 'function.px-retrieve-record.php',
    1 => 'px_retrieve_record',
  ),
  18 => 
  array (
    0 => 'function.px-set-blob-file.php',
    1 => 'px_set_blob_file',
  ),
  19 => 
  array (
    0 => 'function.px-set-parameter.php',
    1 => 'px_set_parameter',
  ),
  20 => 
  array (
    0 => 'function.px-set-tablename.php',
    1 => 'px_set_tablename',
  ),
  21 => 
  array (
    0 => 'function.px-set-targetencoding.php',
    1 => 'px_set_targetencoding',
  ),
  22 => 
  array (
    0 => 'function.px-set-value.php',
    1 => 'px_set_value',
  ),
  23 => 
  array (
    0 => 'function.px-timestamp2string.php',
    1 => 'px_timestamp2string',
  ),
  24 => 
  array (
    0 => 'function.px-update-record.php',
    1 => 'px_update_record',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.paradox.php',
    1 => 'Paradox',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);