<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ldap-8859-to-t61.php',
    1 => 'ldap_8859_to_t61',
  ),
  1 => 
  array (
    0 => 'function.ldap-add.php',
    1 => 'ldap_add',
  ),
  2 => 
  array (
    0 => 'function.ldap-bind.php',
    1 => 'ldap_bind',
  ),
  3 => 
  array (
    0 => 'function.ldap-close.php',
    1 => 'ldap_close',
  ),
  4 => 
  array (
    0 => 'function.ldap-compare.php',
    1 => 'ldap_compare',
  ),
  5 => 
  array (
    0 => 'function.ldap-connect.php',
    1 => 'ldap_connect',
  ),
  6 => 
  array (
    0 => 'function.ldap-count-entries.php',
    1 => 'ldap_count_entries',
  ),
  7 => 
  array (
    0 => 'function.ldap-delete.php',
    1 => 'ldap_delete',
  ),
  8 => 
  array (
    0 => 'function.ldap-dn2ufn.php',
    1 => 'ldap_dn2ufn',
  ),
  9 => 
  array (
    0 => 'function.ldap-err2str.php',
    1 => 'ldap_err2str',
  ),
  10 => 
  array (
    0 => 'function.ldap-errno.php',
    1 => 'ldap_errno',
  ),
  11 => 
  array (
    0 => 'function.ldap-error.php',
    1 => 'ldap_error',
  ),
  12 => 
  array (
    0 => 'function.ldap-explode-dn.php',
    1 => 'ldap_explode_dn',
  ),
  13 => 
  array (
    0 => 'function.ldap-first-attribute.php',
    1 => 'ldap_first_attribute',
  ),
  14 => 
  array (
    0 => 'function.ldap-first-entry.php',
    1 => 'ldap_first_entry',
  ),
  15 => 
  array (
    0 => 'function.ldap-first-reference.php',
    1 => 'ldap_first_reference',
  ),
  16 => 
  array (
    0 => 'function.ldap-free-result.php',
    1 => 'ldap_free_result',
  ),
  17 => 
  array (
    0 => 'function.ldap-get-attributes.php',
    1 => 'ldap_get_attributes',
  ),
  18 => 
  array (
    0 => 'function.ldap-get-dn.php',
    1 => 'ldap_get_dn',
  ),
  19 => 
  array (
    0 => 'function.ldap-get-entries.php',
    1 => 'ldap_get_entries',
  ),
  20 => 
  array (
    0 => 'function.ldap-get-option.php',
    1 => 'ldap_get_option',
  ),
  21 => 
  array (
    0 => 'function.ldap-get-values-len.php',
    1 => 'ldap_get_values_len',
  ),
  22 => 
  array (
    0 => 'function.ldap-get-values.php',
    1 => 'ldap_get_values',
  ),
  23 => 
  array (
    0 => 'function.ldap-list.php',
    1 => 'ldap_list',
  ),
  24 => 
  array (
    0 => 'function.ldap-mod-add.php',
    1 => 'ldap_mod_add',
  ),
  25 => 
  array (
    0 => 'function.ldap-mod-del.php',
    1 => 'ldap_mod_del',
  ),
  26 => 
  array (
    0 => 'function.ldap-mod-replace.php',
    1 => 'ldap_mod_replace',
  ),
  27 => 
  array (
    0 => 'function.ldap-modify.php',
    1 => 'ldap_modify',
  ),
  28 => 
  array (
    0 => 'function.ldap-next-attribute.php',
    1 => 'ldap_next_attribute',
  ),
  29 => 
  array (
    0 => 'function.ldap-next-entry.php',
    1 => 'ldap_next_entry',
  ),
  30 => 
  array (
    0 => 'function.ldap-next-reference.php',
    1 => 'ldap_next_reference',
  ),
  31 => 
  array (
    0 => 'function.ldap-parse-reference.php',
    1 => 'ldap_parse_reference',
  ),
  32 => 
  array (
    0 => 'function.ldap-parse-result.php',
    1 => 'ldap_parse_result',
  ),
  33 => 
  array (
    0 => 'function.ldap-read.php',
    1 => 'ldap_read',
  ),
  34 => 
  array (
    0 => 'function.ldap-rename.php',
    1 => 'ldap_rename',
  ),
  35 => 
  array (
    0 => 'function.ldap-sasl-bind.php',
    1 => 'ldap_sasl_bind',
  ),
  36 => 
  array (
    0 => 'function.ldap-search.php',
    1 => 'ldap_search',
  ),
  37 => 
  array (
    0 => 'function.ldap-set-option.php',
    1 => 'ldap_set_option',
  ),
  38 => 
  array (
    0 => 'function.ldap-set-rebind-proc.php',
    1 => 'ldap_set_rebind_proc',
  ),
  39 => 
  array (
    0 => 'function.ldap-sort.php',
    1 => 'ldap_sort',
  ),
  40 => 
  array (
    0 => 'function.ldap-start-tls.php',
    1 => 'ldap_start_tls',
  ),
  41 => 
  array (
    0 => 'function.ldap-t61-to-8859.php',
    1 => 'ldap_t61_to_8859',
  ),
  42 => 
  array (
    0 => 'function.ldap-unbind.php',
    1 => 'ldap_unbind',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ldap.php',
    1 => 'LDAP',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);