<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.addcslashes.php',
    1 => 'addcslashes',
  ),
  1 => 
  array (
    0 => 'function.addslashes.php',
    1 => 'addslashes',
  ),
  2 => 
  array (
    0 => 'function.bin2hex.php',
    1 => 'bin2hex',
  ),
  3 => 
  array (
    0 => 'function.chop.php',
    1 => 'chop',
  ),
  4 => 
  array (
    0 => 'function.chr.php',
    1 => 'chr',
  ),
  5 => 
  array (
    0 => 'function.chunk-split.php',
    1 => 'chunk_split',
  ),
  6 => 
  array (
    0 => 'function.convert-cyr-string.php',
    1 => 'convert_cyr_string',
  ),
  7 => 
  array (
    0 => 'function.convert-uudecode.php',
    1 => 'convert_uudecode',
  ),
  8 => 
  array (
    0 => 'function.convert-uuencode.php',
    1 => 'convert_uuencode',
  ),
  9 => 
  array (
    0 => 'function.count-chars.php',
    1 => 'count_chars',
  ),
  10 => 
  array (
    0 => 'function.crc32.php',
    1 => 'crc32',
  ),
  11 => 
  array (
    0 => 'function.crypt.php',
    1 => 'crypt',
  ),
  12 => 
  array (
    0 => 'function.echo.php',
    1 => 'echo',
  ),
  13 => 
  array (
    0 => 'function.explode.php',
    1 => 'explode',
  ),
  14 => 
  array (
    0 => 'function.fprintf.php',
    1 => 'fprintf',
  ),
  15 => 
  array (
    0 => 'function.get-html-translation-table.php',
    1 => 'get_html_translation_table',
  ),
  16 => 
  array (
    0 => 'function.hebrev.php',
    1 => 'hebrev',
  ),
  17 => 
  array (
    0 => 'function.hebrevc.php',
    1 => 'hebrevc',
  ),
  18 => 
  array (
    0 => 'function.html-entity-decode.php',
    1 => 'html_entity_decode',
  ),
  19 => 
  array (
    0 => 'function.htmlentities.php',
    1 => 'htmlentities',
  ),
  20 => 
  array (
    0 => 'function.htmlspecialchars-decode.php',
    1 => 'htmlspecialchars_decode',
  ),
  21 => 
  array (
    0 => 'function.htmlspecialchars.php',
    1 => 'htmlspecialchars',
  ),
  22 => 
  array (
    0 => 'function.implode.php',
    1 => 'implode',
  ),
  23 => 
  array (
    0 => 'function.join.php',
    1 => 'join',
  ),
  24 => 
  array (
    0 => 'function.lcfirst.php',
    1 => 'lcfirst',
  ),
  25 => 
  array (
    0 => 'function.levenshtein.php',
    1 => 'levenshtein',
  ),
  26 => 
  array (
    0 => 'function.localeconv.php',
    1 => 'localeconv',
  ),
  27 => 
  array (
    0 => 'function.ltrim.php',
    1 => 'ltrim',
  ),
  28 => 
  array (
    0 => 'function.md5-file.php',
    1 => 'md5_file',
  ),
  29 => 
  array (
    0 => 'function.md5.php',
    1 => 'md5',
  ),
  30 => 
  array (
    0 => 'function.metaphone.php',
    1 => 'metaphone',
  ),
  31 => 
  array (
    0 => 'function.money-format.php',
    1 => 'money_format',
  ),
  32 => 
  array (
    0 => 'function.nl-langinfo.php',
    1 => 'nl_langinfo',
  ),
  33 => 
  array (
    0 => 'function.nl2br.php',
    1 => 'nl2br',
  ),
  34 => 
  array (
    0 => 'function.number-format.php',
    1 => 'number_format',
  ),
  35 => 
  array (
    0 => 'function.ord.php',
    1 => 'ord',
  ),
  36 => 
  array (
    0 => 'function.parse-str.php',
    1 => 'parse_str',
  ),
  37 => 
  array (
    0 => 'function.print.php',
    1 => 'print',
  ),
  38 => 
  array (
    0 => 'function.printf.php',
    1 => 'printf',
  ),
  39 => 
  array (
    0 => 'function.quoted-printable-decode.php',
    1 => 'quoted_printable_decode',
  ),
  40 => 
  array (
    0 => 'function.quoted-printable-encode.php',
    1 => 'quoted_printable_encode',
  ),
  41 => 
  array (
    0 => 'function.quotemeta.php',
    1 => 'quotemeta',
  ),
  42 => 
  array (
    0 => 'function.rtrim.php',
    1 => 'rtrim',
  ),
  43 => 
  array (
    0 => 'function.setlocale.php',
    1 => 'setlocale',
  ),
  44 => 
  array (
    0 => 'function.sha1-file.php',
    1 => 'sha1_file',
  ),
  45 => 
  array (
    0 => 'function.sha1.php',
    1 => 'sha1',
  ),
  46 => 
  array (
    0 => 'function.similar-text.php',
    1 => 'similar_text',
  ),
  47 => 
  array (
    0 => 'function.soundex.php',
    1 => 'soundex',
  ),
  48 => 
  array (
    0 => 'function.sprintf.php',
    1 => 'sprintf',
  ),
  49 => 
  array (
    0 => 'function.sscanf.php',
    1 => 'sscanf',
  ),
  50 => 
  array (
    0 => 'function.str-getcsv.php',
    1 => 'str_getcsv',
  ),
  51 => 
  array (
    0 => 'function.str-ireplace.php',
    1 => 'str_ireplace',
  ),
  52 => 
  array (
    0 => 'function.str-pad.php',
    1 => 'str_pad',
  ),
  53 => 
  array (
    0 => 'function.str-repeat.php',
    1 => 'str_repeat',
  ),
  54 => 
  array (
    0 => 'function.str-replace.php',
    1 => 'str_replace',
  ),
  55 => 
  array (
    0 => 'function.str-rot13.php',
    1 => 'str_rot13',
  ),
  56 => 
  array (
    0 => 'function.str-shuffle.php',
    1 => 'str_shuffle',
  ),
  57 => 
  array (
    0 => 'function.str-split.php',
    1 => 'str_split',
  ),
  58 => 
  array (
    0 => 'function.str-word-count.php',
    1 => 'str_word_count',
  ),
  59 => 
  array (
    0 => 'function.strcasecmp.php',
    1 => 'strcasecmp',
  ),
  60 => 
  array (
    0 => 'function.strchr.php',
    1 => 'strchr',
  ),
  61 => 
  array (
    0 => 'function.strcmp.php',
    1 => 'strcmp',
  ),
  62 => 
  array (
    0 => 'function.strcoll.php',
    1 => 'strcoll',
  ),
  63 => 
  array (
    0 => 'function.strcspn.php',
    1 => 'strcspn',
  ),
  64 => 
  array (
    0 => 'function.strip-tags.php',
    1 => 'strip_tags',
  ),
  65 => 
  array (
    0 => 'function.stripcslashes.php',
    1 => 'stripcslashes',
  ),
  66 => 
  array (
    0 => 'function.stripos.php',
    1 => 'stripos',
  ),
  67 => 
  array (
    0 => 'function.stripslashes.php',
    1 => 'stripslashes',
  ),
  68 => 
  array (
    0 => 'function.stristr.php',
    1 => 'stristr',
  ),
  69 => 
  array (
    0 => 'function.strlen.php',
    1 => 'strlen',
  ),
  70 => 
  array (
    0 => 'function.strnatcasecmp.php',
    1 => 'strnatcasecmp',
  ),
  71 => 
  array (
    0 => 'function.strnatcmp.php',
    1 => 'strnatcmp',
  ),
  72 => 
  array (
    0 => 'function.strncasecmp.php',
    1 => 'strncasecmp',
  ),
  73 => 
  array (
    0 => 'function.strncmp.php',
    1 => 'strncmp',
  ),
  74 => 
  array (
    0 => 'function.strpbrk.php',
    1 => 'strpbrk',
  ),
  75 => 
  array (
    0 => 'function.strpos.php',
    1 => 'strpos',
  ),
  76 => 
  array (
    0 => 'function.strrchr.php',
    1 => 'strrchr',
  ),
  77 => 
  array (
    0 => 'function.strrev.php',
    1 => 'strrev',
  ),
  78 => 
  array (
    0 => 'function.strripos.php',
    1 => 'strripos',
  ),
  79 => 
  array (
    0 => 'function.strrpos.php',
    1 => 'strrpos',
  ),
  80 => 
  array (
    0 => 'function.strspn.php',
    1 => 'strspn',
  ),
  81 => 
  array (
    0 => 'function.strstr.php',
    1 => 'strstr',
  ),
  82 => 
  array (
    0 => 'function.strtok.php',
    1 => 'strtok',
  ),
  83 => 
  array (
    0 => 'function.strtolower.php',
    1 => 'strtolower',
  ),
  84 => 
  array (
    0 => 'function.strtoupper.php',
    1 => 'strtoupper',
  ),
  85 => 
  array (
    0 => 'function.strtr.php',
    1 => 'strtr',
  ),
  86 => 
  array (
    0 => 'function.substr-compare.php',
    1 => 'substr_compare',
  ),
  87 => 
  array (
    0 => 'function.substr-count.php',
    1 => 'substr_count',
  ),
  88 => 
  array (
    0 => 'function.substr-replace.php',
    1 => 'substr_replace',
  ),
  89 => 
  array (
    0 => 'function.substr.php',
    1 => 'substr',
  ),
  90 => 
  array (
    0 => 'function.trim.php',
    1 => 'trim',
  ),
  91 => 
  array (
    0 => 'function.ucfirst.php',
    1 => 'ucfirst',
  ),
  92 => 
  array (
    0 => 'function.ucwords.php',
    1 => 'ucwords',
  ),
  93 => 
  array (
    0 => 'function.vfprintf.php',
    1 => 'vfprintf',
  ),
  94 => 
  array (
    0 => 'function.vprintf.php',
    1 => 'vprintf',
  ),
  95 => 
  array (
    0 => 'function.vsprintf.php',
    1 => 'vsprintf',
  ),
  96 => 
  array (
    0 => 'function.wordwrap.php',
    1 => 'wordwrap',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.strings.php',
    1 => 'Strings',
  ),
  1 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'Text Processing',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);