<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ctype-alnum.php',
    1 => 'ctype_alnum',
  ),
  1 => 
  array (
    0 => 'function.ctype-alpha.php',
    1 => 'ctype_alpha',
  ),
  2 => 
  array (
    0 => 'function.ctype-cntrl.php',
    1 => 'ctype_cntrl',
  ),
  3 => 
  array (
    0 => 'function.ctype-digit.php',
    1 => 'ctype_digit',
  ),
  4 => 
  array (
    0 => 'function.ctype-graph.php',
    1 => 'ctype_graph',
  ),
  5 => 
  array (
    0 => 'function.ctype-lower.php',
    1 => 'ctype_lower',
  ),
  6 => 
  array (
    0 => 'function.ctype-print.php',
    1 => 'ctype_print',
  ),
  7 => 
  array (
    0 => 'function.ctype-punct.php',
    1 => 'ctype_punct',
  ),
  8 => 
  array (
    0 => 'function.ctype-space.php',
    1 => 'ctype_space',
  ),
  9 => 
  array (
    0 => 'function.ctype-upper.php',
    1 => 'ctype_upper',
  ),
  10 => 
  array (
    0 => 'function.ctype-xdigit.php',
    1 => 'ctype_xdigit',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ctype.php',
    1 => 'Ctype',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);