<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.shmop-close.php',
    1 => 'shmop_close',
  ),
  1 => 
  array (
    0 => 'function.shmop-delete.php',
    1 => 'shmop_delete',
  ),
  2 => 
  array (
    0 => 'function.shmop-open.php',
    1 => 'shmop_open',
  ),
  3 => 
  array (
    0 => 'function.shmop-read.php',
    1 => 'shmop_read',
  ),
  4 => 
  array (
    0 => 'function.shmop-size.php',
    1 => 'shmop_size',
  ),
  5 => 
  array (
    0 => 'function.shmop-write.php',
    1 => 'shmop_write',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.shmop.php',
    1 => 'Shared Memory',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);