<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.escapeshellarg.php',
    1 => 'escapeshellarg',
  ),
  1 => 
  array (
    0 => 'function.escapeshellcmd.php',
    1 => 'escapeshellcmd',
  ),
  2 => 
  array (
    0 => 'function.exec.php',
    1 => 'exec',
  ),
  3 => 
  array (
    0 => 'function.passthru.php',
    1 => 'passthru',
  ),
  4 => 
  array (
    0 => 'function.proc-close.php',
    1 => 'proc_close',
  ),
  5 => 
  array (
    0 => 'function.proc-get-status.php',
    1 => 'proc_get_status',
  ),
  6 => 
  array (
    0 => 'function.proc-nice.php',
    1 => 'proc_nice',
  ),
  7 => 
  array (
    0 => 'function.proc-open.php',
    1 => 'proc_open',
  ),
  8 => 
  array (
    0 => 'function.proc-terminate.php',
    1 => 'proc_terminate',
  ),
  9 => 
  array (
    0 => 'function.shell-exec.php',
    1 => 'shell_exec',
  ),
  10 => 
  array (
    0 => 'function.system.php',
    1 => 'system',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.exec.php',
    1 => 'Program execution',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);