<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.m-checkstatus.php',
    1 => 'm_checkstatus',
  ),
  1 => 
  array (
    0 => 'function.m-completeauthorizations.php',
    1 => 'm_completeauthorizations',
  ),
  2 => 
  array (
    0 => 'function.m-connect.php',
    1 => 'm_connect',
  ),
  3 => 
  array (
    0 => 'function.m-connectionerror.php',
    1 => 'm_connectionerror',
  ),
  4 => 
  array (
    0 => 'function.m-deletetrans.php',
    1 => 'm_deletetrans',
  ),
  5 => 
  array (
    0 => 'function.m-destroyconn.php',
    1 => 'm_destroyconn',
  ),
  6 => 
  array (
    0 => 'function.m-destroyengine.php',
    1 => 'm_destroyengine',
  ),
  7 => 
  array (
    0 => 'function.m-getcell.php',
    1 => 'm_getcell',
  ),
  8 => 
  array (
    0 => 'function.m-getcellbynum.php',
    1 => 'm_getcellbynum',
  ),
  9 => 
  array (
    0 => 'function.m-getcommadelimited.php',
    1 => 'm_getcommadelimited',
  ),
  10 => 
  array (
    0 => 'function.m-getheader.php',
    1 => 'm_getheader',
  ),
  11 => 
  array (
    0 => 'function.m-initconn.php',
    1 => 'm_initconn',
  ),
  12 => 
  array (
    0 => 'function.m-initengine.php',
    1 => 'm_initengine',
  ),
  13 => 
  array (
    0 => 'function.m-iscommadelimited.php',
    1 => 'm_iscommadelimited',
  ),
  14 => 
  array (
    0 => 'function.m-maxconntimeout.php',
    1 => 'm_maxconntimeout',
  ),
  15 => 
  array (
    0 => 'function.m-monitor.php',
    1 => 'm_monitor',
  ),
  16 => 
  array (
    0 => 'function.m-numcolumns.php',
    1 => 'm_numcolumns',
  ),
  17 => 
  array (
    0 => 'function.m-numrows.php',
    1 => 'm_numrows',
  ),
  18 => 
  array (
    0 => 'function.m-parsecommadelimited.php',
    1 => 'm_parsecommadelimited',
  ),
  19 => 
  array (
    0 => 'function.m-responsekeys.php',
    1 => 'm_responsekeys',
  ),
  20 => 
  array (
    0 => 'function.m-responseparam.php',
    1 => 'm_responseparam',
  ),
  21 => 
  array (
    0 => 'function.m-returnstatus.php',
    1 => 'm_returnstatus',
  ),
  22 => 
  array (
    0 => 'function.m-setblocking.php',
    1 => 'm_setblocking',
  ),
  23 => 
  array (
    0 => 'function.m-setdropfile.php',
    1 => 'm_setdropfile',
  ),
  24 => 
  array (
    0 => 'function.m-setip.php',
    1 => 'm_setip',
  ),
  25 => 
  array (
    0 => 'function.m-setssl-cafile.php',
    1 => 'm_setssl_cafile',
  ),
  26 => 
  array (
    0 => 'function.m-setssl-files.php',
    1 => 'm_setssl_files',
  ),
  27 => 
  array (
    0 => 'function.m-setssl.php',
    1 => 'm_setssl',
  ),
  28 => 
  array (
    0 => 'function.m-settimeout.php',
    1 => 'm_settimeout',
  ),
  29 => 
  array (
    0 => 'function.m-sslcert-gen-hash.php',
    1 => 'm_sslcert_gen_hash',
  ),
  30 => 
  array (
    0 => 'function.m-transactionssent.php',
    1 => 'm_transactionssent',
  ),
  31 => 
  array (
    0 => 'function.m-transinqueue.php',
    1 => 'm_transinqueue',
  ),
  32 => 
  array (
    0 => 'function.m-transkeyval.php',
    1 => 'm_transkeyval',
  ),
  33 => 
  array (
    0 => 'function.m-transnew.php',
    1 => 'm_transnew',
  ),
  34 => 
  array (
    0 => 'function.m-transsend.php',
    1 => 'm_transsend',
  ),
  35 => 
  array (
    0 => 'function.m-uwait.php',
    1 => 'm_uwait',
  ),
  36 => 
  array (
    0 => 'function.m-validateidentifier.php',
    1 => 'm_validateidentifier',
  ),
  37 => 
  array (
    0 => 'function.m-verifyconnection.php',
    1 => 'm_verifyconnection',
  ),
  38 => 
  array (
    0 => 'function.m-verifysslcert.php',
    1 => 'm_verifysslcert',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.mcve.php',
    1 => 'MCVE',
  ),
  1 => 
  array (
    0 => 'refs.creditcard.php',
    1 => 'Credit Card Processing',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);