<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.chdb-create.php',
    1 => 'chdb_create',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.chdb.php',
    1 => 'chdb',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);