<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ereg-replace.php',
    1 => 'ereg_replace',
  ),
  1 => 
  array (
    0 => 'function.ereg.php',
    1 => 'ereg',
  ),
  2 => 
  array (
    0 => 'function.eregi-replace.php',
    1 => 'eregi_replace',
  ),
  3 => 
  array (
    0 => 'function.eregi.php',
    1 => 'eregi',
  ),
  4 => 
  array (
    0 => 'function.split.php',
    1 => 'split',
  ),
  5 => 
  array (
    0 => 'function.spliti.php',
    1 => 'spliti',
  ),
  6 => 
  array (
    0 => 'function.sql-regcase.php',
    1 => 'sql_regcase',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.regex.php',
    1 => 'POSIX Regex',
  ),
  1 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'Text Processing',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);