<?php
$TOC = array (
  0 => 
  array (
    0 => 'runkit.sandbox.php',
    1 => 'Runkit_Sandbox',
  ),
  1 => 
  array (
    0 => 'runkit.sandbox-parent.php',
    1 => 'Runkit_Sandbox_Parent',
  ),
  2 => 
  array (
    0 => 'function.runkit-class-adopt.php',
    1 => 'runkit_class_adopt',
  ),
  3 => 
  array (
    0 => 'function.runkit-class-emancipate.php',
    1 => 'runkit_class_emancipate',
  ),
  4 => 
  array (
    0 => 'function.runkit-constant-add.php',
    1 => 'runkit_constant_add',
  ),
  5 => 
  array (
    0 => 'function.runkit-constant-redefine.php',
    1 => 'runkit_constant_redefine',
  ),
  6 => 
  array (
    0 => 'function.runkit-constant-remove.php',
    1 => 'runkit_constant_remove',
  ),
  7 => 
  array (
    0 => 'function.runkit-function-add.php',
    1 => 'runkit_function_add',
  ),
  8 => 
  array (
    0 => 'function.runkit-function-copy.php',
    1 => 'runkit_function_copy',
  ),
  9 => 
  array (
    0 => 'function.runkit-function-redefine.php',
    1 => 'runkit_function_redefine',
  ),
  10 => 
  array (
    0 => 'function.runkit-function-remove.php',
    1 => 'runkit_function_remove',
  ),
  11 => 
  array (
    0 => 'function.runkit-function-rename.php',
    1 => 'runkit_function_rename',
  ),
  12 => 
  array (
    0 => 'function.runkit-import.php',
    1 => 'runkit_import',
  ),
  13 => 
  array (
    0 => 'function.runkit-lint-file.php',
    1 => 'runkit_lint_file',
  ),
  14 => 
  array (
    0 => 'function.runkit-lint.php',
    1 => 'runkit_lint',
  ),
  15 => 
  array (
    0 => 'function.runkit-method-add.php',
    1 => 'runkit_method_add',
  ),
  16 => 
  array (
    0 => 'function.runkit-method-copy.php',
    1 => 'runkit_method_copy',
  ),
  17 => 
  array (
    0 => 'function.runkit-method-redefine.php',
    1 => 'runkit_method_redefine',
  ),
  18 => 
  array (
    0 => 'function.runkit-method-remove.php',
    1 => 'runkit_method_remove',
  ),
  19 => 
  array (
    0 => 'function.runkit-method-rename.php',
    1 => 'runkit_method_rename',
  ),
  20 => 
  array (
    0 => 'function.runkit-return-value-used.php',
    1 => 'runkit_return_value_used',
  ),
  21 => 
  array (
    0 => 'function.runkit-sandbox-output-handler.php',
    1 => 'runkit_sandbox_output_handler',
  ),
  22 => 
  array (
    0 => 'function.runkit-superglobals.php',
    1 => 'runkit_superglobals',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.runkit.php',
    1 => 'runkit',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);