<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.openssl-csr-export-to-file.php',
    1 => 'openssl_csr_export_to_file',
  ),
  1 => 
  array (
    0 => 'function.openssl-csr-export.php',
    1 => 'openssl_csr_export',
  ),
  2 => 
  array (
    0 => 'function.openssl-csr-get-public-key.php',
    1 => 'openssl_csr_get_public_key',
  ),
  3 => 
  array (
    0 => 'function.openssl-csr-get-subject.php',
    1 => 'openssl_csr_get_subject',
  ),
  4 => 
  array (
    0 => 'function.openssl-csr-new.php',
    1 => 'openssl_csr_new',
  ),
  5 => 
  array (
    0 => 'function.openssl-csr-sign.php',
    1 => 'openssl_csr_sign',
  ),
  6 => 
  array (
    0 => 'function.openssl-decrypt.php',
    1 => 'openssl_decrypt',
  ),
  7 => 
  array (
    0 => 'function.openssl-dh-compute-key.php',
    1 => 'openssl_dh_compute_key',
  ),
  8 => 
  array (
    0 => 'function.openssl-digest.php',
    1 => 'openssl_digest',
  ),
  9 => 
  array (
    0 => 'function.openssl-encrypt.php',
    1 => 'openssl_encrypt',
  ),
  10 => 
  array (
    0 => 'function.openssl-error-string.php',
    1 => 'openssl_error_string',
  ),
  11 => 
  array (
    0 => 'function.openssl-free-key.php',
    1 => 'openssl_free_key',
  ),
  12 => 
  array (
    0 => 'function.openssl-get-cipher-methods.php',
    1 => 'openssl_get_cipher_methods',
  ),
  13 => 
  array (
    0 => 'function.openssl-get-md-methods.php',
    1 => 'openssl_get_md_methods',
  ),
  14 => 
  array (
    0 => 'function.openssl-get-privatekey.php',
    1 => 'openssl_get_privatekey',
  ),
  15 => 
  array (
    0 => 'function.openssl-get-publickey.php',
    1 => 'openssl_get_publickey',
  ),
  16 => 
  array (
    0 => 'function.openssl-open.php',
    1 => 'openssl_open',
  ),
  17 => 
  array (
    0 => 'function.openssl-pkcs12-export-to-file.php',
    1 => 'openssl_pkcs12_export_to_file',
  ),
  18 => 
  array (
    0 => 'function.openssl-pkcs12-export.php',
    1 => 'openssl_pkcs12_export',
  ),
  19 => 
  array (
    0 => 'function.openssl-pkcs12-read.php',
    1 => 'openssl_pkcs12_read',
  ),
  20 => 
  array (
    0 => 'function.openssl-pkcs7-decrypt.php',
    1 => 'openssl_pkcs7_decrypt',
  ),
  21 => 
  array (
    0 => 'function.openssl-pkcs7-encrypt.php',
    1 => 'openssl_pkcs7_encrypt',
  ),
  22 => 
  array (
    0 => 'function.openssl-pkcs7-sign.php',
    1 => 'openssl_pkcs7_sign',
  ),
  23 => 
  array (
    0 => 'function.openssl-pkcs7-verify.php',
    1 => 'openssl_pkcs7_verify',
  ),
  24 => 
  array (
    0 => 'function.openssl-pkey-export-to-file.php',
    1 => 'openssl_pkey_export_to_file',
  ),
  25 => 
  array (
    0 => 'function.openssl-pkey-export.php',
    1 => 'openssl_pkey_export',
  ),
  26 => 
  array (
    0 => 'function.openssl-pkey-free.php',
    1 => 'openssl_pkey_free',
  ),
  27 => 
  array (
    0 => 'function.openssl-pkey-get-details.php',
    1 => 'openssl_pkey_get_details',
  ),
  28 => 
  array (
    0 => 'function.openssl-pkey-get-private.php',
    1 => 'openssl_pkey_get_private',
  ),
  29 => 
  array (
    0 => 'function.openssl-pkey-get-public.php',
    1 => 'openssl_pkey_get_public',
  ),
  30 => 
  array (
    0 => 'function.openssl-pkey-new.php',
    1 => 'openssl_pkey_new',
  ),
  31 => 
  array (
    0 => 'function.openssl-private-decrypt.php',
    1 => 'openssl_private_decrypt',
  ),
  32 => 
  array (
    0 => 'function.openssl-private-encrypt.php',
    1 => 'openssl_private_encrypt',
  ),
  33 => 
  array (
    0 => 'function.openssl-public-decrypt.php',
    1 => 'openssl_public_decrypt',
  ),
  34 => 
  array (
    0 => 'function.openssl-public-encrypt.php',
    1 => 'openssl_public_encrypt',
  ),
  35 => 
  array (
    0 => 'function.openssl-random-pseudo-bytes.php',
    1 => 'openssl_random_pseudo_bytes',
  ),
  36 => 
  array (
    0 => 'function.openssl-seal.php',
    1 => 'openssl_seal',
  ),
  37 => 
  array (
    0 => 'function.openssl-sign.php',
    1 => 'openssl_sign',
  ),
  38 => 
  array (
    0 => 'function.openssl-verify.php',
    1 => 'openssl_verify',
  ),
  39 => 
  array (
    0 => 'function.openssl-x509-check-private-key.php',
    1 => 'openssl_x509_check_private_key',
  ),
  40 => 
  array (
    0 => 'function.openssl-x509-checkpurpose.php',
    1 => 'openssl_x509_checkpurpose',
  ),
  41 => 
  array (
    0 => 'function.openssl-x509-export-to-file.php',
    1 => 'openssl_x509_export_to_file',
  ),
  42 => 
  array (
    0 => 'function.openssl-x509-export.php',
    1 => 'openssl_x509_export',
  ),
  43 => 
  array (
    0 => 'function.openssl-x509-free.php',
    1 => 'openssl_x509_free',
  ),
  44 => 
  array (
    0 => 'function.openssl-x509-parse.php',
    1 => 'openssl_x509_parse',
  ),
  45 => 
  array (
    0 => 'function.openssl-x509-read.php',
    1 => 'openssl_x509_read',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.openssl.php',
    1 => 'OpenSSL',
  ),
  1 => 
  array (
    0 => 'refs.crypto.php',
    1 => 'Cryptography Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);