<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.openal-buffer-create.php',
    1 => 'openal_buffer_create',
  ),
  1 => 
  array (
    0 => 'function.openal-buffer-data.php',
    1 => 'openal_buffer_data',
  ),
  2 => 
  array (
    0 => 'function.openal-buffer-destroy.php',
    1 => 'openal_buffer_destroy',
  ),
  3 => 
  array (
    0 => 'function.openal-buffer-get.php',
    1 => 'openal_buffer_get',
  ),
  4 => 
  array (
    0 => 'function.openal-buffer-loadwav.php',
    1 => 'openal_buffer_loadwav',
  ),
  5 => 
  array (
    0 => 'function.openal-context-create.php',
    1 => 'openal_context_create',
  ),
  6 => 
  array (
    0 => 'function.openal-context-current.php',
    1 => 'openal_context_current',
  ),
  7 => 
  array (
    0 => 'function.openal-context-destroy.php',
    1 => 'openal_context_destroy',
  ),
  8 => 
  array (
    0 => 'function.openal-context-process.php',
    1 => 'openal_context_process',
  ),
  9 => 
  array (
    0 => 'function.openal-context-suspend.php',
    1 => 'openal_context_suspend',
  ),
  10 => 
  array (
    0 => 'function.openal-device-close.php',
    1 => 'openal_device_close',
  ),
  11 => 
  array (
    0 => 'function.openal-device-open.php',
    1 => 'openal_device_open',
  ),
  12 => 
  array (
    0 => 'function.openal-listener-get.php',
    1 => 'openal_listener_get',
  ),
  13 => 
  array (
    0 => 'function.openal-listener-set.php',
    1 => 'openal_listener_set',
  ),
  14 => 
  array (
    0 => 'function.openal-source-create.php',
    1 => 'openal_source_create',
  ),
  15 => 
  array (
    0 => 'function.openal-source-destroy.php',
    1 => 'openal_source_destroy',
  ),
  16 => 
  array (
    0 => 'function.openal-source-get.php',
    1 => 'openal_source_get',
  ),
  17 => 
  array (
    0 => 'function.openal-source-pause.php',
    1 => 'openal_source_pause',
  ),
  18 => 
  array (
    0 => 'function.openal-source-play.php',
    1 => 'openal_source_play',
  ),
  19 => 
  array (
    0 => 'function.openal-source-rewind.php',
    1 => 'openal_source_rewind',
  ),
  20 => 
  array (
    0 => 'function.openal-source-set.php',
    1 => 'openal_source_set',
  ),
  21 => 
  array (
    0 => 'function.openal-source-stop.php',
    1 => 'openal_source_stop',
  ),
  22 => 
  array (
    0 => 'function.openal-stream.php',
    1 => 'openal_stream',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.openal.php',
    1 => 'OpenAL',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.audio.php',
    1 => 'Audio Formats Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);