<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.flush.php',
    1 => 'flush',
  ),
  1 => 
  array (
    0 => 'function.ob-clean.php',
    1 => 'ob_clean',
  ),
  2 => 
  array (
    0 => 'function.ob-end-clean.php',
    1 => 'ob_end_clean',
  ),
  3 => 
  array (
    0 => 'function.ob-end-flush.php',
    1 => 'ob_end_flush',
  ),
  4 => 
  array (
    0 => 'function.ob-flush.php',
    1 => 'ob_flush',
  ),
  5 => 
  array (
    0 => 'function.ob-get-clean.php',
    1 => 'ob_get_clean',
  ),
  6 => 
  array (
    0 => 'function.ob-get-contents.php',
    1 => 'ob_get_contents',
  ),
  7 => 
  array (
    0 => 'function.ob-get-flush.php',
    1 => 'ob_get_flush',
  ),
  8 => 
  array (
    0 => 'function.ob-get-length.php',
    1 => 'ob_get_length',
  ),
  9 => 
  array (
    0 => 'function.ob-get-level.php',
    1 => 'ob_get_level',
  ),
  10 => 
  array (
    0 => 'function.ob-get-status.php',
    1 => 'ob_get_status',
  ),
  11 => 
  array (
    0 => 'function.ob-gzhandler.php',
    1 => 'ob_gzhandler',
  ),
  12 => 
  array (
    0 => 'function.ob-implicit-flush.php',
    1 => 'ob_implicit_flush',
  ),
  13 => 
  array (
    0 => 'function.ob-list-handlers.php',
    1 => 'ob_list_handlers',
  ),
  14 => 
  array (
    0 => 'function.ob-start.php',
    1 => 'ob_start',
  ),
  15 => 
  array (
    0 => 'function.output-add-rewrite-var.php',
    1 => 'output_add_rewrite_var',
  ),
  16 => 
  array (
    0 => 'function.output-reset-rewrite-vars.php',
    1 => 'output_reset_rewrite_vars',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.outcontrol.php',
    1 => 'Output Control',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);