<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.java-last-exception-clear.php',
    1 => 'java_last_exception_clear',
  ),
  1 => 
  array (
    0 => 'function.java-last-exception-get.php',
    1 => 'java_last_exception_get',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.java.php',
    1 => 'Java',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);