<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.xslt-backend-info.php',
    1 => 'xslt_backend_info',
  ),
  1 => 
  array (
    0 => 'function.xslt-backend-name.php',
    1 => 'xslt_backend_name',
  ),
  2 => 
  array (
    0 => 'function.xslt-backend-version.php',
    1 => 'xslt_backend_version',
  ),
  3 => 
  array (
    0 => 'function.xslt-create.php',
    1 => 'xslt_create',
  ),
  4 => 
  array (
    0 => 'function.xslt-errno.php',
    1 => 'xslt_errno',
  ),
  5 => 
  array (
    0 => 'function.xslt-error.php',
    1 => 'xslt_error',
  ),
  6 => 
  array (
    0 => 'function.xslt-free.php',
    1 => 'xslt_free',
  ),
  7 => 
  array (
    0 => 'function.xslt-getopt.php',
    1 => 'xslt_getopt',
  ),
  8 => 
  array (
    0 => 'function.xslt-process.php',
    1 => 'xslt_process',
  ),
  9 => 
  array (
    0 => 'function.xslt-set-base.php',
    1 => 'xslt_set_base',
  ),
  10 => 
  array (
    0 => 'function.xslt-set-encoding.php',
    1 => 'xslt_set_encoding',
  ),
  11 => 
  array (
    0 => 'function.xslt-set-error-handler.php',
    1 => 'xslt_set_error_handler',
  ),
  12 => 
  array (
    0 => 'function.xslt-set-log.php',
    1 => 'xslt_set_log',
  ),
  13 => 
  array (
    0 => 'function.xslt-set-object.php',
    1 => 'xslt_set_object',
  ),
  14 => 
  array (
    0 => 'function.xslt-set-sax-handler.php',
    1 => 'xslt_set_sax_handler',
  ),
  15 => 
  array (
    0 => 'function.xslt-set-sax-handlers.php',
    1 => 'xslt_set_sax_handlers',
  ),
  16 => 
  array (
    0 => 'function.xslt-set-scheme-handler.php',
    1 => 'xslt_set_scheme_handler',
  ),
  17 => 
  array (
    0 => 'function.xslt-set-scheme-handlers.php',
    1 => 'xslt_set_scheme_handlers',
  ),
  18 => 
  array (
    0 => 'function.xslt-setopt.php',
    1 => 'xslt_setopt',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.xslt.php',
    1 => 'XSLT (PHP4)',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);