<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.checkdnsrr.php',
    1 => 'checkdnsrr',
  ),
  1 => 
  array (
    0 => 'function.closelog.php',
    1 => 'closelog',
  ),
  2 => 
  array (
    0 => 'function.define-syslog-variables.php',
    1 => 'define_syslog_variables',
  ),
  3 => 
  array (
    0 => 'function.dns-check-record.php',
    1 => 'dns_check_record',
  ),
  4 => 
  array (
    0 => 'function.dns-get-mx.php',
    1 => 'dns_get_mx',
  ),
  5 => 
  array (
    0 => 'function.dns-get-record.php',
    1 => 'dns_get_record',
  ),
  6 => 
  array (
    0 => 'function.fsockopen.php',
    1 => 'fsockopen',
  ),
  7 => 
  array (
    0 => 'function.gethostbyaddr.php',
    1 => 'gethostbyaddr',
  ),
  8 => 
  array (
    0 => 'function.gethostbyname.php',
    1 => 'gethostbyname',
  ),
  9 => 
  array (
    0 => 'function.gethostbynamel.php',
    1 => 'gethostbynamel',
  ),
  10 => 
  array (
    0 => 'function.gethostname.php',
    1 => 'gethostname',
  ),
  11 => 
  array (
    0 => 'function.getmxrr.php',
    1 => 'getmxrr',
  ),
  12 => 
  array (
    0 => 'function.getprotobyname.php',
    1 => 'getprotobyname',
  ),
  13 => 
  array (
    0 => 'function.getprotobynumber.php',
    1 => 'getprotobynumber',
  ),
  14 => 
  array (
    0 => 'function.getservbyname.php',
    1 => 'getservbyname',
  ),
  15 => 
  array (
    0 => 'function.getservbyport.php',
    1 => 'getservbyport',
  ),
  16 => 
  array (
    0 => 'function.header-remove.php',
    1 => 'header_remove',
  ),
  17 => 
  array (
    0 => 'function.header.php',
    1 => 'header',
  ),
  18 => 
  array (
    0 => 'function.headers-list.php',
    1 => 'headers_list',
  ),
  19 => 
  array (
    0 => 'function.headers-sent.php',
    1 => 'headers_sent',
  ),
  20 => 
  array (
    0 => 'function.inet-ntop.php',
    1 => 'inet_ntop',
  ),
  21 => 
  array (
    0 => 'function.inet-pton.php',
    1 => 'inet_pton',
  ),
  22 => 
  array (
    0 => 'function.ip2long.php',
    1 => 'ip2long',
  ),
  23 => 
  array (
    0 => 'function.long2ip.php',
    1 => 'long2ip',
  ),
  24 => 
  array (
    0 => 'function.openlog.php',
    1 => 'openlog',
  ),
  25 => 
  array (
    0 => 'function.pfsockopen.php',
    1 => 'pfsockopen',
  ),
  26 => 
  array (
    0 => 'function.setcookie.php',
    1 => 'setcookie',
  ),
  27 => 
  array (
    0 => 'function.setrawcookie.php',
    1 => 'setrawcookie',
  ),
  28 => 
  array (
    0 => 'function.socket-get-status.php',
    1 => 'socket_get_status',
  ),
  29 => 
  array (
    0 => 'function.socket-set-blocking.php',
    1 => 'socket_set_blocking',
  ),
  30 => 
  array (
    0 => 'function.socket-set-timeout.php',
    1 => 'socket_set_timeout',
  ),
  31 => 
  array (
    0 => 'function.syslog.php',
    1 => 'syslog',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.network.php',
    1 => 'Network',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);