<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.event_add.php',
    1 => 'event_add',
  ),
  1 => 
  array (
    0 => 'function.event-base-free.php',
    1 => 'event_base_free',
  ),
  2 => 
  array (
    0 => 'function.event-base-loop.php',
    1 => 'event_base_loop',
  ),
  3 => 
  array (
    0 => 'function.event-base-loopbreak.php',
    1 => 'event_base_loopbreak',
  ),
  4 => 
  array (
    0 => 'function.event-base-loopexit.php',
    1 => 'event_base_loopexit',
  ),
  5 => 
  array (
    0 => 'function.event-base-new.php',
    1 => 'event_base_new',
  ),
  6 => 
  array (
    0 => 'function.event-base-priority-init.php',
    1 => 'event_base_priority_init',
  ),
  7 => 
  array (
    0 => 'function.event-base-set.php',
    1 => 'event_base_set',
  ),
  8 => 
  array (
    0 => 'function.event-buffer-base-set.php',
    1 => 'event_buffer_base_set',
  ),
  9 => 
  array (
    0 => 'function.event-buffer-disable.php',
    1 => 'event_buffer_disable',
  ),
  10 => 
  array (
    0 => 'function.event-buffer-enable.php',
    1 => 'event_buffer_enable',
  ),
  11 => 
  array (
    0 => 'function.event-buffer-fd-set.php',
    1 => 'event_buffer_fd_set',
  ),
  12 => 
  array (
    0 => 'function.event-buffer-free.php',
    1 => 'event_buffer_free',
  ),
  13 => 
  array (
    0 => 'function.event-buffer-new.php',
    1 => 'event_buffer_new',
  ),
  14 => 
  array (
    0 => 'function.event-buffer-priority-set.php',
    1 => 'event_buffer_priority_set',
  ),
  15 => 
  array (
    0 => 'function.event-buffer-read.php',
    1 => 'event_buffer_read',
  ),
  16 => 
  array (
    0 => 'function.event-buffer-set-callback.php',
    1 => 'event_buffer_set_callback',
  ),
  17 => 
  array (
    0 => 'function.event-buffer-timeout-set.php',
    1 => 'event_buffer_timeout_set',
  ),
  18 => 
  array (
    0 => 'function.event-buffer-watermark-set.php',
    1 => 'event_buffer_watermark_set',
  ),
  19 => 
  array (
    0 => 'function.event-buffer-write.php',
    1 => 'event_buffer_write',
  ),
  20 => 
  array (
    0 => 'function.event-del.php',
    1 => 'event_del',
  ),
  21 => 
  array (
    0 => 'function.event-free.php',
    1 => 'event_free',
  ),
  22 => 
  array (
    0 => 'function.event-new.php',
    1 => 'event_new',
  ),
  23 => 
  array (
    0 => 'function.event-set.php',
    1 => 'event_set',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.libevent.php',
    1 => 'Libevent',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);