<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.qdom-error.php',
    1 => 'qdom_error',
  ),
  1 => 
  array (
    0 => 'function.qdom-tree.php',
    1 => 'qdom_tree',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.qtdom.php',
    1 => 'qtdom',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);