<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.sdo-das-relational-applychanges.php',
    1 => 'SDO_DAS_Relational::applyChanges',
  ),
  1 => 
  array (
    0 => 'function.sdo-das-relational-construct.php',
    1 => 'SDO_DAS_Relational::__construct',
  ),
  2 => 
  array (
    0 => 'function.sdo-das-relational-createrootdataobject.php',
    1 => 'SDO_DAS_Relational::createRootDataObject',
  ),
  3 => 
  array (
    0 => 'function.sdo-das-relational-executepreparedquery.php',
    1 => 'SDO_DAS_Relational::executePreparedQuery',
  ),
  4 => 
  array (
    0 => 'function.sdo-das-relational-executequery.php',
    1 => 'SDO_DAS_Relational::executeQuery',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sdodasrel.php',
    1 => 'SDO-DAS-Relational',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);