<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.abs.php',
    1 => 'abs',
  ),
  1 => 
  array (
    0 => 'function.acos.php',
    1 => 'acos',
  ),
  2 => 
  array (
    0 => 'function.acosh.php',
    1 => 'acosh',
  ),
  3 => 
  array (
    0 => 'function.asin.php',
    1 => 'asin',
  ),
  4 => 
  array (
    0 => 'function.asinh.php',
    1 => 'asinh',
  ),
  5 => 
  array (
    0 => 'function.atan2.php',
    1 => 'atan2',
  ),
  6 => 
  array (
    0 => 'function.atan.php',
    1 => 'atan',
  ),
  7 => 
  array (
    0 => 'function.atanh.php',
    1 => 'atanh',
  ),
  8 => 
  array (
    0 => 'function.base-convert.php',
    1 => 'base_convert',
  ),
  9 => 
  array (
    0 => 'function.bindec.php',
    1 => 'bindec',
  ),
  10 => 
  array (
    0 => 'function.ceil.php',
    1 => 'ceil',
  ),
  11 => 
  array (
    0 => 'function.cos.php',
    1 => 'cos',
  ),
  12 => 
  array (
    0 => 'function.cosh.php',
    1 => 'cosh',
  ),
  13 => 
  array (
    0 => 'function.decbin.php',
    1 => 'decbin',
  ),
  14 => 
  array (
    0 => 'function.dechex.php',
    1 => 'dechex',
  ),
  15 => 
  array (
    0 => 'function.decoct.php',
    1 => 'decoct',
  ),
  16 => 
  array (
    0 => 'function.deg2rad.php',
    1 => 'deg2rad',
  ),
  17 => 
  array (
    0 => 'function.exp.php',
    1 => 'exp',
  ),
  18 => 
  array (
    0 => 'function.expm1.php',
    1 => 'expm1',
  ),
  19 => 
  array (
    0 => 'function.floor.php',
    1 => 'floor',
  ),
  20 => 
  array (
    0 => 'function.fmod.php',
    1 => 'fmod',
  ),
  21 => 
  array (
    0 => 'function.getrandmax.php',
    1 => 'getrandmax',
  ),
  22 => 
  array (
    0 => 'function.hexdec.php',
    1 => 'hexdec',
  ),
  23 => 
  array (
    0 => 'function.hypot.php',
    1 => 'hypot',
  ),
  24 => 
  array (
    0 => 'function.is-finite.php',
    1 => 'is_finite',
  ),
  25 => 
  array (
    0 => 'function.is-infinite.php',
    1 => 'is_infinite',
  ),
  26 => 
  array (
    0 => 'function.is-nan.php',
    1 => 'is_nan',
  ),
  27 => 
  array (
    0 => 'function.lcg-value.php',
    1 => 'lcg_value',
  ),
  28 => 
  array (
    0 => 'function.log10.php',
    1 => 'log10',
  ),
  29 => 
  array (
    0 => 'function.log1p.php',
    1 => 'log1p',
  ),
  30 => 
  array (
    0 => 'function.log.php',
    1 => 'log',
  ),
  31 => 
  array (
    0 => 'function.max.php',
    1 => 'max',
  ),
  32 => 
  array (
    0 => 'function.min.php',
    1 => 'min',
  ),
  33 => 
  array (
    0 => 'function.mt-getrandmax.php',
    1 => 'mt_getrandmax',
  ),
  34 => 
  array (
    0 => 'function.mt-rand.php',
    1 => 'mt_rand',
  ),
  35 => 
  array (
    0 => 'function.mt-srand.php',
    1 => 'mt_srand',
  ),
  36 => 
  array (
    0 => 'function.octdec.php',
    1 => 'octdec',
  ),
  37 => 
  array (
    0 => 'function.pi.php',
    1 => 'pi',
  ),
  38 => 
  array (
    0 => 'function.pow.php',
    1 => 'pow',
  ),
  39 => 
  array (
    0 => 'function.rad2deg.php',
    1 => 'rad2deg',
  ),
  40 => 
  array (
    0 => 'function.rand.php',
    1 => 'rand',
  ),
  41 => 
  array (
    0 => 'function.round.php',
    1 => 'round',
  ),
  42 => 
  array (
    0 => 'function.sin.php',
    1 => 'sin',
  ),
  43 => 
  array (
    0 => 'function.sinh.php',
    1 => 'sinh',
  ),
  44 => 
  array (
    0 => 'function.sqrt.php',
    1 => 'sqrt',
  ),
  45 => 
  array (
    0 => 'function.srand.php',
    1 => 'srand',
  ),
  46 => 
  array (
    0 => 'function.tan.php',
    1 => 'tan',
  ),
  47 => 
  array (
    0 => 'function.tanh.php',
    1 => 'tanh',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.math.php',
    1 => 'Math',
  ),
  1 => 
  array (
    0 => 'refs.math.php',
    1 => 'Mathematical Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);