<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.xmlrpc-decode-request.php',
    1 => 'xmlrpc_decode_request',
  ),
  1 => 
  array (
    0 => 'function.xmlrpc-decode.php',
    1 => 'xmlrpc_decode',
  ),
  2 => 
  array (
    0 => 'function.xmlrpc-encode-request.php',
    1 => 'xmlrpc_encode_request',
  ),
  3 => 
  array (
    0 => 'function.xmlrpc-encode.php',
    1 => 'xmlrpc_encode',
  ),
  4 => 
  array (
    0 => 'function.xmlrpc-get-type.php',
    1 => 'xmlrpc_get_type',
  ),
  5 => 
  array (
    0 => 'function.xmlrpc-is-fault.php',
    1 => 'xmlrpc_is_fault',
  ),
  6 => 
  array (
    0 => 'function.xmlrpc-parse-method-descriptions.php',
    1 => 'xmlrpc_parse_method_descriptions',
  ),
  7 => 
  array (
    0 => 'function.xmlrpc-server-add-introspection-data.php',
    1 => 'xmlrpc_server_add_introspection_data',
  ),
  8 => 
  array (
    0 => 'function.xmlrpc-server-call-method.php',
    1 => 'xmlrpc_server_call_method',
  ),
  9 => 
  array (
    0 => 'function.xmlrpc-server-create.php',
    1 => 'xmlrpc_server_create',
  ),
  10 => 
  array (
    0 => 'function.xmlrpc-server-destroy.php',
    1 => 'xmlrpc_server_destroy',
  ),
  11 => 
  array (
    0 => 'function.xmlrpc-server-register-introspection-callback.php',
    1 => 'xmlrpc_server_register_introspection_callback',
  ),
  12 => 
  array (
    0 => 'function.xmlrpc-server-register-method.php',
    1 => 'xmlrpc_server_register_method',
  ),
  13 => 
  array (
    0 => 'function.xmlrpc-set-type.php',
    1 => 'xmlrpc_set_type',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.xmlrpc.php',
    1 => 'XML-RPC',
  ),
  1 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);