<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.yp-all.php',
    1 => 'yp_all',
  ),
  1 => 
  array (
    0 => 'function.yp-cat.php',
    1 => 'yp_cat',
  ),
  2 => 
  array (
    0 => 'function.yp-err-string.php',
    1 => 'yp_err_string',
  ),
  3 => 
  array (
    0 => 'function.yp-errno.php',
    1 => 'yp_errno',
  ),
  4 => 
  array (
    0 => 'function.yp-first.php',
    1 => 'yp_first',
  ),
  5 => 
  array (
    0 => 'function.yp-get-default-domain.php',
    1 => 'yp_get_default_domain',
  ),
  6 => 
  array (
    0 => 'function.yp-master.php',
    1 => 'yp_master',
  ),
  7 => 
  array (
    0 => 'function.yp-match.php',
    1 => 'yp_match',
  ),
  8 => 
  array (
    0 => 'function.yp-next.php',
    1 => 'yp_next',
  ),
  9 => 
  array (
    0 => 'function.yp-order.php',
    1 => 'yp_order',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.nis.php',
    1 => 'YP/NIS',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);