<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.dio-close.php',
    1 => 'dio_close',
  ),
  1 => 
  array (
    0 => 'function.dio-fcntl.php',
    1 => 'dio_fcntl',
  ),
  2 => 
  array (
    0 => 'function.dio-open.php',
    1 => 'dio_open',
  ),
  3 => 
  array (
    0 => 'function.dio-read.php',
    1 => 'dio_read',
  ),
  4 => 
  array (
    0 => 'function.dio-seek.php',
    1 => 'dio_seek',
  ),
  5 => 
  array (
    0 => 'function.dio-stat.php',
    1 => 'dio_stat',
  ),
  6 => 
  array (
    0 => 'function.dio-tcsetattr.php',
    1 => 'dio_tcsetattr',
  ),
  7 => 
  array (
    0 => 'function.dio-truncate.php',
    1 => 'dio_truncate',
  ),
  8 => 
  array (
    0 => 'function.dio-write.php',
    1 => 'dio_write',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dio.php',
    1 => 'Direct IO',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.file.php',
    1 => 'File System Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);