<?php
$TOC = array (
  0 => 
  array (
    0 => 'ref.pdo-oci.connection.php',
    1 => 'PDO_OCI DSN',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'pdo.drivers.php',
    1 => 'PDO Drivers',
  ),
  1 => 
  array (
    0 => 'book.pdo.php',
    1 => 'PDO',
  ),
  2 => 
  array (
    0 => 'refs.database.abstract.php',
    1 => 'Abstraction Layers',
  ),
  3 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  4 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  5 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);