<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.dbase-add-record.php',
    1 => 'dbase_add_record',
  ),
  1 => 
  array (
    0 => 'function.dbase-close.php',
    1 => 'dbase_close',
  ),
  2 => 
  array (
    0 => 'function.dbase-create.php',
    1 => 'dbase_create',
  ),
  3 => 
  array (
    0 => 'function.dbase-delete-record.php',
    1 => 'dbase_delete_record',
  ),
  4 => 
  array (
    0 => 'function.dbase-get-header-info.php',
    1 => 'dbase_get_header_info',
  ),
  5 => 
  array (
    0 => 'function.dbase-get-record-with-names.php',
    1 => 'dbase_get_record_with_names',
  ),
  6 => 
  array (
    0 => 'function.dbase-get-record.php',
    1 => 'dbase_get_record',
  ),
  7 => 
  array (
    0 => 'function.dbase-numfields.php',
    1 => 'dbase_numfields',
  ),
  8 => 
  array (
    0 => 'function.dbase-numrecords.php',
    1 => 'dbase_numrecords',
  ),
  9 => 
  array (
    0 => 'function.dbase-open.php',
    1 => 'dbase_open',
  ),
  10 => 
  array (
    0 => 'function.dbase-pack.php',
    1 => 'dbase_pack',
  ),
  11 => 
  array (
    0 => 'function.dbase-replace-record.php',
    1 => 'dbase_replace_record',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.dbase.php',
    1 => 'dBase',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);