<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.samconnection-commit.php',
    1 => 'SAMConnection-&gt;commit',
  ),
  1 => 
  array (
    0 => 'function.samconnection-connect.php',
    1 => 'SAMConnection-&gt;connect',
  ),
  2 => 
  array (
    0 => 'function.samconnection-constructor.php',
    1 => 'SAMConnection-&gt;__construct',
  ),
  3 => 
  array (
    0 => 'function.samconnection-disconnect.php',
    1 => 'SAMConnection-&gt;disconnect',
  ),
  4 => 
  array (
    0 => 'function.samconnection-errno.php',
    1 => 'SAMConnection-&gt;errno',
  ),
  5 => 
  array (
    0 => 'function.samconnection-error.php',
    1 => 'SAMConnection-&gt;error',
  ),
  6 => 
  array (
    0 => 'function.samconnection-isconnected.php',
    1 => 'SAMConnection-&gt;isConnected',
  ),
  7 => 
  array (
    0 => 'function.samconnection-peek.php',
    1 => 'SAMConnection-&gt;peek',
  ),
  8 => 
  array (
    0 => 'function.samconnection-peekall.php',
    1 => 'SAMConnection-&gt;peekAll',
  ),
  9 => 
  array (
    0 => 'function.samconnection-receive.php',
    1 => 'SAMConnection-&gt;receive',
  ),
  10 => 
  array (
    0 => 'function.samconnection-remove.php',
    1 => 'SAMConnection-&gt;remove',
  ),
  11 => 
  array (
    0 => 'function.samconnection-rollback.php',
    1 => 'SAMConnection-&gt;rollback',
  ),
  12 => 
  array (
    0 => 'function.samconnection-send.php',
    1 => 'SAMConnection-&gt;send',
  ),
  13 => 
  array (
    0 => 'function.samconnection-setDebug.php',
    1 => 'SAMConnection::setDebug',
  ),
  14 => 
  array (
    0 => 'function.samconnection-subscribe.php',
    1 => 'SAMConnection-&gt;subscribe',
  ),
  15 => 
  array (
    0 => 'function.samconnection-unsubscribe.php',
    1 => 'SAMConnection-&gt;unsubscribe',
  ),
  16 => 
  array (
    0 => 'function.sammessage-body.php',
    1 => 'SAMMessage-&gt;body',
  ),
  17 => 
  array (
    0 => 'function.sammessage-constructor.php',
    1 => 'SAMMessage-&gt;__construct',
  ),
  18 => 
  array (
    0 => 'function.sammessage-header.php',
    1 => 'SAMMessage-&gt;header',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sam.php',
    1 => 'SAM',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);