<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.xmlwriter-end-attribute.php',
    1 => 'XMLWriter::endAttribute',
  ),
  1 => 
  array (
    0 => 'function.xmlwriter-end-cdata.php',
    1 => 'XMLWriter::endCData',
  ),
  2 => 
  array (
    0 => 'function.xmlwriter-end-comment.php',
    1 => 'XMLWriter::endComment',
  ),
  3 => 
  array (
    0 => 'function.xmlwriter-end-document.php',
    1 => 'XMLWriter::endDocument',
  ),
  4 => 
  array (
    0 => 'function.xmlwriter-end-dtd-attlist.php',
    1 => 'XMLWriter::endDTDAttlist',
  ),
  5 => 
  array (
    0 => 'function.xmlwriter-end-dtd-element.php',
    1 => 'XMLWriter::endDTDElement',
  ),
  6 => 
  array (
    0 => 'function.xmlwriter-end-dtd-entity.php',
    1 => 'XMLWriter::endDTDEntity',
  ),
  7 => 
  array (
    0 => 'function.xmlwriter-end-dtd.php',
    1 => 'XMLWriter::endDTD',
  ),
  8 => 
  array (
    0 => 'function.xmlwriter-end-element.php',
    1 => 'XMLWriter::endElement',
  ),
  9 => 
  array (
    0 => 'function.xmlwriter-end-pi.php',
    1 => 'XMLWriter::endPI',
  ),
  10 => 
  array (
    0 => 'function.xmlwriter-flush.php',
    1 => 'XMLWriter::flush',
  ),
  11 => 
  array (
    0 => 'function.xmlwriter-full-end-element.php',
    1 => 'XMLWriter::fullEndElement',
  ),
  12 => 
  array (
    0 => 'function.xmlwriter-open-memory.php',
    1 => 'XMLWriter::openMemory',
  ),
  13 => 
  array (
    0 => 'function.xmlwriter-open-uri.php',
    1 => 'XMLWriter::openURI',
  ),
  14 => 
  array (
    0 => 'function.xmlwriter-output-memory.php',
    1 => 'XMLWriter::outputMemory',
  ),
  15 => 
  array (
    0 => 'function.xmlwriter-set-indent-string.php',
    1 => 'XMLWriter::setIndentString',
  ),
  16 => 
  array (
    0 => 'function.xmlwriter-set-indent.php',
    1 => 'XMLWriter::setIndent',
  ),
  17 => 
  array (
    0 => 'function.xmlwriter-start-attribute-ns.php',
    1 => 'XMLWriter::startAttributeNS',
  ),
  18 => 
  array (
    0 => 'function.xmlwriter-start-attribute.php',
    1 => 'XMLWriter::startAttribute',
  ),
  19 => 
  array (
    0 => 'function.xmlwriter-start-cdata.php',
    1 => 'XMLWriter::startCData',
  ),
  20 => 
  array (
    0 => 'function.xmlwriter-start-comment.php',
    1 => 'XMLWriter::startComment',
  ),
  21 => 
  array (
    0 => 'function.xmlwriter-start-document.php',
    1 => 'XMLWriter::startDocument',
  ),
  22 => 
  array (
    0 => 'function.xmlwriter-start-dtd-attlist.php',
    1 => 'XMLWriter::startDTDAttlist',
  ),
  23 => 
  array (
    0 => 'function.xmlwriter-start-dtd-element.php',
    1 => 'XMLWriter::startDTDElement',
  ),
  24 => 
  array (
    0 => 'function.xmlwriter-start-dtd-entity.php',
    1 => 'XMLWriter::startDTDEntity',
  ),
  25 => 
  array (
    0 => 'function.xmlwriter-start-dtd.php',
    1 => 'XMLWriter::startDTD',
  ),
  26 => 
  array (
    0 => 'function.xmlwriter-start-element-ns.php',
    1 => 'XMLWriter::startElementNS',
  ),
  27 => 
  array (
    0 => 'function.xmlwriter-start-element.php',
    1 => 'XMLWriter::startElement',
  ),
  28 => 
  array (
    0 => 'function.xmlwriter-start-pi.php',
    1 => 'XMLWriter::startPI',
  ),
  29 => 
  array (
    0 => 'function.xmlwriter-text.php',
    1 => 'XMLWriter::text',
  ),
  30 => 
  array (
    0 => 'function.xmlwriter-write-attribute-ns.php',
    1 => 'XMLWriter::writeAttributeNS',
  ),
  31 => 
  array (
    0 => 'function.xmlwriter-write-attribute.php',
    1 => 'XMLWriter::writeAttribute',
  ),
  32 => 
  array (
    0 => 'function.xmlwriter-write-cdata.php',
    1 => 'XMLWriter::writeCData',
  ),
  33 => 
  array (
    0 => 'function.xmlwriter-write-comment.php',
    1 => 'XMLWriter::writeComment',
  ),
  34 => 
  array (
    0 => 'function.xmlwriter-write-dtd-attlist.php',
    1 => 'XMLWriter::writeDTDAttlist',
  ),
  35 => 
  array (
    0 => 'function.xmlwriter-write-dtd-element.php',
    1 => 'XMLWriter::writeDTDElement',
  ),
  36 => 
  array (
    0 => 'function.xmlwriter-write-dtd-entity.php',
    1 => 'XMLWriter::writeDTDEntity',
  ),
  37 => 
  array (
    0 => 'function.xmlwriter-write-dtd.php',
    1 => 'XMLWriter::writeDTD',
  ),
  38 => 
  array (
    0 => 'function.xmlwriter-write-element-ns.php',
    1 => 'XMLWriter::writeElementNS',
  ),
  39 => 
  array (
    0 => 'function.xmlwriter-write-element.php',
    1 => 'XMLWriter::writeElement',
  ),
  40 => 
  array (
    0 => 'function.xmlwriter-write-pi.php',
    1 => 'XMLWriter::writePI',
  ),
  41 => 
  array (
    0 => 'function.xmlwriter-write-raw.php',
    1 => 'XMLWriter::writeRaw',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.xmlwriter.php',
    1 => 'XMLWriter',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);