<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.ibase-add-user.php',
    1 => 'ibase_add_user',
  ),
  1 => 
  array (
    0 => 'function.ibase-affected-rows.php',
    1 => 'ibase_affected_rows',
  ),
  2 => 
  array (
    0 => 'function.ibase-backup.php',
    1 => 'ibase_backup',
  ),
  3 => 
  array (
    0 => 'function.ibase-blob-add.php',
    1 => 'ibase_blob_add',
  ),
  4 => 
  array (
    0 => 'function.ibase-blob-cancel.php',
    1 => 'ibase_blob_cancel',
  ),
  5 => 
  array (
    0 => 'function.ibase-blob-close.php',
    1 => 'ibase_blob_close',
  ),
  6 => 
  array (
    0 => 'function.ibase-blob-create.php',
    1 => 'ibase_blob_create',
  ),
  7 => 
  array (
    0 => 'function.ibase-blob-echo.php',
    1 => 'ibase_blob_echo',
  ),
  8 => 
  array (
    0 => 'function.ibase-blob-get.php',
    1 => 'ibase_blob_get',
  ),
  9 => 
  array (
    0 => 'function.ibase-blob-import.php',
    1 => 'ibase_blob_import',
  ),
  10 => 
  array (
    0 => 'function.ibase-blob-info.php',
    1 => 'ibase_blob_info',
  ),
  11 => 
  array (
    0 => 'function.ibase-blob-open.php',
    1 => 'ibase_blob_open',
  ),
  12 => 
  array (
    0 => 'function.ibase-close.php',
    1 => 'ibase_close',
  ),
  13 => 
  array (
    0 => 'function.ibase-commit-ret.php',
    1 => 'ibase_commit_ret',
  ),
  14 => 
  array (
    0 => 'function.ibase-commit.php',
    1 => 'ibase_commit',
  ),
  15 => 
  array (
    0 => 'function.ibase-connect.php',
    1 => 'ibase_connect',
  ),
  16 => 
  array (
    0 => 'function.ibase-db-info.php',
    1 => 'ibase_db_info',
  ),
  17 => 
  array (
    0 => 'function.ibase-delete-user.php',
    1 => 'ibase_delete_user',
  ),
  18 => 
  array (
    0 => 'function.ibase-drop-db.php',
    1 => 'ibase_drop_db',
  ),
  19 => 
  array (
    0 => 'function.ibase-errcode.php',
    1 => 'ibase_errcode',
  ),
  20 => 
  array (
    0 => 'function.ibase-errmsg.php',
    1 => 'ibase_errmsg',
  ),
  21 => 
  array (
    0 => 'function.ibase-execute.php',
    1 => 'ibase_execute',
  ),
  22 => 
  array (
    0 => 'function.ibase-fetch-assoc.php',
    1 => 'ibase_fetch_assoc',
  ),
  23 => 
  array (
    0 => 'function.ibase-fetch-object.php',
    1 => 'ibase_fetch_object',
  ),
  24 => 
  array (
    0 => 'function.ibase-fetch-row.php',
    1 => 'ibase_fetch_row',
  ),
  25 => 
  array (
    0 => 'function.ibase-field-info.php',
    1 => 'ibase_field_info',
  ),
  26 => 
  array (
    0 => 'function.ibase-free-event-handler.php',
    1 => 'ibase_free_event_handler',
  ),
  27 => 
  array (
    0 => 'function.ibase-free-query.php',
    1 => 'ibase_free_query',
  ),
  28 => 
  array (
    0 => 'function.ibase-free-result.php',
    1 => 'ibase_free_result',
  ),
  29 => 
  array (
    0 => 'function.ibase-gen-id.php',
    1 => 'ibase_gen_id',
  ),
  30 => 
  array (
    0 => 'function.ibase-maintain-db.php',
    1 => 'ibase_maintain_db',
  ),
  31 => 
  array (
    0 => 'function.ibase-modify-user.php',
    1 => 'ibase_modify_user',
  ),
  32 => 
  array (
    0 => 'function.ibase-name-result.php',
    1 => 'ibase_name_result',
  ),
  33 => 
  array (
    0 => 'function.ibase-num-fields.php',
    1 => 'ibase_num_fields',
  ),
  34 => 
  array (
    0 => 'function.ibase-num-params.php',
    1 => 'ibase_num_params',
  ),
  35 => 
  array (
    0 => 'function.ibase-param-info.php',
    1 => 'ibase_param_info',
  ),
  36 => 
  array (
    0 => 'function.ibase-pconnect.php',
    1 => 'ibase_pconnect',
  ),
  37 => 
  array (
    0 => 'function.ibase-prepare.php',
    1 => 'ibase_prepare',
  ),
  38 => 
  array (
    0 => 'function.ibase-query.php',
    1 => 'ibase_query',
  ),
  39 => 
  array (
    0 => 'function.ibase-restore.php',
    1 => 'ibase_restore',
  ),
  40 => 
  array (
    0 => 'function.ibase-rollback-ret.php',
    1 => 'ibase_rollback_ret',
  ),
  41 => 
  array (
    0 => 'function.ibase-rollback.php',
    1 => 'ibase_rollback',
  ),
  42 => 
  array (
    0 => 'function.ibase-server-info.php',
    1 => 'ibase_server_info',
  ),
  43 => 
  array (
    0 => 'function.ibase-service-attach.php',
    1 => 'ibase_service_attach',
  ),
  44 => 
  array (
    0 => 'function.ibase-service-detach.php',
    1 => 'ibase_service_detach',
  ),
  45 => 
  array (
    0 => 'function.ibase-set-event-handler.php',
    1 => 'ibase_set_event_handler',
  ),
  46 => 
  array (
    0 => 'function.ibase-timefmt.php',
    1 => 'ibase_timefmt',
  ),
  47 => 
  array (
    0 => 'function.ibase-trans.php',
    1 => 'ibase_trans',
  ),
  48 => 
  array (
    0 => 'function.ibase-wait-event.php',
    1 => 'ibase_wait_event',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ibase.php',
    1 => 'Firebird/InterBase',
  ),
  1 => 
  array (
    0 => 'refs.database.vendors.php',
    1 => 'Vendor Specific Database Extensions',
  ),
  2 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);