<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.preg-filter.php',
    1 => 'preg_filter',
  ),
  1 => 
  array (
    0 => 'function.preg-grep.php',
    1 => 'preg_grep',
  ),
  2 => 
  array (
    0 => 'function.preg-last-error.php',
    1 => 'preg_last_error',
  ),
  3 => 
  array (
    0 => 'function.preg-match-all.php',
    1 => 'preg_match_all',
  ),
  4 => 
  array (
    0 => 'function.preg-match.php',
    1 => 'preg_match',
  ),
  5 => 
  array (
    0 => 'function.preg-quote.php',
    1 => 'preg_quote',
  ),
  6 => 
  array (
    0 => 'function.preg-replace-callback.php',
    1 => 'preg_replace_callback',
  ),
  7 => 
  array (
    0 => 'function.preg-replace.php',
    1 => 'preg_replace',
  ),
  8 => 
  array (
    0 => 'function.preg-split.php',
    1 => 'preg_split',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.pcre.php',
    1 => 'PCRE',
  ),
  1 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'Text Processing',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);