<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.rar-wrapper-cache-stats.php',
    1 => 'rar_wrapper_cache_stats',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.rar.php',
    1 => 'Rar',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);