<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.gnupg-adddecryptkey.php',
    1 => 'gnupg_adddecryptkey',
  ),
  1 => 
  array (
    0 => 'function.gnupg-addencryptkey.php',
    1 => 'gnupg_addencryptkey',
  ),
  2 => 
  array (
    0 => 'function.gnupg-addsignkey.php',
    1 => 'gnupg_addsignkey',
  ),
  3 => 
  array (
    0 => 'function.gnupg-cleardecryptkeys.php',
    1 => 'gnupg_cleardecryptkeys',
  ),
  4 => 
  array (
    0 => 'function.gnupg-clearencryptkeys.php',
    1 => 'gnupg_clearencryptkeys',
  ),
  5 => 
  array (
    0 => 'function.gnupg-clearsignkeys.php',
    1 => 'gnupg_clearsignkeys',
  ),
  6 => 
  array (
    0 => 'function.gnupg-decrypt.php',
    1 => 'gnupg_decrypt',
  ),
  7 => 
  array (
    0 => 'function.gnupg-decryptverify.php',
    1 => 'gnupg_decryptverify',
  ),
  8 => 
  array (
    0 => 'function.gnupg-encrypt.php',
    1 => 'gnupg_encrypt',
  ),
  9 => 
  array (
    0 => 'function.gnupg-encryptsign.php',
    1 => 'gnupg_encryptsign',
  ),
  10 => 
  array (
    0 => 'function.gnupg-export.php',
    1 => 'gnupg_export',
  ),
  11 => 
  array (
    0 => 'function.gnupg-geterror.php',
    1 => 'gnupg_geterror',
  ),
  12 => 
  array (
    0 => 'function.gnupg-getprotocol.php',
    1 => 'gnupg_getprotocol',
  ),
  13 => 
  array (
    0 => 'function.gnupg-import.php',
    1 => 'gnupg_import',
  ),
  14 => 
  array (
    0 => 'function.gnupg-init.php',
    1 => 'gnupg_init',
  ),
  15 => 
  array (
    0 => 'function.gnupg-keyinfo.php',
    1 => 'gnupg_keyinfo',
  ),
  16 => 
  array (
    0 => 'function.gnupg-setarmor.php',
    1 => 'gnupg_setarmor',
  ),
  17 => 
  array (
    0 => 'function.gnupg-seterrormode.php',
    1 => 'gnupg_seterrormode',
  ),
  18 => 
  array (
    0 => 'function.gnupg-setsignmode.php',
    1 => 'gnupg_setsignmode',
  ),
  19 => 
  array (
    0 => 'function.gnupg-sign.php',
    1 => 'gnupg_sign',
  ),
  20 => 
  array (
    0 => 'function.gnupg-verify.php',
    1 => 'gnupg_verify',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.gnupg.php',
    1 => 'GnuPG',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);