<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.oauth_get_sbs.php',
    1 => 'oauth_get_sbs',
  ),
  1 => 
  array (
    0 => 'function.oauth-urlencode.php',
    1 => 'oauth_urlencode',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.oauth.php',
    1 => 'OAuth',
  ),
  1 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);