<?php
$TOC = array (
  0 => 
  array (
    0 => 'function.apc-add.php',
    1 => 'apc_add',
  ),
  1 => 
  array (
    0 => 'function.apc-bin-dump.php',
    1 => 'apc_bin_dump',
  ),
  2 => 
  array (
    0 => 'function.apc-bin-dumpfile.php',
    1 => 'apc_bin_dumpfile',
  ),
  3 => 
  array (
    0 => 'function.apc-bin-load.php',
    1 => 'apc_bin_load',
  ),
  4 => 
  array (
    0 => 'function.apc-bin-loadfile.php',
    1 => 'apc_bin_loadfile',
  ),
  5 => 
  array (
    0 => 'function.apc-cache-info.php',
    1 => 'apc_cache_info',
  ),
  6 => 
  array (
    0 => 'function.apc-cas.php',
    1 => 'apc_cas',
  ),
  7 => 
  array (
    0 => 'function.apc-clear-cache.php',
    1 => 'apc_clear_cache',
  ),
  8 => 
  array (
    0 => 'function.apc-compile-file.php',
    1 => 'apc_compile_file',
  ),
  9 => 
  array (
    0 => 'function.apc-dec.php',
    1 => 'apc_dec',
  ),
  10 => 
  array (
    0 => 'function.apc-define-constants.php',
    1 => 'apc_define_constants',
  ),
  11 => 
  array (
    0 => 'function.apc-delete-file.php',
    1 => 'apc_delete_file',
  ),
  12 => 
  array (
    0 => 'function.apc-delete.php',
    1 => 'apc_delete',
  ),
  13 => 
  array (
    0 => 'function.apc-exists.php',
    1 => 'apc_exists',
  ),
  14 => 
  array (
    0 => 'function.apc-fetch.php',
    1 => 'apc_fetch',
  ),
  15 => 
  array (
    0 => 'function.apc-inc.php',
    1 => 'apc_inc',
  ),
  16 => 
  array (
    0 => 'function.apc-load-constants.php',
    1 => 'apc_load_constants',
  ),
  17 => 
  array (
    0 => 'function.apc-sma-info.php',
    1 => 'apc_sma_info',
  ),
  18 => 
  array (
    0 => 'function.apc-store.php',
    1 => 'apc_store',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.apc.php',
    1 => 'APC',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);