<?php
$TOC = array (
  0 => 
  array (
    0 => 'regexp.introduction.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'regexp.reference.delimiters.php',
    1 => 'Delimiters',
  ),
  2 => 
  array (
    0 => 'regexp.reference.meta.php',
    1 => 'Meta-characters',
  ),
  3 => 
  array (
    0 => 'regexp.reference.escape.php',
    1 => 'Escape sequences',
  ),
  4 => 
  array (
    0 => 'regexp.reference.unicode.php',
    1 => 'Unicode character properties',
  ),
  5 => 
  array (
    0 => 'regexp.reference.anchors.php',
    1 => 'Anchors',
  ),
  6 => 
  array (
    0 => 'regexp.reference.dot.php',
    1 => 'Dot',
  ),
  7 => 
  array (
    0 => 'regexp.reference.character-classes.php',
    1 => 'Character classes',
  ),
  8 => 
  array (
    0 => 'regexp.reference.alternation.php',
    1 => 'Alternation',
  ),
  9 => 
  array (
    0 => 'regexp.reference.internal-options.php',
    1 => 'Internal option setting',
  ),
  10 => 
  array (
    0 => 'regexp.reference.subpatterns.php',
    1 => 'Subpatterns',
  ),
  11 => 
  array (
    0 => 'regexp.reference.repetition.php',
    1 => 'Repetition',
  ),
  12 => 
  array (
    0 => 'regexp.reference.back-references.php',
    1 => 'Back references',
  ),
  13 => 
  array (
    0 => 'regexp.reference.assertions.php',
    1 => 'Assertions',
  ),
  14 => 
  array (
    0 => 'regexp.reference.onlyonce.php',
    1 => 'Once-only subpatterns',
  ),
  15 => 
  array (
    0 => 'regexp.reference.conditional.php',
    1 => 'Conditional subpatterns',
  ),
  16 => 
  array (
    0 => 'regexp.reference.comments.php',
    1 => 'Comments',
  ),
  17 => 
  array (
    0 => 'regexp.reference.recursive.php',
    1 => 'Recursive patterns',
  ),
  18 => 
  array (
    0 => 'regexp.reference.performances.php',
    1 => 'Performances',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'pcre.pattern.php',
    1 => 'PCRE Patterns',
  ),
  1 => 
  array (
    0 => 'book.pcre.php',
    1 => 'PCRE',
  ),
  2 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'Text Processing',
  ),
  3 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  4 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);