<?php
$TOC = array (
  0 => 
  array (
    0 => 'reflection.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'reflection.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'reflection.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'reflection.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.reflection.php',
    1 => 'Reflection',
  ),
  1 => 
  array (
    0 => 'refs.basic.vartype.php',
    1 => 'Variable and Type Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);