<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.id3.php',
    1 => 'ID3',
  ),
  1 => 
  array (
    0 => 'book.ktaglib.php',
    1 => 'KTaglib',
  ),
  2 => 
  array (
    0 => 'book.oggvorbis.php',
    1 => 'oggvorbis',
  ),
  3 => 
  array (
    0 => 'book.openal.php',
    1 => 'OpenAL',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);