<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.dom.php',
    1 => 'DOM',
  ),
  1 => 
  array (
    0 => 'book.domxml.php',
    1 => 'DOM XML (PHP 4)',
  ),
  2 => 
  array (
    0 => 'book.libxml.php',
    1 => 'libxml',
  ),
  3 => 
  array (
    0 => 'book.qtdom.php',
    1 => 'qtdom',
  ),
  4 => 
  array (
    0 => 'book.sdo.php',
    1 => 'SDO',
  ),
  5 => 
  array (
    0 => 'book.sdodasrel.php',
    1 => 'SDO-DAS-Relational',
  ),
  6 => 
  array (
    0 => 'book.sdo-das-xml.php',
    1 => 'SDO DAS XML',
  ),
  7 => 
  array (
    0 => 'book.simplexml.php',
    1 => 'SimpleXML',
  ),
  8 => 
  array (
    0 => 'book.wddx.php',
    1 => 'WDDX',
  ),
  9 => 
  array (
    0 => 'book.xml.php',
    1 => 'XML Parser',
  ),
  10 => 
  array (
    0 => 'book.xmlreader.php',
    1 => 'XMLReader',
  ),
  11 => 
  array (
    0 => 'book.xmlwriter.php',
    1 => 'XMLWriter',
  ),
  12 => 
  array (
    0 => 'book.xsl.php',
    1 => 'XSL',
  ),
  13 => 
  array (
    0 => 'book.xslt.php',
    1 => 'XSLT (PHP4)',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);