<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.dotnet.php',
    1 => '.NET',
  ),
  1 => 
  array (
    0 => 'book.com.php',
    1 => 'COM',
  ),
  2 => 
  array (
    0 => 'book.printer.php',
    1 => 'Printer',
  ),
  3 => 
  array (
    0 => 'book.w32api.php',
    1 => 'W32api',
  ),
  4 => 
  array (
    0 => 'book.win32ps.php',
    1 => 'win32ps',
  ),
  5 => 
  array (
    0 => 'book.win32service.php',
    1 => 'win32service',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);