<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.exec.php',
    1 => 'Program execution',
  ),
  1 => 
  array (
    0 => 'book.expect.php',
    1 => 'Expect',
  ),
  2 => 
  array (
    0 => 'book.libevent.php',
    1 => 'Libevent',
  ),
  3 => 
  array (
    0 => 'book.pcntl.php',
    1 => 'PCNTL',
  ),
  4 => 
  array (
    0 => 'book.posix.php',
    1 => 'POSIX',
  ),
  5 => 
  array (
    0 => 'book.sem.php',
    1 => 'Semaphore',
  ),
  6 => 
  array (
    0 => 'book.shmop.php',
    1 => 'Shared Memory',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);