<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.msession.php',
    1 => 'Msession',
  ),
  1 => 
  array (
    0 => 'book.session.php',
    1 => 'Sessions',
  ),
  2 => 
  array (
    0 => 'book.session-pgsql.php',
    1 => 'Session PgSQL',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);