<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.array.php',
    1 => 'Arrays',
  ),
  1 => 
  array (
    0 => 'book.classobj.php',
    1 => 'Classes/Objects',
  ),
  2 => 
  array (
    0 => 'book.classkit.php',
    1 => 'Classkit',
  ),
  3 => 
  array (
    0 => 'book.ctype.php',
    1 => 'Ctype',
  ),
  4 => 
  array (
    0 => 'book.filter.php',
    1 => 'Filter',
  ),
  5 => 
  array (
    0 => 'book.funchand.php',
    1 => 'Function Handling',
  ),
  6 => 
  array (
    0 => 'book.objaggregation.php',
    1 => 'Object Aggregation',
  ),
  7 => 
  array (
    0 => 'book.quickhash.php',
    1 => 'Quickhash',
  ),
  8 => 
  array (
    0 => 'book.reflection.php',
    1 => 'Reflection',
  ),
  9 => 
  array (
    0 => 'book.var.php',
    1 => 'Variable handling',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);