<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.exif.php',
    1 => 'Exif',
  ),
  1 => 
  array (
    0 => 'book.image.php',
    1 => 'GD',
  ),
  2 => 
  array (
    0 => 'book.imagick.php',
    1 => 'ImageMagick',
  ),
  3 => 
  array (
    0 => 'book.gmagick.php',
    1 => 'Gmagick',
  ),
  4 => 
  array (
    0 => 'book.cairo.php',
    1 => 'Cairo',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);