<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.bc.php',
    1 => 'BC Math',
  ),
  1 => 
  array (
    0 => 'book.gmp.php',
    1 => 'GMP',
  ),
  2 => 
  array (
    0 => 'book.math.php',
    1 => 'Math',
  ),
  3 => 
  array (
    0 => 'book.stats.php',
    1 => 'Statistics',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);