<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.fdf.php',
    1 => 'FDF',
  ),
  1 => 
  array (
    0 => 'book.gnupg.php',
    1 => 'GnuPG',
  ),
  2 => 
  array (
    0 => 'book.haru.php',
    1 => 'haru',
  ),
  3 => 
  array (
    0 => 'book.ming.php',
    1 => 'Ming',
  ),
  4 => 
  array (
    0 => 'book.pdf.php',
    1 => 'PDF',
  ),
  5 => 
  array (
    0 => 'book.ps.php',
    1 => 'PS',
  ),
  6 => 
  array (
    0 => 'book.rpmreader.php',
    1 => 'RPM Reader',
  ),
  7 => 
  array (
    0 => 'book.swf.php',
    1 => 'SWF',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);