<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.geoip.php',
    1 => 'GeoIP',
  ),
  1 => 
  array (
    0 => 'book.judy.php',
    1 => 'Judy',
  ),
  2 => 
  array (
    0 => 'book.json.php',
    1 => 'JSON',
  ),
  3 => 
  array (
    0 => 'book.misc.php',
    1 => 'Misc.',
  ),
  4 => 
  array (
    0 => 'book.parsekit.php',
    1 => 'Parsekit',
  ),
  5 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  6 => 
  array (
    0 => 'book.spl-types.php',
    1 => 'SPL Types',
  ),
  7 => 
  array (
    0 => 'book.stream.php',
    1 => 'Streams',
  ),
  8 => 
  array (
    0 => 'book.tidy.php',
    1 => 'Tidy',
  ),
  9 => 
  array (
    0 => 'book.tokenizer.php',
    1 => 'Tokenizer',
  ),
  10 => 
  array (
    0 => 'book.url.php',
    1 => 'URLs',
  ),
  11 => 
  array (
    0 => 'book.yaml.php',
    1 => 'Yaml',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);