<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.bbcode.php',
    1 => 'BBCode',
  ),
  1 => 
  array (
    0 => 'book.pcre.php',
    1 => 'PCRE',
  ),
  2 => 
  array (
    0 => 'book.regex.php',
    1 => 'POSIX Regex',
  ),
  3 => 
  array (
    0 => 'book.ssdeep.php',
    1 => 'ssdeep',
  ),
  4 => 
  array (
    0 => 'book.strings.php',
    1 => 'Strings',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);