<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.mnogosearch.php',
    1 => 'mnoGoSearch',
  ),
  1 => 
  array (
    0 => 'book.sphinx.php',
    1 => 'Sphinx',
  ),
  2 => 
  array (
    0 => 'book.swish.php',
    1 => 'Swish',
  ),
  3 => 
  array (
    0 => 'book.solr.php',
    1 => 'Solr',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);