<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.cyrus.php',
    1 => 'Cyrus',
  ),
  1 => 
  array (
    0 => 'book.imap.php',
    1 => 'IMAP',
  ),
  2 => 
  array (
    0 => 'book.mail.php',
    1 => 'Mail',
  ),
  3 => 
  array (
    0 => 'book.mailparse.php',
    1 => 'Mailparse',
  ),
  4 => 
  array (
    0 => 'book.vpopmail.php',
    1 => 'vpopmail',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);