<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.enchant.php',
    1 => 'Enchant',
  ),
  1 => 
  array (
    0 => 'book.fribidi.php',
    1 => 'FriBiDi',
  ),
  2 => 
  array (
    0 => 'book.gettext.php',
    1 => 'Gettext',
  ),
  3 => 
  array (
    0 => 'book.iconv.php',
    1 => 'iconv',
  ),
  4 => 
  array (
    0 => 'book.intl.php',
    1 => 'intl',
  ),
  5 => 
  array (
    0 => 'book.mbstring.php',
    1 => 'Multibyte String',
  ),
  6 => 
  array (
    0 => 'book.pspell.php',
    1 => 'Pspell',
  ),
  7 => 
  array (
    0 => 'book.recode.php',
    1 => 'Recode',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);