<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.cubrid.php',
    1 => 'Cubrid',
  ),
  1 => 
  array (
    0 => 'book.dbase.php',
    1 => 'dBase',
  ),
  2 => 
  array (
    0 => 'book.dbplus.php',
    1 => 'DB++',
  ),
  3 => 
  array (
    0 => 'book.fbsql.php',
    1 => 'FrontBase',
  ),
  4 => 
  array (
    0 => 'book.filepro.php',
    1 => 'filePro',
  ),
  5 => 
  array (
    0 => 'book.ibase.php',
    1 => 'Firebird/InterBase',
  ),
  6 => 
  array (
    0 => 'book.ifx.php',
    1 => 'Informix',
  ),
  7 => 
  array (
    0 => 'book.ibm-db2.php',
    1 => 'IBM DB2',
  ),
  8 => 
  array (
    0 => 'book.ingres.php',
    1 => 'Ingres',
  ),
  9 => 
  array (
    0 => 'book.maxdb.php',
    1 => 'MaxDB',
  ),
  10 => 
  array (
    0 => 'book.mongo.php',
    1 => 'Mongo',
  ),
  11 => 
  array (
    0 => 'book.msql.php',
    1 => 'mSQL',
  ),
  12 => 
  array (
    0 => 'book.mssql.php',
    1 => 'Mssql',
  ),
  13 => 
  array (
    0 => 'book.mysql.php',
    1 => 'MySQL',
  ),
  14 => 
  array (
    0 => 'book.mysqli.php',
    1 => 'Mysqli',
  ),
  15 => 
  array (
    0 => 'book.mysqlnd.php',
    1 => 'Mysqlnd',
  ),
  16 => 
  array (
    0 => 'book.mysqlnd-qc.php',
    1 => 'mysqlnd_qc',
  ),
  17 => 
  array (
    0 => 'book.oci8.php',
    1 => 'OCI8',
  ),
  18 => 
  array (
    0 => 'book.ovrimos.php',
    1 => 'Ovrimos SQL',
  ),
  19 => 
  array (
    0 => 'book.paradox.php',
    1 => 'Paradox',
  ),
  20 => 
  array (
    0 => 'book.pgsql.php',
    1 => 'PostgreSQL',
  ),
  21 => 
  array (
    0 => 'book.sqlite.php',
    1 => 'SQLite',
  ),
  22 => 
  array (
    0 => 'book.sqlite3.php',
    1 => 'SQLite3',
  ),
  23 => 
  array (
    0 => 'book.sybase.php',
    1 => 'Sybase',
  ),
  24 => 
  array (
    0 => 'book.tokyo-tyrant.php',
    1 => 'tokyo_tyrant',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);