<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.crack.php',
    1 => 'Crack',
  ),
  1 => 
  array (
    0 => 'book.hash.php',
    1 => 'Hash',
  ),
  2 => 
  array (
    0 => 'book.mcrypt.php',
    1 => 'Mcrypt',
  ),
  3 => 
  array (
    0 => 'book.mhash.php',
    1 => 'Mhash',
  ),
  4 => 
  array (
    0 => 'book.openssl.php',
    1 => 'OpenSSL',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);