<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.dba.php',
    1 => 'DBA',
  ),
  1 => 
  array (
    0 => 'book.dbx.php',
    1 => 'dbx',
  ),
  2 => 
  array (
    0 => 'book.uodbc.php',
    1 => 'ODBC',
  ),
  3 => 
  array (
    0 => 'book.pdo.php',
    1 => 'PDO',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'refs.database.php',
    1 => 'Database Extensions',
  ),
  1 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  2 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);