<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.apc.php',
    1 => 'APC',
  ),
  1 => 
  array (
    0 => 'book.apd.php',
    1 => 'APD',
  ),
  2 => 
  array (
    0 => 'book.bcompiler.php',
    1 => 'bcompiler',
  ),
  3 => 
  array (
    0 => 'book.errorfunc.php',
    1 => 'Error Handling',
  ),
  4 => 
  array (
    0 => 'book.htscanner.php',
    1 => 'htscanner',
  ),
  5 => 
  array (
    0 => 'book.inclued.php',
    1 => 'inclued',
  ),
  6 => 
  array (
    0 => 'book.info.php',
    1 => 'PHP Options/Info',
  ),
  7 => 
  array (
    0 => 'book.memtrack.php',
    1 => 'Memtrack',
  ),
  8 => 
  array (
    0 => 'book.overload.php',
    1 => 'Object overloading',
  ),
  9 => 
  array (
    0 => 'book.outcontrol.php',
    1 => 'Output Control',
  ),
  10 => 
  array (
    0 => 'book.runkit.php',
    1 => 'runkit',
  ),
  11 => 
  array (
    0 => 'book.scream.php',
    1 => 'scream',
  ),
  12 => 
  array (
    0 => 'book.wincache.php',
    1 => 'WinCache',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);