<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.oauth.php',
    1 => 'OAuth',
  ),
  1 => 
  array (
    0 => 'book.sca.php',
    1 => 'SCA',
  ),
  2 => 
  array (
    0 => 'book.soap.php',
    1 => 'SOAP',
  ),
  3 => 
  array (
    0 => 'book.xmlrpc.php',
    1 => 'XML-RPC',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);