<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.dio.php',
    1 => 'Direct IO',
  ),
  1 => 
  array (
    0 => 'book.dir.php',
    1 => 'Directories',
  ),
  2 => 
  array (
    0 => 'book.fileinfo.php',
    1 => 'Fileinfo',
  ),
  3 => 
  array (
    0 => 'book.filesystem.php',
    1 => 'Filesystem',
  ),
  4 => 
  array (
    0 => 'book.inotify.php',
    1 => 'Inotify',
  ),
  5 => 
  array (
    0 => 'book.mime-magic.php',
    1 => 'Mimetype',
  ),
  6 => 
  array (
    0 => 'book.xattr.php',
    1 => 'xattr',
  ),
  7 => 
  array (
    0 => 'book.xdiff.php',
    1 => 'xdiff',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);