<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.bzip2.php',
    1 => 'Bzip2',
  ),
  1 => 
  array (
    0 => 'book.lzf.php',
    1 => 'LZF',
  ),
  2 => 
  array (
    0 => 'book.phar.php',
    1 => 'Phar',
  ),
  3 => 
  array (
    0 => 'book.rar.php',
    1 => 'Rar',
  ),
  4 => 
  array (
    0 => 'book.zip.php',
    1 => 'Zip',
  ),
  5 => 
  array (
    0 => 'book.zlib.php',
    1 => 'Zlib',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);