<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.amqp.php',
    1 => 'AMQP',
  ),
  1 => 
  array (
    0 => 'book.chdb.php',
    1 => 'chdb',
  ),
  2 => 
  array (
    0 => 'book.curl.php',
    1 => 'cURL',
  ),
  3 => 
  array (
    0 => 'book.fam.php',
    1 => 'FAM',
  ),
  4 => 
  array (
    0 => 'book.ftp.php',
    1 => 'FTP',
  ),
  5 => 
  array (
    0 => 'book.gupnp.php',
    1 => 'Gupnp',
  ),
  6 => 
  array (
    0 => 'book.hw.php',
    1 => 'Hyperwave',
  ),
  7 => 
  array (
    0 => 'book.hwapi.php',
    1 => 'Hyperwave API',
  ),
  8 => 
  array (
    0 => 'book.http.php',
    1 => 'HTTP',
  ),
  9 => 
  array (
    0 => 'book.java.php',
    1 => 'Java',
  ),
  10 => 
  array (
    0 => 'book.ldap.php',
    1 => 'LDAP',
  ),
  11 => 
  array (
    0 => 'book.notes.php',
    1 => 'Lotus Notes',
  ),
  12 => 
  array (
    0 => 'book.memcache.php',
    1 => 'Memcache',
  ),
  13 => 
  array (
    0 => 'book.memcached.php',
    1 => 'Memcached',
  ),
  14 => 
  array (
    0 => 'book.gearman.php',
    1 => 'Gearman',
  ),
  15 => 
  array (
    0 => 'book.mqseries.php',
    1 => 'mqseries',
  ),
  16 => 
  array (
    0 => 'book.net-gopher.php',
    1 => 'Gopher',
  ),
  17 => 
  array (
    0 => 'book.network.php',
    1 => 'Network',
  ),
  18 => 
  array (
    0 => 'book.sam.php',
    1 => 'SAM',
  ),
  19 => 
  array (
    0 => 'book.snmp.php',
    1 => 'SNMP',
  ),
  20 => 
  array (
    0 => 'book.sockets.php',
    1 => 'Sockets',
  ),
  21 => 
  array (
    0 => 'book.ssh2.php',
    1 => 'SSH2',
  ),
  22 => 
  array (
    0 => 'book.stomp.php',
    1 => 'Stomp',
  ),
  23 => 
  array (
    0 => 'book.svn.php',
    1 => 'SVN',
  ),
  24 => 
  array (
    0 => 'book.tcpwrap.php',
    1 => 'TCP',
  ),
  25 => 
  array (
    0 => 'book.yaz.php',
    1 => 'YAZ',
  ),
  26 => 
  array (
    0 => 'book.nis.php',
    1 => 'YP/NIS',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);