<?php
$TOC = array (
  0 => 
  array (
    0 => 'book.newt.php',
    1 => 'Newt',
  ),
  1 => 
  array (
    0 => 'book.ncurses.php',
    1 => 'Ncurses',
  ),
  2 => 
  array (
    0 => 'book.readline.php',
    1 => 'Readline',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);