<?php
$TOC = array (
  0 => 
  array (
    0 => 'class.traversable.php',
    1 => 'Traversable',
  ),
  1 => 
  array (
    0 => 'class.iterator.php',
    1 => 'Iterator',
  ),
  2 => 
  array (
    0 => 'class.iteratoraggregate.php',
    1 => 'IteratorAggregate',
  ),
  3 => 
  array (
    0 => 'class.arrayaccess.php',
    1 => 'ArrayAccess',
  ),
  4 => 
  array (
    0 => 'class.serializable.php',
    1 => 'Serializable',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);