<?php
$TOC = array (
  0 => 
  array (
    0 => 'reserved.keywords.php',
    1 => 'List of Keywords',
  ),
  1 => 
  array (
    0 => 'reserved.classes.php',
    1 => 'Predefined Classes',
  ),
  2 => 
  array (
    0 => 'reserved.constants.php',
    1 => 'Predefined Constants',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'appendices.php',
    1 => 'Appendices',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);