<?php
$TOC = array (
  0 => 
  array (
    0 => 'language.variables.superglobals.php',
    1 => 'Superglobals',
  ),
  1 => 
  array (
    0 => 'reserved.variables.globals.php',
    1 => '$GLOBALS',
  ),
  2 => 
  array (
    0 => 'reserved.variables.server.php',
    1 => '$_SERVER',
  ),
  3 => 
  array (
    0 => 'reserved.variables.get.php',
    1 => '$_GET',
  ),
  4 => 
  array (
    0 => 'reserved.variables.post.php',
    1 => '$_POST',
  ),
  5 => 
  array (
    0 => 'reserved.variables.files.php',
    1 => '$_FILES',
  ),
  6 => 
  array (
    0 => 'reserved.variables.request.php',
    1 => '$_REQUEST',
  ),
  7 => 
  array (
    0 => 'reserved.variables.session.php',
    1 => '$_SESSION',
  ),
  8 => 
  array (
    0 => 'reserved.variables.environment.php',
    1 => '$_ENV',
  ),
  9 => 
  array (
    0 => 'reserved.variables.cookies.php',
    1 => '$_COOKIE',
  ),
  10 => 
  array (
    0 => 'reserved.variables.phperrormsg.php',
    1 => '$php_errormsg',
  ),
  11 => 
  array (
    0 => 'reserved.variables.httprawpostdata.php',
    1 => '$HTTP_RAW_POST_DATA',
  ),
  12 => 
  array (
    0 => 'reserved.variables.httpresponseheader.php',
    1 => '$http_response_header',
  ),
  13 => 
  array (
    0 => 'reserved.variables.argc.php',
    1 => '$argc',
  ),
  14 => 
  array (
    0 => 'reserved.variables.argv.php',
    1 => '$argv',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);