<?php
$TOC = array (
  0 => 
  array (
    0 => 'sam.connections.php',
    1 => 'Connections',
  ),
  1 => 
  array (
    0 => 'sam.messages.php',
    1 => 'Messages',
  ),
  2 => 
  array (
    0 => 'sam.operations.php',
    1 => 'Messaging operations',
  ),
  3 => 
  array (
    0 => 'sam.pubsub.php',
    1 => 'Publish/Subscribe and subscriptions to topics',
  ),
  4 => 
  array (
    0 => 'sam.errors.php',
    1 => 'Error handling',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sam.php',
    1 => 'SAM',
  ),
  1 => 
  array (
    0 => 'refs.remote.other.php',
    1 => 'Other Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);