<?php
$TOC = array (
  0 => 
  array (
    0 => 'SCA.examples.structure.php',
    1 => 'The structure of a Service Component',
  ),
  1 => 
  array (
    0 => 'SCA.examples.proxies.php',
    1 => 'Obtaining a proxy for another Service Component',
  ),
  2 => 
  array (
    0 => 'SCA.examples.calling.php',
    1 => 'Calling another Service Component',
  ),
  3 => 
  array (
    0 => 'SCA.examples.nonSCAscript.php',
    1 => 'Locating and calling services from a script which is not an
   SCA Component',
  ),
  4 => 
  array (
    0 => 'sca.examples.exposing-webservice.php',
    1 => 'Exposing a Service Component as a Web service',
  ),
  5 => 
  array (
    0 => 'SCA.examples.deploy.php',
    1 => 'Deploying an SCA component',
  ),
  6 => 
  array (
    0 => 'SCA.examples.obtaining-wsdl.php',
    1 => 'Obtaining the WSDL for an SCA component offering a Service as
   a Web service',
  ),
  7 => 
  array (
    0 => 'SCA.examples.understanding-wsdl.php',
    1 => 'Understanding how the WSDL is generated',
  ),
  8 => 
  array (
    0 => 'SCA.examples.structures.php',
    1 => 'Working with Data Structures',
  ),
  9 => 
  array (
    0 => 'SCA.examples.errorhandling.php',
    1 => 'Error handling',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sca.php',
    1 => 'SCA',
  ),
  1 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);