<?php
$TOC = array (
  0 => 
  array (
    0 => 'scream.examples-simple.php',
    1 => 'Example that shows the effect of scream',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.scream.php',
    1 => 'scream',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);