<?php
$TOC = array (
  0 => 
  array (
    0 => 'sdo.das.rel.examples-crud.php',
    1 => 'Creating, retrieving, updating and deleting data',
  ),
  1 => 
  array (
    0 => 'sdo.das.rel.metadata.php',
    1 => 'Specifying the metadata',
  ),
  2 => 
  array (
    0 => 'sdo.das.rel.examples.one-table.php',
    1 => 'One-table examples',
  ),
  3 => 
  array (
    0 => 'sdo.das.rel.examples.two-table.php',
    1 => 'Two-table examples',
  ),
  4 => 
  array (
    0 => 'sdo.das.rel.examples.three-table.php',
    1 => 'Three-table example',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sdodasrel.php',
    1 => 'SDO-DAS-Relational',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);