<?php
$TOC = array (
  0 => 
  array (
    0 => 'sdo.examples-basic.php',
    1 => 'Basic Usage',
  ),
  1 => 
  array (
    0 => 'sdo.sample.getset.php',
    1 => 'Setting and Getting Property Values',
  ),
  2 => 
  array (
    0 => 'sdo.sample.sequence.php',
    1 => 'Working with Sequenced Data Objects',
  ),
  3 => 
  array (
    0 => 'sdo.sample.reflection.php',
    1 => 'Reflecting on Service Data Objects',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sdo.php',
    1 => 'SDO',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);