<?php
$TOC = array (
  0 => 
  array (
    0 => 'sdodasrel.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'sdodasrel.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'sdodasrel.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'sdodasrel.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sdodasrel.php',
    1 => 'SDO-DAS-Relational',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);