<?php
$TOC = array (
  0 => 
  array (
    0 => 'security.cgi-bin.attacks.php',
    1 => 'Possible attacks',
  ),
  1 => 
  array (
    0 => 'security.cgi-bin.default.php',
    1 => 'Case 1: only public files served',
  ),
  2 => 
  array (
    0 => 'security.cgi-bin.force-redirect.php',
    1 => 'Case 2: using cgi.force_redirect',
  ),
  3 => 
  array (
    0 => 'security.cgi-bin.doc-root.php',
    1 => 'Case 3: setting doc_root or user_dir',
  ),
  4 => 
  array (
    0 => 'security.cgi-bin.shell.php',
    1 => 'Case 4: PHP parser outside of web tree',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'security.php',
    1 => 'Security',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);