<?php
$TOC = array (
  0 => 
  array (
    0 => 'security.intro.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'security.general.php',
    1 => 'General considerations',
  ),
  2 => 
  array (
    0 => 'security.cgi-bin.php',
    1 => 'Installed as CGI binary',
  ),
  3 => 
  array (
    0 => 'security.apache.php',
    1 => 'Installed as an Apache module',
  ),
  4 => 
  array (
    0 => 'security.filesystem.php',
    1 => 'Filesystem Security',
  ),
  5 => 
  array (
    0 => 'security.database.php',
    1 => 'Database Security',
  ),
  6 => 
  array (
    0 => 'security.errors.php',
    1 => 'Error Reporting',
  ),
  7 => 
  array (
    0 => 'security.globals.php',
    1 => 'Using Register Globals',
  ),
  8 => 
  array (
    0 => 'security.variables.php',
    1 => 'User Submitted Data',
  ),
  9 => 
  array (
    0 => 'security.magicquotes.php',
    1 => 'Magic Quotes',
  ),
  10 => 
  array (
    0 => 'security.hiding.php',
    1 => 'Hiding PHP',
  ),
  11 => 
  array (
    0 => 'security.current.php',
    1 => 'Keeping Current',
  ),
);
$TOC_DEPRECATED = array (
);
$PARENTS = array (
  0 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);