<?php
$TOC = array (
  0 => 
  array (
    0 => 'security.magicquotes.what.php',
    1 => 'What are Magic Quotes',
  ),
  1 => 
  array (
    0 => 'security.magicquotes.why.php',
    1 => 'Why did we use Magic Quotes',
  ),
  2 => 
  array (
    0 => 'security.magicquotes.whynot.php',
    1 => 'Why not to use Magic Quotes',
  ),
  3 => 
  array (
    0 => 'security.magicquotes.disabling.php',
    1 => 'Disabling Magic Quotes',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'security.php',
    1 => 'Security',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);