<?php
$TOC = array (
  0 => 
  array (
    0 => 'security.database.design.php',
    1 => 'Designing Databases',
  ),
  1 => 
  array (
    0 => 'security.database.connection.php',
    1 => 'Connecting to Database',
  ),
  2 => 
  array (
    0 => 'security.database.storage.php',
    1 => 'Encrypted Storage Model',
  ),
  3 => 
  array (
    0 => 'security.database.sql-injection.php',
    1 => 'SQL Injection',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'security.php',
    1 => 'Security',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);