<?php
$TOC = array (
  0 => 
  array (
    0 => 'sem.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'sem.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'sem.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'sem.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sem.php',
    1 => 'Semaphore',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);