<?php
$TOC = array (
  0 => 
  array (
    0 => 'session.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'session.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'session.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'session.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.session.php',
    1 => 'Sessions',
  ),
  1 => 
  array (
    0 => 'refs.basic.session.php',
    1 => 'Session Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);