<?php
$TOC = array (
  0 => 
  array (
    0 => 'session.examples.basic.php',
    1 => 'Registering a variable with $_SESSION.',
  ),
  1 => 
  array (
    0 => 'session.idpassing.php',
    1 => 'Passing the Session ID',
  ),
  2 => 
  array (
    0 => 'session.customhandler.php',
    1 => 'Custom Session Handlers',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.session.php',
    1 => 'Sessions',
  ),
  1 => 
  array (
    0 => 'refs.basic.session.php',
    1 => 'Session Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);