<?php
$TOC = array (
  0 => 
  array (
    0 => 'shmop.examples-basic.php',
    1 => 'Shared Memory Operations Overview',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.shmop.php',
    1 => 'Shared Memory',
  ),
  1 => 
  array (
    0 => 'refs.fileprocess.process.php',
    1 => 'Process Control Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);