<?php
$TOC = array (
  0 => 
  array (
    0 => 'simplexml.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'simplexml.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'simplexml.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'simplexml.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.simplexml.php',
    1 => 'SimpleXML',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);