<?php
$TOC = array (
  0 => 
  array (
    0 => 'simplexml.examples-basic.php',
    1 => 'Basic usage',
  ),
  1 => 
  array (
    0 => 'simplexml.examples-errors.php',
    1 => 'Dealing with XML errors',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.simplexml.php',
    1 => 'SimpleXML',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);