<?php
$TOC = array (
  0 => 
  array (
    0 => 'sphinx.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'sphinx.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'sphinx.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'sphinx.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.sphinx.php',
    1 => 'Sphinx',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);