<?php
$TOC = array (
  0 => 
  array (
    0 => 'class.appenditerator.php',
    1 => 'AppendIterator',
  ),
  1 => 
  array (
    0 => 'class.arrayiterator.php',
    1 => 'ArrayIterator',
  ),
  2 => 
  array (
    0 => 'class.cachingiterator.php',
    1 => 'CachingIterator',
  ),
  3 => 
  array (
    0 => 'class.directoryiterator.php',
    1 => 'DirectoryIterator',
  ),
  4 => 
  array (
    0 => 'class.emptyiterator.php',
    1 => 'EmptyIterator',
  ),
  5 => 
  array (
    0 => 'class.filesystemiterator.php',
    1 => 'FilesystemIterator',
  ),
  6 => 
  array (
    0 => 'class.filteriterator.php',
    1 => 'FilterIterator',
  ),
  7 => 
  array (
    0 => 'class.globiterator.php',
    1 => 'GlobIterator',
  ),
  8 => 
  array (
    0 => 'class.infiniteiterator.php',
    1 => 'InfiniteIterator',
  ),
  9 => 
  array (
    0 => 'class.iteratoriterator.php',
    1 => 'IteratorIterator',
  ),
  10 => 
  array (
    0 => 'class.limititerator.php',
    1 => 'LimitIterator',
  ),
  11 => 
  array (
    0 => 'class.multipleiterator.php',
    1 => 'MultipleIterator',
  ),
  12 => 
  array (
    0 => 'class.norewinditerator.php',
    1 => 'NoRewindIterator',
  ),
  13 => 
  array (
    0 => 'class.parentiterator.php',
    1 => 'ParentIterator',
  ),
  14 => 
  array (
    0 => 'class.recursivearrayiterator.php',
    1 => 'RecursiveArrayIterator',
  ),
  15 => 
  array (
    0 => 'class.recursivecachingiterator.php',
    1 => 'RecursiveCachingIterator',
  ),
  16 => 
  array (
    0 => 'class.recursivedirectoryiterator.php',
    1 => 'RecursiveDirectoryIterator',
  ),
  17 => 
  array (
    0 => 'class.recursivefilteriterator.php',
    1 => 'RecursiveFilterIterator',
  ),
  18 => 
  array (
    0 => 'class.recursiveiteratoriterator.php',
    1 => 'RecursiveIteratorIterator',
  ),
  19 => 
  array (
    0 => 'class.recursiveregexiterator.php',
    1 => 'RecursiveRegexIterator',
  ),
  20 => 
  array (
    0 => 'class.recursivetreeiterator.php',
    1 => 'RecursiveTreeIterator',
  ),
  21 => 
  array (
    0 => 'class.regexiterator.php',
    1 => 'RegexIterator',
  ),
  22 => 
  array (
    0 => 'class.simplexmliterator.php',
    1 => 'SimpleXMLIterator',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);