<?php
$TOC = array (
  0 => 
  array (
    0 => 'class.badfunctioncallexception.php',
    1 => 'BadFunctionCallException',
  ),
  1 => 
  array (
    0 => 'class.badmethodcallexception.php',
    1 => 'BadMethodCallException',
  ),
  2 => 
  array (
    0 => 'class.domainexception.php',
    1 => 'DomainException',
  ),
  3 => 
  array (
    0 => 'class.invalidargumentexception.php',
    1 => 'InvalidArgumentException',
  ),
  4 => 
  array (
    0 => 'class.lengthexception.php',
    1 => 'LengthException',
  ),
  5 => 
  array (
    0 => 'class.logicexception.php',
    1 => 'LogicException',
  ),
  6 => 
  array (
    0 => 'class.outofboundsexception.php',
    1 => 'OutOfBoundsException',
  ),
  7 => 
  array (
    0 => 'class.outofrangeexception.php',
    1 => 'OutOfRangeException',
  ),
  8 => 
  array (
    0 => 'class.overflowexception.php',
    1 => 'OverflowException',
  ),
  9 => 
  array (
    0 => 'class.rangeexception.php',
    1 => 'RangeException',
  ),
  10 => 
  array (
    0 => 'class.runtimeexception.php',
    1 => 'RuntimeException',
  ),
  11 => 
  array (
    0 => 'class.underflowexception.php',
    1 => 'UnderflowException',
  ),
  12 => 
  array (
    0 => 'class.unexpectedvalueexception.php',
    1 => 'UnexpectedValueException',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);