<?php
$TOC = array (
  0 => 
  array (
    0 => 'class.arrayobject.php',
    1 => 'ArrayObject',
  ),
  1 => 
  array (
    0 => 'class.splobserver.php',
    1 => 'SplObserver',
  ),
  2 => 
  array (
    0 => 'class.splsubject.php',
    1 => 'SplSubject',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);