<?php
$TOC = array (
  0 => 
  array (
    0 => 'class.spldoublylinkedlist.php',
    1 => 'SplDoublyLinkedList',
  ),
  1 => 
  array (
    0 => 'class.splstack.php',
    1 => 'SplStack',
  ),
  2 => 
  array (
    0 => 'class.splqueue.php',
    1 => 'SplQueue',
  ),
  3 => 
  array (
    0 => 'class.splheap.php',
    1 => 'SplHeap',
  ),
  4 => 
  array (
    0 => 'class.splmaxheap.php',
    1 => 'SplMaxHeap',
  ),
  5 => 
  array (
    0 => 'class.splminheap.php',
    1 => 'SplMinHeap',
  ),
  6 => 
  array (
    0 => 'class.splpriorityqueue.php',
    1 => 'SplPriorityQueue',
  ),
  7 => 
  array (
    0 => 'class.splfixedarray.php',
    1 => 'SplFixedArray',
  ),
  8 => 
  array (
    0 => 'class.splobjectstorage.php',
    1 => 'SplObjectStorage',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);