<?php
$TOC = array (
  0 => 
  array (
    0 => 'class.splfileinfo.php',
    1 => 'SplFileInfo',
  ),
  1 => 
  array (
    0 => 'class.splfileobject.php',
    1 => 'SplFileObject',
  ),
  2 => 
  array (
    0 => 'class.spltempfileobject.php',
    1 => 'SplTempFileObject',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);