<?php
$TOC = array (
  0 => 
  array (
    0 => 'class.countable.php',
    1 => 'Countable',
  ),
  1 => 
  array (
    0 => 'class.outeriterator.php',
    1 => 'OuterIterator',
  ),
  2 => 
  array (
    0 => 'class.recursiveiterator.php',
    1 => 'RecursiveIterator',
  ),
  3 => 
  array (
    0 => 'class.seekableiterator.php',
    1 => 'SeekableIterator',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.spl.php',
    1 => 'SPL',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);