<?php
$TOC = array (
  0 => 
  array (
    0 => 'ssdeep.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'ssdeep.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'ssdeep.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'ssdeep.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.ssdeep.php',
    1 => 'ssdeep',
  ),
  1 => 
  array (
    0 => 'refs.basic.text.php',
    1 => 'Text Processing',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);