<?php
$TOC = array (
  0 => 
  array (
    0 => 'stats.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'stats.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'stats.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'stats.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.stats.php',
    1 => 'Statistics',
  ),
  1 => 
  array (
    0 => 'refs.math.php',
    1 => 'Mathematical Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);