<?php
$TOC = array (
  0 => 
  array (
    0 => 'stream.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'stream.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'stream.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'stream.resources.php',
    1 => 'Stream Classes',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.stream.php',
    1 => 'Streams',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);