<?php
$TOC = array (
  0 => 
  array (
    0 => 'stream.streamwrapper.example-1.php',
    1 => 'Example class registered as stream wrapper',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.stream.php',
    1 => 'Streams',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);