<?php
$TOC = array (
  0 => 
  array (
    0 => 'swf.examples-basic.php',
    1 => 'Basic Usage',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.swf.php',
    1 => 'SWF',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.nontext.php',
    1 => 'Non-Text MIME Output',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);