<?php
$TOC = array (
  0 => 
  array (
    0 => 'swish.examples-basic.php',
    1 => 'Basic usage',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.swish.php',
    1 => 'Swish',
  ),
  1 => 
  array (
    0 => 'refs.search.php',
    1 => 'Search Engine Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);