<?php
$TOC = array (
  0 => 
  array (
    0 => 'tidy.examples.basic.php',
    1 => 'Examples',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.tidy.php',
    1 => 'Tidy',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);