<?php
$TOC = array (
  0 => 
  array (
    0 => 'timezones.africa.php',
    1 => 'Africa',
  ),
  1 => 
  array (
    0 => 'timezones.america.php',
    1 => 'America',
  ),
  2 => 
  array (
    0 => 'timezones.antarctica.php',
    1 => 'Antarctica',
  ),
  3 => 
  array (
    0 => 'timezones.arctic.php',
    1 => 'Arctic',
  ),
  4 => 
  array (
    0 => 'timezones.asia.php',
    1 => 'Asia',
  ),
  5 => 
  array (
    0 => 'timezones.atlantic.php',
    1 => 'Atlantic',
  ),
  6 => 
  array (
    0 => 'timezones.australia.php',
    1 => 'Australia',
  ),
  7 => 
  array (
    0 => 'timezones.europe.php',
    1 => 'Europe',
  ),
  8 => 
  array (
    0 => 'timezones.indian.php',
    1 => 'Indian',
  ),
  9 => 
  array (
    0 => 'timezones.pacific.php',
    1 => 'Pacific',
  ),
  10 => 
  array (
    0 => 'timezones.others.php',
    1 => 'Others',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.datetime.php',
    1 => 'Date/Time',
  ),
  1 => 
  array (
    0 => 'refs.calendar.php',
    1 => 'Date and Time Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);