<?php
$TOC = array (
  0 => 
  array (
    0 => 'tutorial.requirements.php',
    1 => 'What do I need?',
  ),
  1 => 
  array (
    0 => 'tutorial.firstpage.php',
    1 => 'Your first PHP-enabled page',
  ),
  2 => 
  array (
    0 => 'tutorial.useful.php',
    1 => 'Something Useful',
  ),
  3 => 
  array (
    0 => 'tutorial.forms.php',
    1 => 'Dealing with Forms',
  ),
  4 => 
  array (
    0 => 'tutorial.oldcode.php',
    1 => 'Using old code with new versions of PHP',
  ),
  5 => 
  array (
    0 => 'tutorial.whatsnext.php',
    1 => 'What\'s next?',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'getting-started.php',
    1 => 'Getting Started',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);