<?php
$TOC = array (
  0 => 
  array (
    0 => 'userlandnaming.globalnamespace.php',
    1 => 'Global Namespace',
  ),
  1 => 
  array (
    0 => 'userlandnaming.rules.php',
    1 => 'Rules',
  ),
  2 => 
  array (
    0 => 'userlandnaming.tips.php',
    1 => 'Tips',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'appendices.php',
    1 => 'Appendices',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);