<?php
$TOC = array (
  0 => 
  array (
    0 => 'vpopmail.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'vpopmail.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'vpopmail.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'vpopmail.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.vpopmail.php',
    1 => 'vpopmail',
  ),
  1 => 
  array (
    0 => 'refs.remote.mail.php',
    1 => 'Mail Related Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);