<?php
$TOC = array (
  0 => 
  array (
    0 => 'w32api.examples-uptime.php',
    1 => 'Get the uptime and display it in a message box',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.w32api.php',
    1 => 'W32api',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);