<?php
$TOC = array (
  0 => 
  array (
    0 => 'wddx.examples-serialize.php',
    1 => 'Serializing a single value with WDDX',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.wddx.php',
    1 => 'WDDX',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);