<?php
$TOC = array (
  0 => 
  array (
    0 => 'win32service.examples-service.php',
    1 => 'Registering a PHP script to run as a service',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.win32service.php',
    1 => 'win32service',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);