<?php
$TOC = array (
  0 => 
  array (
    0 => 'win32ps.examples-process.php',
    1 => 'Statistics about the current PHP process',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.win32ps.php',
    1 => 'win32ps',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);