<?php
$TOC = array (
  0 => 
  array (
    0 => 'win32service.constants.servicetype.php',
    1 => 'Win32Service Service Type Bitmasks',
  ),
  1 => 
  array (
    0 => 'win32service.constants.servicestatus.php',
    1 => 'Win32Service Service Status Constants',
  ),
  2 => 
  array (
    0 => 'win32service.constants.servicecontrol.php',
    1 => 'Win32Service Service Control Message Constants',
  ),
  3 => 
  array (
    0 => 'win32service.constants.controlsaccepted.php',
    1 => 'Win32Service Service Control Message Accepted Bitmasks',
  ),
  4 => 
  array (
    0 => 'win32service.constants.servicestarttype.php',
    1 => 'Win32Service Service Start Type Constants',
  ),
  5 => 
  array (
    0 => 'win32service.constants.errorcontrol.php',
    1 => 'Win32Service Service Error Control Constants',
  ),
  6 => 
  array (
    0 => 'win32service.constants.serviceflag.php',
    1 => 'Win32Service Service Flag Constants',
  ),
  7 => 
  array (
    0 => 'win32service.constants.errors.php',
    1 => 'Win32 Error Codes',
  ),
  8 => 
  array (
    0 => 'win32service.constants.basepriorities.php',
    1 => 'Win32 Base Priority Classes',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.win32service.php',
    1 => 'win32service',
  ),
  1 => 
  array (
    0 => 'refs.utilspec.windows.php',
    1 => 'Windows Only Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);