<?php
$TOC = array (
  0 => 
  array (
    0 => 'wincache.win32build.prereq.php',
    1 => 'Prerequisites',
  ),
  1 => 
  array (
    0 => 'wincache.win32build.building.php',
    1 => 'Compiling and building',
  ),
  2 => 
  array (
    0 => 'wincache.win32build.verify.php',
    1 => 'Verifying the build',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.wincache.php',
    1 => 'WinCache',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);