<?php
$TOC = array (
  0 => 
  array (
    0 => 'wincache.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'wincache.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'wincache.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'wincache.stats.php',
    1 => 'WinCache Statistics Script',
  ),
  4 => 
  array (
    0 => 'wincache.sessionhandler.php',
    1 => 'WinCache Session Handler',
  ),
  5 => 
  array (
    0 => 'wincache.reroutes.php',
    1 => 'WinCache Functions Reroutes',
  ),
  6 => 
  array (
    0 => 'wincache.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.wincache.php',
    1 => 'WinCache',
  ),
  1 => 
  array (
    0 => 'refs.basic.php.php',
    1 => 'Affecting PHP\'s Behaviour',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);