<?php
$TOC = array (
  0 => 
  array (
    0 => 'wrappers.file.php',
    1 => 'Filesystem',
  ),
  1 => 
  array (
    0 => 'wrappers.http.php',
    1 => 'HTTP and HTTPS',
  ),
  2 => 
  array (
    0 => 'wrappers.ftp.php',
    1 => 'FTP and FTPS',
  ),
  3 => 
  array (
    0 => 'wrappers.php.php',
    1 => 'PHP input/output',
  ),
  4 => 
  array (
    0 => 'wrappers.compression.php',
    1 => 'zlib, bzip2 and zip',
  ),
  5 => 
  array (
    0 => 'wrappers.data.php',
    1 => 'data://',
  ),
  6 => 
  array (
    0 => 'wrappers.glob.php',
    1 => 'Glob',
  ),
  7 => 
  array (
    0 => 'wrappers.phar.php',
    1 => 'phar://',
  ),
  8 => 
  array (
    0 => 'wrappers.ssh2.php',
    1 => 'ssh2://',
  ),
  9 => 
  array (
    0 => 'wrappers.rar.php',
    1 => 'rar://',
  ),
  10 => 
  array (
    0 => 'wrappers.audio.php',
    1 => 'ogg://',
  ),
  11 => 
  array (
    0 => 'wrappers.expect.php',
    1 => 'expect://',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'langref.php',
    1 => 'Language Reference',
  ),
  1 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);