<?php
$TOC = array (
  0 => 
  array (
    0 => 'example.xml-structure.php',
    1 => 'XML Element Structure Example',
  ),
  1 => 
  array (
    0 => 'example.xml-map-tags.php',
    1 => 'XML Tag Mapping Example',
  ),
  2 => 
  array (
    0 => 'example.xml-external-entity.php',
    1 => 'XML External Entity Example',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.xml.php',
    1 => 'XML Parser',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);