<?php
$TOC = array (
  0 => 
  array (
    0 => 'xmlrpc.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'xmlrpc.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'xmlrpc.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'xmlrpc.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.xmlrpc.php',
    1 => 'XML-RPC',
  ),
  1 => 
  array (
    0 => 'refs.webservice.php',
    1 => 'Web Services',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);