<?php
$TOC = array (
  0 => 
  array (
    0 => 'xsl.examples-collection.php',
    1 => 'collection.xml',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.xsl.php',
    1 => 'XSL',
  ),
  1 => 
  array (
    0 => 'refs.xml.php',
    1 => 'XML Manipulation',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);