<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaml.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'yaml.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'yaml.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'yaml.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaml.php',
    1 => 'Yaml',
  ),
  1 => 
  array (
    0 => 'refs.basic.other.php',
    1 => 'Other Basic Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);