<?php
$TOC = array (
  0 => 
  array (
    0 => 'zip.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'zip.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'zip.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'zip.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.zip.php',
    1 => 'Zip',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);