<?php
$TOC = array (
  0 => 
  array (
    0 => 'zlib.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'zlib.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'zlib.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'zlib.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.zlib.php',
    1 => 'Zlib',
  ),
  1 => 
  array (
    0 => 'refs.compression.php',
    1 => 'Compression and Archive Extensions',
  ),
  2 => 
  array (
    0 => 'funcref.php',
    1 => 'Function Reference',
  ),
  3 => 
  array (
    0 => 'index.php',
    1 => 'PHP Manual',
  ),
);