name: "Bug Report"
description: "Report a bug to help us improve"
labels: ["Bug", "Status: Needs Triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible.

  - type: input
    id: page_url
    attributes:
      label: Affected Page URL
      description: The exact page address where the bug occurs
      placeholder: e.g. https://www.php.net/manual/en/function.date.php
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the issue here..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to reproduce"
      description: "Explain how to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
      placeholder: "A clear and concise description..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
