name: "PHP 8.5 Release Page Design Content Submission"
description: "Submit your design for the PHP 8.5 Release Page"
labels: ["Design Contest"]

body:
  - type: input
    id: team
    attributes:
      label: "Names and Contact Details"
      description: "Please provide your contact details"
    validations:
      required: true

  - type: input
    id: links
    attributes:
      label: "Link to mockup/prototype"
      description: "Please provide a link to the mockup or prototype if available."
      placeholder: "https://example.com/my-design.html"
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: "Rationale (300-600 words)"
      description: |
        Explain information hierarchy, layout choices, and how the design meets
        goals. You must add 3 to 5 screenshots through "Paste, drop, or click
        to add files".
    validations:
      required: true

  - type: checkboxes
    id: license
    attributes:
      label: "License"
      description: |
        Submissions must be original. If selected, I agree to license it under
        the [same terms as the php.net website](https://www.php.net/copyright.php) and allow
        adaptations for implementation.
      options:
        - label: "I confirm, and agree."
          required: true
