<?php

/*
 This is a list of all manual languages hosted
 on a full PHP.net mirror site

 Some codes, like "ko" and "tw" are not in conformance
 with the official language code standard!

 http://www.unicode.org/unicode/onlinedat/languages.html
*/
$LANGUAGES = array(
    'en'    => 'English',
    'ar'    => 'Arabic',
    'pt_BR' => 'Brazilian Portuguese',
    'tw'    => 'Chinese (Traditional)',
    'zh'    => 'Chinese (Continental)',
    'cs'    => 'Czech',
    'nl'    => 'Dutch',
    'fi'    => 'Finnish',
    'fr'    => 'French',
    'de'    => 'German',
    'he'    => 'Hebrew',
    //'hk' => '',
    'hu'    => 'Hungarian',
    'it'    => 'Italian',
    'ja'    => 'Japanese',
    'kr'    => 'Korean',
    'pl'    => 'Polish',
    'ro'    => 'Romanian',
    'ru'    => 'Russian',
    'sk'    => 'Slovak',
    'sl'    => 'Slovenian',
    'es'    => 'Spanish',
    'sv'    => 'Swedish',
    'tr'    => 'Turkish',
);
?>