<?php









/*
 * DO NOTE MODIFY THIS FILE
 * This file is automagically generated, and overwritten,
 * by the rsync box. It is only included in this repo to simplify getting
 * up and running on your localhost without needing to generate all this
 * yourself from master.
*/
 








$CONF_TEASER = array (
  'cfp' => 
  array (
    'http://php.net/conferences/index.php#id2013-09-05-1' => ' PHPBenelux Conference 2014',
    'http://php.net/conferences/index.php#id2013-09-01-1' => 'ConFoo 2014 wants you to be a speaker',
    'http://php.net/conferences/index.php#id2013-08-31-1' => 'SunshinePHP 2014',
    'http://php.net/conferences/index.php#id2013-07-19-2' => 'Ski PHP 2014',
  ),
  'conference' => 
  array (
    'http://php.net/conferences/index.php#id2013-08-19-2' => 'CodeConnexx 2013',
    'http://php.net/conferences/index.php#id2013-08-19-1' => 'ZendCon 2013',
    'http://php.net/conferences/index.php#id2013-08-07-1' => 'International PHP Conference 2013',
    'http://php.net/conferences/index.php#id2013-05-06-1' => 'PHP Conference Argentina',
    'http://php.net/conferences/index.php#id2013-04-12-1' => 'PHP South Africa 2013',
  ),
)
?>
