<?php









/*
 * DO NOTE MODIFY THIS FILE
 * This file is automagically generated, and overwritten,
 * by the rsync box. It is only included in this repo to simplify getting
 * up and running on your localhost without needing to generate all this
 * yourself from master.
*/
 








$CONF_TEASER = array (
  'cfp' => 
  array (
    'http://php.net/conferences/index.php#id2015-01-16-1' => 'Dutch PHP Conference 2015',
  ),
  'conference' => 
  array (
    'http://php.net/conferences/index.php#id2015-01-10-1' => 'Midwest PHP 2015',
    'http://php.net/conferences/index.php#id2015-01-06-1' => 'ConFoo 2015 - Become a Master',
    'http://php.net/conferences/index.php#id2014-12-29-1' => 'Bulgaria Web Summit 2015',
    'http://php.net/conferences/index.php#id2014-11-05-1' => 'International PHP Conference Spring 2015',
    'http://php.net/conferences/index.php#id2014-10-27-1' => 'PHP Unconference Europe 2015',
    'http://php.net/conferences/index.php#id2014-09-26-1' => 'PHP Australia Conference 2015',
  ),
)
?>
