<?php








/*
 * DO NOTE MODIFY THIS FILE
 * This file is automagically generated, and overwritten,
 * by the rsync box. It is only included in this repo to simplify getting
 * up and running on your localhost without needing to generate all this
 * yourself from master.
*/
 








 $NEWS_ENTRIES = array (
  0 => 
  array (
    'title' => 'Our modern web theme goes live!',
    'id' => 'http://php.net/archive/2013.php#id2013-11-20-1',
    'published' => '2013-11-20T04:00:00-08:00',
    'updated' => '2013-11-20T13:32:00-00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-11-20-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-11-20-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP web team are delighted to announce the launch of the new web theme that has been
    in beta for many months. Lots of hard work has gone into this release and we will be continually 
    improving things over time now that we have migrated away from the legacy theme.</p>

    <p>From an aesthetics point of view the general color scheme of the website has been lightened from the
      older dark purple. Lots of borders and links use a similar purple color to attain
      consistency. Fonts are smoother, and colors, contrast and highlighting have significantly improved; especially
      on function reference pages. Code examples should now be much more readable.</p>

     <p>The theme is marked up using HTML5 and is generally much more modern. We are using Google Fonts and
      Bootstrap for our theme base.</p>
     
     <p>To provide valuable feedback, you can use the \'Feedback\' widget on the side of the page (not visible
      on smartphones) and to report bugs, you can make use of the <a href="http://bugs.php.net" title="PHP Bug Tracker">bugs.php.net</a>
      tracker. Despite our extensive multi-device/multi-browser testing, we may have missed something. So, if you
      spot any issues please do get in touch.</p>

     <p>Special thanks to the guys who helped make this happen, you know who you are!</p>

    </div>
  ',
    'intro' => '<div><p>The PHP web team are delighted to announce the launch of the new web theme that has been
    in beta for many months. Lots of hard work has gone into this release and we will be continually 
    improving things over time now that we have migrated away from the legacy theme.</p><p>From an aesthetics point of view the general color scheme of the website has been lightened from the
      older dark purple. Lots of borders and links use a similar purple color to attain
      consistency. Fonts are smoother, and colors, contrast and highlighting have significantly improved; especially
      on function reference pages. Code examples should now be much more readable.</p><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-11-20-1\' class>&hellip; read full article</a></p></div>',
  ),
  1 => 
  array (
    'title' => 'PHP 5.4.22 Released',
    'id' => 'http://php.net/archive/2013.php#id2013-11-14-3',
    'published' => '2013-11-14T22:39:47-08:00',
    'updated' => '2013-11-14T22:39:47-08:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-11-14-3',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-11-14-3',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP
     5.4.22. About 10 bugs were fixed. All PHP 5.4 users are encouraged to upgrade to this version.
     </p>
     
     <p>For source downloads of PHP 5.4.22 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.4.22">ChangeLog</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP
     5.4.22. About 10 bugs were fixed. All PHP 5.4 users are encouraged to upgrade to this version.
     </p><p>For source downloads of PHP 5.4.22 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.4.22">ChangeLog</a>.
     </p></div>',
  ),
  2 => 
  array (
    'title' => 'PHP Johannesburg 2014',
    'id' => 'http://php.net/archive/2013.php#id2013-11-14-2',
    'published' => '2013-11-14T18:22:25-08:00',
    'updated' => '2013-11-14T18:22:25-08:00',
    'finalTeaserDate' => '2013-12-01',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'cfp',
        'label' => 'Call for Papers',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-11-14-2',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://www.phpsouthafrica.com',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://www.phpsouthafrica.com',
      'title' => 'PHP Johannesburg 2014',
      'content' => 'phpjohannesburg2014.png',
    ),
    'content' => '<div>
     <p>
     Following from a very successful 1st PHP Conference in Cape Town, we are now breaking
     ground for Johannesburg`s inaugural conference.  Johannesburg will be host to
     <strong>Africa`s Biggest PHP Conference on the continent April 4th&amp;5th 2014</strong>. With
     over 200 delegates attending, the two day event is hosting some of the Continents most
     influential people in their field. With delegates flying in from as far afield as
     Ethiopia, Nigeria, Kenya and ROW.
     </p>
     
     <p>
     <strong>Call for Papers : Closes 30th Novermber 2013</strong>
     </p>
     
     <p>
     Our event will run over 2 days, come join us for a few days of sharing, networking,
     learning and some fun.  <strong>What will make this Conference very special is our Keynote
     Speaker - For PHPJohannesburg we have Rasmus Lerdorf who will be opening Africa`s Biggest
     PHP Conference</strong>.
     </p>
     
     <p>
     We look forward to seeing you.
     <a href="http://www.phpsouthafrica.com">www.phpsouthafrica.com</a>
     </p>
    </div>
  ',
    'intro' => '<div><p>
     Following from a very successful 1st PHP Conference in Cape Town, we are now breaking
     ground for Johannesburg`s inaugural conference.  Johannesburg will be host to
     <strong>Africa`s Biggest PHP Conference on the continent April 4th&amp;5th 2014</strong>. With
     over 200 delegates attending, the two day event is hosting some of the Continents most
     influential people in their field. With delegates flying in from as far afield as
     Ethiopia, Nigeria, Kenya and ROW.
     </p><p>
     <strong>Call for Papers : Closes 30th Novermber 2013</strong>
     </p><p class=\'fullArticleLink\'><a href=\'http://www.phpsouthafrica.com\' class>&hellip; read full article</a></p></div>',
  ),
  3 => 
  array (
    'title' => 'PHP 5.5.6 is now available',
    'id' => 'http://php.net/archive/2013.php#id2013-11-14-1',
    'published' => '2013-11-14T08:58:23+00:00',
    'updated' => '2013-11-14T08:58:23+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-11-14-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-11-14-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP 5.5.6. This release fixes some bugs against
      PHP 5.5.5, and adds some performance improvements.</p>

     <p>For source downloads of PHP 5.5.6 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.5.6">ChangeLog</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP 5.5.6. This release fixes some bugs against
      PHP 5.5.5, and adds some performance improvements.</p><p>For source downloads of PHP 5.5.6 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.5.6">ChangeLog</a>.
     </p></div>',
  ),
  4 => 
  array (
    'title' => 'A further update on php.net',
    'id' => 'http://php.net/archive/2013.php#id2013-10-24-2',
    'published' => '2013-10-24T18:57:54-07:00',
    'updated' => '2013-10-24T18:57:54-07:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-10-24-2',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-10-24-2',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>We are continuing to work through the repercussions of the php.net malware issue described in a news post earlier today. As part of this, the php.net systems team have audited every server operated by php.net, and have found that two servers were compromised: the server which hosted the www.php.net, static.php.net and git.php.net domains, and was previously suspected based on the JavaScript malware, and the server hosting bugs.php.net. The method by which these servers were compromised is unknown at this time.</p>
     
     <p>All affected services have been migrated off those servers. We have verified that our Git repository was not compromised, and it remains in read only mode as services are brought back up in full.</p>
     
     <p>As it\'s possible that the attackers may have accessed the private key of the php.net SSL certificate, we have revoked it immediately. We are in the process of getting a new certificate, and expect to restore access to php.net sites that require SSL (including bugs.php.net and wiki.php.net) in the next few hours.</p>
     
     <p>To summarise, the situation right now is that:</p>
     
     <ul>
       <li>JavaScript malware was served to a small percentage of php.net users from the 22nd to the 24th of October 2013.</li>
       <li>Neither the source tarball downloads nor the Git repository were modified or compromised.</li>
       <li>Two php.net servers were compromised, and have been removed from service. All services have been migrated to new, secure servers.</li>
       <li>SSL access to php.net Web sites is temporarily unavailable until a new SSL certificate is issued and installed on the servers that need it.</li>
     </ul>
     
     <p>Over the next few days, we will be taking further action:</p>
     
     <ul>
       <li>php.net users will have their passwords reset. Note that users of PHP are unaffected by this: this is solely for people committing code to projects hosted on svn.php.net or git.php.net.</li>
     </ul>
     
     <p>We will provide a full post mortem in due course, most likely next week. You can also get updates from the official php.net Twitter: <a href="https://twitter.com/official_php">@official_php</a>.</p>
    </div>
  ',
    'intro' => '<div><p>We are continuing to work through the repercussions of the php.net malware issue described in a news post earlier today. As part of this, the php.net systems team have audited every server operated by php.net, and have found that two servers were compromised: the server which hosted the www.php.net, static.php.net and git.php.net domains, and was previously suspected based on the JavaScript malware, and the server hosting bugs.php.net. The method by which these servers were compromised is unknown at this time.</p><p>All affected services have been migrated off those servers. We have verified that our Git repository was not compromised, and it remains in read only mode as services are brought back up in full.</p><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-10-24-2\' class>&hellip; read full article</a></p></div>',
  ),
  5 => 
  array (
    'title' => 'A quick update on the status of php.net',
    'id' => 'http://php.net/archive/2013.php#id2013-10-24-1',
    'published' => '2013-10-24T20:55:17-05:00',
    'updated' => '2013-10-24T20:55:17-05:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-10-24-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-10-24-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>
     On 24 Oct 2013 06:15:39 +0000 Google started saying www.php.net was hosting
     malware. The Google Webmaster Tools were initially quite delayed in showing
     the reason why and when they did it looked a lot like a false positive
     because we had some minified/obfuscated javascript being dynamically
     injected into userprefs.js. This looked suspicious to us as well, but
     it was actually written to do exactly that so we were quite certain it
     was a false positive, but we kept digging.
     </p>
     
     <p>
     It turned out that by combing through the access logs for static.php.net
     it was periodically serving up userprefs.js with the wrong content length
     and then reverting back to the right size after a few minutes. This is due
     to an rsync cron job. So the file was being modified locally and reverted.
     Google\'s crawler caught one of these small windows where the wrong file
     was being served, but of course, when we looked at it manually it looked
     fine. So more confusion.
     </p>
     
     <p>
     We are still investigating how someone caused that file to be changed,
     but in the meantime we have migrated www/static to new clean servers.
     The highest priority is obviously the source code integrity and after
     a quick:
     </p>
     
       <blockquote>git fsck --no-reflog --full --strict</blockquote>
     
     <p>
     on all our repos plus manually checking the md5sums of the PHP distribution
     files we see no evidence that the PHP code has been compromised. We have
     a mirror of our git repos on github.com and we will manually check git
     commits as well and have a full post-mortem on the intrusion when we have
     a clearer picture of what happened.
     </p>
    </div>
  ',
    'intro' => '<div><p>
     On 24 Oct 2013 06:15:39 +0000 Google started saying www.php.net was hosting
     malware. The Google Webmaster Tools were initially quite delayed in showing
     the reason why and when they did it looked a lot like a false positive
     because we had some minified/obfuscated javascript being dynamically
     injected into userprefs.js. This looked suspicious to us as well, but
     it was actually written to do exactly that so we were quite certain it
     was a false positive, but we kept digging.
     </p><p>
     It turned out that by combing through the access logs for static.php.net
     it was periodically serving up userprefs.js with the wrong content length
     and then reverting back to the right size after a few minutes. This is due
     to an rsync cron job. So the file was being modified locally and reverted.
     Google\'s crawler caught one of these small windows where the wrong file
     was being served, but of course, when we looked at it manually it looked
     fine. So more confusion.
     </p><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-10-24-1\' class>&hellip; read full article</a></p></div>',
  ),
  6 => 
  array (
    'title' => 'PHP 5.4.21 Released',
    'id' => 'http://php.net/archive/2013.php#id2013-10-17-1',
    'published' => '2013-10-17T15:28:32-07:00',
    'updated' => '2013-10-17T15:28:32-07:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-10-17-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-10-17-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP
     5.4.21. About 10 bugs were fixed. All PHP 5.4 users are encouraged to upgrade to this version.
     </p>
     
     <p>For source downloads of PHP 5.4.21 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.4.21">ChangeLog</a>.
     </p>
     
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP
     5.4.21. About 10 bugs were fixed. All PHP 5.4 users are encouraged to upgrade to this version.
     </p><p>For source downloads of PHP 5.4.21 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.4.21">ChangeLog</a>.
     </p></div>',
  ),
  7 => 
  array (
    'title' => 'PHP 5.5.5 has been released',
    'id' => 'http://php.net/archive/2013.php#id2013-10-16-1',
    'published' => '2013-10-16T14:54:24+00:00',
    'updated' => '2013-10-16T14:54:24+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-10-16-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-10-16-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP 5.5.5. This release fixes about twenty bugs against
      PHP 5.5.4, some of them regarding the build system. All PHP users are encouraged to upgrade to this new version.</p>

     <p>For source downloads of PHP 5.5.5 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.5.5">ChangeLog</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP 5.5.5. This release fixes about twenty bugs against
      PHP 5.5.4, some of them regarding the build system. All PHP users are encouraged to upgrade to this new version.</p><p>For source downloads of PHP 5.5.5 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.5.5">ChangeLog</a>.
     </p></div>',
  ),
  8 => 
  array (
    'title' => 'Ski PHP 2014',
    'id' => 'http://php.net/archive/2013.php#id2013-10-10-2',
    'published' => '2013-10-10T13:00:14-07:00',
    'updated' => '2013-10-10T13:00:14-07:00',
    'finalTeaserDate' => '2014-01-18',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-10-10-2',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'https://www.skiphp.com',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'https://www.skiphp.com',
      'title' => 'Ski PHP 2014',
      'content' => 'ski-php.png',
    ),
    'content' => '<div>
     <p>
     <a href="https://www.skiphp.com/">Ski PHP 2014</a> has announced the
     <a href="https://www.skiphp.com/attend/schedule">schedule for their upcoming
     conference</a>, which will be on January 17-18, 2014 in Salt Lake City, Utah,
     USA.  Our schedule is anchored by keynotes from Jared Smith, Laura Thomson, and
     Chris Hartjes, and also includes talks from Julien Pauli, Ed Finkler, John
     Coggeshall, Elizabeth Naramore, and many more.
     </p>
     
     <p>
     Our Early Bird registration rate of just $129 is available until October 15th.
     Hotel group rate information is available at our site.
     </p>
    </div>
  ',
    'intro' => '<div><p>
     <a href="https://www.skiphp.com/">Ski PHP 2014</a> has announced the
     <a href="https://www.skiphp.com/attend/schedule">schedule for their upcoming
     conference</a>, which will be on January 17-18, 2014 in Salt Lake City, Utah,
     USA.  Our schedule is anchored by keynotes from Jared Smith, Laura Thomson, and
     Chris Hartjes, and also includes talks from Julien Pauli, Ed Finkler, John
     Coggeshall, Elizabeth Naramore, and many more.
     </p><p>
     Our Early Bird registration rate of just $129 is available until October 15th.
     Hotel group rate information is available at our site.
     </p></div>',
  ),
  9 => 
  array (
    'title' => 'Madison PHP Conference',
    'id' => 'http://php.net/archive/2013.php#id2013-10-10-1',
    'published' => '2013-10-10T12:46:40-07:00',
    'updated' => '2013-10-10T12:46:40-07:00',
    'finalTeaserDate' => '2013-11-17',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-10-10-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://www.madisonphpconference.com/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://www.madisonphpconference.com/',
      'title' => 'Madison PHP Conference',
      'content' => 'madison-php-2013.png',
    ),
    'content' => '<div>
     <p>
     November 16th, 2013 - 8:30am - 3:30pm<br/>
     Warner Park Community Recreation Center <br/>
     1625 Northport Dr, Madison, WI 53704<br/>
     $40 (before October 16th), $60 (after October 16th), $100 at the door<br/>
     </p>
     
     <p>
     <strong>Call for Papers</strong>: Now through October 8th, 2013
     </p>
     
     <p>
     Join us for a one day, two-track conference that focuses on PHP and related web technologies. This event is organized by Madison PHP and is designed to offer something to attendees at all skill levels.   It will be a day of networking, learning, sharing, and great fun!
     </p>
     
     <p>
     <strong>Two Tracks</strong>
     We\'ve carefully crafted two distinct tracks but you\'re not locked into just one. Attend any talk from any track.
     </p>
     
     <p>
     <strong>PHP Foundations</strong>
     Track Learn the basics of PHP development. A carefully selected set of talks for those who have never programmed before or who are new to PHP and would like a refresher of the basics.
     </p>
     
     <p>
     <strong>PHP Professional Track</strong>
     Explore new technologies and techniques. Gather with other seasoned developers and increase your value with a series of talks that will both energize and get you excited about the future of PHP.
     </p>
     
     <p>
     For more information and to register, please visit: <a href="http://www.MadisonPHPConference.com">http://www.MadisonPHPConference.com</a>
     </p>
    </div>
  ',
    'intro' => '<div><p>
     November 16th, 2013 - 8:30am - 3:30pm<br/>
     Warner Park Community Recreation Center <br/>
     1625 Northport Dr, Madison, WI 53704<br/>
     $40 (before October 16th), $60 (after October 16th), $100 at the door<br/></p><p>
     <strong>Call for Papers</strong>: Now through October 8th, 2013
     </p><p class=\'fullArticleLink\'><a href=\'http://www.madisonphpconference.com/\' class>&hellip; read full article</a></p></div>',
  ),
  10 => 
  array (
    'title' => 'PHP 5.4.20 released',
    'id' => 'http://php.net/archive/2013.php#id2013-09-19-2',
    'published' => '2013-09-19T21:42:19-07:00',
    'updated' => '2013-09-19T21:42:19-07:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-09-19-2',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-09-19-2',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP
     5.4.20. About 30 bugs were fixed. All PHP 5.4 users are encouraged to upgrade to this version.
     </p>
     
     <p>For source downloads of PHP 5.4.20 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.4.20">ChangeLog</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP
     5.4.20. About 30 bugs were fixed. All PHP 5.4 users are encouraged to upgrade to this version.
     </p><p>For source downloads of PHP 5.4.20 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.4.20">ChangeLog</a>.
     </p></div>',
  ),
  11 => 
  array (
    'title' => 'PHP 5.5.4 released',
    'id' => 'http://php.net/archive/2013.php#id2013-09-19-1',
    'published' => '2013-09-19T13:08:02+00:00',
    'updated' => '2013-09-19T13:08:02+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-09-19-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-09-19-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
      <p>The PHP development team announces the immediate availability of PHP 5.5.4. This release fixes several bugs against
      PHP 5.5.3. All PHP users are encouraged to upgrade to this new version.</p>

     <p>For source downloads of PHP 5.5.4 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.5.4">ChangeLog</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP 5.5.4. This release fixes several bugs against
      PHP 5.5.3. All PHP users are encouraged to upgrade to this new version.</p><p>For source downloads of PHP 5.5.4 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.5.4">ChangeLog</a>.
     </p></div>',
  ),
  12 => 
  array (
    'title' => ' PHPBenelux Conference 2014',
    'id' => 'http://php.net/archive/2013.php#id2013-09-05-1',
    'published' => '2013-09-05T14:44:36-07:00',
    'updated' => '2013-09-05T14:44:36-07:00',
    'finalTeaserDate' => '2013-10-06',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'cfp',
        'label' => 'Call for Papers',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-09-05-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://conference.phpbenelux.eu/2014',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://conference.phpbenelux.eu/2014',
      'title' => 'PHPBenelux Conference 2014',
      'content' => 'phpbenelux_conference_logo-2014-e1377030913837.png',
    ),
    'content' => '<div>
     <p>
     It\'s that time of the year again! The call for proposals is here, this is your
     chance to grab the microphone on stage, hook up your laptop and teach the
     world how to make better PHP sites and applications! Did anything new lately
     which gave you a lot of cool insights? Do you feel like an expert on a certain
     topic? Why not share it with other developers? We now have opened up our
     <a href="http://conference.phpbenelux.eu/2014/call-for-proposals/">Call
     for Proposals (CfP)</a> for you to start submitting your talks.
     </p>
     <p>
     We accept proposals up to October 6, 2013 23:59 and we have no limit on how
     many talks you submit. So, don\'t wait until the latest moment and start
     submitting your talks.
     </p>
     <p>
     What\'s in it for the speakers?
     </p>
     <p>
     When you get selected there is more than eternal fame and glory at the venue
     and beyond, we also offer;
     </p>
     <ul>
     <li>pick-up service from Brussels Airport (Zaventem)/train to the hotel</li>
     <li>three hotel nights (from Thursday afternoon until Sunday morning)</li>
     <li>full access to the conference</li>
     <li>an invitation to our 5th celebration very special speakers dinner on Thursday the 23rd of January</li>
     <li>up to 300 euro of reimbursement for travel expenses</li>
     </ul>
     
     <p>
     More information can be found on <a href="http://conference.phpbenelux.eu/2014">our website</a>
     or follow <a href="http://www.twitter.com/phpbenelux">PHPBenelux on Twitter</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>
     It\'s that time of the year again! The call for proposals is here, this is your
     chance to grab the microphone on stage, hook up your laptop and teach the
     world how to make better PHP sites and applications! Did anything new lately
     which gave you a lot of cool insights? Do you feel like an expert on a certain
     topic? Why not share it with other developers? We now have opened up our
     <a href="http://conference.phpbenelux.eu/2014/call-for-proposals/">Call
     for Proposals (CfP)</a> for you to start submitting your talks.
     </p><p>
     We accept proposals up to October 6, 2013 23:59 and we have no limit on how
     many talks you submit. So, don\'t wait until the latest moment and start
     submitting your talks.
     </p><p class=\'fullArticleLink\'><a href=\'http://conference.phpbenelux.eu/2014\' class>&hellip; read full article</a></p></div>',
  ),
  13 => 
  array (
    'title' => 'ConFoo 2014 wants you to be a speaker',
    'id' => 'http://php.net/archive/2013.php#id2013-09-01-1',
    'published' => '2013-09-02T11:57:28-07:00',
    'updated' => '2013-09-02T11:57:28-07:00',
    'finalTeaserDate' => '2013-10-15',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'cfp',
        'label' => 'Call for Papers',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-09-01-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://confoo.ca',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://confoo.ca',
      'title' => 'ConFoo 2014 in Montreal',
      'content' => 'confoo-2014-php.gif',
    ),
    'content' => '<div>
      <p>We are looking for PHP professionals to share their skills and experience at the next ConFoo.
        <a href="http://confoo.ca/en/call-for-papers">Submit your proposals</a> until <b>September 22nd.</b>
      </p>

      <p>ConFoo is a conference for developers that has built a reputation as a prime destination for exploring new technologies, diving deeper into familiar topics, and experiencing the best of community and culture.</p>

      <ul>
        <li>ConFoo 2014 will be hosted on February 26-28 in Montreal, at the Hilton Bonaventure Hotel.</li>
        <li>We take good care of our speakers by covering most expenses including travel, accommodation, lunch, full conference ticket, etc.</li>
        <li>Presentations are 45 minutes including questions, and may be delivered in English or French.</li>
        <li>ConFoo is an open environment where everyone is welcome to submit. We are simply looking for quality proposals by skilled and friendly people.</li>
      </ul>

      <p>If you would prefer to attend the conference, we have a <a href="http://confoo.ca/en/register">$230 discount</a> until October 16th.</p>
    </div>
  ',
    'intro' => '<div><p>We are looking for PHP professionals to share their skills and experience at the next ConFoo.
        <a href="http://confoo.ca/en/call-for-papers">Submit your proposals</a> until <b>September 22nd.</b>
      </p><p>ConFoo is a conference for developers that has built a reputation as a prime destination for exploring new technologies, diving deeper into familiar topics, and experiencing the best of community and culture.</p><p class=\'fullArticleLink\'><a href=\'http://confoo.ca\' class>&hellip; read full article</a></p></div>',
  ),
  14 => 
  array (
    'title' => 'SunshinePHP 2014',
    'id' => 'http://php.net/archive/2013.php#id2013-08-31-1',
    'published' => '2013-08-31T11:57:28-07:00',
    'updated' => '2013-08-31T11:57:28-07:00',
    'finalTeaserDate' => '2013-10-15',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'cfp',
        'label' => 'Call for Papers',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-08-31-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://sunshinephp.com/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://sunshinephp.com/',
      'title' => 'SunshinePHP',
      'content' => 'sunshinephp_logo.png',
    ),
    'content' => '<div>
     <p>
     The <a href="http://sunshinephp.com">SunshinePHP</a> Developer Conference from
     February 6th - 8th, 2014 is being brought to you by the (SoFloPHP) <a href="http://soflophp.org">South Florida PHP User Group</a>. The conference
     will have a full tutorial day followed by a 2 day conferenece in Miami, Florida
     at the Embassy Suites Miami International.  Our call for papers will run until
     October 15th at <a href="http://cfp.sunshinephp.com">http://cfp.sunshinephp.com</a>.
     </p>
     
     <p>
     So when it is cold everywhere else, come down to Florida where it is sunny and
     warm to enjoy some PHP, learning, community, and fun.  For more information,
     visit <a href="http://sunshinephp.com">http://sunshinephp.com</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>
     The <a href="http://sunshinephp.com">SunshinePHP</a> Developer Conference from
     February 6th - 8th, 2014 is being brought to you by the (SoFloPHP) <a href="http://soflophp.org">South Florida PHP User Group</a>. The conference
     will have a full tutorial day followed by a 2 day conferenece in Miami, Florida
     at the Embassy Suites Miami International.  Our call for papers will run until
     October 15th at <a href="http://cfp.sunshinephp.com">http://cfp.sunshinephp.com</a>.
     </p><p>
     So when it is cold everywhere else, come down to Florida where it is sunny and
     warm to enjoy some PHP, learning, community, and fun.  For more information,
     visit <a href="http://sunshinephp.com">http://sunshinephp.com</a>.
     </p></div>',
  ),
  15 => 
  array (
    'title' => 'PHP 5.4.19 and PHP 5.5.3 Released!',
    'id' => 'http://php.net/archive/2013.php#id2013-08-22-1',
    'published' => '2013-08-22T16:06:05-07:00',
    'updated' => '2013-08-22T16:06:05-07:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-08-22-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-08-22-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<p xmlns="http://www.w3.org/2005/Atom">The PHP development team announces the immediate availability of PHP
     5.4.19 and PHP 5.5.3. These releases fix a bug in the patch for CVE-2013-4248 in OpenSSL module and
     compile failure with ZTS enabled in PHP 5.4. All PHP users are encouraged to upgrade to either PHP 5.5.3 or PHP 5.4.19.</p>
     
     <p xmlns="http://www.w3.org/2005/Atom">For source downloads of PHP 5.4.19 and PHP 5.5.3 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.4.19">ChangeLog</a>.
 	</p>
',
    'intro' => '<div></div>',
  ),
  16 => 
  array (
    'title' => 'CodeConnexx 2013',
    'id' => 'http://php.net/archive/2013.php#id2013-08-19-2',
    'published' => '2013-08-19T12:57:55-07:00',
    'updated' => '2013-08-31T12:57:55-07:00',
    'finalTeaserDate' => '2013-11-09',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-08-19-2',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://codeconnexx.com/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://codeconnexx.com/',
      'title' => 'CodeConnexx 2013',
      'content' => 'codeconnexx_logo_2013.png',
    ),
    'content' => '<div>
     <p>
     <a href="http://codeconnexx.com/">CodeConnexx</a> is a two-day, one track conference that aims to bring together everyone interested in talking about code.
     </p>
     <p>
     As we know, choosing a career as a coder comes with its own set of life
     challenges, and we want to talk about those too. In short, this conference is a
     different kind of conference, as it connects those two pieces of the puzzle
     together in one event.
     </p>
     
     <p>
     Every technical talk will be followed by a talk about life skills and work/life
     balance. There will also be plenty of social opportunities to get to know the
     other attendees. Not only do we want to help you bridge the gap between work
     and life, we want to help you connect with each other as well.
     </p>
     
     <p>
         CodeConnexx, hosted by <a href="http://phpwomen.org/">PHPWomen</a>, will
     take <a href="http://codeconnexx.com/location/">place</a> in Maastricht,
     Netherlands on November 8th &amp; 9th 2013. We sincerely hope you are able to
     join us!
     </p>
    </div>
  ',
    'intro' => '<div><p>
     <a href="http://codeconnexx.com/">CodeConnexx</a> is a two-day, one track conference that aims to bring together everyone interested in talking about code.
     </p><p>
     As we know, choosing a career as a coder comes with its own set of life
     challenges, and we want to talk about those too. In short, this conference is a
     different kind of conference, as it connects those two pieces of the puzzle
     together in one event.
     </p><p class=\'fullArticleLink\'><a href=\'http://codeconnexx.com/\' class>&hellip; read full article</a></p></div>',
  ),
  17 => 
  array (
    'title' => 'ZendCon 2013',
    'id' => 'http://php.net/archive/2013.php#id2013-08-19-1',
    'published' => '2013-08-19T12:53:59-07:00',
    'updated' => '2013-08-31T12:53:59-07:00',
    'finalTeaserDate' => '2013-10-13',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-08-19-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-08-19-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://www.zendcon.com/',
      'title' => 'ZendCon',
      'content' => 'ZendCon2013.png',
    ),
    'content' => '<div>
      <p>
        The 9th Annual <a href="http://www.zendcon.com/">ZendCon</a> will bring together developers, IT managers and PHP
        experts from around the world. With a focus on PHP, mobile and cloud
        development, attendees at this highly acclaimed conference will expand their
        skills and explore new technologies.
      </p>

      <p>
        ZendCon provides unique opportunities to learn from a wide variety of technical
        sessions, hear keynote presentations from thought leaders, and engage with
        prominent PHP speakers and vendors. You’ll learn about the latest innovations
        and network with peers to solve PHP challenges
      </p>
      <p>
        The conference is scheduled from October 7-10, 2013. For more information,
        visit <a href="http://www.zendcon.com/">http://www.zendcon.com/</a>.
      </p>
    </div>
  ',
    'intro' => '<div><p>
        The 9th Annual <a href="http://www.zendcon.com/">ZendCon</a> will bring together developers, IT managers and PHP
        experts from around the world. With a focus on PHP, mobile and cloud
        development, attendees at this highly acclaimed conference will expand their
        skills and explore new technologies.
      </p><p>
        ZendCon provides unique opportunities to learn from a wide variety of technical
        sessions, hear keynote presentations from thought leaders, and engage with
        prominent PHP speakers and vendors. Youâll learn about the latest innovations
        and network with peers to solve PHP challenges
      </p><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-08-19-1\' class>&hellip; read full article</a></p></div>',
  ),
  18 => 
  array (
    'title' => 'PHP 5.5.2 Released!',
    'id' => 'http://php.net/archive/2013.php#id2013-08-16-1',
    'published' => '2013-08-16T11:39:27-07:00',
    'updated' => '2013-08-16T11:39:27-07:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-08-16-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-08-16-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP
     5.5.2. About 20 bugs were fixed, including security issue in OpenSSL module (CVE-2013-4248) and session fixation problem (CVE-2011-4718).
     All users of PHP are encouraged to upgrade to this release.</p>
     
     <p>For source downloads of PHP 5.5.2 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.5.2">ChangeLog</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP
     5.5.2. About 20 bugs were fixed, including security issue in OpenSSL module (CVE-2013-4248) and session fixation problem (CVE-2011-4718).
     All users of PHP are encouraged to upgrade to this release.</p><p>For source downloads of PHP 5.5.2 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.5.2">ChangeLog</a>.
     </p></div>',
  ),
  19 => 
  array (
    'title' => 'PHP 5.4.18 Released!',
    'id' => 'http://php.net/archive/2013.php#id2013-08-15-1',
    'published' => '2013-08-15T21:21:42-07:00',
    'updated' => '2013-08-15T21:21:42-07:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-08-15-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-08-15-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP
     5.4.18. About 30 bugs were fixed, including security issues CVE-2013-4113 and CVE-2013-4248.
     All users of PHP are encouraged to upgrade to this release.</p>
     
     <p>For source downloads of PHP 5.4.18 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.4.18">ChangeLog</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP
     5.4.18. About 30 bugs were fixed, including security issues CVE-2013-4113 and CVE-2013-4248.
     All users of PHP are encouraged to upgrade to this release.</p><p>For source downloads of PHP 5.4.18 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.4.18">ChangeLog</a>.
     </p></div>',
  ),
  20 => 
  array (
    'title' => 'Web & PHP Conference',
    'id' => 'http://php.net/archive/2013.php#id2013-08-08-1',
    'published' => '2013-08-08T10:37:33-07:00',
    'updated' => '2013-08-12T13:07:33-07:00',
    'finalTeaserDate' => '2013-09-18',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-08-08-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://webandphp.com/conference/webandphpcon2013',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://webandphp.com/conference/webandphpcon2013',
      'title' => 'WPC 2013',
      'content' => 'WPCLogo-2013.jpg',
    ),
    'content' => '<div>
     <p>
     <a href="http://webandphp.com/conference/webandphpcon2013">Web &amp; PHP Magazine invites you to its first ever conference.</a>
     This 3 day
     conference, taking place in San Jose, CA this September, will immerse you in a
     world of continuously evolving web technologies.
     </p>
     <p>
     Sticking with our ethos of
     open knowledge sharing and community support, all conference sessions, keynote
     presentations, hacks and Expo on September 17 &amp; 18 are FREE to attend!
     </p>
     <p>
     Whether
     your interests lay in core PHP, security, testing,architecture, frameworks,
     cloud, HTML5, CSS3, responsive design, UX, mobile web or web-based mobile apps,
     our final program of sessions, workshops and keynote presentations will have
     something for you....
     </p>
     <p>
     There will also be a pre-conference day with hands-on workshops and
     deep-dive tutorials, allowing you to work with and learn from some of
     the leading experts in their field. With this special discount code:
     <strong>WPC13PN</strong> you can access the Workshops Day for the
     special price of $159 instead of $199.
     </p>
    </div>
  ',
    'intro' => '<div><p>
     <a href="http://webandphp.com/conference/webandphpcon2013">Web &amp; PHP Magazine invites you to its first ever conference.</a>
     This 3 day
     conference, taking place in San Jose, CA this September, will immerse you in a
     world of continuously evolving web technologies.
     </p><p>
     Sticking with our ethos of
     open knowledge sharing and community support, all conference sessions, keynote
     presentations, hacks and Expo on September 17 &amp; 18 are FREE to attend!
     </p><p class=\'fullArticleLink\'><a href=\'http://webandphp.com/conference/webandphpcon2013\' class>&hellip; read full article</a></p></div>',
  ),
  21 => 
  array (
    'title' => 'International PHP Conference 2013',
    'id' => 'http://php.net/archive/2013.php#id2013-08-07-1',
    'published' => '2013-08-07T16:54:24-07:00',
    'updated' => '2013-08-07T16:54:24-07:00',
    'finalTeaserDate' => '2013-10-30',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-08-07-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://phpconference.com/2013/en',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://phpconference.com/2013/en',
      'title' => 'IPC 2013',
      'content' => 'ipc-2013.jpg',
    ),
    'content' => '<div>
     <p>Once again, the <a href="http://phpconference.com/2013/en">International PHP Conference</a>
     will explore key topics and core technologies for PHP developers, webworkers,
     IT managers and everyone interested in web technology in more than
     <a href="http://phpconference.com/2013/sessions">75 sessions,
     workshops and keynotes</a>.
     </p>
     <p>
     We\'ll show you how to scale your applications, explain
     the details of Continuous Integration or evaluate different approaches to
     NoSQL. Attendees will have the opportunity to meet with speakers, core
     developers and consultants, and there are often opportunities to evaluate your
     code. Community and enterprise projects profit from our international
     reputation and impulses given from the developer community..
     </p>
     <p>
     <a href="http://phpconference.com">http://phpconference.com</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>Once again, the <a href="http://phpconference.com/2013/en">International PHP Conference</a>
     will explore key topics and core technologies for PHP developers, webworkers,
     IT managers and everyone interested in web technology in more than
     <a href="http://phpconference.com/2013/sessions">75 sessions,
     workshops and keynotes</a>.
     </p><p>
     We\'ll show you how to scale your applications, explain
     the details of Continuous Integration or evaluate different approaches to
     NoSQL. Attendees will have the opportunity to meet with speakers, core
     developers and consultants, and there are often opportunities to evaluate your
     code. Community and enterprise projects profit from our international
     reputation and impulses given from the developer community..
     </p><p class=\'fullArticleLink\'><a href=\'http://phpconference.com/2013/en\' class>&hellip; read full article</a></p></div>',
  ),
  22 => 
  array (
    'title' => 'Ski PHP 2014',
    'id' => 'http://php.net/archive/2013.php#id2013-07-19-2',
    'published' => '2013-07-19T11:56:29-07:00',
    'updated' => '2013-07-19T11:56:29-07:00',
    'finalTeaserDate' => '2014-01-14',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'cfp',
        'label' => 'Call for Papers',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-07-19-2',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'https://www.skiphp.com/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'https://www.skiphp.com/',
      'title' => 'Ski PHP 2014',
      'content' => 'ski-php.png',
    ),
    'content' => '<div>
          <p>
              For those who like to do more than just code, we\'re pleased to
              announce Ski PHP 2014, which will be held on January 17 and 18,
              2014.  In the U.S., this is a 3-day weekend, so attendees will be
              able to enjoy the skiing, snowboarding, snowmobiling, and other
              activities that Utah has to offer after the conclusion of the
              conference.
          </p>
          <p>
              We are looking for presentations on a variety of topics, including
              frameworks, security, front-end, and data.  Interested presenters
              should submit a CFP at
              <a href="https://www.skiphp.com/speak/package">https://www.skiphp.com/speak/package</a>.
              A generous speaker package will be provided for accepted speakers.
          </p>
      </div>
  ',
    'intro' => '<div><p>
              For those who like to do more than just code, we\'re pleased to
              announce Ski PHP 2014, which will be held on January 17 and 18,
              2014.  In the U.S., this is a 3-day weekend, so attendees will be
              able to enjoy the skiing, snowboarding, snowmobiling, and other
              activities that Utah has to offer after the conclusion of the
              conference.
          </p><p>
              We are looking for presentations on a variety of topics, including
              frameworks, security, front-end, and data.  Interested presenters
              should submit a CFP at
              <a href="https://www.skiphp.com/speak/package">https://www.skiphp.com/speak/package</a>.
              A generous speaker package will be provided for accepted speakers.
          </p></div>',
  ),
  23 => 
  array (
    'title' => 'Northeast PHP Technical Conference',
    'id' => 'http://php.net/archive/2013.php#id2013-07-19-1',
    'published' => '2013-07-19T11:53:40-07:00',
    'updated' => '2013-07-19T11:53:40-07:00',
    'finalTeaserDate' => '2013-08-18',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-07-19-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://www.northeastphp.org/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://www.northeastphp.org/',
      'title' => 'Northeast PHP Technical Conference',
      'content' => 'NENA_logo_2013.png',
    ),
    'content' => '<div>
          <p>
              2nd Annual Northeast PHP Technical Conference - August 16 to 18!
          </p>
          <p>
              This year’s Northeast PHP Conference will once again be held in
              Boston, MA from August 16 to 18. This year we are adding a day to the
              front of the weekend for half-day workshops.
          </p>
          <p>We have 2 great Keynote speakers lined up as well:</p>
          <p>Eli White</p>
          <p>
              Eli is a strong advocate for PHP and used it in every project he\'s
              work on. He is currently a Founding Partner &amp; CTO of Musketeers.me,
              and the Managing Editor of php|architect magazine. He is also an avid
              writer (blogs, articles and books), and has spoken at numerous
              conferences.
          </p>
          <p>and Terry Chay</p>
          <p>
              Terry Chay is administrative overhead (Director of Features
              Engineering) at the Wikimedia Foundation, maintainers of Wikipedia.
              And when he isn’t doing that, he’s saying outrageous things on his
              blog.</p>
          <p>
              For tickets and more information:
              <a href="http://www.nephp.org/">http://www.nephp.org/</a>
          </p>
      </div>
  ',
    'intro' => '<div><p>
              2nd Annual Northeast PHP Technical Conference - August 16 to 18!
          </p><p>
              This yearâs Northeast PHP Conference will once again be held in
              Boston, MA from August 16 to 18. This year we are adding a day to the
              front of the weekend for half-day workshops.
          </p><p class=\'fullArticleLink\'><a href=\'http://www.northeastphp.org/\' class>&hellip; read full article</a></p></div>',
  ),
  24 => 
  array (
    'title' => 'PHP 5.5.1 Released',
    'id' => 'http://php.net/archive/2013.php#id2013-07-18-1',
    'published' => '2013-07-18T15:53:15+00:00',
    'updated' => '2013-07-18T15:53:15+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-07-18-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-07-18-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP 5.5.1. About 20 bugs were fixed including a security fix in the XML parser (Bug #65236).</p>
     
     <p>For source downloads of PHP 5.5.1 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.5.1">ChangeLog</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP 5.5.1. About 20 bugs were fixed including a security fix in the XML parser (Bug #65236).</p><p>For source downloads of PHP 5.5.1 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.5.1">ChangeLog</a>.
     </p></div>',
  ),
  25 => 
  array (
    'title' => 'PHP 5.3.27 Released - PHP 5.3 Reaching End of Life',
    'id' => 'http://php.net/archive/2013.php#id2013-07-11-1',
    'published' => '2013-07-11T15:10:59+00:00',
    'updated' => '2013-07-11T15:10:59+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-07-11-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-07-11-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP 5.3.27. About 10 bugs were fixed, including a security fix in the XML parser (Bug #65236).</p>
     
     <p><b>Please Note:</b> This will be the last regular release of the PHP 5.3 series. All users of PHP are encouraged to upgrade to PHP 5.4 or PHP 5.5. The PHP 5.3 series will receive only security fixes for the next year.</p>
     
     <p>For source downloads of PHP 5.3.27 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.3.27">ChangeLog</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP 5.3.27. About 10 bugs were fixed, including a security fix in the XML parser (Bug #65236).</p><p><b>Please Note:</b> This will be the last regular release of the PHP 5.3 series. All users of PHP are encouraged to upgrade to PHP 5.4 or PHP 5.5. The PHP 5.3 series will receive only security fixes for the next year.</p><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-07-11-1\' class>&hellip; read full article</a></p></div>',
  ),
  26 => 
  array (
    'title' => 'PHP 5.4.17 released!',
    'id' => 'http://php.net/archive/2013.php#id2013-07-04-1',
    'published' => '2013-07-04T20:33:50-07:00',
    'updated' => '2013-07-04T20:33:50-07:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-07-04-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-07-04-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP
     5.4.17. About 20 bugs were fixed. All users of PHP are encouraged to upgrade to this release.</p>
     
     <p>For source downloads of PHP 5.4.17 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.4.17">ChangeLog</a>.
     </p>
     
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP
     5.4.17. About 20 bugs were fixed. All users of PHP are encouraged to upgrade to this release.</p><p>For source downloads of PHP 5.4.17 please visit our <a href="http://www.php.net/downloads.php">downloads page</a>,
     Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.
     The list of changes is recorded in the <a href="http://www.php.net/ChangeLog-5.php#5.4.17">ChangeLog</a>.
     </p></div>',
  ),
  27 => 
  array (
    'title' => 'PHP 5.5.0 released.',
    'id' => 'http://php.net/archive/2013.php#id2013-06-20-1',
    'published' => '2013-06-20T16:20:26+00:00',
    'updated' => '2013-06-20T16:20:26+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-06-20-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-06-20-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team is proud to announce the immediate availability of PHP 5.5.0.
     This release includes a large number of new features and bug fixes.
     </p>
     
     <p>
        <b>The key features of PHP 5.5.0 include:</b>
        </p>
        <ul>
         <li>Added <a href="http://php.net/generators">generators</a> and coroutines.</li>
         <li>Added the <a href="http://php.net/exceptions">finally</a> keyword.</li>
         <li>Added a <a href="http://php.net/password">simplified password hashing API</a>.</li>
         <li>Added <a href="http://php.net/migration55.new-features#migration55.new-features.const-dereferencing">support for constant array/string dereferencing</a>.</li>
         <li>Added scalar class name resolution via <a href="http://php.net/oop5.basic#language.oop5.basic.class.class">::class</a>.</li>
         <li>Added <a href="http://php.net/migration55.new-features#migration55.new-features.empty">support for using empty() on the result of function calls and other expressions</a>.</li>
         <li>Added <a href="http://php.net/migration55.new-features#migration55.new-features.non-scalar-iterator-keys">support for non-scalar Iterator keys in foreach</a>.</li>
         <li>Added <a href="http://php.net/foreach#control-structures.foreach.list">support for list() constructs in foreach statements</a>.</li>
         <li>Added the <a href="http://php.net/opcache">Zend OPcache</a> extension for opcode caching.</li>
         <li>The GD library has been upgraded to version 2.1 adding new functions and improving existing functionality.</li>
         <li>A lot more improvements and fixes.</li>
        </ul>

        <p>
        <b>Changes that affect compatibility:</b>
        </p>

        <ul>
         <li><a href="http://php.net/php_logo_guid">PHP logo GUIDs</a> have been removed.</li>
         <li>Windows XP and 2003 support dropped.</li>
         <li>Case insensitivity is no longer locale specific. All case insensitive matching for function, class and constant names is now performed in a locale independent manner according to ASCII rules.</li>
        </ul>

        <p>
         For users upgrading from PHP 5.4,
         <a href="http://php.net/migration55">a migration guide is available</a>
         detailing the changes between 5.4 and 5.5.0.
        </p>

        <p>
         For a full list of changes in PHP 5.5.0, see the <a href="http://php.net/ChangeLog-5.php#5.5.0">ChangeLog</a>.
       </p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team is proud to announce the immediate availability of PHP 5.5.0.
     This release includes a large number of new features and bug fixes.
     </p><p>
        <b>The key features of PHP 5.5.0 include:</b>
        </p><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-06-20-1\' class>&hellip; read full article</a></p></div>',
  ),
  28 => 
  array (
    'title' => 'International PHP Conference',
    'id' => 'http://php.net/archive/2013.php#id2013-06-10-1',
    'published' => '2013-06-10T14:57:56-07:00',
    'updated' => '2013-06-10T14:57:56-07:00',
    'finalTeaserDate' => '2013-08-08',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'cfp',
        'label' => 'Call for Papers',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-06-10-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://phpconference.com',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://phpconference.com',
      'title' => 'IPC 2012',
      'content' => 'ipc_2013.jpg',
    ),
    'content' => '<div>
     <p>The International PHP Conference is a globally recognized event for PHP developers, webworkers, IT managers and everyone interested in web technology.</p>
     <p>We are about to start planning the next conference and if you have some projects to talk about, you can submit your sessions here: <a href="http://phpconference.com/cfp">http://phpconference.com/cfp</a></p>
    </div>
  ',
    'intro' => '<div><p>The International PHP Conference is a globally recognized event for PHP developers, webworkers, IT managers and everyone interested in web technology.</p><p>We are about to start planning the next conference and if you have some projects to talk about, you can submit your sessions here: <a href="http://phpconference.com/cfp">http://phpconference.com/cfp</a></p></div>',
  ),
  29 => 
  array (
    'title' => 'PHP 5.4.16 and PHP 5.3.26 released!',
    'id' => 'http://php.net/archive/2013.php#id2013-06-06-2',
    'published' => '2013-06-06T13:19:21-07:00',
    'updated' => '2013-06-06T13:19:21-07:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-06-06-2',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-06-06-2',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP 5.4.16 and PHP 5.3.26. These releases fix about 15 bugs, including CVE-2013-2110. All users of PHP are encouraged to upgrade to PHP 5.4.16.</p>
     
     <p>For source downloads of PHP 5.4.16 and PHP 5.3.26 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p>
     
     <p>The list of changes are recorded in the <a href="/ChangeLog-5.php">ChangeLog</a>.</p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP 5.4.16 and PHP 5.3.26. These releases fix about 15 bugs, including CVE-2013-2110. All users of PHP are encouraged to upgrade to PHP 5.4.16.</p><p>For source downloads of PHP 5.4.16 and PHP 5.3.26 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-06-06-2\' class>&hellip; read full article</a></p></div>',
  ),
  30 => 
  array (
    'title' => 'PHP 5.5 RC3 is available',
    'id' => 'http://php.net/archive/2013.php#id2013-06-06-1',
    'published' => '2013-06-06T17:01:36+00:00',
    'updated' => '2013-06-06T17:01:36+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-06-06-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-06-06-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>
     The PHP development team announces the availability of PHP 5.5 RC3.
     This release fixes some bugs against RC2.
     </p>
    <strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong>
    <p>
    You can find an incomplete changelog of PHP 5.5.0RC3 here :
    </p>
    <ul>
     <li>Fixed bug causing segfault in gc_zval_possible_root)</li>
     <li>Fixed bug about a heap based buffer overflow in quoted_printable_encode</li>
     <li>hash_pbkdf2() truncates data when using default length and hex output</li>
   </ul>
    <p>
    To get the full changelog, please, check the <a href="https://github.com/php/php-src/blob/php-5.5.0RC3/NEWS">NEWS file</a> attached to the archive.
    For source downloads of PHP 5.5.0RC3 please visit <a href="http://downloads.php.net/dsp">the download page</a>,
    Windows binaries can be found on <a href="http://windows.php.net/qa/">windows.php.net/qa/</a>.
    </p>
    <p>
     We were pleased if you could test this release candidate against your code base and report any problems that you encounter to the
     <a href="mailto:php-qa@lists.php.net">QA mailing list</a> and/or the <a href="https://bugs.php.net">PHP bug tracker</a>.
    </p>
    <p>
     Thanks you helping us making PHP better.
    </p>
    </div>
  ',
    'intro' => '<div><p>
     The PHP development team announces the availability of PHP 5.5 RC3.
     This release fixes some bugs against RC2.
     </p><strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-06-06-1\' class>&hellip; read full article</a></p></div>',
  ),
  31 => 
  array (
    'title' => 'Shanghai PHP conference 2013',
    'id' => 'http://php.net/archive/2013.php#id2013-06-04-1',
    'published' => '2013-06-04T10:56:01-07:00',
    'updated' => '2013-06-04T10:56:01-07:00',
    'finalTeaserDate' => '2013-06-30',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-06-04-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.thinkinlamp.com/2013',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://php.thinkinlamp.com/2013',
      'title' => 'Shanghai PHP conference 2013',
      'content' => 'thinklamp2013.jpg',
    ),
    'content' => '<div>
        <p><a href="http://php.thinkinlamp.com/2013">ThinkInLAMP</a> is pleased to announce the first Shanghai PHP conference 2013.
     This event will be held on Sunday June 30th 2013 in Shanghai, China. A
     community oriented conference which is organized by an excellent line up
     and socials.</p>
     <p>This event will concentrate on PHP languages and web based technologies
     used today; extension, latest dynamics and new applications within the
     increased demand for developers and everyone who is interested in PHP
     language.</p>
     <p>There will be more than 500 developers owned over 3 year’s
     experiences andsenior technical persons come for learning and networking.
     Register soon as the Early Bird discount rate expires on May 30.</p>
     <p>Go to <a href="http://php.thinkinlamp.com/2013">http://php.thinkinlamp.com/2013</a> for more information, we are looking
     forward to seeing you in June!
     </p>
    </div>
  ',
    'intro' => '<div><p><a href="http://php.thinkinlamp.com/2013">ThinkInLAMP</a> is pleased to announce the first Shanghai PHP conference 2013.
     This event will be held on Sunday June 30th 2013 in Shanghai, China. A
     community oriented conference which is organized by an excellent line up
     and socials.</p><p>This event will concentrate on PHP languages and web based technologies
     used today; extension, latest dynamics and new applications within the
     increased demand for developers and everyone who is interested in PHP
     language.</p><p class=\'fullArticleLink\'><a href=\'http://php.thinkinlamp.com/2013\' class>&hellip; read full article</a></p></div>',
  ),
  32 => 
  array (
    'title' => 'PHP 5.5.0RC2 is available',
    'id' => 'http://php.net/archive/2013.php#id2013-05-23-1',
    'published' => '2013-05-23T08:16:02+00:00',
    'updated' => '2013-05-23T08:16:02+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-05-23-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-05-23-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>
     The PHP development team announces the availability of the second release candidate of PHP 5.5.
     This release fixes some bugs against RC1 and improves overall stability.
     </p>
    <strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong>
    <p>
    You can find an incomplete changelog of PHP 5.5.0RC2 here :
    </p>
    <ul>
     <li>Fixed a bug related to segfault on memory exhaustion within function definition.</li>
     <li>Fixed bug in mbstring PHPTs which would crash on Windows x64.</li>
     <li>Fixed a bug where Custom Exceptions could crash when internal properties overridden.</li>
   </ul>
    <p>
    To get the full changelog, please, check the <a href="https://github.com/php/php-src/blob/php-5.5.0RC2/NEWS">NEWS file</a> attached to the archive.
    For source downloads of PHP 5.5.0RC2 please visit <a href="http://downloads.php.net/dsp">the download page</a>,
    Windows binaries can be found on <a href="http://windows.php.net/qa/">windows.php.net/qa/</a>.
    </p>
    <p>
     Please help us to identify bugs in order to ensure that the release is solid and all things behave as expected.
     Please test this release candidate against your code base and report any problems that you encounter to the
     <a href="mailto:php-qa@lists.php.net">QA mailing list</a> and/or the <a href="https://bugs.php.net">PHP bug tracker</a>.
    </p>
    <p>
     Thanks to all people helping on the PHP project.
    </p>
    </div>
  ',
    'intro' => '<div><p>
     The PHP development team announces the availability of the second release candidate of PHP 5.5.
     This release fixes some bugs against RC1 and improves overall stability.
     </p><strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-05-23-1\' class>&hellip; read full article</a></p></div>',
  ),
  33 => 
  array (
    'title' => 'Seriously: PHP 5.4.15 and PHP 5.3.25 really were released!',
    'id' => 'http://php.net/archive/2013.php#id2013-05-09-3',
    'published' => '2013-05-09T13:14:43-05:00',
    'updated' => '2013-05-09T13:14:43-05:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-05-09-3',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-05-09-3',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>

     <p>We weren\'t trying to pull an April Fool\'s Day joke in May.  A temporary glitch caused the latest distributions of PHP to not properly propagate to the mirror servers.  This has been fixed at the root level, and it\'s now being distributed to all of the mirrors.  We\'ll take some bacon to go with the egg on our faces, please!</p>

     <p>If you continue to experience issues with downloading these versions after 21:00 UTC on 9 May, 2013, please drop us a line at <a href="mailto:php-mirrors@lists.php.net">php-mirrors@lists.php.net</a>, telling us from which mirror you\'re trying to download, and we\'ll get it resolved.</p>

     <p>We apologize for the delays and confusion this may have caused, and thank you for using PHP.</p>

    </div>
  ',
    'intro' => '<div><p>We weren\'t trying to pull an April Fool\'s Day joke in May.  A temporary glitch caused the latest distributions of PHP to not properly propagate to the mirror servers.  This has been fixed at the root level, and it\'s now being distributed to all of the mirrors.  We\'ll take some bacon to go with the egg on our faces, please!</p><p>If you continue to experience issues with downloading these versions after 21:00 UTC on 9 May, 2013, please drop us a line at <a href="mailto:php-mirrors@lists.php.net">php-mirrors@lists.php.net</a>, telling us from which mirror you\'re trying to download, and we\'ll get it resolved.</p><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-05-09-3\' class>&hellip; read full article</a></p></div>',
  ),
  34 => 
  array (
    'title' => 'PHP 5.5.0RC1 is available',
    'id' => 'http://php.net/archive/2013.php#id2013-05-09-2',
    'published' => '2013-05-09T09:12:44+00:00',
    'updated' => '2013-05-09T09:12:44+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-05-09-2',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-05-09-2',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>
     The PHP development team announces the availability of the first release candidate of PHP 5.5.
     This release fixes some bugs as well as some possible leaks from our last beta.
     </p>
    <strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong>
    <p>
    You can find an incomplete changelog of PHP 5.5.0RC1 here :
    </p>
    <ul>
     <li>Ignore QUERY_STRING when sent in SCRIPT_FILENAME in FPM SAPI.</li>
     <li>Fix build with system libgd &gt;= 2.1 which is now the minimal
         version required (as build with previous version is broken).
         No change when bundled libgd is used.</li>
    <li> Fixed some bugs in SNMP</li>
    <li> Fixed bug where stream_select() fails with pipes returned by proc_open()
         on Windows x64).</li>
    </ul>
    <p>
    To get the full changelog, please, check the <a href="https://github.com/php/php-src/blob/php-5.5.0RC1/NEWS">NEWS file</a> attached to the archive.
    For source downloads of PHP 5.5.0RC1 please visit <a href="http://downloads.php.net/dsp">the download page</a>,
    Windows binaries can be found on <a href="http://windows.php.net/qa/">windows.php.net/qa/</a>.
    </p>
    <p>
    Note that our release candidate cycle is only meant to bug fixes, no more features will be added to PHP 5.5 from now.
    </p>     
    <p>
     Please help us to identify bugs in order to ensure that the release is solid and all things behave as expected.
     Please test this release candidate against your code base and report any problems that you encounter to the
     <a href="mailto:php-qa@lists.php.net">QA mailing list</a> and/or the <a href="https://bugs.php.net">PHP bug tracker</a>.
    </p>
    <p>
     We would like to thank all people helping us making PHP better by testing it and reporting problems, as well as all its
     contributors for their great work on this 5.5 version of PHP.
    </p>
    </div>
  ',
    'intro' => '<div><p>
     The PHP development team announces the availability of the first release candidate of PHP 5.5.
     This release fixes some bugs as well as some possible leaks from our last beta.
     </p><strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-05-09-2\' class>&hellip; read full article</a></p></div>',
  ),
  35 => 
  array (
    'title' => 'PHP 5.4.15 and PHP 5.3.25 released!',
    'id' => 'http://php.net/archive/2013.php#id2013-05-09-1',
    'published' => '2013-05-09T00:05:05-07:00',
    'updated' => '2013-05-09T00:05:05-07:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-05-09-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-05-09-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP 5.4.15 and PHP 5.3.25. These releases fix about 10 bugs aswell as upgrading the bundled libmagic library. All users of PHP are encouraged to upgrade to PHP 5.4.15.</p>
     
     <p>For source downloads of PHP 5.4.15 and PHP 5.3.25 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p>
     
     <p>The list of changes are recorded in the <a href="/ChangeLog-5.php">ChangeLog</a>.</p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP 5.4.15 and PHP 5.3.25. These releases fix about 10 bugs aswell as upgrading the bundled libmagic library. All users of PHP are encouraged to upgrade to PHP 5.4.15.</p><p>For source downloads of PHP 5.4.15 and PHP 5.3.25 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-05-09-1\' class>&hellip; read full article</a></p></div>',
  ),
  36 => 
  array (
    'title' => 'DevConf 2013',
    'id' => 'http://www.php.net/archive/2013.php#id2013-05-07-1',
    'published' => '2013-05-07T05:20:52+00:00',
    'updated' => '2013-05-07T05:20:52+00:00',
    'finalTeaserDate' => '2013-06-14',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://www.php.net/conferences/index.php#id2013-05-07-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://devconf.ru',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://devconf.ru',
      'title' => 'DevConf 2013',
      'content' => 'devconfru2012.png',
    ),
    'content' => '<div>
     <p>
      DevConf 2013 in Moscow, Russia on Jun 14
     </p>
	 <p>
      DevConf is the ultimate meeting place for russian-speaking web-developers,
      combining several language-specific conferences under one roof.
     </p>
	 <p>
      This year DevConf will include the following sections:
     </p>
     <ul>
      <li>DevConf::PHP();</li>
      <li>DevConf::Ruby();</li>
      <li>DevConf::Python();</li>
      <li>DevConf::Javascript();</li>
      <li>DevConf::Mobi();</li>
     </ul>
     <p>
      Each section will feature several talks from the active contributors/authors of the language.
	  Among the invited speakers are Dmitry Stogov (maintainer of Zend Engine and Zend OpCache and many more),
      Chiu-Ki Chan (Google), Lennart Regebro, Andrey Aksyonov (author of Sphinx), Alexey Rybak (Badoo),
      Alexander Makarov (one of the main contributors to Yii), Sergey Petrunya (of MariaDB fame),
	  and many others, see more details on <a href="http://devconf.ru">the official website</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>
      DevConf 2013 in Moscow, Russia on Jun 14
     </p><p>
      DevConf is the ultimate meeting place for russian-speaking web-developers,
      combining several language-specific conferences under one roof.
     </p><p class=\'fullArticleLink\'><a href=\'http://devconf.ru\' class>&hellip; read full article</a></p></div>',
  ),
  37 => 
  array (
    'title' => 'PHP Conference Argentina',
    'id' => 'http://php.net/archive/2013.php#id2013-05-06-1',
    'published' => '2013-05-06T18:39:48-07:00',
    'updated' => '2013-05-06T18:39:48-07:00',
    'finalTeaserDate' => '2013-10-05',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-05-06-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://www.phpconference.com.ar/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://www.phpconference.com.ar/',
      'title' => 'PHP Conference Argentina',
      'content' => 'logo-php-argentina.png',
    ),
    'content' => '<div>
     <p>
     4-5 OCTOBER 2013, Buenos Aires, ARGENTINA
     </p>
     <p>
         This year we gathered the best of the programming world. With several
         talks that cover a wide range of topics related to web development,
         <a href="http://www.phpconference.com.ar/">PHP Conference
         Argentina</a> is a conference no programmer wishes to miss
         (whether or not they use PHP.)
     </p>
    </div>
  ',
    'intro' => '<div><p>
     4-5 OCTOBER 2013, Buenos Aires, ARGENTINA
     </p><p>
         This year we gathered the best of the programming world. With several
         talks that cover a wide range of topics related to web development,
         <a href="http://www.phpconference.com.ar/">PHP Conference
         Argentina</a> is a conference no programmer wishes to miss
         (whether or not they use PHP.)
     </p></div>',
  ),
  38 => 
  array (
    'title' => 'PHP 5.5 beta 4 is now available',
    'id' => 'http://php.net/archive/2013.php#id2013-04-25-1',
    'published' => '2013-04-25T08:18:09+00:00',
    'updated' => '2013-04-25T08:18:09+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-04-25-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-04-25-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>
        The PHP development team announces the release of the 4th beta of PHP 5.5.0.
        This release fixes some bugs against beta 3 and cleans up some features.
     </p>

     <strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong>

     <p>
      PHP 5.5.0beta4 is shipped with some bug fixes. Here is the list:
     </p>
     <ul>
        <li>Fixed bug #64677, execution operator `` stealing surrounding arguments.</li>
        <li>Fixed bug #64342, ZipArchive::addFile() has to check for file existence.</li>
        <li>Fixed Windows x64 version of stream_socket_pair() and improved error handling.</li>
        <li>Remove curl stream wrappers</li>
     </ul>

     <p>You can read the full list of changes in the
      <a href="https://github.com/php/php-src/blob/php-5.5.0beta4/NEWS">NEWS file</a> contained
      in the release archive.
     </p>

     <p>
      For source downloads of PHP 5.5.0beta4 please visit
      the <a href="http://downloads.php.net/dsp">download page</a>, Windows binaries
      can be found on <a href="http://windows.php.net/qa/">windows.php.net/qa/</a>.
     </p>

     <p>
      Next step is Release Candidate. Our 1st RC is expected for May 9th.
     </p>

     <p>
        Thank you for supporting PHP.
     </p>
    </div>
  ',
    'intro' => '<div><p>
        The PHP development team announces the release of the 4th beta of PHP 5.5.0.
        This release fixes some bugs against beta 3 and cleans up some features.
     </p><strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-04-25-1\' class>&hellip; read full article</a></p></div>',
  ),
  39 => 
  array (
    'title' => 'Dutch PHP Conference 2013',
    'id' => 'http://php.net/archive/2013.php#id2013-04-23-1',
    'published' => '2013-04-23T11:56:47-07:00',
    'updated' => '2013-04-23T11:56:47-07:00',
    'finalTeaserDate' => '2013-06-08',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-04-23-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://www.phpconference.nl/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://www.phpconference.nl/',
      'title' => 'Dutch PHP Conference 2013',
      'content' => 'dpc_2013.png',
    ),
    'content' => '<div>
     <p>
     Ibuildings is proud to organise the seventh Dutch PHP Conference on June 7 and
     8, plus a pre-conference tutorial day on June 6. Both programs will be
     completely in English so the only Dutch thing about it is the location.
     </p>
     
     <p>
     This year we have 30+ speakers gathering in Amsterdam. The 3-track main
     conference covers topics like PHP 5.5, software design, APIs, Zend Framework 2,
     Symfony 2, security, scalability and more. Our Tutorial Day has an additional
     16 in-depth sessions to choose from.
     </p>
     
     <p>
     Your DPC ticket also lets you into the Dutch Mobile Conference: an additional
     two tracks about cutting edge javascript and non-native application
     development. This year features several side events: a bigger and better
     unconference, a Zend sponsored hackathon, a social in downtown Amsterdam, and a
     Symfony2 certification exam.
     </p>
     
     <p>
     The Early Bird special ends April 28th, so book right away for a 15% discount.
     We look forward to seeing you in June!
     </p>
    </div>
  ',
    'intro' => '<div><p>
     Ibuildings is proud to organise the seventh Dutch PHP Conference on June 7 and
     8, plus a pre-conference tutorial day on June 6. Both programs will be
     completely in English so the only Dutch thing about it is the location.
     </p><p>
     This year we have 30+ speakers gathering in Amsterdam. The 3-track main
     conference covers topics like PHP 5.5, software design, APIs, Zend Framework 2,
     Symfony 2, security, scalability and more. Our Tutorial Day has an additional
     16 in-depth sessions to choose from.
     </p><p class=\'fullArticleLink\'><a href=\'http://www.phpconference.nl/\' class>&hellip; read full article</a></p></div>',
  ),
  40 => 
  array (
    'title' => 'PHP South Africa 2013',
    'id' => 'http://php.net/archive/2013.php#id2013-04-12-1',
    'published' => '2013-04-12T05:59:41-07:00',
    'updated' => '2013-04-12T05:59:41-07:00',
    'finalTeaserDate' => '2013-10-05',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-04-12-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://www.phpsouthafrica.com/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://www.phpsouthafrica.com/',
      'title' => 'PHP South Africa',
      'content' => 'phpsafrica.png',
    ),
    'content' => '<div>
        <p>
            <a href="http://www.phpsouthafrica.com/">PHPSouthAfrica</a> is a 2
            day conference (October 4th &amp; 5th) to be hosted in the most
            beautiful city in the world, Cape Town South Africa.  It is aimed
            at proficient developers, new developers and people who care about
            developers.
        </p>
        <p>
            PHP is one of the most popular web programming languages used today
            to power most websites. As the language continues to grow stronger,
            PHP has now been linked with mobile powered applications. We are
            noticing a migration from mobile language applications to web based
            technologies (JavaScript, HTML5,CSS).
        </p>
        <p>
            PHPSouthAfrica has been a long time coming. With the increased
            demand for PHP programmers, not only locally but also
            internationally, our vision is to marry the latest technologies
            with international speakers. We are creating a conference that
            will hone established developers, but also assist up and coming
            programmers develop and learn new skills.With the conference
            based in Cape Town, it gives us the opportunity to showcase
            “The Mother City,” voted one of the top 10 places to visit and
            home of Table Mountain- one of the New7Wonders of Nature.
        </p>
        <p>Come and experience our great wine, food, beaches and people.</p>
        <p>We would like to welcome you.</p>
    </div>
  ',
    'intro' => '<div><p>
            <a href="http://www.phpsouthafrica.com/">PHPSouthAfrica</a> is a 2
            day conference (October 4th &amp; 5th) to be hosted in the most
            beautiful city in the world, Cape Town South Africa.  It is aimed
            at proficient developers, new developers and people who care about
            developers.
        </p><p>
            PHP is one of the most popular web programming languages used today
            to power most websites. As the language continues to grow stronger,
            PHP has now been linked with mobile powered applications. We are
            noticing a migration from mobile language applications to web based
            technologies (JavaScript, HTML5,CSS).
        </p><p class=\'fullArticleLink\'><a href=\'http://www.phpsouthafrica.com/\' class>&hellip; read full article</a></p></div>',
  ),
  41 => 
  array (
    'title' => 'PHP 5.4.14 and PHP 5.3.24 released!',
    'id' => 'http://php.net/archive/2013.php#id2013-04-11-2',
    'published' => '2013-04-11T10:16:06+00:00',
    'updated' => '2013-04-11T10:16:06+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-04-11-2',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-04-11-2',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP 5.4.14 and PHP 5.3.24. These releases fix about 10 bugs aswell as upgrading the bundled PCRE library. All users of PHP are encouraged to upgrade to PHP 5.4.14.</p>
     
     <p>For source downloads of PHP 5.4.14 and PHP 5.3.24 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p>
     
     <p>The list of changes are recorded in the <a href="/ChangeLog-5.php">ChangeLog</a>.</p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP 5.4.14 and PHP 5.3.24. These releases fix about 10 bugs aswell as upgrading the bundled PCRE library. All users of PHP are encouraged to upgrade to PHP 5.4.14.</p><p>For source downloads of PHP 5.4.14 and PHP 5.3.24 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-04-11-2\' class>&hellip; read full article</a></p></div>',
  ),
  42 => 
  array (
    'title' => 'PHP 5.5 beta3 is available',
    'id' => 'http://php.net/archive/2013.php#id2013-04-11-1',
    'published' => '2013-04-11T08:32:44+00:00',
    'updated' => '2013-04-11T08:32:44+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-04-11-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-04-11-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>
        The PHP development team announces the release of the 3rd beta of PHP 5.5.0.
        This release fixes some bugs against beta 2.
     </p>

     <strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong>

     <p>
      PHP 5.5.0beta3 is shipped with some bug fixes and improvements. Here is an incomplete list:
     </p>
     <ul>
        <li>Drop support for bison &lt; 2.4 when building PHP from GIT source.</li>
        <li>Fixed bug #54567 (DateTimeZone serialize/unserialize)</li>
        <li>Fixed bug #64555 (foreach no longer copies keys if they are interned)</li>
        <li>Fixed bug #64578 (debug_backtrace in set_error_handler corrupts zend heap)</li>
     </ul>

     <p>You can read the full list of changes in the
      <a href="https://github.com/php/php-src/blob/php-5.5.0beta3/NEWS">NEWS file</a> contained
      in the release archive.
     </p>

     <p>
      For source downloads of PHP 5.5.0beta3 please visit
      the <a href="http://downloads.php.net/dsp">download page</a>, Windows binaries
      can be found on <a href="http://windows.php.net/qa/">windows.php.net/qa/</a>.
     </p>

     <p>
      Our next beta is expected for April 25th. RC should follow.
     </p>

     <p>
        Thank you for supporting PHP.
     </p>
    </div>
  ',
    'intro' => '<div><p>
        The PHP development team announces the release of the 3rd beta of PHP 5.5.0.
        This release fixes some bugs against beta 2.
     </p><strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-04-11-1\' class>&hellip; read full article</a></p></div>',
  ),
  43 => 
  array (
    'title' => 'Northeast PHP Technical Conference',
    'id' => 'http://php.net/archive/2013.php#id2013-04-06-1',
    'published' => '2013-04-06T09:51:03-07:00',
    'updated' => '2013-04-06T09:51:03-07:00',
    'finalTeaserDate' => '2013-05-01',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'cfp',
        'label' => 'Call for Papers',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-04-06-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://www.nephp.org/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://www.nephp.org/',
      'title' => 'Northeast PHP Technical Conference',
      'content' => 'NENA_logo_2013.png',
    ),
    'content' => '<div>
     <p>2nd Annual Northeast PHP Technical Conference Announced!
     </p>
     <p>Call for Papers and Workshops.
     </p>
     <p>
     This year’s Northeast PHP Conference will once again be held in Boston, MA from August 16 to 18. The call for speakers is currently open and will close at the end of April, with speaker selection being determined by the end of May. This year we are adding a day to the front of the weekend for half-day workshops, so please feel free to make those proposals as well. For more information:
     </p>
     <p><a href="http://www.nephp.org/">http://www.nephp.org/</a></p>
    </div>
  ',
    'intro' => '<div><p>2nd Annual Northeast PHP Technical Conference Announced!
     </p><p>Call for Papers and Workshops.
     </p><p class=\'fullArticleLink\'><a href=\'http://www.nephp.org/\' class>&hellip; read full article</a></p></div>',
  ),
  44 => 
  array (
    'title' => 'PHP 5.5 beta2 released',
    'id' => 'http://php.net/archive/2013.php#id2013-03-28-1',
    'published' => '2013-03-28T08:55:45+00:00',
    'updated' => '2013-03-28T08:55:45+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-03-28-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-03-28-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>
        The PHP development team announces the release of the second beta of PHP 5.5.0.
        This release fixes some bugs from beta one that could prevent the release from compiling.
     </p>

     <strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong>

     <p>
      PHP 5.5.0beta2 is shipped with some bug fixes. Here is an incomplete list:
     </p>
     <ul>
        <li>Fixed a memoryleak when using the same variablename 2times in
        function declaration.</li>
        <li>Fixed a compilation fail with error: conflicting types for \'zendparse\'</li>
        <li>Fixed Debug backtrace changed behavior since 5.4.10 or 5.4.11</li>
     </ul>

     <p>You can read the full list of changes in the
      <a href="https://github.com/php/php-src/blob/php-5.5.0beta2/NEWS">NEWS file</a> contained
      in the release archive.
     </p>

     <p>
      For source downloads of PHP 5.5.0beta2 please visit
      the <a href="http://downloads.php.net/dsp">download page</a>, Windows binaries
      can be found on <a href="http://windows.php.net/qa/">windows.php.net/qa/</a>.
     </p>

     <p>
      Our next beta is expected for April 11th.
     </p>

     <p>
        Thank you for supporting PHP.
     </p>
     
    </div>
  ',
    'intro' => '<div><p>
        The PHP development team announces the release of the second beta of PHP 5.5.0.
        This release fixes some bugs from beta one that could prevent the release from compiling.
     </p><strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-03-28-1\' class>&hellip; read full article</a></p></div>',
  ),
  45 => 
  array (
    'title' => 'PHP 5.5.0 beta1 available',
    'id' => 'http://php.net/archive/2013.php#id2013-03-21-1',
    'published' => '2013-03-21T12:45:18+00:00',
    'updated' => '2013-03-21T12:45:18+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-03-21-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-03-21-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>
        The PHP development team announces the release of the first beta of PHP 5.5.0.
        This release is the first to include the <a href="https://wiki.php.net/rfc/optimizerplus">Zend OPCache</a>.
        Please help our efforts to provide a stable PHP version and test this version carefully
        against several different applications, with Zend OPCache enabled and report any bug in
        <a href="https://bugs.php.net">the bug tracking system</a>.
     </p>

     <strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong>

     <p>
      PHP 5.5.0beta1 is shipped with improvements. Here is an incomplete list:
     </p>
     <ul>
        <li>Added Zend Opcache extension (but disabled by ini setting),</li>
        <li>Added array_column function which returns a column in a multidimensional
            array,</li>
        <li>Added support for non-scalar Iterator keys in foreach,</li>
        <li>Added support for changing the process\'s title in CLI/CLI-Server SAPIs</li>
     </ul>

     <p>You can read the full list of changes in the
      <a href="https://github.com/php/php-src/blob/php-5.5.0beta1/NEWS">NEWS file</a> contained
      in the release archive.
     </p>

     <p>
      For source downloads of PHP 5.5.0beta1 please visit
      the <a href="http://downloads.php.net/dsp">download page</a>, Windows binaries
      can be found on <a href="http://windows.php.net/qa/">windows.php.net/qa/</a>.
     </p>

     <p>
         This beta marks the beginning of the feature freeze. No new
         features will be added to PHP 5.5 after this point.  Please,
         test and help us to roll out a stable release. Our next beta is
         planned for April 4th.
     </p>

     <p>
        Thank you for supporting PHP.
     </p>
     
    </div>
  ',
    'intro' => '<div><p>
        The PHP development team announces the release of the first beta of PHP 5.5.0.
        This release is the first to include the <a href="https://wiki.php.net/rfc/optimizerplus">Zend OPCache</a>.
        Please help our efforts to provide a stable PHP version and test this version carefully
        against several different applications, with Zend OPCache enabled and report any bug in
        <a href="https://bugs.php.net">the bug tracking system</a>.
     </p><strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-03-21-1\' class>&hellip; read full article</a></p></div>',
  ),
  46 => 
  array (
    'title' => 'PHP 5.4.13 and PHP 5.3.23 released!',
    'id' => 'http://php.net/archive/2013.php#id2013-03-14-1',
    'published' => '2013-03-14T20:38:02+00:00',
    'updated' => '2013-03-14T20:38:02+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-03-14-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-03-14-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <div>
       <div>
         <p>The PHP development team announces the immediate availability of PHP 5.4.13 and PHP 5.3.23. These releases fix about 15 bugs, including fixes for CVE-2013-1643 and CVE-2013-1635. All users of PHP are encouraged to upgrade to PHP 5.4.13.</p>
     
         <p>For source downloads of PHP 5.4.13 and PHP 5.3.23 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p>
         <p>The list of changes are recorded in the <a href="/ChangeLog-5.php">ChangeLog</a>.</p>
       </div>
     </div>
    </div>
  ',
    'intro' => '<div><div>
       <div>
         <p>The PHP development team announces the immediate availability of PHP 5.4.13 and PHP 5.3.23. These releases fix about 15 bugs, including fixes for CVE-2013-1643 and CVE-2013-1635. All users of PHP are encouraged to upgrade to PHP 5.4.13.</p>
     
         <p>For source downloads of PHP 5.4.13 and PHP 5.3.23 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p>
         <p>The list of changes are recorded in the <a href="/ChangeLog-5.php">ChangeLog</a>.</p>
       </div>
     </div></div>',
  ),
  47 => 
  array (
    'title' => 'PHP 5.5.0alpha6 released',
    'id' => 'http://php.net/archive/2013.php#id2013-03-07-1',
    'published' => '2013-03-07T13:26:26+00:00',
    'updated' => '2013-03-07T13:26:26+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-03-07-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-03-07-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>
        The PHP development team announces the release of PHP 5.5.0alpha6.
        This release fixes some bugs from alpha5. It also serves as a delay for our next release, beta1,
        integrating ZendOptimizer+ OPCode cache which is not ready yet to be merged.
        All users of PHP are encouraged to test this version carefully,
        and report any bugs in <a href="https://bugs.php.net">the bug tracking system</a>.
     </p>

     <strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong>

     <p>
      PHP 5.5.0alpha6 is shipped with improvements. Here is an incomplete list:
     </p>
     <ul>
        <li>Fixed a bug where uninitialized ++$foo-&gt;bar; does not cause a notice,</li>
        <li>Updated bundled PCRE 8.32,</li>
        <li>Fixed a bug in ext/sockets where sendmsg/recvmsg shutdown handler causes segfault</li>
     </ul>

     <p>You can read the full list of changes in the
      <a href="https://github.com/php/php-src/blob/php-5.5.0alpha6/NEWS">NEWS file</a> contained
      in the release archive.
     </p>

     <p>
      For source downloads of PHP 5.5.0alpha6 please visit
      the <a href="http://downloads.php.net/dsp">download page</a>, Windows binaries
      can be found on <a href="http://windows.php.net/qa/">windows.php.net/qa/</a>.
     </p>

     <p>
      Our first beta should show up on 21st of March.
     </p>

     <p>
        Thank you for supporting PHP.
     </p>
     
    </div>
  ',
    'intro' => '<div><p>
        The PHP development team announces the release of PHP 5.5.0alpha6.
        This release fixes some bugs from alpha5. It also serves as a delay for our next release, beta1,
        integrating ZendOptimizer+ OPCode cache which is not ready yet to be merged.
        All users of PHP are encouraged to test this version carefully,
        and report any bugs in <a href="https://bugs.php.net">the bug tracking system</a>.
     </p><strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-03-07-1\' class>&hellip; read full article</a></p></div>',
  ),
  48 => 
  array (
    'title' => 'International PHP Conference',
    'id' => 'http://php.net/archive/2013.php#id2013-02-24-1',
    'published' => '2013-02-24T15:16:20-08:00',
    'updated' => '2013-02-24T15:16:20-08:00',
    'finalTeaserDate' => '2013-06-05',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-02-24-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://www.phpconference.com/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://www.phpconference.com/',
      'title' => 'IPC2013',
      'content' => 'ipc2013.jpg',
    ),
    'content' => '<div>
        <p><a href="http://www.phpconference.com/">International PHP Conference</a> – June 2-5, 2013, Maritim proArte
     </p>
     <p><a href="http://www.phpconference.com/">The International PHP Conference</a> is a globally recognized event for PHP developers, webworkers, IT managers and everyone interested in web-technology.</p>
     <p>Again, the conference will focus on main topics for developers and core-technologies for decision makers. We will show how to scale your applications, explain the details of Continuous Integration or evaluate different approaches to NoSQL. Attendees will have the opportunity to meet with speakers, core-developers and consultants, often there is a chance for an evaluation of your code. Community as well as enterprise projects profit from our international reputation and impulses given from the developer community.</p>
    </div>
  ',
    'intro' => '<div><p><a href="http://www.phpconference.com/">International PHP Conference</a> â June 2-5, 2013, Maritim proArte
     </p><p><a href="http://www.phpconference.com/">The International PHP Conference</a> is a globally recognized event for PHP developers, webworkers, IT managers and everyone interested in web-technology.</p><p class=\'fullArticleLink\'><a href=\'http://www.phpconference.com/\' class>&hellip; read full article</a></p></div>',
  ),
  49 => 
  array (
    'title' => 'PHP 5.4.12 and PHP 5.3.22 released!',
    'id' => 'http://php.net/archive/2013.php#id2013-02-21-1',
    'published' => '2013-02-21T20:38:02+00:00',
    'updated' => '2013-02-21T20:38:02+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-02-21-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-02-21-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <div>
       <div>
         <p>The PHP development team announces the immediate availability of PHP 5.4.12 and PHP 5.3.22. These releases fix about 10 bugs. All users of PHP are encouraged to upgrade to PHP 5.4.12.</p>
     
         <p>For source downloads of PHP 5.4.12 and PHP 5.3.22 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p>
         <p>The list of changes are recorded in the <a href="/ChangeLog-5.php">ChangeLog</a>.</p>
       </div>
     </div>
    </div>
  ',
    'intro' => '<div><div>
       <div>
         <p>The PHP development team announces the immediate availability of PHP 5.4.12 and PHP 5.3.22. These releases fix about 10 bugs. All users of PHP are encouraged to upgrade to PHP 5.4.12.</p>
     
         <p>For source downloads of PHP 5.4.12 and PHP 5.3.22 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p>
         <p>The list of changes are recorded in the <a href="/ChangeLog-5.php">ChangeLog</a>.</p>
       </div>
     </div></div>',
  ),
  50 => 
  array (
    'title' => 'PHP 5.5.0alpha5 released',
    'id' => 'http://php.net/archive/2013.php#id2013-02-21-2',
    'published' => '2013-02-21T13:33:25+00:00',
    'updated' => '2013-02-21T13:33:25+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-02-21-2',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-02-21-2',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>
        The PHP development team announces the release of PHP 5.5.0alpha5.
        This release fixes some bugs from alpha4 and adds some new features.
        All users of PHP are encouraged to test this version carefully,
        and report any bugs in <a href="https://bugs.php.net">the bug tracking system</a>.
     </p>

     <strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong>

     <p>
      PHP 5.5.0alpha5 is shipped with new features and improvements. Here is an incomplete list:
     </p>
     <ul>
        <li>Added the ability to change the tmp dir PHP will use during runtime, using a new php.ini
        entry,
        </li>
        <li>Added mysqli_begin_transaction()/mysqli::begin_transaction(). Implemented all
            options, per MySQL 5.6, which can be used with START TRANSACTION, COMMIT
            and ROLLBACK through options to mysqli_commit()/mysqli_rollback() and their
            respective OO counterparts.
            These changes are reflected in the mysqlnd API as well,
        </li>
        <li>
            Added recvmsg() and sendmsg() wrappers for ext/sockets
        </li>
     </ul>

     <p>You can read the full list of changes in the
      <a href="https://github.com/php/php-src/blob/php-5.5.0alpha5/NEWS">NEWS file</a> contained
      in the release archive.
     </p>

     <p>
      For source downloads of PHP 5.5.0alpha5 please visit
      the <a href="http://downloads.php.net/dsp">download page</a>, Windows binaries
      can be found on <a href="http://windows.php.net/qa/">windows.php.net/qa/</a>.
     </p>

     <p>
      Alpha5 is the last alpha for PHP 5.5. There has been a delay in alpha releases due to late coming new features.
      We are now beginning the betas, and the first beta
      is expected for March 7th. Betas won\'t add any new features, except the first one, but consolidate the source
      code and fix found bugs.
     </p>

     <p>
        Thank you for supporting PHP.
     </p>
    </div>
  ',
    'intro' => '<div><p>
        The PHP development team announces the release of PHP 5.5.0alpha5.
        This release fixes some bugs from alpha4 and adds some new features.
        All users of PHP are encouraged to test this version carefully,
        and report any bugs in <a href="https://bugs.php.net">the bug tracking system</a>.
     </p><strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-02-21-2\' class>&hellip; read full article</a></p></div>',
  ),
  51 => 
  array (
    'title' => 'Lone Star PHP 2013',
    'id' => 'http://php.net/archive/2013.php#id2013-02-12-1',
    'published' => '2013-02-12T17:20:07-08:00',
    'updated' => '2013-02-12T17:20:07-08:00',
    'finalTeaserDate' => '2013-02-28',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'cfp',
        'label' => 'Call for Papers',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-02-12-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://lonestarphp.com/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://lonestarphp.com/',
      'title' => 'Lone Star PHP 2013',
      'content' => 'logo-lonestarphp.png',
    ),
    'content' => '<div>
        <p><a href="http://lonestarphp.com/">Lone Star PHP</a> is back again for its 3rd year in Dallas, Texas from June 28th - 29th. This 2 day event will offer 2 tracks showcasing amazing speakers from all over the PHP community.</p>
     <p>Come join more than 200 developers for 2 days of learning and networking. This year will be featuring a brand new focused 1 day track, PHP Fundamentals.
     </p>
     <p><a href="http://lonestarphp.com/call-for-papers">Call for Papers</a> are open until February 28th, 2013. Get your talk ideas in quick and join us in Dallas! Early bird registration opening soon!</p>
    </div>
  ',
    'intro' => '<div><p><a href="http://lonestarphp.com/">Lone Star PHP</a> is back again for its 3rd year in Dallas, Texas from June 28th - 29th. This 2 day event will offer 2 tracks showcasing amazing speakers from all over the PHP community.</p><p>Come join more than 200 developers for 2 days of learning and networking. This year will be featuring a brand new focused 1 day track, PHP Fundamentals.
     </p><p class=\'fullArticleLink\'><a href=\'http://lonestarphp.com/\' class>&hellip; read full article</a></p></div>',
  ),
  52 => 
  array (
    'title' => 'php[tek] 2013: Schedule Posted',
    'id' => 'http://php.net/archive/2013.php#id2013-02-07-1',
    'published' => '2013-02-07T17:45:52-08:00',
    'updated' => '2013-02-07T17:45:52-08:00',
    'finalTeaserDate' => '2013-05-17',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2013-02-07-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://tek13.phparch.com/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://tek13.phparch.com/',
      'title' => 'php[tek] 2013',
      'content' => 'tek13_badge.png',
    ),
    'content' => '<div>
     <p>The <a href="http://tek13.phparch.com/schedule">conference
     schedule</a> &amp; speaker selection for <a href="http://tek13.phparch.com/">tek13</a> have now been posted online.
      tek13 is taking place from May 14th - 17th, 2013 in it\'s traditional
     Chicago, IL location.  This year we\'ve decided to expand the conference,
     and it is now running 4 parallel tracks!  <a href="http://tek13.phparch.com/pricing-and-registration/">Register
     soon</a> as the Early Bird discount rate expires on February 28th.</p>
    </div>
  ',
    'intro' => '<div><p>The <a href="http://tek13.phparch.com/schedule">conference
     schedule</a> &amp; speaker selection for <a href="http://tek13.phparch.com/">tek13</a> have now been posted online.
      tek13 is taking place from May 14th - 17th, 2013 in it\'s traditional
     Chicago, IL location.  This year we\'ve decided to expand the conference,
     and it is now running 4 parallel tracks!  <a href="http://tek13.phparch.com/pricing-and-registration/">Register
     soon</a> as the Early Bird discount rate expires on February 28th.</p></div>',
  ),
  53 => 
  array (
    'title' => 'PHP 5.5.0alpha4 released',
    'id' => 'http://php.net/archive/2013.php#id2013-01-24-1',
    'published' => '2013-01-24T10:28:02+00:00',
    'updated' => '2013-01-24T10:28:02+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-01-24-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-01-24-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>
        The PHP development team announces the release of PHP 5.5.0alpha4.
        This release fixes some bugs from alpha3 and adds some new features.
        All users of PHP are encouraged to test this version carefully,
        and report any bugs in <a href="https://bugs.php.net">the bug tracking system</a>.
     </p>

     <strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong>

     <p>
      PHP 5.5.0alpha4 is shipped with new features and improvements such as (incomplete list):
     </p>
     <ul>
        <li>Class Name Resolution as scalar via "class" keyword,
        </li>
        <li>Added DateTimeImmutable class, a variant of DateTime that only returns the
            modified state instead of changing itself
        </li>
     </ul>

     <p>You can read the full list of changes in the
      <a href="https://github.com/php/php-src/blob/php-5.5.0alpha4/NEWS">NEWS file</a> contained
      in the release archive.
     </p>

     <p>
      For source downloads of PHP 5.5.0alpha4 please visit
      the <a href="http://downloads.php.net/dsp">download page</a>, Windows binaries
      can be found on <a href="http://windows.php.net/qa/">windows.php.net/qa/</a>.
     </p>
     
     <p>
      Alpha4 is the last alpha for PHP 5.5. We are now beginning the betas, and the first beta
      is expected for February 7th. Betas won\'t add any new features but consolidate the source
      code and fix found bugs.
     </p>

     <p>
        Thank you for supporting PHP.
     </p>
    </div>
  ',
    'intro' => '<div><p>
        The PHP development team announces the release of PHP 5.5.0alpha4.
        This release fixes some bugs from alpha3 and adds some new features.
        All users of PHP are encouraged to test this version carefully,
        and report any bugs in <a href="https://bugs.php.net">the bug tracking system</a>.
     </p><strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-01-24-1\' class>&hellip; read full article</a></p></div>',
  ),
  54 => 
  array (
    'title' => 'PHP 5.4.11 and PHP 5.3.21 released!',
    'id' => 'http://php.net/archive/2013.php#id2013-01-17-1',
    'published' => '2013-01-17T14:54:00+00:00',
    'updated' => '2013-01-17T14:54:00+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-01-17-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-01-17-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <div>
       <p>The PHP development team announces the immediate availability of PHP 5.4.11 and PHP 5.3.21. These releases fix about 10 bugs. All users of PHP are encouraged to upgrade to PHP 5.4.</p>
       <p>For source downloads of PHP 5.4.11 and PHP 5.3.21 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p>
       <p>The list of changes are recorded in the <a href="/ChangeLog-5.php">ChangeLog</a>.</p>
     </div>
    </div>
  ',
    'intro' => '<div><div>
       <p>The PHP development team announces the immediate availability of PHP 5.4.11 and PHP 5.3.21. These releases fix about 10 bugs. All users of PHP are encouraged to upgrade to PHP 5.4.</p>
       <p>For source downloads of PHP 5.4.11 and PHP 5.3.21 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p>
       <p>The list of changes are recorded in the <a href="/ChangeLog-5.php">ChangeLog</a>.</p>
     </div></div>',
  ),
  55 => 
  array (
    'title' => 'ConFoo: Last Chance to Save $145',
    'id' => 'http://www.php.net/archive/2013.php#id2013-01-11-1',
    'published' => '2013-01-11T21:31:28+00:00',
    'updated' => '2013-01-11T21:31:28+00:00',
    'finalTeaserDate' => '2013-02-25',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://www.php.net/conferences/index.php#id2013-01-11-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://confoo.ca',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://confoo.ca',
      'title' => 'ConFoo 2013',
      'content' => 'confoo-2013-php.jpg',
    ),
    'content' => '<div>
     <p>Save $145 on ConFoo tickets by purchasing before January 20th. <a href="http://confoo.ca/en/register">Register online</a> without delay. ConFoo 2013 will be held on February 27th through March 1st in Montreal, Canada and is loaded with PHP content.</p>
     
     <p>We gathered 100 speakers from around the world to talk about all aspects of web programming. The conference is preceeded by two training days. Places are very limited. Choose from 4 training topics:</p>
     
     <ul>
     	<li>Advanced PHP Training (Sebastian Bergmann, Arne Blankerts and Stefan Priebsch)</li>
     	<li>PHP Web Security: From Exploitation to Correction (Jonathan Marcil)</li>
     	<li>Practical Symfony2 (Hugo Hamon)</li>
     	<li>JavaScript Training (Laurent Villeneuve)</li>
     </ul>
    </div>
  ',
    'intro' => '<div><p>Save $145 on ConFoo tickets by purchasing before January 20th. <a href="http://confoo.ca/en/register">Register online</a> without delay. ConFoo 2013 will be held on February 27th through March 1st in Montreal, Canada and is loaded with PHP content.</p><p>We gathered 100 speakers from around the world to talk about all aspects of web programming. The conference is preceeded by two training days. Places are very limited. Choose from 4 training topics:</p><p class=\'fullArticleLink\'><a href=\'http://confoo.ca\' class>&hellip; read full article</a></p></div>',
  ),
  56 => 
  array (
    'title' => 'PHP 5.5.0 Alpha3 released',
    'id' => 'http://php.net/archive/2013.php#id2013-01-10-1',
    'published' => '2013-01-10T14:42:37+00:00',
    'updated' => '2013-01-10T14:42:37+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2013-01-10-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2013.php#id2013-01-10-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
    <p>
        The PHP development team announces the release of PHP 5.5.0alpha3.
        This release adds few features and fix some bugs from alpha2.
        All users of PHP are encouraged to test this version carefully,
        and report any bugs in <a href="https://bugs.php.net">the bug tracking system</a>.
     </p>

     <strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong>

     <p>
      PHP 5.5.0 Alpha 3 comes with new features and improvements such as (incomplete list) :
     </p>
     <ul>
        <li>Generator::throw() method,
        </li>
        <li>New cURL functions and options such as curl_escape(), curl_multi_setopt(), curl_multi_strerror(),
            curl_pause(), curl_reset()...
        </li>
        <li>Max-Age attribute support in setcookie(),
        </li>
        <li>Few bug fixes in mysqlnd and core
        </li>
     </ul>

     <p>You can read the full list of changes in the
      <a href="https://github.com/php/php-src/blob/php-5.5.0alpha3/NEWS">NEWS file</a> contained
      in the release archive.
     </p>

     <p>
      For source downloads of PHP 5.5.0 Alpha 3 please visit
      the <a href="http://downloads.php.net/dsp">download page</a>, Windows binaries
      can be found on <a href="http://windows.php.net/qa/">windows.php.net/qa/</a>.
     </p>

     <p>
        Thank you for supporting PHP.
     </p>
    </div>
  ',
    'intro' => '<div><p>
        The PHP development team announces the release of PHP 5.5.0alpha3.
        This release adds few features and fix some bugs from alpha2.
        All users of PHP are encouraged to test this version carefully,
        and report any bugs in <a href="https://bugs.php.net">the bug tracking system</a>.
     </p><strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2013.php#id2013-01-10-1\' class>&hellip; read full article</a></p></div>',
  ),
  57 => 
  array (
    'title' => 'PHP 5.5.0 Alpha2 released',
    'id' => 'http://php.net/archive/2012.php#id2012-12-21-1',
    'published' => '2012-12-21T16:19:14+00:00',
    'updated' => '2012-12-21T16:19:14+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2012-12-21-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2012.php#id2012-12-21-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
    <p>
        The PHP development team announces the immediate availability of
        PHP 5.5.0alpha2. This release adds new features and fix some bugs from alpha1.
        All users of PHP are encouraged to test this version carefully,
        and report any bugs in <a href="https://bugs.php.net">the bug tracking system</a>.
     </p>

     <strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong>

     <p>
      PHP 5.5.0 Alpha 2 comes with new features and improvements such as (incomplete list) :
     </p>
     <ul>
        <li>Support for using empty() on the result of function calls and
            other expressions,
        </li>
        <li>Systemtap support by enabling systemtap compatible dtrace probes on
            linux,
        </li>
        <li>Optimized access to temporary and compiled VM variables.
            8% less memory reads.
        </li>
     </ul>
     <p>
      Please, note that this alpha version also introduces the ext/mysql depreciation.
     </p>

     <p>You can read the full list of changes in the
      <a href="https://github.com/php/php-src/blob/php-5.5.0alpha2/NEWS">NEWS file</a> contained
      in the release archive.
     </p>

     <p>
      For source downloads of PHP 5.5.0 Alpha 2 please visit
      the <a href="http://downloads.php.net/dsp">download page</a>, Windows binaries
      can be found on <a href="http://windows.php.net/qa/">windows.php.net/qa/</a>.
     </p>

     <p>
        Thank you for helping us making PHP better.
     </p>
    </div>
  ',
    'intro' => '<div><p>
        The PHP development team announces the immediate availability of
        PHP 5.5.0alpha2. This release adds new features and fix some bugs from alpha1.
        All users of PHP are encouraged to test this version carefully,
        and report any bugs in <a href="https://bugs.php.net">the bug tracking system</a>.
     </p><strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong><p class=\'fullArticleLink\'><a href=\'http://php.net/archive/2012.php#id2012-12-21-1\' class>&hellip; read full article</a></p></div>',
  ),
  58 => 
  array (
    'title' => 'PHPBenelux Conference 2013',
    'id' => 'http://php.net/archive/2012.php#id2012-12-20-2',
    'published' => '2012-12-20T12:16:46-08:00',
    'updated' => '2012-12-20T12:16:46-08:00',
    'finalTeaserDate' => '2013-01-26',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2012-12-20-2',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://conference.phpbenelux.eu/2013/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://conference.phpbenelux.eu/2013/',
      'title' => 'PHPBenelux Conference 2013',
      'content' => 'phpbenelux_conference_logo-01-e1344277762627.png',
    ),
    'content' => '<div>
     <p>
     After a very successful 2012 edition, we are proud to announce PHPBenelux
     Conference 2013. This event will take place on Friday January 25th and
     Saturday January 26th 2013 in Antwerp, Belgium. We organize a community
     oriented conference that is built around an excellent lineup and awesome
     socials. Our schedule has been announced and tickets are available. Go to
     <a href="http://conference.phpbenelux.eu/2013/">http://conference.phpbenelux.eu/2013/</a> for more information.
     </p>
    </div>
  ',
    'intro' => '<div><p>
     After a very successful 2012 edition, we are proud to announce PHPBenelux
     Conference 2013. This event will take place on Friday January 25th and
     Saturday January 26th 2013 in Antwerp, Belgium. We organize a community
     oriented conference that is built around an excellent lineup and awesome
     socials. Our schedule has been announced and tickets are available. Go to
     <a href="http://conference.phpbenelux.eu/2013/">http://conference.phpbenelux.eu/2013/</a> for more information.
     </p></div>',
  ),
  59 => 
  array (
    'title' => 'PHP 5.4.10 and PHP 5.3.20 released!',
    'id' => 'http://php.net/archive/2012.php#id2012-12-20-1',
    'published' => '2012-12-20T11:38:49+00:00',
    'updated' => '2012-12-20T11:38:49+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/index.php#id2012-12-20-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://php.net/archive/2012.php#id2012-12-20-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <div>
       <p>The PHP development team announces the immediate availability of PHP 5.4.10 and PHP 5.3.20. These releases fix about 15 bugs. Please note that the PHP 5.3 series will enter an end of life cycle and receive only critical fixes as of March 2013. All users of PHP are encouraged to upgrade to PHP 5.4.</p>
       <p>For source downloads of PHP 5.4.10 and PHP 5.3.20 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p>
       <p>The list of changes are recorded in the <a href="/ChangeLog-5.php">ChangeLog</a>.</p>
     </div>
    </div>
  ',
    'intro' => '<div><div>
       <p>The PHP development team announces the immediate availability of PHP 5.4.10 and PHP 5.3.20. These releases fix about 15 bugs. Please note that the PHP 5.3 series will enter an end of life cycle and receive only critical fixes as of March 2013. All users of PHP are encouraged to upgrade to PHP 5.4.</p>
       <p>For source downloads of PHP 5.4.10 and PHP 5.3.20 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p>
       <p>The list of changes are recorded in the <a href="/ChangeLog-5.php">ChangeLog</a>.</p>
     </div></div>',
  ),
  60 => 
  array (
    'title' => 'php[tek] 2013 Conference',
    'id' => 'http://php.net/archive/2012.php#id2012-12-19-1',
    'published' => '2012-12-19T14:57:57-08:00',
    'updated' => '2013-01-19T14:02:30+00:00',
    'finalTeaserDate' => '2013-05-14',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://php.net/conferences/index.php#id2012-12-19-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://tek13.phparch.com/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://tek13.phparch.com/',
      'title' => 'php[tek] 2013',
      'content' => 'tek13_badge.png',
    ),
    'content' => '<div>
     <p>We are pleased to announce that <a href="http://tek13.phparch.com/">tek13</a> will be taking place this
     year again at it\'s traditional location in Chicago, IL.  This year\'s
     dates are from May 14th - 17th, 2013.  It will again be a 3-track
     conference with a focus on the community.</p>
     
     <p>The <a href="http://tek13.phparch.com/call-for-papers/">Call for
     Papers</a> has been announced and will be running until January 15th,
     2013.   Conference registration will open on January 1st.  We look
     forward to seeing many of you there this year!</p>
    </div>
  ',
    'intro' => '<div><p>We are pleased to announce that <a href="http://tek13.phparch.com/">tek13</a> will be taking place this
     year again at it\'s traditional location in Chicago, IL.  This year\'s
     dates are from May 14th - 17th, 2013.  It will again be a 3-track
     conference with a focus on the community.</p><p>The <a href="http://tek13.phparch.com/call-for-papers/">Call for
     Papers</a> has been announced and will be running until January 15th,
     2013.   Conference registration will open on January 1st.  We look
     forward to seeing many of you there this year!</p></div>',
  ),
  61 => 
  array (
    'title' => 'PHP 5.4.9 and PHP 5.3.19 released!',
    'id' => 'http://www.php.net/archive/2012.php#id2012-11-22-1',
    'published' => '2012-11-22T17:54:29+01:00',
    'updated' => '2012-11-22T17:54:29+01:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://www.php.net/index.php#id2012-11-22-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://www.php.net/archive/2012.php#id2012-11-22-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
     <p>The PHP development team announces the immediate availability of PHP 5.4.9 and PHP 5.3.19. These releases fix over 15 bugs. All users of PHP are encouraged to upgrade to PHP 5.4.9, or at least 5.3.19.</p>
     <p>For source downloads of PHP 5.4.9 and PHP 5.3.19 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p>
     <p>The list of changes are recorded in the <a href="/ChangeLog-5.php">ChangeLog</a>.</p>
    </div>
  ',
    'intro' => '<div><p>The PHP development team announces the immediate availability of PHP 5.4.9 and PHP 5.3.19. These releases fix over 15 bugs. All users of PHP are encouraged to upgrade to PHP 5.4.9, or at least 5.3.19.</p><p>For source downloads of PHP 5.4.9 and PHP 5.3.19 please visit our <a href="/downloads.php">downloads page</a>, Windows binaries can be found on <a href="http://windows.php.net/download/">windows.php.net/download/</a>.</p><p class=\'fullArticleLink\'><a href=\'http://www.php.net/archive/2012.php#id2012-11-22-1\' class>&hellip; read full article</a></p></div>',
  ),
  62 => 
  array (
    'title' => 'PHP 5.5.0 Alpha1 released',
    'id' => 'http://www.php.net/archive/2012.php#id2012-11-15-1',
    'published' => '2012-11-15T14:10:06+00:00',
    'updated' => '2012-11-15T14:10:06+00:00',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'frontpage',
        'label' => 'PHP.net frontpage news',
      ),
      1 => 
      array (
        'term' => 'releases',
        'label' => 'New PHP release',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://www.php.net/index.php#id2012-11-15-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://www.php.net/archive/2012.php#id2012-11-15-1',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'content' => '<div>
      <p>
        The PHP development team announces the immediate availability of
        PHP 5.5.0alpha1. This release marks the beginning of the PHP 5.5.0 release cycle.
        All users of PHP are encouraged to test this version carefully,
        and report any bugs in <a href="https://bugs.php.net">the bug tracking system</a>.
     </p>

     <strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong>

     <p>
      PHP 5.5.0 Alpha 1 comes with new features such as (incomplete list) :
     </p>
     <ul>
        <li>support for Generators,</li>
        <li>a new password hashing API,</li>
        <li>support for finally in try/catch blocks</li>
        <li>support for list() in foreach,</li>
        <li>constant array/string dereferencing,</li>
        <li>ext/intl improvement.</li>
     </ul>
     <p>We also dropped support for Windows XP and 2003.</p>

     <p>You can read the full list of changes in the
      <a href="https://github.com/php/php-src/blob/php-5.5.0alpha1/NEWS">NEWS file</a> contained
      in the release archive.
     </p>

     <p>
      For source downloads of PHP 5.5.0 Alpha 1 please visit
      the <a href="http://downloads.php.net/dsp">download page</a>, Windows binaries
      can be found on <a href="http://windows.php.net/qa/">windows.php.net/qa/</a>.
     </p>

     <p>
        Thank you for helping us making PHP better.
     </p>

    </div>
  ',
    'intro' => '<div><p>
        The PHP development team announces the immediate availability of
        PHP 5.5.0alpha1. This release marks the beginning of the PHP 5.5.0 release cycle.
        All users of PHP are encouraged to test this version carefully,
        and report any bugs in <a href="https://bugs.php.net">the bug tracking system</a>.
     </p><strong>THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!</strong><p class=\'fullArticleLink\'><a href=\'http://www.php.net/archive/2012.php#id2012-11-15-1\' class>&hellip; read full article</a></p></div>',
  ),
  63 => 
  array (
    'title' => 'SunshinePHP Developer Conference',
    'id' => 'http://www.php.net/archive/2012.php#id2012-11-03-1',
    'published' => '2012-11-03T13:04:07-07:00',
    'updated' => '2013-01-19T08:18:26-05:00',
    'finalTeaserDate' => '2013-02-08',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://www.php.net/conferences/index.php#id2012-11-03-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://sunshinephp.com/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://sunshinephp.com/',
      'title' => 'SunshinePHP Developer Conference',
      'content' => 'sunshine2013.png',
    ),
    'content' => '<div>
      <p>
       <a href="http://soflophp.org/">SoFloPHP</a> is excited to present the inaugural <a href="http://sunshinephp.com/">SunshinePHP Developer Conference</a> in Miami, Florida
         from February 8th - 9th, 2013.  This 2 day event will feature 3 awesome tracks, with one track
         dedicated to Symfony.  We are also planning an Uncon, as well as a hack event, and many
         opportunities to socialize with the PHP community.  Please register soon to take advantage of
         our early bird discounted rate before it ends.
      </p>
      <p>
         In February when the rest of the world is cold and snowy, it is sunny and beautiful in
         Florida. Come join us for some sun and learning.
      </p>
    </div>
  ',
    'intro' => '<div><p>
       <a href="http://soflophp.org/">SoFloPHP</a> is excited to present the inaugural <a href="http://sunshinephp.com/">SunshinePHP Developer Conference</a> in Miami, Florida
         from February 8th - 9th, 2013.  This 2 day event will feature 3 awesome tracks, with one track
         dedicated to Symfony.  We are also planning an Uncon, as well as a hack event, and many
         opportunities to socialize with the PHP community.  Please register soon to take advantage of
         our early bird discounted rate before it ends.
      </p><p>
         In February when the rest of the world is cold and snowy, it is sunny and beautiful in
         Florida. Come join us for some sun and learning.
      </p></div>',
  ),
  64 => 
  array (
    'title' => 'PHP UK Conference',
    'id' => 'http://www.php.net/archive/2012.php#id2012-11-02-1',
    'published' => '2012-11-02T09:39:14-07:00',
    'updated' => '2013-01-19T14:02:30+00:00',
    'finalTeaserDate' => '2013-02-23',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://www.php.net/conferences/index.php#id2012-11-02-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://phpconference.co.uk/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://phpconference.co.uk/',
      'title' => 'PHP UK 2013',
      'content' => 'phpuk2013.jpeg',
    ),
    'content' => '<div>
     <p>
         <a href="http://phplondon.org">PHP London</a> are pleased to announce the 8th Annual PHP UK conference;
         a 2-day event with 4 great tracks held at at The Brewery in the heart of the City of London on February 22nd- 23rd 2013.
     </p>
     <p>
         With over 600 delegates, speakers, and sponsors, PHP UK conference aims to deliver fantastic up to date content about
         PHP and related web technologies in a comfortable and professional setting. There are countless networking opportunities
         to engage with international speakers and delegates, which makes the event one you won\'t want to miss.
     </p>
     <p>
         Our call for papers is open until November the 22nd and we would love to hear from you!
     </p>
    </div>
  ',
    'intro' => '<div><p>
         <a href="http://phplondon.org">PHP London</a> are pleased to announce the 8th Annual PHP UK conference;
         a 2-day event with 4 great tracks held at at The Brewery in the heart of the City of London on February 22nd- 23rd 2013.
     </p><p>
         With over 600 delegates, speakers, and sponsors, PHP UK conference aims to deliver fantastic up to date content about
         PHP and related web technologies in a comfortable and professional setting. There are countless networking opportunities
         to engage with international speakers and delegates, which makes the event one you won\'t want to miss.
     </p><p class=\'fullArticleLink\'><a href=\'http://phpconference.co.uk/\' class>&hellip; read full article</a></p></div>',
  ),
  65 => 
  array (
    'title' => 'Web Developer Conference (WDC) 2013',
    'id' => 'http://www.php.net/archive/2012.php#id2012-10-13-1',
    'published' => '2012-10-13T16:17:20-07:00',
    'updated' => '2012-10-13T16:17:20-07:00',
    'finalTeaserDate' => '2013-06-27',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://www.php.net/conferences/index.php#id2012-10-13-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://www.web-developer-conference.de/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://www.web-developer-conference.de/',
      'title' => 'WDC2013',
      'content' => 'Logo_WDC_2013.jpg',
    ),
    'content' => '<div>
     <p>
     The Web Developer Conference (WDC) is the conference for web developers from the 24th – 27th
     June 2013 in Nuremberg (Germany). The conference is addressed to developers of web applications,
     content and online managers, agencies and webmasters. The WDC will be presented by the German
     trade magazine "web &amp; mobile developer". More information about the conference can be found on
     the website via <a href="http://www.web-developer-conference.de">www.web-developer-conference.de</a>.
     </p>
    </div>
  ',
    'intro' => '<div><p>
     The Web Developer Conference (WDC) is the conference for web developers from the 24th â 27th
     June 2013 in Nuremberg (Germany). The conference is addressed to developers of web applications,
     content and online managers, agencies and webmasters. The WDC will be presented by the German
     trade magazine "web &amp; mobile developer". More information about the conference can be found on
     the website via <a href="http://www.web-developer-conference.de">www.web-developer-conference.de</a>.
     </p></div>',
  ),
  66 => 
  array (
    'title' => 'Midwest PHP Conference',
    'id' => 'http://www.php.net/archive/2012.php#id2012-10-05-1',
    'published' => '2012-10-05T15:43:04-07:00',
    'updated' => '2012-10-05T15:43:04-07:00',
    'finalTeaserDate' => '2013-03-03',
    'category' => 
    array (
      0 => 
      array (
        'term' => 'conferences',
        'label' => 'Conference announcement',
      ),
    ),
    'link' => 
    array (
      0 => 
      array (
        'href' => 'http://www.php.net/conferences/index.php#id2012-10-05-1',
        'rel' => 'alternate',
        'type' => 'text/html',
      ),
      1 => 
      array (
        'href' => 'http://www.midwestphp.com/',
        'rel' => 'via',
        'type' => 'text/html',
      ),
    ),
    'newsImage' => 
    array (
      'xmlns' => 'http://php.net/ns/news',
      'link' => 'http://www.midwestphp.com/',
      'title' => 'Midwest PHP Conference',
      'content' => 'rsz_midwestphpconference_customlogodesign_rl3.jpg',
    ),
    'content' => '<div>
     <p>
         <a href="http://www.midwestphp.com/">MidwestPHP</a> (March 2 and 3rd, 2013 - St. Paul, MN, USA)
         is a two-day conference in the heart of Minnesota featuring 40+ sessions covering a
         wide range of topics ranging from PHP basics for newbies to advanced PHP concepts,
         frameworks, databases, third party tools and components, and web development.
     </p>
    </div>
  ',
    'intro' => '<div><p>
         <a href="http://www.midwestphp.com/">MidwestPHP</a> (March 2 and 3rd, 2013 - St. Paul, MN, USA)
         is a two-day conference in the heart of Minnesota featuring 40+ sessions covering a
         wide range of topics ranging from PHP basics for newbies to advanced PHP concepts,
         frameworks, databases, third party tools and components, and web development.
     </p></div>',
  ),
);
