<?php









/*
 * DO NOTE MODIFY THIS FILE
 * This file is automagically generated, and overwritten,
 * by the rsync box. It is only included in this repo to simplify getting
 * up and running on your localhost without needing to generate all this
 * yourself from master.
*/
 








$CONF_TEASER = array (
  'conference' => 
  array (
    'http://php.net/conferences/index.php#id2015-10-15-3' => 'PhpConference Brasil 2015',
    'http://php.net/conferences/index.php#id2015-10-15-1' => 'PHP Frameworks Day 2015',
    'http://php.net/conferences/index.php#id2015-10-07-1' => 'SunshinePHP 2016',
    'http://php.net/conferences/index.php#id2015-08-31-1' => 'International PHP Conference 2015',
    'http://php.net/conferences/index.php#id2015-06-29-1' => 'php[world] 2015 Schedule Announced',
    'http://php.net/conferences/index.php#id2015-06-23-1' => 'Madison PHP Conference 2015',
    'http://php.net/conferences/index.php#id2015-06-19-1' => 'ZendCon 2015',
    'http://php.net/conferences/index.php#id2015-06-01-1' => 'PHP Barcelona Conference 2015',
  ),
)
?>
