<?php
$OLDRELEASES = array (
  5 => 
  array (
    '5.2.4' => 
    array (
      'date' => '30 August 2007',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.4.tar.bz2',
          'name' => 'Source (tar.bz2)',
          'md5' => '55c97a671fdabf462cc7a82971a656d2',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.4.tar.gz',
          'name' => 'Source (tar.gz)',
          'md5' => '0826e231c3148b29fd039d7a8c893ad3',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.4-Win32.zip',
          'name' => 'Windows binary',
          'md5' => '979b8a305b028b296b97ed72322026b2',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.2.4-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.2.4',
          'md5' => 'dd98dfe607ceb98e727c394d5bd679fb',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_2_4.php',
      ),
      'museum' => false,
    ),
    '5.2.3' => 
    array (
      'date' => '31 May 2007',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.3.tar.bz2',
          'name' => 'Source (tar.bz2)',
          'md5' => 'eb50b751c8e1ced05bd012d5a0e4dec3',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.3.tar.gz',
          'name' => 'Source (tar.gz)',
          'md5' => 'df79b04d63fc4c1ccb6d8ea58a9cf3ac',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.3-Win32.zip',
          'name' => 'Windows binary',
          'md5' => 'ff6e5dc212823009e68f26d66d85cbac',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.2.3-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.2.3',
          'md5' => '0480ffaf5a5333e83d90d75cece54748',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_2_3.php',
      ),
      'museum' => false,
    ),
    '5.2.2' => 
    array (
      'date' => '03 May 2007',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.2.tar.bz2',
          'name' => 'Source (tar.bz2)',
          'md5' => 'd084337867d70b50a10322577be0e44e',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.2.tar.gz',
          'name' => 'Source (tar.gz)',
          'md5' => '7a920d0096900b2b962b21dc5c55fe3c',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.2-Win32.zip',
          'name' => 'Windows binary',
          'md5' => '634cf45c34f80dfb1284cabf1bbb1417',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.2.2-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.2.2',
          'md5' => '5d206368799dfbac983d83954328ae3a',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_2_2.php',
      ),
      'museum' => false,
    ),
    '5.2.1' => 
    array (
      'date' => '08 Feb 2007',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.1.tar.bz2',
          'name' => 'Source (tar.bz2)',
          'md5' => '261218e3569a777dbd87c16a15f05c8d',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.1.tar.gz',
          'name' => 'Source (tar.gz)',
          'md5' => '604eaee2b834bb037d2c83e53e300d3f',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.1-Win32.zip',
          'name' => 'Windows binary',
          'md5' => '682dd66fb03c7dd24c522f474e1b04b6',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.2.1-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.2.1',
          'md5' => 'dc8b394146faf7effa6f26df02e8e534',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_2_1.php',
      ),
      'museum' => false,
    ),
    '5.2.0' => 
    array (
      'date' => '02 Nov 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.0.tar.bz2',
          'name' => 'Source (tar.bz2)',
          'md5' => 'e6029fafcee029edcfa2ceed7a005333',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.0.tar.gz',
          'name' => 'Source (tar.gz)',
          'md5' => '52d7e8b3d8d7573e75c97340f131f988',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.0-Win32.zip',
          'name' => 'Windows binary',
          'md5' => '910734e96f41190020272d80b82ce553',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.2.0-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.2.0',
          'md5' => '638f5997884ae3ce35d2b3ec12f399b2',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_2_0.php',
      ),
      'museum' => false,
    ),
    '5.1.6' => 
    array (
      'date' => '24 Aug 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.6.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.6.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.6-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.1.6-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.1.6',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_6.php',
      ),
      'museum' => true,
    ),
    '5.1.5' => 
    array (
      'date' => '17 Aug 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.5.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.5.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.5-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.5-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.1.5-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.1.5',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_5.php',
      ),
      'museum' => true,
    ),
    '5.1.4' => 
    array (
      'date' => '04 May 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.4.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.4.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.4-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.4-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.1.4-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.1.4',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_4.php',
      ),
      'museum' => true,
    ),
    '5.1.3' => 
    array (
      'date' => '12 Jan 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.3.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.3-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.3-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.1.3-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.1.3',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_3.php',
      ),
      'museum' => true,
    ),
    '5.1.2' => 
    array (
      'date' => '12 Jan 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.2-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.2-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.1.2-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.1.2',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_2.php',
      ),
      'museum' => true,
    ),
    '5.1.1' => 
    array (
      'date' => '28 Nov 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.1-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.1.1-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.1.1',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_1.php',
      ),
      'museum' => true,
    ),
    '5.1.0' => 
    array (
      'date' => '24 Nov 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.0-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.0-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_0.php',
      ),
      'museum' => true,
    ),
    '5.0.5' => 
    array (
      'date' => '05 Sep 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.5.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.5-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.0.5-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.0.5-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.0.5',
        ),
      ),
      'museum' => true,
    ),
    '5.0.4' => 
    array (
      'date' => '31 Mar 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.4.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.4-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.0.4-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.0.4-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.0.4',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/55',
      ),
      'museum' => true,
    ),
    '5.0.3' => 
    array (
      'date' => '15 Dec 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.3.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.3-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.0.3-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.0.3-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.0.3',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/54',
      ),
      'museum' => true,
    ),
    '5.0.2' => 
    array (
      'date' => '23 Sep 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.2-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.0.2-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.0.2-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.0.2',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/53',
      ),
      'museum' => true,
    ),
    '5.0.1' => 
    array (
      'date' => '12 Aug 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.0.1-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.0.1',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/51',
      ),
      'museum' => true,
    ),
    '5.0.0' => 
    array (
      'date' => '13 July 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.0-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.0.0-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.0.0-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.0.0',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/50',
      ),
      'museum' => true,
    ),
  ),
  4 => 
  array (
    '4.4.6' => 
    array (
      'date' => '01 Mar 2007',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.6.tar.bz2',
          'name' => 'Source (tar.bz2)',
          'md5' => '5db283824310c87efb18c76b4735c4bd',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.6.tar.gz',
          'name' => 'Source (tar.gz)',
          'md5' => '07c607fcf12435f0078d72fe0de4e3c0',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.6-Win32.zip',
          'name' => 'Windows binary',
          'md5' => '486764cefb5f7bde39e95c49b2e38635',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_6.php',
      ),
      'museum' => false,
    ),
    '4.4.5' => 
    array (
      'date' => '14 Feb 2007',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.5.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.5.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.5-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_5.php',
      ),
      'museum' => true,
    ),
    '4.4.4' => 
    array (
      'date' => '17 Aug 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.4.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.4.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.4-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.4-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_4.php',
      ),
      'museum' => true,
    ),
    '4.4.3' => 
    array (
      'date' => '03 Aug 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.3.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.3.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.3-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.3-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_3.php',
      ),
      'museum' => true,
    ),
    '4.4.2' => 
    array (
      'date' => '13 Jan 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.2.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.2-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.2-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_2.php',
      ),
      'museum' => true,
    ),
    '4.4.1' => 
    array (
      'date' => '31 Oct 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.1.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.1-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_1.php',
      ),
      'museum' => true,
    ),
    '4.4.0' => 
    array (
      'date' => '11 Jul 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.0.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.0-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.0-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_0.php',
      ),
      'museum' => true,
    ),
    '4.3.11' => 
    array (
      'date' => '31 Mar 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.11.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.11.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.11-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.11-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_11.php',
        'French' => '/releases/4_3_11_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.10' => 
    array (
      'date' => '15 Dec 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.10.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.10.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.10-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.10-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_10.php',
        'French' => '/releases/4_3_10_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.9' => 
    array (
      'date' => '22 Sep 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.9.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.9.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.9-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.9-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_9.php',
        'French' => '/releases/4_3_9_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.8' => 
    array (
      'date' => '13 July 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.8.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.8-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.8-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_8.php',
      ),
      'museum' => true,
    ),
    '4.3.7' => 
    array (
      'date' => '03 June 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.7.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.7-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.7-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_7.php',
        'French' => '/releases/4_3_7_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.6' => 
    array (
      'date' => '15 April 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.6.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.6-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.6-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_6.php',
        'French' => '/releases/4_3_6_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.5' => 
    array (
      'date' => '26 March 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.5.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.5-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.5-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_5.php',
        'French' => '/releases/4_3_5_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.4' => 
    array (
      'date' => '03 November 2003',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.4.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.4-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.4-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_4.php',
        'French' => '/releases/4_3_4_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.3' => 
    array (
      'date' => '25 August 2003',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.3.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.3.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.3-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_3.php',
        'French' => '/releases/4_3_3_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.2' => 
    array (
      'date' => '29 May 2003',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.2.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.2-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.2-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_2.php',
        'French' => '/releases/4_3_2_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.1' => 
    array (
      'date' => '17 February 2003',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.1-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_1.php',
      ),
      'museum' => true,
    ),
    '4.3.0' => 
    array (
      'date' => '27 December 2002',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.0-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.0-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_0.php',
        'French' => '/releases/4_3_0_fr.php',
      ),
      'museum' => true,
    ),
    '4.2.3' => 
    array (
      'date' => '6 September 2002',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.3.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.3-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.2.3-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/37',
      ),
      'museum' => true,
    ),
    '4.2.2' => 
    array (
      'date' => '22 July 2002',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.2-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.2.2-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_2_2.php',
        'French' => '/releases/4_2_2_fr.php',
      ),
      'museum' => true,
    ),
    '4.2.1' => 
    array (
      'date' => '13 May 2002',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.2.1-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_2_1.php',
        'French' => '/releases/4_2_1_fr.php',
      ),
      'museum' => true,
    ),
    '4.2.0' => 
    array (
      'date' => '22 April 2002',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.0-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.2.0-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_2_0.php',
        'French' => '/releases/4_2_0_fr.php',
      ),
      'museum' => true,
    ),
    '4.1.2' => 
    array (
      'date' => '12 March 2002',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.1.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.1.2-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.1.2-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_1_2_win32.php',
      ),
      'museum' => true,
    ),
    '4.1.1' => 
    array (
      'date' => '26 Dec 2001',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.1.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.1.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.1.1-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_1_1.php',
      ),
      'museum' => true,
    ),
    '4.1.0' => 
    array (
      'date' => '10 Dec 2001',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.1.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.1.0-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_1_0.php',
        'French' => '/releases/4_1_0_fr.php',
      ),
      'museum' => true,
    ),
    '4.0.6' => 
    array (
      'date' => '23 June 2001',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.6.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.6-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'museum' => true,
    ),
    '4.0.5' => 
    array (
      'date' => '30 April 2001',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.5.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.5-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'museum' => true,
    ),
    '4.0.4' => 
    array (
      'date' => '19 December 2000',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.4.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.0.4pl1.tar.gz',
          'name' => '4.0.4pl1 Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.4-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.0.4-installer.zip',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'php-4.0.4pl1-Win32.zip',
          'name' => '4.0.4pl1 Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/28',
      ),
      'museum' => true,
    ),
    '4.0.3' => 
    array (
      'date' => '11 October 2000',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.3.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.0.3pl1.tar.gz',
          'name' => '4.0.3pl1 Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.3-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.0.3pl1-installer.exe',
          'name' => '4.0.3pl1 Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/26',
        'English (pl1)' => 'http://news.php.net/php.announce/27',
      ),
      'museum' => true,
    ),
    '4.0.2' => 
    array (
      'date' => '29 August 2000',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.2-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/24',
      ),
      'museum' => true,
    ),
    '4.0.1' => 
    array (
      'date' => '28 June 2000',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.0.1pl2.tar.gz',
          'name' => '4.0.1pl2 Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.0.1pl1-Win32.zip',
          'name' => '4.0.1pl1 Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/23',
      ),
      'museum' => true,
    ),
    '4.0.0' => 
    array (
      'date' => '22 May 2000',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.0-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/22',
      ),
      'museum' => true,
    ),
  ),
  3 => 
  array (
    '3.0.x (latest)' => 
    array (
      'date' => '20 Oct 2000',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-3.0.18.tar.gz',
          'name' => 'PHP 3.0.18 Source Code',
          'md5' => 'b4b8f7f1151ce66d5f3910a066651133',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-3.0.17-win32.zip',
          'name' => 'PHP 3.0.17 Windows binary',
          'md5' => '29029ac1c3c2075dce38bbd804c42f72',
        ),
      ),
      'museum' => false,
    ),
  ),
);

