<?php
$OLDRELEASES = array (
  5 => 
  array (
    '5.3.0' => 
    array (
      'announcement' => 
      array (
        'English' => '/releases/5_3_0.php',
      ),
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.3.0.tar.bz2',
          'name' => 'PHP 5.3.0 (tar.bz2)',
          'md5' => '846760cd655c98dfd86d6d97c3d964b0',
          'date' => '30 June 2009',
        ),
        1 => 
        array (
          'filename' => 'php-5.3.0.tar.gz',
          'name' => 'PHP 5.3.0 (tar.gz)',
          'md5' => 'f4905eca4497da3f0beb5c96863196b4',
          'date' => '30 June 2009',
        ),
      ),
      'date' => '30 June 2009',
      'museum' => false,
    ),
    '5.2.10' => 
    array (
      'announcement' => 
      array (
        'English' => '/releases/5_2_10.php',
      ),
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.10.tar.bz2',
          'name' => 'PHP 5.2.10 (tar.bz2)',
          'md5' => '15c7b5a87f57332d6fc683528e28247b',
          'date' => '18 June 2009',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.10.tar.gz',
          'name' => 'PHP 5.2.10 (tar.gz)',
          'md5' => '85753ba2909ac9fae5bca516adbda9e9',
          'date' => '18 June 2009',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.10-Win32.zip',
          'name' => 'PHP 5.2.10 zip package',
          'md5' => '95ae7ccfcd05b6c81c93aa2e9e792f9e',
          'date' => '18 June 2009',
          'note' => 'The PECL package will <em>not</em> be released for
this version. The 5.2.6 PECL package does however work with this release',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.10-win32-installer.msi',
          'name' => 'PHP 5.2.10 installer',
          'md5' => '38b65bc57f64c66ff73f6f4e2db2cbb4',
          'date' => '18 June 2009',
          'note' => '',
        ),
        2 => 
        array (
          'filename' => 'php-debug-pack-5.2.10-Win32.zip',
          'name' => 'PHP 5.2.10 Win32 Debug Pack',
          'md5' => 'f6bdea0e1f71ca46f78e78c86e86606',
          'date' => '18 June 2009',
        ),
        3 => 
        array (
          'filename' => 'php-5.2.10-nts-Win32.zip',
          'name' => 'PHP 5.2.10 Non-thread-safe zip package',
          'md5' => 'b1c53e6f525133647e621a9c95b09e65',
          'date' => '18 June 2009',
          'note' => 'The PECL package will <em>not</em> be released for
this version. The 5.2.6 PECL package does however work with this release',
        ),
        4 => 
        array (
          'filename' => 'php-5.2.10-nts-win32-installer.msi',
          'name' => 'PHP 5.2.10 Non-thread-safe installer',
          'md5' => 'e341deb2872d3f8f4589593da88bbede',
          'date' => '18 June 2009',
        ),
        5 => 
        array (
          'filename' => 'php-debug-pack-5.2.10-nts-Win32.zip',
          'name' => 'PHP 5.2.10 Non-thread-safe Win32 Debug Pack',
          'md5' => '760a141c861a789f928b91c655c9d58',
          'date' => '18 June 2009',
        ),
      ),
      'date' => '18 June 2009',
      'museum' => false,
    ),
    '5.2.9' => 
    array (
      'announcement' => 
      array (
        'English' => '/releases/5_2_9.php',
      ),
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.9.tar.bz2',
          'name' => 'PHP 5.2.9 (tar.bz2)',
          'md5' => '280d6cda7f72a4fc6de42fda21ac2db7',
          'date' => '26 February 2009',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.9.tar.gz',
          'name' => 'PHP 5.2.9 (tar.gz)',
          'md5' => '98b647561dc664adefe296106056cf11',
          'date' => '26 February 2009',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.9-2-Win32.zip',
          'name' => 'PHP 5.2.9-2 zip package',
          'md5' => '316b9c81bab08e6547a730315ea2abfd',
          'date' => '8 April 2009',
          'note' => 'Updated 9th of April: Added the missing oci8 DLL<br />
The PECL package will <em>not</em> be released for
this version. The 5.2.6 PECL package does however work with this release',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.9-2-win32-installer.msi',
          'name' => 'PHP 5.2.9-2 installer',
          'md5' => 'e2162faa3467aed01651df4269aa6944',
          'date' => '8 April 2009',
          'note' => 'Updated 9th of April: Added the missing oci8 DLL',
        ),
        2 => 
        array (
          'filename' => 'php-debug-pack-5.2.9-2-Win32.zip',
          'name' => 'PHP 5.2.9 Win32 Debug Pack',
          'md5' => 'b52e9a152e105c7391c832fdfe0fa06f',
          'date' => '8 April 2009',
        ),
        3 => 
        array (
          'filename' => 'php-5.2.9-2-nts-Win32.zip',
          'name' => 'PHP 5.2.9-2 Non-thread-safe zip package',
          'md5' => '8f85777941f7722fcbfe08e7de358f7d',
          'date' => '8 April 2009',
          'note' => 'Updated 9th of April: Added the missing oci8 DLL<br />
The PECL package will <em>not</em> be released for
this version. The 5.2.6 PECL package does however work with this release',
        ),
        4 => 
        array (
          'filename' => 'php-5.2.9-2-nts-win32-installer.msi',
          'name' => 'PHP 5.2.9-2 Non-thread-safe installer',
          'md5' => '4e7a1bec2b268d3d2d28cb89f629b680',
          'date' => '8 April 2009',
          'note' => 'Updated 9th of April: Added the missing oci8 DLL',
        ),
        5 => 
        array (
          'filename' => 'php-debug-pack-5.2.9-2-nts-Win32.zip',
          'name' => 'PHP 5.2.9 Non-thread-safe Win32 Debug Pack',
          'md5' => '4b7b695a257527f2896312f98dc30fd3',
          'date' => '8 April 2009',
        ),
      ),
      'date' => '26 February 2009',
      'museum' => false,
    ),
    '5.2.8' => 
    array (
      'announcement' => 
      array (
        'English' => '/releases/5_2_8.php',
      ),
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.8.tar.bz2',
          'name' => 'PHP 5.2.8 (tar.bz2)',
          'md5' => '8760a833cf10433d3e72271ab0d0eccf',
          'date' => '08 December 2008',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.8.tar.gz',
          'name' => 'PHP 5.2.8 (tar.gz)',
          'md5' => 'e748cace3cfecb66fb6de9a945f98e2a',
          'date' => '08 December 2008',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.8-Win32.zip',
          'name' => 'PHP 5.2.8 zip package',
          'md5' => '71511834881753ea0906f2bca91632b9',
          'date' => '08 December 2008',
          'note' => 'The PECL package will <em>not</em> be released for
this version. The 5.2.6 PECL package does however work with this release',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.8-win32-installer.msi',
          'name' => 'PHP 5.2.8 installer',
          'md5' => '159def484800411060a9eacccafd2253',
          'date' => '08 December 2008',
          'note' => '',
        ),
        2 => 
        array (
          'filename' => 'php-debug-pack-5.2.8-Win32.zip',
          'name' => 'PHP 5.2.8 Win32 Debug Pack',
          'md5' => 'fabc6e79c1c66dc80320165336b5ed54',
          'date' => '08 December 2008',
        ),
        3 => 
        array (
          'filename' => 'php-5.2.8-nts-Win32.zip',
          'name' => 'PHP 5.2.8 Non-thread-safe zip package',
          'md5' => '207abb02054c5ce996bc350352224acc',
          'date' => '08 December 2008',
          'note' => 'The PECL package will <em>not</em> be released for
this version. The 5.2.6 PECL package does however work with this release',
        ),
        4 => 
        array (
          'filename' => 'php-5.2.8-nts-win32-installer.msi',
          'name' => 'PHP 5.2.8 Non-thread-safe installer',
          'md5' => 'd4490964818542c416644b3d67f5b350',
          'date' => '08 December 2008',
        ),
        5 => 
        array (
          'filename' => 'php-debug-pack-5.2.8-nts-Win32.zip',
          'name' => 'PHP 5.2.8 Non-thread-safe Win32 Debug Pack',
          'md5' => '240566ce66761ab076ae9901547b7ce2',
          'date' => '08 December 2008',
        ),
      ),
      'date' => '08 December 2008',
      'museum' => false,
    ),
    '5.2.6' => 
    array (
      'announcement' => 
      array (
        'English' => '/releases/5_2_6.php',
      ),
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.6.tar.bz2',
          'name' => 'PHP 5.2.6 (tar.bz2)',
          'md5' => '7380ffecebd95c6edb317ef861229ebd',
          'date' => '01 May 2008',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.6.tar.gz',
          'name' => 'PHP 5.2.6 (tar.gz)',
          'md5' => '1720f95f26c506338f0dba3a51906bbd',
          'date' => '01 May 2008',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.6-Win32.zip',
          'name' => 'PHP 5.2.6 zip package',
          'md5' => 'c7e5010114f58282858d7d78e6509cdc',
          'date' => '3 May 2008',
          'note' => 'Update May 3rd: Added missing XSL and IMAP extension',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.6-win32-installer.msi',
          'name' => 'PHP 5.2.6 installer',
          'md5' => '94e551037e7c9c056f90179f351c0560',
          'date' => '6 May 2008',
          'note' => 'Update May 6th: Added missing XSL and IMAP extension',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.2.6-Win32.zip',
          'name' => 'PECL 5.2.6 Win32 binaries',
          'md5' => 'f0e7b245589d705eef731b51142d5def',
          'date' => '3 May 2008',
          'note' => 'Update May 3rd: Added missing XSL and IMAP extension',
        ),
        3 => 
        array (
          'filename' => 'php-debug-pack-5.2.6-Win32.zip',
          'name' => 'PHP 5.2.6 Win32 Debug Pack',
          'md5' => '24dde2726e3e0cefbb83c0c375ea1f84',
          'date' => '3 May 2008',
          'note' => 'Update May 3rd: Added missing XSL and IMAP extension',
        ),
        4 => 
        array (
          'filename' => 'php-5.2.6-nts-Win32.zip',
          'name' => 'PHP 5.2.6 Non-thread-safe zip package',
          'md5' => '1d3661a086f352ec7e318e7c2eeba4de',
          'date' => '3 May 2008',
          'note' => 'Update May 3rd: Added missing XSL and IMAP extension',
        ),
        5 => 
        array (
          'filename' => 'php-5.2.6-nts-win32-installer.msi',
          'name' => 'PHP 5.2.6 Non-thread-safe installer',
          'md5' => '96a2326b16bda488734d3956a48201b7',
          'date' => '6 May 2008',
          'note' => 'Update May 6th: Added missing XSL and IMAP extension',
        ),
        6 => 
        array (
          'filename' => 'php-debug-pack-5.2.6-nts-Win32.zip',
          'name' => 'PHP 5.2.6 Win32 Debug Pack',
          'md5' => '4c1fd96c8a78e1896d37da81467ff70d',
          'date' => '3 May 2008',
          'note' => 'Update May 3rd: Added missing XSL and IMAP extension',
        ),
        7 => 
        array (
          'filename' => 'pecl-5.2.6-nts-Win32.zip',
          'name' => 'PECL 5.2.6 Non-thread-safe Win32 binaries',
          'md5' => '62b102221920092dfefc08756aa3e926',
          'date' => '3 May 2008',
          'note' => 'Update May 3rd: Added missing XSL and IMAP extension',
        ),
      ),
      'date' => '01 May 2008',
      'museum' => true,
    ),
    '5.2.5' => 
    array (
      'date' => '08 November 2007',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.5.tar.bz2',
          'name' => 'Source (tar.bz2)',
          'md5' => '1fe14ca892460b09f06729941a1bb605',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.5.tar.gz',
          'name' => 'Source (tar.gz)',
          'md5' => '61a0e1661b70760acc77bc4841900b7a',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.5-Win32.zip',
          'name' => 'Windows binary',
          'md5' => 'a1e31c0d872ab030a2256b1cd6d3b7d1',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.2.5-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.2.5',
          'md5' => 'a3553b61c9332d08a5044cf9bf89f2df',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_2_5.php',
      ),
      'museum' => true,
    ),
    '5.2.4' => 
    array (
      'date' => '30 August 2007',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.4.tar.bz2',
          'name' => 'Source (tar.bz2)',
          'md5' => '55c97a671fdabf462cc7a82971a656d2',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.4.tar.gz',
          'name' => 'Source (tar.gz)',
          'md5' => '0826e231c3148b29fd039d7a8c893ad3',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.4-Win32.zip',
          'name' => 'Windows binary',
          'md5' => '979b8a305b028b296b97ed72322026b2',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.2.4-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.2.4',
          'md5' => 'dd98dfe607ceb98e727c394d5bd679fb',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_2_4.php',
      ),
      'museum' => true,
    ),
    '5.2.3' => 
    array (
      'date' => '31 May 2007',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.3.tar.bz2',
          'name' => 'Source (tar.bz2)',
          'md5' => 'eb50b751c8e1ced05bd012d5a0e4dec3',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.3.tar.gz',
          'name' => 'Source (tar.gz)',
          'md5' => 'df79b04d63fc4c1ccb6d8ea58a9cf3ac',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.3-Win32.zip',
          'name' => 'Windows binary',
          'md5' => 'ff6e5dc212823009e68f26d66d85cbac',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.2.3-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.2.3',
          'md5' => '0480ffaf5a5333e83d90d75cece54748',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_2_3.php',
      ),
      'museum' => true,
    ),
    '5.2.2' => 
    array (
      'date' => '03 May 2007',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.2.tar.bz2',
          'name' => 'Source (tar.bz2)',
          'md5' => 'd084337867d70b50a10322577be0e44e',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.2.tar.gz',
          'name' => 'Source (tar.gz)',
          'md5' => '7a920d0096900b2b962b21dc5c55fe3c',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.2-Win32.zip',
          'name' => 'Windows binary',
          'md5' => '634cf45c34f80dfb1284cabf1bbb1417',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.2.2-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.2.2',
          'md5' => '5d206368799dfbac983d83954328ae3a',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_2_2.php',
      ),
      'museum' => true,
    ),
    '5.2.1' => 
    array (
      'date' => '08 Feb 2007',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.1.tar.bz2',
          'name' => 'Source (tar.bz2)',
          'md5' => '261218e3569a777dbd87c16a15f05c8d',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.1.tar.gz',
          'name' => 'Source (tar.gz)',
          'md5' => '604eaee2b834bb037d2c83e53e300d3f',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.1-Win32.zip',
          'name' => 'Windows binary',
          'md5' => '682dd66fb03c7dd24c522f474e1b04b6',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.2.1-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.2.1',
          'md5' => 'dc8b394146faf7effa6f26df02e8e534',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_2_1.php',
      ),
      'museum' => true,
    ),
    '5.2.0' => 
    array (
      'date' => '02 Nov 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.0.tar.bz2',
          'name' => 'Source (tar.bz2)',
          'md5' => 'e6029fafcee029edcfa2ceed7a005333',
        ),
        1 => 
        array (
          'filename' => 'php-5.2.0.tar.gz',
          'name' => 'Source (tar.gz)',
          'md5' => '52d7e8b3d8d7573e75c97340f131f988',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.2.0-Win32.zip',
          'name' => 'Windows binary',
          'md5' => '910734e96f41190020272d80b82ce553',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.2.0-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.2.0',
          'md5' => '638f5997884ae3ce35d2b3ec12f399b2',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_2_0.php',
      ),
      'museum' => true,
    ),
    '5.1.6' => 
    array (
      'date' => '24 Aug 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.6.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.6.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.6-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.1.6-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.1.6',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_6.php',
      ),
      'museum' => true,
    ),
    '5.1.5' => 
    array (
      'date' => '17 Aug 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.5.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.5.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.5-installer.exe',
          'name' => 'Windows installer',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.1.5-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.1.5',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_5.php',
      ),
      'museum' => true,
    ),
    '5.1.4' => 
    array (
      'date' => '04 May 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.4.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.4.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.4-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.4-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.1.4-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.1.4',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_4.php',
      ),
      'museum' => true,
    ),
    '5.1.3' => 
    array (
      'date' => '02 May 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.3.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.3-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.3-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.1.3-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.1.3',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_3.php',
      ),
      'museum' => true,
    ),
    '5.1.2' => 
    array (
      'date' => '12 Jan 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.2-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.2-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.1.2-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.1.2',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_2.php',
      ),
      'museum' => true,
    ),
    '5.1.1' => 
    array (
      'date' => '28 Nov 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.1-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.1.1-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.1.1',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_1.php',
      ),
      'museum' => true,
    ),
    '5.1.0' => 
    array (
      'date' => '24 Nov 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.1.0-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.1.0-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/5_1_0.php',
      ),
      'museum' => true,
    ),
    '5.0.5' => 
    array (
      'date' => '05 Sep 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.5.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.5-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.0.5-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.0.5-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.0.5',
        ),
      ),
      'museum' => true,
    ),
    '5.0.4' => 
    array (
      'date' => '31 Mar 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.4.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.4-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.0.4-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.0.4-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.0.4',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/55',
      ),
      'museum' => true,
    ),
    '5.0.3' => 
    array (
      'date' => '15 Dec 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.3.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.3-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.0.3-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.0.3-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.0.3',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/54',
      ),
      'museum' => true,
    ),
    '5.0.2' => 
    array (
      'date' => '23 Sep 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.2-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.0.2-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.0.2-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.0.2',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/53',
      ),
      'museum' => true,
    ),
    '5.0.1' => 
    array (
      'date' => '12 Aug 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'pecl-5.0.1-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.0.1',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/51',
      ),
      'museum' => true,
    ),
    '5.0.0' => 
    array (
      'date' => '13 July 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-5.0.0-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-5.0.0-installer.exe',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'pecl-5.0.0-Win32.zip',
          'name' => 'Collection of PECL modules for PHP 5.0.0',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/50',
      ),
      'museum' => true,
    ),
  ),
  4 => 
  array (
    '4.4.9' => 
    array (
      'announcement' => 
      array (
        'English' => '/releases/4_4_9.php',
      ),
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.9.tar.bz2',
          'name' => 'PHP 4.4.9 (tar.bz2)',
          'md5' => '2e3b2a0e27f10cb84fd00e5ecd7a1880',
          'date' => '07 August 2008',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.9.tar.gz',
          'name' => 'PHP 4.4.9 (tar.gz)',
          'md5' => '9bcc1aba50be0dfeeea551d018375548',
          'date' => '07 August 2008',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.9-Win32.zip',
          'name' => 'PHP 4.4.9 zip package',
          'md5' => '7395068d5489a9f8abf50c6e4b48622f',
          'date' => '07 August 2008',
        ),
      ),
      'date' => '07 August 2008',
      'museum' => false,
    ),
    '4.4.8' => 
    array (
      'announcement' => 
      array (
        'English' => '/releases/4_4_8.php',
      ),
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.8.tar.bz2',
          'name' => 'PHP 4.4.8 (tar.bz2)',
          'md5' => 'ed31e77414e0331e787487b53732dbca',
          'date' => '03 January 2008',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.8.tar.gz',
          'name' => 'PHP 4.4.8 (tar.gz)',
          'md5' => '8ad5d1ca793d55b24cd82e591248c04e',
          'date' => '03 January 2008',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.8-Win32.zip',
          'name' => 'PHP 4.4.8 zip package',
          'md5' => '09ffff4b1a54bbadb8fee6acd85a2c1f',
          'date' => '12 Feb 2008',
        ),
      ),
      'date' => '03 January 2008',
      'museum' => false,
    ),
    '4.4.7' => 
    array (
      'announcement' => 
      array (
        'English' => '/releases/4_4_7.php',
      ),
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.7.tar.bz2',
          'name' => 'PHP 4.4.7 (tar.bz2)',
          'md5' => '3f21b44d37a57ca3876d3aea713c700d',
          'date' => '03 May 2007',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.7.tar.gz',
          'name' => 'PHP 4.4.7 (tar.gz)',
          'md5' => '2669d2049822ac14abb263703d24f643',
          'date' => '03 May 2007',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.7-Win32.zip',
          'name' => 'PHP 4.4.7 zip package',
          'md5' => '065e867fa3cfa75cba8271dde9b10cee',
          'date' => '04 May 2007',
          'note' => 'This package was updated due to faulty Apache2 module shipped with the orginal.<br /> (CGI binary plus server API versions for Apache, Apache2 (experimental), ISAPI, NSAPI, Servlet and Pi3Web. MySQL support built-in, many extensions included, packaged as zip)<br />',
        ),
      ),
      'date' => '03 May 2007',
      'museum' => false,
    ),
    '4.4.6' => 
    array (
      'date' => '01 Mar 2007',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.6.tar.bz2',
          'name' => 'Source (tar.bz2)',
          'md5' => '5db283824310c87efb18c76b4735c4bd',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.6.tar.gz',
          'name' => 'Source (tar.gz)',
          'md5' => '07c607fcf12435f0078d72fe0de4e3c0',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.6-Win32.zip',
          'name' => 'Windows binary',
          'md5' => '486764cefb5f7bde39e95c49b2e38635',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_6.php',
      ),
      'museum' => true,
    ),
    '4.4.5' => 
    array (
      'date' => '14 Feb 2007',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.5.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.5.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.5-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_5.php',
      ),
      'museum' => true,
    ),
    '4.4.4' => 
    array (
      'date' => '17 Aug 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.4.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.4.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.4-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.4-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_4.php',
      ),
      'museum' => true,
    ),
    '4.4.3' => 
    array (
      'date' => '03 Aug 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.3.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.3.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.3-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.3-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_3.php',
      ),
      'museum' => true,
    ),
    '4.4.2' => 
    array (
      'date' => '13 Jan 2006',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.2.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.2-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.2-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_2.php',
      ),
      'museum' => true,
    ),
    '4.4.1' => 
    array (
      'date' => '31 Oct 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.1.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.1-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_1.php',
      ),
      'museum' => true,
    ),
    '4.4.0' => 
    array (
      'date' => '11 Jul 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.0.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.4.0-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.4.0-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_4_0.php',
      ),
      'museum' => true,
    ),
    '4.3.11' => 
    array (
      'date' => '31 Mar 2005',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.11.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.11.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.11-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.11-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_11.php',
        'French' => '/releases/4_3_11_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.10' => 
    array (
      'date' => '15 Dec 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.10.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.10.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.10-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.10-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_10.php',
        'French' => '/releases/4_3_10_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.9' => 
    array (
      'date' => '22 Sep 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.9.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.9.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.9-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.9-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_9.php',
        'French' => '/releases/4_3_9_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.8' => 
    array (
      'date' => '13 July 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.8.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.8-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.8-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_8.php',
      ),
      'museum' => true,
    ),
    '4.3.7' => 
    array (
      'date' => '03 June 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.7.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.7-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.7-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_7.php',
        'French' => '/releases/4_3_7_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.6' => 
    array (
      'date' => '15 April 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.6.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.6-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.6-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_6.php',
        'French' => '/releases/4_3_6_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.5' => 
    array (
      'date' => '26 March 2004',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.5.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.5-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.5-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_5.php',
        'French' => '/releases/4_3_5_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.4' => 
    array (
      'date' => '03 November 2003',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.4.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.4-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.4-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_4.php',
        'French' => '/releases/4_3_4_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.3' => 
    array (
      'date' => '25 August 2003',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.3.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.3.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.3-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_3.php',
        'French' => '/releases/4_3_3_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.2' => 
    array (
      'date' => '29 May 2003',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.2.tar.bz2',
          'name' => 'Source (tar.bz2)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.2-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.2-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_2.php',
        'French' => '/releases/4_3_2_fr.php',
      ),
      'museum' => true,
    ),
    '4.3.1' => 
    array (
      'date' => '17 February 2003',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.1-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_1.php',
      ),
      'museum' => true,
    ),
    '4.3.0' => 
    array (
      'date' => '27 December 2002',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.3.0-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.3.0-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_3_0.php',
        'French' => '/releases/4_3_0_fr.php',
      ),
      'museum' => true,
    ),
    '4.2.3' => 
    array (
      'date' => '6 September 2002',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.3.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.3-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.2.3-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/37',
      ),
      'museum' => true,
    ),
    '4.2.2' => 
    array (
      'date' => '22 July 2002',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.2-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.2.2-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_2_2.php',
        'French' => '/releases/4_2_2_fr.php',
      ),
      'museum' => true,
    ),
    '4.2.1' => 
    array (
      'date' => '13 May 2002',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.2.1-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_2_1.php',
        'French' => '/releases/4_2_1_fr.php',
      ),
      'museum' => true,
    ),
    '4.2.0' => 
    array (
      'date' => '22 April 2002',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.2.0-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.2.0-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_2_0.php',
        'French' => '/releases/4_2_0_fr.php',
      ),
      'museum' => true,
    ),
    '4.1.2' => 
    array (
      'date' => '12 March 2002',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.1.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.1.2-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.1.2-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_1_2_win32.php',
      ),
      'museum' => true,
    ),
    '4.1.1' => 
    array (
      'date' => '26 Dec 2001',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.1.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.1.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.1.1-installer.exe',
          'name' => 'Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_1_1.php',
      ),
      'museum' => true,
    ),
    '4.1.0' => 
    array (
      'date' => '10 Dec 2001',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.1.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.1.0-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => '/releases/4_1_0.php',
        'French' => '/releases/4_1_0_fr.php',
      ),
      'museum' => true,
    ),
    '4.0.6' => 
    array (
      'date' => '23 June 2001',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.6.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.6-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'museum' => true,
    ),
    '4.0.5' => 
    array (
      'date' => '30 April 2001',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.5.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.5-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'museum' => true,
    ),
    '4.0.4' => 
    array (
      'date' => '19 December 2000',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.4.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.0.4pl1.tar.gz',
          'name' => '4.0.4pl1 Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.4-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.0.4-installer.zip',
          'name' => 'Windows installer',
        ),
        2 => 
        array (
          'filename' => 'php-4.0.4pl1-Win32.zip',
          'name' => '4.0.4pl1 Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/28',
      ),
      'museum' => true,
    ),
    '4.0.3' => 
    array (
      'date' => '11 October 2000',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.3.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.0.3pl1.tar.gz',
          'name' => '4.0.3pl1 Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.3-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.0.3pl1-installer.exe',
          'name' => '4.0.3pl1 Windows installer',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/26',
        'English (pl1)' => 'http://news.php.net/php.announce/27',
      ),
      'museum' => true,
    ),
    '4.0.2' => 
    array (
      'date' => '29 August 2000',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.2.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.2-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/24',
      ),
      'museum' => true,
    ),
    '4.0.1' => 
    array (
      'date' => '28 June 2000',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.1.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
        1 => 
        array (
          'filename' => 'php-4.0.1pl2.tar.gz',
          'name' => '4.0.1pl2 Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.1-Win32.zip',
          'name' => 'Windows binary',
        ),
        1 => 
        array (
          'filename' => 'php-4.0.1pl1-Win32.zip',
          'name' => '4.0.1pl1 Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/23',
      ),
      'museum' => true,
    ),
    '4.0.0' => 
    array (
      'date' => '22 May 2000',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.0.tar.gz',
          'name' => 'Source (tar.gz)',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-4.0.0-Win32.zip',
          'name' => 'Windows binary',
        ),
      ),
      'announcement' => 
      array (
        'English' => 'http://news.php.net/php.announce/22',
      ),
      'museum' => true,
    ),
  ),
  3 => 
  array (
    '3.0.x (latest)' => 
    array (
      'date' => '20 Oct 2000',
      'source' => 
      array (
        0 => 
        array (
          'filename' => 'php-3.0.18.tar.gz',
          'name' => 'PHP 3.0.18 Source Code',
          'md5' => 'b4b8f7f1151ce66d5f3910a066651133',
        ),
      ),
      'windows' => 
      array (
        0 => 
        array (
          'filename' => 'php-3.0.17-win32.zip',
          'name' => 'PHP 3.0.17 Windows binary',
          'md5' => '29029ac1c3c2075dce38bbd804c42f72',
        ),
      ),
      'museum' => true,
    ),
  ),
);
