<!-- UserVoice JavaScript SDK (only needed once on a page) -->
<script>(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/zDo1PI3X0lzE9SaQxC3LQ.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})()</script>

<!-- A tab to launch the Classic Widget -->
<script>
UserVoice = window.UserVoice || [];
UserVoice.push(['showTab', 'classic_widget', {
  mode: 'feedback',
  primary_color: '#9999cc',
  link_color: '#3f438d',
  forum_id: 211823,
  feedback_tab_name: 'Give feedback',
  tab_label: 'Feedback & Ideas',
  tab_color: '#666699',
  tab_position: 'middle-right',
  tab_inverted: false
}]);
</script>